### ISSUE TITLE
Glgrep opens quickfix window instead of location list 

### ISSUE THREAD

**Issue by CGamesPlay** [tpope/vim-fugitive#1001]
When I run `Glgrep! foo`, the results are placed into the location list and can be viewed with `:lw`. However, the quickfix window is automatically opened by default (`:cw`), instead of the location list window (`:lw`).

Using 3e0bd86b99c50691.

**Comment by tpope** [comment]
Neither `:Ggrep` not `:Glgrep` opens the quickfix window. That's something in your config.

**Comment by CGamesPlay** [comment]
Thanks for highlighting my stupidity :)

For documentation, this was the behavior I was targeting:

```
augroup grep " {{{
  au!
  " Automatically open the location list after performing an lgrep.
  autocmd QuickFixCmdPost lgrep botright lwindow
augroup END " }}}
```
