### ISSUE TITLE
Gpush showing (tmux/?) instead of pushing

### ISSUE THREAD

**Issue by sunnypp** [tpope/vim-fugitive#1005]
When I do `:Gpush`, the screen was redrawn and `(tmux/?`) is shown as a message in my (neo)vim.

Sorry for raising this -- guessing this should be asked before but I cannot find any related post by searching.

## Details
1. Using tmux, neovim
2. `:copen` after `:Gpush` shows `:Dispatch git push (tmux/?)` with nothing inside QF window
3. `:!git push` works
4. Same result no matter I have a commit to push or not

Thanks in advance.

**Comment by tpope** [comment]
That means dispatch.vim ran into an issue with tmux. The `?` would be a PID if it was successful. Try `:Dispatch git push` and `:Dispatch ls` to if it's a Git specific issue or not.

**Comment by sunnypp** [comment]
## When there's nothing to push
`:Gpush` behaves as raised above `(tmux/?)`.
`:Dispatch git push` would show `|| Everything up-to-date` with `Success: !git push (sync/?)` as a message.
`:Dispatch ls` also succeeds (populates the qf list with filenames)

## When there's something to push
`:Gpush` behaves as above..
`:Dispatch git push` would show `|| To ....git || xxxxxxx..xxxxxxx master -> master` in QF window and the message is the same as above.
(and as expected `:Dispatch ls` has no changes)

# "Cause" found
I am using iTerm and I "send text at start" which is `tmux ls && read tmux_session && tmux attach -t ${tmux_session:-default} || tmux new -s ${tmux_session:-default}`.

If I `tmux kill-server` and then start tmux with `tmux` it works fine...
