### ISSUE TITLE
[doc] Gdiff does support diff with renamed files

### ISSUE THREAD

**Issue by talineo** [tpope/vim-fugitive#1007]
It may be interesting to document the fact that :Gdiff revision:old_name does work !

**Comment by talineo** [comment]
my bad, after checking this is normal revision syntax in git, nothing specific to git diff.

**Comment by davidmaxwaterman** [comment]
Care to add what that 'normal revision syntax' is in this case?

**Comment by tpope** [comment]
Everything in `man git-rev-parse`.
