### ISSUE TITLE
Strip out carriage returns

### ISSUE THREAD

**Issue by teoljungberg** [tpope/vim-fugitive#1008]
GitHub's new-ish [squash-and-merge button] seems to add carriage returns, that are visible in i.e `:Gedit`.

Example:

<img width="804" alt="screenshot 2018-04-04 14 52 42" src="https://user-images.githubusercontent.com/810650/38308571-d8a669d8-3817-11e8-99ed-9731d3da8d87.png">

Would it be possible to strip these out, or hide them somehow? Or is this a customization issue, where something in my local configuration mucks it up?

[squash-and-merge button]: https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits

**Comment by tpope** [comment]
I've seen this from Windows users. Some GitHub workflow doing the same thing wouldn't surprise me. It would be nice to get rid of them!

**Comment by tpope** [comment]
I take it back, the most recent incident was actually a Windows user ... getting squashed and merged by me.

**Comment by teoljungberg** [comment]
I’m on macOS, so I agree that the issue lies within GitHub. So there’s probably nothing we can do there.

Would it be possible to strip them out? Or use a `fileformat` that silences them?

**Comment by tpope** [comment]
`'fileformat'` is worthless for mixed files. Please do investigate stripping them out.

**Comment by teoljungberg** [comment]
Gladly, any pointers on where to start looking inside fugitive?

**Comment by teoljungberg** [comment]
@tpope The carriage returns have made their way back into fugitive.

Looking at https://github.com/tpope/vim-fugitive/blob/a9100fafb8c6deb187ee1cfaa37a4a02018d6c9a/autoload/fugitive.vim#L1503 it should still strip them out. Has there been any other refactorings like changing the filetypes that caused this?

**Comment by teoljungberg** [comment]
If I remove `(exists(':keeppatterns') ? 'keeppatterns' : '')` from the command, it executes as expectedly removing the carriage returns.

What could be the culprit?

**Comment by tpope** [comment]
Oh that is weird, I'm not sure. What if you flip it around so `keepjumps` comes first?

**Comment by teoljungberg** [comment]
Sadly nothing, the issue still stands.

**Comment by tpope** [comment]
What Vim version? Having trouble imagining any other explanation than a Vim bug.

**Comment by teoljungberg** [comment]
I've tested this on both the version that ships with macOS and one built from source.

- 8.0.1283
- 8.1.473

**Comment by tpope** [comment]
Can you point me at a commit for testing?

**Comment by teoljungberg** [comment]
Here's an example commit:

https://github.com/tpope/vim-fugitive/commit/4f24757df2a57fc01900334114b1790fcb75ad54

<img width="718" alt="screenshot 2018-10-28 at 10 09 35" src="https://user-images.githubusercontent.com/810650/47614042-946fb380-da99-11e8-8522-1420a549f9fc.png">

**Comment by teoljungberg** [comment]
Works wonders! Thank you.
