### ISSUE TITLE
Please don't depend on netrw for `:Gbrowse`

### ISSUE THREAD

**Issue by doronbehar** [tpope/vim-fugitive#1010]
In relation to most of [these issues](https://github.com/tpope/vim-fugitive/issues?utf8=%E2%9C%93&q=netrw), it could be great if the plugin wouldn't depend on netrw as a must dependency. I disable `netrw` completely with these in my `.vimrc`:
```
let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1
```
And I can't use `:Gbrowse` unless I comment these. Would be great if this could be handled.

Thanks.

**Comment by tpope** [comment]
Disable the plugin file, sure, but does loading the autoload file hurt anything?
