### ISSUE TITLE
Please make `:Gcommit -v` the same as `commit -v`

### ISSUE THREAD

**Issue by chrisbra** [tpope/vim-fugitive#1011]
Okay, don't know why `:Gcommit -v` would open a new tab. I would expect that `:tab :Gcommit` would open a new tab and `:Gcommit -v` would essentially just use `git commit -v` (e.g. I see a diff of what is going to be commited). Can you please consider changing that behaviour or make it at least configurable?

**Comment by tpope** [comment]
#513, which happened before `<mods>` made `:tab Gcommit` possible. Add support for that and we could ditch the `-v` special casing (though I have grown fond of it).

**Comment by chrisbra** [comment]
Ah I see. Anyway, I understand this would be a possible backwards incompatible change. How about special casing `-V` to `-v` but without opening in a new tab?
I could submit a PR, but considering that my other PRs are still all hanging around without any feedback I am not too fond of it.

**Comment by tpope** [comment]
I don't want to invent a new argument, but you can definitely have the spelled out `--verbose`.

As for backwards compatibility, I don't think an interactive change like this is a huge deal, but you're right, I don't want to shatter it on a whim. For now, I'll just add `:tab` support, and exclude `--verbose`, as an incremental step.
