### ISSUE TITLE
How to stage the current file without side-effects?

### ISSUE THREAD

**Issue by tankorsmash** [tpope/vim-fugitive#1013]
I'd normally use `:Gwrite` but that also [`:write`](https://github.com/tpope/vim-fugitive/blob/master/plugin/fugitive.vim#L1510)s the file, updating the file's timestamp (in my project, causing another recompile, without any code change). If it used `:update`, it'd suit my case.

I've tried `:Git add %` which gets closest, but on Windows keeps a cmd window open where I'd need to hit a key to close the window.

Another choice is `:Gcommit`, but that also adds all the other changed files too.

Another choice is `:Gstatus` where I'd manually add the file with `-` but that takes several inputs to do which is not ideal. 

Is there a command that I could use to add the current file to the index?

**Comment by tpope** [comment]
`:sil Git add %` is probably your best bet. I could see an argument for changing `:Gwrite` to use `:update`, but given the name of the command I think I'd rather stick to using `:write` for consistency.

**Comment by tankorsmash** [comment]
Definitely agree, it makes sense to that `:Gwrite` works as much as `:write` as possible. 

`:silent Git add %` works perfectly for my case, thanks!
