### ISSUE TITLE
Git add is not working when using Gstatus

### ISSUE THREAD

**Issue by Akemi-Homura** [tpope/vim-fugitive#1014]
I use Gstatus and press `p` on the modified file,but nothing happened.What's up?
This is the screenshot of Gstatus (I just press `p` on the 7th line):
![image](https://user-images.githubusercontent.com/16780053/38497369-7d42d566-3c33-11e8-9b67-d128a8b36b54.png)
This is the screenshot of my `.vimrc` file:
![image](https://user-images.githubusercontent.com/16780053/38497409-9685fe2c-3c33-11e8-87db-fc7cb76f1bbe.png)

**Comment by justinmk** [comment]
scrooloose/vim-fugitive ...?

**Comment by tpope** [comment]
Yeah that's a 5 year old fork.
