### ISSUE TITLE
 Fugitive not loaded in new tab

### ISSUE THREAD

**Issue by memeplex** [tpope/vim-fugitive#1018]
Say I open vim inside a git repo, I get an empty buffer and execute `:Gstatus`, that works just fine.

Now almost the same, but after getting the initial empty buffer I just open a `:newtaband` there I run `:Gs<tab><tab><tab>`... `Gstatus` is not defined. But my `:pwd` contains a git repo, indeed.

**Comment by tpope** [comment]
This is in the FAQ.

**Comment by memeplex** [comment]
Oh I hadn't read it, Tim.

But still there are a couple of points that doesn't quite match the answer there:

1. When running vim without opening any file but inside a repo dir, fugitive does install its commands.

2. Gstatus it's quite useful by itself without a file being open at all. It's more like a global command.

This and my other report today were the result of trying to set up a new tab for reviewing changes before committing. My first try was to open the status window in the current tab and then moving it to a new one, but there was this previewwindow issue. Then I tried creating a new tab and opening the status window there, but the Gstatus command wasn't available anymore. I still think it's a valid use case, don't you?

**Comment by memeplex** [comment]
Btw, I tried to set an autocmd for installing fugitive on tabnew based on the ones set by the plugin, but i didn't manage to get it working (the command creation code is run but nothing is there after that, I even set NewBuf and NewWin autocmds but to no avail). Any suggestion?

**Comment by tpope** [comment]
See #1000, which includes discussion of the same `:Gstatus` issue.

**Comment by tpope** [comment]
Also, consider `:tabe.` rather than `:tabnew`. Saves a character, even.

**Comment by memeplex** [comment]
Thank you for all the tips and sorry for bothering you with one more question: do you know what would be a working autocmd for detecting fugitive on a new tab? I tried setting for TabNew, WinNew, BufNew, TabEnter the same code that is set for VimEnter (or just the call to fugitive#detect without the guard) but it didn't work at all. Weird enough fugitive#detect is run and the git commands are created but I suspect not in the right environment at the point the event is triggered.

**Comment by tpope** [comment]
There is not a good autocommand for it. That's a big part of the reason it's not supported.
