### ISSUE TITLE
:Gedit from a revision activates vim-dirvish

### ISSUE THREAD

**Issue by shmup** [tpope/vim-fugitive#1020]
Alternatively if I remove vim-dirvish, `:Gedit` will now trigger netrw

I must be doing something wrong?

It goes like: 1) open a thing 2) `:Gblame` the thing, press `o` or `<CR>` on a line. `:Gedit`, and pan-to-dirvish.

**Comment by justinmk** [comment]
What is the resulting buffer name in dirvish / netrw? Does that match the name of a directory in your environment?

**Comment by shmup** [comment]
@justinmk dirvish uses buftype=nofile and netrw doesn't add to buffers either

**Comment by shmup** [comment]
No shit? Ok, well yeah, this all makes sense now. I have never ever tried pressing `<CR>` again, but sure enough my intuition might suck.

Thanks.
