### ISSUE TITLE
Glog going to stdout instead of opening in quickfix window

### ISSUE THREAD

**Issue by jonahx** [tpope/vim-fugitive#1021]
Apologies if this is a misunderstanding of the feature on my part.  That said...

I have removed everything from my `.vimrc` except for fugitive plugin.  When I run `:Glog`, I see the output in the vim standard out window (if that terminology is correct) -- the one that vanishes after you press Enter.  The output looks like this:

```
:!git --git-dir=/Users/jg/.git --no-pager log --no-color '--pretty=format:fugitive:///Users/jg/.git//%H/.gitignore::%s' -- .gitignore  2>&1| tee /var/folders/hm/rr6zdtjs4k5221zffq6yy_5h0000gn/T/nvimX65Gj6
/1

fugitive:///Users/jg/.git//f9f374a5b6d7e74efabeebe7c6b9432a089a2d4b/.gitignore::Add nvim init file
fugitive:///Users/jg/.git//6c5e662ac608c1f266647d8a227752ba8755238b/.gitignore::Add .gemrc
fugitive:///Users/jg/.git//94b85ec17d823a55e2e0891cc3325198075328dc/.gitignore::Support side by side diffs in terminal with icdiff
fugitive:///Users/jg/.git//9b977c99091125c2bfc903fac18c7829ea103ce3/.gitignore::Add custom bin scripts
fugitive:///Users/jg/.git//5017e43e7e4697c4dd46a22a931dafcb5589b693/.gitignore::Add whitlisting of files, bash_profile, git completion
(1 of 5): Add nvim init file
Press ENTER or type command to continue
```

The help docs say that `Glog` will "Load all previous revisions of the current file into the quickfix list."

Do I need to configure something to get that behavior?

Other notes:
- I updated fugitive before testing
- I tested in both nvim and macvim (same behavior in both)

Thanks.

**Comment by tpope** [comment]
It populates the quickfix *list* but it doesn't open the quickfix *window*. This is identical to how Vim built-ins like `:grep` and `:make` behave.
