### ISSUE TITLE
Gdiff: Combining BOTH the target, merge branch conflict chunks into working copy 

### ISSUE THREAD

**Issue by tecfu** [tpope/vim-fugitive#1022]
**Issue**:

There are times when one wants to use lines from both the target and the merge branch to resolve a particular conflict. Unfortunately, *:diffput* and *:diffget* don't seem to allow this. 

 Is there a better way to combine the target and the merge branch into the working branch outside of [1] manually yanking from the target and merge branch and then [2] pasting into the working branch?

**Proposal if no other workaround exists**:
- Allow passing of extra argument to diffget in order to get from multiple buffers into the current buffer.
For example (order matters here):
```
 :diffget [integer],[integer]  
```
See also: 
https://vi.stackexchange.com/questions/10534/is-there-a-way-to-take-both-when-using-vim-as-merge-tool
https://stackoverflow.com/questions/36701875/how-do-i-accept-both-changes-in-vimdiff-hunk

**Comment by tpope** [comment]
`:diffget` is a built-in. We can't change it. It does accept a range, but I generally just favor copy/paste when it gets that hairy.

**Comment by tecfu** [comment]
@tpope I accept your position and I still love you, Tim. But I'll add the following deletion command for anyone in the future who stumbles across this issue and wishes for a single command alternative. 

To delete all lines that start with:
```
<<<<<<<
=======
>>>>>>>
```

Use: 
```vim
:g/^<\{7}\|^|\{7}\|^=\{7}\|^>\{7}/d
```
