### ISSUE TITLE
Committing sometimes fails to work, often with no error message

### ISSUE THREAD

**Issue by BRMatt** [tpope/vim-fugitive#1024]
I usually use `:Gstatus` to stage the appropriate files, then press `cc` to start writing a commit message. Once I've written a message saved it with `:wq` fugitive should (and often does) create  a commit with that message. However, quite often fugitive *doesn't* create a commit, and the contents of the commit message are still in `.git/COMMIT_EDITMSG` when that buffer has closed. This is all that I see in vim's footer:

```
".git/COMMIT_EDITMSG" 32L, 1889C written
```

Unfortunately I don't have repro steps as it seems to start happening when I'm several hours in, and I'm not exactly sure what causes it.

I'm not really sure how to collect fugitive debug logs(?), but I'm trying to use sysdig from outside the editor to see if anything notable is happening. I'm mainly opening this issue to track the problem/find out if there's anything I should try.

Here are some details about my environment:

```console
$ nvim --version
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.4
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-HJnLxJ/neovim-0.2.2/build/config -I/build/neovim-HJnLxJ/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-HJnLxJ/neovim-0.2.2/build/src/nvim/auto -I/build/neovim-HJnLxJ/neovim-0.2.2/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

I'm currently on version 40d78f07dee2ffab68abb9d6d1a9e27843df0fe0, here're the dotfiles I'm using https://github.com/BRMatt/dotfiles/blob/master/nvim/init.vim#L34

**Comment by tpope** [comment]
I have seen this happen too. The commit is created in the `BufDelete` event, and sometimes *all* `BufDelete` events seem to stop firing, with the only solution being to restart Vim. I'm guessing an obscure Vim bug. Unless you know your way around the Vim source code, I don't have much to suggest other than checking if `BufDelete` is broken for you too.

**Comment by BRMatt** [comment]
Hey Tim, sorry I didn't followup sooner, I completely missed your reply.

Thanks for the info, that's really useful to know. I'll try to look into the `BufDelete` events the next time it pops up. It's frustrating that it's so difficult to replicate reliably.

**Comment by tpope** [comment]
FWIW I upgraded Vim last week and haven't seen the issue since, although it was an infrequent enough issue that it could still be hiding.

**Comment by tpope** [comment]
It's been months, I'm assuming this was a Vim bug.

**Comment by qoobes** [comment]
Still happens to me occasionally, with the same steps the original author described. The difference being that one of the three following cases can happen:

- After pressing `cc` again, the original contents of the commit are present
- After pressing `cc` again, the commit is created without opening the commit message buffer
- After pressing `cc` again, a new empty buffer is shown

**Comment by tpope** [comment]
Unless you're running a version of Vim from 2018, I doubt it's the same cause. The first thing that comes to mind is that a hook might be failing. You might want to try disabling those for a bit and see if the problem helps.

When the problem next happens, you should check if `git commit` is still running in the background. That will clarify if `git commit` is failing, or just running indefinitely.
