### ISSUE TITLE
Gblame offset mismatch in diff view with diffopt+=filler (Gdiff)

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-fugitive#1026]
TEST CASE:

1. Adding a line to the working tree copy of a file
2. `:Gdiff`
3. `:Gblame` on the file from the index

The blame buffer's lines get misaligned, since the diff view has the added line from the worktree as missing.

![2018-05-04-121426_952x515_escrotum](https://user-images.githubusercontent.com/9766/39623170-0c59deb0-4f95-11e8-90ed-c18e552da35d.png)

I guess there is not much that can be done here, because the blame view is not in diff mode, and it's also not possible to align lines manually there (https://github.com/vim/vim/issues/2545).

What might work in this case is running `git diff` first to get the new/removed lines and adjusting the output from `git blame`, but that's not really straight forward.

A workaround is to use `set diffopt-=filler` (a global option).
Fugitive might want to set this when using `Gblame` and there are (fugitive) diff windows maybe.

**Comment by blueyed** [comment]
Yes, `diffopt-=filler` has obvious drawbacks, but I think it's better than having the blame window being misaligned - which really confused me initially.
Instead of setting `diffopt-=filler` automatically, a warning/message could be displayed when this situation is detected, suggestion to use `diffopt-=filler`.

**Comment by tpope** [comment]
`diffopt` is global, changing a global behavior seems more confusing than a local failure. I would entertain a change that disables diffing entirely, if that seems like an improvement.

**Comment by blueyed** [comment]
Just for reference: it might become a tablocal option: https://github.com/vim/vim/issues/4782
