### ISSUE TITLE
Gblame window commands broken using custom TMPDIR

### ISSUE THREAD

**Issue by sofal** [tpope/vim-fugitive#103]
I've used git bisect to determine that commit 4a20d8802ec16290ba903d032546731537d4b773 has broken the Gblame window commands for me when I use a custom setting of $TMPDIR in my vimrc. When I use the 'o' command I get:

Error detected while processing function <SNR>21_Edit..<SNR>21_buffer..<SNR>21_throw:
line    2:
E605: Exception not caught: fugitive: not a git repository: /home/ryanph/.vim-tmp/vXXX/vJVH5Zt/1.fugitiveblame
Error detected while processing function <SNR>21_Edit:
line    4:
E171: Missing :endif

The 'q' command also does not work for me after this commit (it records instead of exiting the Gblame window).

**Comment by Newlifer** [comment]
I second this.

**Comment by tpope** [comment]
I sent an email reply to this ages ago but apparently it never went through. Check `:echo b:git_dir` in the blame window.

**Comment by filcab** [comment]
Hi @tpope,

I'm having this problem on Windows too. `:echo b:git_dir` shows me the current git directory on the text file window. But on the blame window that opens next to it, I get `Undefined variable: b:git_dir`.

On a macOS box, both of them agree.

On Windows I only get this problem if I start vim from a git bash window. If I start it from cmd or gvim, I get that variable set properly.

**Comment by filcab** [comment]
If there's a way to turn on additional logging on vim or fugitive (I'm a bit of a newbie on vim debugging), I can try that and report back.

**Comment by tpope** [comment]
I retooled temp file handling, please try again.
