### ISSUE TITLE
Can't open a new "Gedit' in a new tab if one is already open

### ISSUE THREAD

**Issue by alphaCTzo7G** [tpope/vim-fugitive#1031]
If I open a file in a certain revision using 'Gedit revision:filename.py` and then try to use `:tabe` to open a new tab and edit another file from the same revision `Gedit revision:filename2.py`, `Gedit revision:filename2.py` fails with the error message

`E492: Not an editor command: Gedit revision:filename2.py`

Is that the designed behaviour, or a bug?

**Comment by tpope** [comment]
Designed behavior, use `:Gtabedit`
