### ISSUE TITLE
Status line branch name not truncated

### ISSUE THREAD

**Issue by dylan-chong** [tpope/vim-fugitive#1032]
![screen shot 2018-05-27 at 2 02 02 pm](https://user-images.githubusercontent.com/17482349/40581842-93a19876-61b6-11e8-9243-a7438897cfe1.png)

When on a branch that has a very long name, the branch name in the status line hogs the space.

There should be a good default that truncates the length of the branch.

**Comment by tpope** [comment]
Fugitive has a statusline indicator but that isn't it. Report to Powerline or Airline or whatever plugin you're using.
