### ISSUE TITLE
Removing 'compatible' check drastically increases startup time

### ISSUE THREAD

**Issue by brovie96** [tpope/vim-fugitive#1035]
TEST CASE:
1. Have [junegunn/vim-plug](https://github.com/junegunn/vim-plug) loaded and set it to install fugitive.vim @ ddec4bf and [tweekmonster/startuptime.vim](https://github.com/tweekmonster/startuptime.vim)
2. Start Vim, run `:PlugInstall`, and restart
3. Run `:StartupTime 100` and observe that fugitive.vim takes substantially less than a millisecond to load
4. Remove the section in vim-plug's settings specifying the commit to use for fugitive.vim so it uses the newest commit (dd4d4c7 at the time of writing)
5. Repeat Step 2
6. Run `:StartupTime 100` again and observe that fugitive.vim now takes almost 30 milliseconds to load

As described above, fugitive.vim takes a lot longer to load without checking for `compatible` at the beginning. Screenshots below.

Before removing `compatible` check:
![screen shot 2018-06-01 at 2 20 29 pm](https://user-images.githubusercontent.com/5694763/40864407-884c3562-65a8-11e8-8339-50eea809cca3.png)

After removing `compatible` check:
![screen shot 2018-06-01 at 2 21 28 pm](https://user-images.githubusercontent.com/5694763/40864437-a914dd44-65a8-11e8-8864-9d1af4aab660.png)

(The red highlighting is from my Vim config highlighting trailing whitespace, and should be ignored)

**Comment by tpope** [comment]
This **has** to be `:StartupTime` launching in compatible mode, causing Fugitive to short circuit. What else could it be?

**Comment by brovie96** [comment]
Yep, that's it. Adding an explicit `set nocompatible` to my `.vimrc` fixed the issue, and now it appears to take a constant ~4 ms whether it checks `compatible` or not. Thanks for pointing out that issue with `:StartupTime`!
