### ISSUE TITLE
How To Use PGP

### ISSUE THREAD

**Issue by weilbith** [tpope/vim-fugitive#1036]
Hey!
First thanks for this nice plugin. I really like it!
I prefer to sign my commits per default when working with _Git_. I also prefer to stage my files within _Vim_ using this plugin. But when I start to commit and use `:wq` as stated in the documentation, I get no option to insert my password for my private key. I couldn't found a hint within in the documentation nor a issue discussing that, so I ask for help here.
Thanks!

**Comment by gmarmstrong** [comment]
What is the output of:

```
git config gpg.program
git config commit.gpgsign
git config user.signingkey
```

**Comment by weilbith** [comment]
@gmarmstrong even if I set `git config gpg.program` this does not work. Any suggestions?

**Comment by gmarmstrong** [comment]
Okay, next check these:

```
git config core.askPass
echo $GIT_ASKPASS
echo $SSH_ASKPASS
```

**Comment by weilbith** [comment]
All of them are empty. Have never set them in my environment or git config.
I was wondering cause in plain terminal it works as expected. After close the editor for the commit message, a window pops-up and ask me for my password. 
Can I set a variable to use exhaustive debugging messages by fugitive?

**Comment by weilbith** [comment]
As I observe it, it just fail silently. Means after I save, nothing happens. So checking my git status afterwards and also the log, there is new commit and the stage is the same.

**Comment by tpope** [comment]
Surely you mean there *isn't* a new commit?

Are you using plain terminal Vim? GUI Vim? Neovim? I haven't tested but the latter two might fail that way, possibly.

**Comment by weilbith** [comment]
I'm using NeoVim inside a zsh, running whithin TMux.

I just opened a new local repo. Open a new file with `nvim`, write something and save it. Then directly call `:GStatus` and stage the new file with `-`. In the same status buffer I type `cc` to make the commit, enter my message and `:wq` the buffer. I c the message `"/tmp/test/.git/COMMIT_EDITMSG" 11L, 239C written`. Afterwards the commit history is still empty (as it is a new repo) and the new created file is still in the staging area.

**Comment by gmarmstrong** [comment]
Where you see `/tmp/test/.git/COMMIT_EDITMSG`, I see `~/test/.git/COMMIT_EDITMSG`, and my commit is successfully signed. Does this issue still occur when `gpg-agent` is running with your password cached?

**Comment by weilbith** [comment]
It is the same for than for me. I jus created my example repo at `/tmp/test/`.
I've done now a first commit (while password not cached) so it requests my password and cache it. Afterwards I do exactly the same again, but it doesn't work either. Sorry. :/

**Comment by weilbith** [comment]
Not sure how much I can do wrong. :see_no_evil:

**Comment by tpope** [comment]
Neovim doesn't give a terminal to commands executed from Vim, so there's no way to prompt for a password. Use of either an agent or an askpass program will be mandatory.

**Comment by weilbith** [comment]
Okay, thanks!
So if I would establish the default `gpg-agent` this works? What happens then? Get I the normal pop-up window to ask me for the password or is this meant by `askpass`? Do I need to defined `pinentry` program in this scenario?
Sry so far GnuPG has just worked for me without much to do.

**Comment by weilbith** [comment]
I switched to `pinentry-curses` and apparently it works now.

**Comment by CarlosNihelton** [comment]
Since this is one the first Google entries when searching for gpg commit sign with neovim and fugitive, I'd like to keep for the record that [this approach of enabling pinetry loopback mode](https://stackoverflow.com/questions/41052538/git-error-gpg-failed-to-sign-data#answer-61314861) worked really fine for me with the combo `WSL2 + tmux + zsh + neovim + fugitive.vim` and I got the password prompt from Neovim itself, instead of the pinentry program configured in my `gpg-agent.conf`. For now I prefer that, unless I discover some security issue.

@tpope , really appreciate your plugins! Thanks for the awesome work!
