### ISSUE TITLE
Stuck in preview window when exiting from GStatus

### ISSUE THREAD

**Issue by marcomagdy** [tpope/vim-fugitive#1037]
1. run `GStatus`
1. hit `dp` on a new or changed file, the patch file will be displayed and the focus will move to its buffer
1. hit 'q' while in the patch buffer, it exits and leaves the status preview window
1. hit 'q' again to exit the status preview window and return back to your source
1. notice how you're still stuck in the preview window
1. repeat the steps above and commit instead of exiting status, vim exits.

- Vim 8.1
- Mac OS 10.11.6

**Comment by tpope** [comment]
This feels like a Vim design issue. If you close all windows but the preview window, you're stuck in the preview window. Until you `:set nopreviewwindow`, anyways.

**Comment by marcomagdy** [comment]
This happens even if you have other buffers still open

**Comment by tpope** [comment]
You mean other splits in the same tab? I can't reproduce that.

**Comment by marcomagdy** [comment]
>You mean other splits in the same tab? I can't reproduce that.

Not splits, full window buffers.
Revising the steps for clarification:
1. open two source files in vim in two buffers (no tabs, no splits)
1. make a change in buffer 1, save and run` :Gstatus`
1. `dp` on the changed file, now the focus is in the patch window
1. hit `q`, the patch window will close, leaving the status preview window occupying the whole screen (no splits). Note, that at this point buffer 1 and buffer 2 from step 1 are still open (not in splits, not in tabs)
1. hit `q` again to exit the status window and return back to either buffer 1 or buffer 2
1. Now, buffer 1 and buffer 2 are displaying in the 'preview window', exiting any of them, exits vim.

**Comment by tpope** [comment]
Preview is a property of the window, not the buffer. Do `:pedit somefile` then `:edit anotherfile` in that same window and it's still the preview window. It's just how Vim works.

**Comment by marcomagdy** [comment]
The problem is hitting `q` in the patch window closes it. Even though the patch window is not a preview window.

**Comment by tpope** [comment]
`q` is just a convenience alias for `:bd`. What are you proposing it do instead?

**Comment by marcomagdy** [comment]
`q` makes sense, but the behavior is different when you exit the status window then the patch window, versus exiting the patch window then the status. The latter keeps you stuck in a preview window. The former works great.

**Comment by tpope** [comment]
If you close the preview window then you're not stuck in the preview window. If you close every window but the preview window you're left (or "stuck") in the preview window. I don't know how else to explain it.

**Comment by marcomagdy** [comment]
>If you close every window but the preview window you're left (or "stuck") in the preview window.

But I didn't close every other window is what I'm saying.
here is a recording https://asciinema.org/a/Jv0GiqB0T3R0EnGHkt07COZTw

**Comment by tpope** [comment]
You literally close the only other window at the 37 second mark.
