### ISSUE TITLE
Gstatus's preview window has syntax on only when not focused.

### ISSUE THREAD

**Issue by vheon** [tpope/vim-fugitive#1038]
I've tried with an old version of vim-fugitive and and it doesn't happen. I didn't do a bisect though.

**Comment by tpope** [comment]
Weird, I'm not even sure how that could be possible. You should test dd4d4c75959767b591852091bb73b7c7a85a02e2 as that's right before switching to an autoload file.

**Comment by vheon** [comment]
Sorry, I still don't know what causes it but it happens on one machine but not in another with a almost identical configuration. I guess I have to do some config spelunking 😞.
