### ISSUE TITLE
fugitive should save the file before running commands

### ISSUE THREAD

**Issue by dylan-chong** [tpope/vim-fugitive#1040]
eg running `Gcommit` should save the file before running to make sure the most up to date file is committed

**Comment by tpope** [comment]
It does if you set `'autowrite'`.

**Comment by dylan-chong** [comment]
The thing is, you may not want autowrite. for example if you have a livereload server and you dont want it to chew cpu evrytime you switch buffers. i only save when focus is lost

**Comment by tpope** [comment]
People may not want `:Gcommit` to autowrite either.

**Comment by dylan-chong** [comment]
I suppose that might be possible, although I can't think of any reasonable situations that would be true at the moment...

Oh well I guess one option is to create key mappings that do something like `:w | Gcommit` instead. I guess that will be a good enough solution for now
