### ISSUE TITLE
Gcommit "silently" fails

### ISSUE THREAD

**Issue by blayz3r** [tpope/vim-fugitive#1042]
This is on MS windows 10. Vim 8.1
All other commands work well but Gcommit fail "silently".
An error briefly flashes **fatal: xxx.tmp is outside repository**. It is not saved in the :messages.

The commands work from the terminal

**Comment by tpope** [comment]
Does it fail when first call it, or when you `:wq` the commit buffer? Does `:Gcommit -m message` work?

**Comment by blayz3r** [comment]
It fails on first call, :Gcommit -m message does not work?

**Comment by tpope** [comment]
Easiest solution would probably be to wrap [the shell invocation](https://github.com/tpope/vim-fugitive/blob/cbf96cc01a429143c9a135ae572fec5ffaad8c40/autoload/fugitive.vim#L1022-L1028) in a `try` block that temporarily sets `guioptions-=!`.

**Comment by blayz3r** [comment]
Excellent thanks!!

**Comment by tpope** [comment]
I'm removing the workaround because we're using `system()` now which should render it obsolete. Let me know if it's still an issue.
