### ISSUE TITLE
:Git is tedious in NeoVim / with :terminal

### ISSUE THREAD

**Issue by niklaas** [tpope/vim-fugitive#1048]
Maybe it's just me, if so feel free to close this issue, but I find using `:Git` quite tedious in NeoVim. The reason for this is mainly that `:terminal` instead of `:!` is used to call to the provided comand. In addition, as discussed in #784, a new tab is opened beforehand.

Take the example of `:Git status` or `:Git checkout`. When called, a new tab is opened and a `:terminal` session spawned. I read the output and must close the tab with `:q` or the buffer with `:bd!`. In comparison, `:!git status` or `:git checkout` wouldn't create a new tab, hence I could simply hit `<Enter>` and continue editing. The same worklflow as with "normal" Vim would apply.

So I vote for using `:!` instead of `:terminal` when using `:Git`. However, it's more likely that I miss some advantages of `:terminal` over `:!` in a lot of other use cases, so please enlighten me! :-)

**Comment by justinmk** [comment]
@niklaas This is a Neovim limitation. There's little that fugitive can do about it until https://github.com/neovim/neovim/issues/1496 is fixed. 

See also https://github.com/neovim/neovim/wiki/FAQ#-and-system-do-weird-things-with-interactive-processes

**Comment by niklaas** [comment]
I see. Thanks a lot for the explanation and the wiki link!
