### ISSUE TITLE
increase to 100% CPU when using diff

### ISSUE THREAD

**Issue by thovt93** [tpope/vim-fugitive#1049]
I use `:Gstatus` to show anything files change and then I press `D` or `ds` to view anything change in a file and then my CPU increase to 100% in few seconds.
I use `NEOVIM v0.2.2`.
How to fix that?

**Comment by IamTheFij** [comment]
This also happens to me with vim8

**Comment by tpope** [comment]
Still happening? Does "a few seconds" mean it eventually does the diff?

**Comment by tpope** [comment]
If this is still happening, check `top` and report back if with it's Vim or Git that's pegging the CPU.
