### ISSUE TITLE
[question] Git checkout and similar commands open a new buffer

### ISSUE THREAD

**Issue by vn-ki** [tpope/vim-fugitive#1051]
When I do `:Git checkout master`, I get a new tab (not buffer) with the output of `git checkout master`, with `[Process exited 0]`. Then I have to either close that buffer (`:bd`) or go to insert mode and press a key.

I do not want this. Is it possible to show the output in the preview window or not show the output at all?

**Comment by tpope** [comment]
Neovim has a broken `:!`, so we use `:terminal` instead. You can use `:Gpedit! checkout master` to achieve the literal behavior you request, although I doubt using a different command is what you had in mind. My personal solution is to not use Neovim. 🤷‍♀️

**Comment by vn-ki** [comment]
But doing `:!git checkout master` gives the desired (atleast on my nvim). Is this not what you were talking about being broken?

**Comment by tpope** [comment]
More precisely, if you call a command that tries to do interactive input, such as `git push` asking for a password, it hard locks Vim.

I guess I would be okay with adding a `g:fugitive_force_bang_command` or something that you could enable if you accept the risk.

**Comment by vn-ki** [comment]
Yes. Please add that. I would be very grateful.

I am completely accept the risk. It is very annoying when a new terminal starts every single time.

**Comment by vn-ki** [comment]
Is there an open issue tracking this at neovim repo?

**Comment by tpope** [comment]
I believe so, it comes up a lot. I'll let you have the honor of tracking it down. Look for similar Fugitive issues for leads.

**Comment by tpope** [comment]
I added the option.

**Comment by vn-ki** [comment]
Wow. You are fast. 

Thank you very much @tpope. Without you vim would be unusable. I love your plugins.
