### ISSUE TITLE
Yank Git Link To Specific Line

### ISSUE THREAD

**Issue by sammerry** [tpope/vim-fugitive#1053]
Is there a way to yank the line number for a git project? I'd like to map something like `Gyank` to yank a git link to a specific line. With a small settings change i could then paste it into Slack or IRC or qutebrowser.

Example:
Gyank would put a url like
`https://github.com/tpope/vim-fugitive/blob/master/plugin/fugitive.vim#L50` into the yank buffer.

**Comment by tpope** [comment]
`:.Gbrowse!` puts the URL into the clipboard register.

**Comment by HarrisonB** [comment]
To anyone stumbling upon this, these mappings might prove useful:

```vim
nnoremap <Leader>gy :.Gbrowse!<CR>
vnoremap <Leader>gy :'<'>Gbrowse!<CR>
```

**Comment by tpope** [comment]
Use `xnoremap` not `vnoremap`.

**Comment by kwrobert** [comment]
@tpope In case anybody hasn't told you they love you recently I just want to say I love you and your plugins bring great joy to my daily vim experience.
