### ISSUE TITLE
No fugitive commands working - temp file name problem or <SNR>52_ReplaceCmd issue?

### ISSUE THREAD

**Issue by philwhiles** [tpope/vim-fugitive#1054]
Fugitive cloned from master today, installed with Pathogen, running with vim81 under cygwin on windows server 2012

Git installation is windows version, not cygwin - git works fine when invoked from bash.

 :Glog, :Gstatus etc shows a disparity between the temp file name used in the !git command redirection and the subsequent output display, but this is always preceded by a complaint about <SNR>52_ReplaceCmd.

Is this a bug or a setup/env issue?

![untitled](https://user-images.githubusercontent.com/5368272/42685230-54f0b410-868a-11e8-98b3-feecf9d6c737.png)

**Comment by tpope** [comment]
Those tempfiles are unrelated. The first is for running `git log` and the second is for displaying the first result. "Cannot open file" usually means "the command that was supposed to create this file failed". You'll have to crack open `s:ReplaceCmd` to see what went wrong. I don't have a way to test on Windows currently so I can't do much debugging myself.

**Comment by tpope** [comment]
I guess I can at least direct you to the line that's probably failing: https://github.com/tpope/vim-fugitive/blob/302f30c9243984b62434dbd03341903e54f3cd09/autoload/fugitive.vim#L2662

**Comment by tpope** [comment]
I improved the error messages a bit which might provide a clue.

**Comment by philwhiles** [comment]
Pulled master - no better clues.
Sorry - don't do vimscript
The line you ref above appears not to be in master btw?

**Comment by tpope** [comment]
It's here now:

https://github.com/tpope/vim-fugitive/blob/5ba918ea7b1dff196c64872bd72cdcf5bc052dff/autoload/fugitive.vim#L2670

You could change that `return system` to `echomsg` to see what it's trying to run.

**Comment by tpope** [comment]
I have pushed some really good error messages.

**Comment by tpope** [comment]
If it's still happening, report back with the new error message.
