### ISSUE TITLE
0717396aa2a5679 breaks :Glog

### ISSUE THREAD

**Issue by lanza** [tpope/vim-fugitive#1059]
When you run :Glog with 0717396aa2a5679 you get

    :!0  2>&1| tee /var/folders/p5/2m9kg46x21q8h5f9p6tpft64rm_j69/T/nvimdzJ9oV/1
    /usr/local/bin/bash: 0: command not found

If you `$ git checkout HEAD~1` from there it works fine.

**Comment by tpope** [comment]
Thanks!
