### ISSUE TITLE
autocmd seems to be broken

### ISSUE THREAD

**Issue by griffingarland** [tpope/vim-fugitive#1060]
It seems when creating a new buffer with fugitive://\*/\/*, nothing loads (at least on my machine).

It works when I revert this commit: 29411e28013d604a665a370e94ae3ee749ae2f93.

I'm currently using fzf.vim with the :Commits command to reproduce this.

**Comment by griffingarland** [comment]
HEAD:
![Broken](https://i.imgur.com/VG7VZDU.png)

HEAD~7:
![Working](https://i.imgur.com/E90oMPc.png)

**Comment by griffingarland** [comment]
Wish I had a better way to reproduce but I just noticed it when using fzf

**Comment by tpope** [comment]
So it's failing for commits. Can you check if any of the following work?

* `:Gedit commit:file`
* `:Gedit commit:dir`
* `:Gedit :file`
* `:Gstatus`

**Comment by tpope** [comment]
If you delete this line, you might find a more useful error message in `b:fugitive_type`:

https://github.com/tpope/vim-fugitive/blob/c118dabb89b6e7e42383d4cf6f426e53bb45279c/autoload/fugitive.vim#L2846

**Comment by tpope** [comment]
Sounds good. I'll add a warning about the invalid name.
