### ISSUE TITLE
:Gwrite and equivalent (- in :Gstatus) stopped working with lcd and cd autocommands

### ISSUE THREAD

**Issue by raymond-w-ko** [tpope/vim-fugitive#1061]
I update to ```master``` pretty frequently and noticed this following regression today. Like the title says, both of these commands fail to work with the error reported below.

I ran a ```git bisect``` and got the below.

```
fugitive: fatal: pathspec 'directory/filename.py' did not match any files

978ca4a5ce10a0c05bdccd5c04adba2f430412a2 is the first bad commit
commit 978ca4a5ce10a0c05bdccd5c04adba2f430412a2
Author: Tim Pope <code@tpope.net>
Date:   Sun Jul 22 13:56:21 2018 -0400

    Encapsulate fugitive#repo().git_chomp_in_tree()

:040000 040000 4afb34e975b64e1ab1c9d33dc8cd005b2de0106f 314fe8cbd9041c5cb98949ebf15bd197727ce555 M      autoload
```

Assuming this is something that only affects me, I got some pretty crazy "autochdir" going on with these autocommands going in my vimrc. Am I crazy for having this? I vaguely remember forcing this years ago as I was getting issues of sometimes files would not ```autochdir``` correctly. 
```
set noautochdir
autocmd BufEnter * silent! lcd %:p:h
autocmd BufEnter * silent! cd %:p:h
```

**Comment by raymond-w-ko** [comment]
Oh yeah, disabling this in my ```vimrc``` makes ```:Gwrite``` and friends work again.

**Comment by tpope** [comment]
Crazy indeed but it's still a bug.
