### ISSUE TITLE
`Error detected while processing function FugitiveDetect`

### ISSUE THREAD

**Issue by carlwgeorge** [tpope/vim-fugitive#1062]
Hello!  I maintain (and use) vim-fugitive RPMs for Fedora and EPEL (RHEL/CentOS).  The latest 2.4 update is giving me errors.  I can reproduce this in new containers where no other plugins are installed.

steps to reproduce:

```
yum install git-core vim-enhanced
yum --enablerepo updates-testing install vim-fugitive
git init
vim test
```

result:

```
"test" [New File]
Error detected while processing function FugitiveDetect:
line   11:
E117: Unknown function: fugitive#Init
E15: Invalid expression: fugitive#Init()
Press ENTER or type command to continue
```

I get the same error on CentOS 7, Fedora 27, and Fedora 28.  The problem did not exist in version 2.3 of the plugin, and started showing up in the 2.4 update.  Here are the versions of vim and git involved in each of those environments.

CentOS 7:
- vim-enhanced-7.4.160-4.el7
- git-1.8.3.1-14.el7_5

Fedora 27:
- vim-enhanced-8.1.177-1.fc27
- git-core-2.14.4-1.fc27

Fedora 28:
- vim-enhanced-8.1.197-1.fc28
- git-core-2.17.1-3.fc28

**Comment by tpope** [comment]
Guessing the build scripts need to be updated to include `autoload/fugitive.vim` (and `ftdetect/fugitive.vim`).

**Comment by carlwgeorge** [comment]
Thanks for the feedback!  Sure enough, right now the package is only putting `plugin/fugitive.vim` and `doc/fugitive.txt` on disk.

https://src.fedoraproject.org/rpms/vim-fugitive/blob/master/f/vim-fugitive.spec#_65-66

```
install -D -p -m 0644 doc/fugitive.txt %{buildroot}%{vimfiles_root}/doc/fugitive.txt
install -D -p -m 0644 plugin/fugitive.vim %{buildroot}%{vimfiles_root}/plugin/fugitive.vim
```

I manually put the missing files in place and it resolved my issue.  I'll get the package updated to correctly install these.  Thanks!
