### ISSUE TITLE
This error always appear when i browse code

### ISSUE THREAD

**Issue by Abson** [tpope/vim-fugitive#1063]
![wx20180724-174133](https://user-images.githubusercontent.com/13198014/43130279-f1aa1d28-8f68-11e8-8db0-80dfe2230545.png)

**Comment by tpope** [comment]
Something seriously strange appears to be going on. Can you `cat .git/HEAD` in that repository?

**Comment by Abson** [comment]
![1532489247153](https://user-images.githubusercontent.com/13198014/43178020-de45ef10-8ffd-11e8-893a-c17f7e968f9b.jpg)


In my opinion，there is no problem with .git/HEAD file.

**Comment by tpope** [comment]
Try `:echo readfile('.../.git/HEAD')`.

Also, make sure you're running the latest version. That screenshot is not from the latest version.

**Comment by matyus** [comment]
I'm getting a similar thing:

```
Error detected while processing function <SNR>34_Browse:
line   11:
E117: Unknown function: s:buffer
E15: Invalid expression: s:buffer().rev()
Press ENTER or type command to continue
```
`.git/HEAD` reads:
```
ref: refs/heads/master
```

**Comment by tpope** [comment]
Chalking this up to "old Fugitive version" until I hear otherwise.
