### ISSUE TITLE
File open from Gstatus window opens file in the same window

### ISSUE THREAD

**Issue by kaba-official** [tpope/vim-fugitive#1064]
Whenever I run :Gstatus I used to get a Gstatus pane opened on top of the current working pane. And when I press enter of a file being staged, the file will appear in the below pane. Once I verify the changes with :Gvdiff, I'll open the next staging file. It was very easy to verify each files before committing, as Gstatus pane is open the whole process.

But now [after updating on 25-July] if I press enter on a file being staged in Gstatus window, the file is being opened on the same pane not on a new pane below.

**Comment by tpope** [comment]
Are you sure you're on the latest? I fixed that earlier today.

**Comment by kaba-official** [comment]
Sorry. Updated again. Seems the issue causing patch is reverted at 49c2a4acb535e3c24b81c332a19934e980b731da.

Thanks 👍
