### ISSUE TITLE
Gdiff conflicts with BufWinEnter loadview places working copy at right or bottom if the file isn't open in buffer 1

### ISSUE THREAD

**Issue by jasminabasurita** [tpope/vim-fugitive#1065]
If I open a file with a conflict in it from the command line I can `:Gdiff` and the working copy will be centered as expected. If, however, I have had any other buffers open prior and the buff number of the working copy is not 1 then `:Gdiff` opens the working copy at the right in vertical mode or at the bottom in horizontal mode.
I'm running NeoVim v0.3.1 in case that holds any relevance to this.
![screenshot from 2018-07-26 09-41-14](https://user-images.githubusercontent.com/4014487/43265919-153a9d58-90b8-11e8-9ec2-5df3b208cc7b.png)

**Comment by tpope** [comment]
The first thing to try here is disabling other plugins to see if that resolves it.  A sufficiently clever plugin could be interfering with fugitive trying to switch back to the original window in between `leftabove split` and `rightbelow split`. (If that's the case, we can probably find a way to work around it.)

https://github.com/tpope/vim-fugitive/blob/6bab1a0c398a9a6aaef607a5361709393eba79ac/autoload/fugitive.vim#L2046-L2060

**Comment by jasminabasurita** [comment]
Interesting, I traced it back to 1 setting I have to save and load views automatically:

```vim
autocmd BufWinLeave *.* mkview
autocmd BufWinEnter *.* silent! loadview
```

**Comment by tpope** [comment]
Even with that I can't reproduce it. What's in `:set viewoptions?`?

**Comment by jasminabasurita** [comment]
`viewoptions=folds,options,cursor,curdir`

**Comment by jasminabasurita** [comment]
Removing everything from my `init.vim` except for fugitive.vim and those 2 lines of codes still manages to reproduce the bug on my end :confused:

**Comment by tpope** [comment]
Rather than keep going down this rabbit hole I've taken a stab at working around it. Assuming it works, a similar fix should probably be applied to the other uses of `wincmd p`.

**Comment by jasminabasurita** [comment]
:tada: :confetti_ball: Works great!
