### ISSUE TITLE
Do not show git branch in statusline when using flagship

### ISSUE THREAD

**Issue by Asheq** [tpope/vim-fugitive#1070]
When using flagship, fugitive automatically adds the git branch to the `statusline`. I would like to be able to turn this off since I don't like seeing the git branch at all times.

Thanks!

**Comment by tpope** [comment]
See tpope/vim-flagship#11 for info about globally disabling a flag. Note that will also disable the thing that shows you when you're editing a historical object, which is probably something we should come up with a solution for now that it shows a regular filename in that case.

**Comment by Asheq** [comment]
`let g:flagship_skip = 'FugitiveStatusline'` works for me. Thanks for the fast response!
