### ISSUE TITLE
Gstatus: "not a git repository" error when diffing/opening

### ISSUE THREAD

**Issue by unclechu** [tpope/vim-fugitive#1072]
When I press `D` or `<CR>` on a file in `Gstatus` window I get "not a git repository" error.
Here is an short screencast that demonstrates the issue: https://www.youtube.com/watch?v=vexK05Hw3kU
Fugitive commit hash: 85f340590d34ca65e383e3e937b0ed2c21b5f418
Result of `nvim --version`:
```
NVIM v0.3.0
Build type: RelWithDebInfo
Lua 5.3
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wconversion -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/builddir/build/BUILD/neovim-0.3.0/build/config -I/builddir/build/BUILD/neovim-0.3.0/src -I/usr/include -I/builddir/build/BUILD/neovim-0.3.0/build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.3.0/build/include
Compiled by mockbuild

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
Result of `:checkhealth`: [1.txt.gz](https://github.com/tpope/vim-fugitive/files/2247517/1.txt.gz)

**Comment by tpope** [comment]
Can you check `:echo b:git_dir` in the status window and see if it's
defined?

**Comment by tpope** [comment]
I see now the issue is you don't have a file open in the other window. Latest should fix it.

**Comment by unclechu** [comment]
Yep, now it's working, thanks!

**Comment by kenny-evitt** [comment]
More 'search terms':

> `fugitive: file does not belong to a Git repository`

In my case, 're-opening' files I had open *before* I installed the plugin with vim-plug with `:e %` resolved the issue.
