### ISSUE TITLE
get error when running ":Glog -- %" on macOS 10.13.6 (17G65)

### ISSUE THREAD

**Issue by wangxiexe** [tpope/vim-fugitive#1073]
Vim version is :  VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 22 2018 05:24:30)

git version 2.18.0

The error is : 

Error detected while processing function <SNR>53_Log[15]..<SNR>53_sub:
line    1:
E115: Missing quote: '),submatch(1))
E116: Invalid arguments for function s:Relative('),submatch(1))
E116: Invalid arguments for function fnamemodify(s:Relative('),submatch
(1))
E15: Invalid expression: fnamemodify(s:Relative('),submatch(1))

please take a look. Thanks.

**Comment by tpope** [comment]
Fixed, thanks!

**Comment by wangxiexe** [comment]
Thanks, verified.
