### ISSUE TITLE
Allow ggrep to use the word under vim cursor

### ISSUE THREAD

**Issue by srikard** [tpope/vim-fugitive#1074]
When view a file, if we want to git grep, it would be great, if we can choose the word under cursor.

**Comment by tpope** [comment]
You can do `:Ggrep <C-R><C-W>`.

**Comment by srikard** [comment]
Thanks works.. Did I miss it being documented in the Doc file?

**Comment by aschrab** [comment]
@srikard That's a general vim feature, not something fugitive specific. See `:help c_<C-R>_<C-W>`.
