### ISSUE TITLE
Using <nowait> on mapping in :Gstatus or a way to map to `-`

### ISSUE THREAD

**Issue by gauteh** [tpope/vim-fugitive#1076]
This is more a question than a request. I use `-` as a leader for a bunch of global mappings, my keyboard layout makes this pretty convenient and it would be a shame to not being able to do that. However, this causes unnecessary delays in Gstatus when toggling add/remove status. For the life of me I cannot figure out how to either unmap the global keybindings locally, or remap something to `-` without the delay.

As far as I can see the `<nowait>` option would have to be used in fugitives setup. Otherwise I would have to unmap/map my other bindings on BufEnter/BufLeave.

I realize suggesting new maps is a bit radical, at least a bit rash, so is there a way I could map this myself? Something like `A` to match the `P` mapping.

My best bet so far is:
```
let g:old_timeoutlen = &timeoutlen
au BufEnter */.git/index set timeoutlen=0
au BufLeave */.git/index exe 'set timeoutlen=' . g:old_timeoutlen
```

Thanks for an amazing plugin.

**Comment by tpope** [comment]
Best bet for custom `:Gstatus` maps is to fire on `FileType gitcommit` and check `&modifiable`.

**Comment by gauteh** [comment]
Great! Thanks!!
