### ISSUE TITLE
GBlame cannot create temp file

### ISSUE THREAD

**Issue by kyrashelwo** [tpope/vim-fugitive#1078]
When I run GBlame in a file from any git repository on my machine I get the error message:

'Can't open file "C:\Users\My Username\AppData\Local\VIXXXXX.tmp"' (translated since it is not displayed in English on my machine). My user directory contains a white space, like in this example path maybe this causes the problem. 

I run vim 8.1 (including patches 1-22) on Windows10 and the current origin/master of vim-fugitive (7b0aa580905673b57b1bfeab6a260b8193633cf2).

In earlier versions (about beginning of this year) GBlame worked fine for me, only after the pull to the newest version it fails.

**Comment by tpope** [comment]
Is that the full error or is there a line number and function name?

**Comment by bothyhead** [comment]
I'm getting the same error Tim.

"Error detected while processing function <SNR>65_Blame:"
"Line 43"
"E484: Can't open file c:\users\XYZ\AppDat\Local\Temp\VIBE8BF.tmp"

I'm also running Win 10 and vim 8.1 (with only patch 1)

**Comment by bothyhead** [comment]
If it is of any help, here is the result of a git bisect: 

-- snip --
8df073165a40d5299ca24f0c2fccf6401dff46fd is the first bad commit
commit 8df073165a40d5299ca24f0c2fccf6401dff46fd
Author: Tim Pope <code@tpope.net>
Date:   Fri Jul 13 16:06:42 2018 -0400

    Extract helper for robust tempname
-- snip --

**Comment by tpope** [comment]
Yes that helps a lot. Can you report back on the results of each of these commands?

```vim
:echo tempname()
:echo fnamemodify(tempname(), ':p:h')
:echo fnamemodify(fnamemodify(tempname(), ':h'), ':p')
```

I'm looking for which if any have Windows style `~1` short paths.

**Comment by bothyhead** [comment]
`:echo tempname()`
c:\users\bothyh~1\AppData\Local\Temp\VIxxx..tmp

`:echo fnamemodify(tempname(), ':p:h')`
c:\users\bothyh~1\AppData\Local\Temp

`:echo fnamemodify(fnamemodify(tempname(), ':h'), ':p')`
c:\users\bothyhead\AppData\Local\Temp

The first two do what you want.

**Comment by sleepyhollo** [comment]
I do not think this is a vim-fugitive issue and more of a gvim (or gvim installation issue). I am also having this problem with GVim. I tried moving my temp directory which doesnt help. However, these things work with a normal vim.

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 29 2018 21:10:00)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-551
```

**Comment by tpope** [comment]
Can you confirm the full error message, complete with whether or not it's a `~1` path?

**Comment by sleepyhollo** [comment]
The problem was my antivirus. It was quarantining some of the files GVim requires to do the things (like *vimrun.exe*). Now both vundle and vim-fugitive work. @tpope Thanks for replying. Appreciate all your work on making and maintaining these awesome things!
