### ISSUE TITLE
:Gbrowse does not open browser and only shows URL

### ISSUE THREAD

**Issue by AndrewRayCode** [tpope/vim-fugitive#108]
I'm not sure if this is a configuraiton issue with VIM or my browser, but if I type :Gbrowse it just shows the URL on the ruler line.

I tried `git config --global web.browser firefox` and also tried chrome but I get the same result. I just cloned and that didn't fix it.

**Comment by JasonGhent** [comment]
Supposing one cannot get the browser to open with GBlame, and the URL is not showing anywhere, is there any way to perhaps set

```
git config --global web.browser ff
git config --global browser.ff.cmd "open -a Firefox.app"
```

differently, where it would send the URL to `pbcopy` or output to the status bar below vim or something? I'm perfectly content to open the browser myself as long as I can grab the URL fugitive is trying to send to `git web--browse`

**Comment by tpope** [comment]
Well it won't work now that we're using netrw, but for posterity, yes, you could do something like that if you override a browser like `dillo` that doesn't take arguments.

**Comment by JarenGlover** [comment]
When I installed vim using `homebrew` these solved all my troubles ... doesn't seem to like the native vim version from 2010 ...thanks for help from @JamshedVesuna
