### ISSUE TITLE
allow user to disable MapJumps

### ISSUE THREAD

**Issue by kalbasit** [tpope/vim-fugitive#1080]
Hello,

This is a follow up on #761, I use the Colemak keyboard layout and the when in Git status I cannot move left (the key is `o` for me) because it gets overwritten by the [fugitive#MapJumps function](https://github.com/tpope/vim-fugitive/blob/bb2797d313f8b1cfd6ec6f8ee9fad69506909f92/autoload/fugitive.vim#L3399-L3429). Is it possible to disable these mappings? Maybe using the same `g:fugitive_no_maps`? How to define them once they get disabled? [`s:map`](https://github.com/tpope/vim-fugitive/commit/b1df5f1226676ae52380a214e0b13af1250951cd) is private so I would have to just `nnoremap` in my vimrc?

Thanks!

**Comment by tpope** [comment]
`s:map` is the [new mapping customization system](https://github.com/tpope/vim-fugitive/issues/761#issuecomment-384468073). It's only used for the universal maps like `y<C-G>` currently, but using it for *all* maps would enable you to achieve your goals.

**Comment by kalbasit** [comment]
@tpope unless I disable the one in MapJumps, I won't be able to do that correct? Should I submit a PR that wraps MapJumps with `g:fugitive_no_maps`.

**Comment by tpope** [comment]
You should submit a PR that changes every `nnoremap` in `#MapJumps` to look like this:

https://github.com/tpope/vim-fugitive/blob/bb2797d313f8b1cfd6ec6f8ee9fad69506909f92/autoload/fugitive.vim#L3366-L3370

**Comment by tpope** [comment]
I went ahead and did this for some of the more important maps.  You need to tell Fugitive where to map instead with a dictionary of replacements for each mode:

```
let g:nremap = {'o': 'l'}
let g:xremap = {'o': 'l'}
let g:oremap = {'o': 'l'}
```

The idea is that this could live in a plugin like colemak.vim, solving it for all compliant plugins once and for all.

**Comment by albertnetymk** [comment]
There are still quite a few [mappings](https://github.com/tpope/vim-fugitive/blob/master/autoload/fugitive.vim#L5440) that are not using `s:map` framework. Any particular reason why?

**Comment by tpope** [comment]
Because I plan to make a singular `c` map and I have no desire to do a bunch of busywork in the meantime.

**Comment by runiq** [comment]
Would you accept a PR that ports the [remaining mappings](https://github.com/tpope/vim-fugitive/blob/4a24804adc25f915520c57a5504c45ca70e590e6/autoload/fugitive.vim#L5962-L6028)?

**Comment by tpope** [comment]
Given that the singular map is still a ways away, I suppose I’ll allow it.

**Comment by runiq** [comment]
Done:  https://github.com/tpope/vim-fugitive/pull/1491
