### ISSUE TITLE
fugitive#StatusCfile: fallback to using includeexpr

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-fugitive#1084]
When using `gf` in a gitcommit buffer it will not fallback to using `includeexpr`.

My use case if using `gf` on something like `c/foo.txt` from the diff section of the buffer (using Git's `diff.mnemonicprefix = true`).

While this could be handled by fugitive already in a better way, I am using a custom includeexpr that handles this already (https://github.com/blueyed/vim-smartinclude), but fugitive does not use it.

Related commit/issue: https://github.com/tpope/vim-fugitive/commit/9835920a3c91236021fc8c88cc4157304e24356b / https://github.com/tpope/vim-fugitive/issues/744.

I've started to hack on this, beginning with `fugitive#Cfile`, but then thought it would be better to first discuss this, or rather let you come up with a better way already.

```diff
diff --git i/autoload/fugitive.vim w/autoload/fugitive.vim
index 27df8f6..e9cda5f 100644
--- i/autoload/fugitive.vim
+++ w/autoload/fugitive.vim
@@ -3689,15 +3689,27 @@ function! s:GF(mode) abort
   endif
 endfunction
 
+function! s:eval_includeexpr(cfile) abort
+  let cfile = a:cfile
+  if &includeexpr =~# '\<v:fname\>'
+    redir => out
+      silent verbose setlocal includeexpr?
+    redir END
+    let from_modeline = out =~# 'Last set from modeline' ? 1 : 0
+    if from_modeline
+      sandbox let cfile = eval(substitute(&includeexpr, '\C\<v:fname\>', '\=string(cfile)', 'g'))
+    else
+      let cfile = eval(substitute(&includeexpr, '\C\<v:fname\>', '\=string(cfile)', 'g'))
+    endif
+  endif
+  return cfile
+endfunction
+
 function! fugitive#Cfile() abort
   let pre = ''
   let results = s:cfile()
   if empty(results)
-    let cfile = expand('<cfile>')
-    if &includeexpr =~# '\<v:fname\>'
-      sandbox let cfile = eval(substitute(&includeexpr, '\C\<v:fname\>', '\=string(cfile)', 'g'))
-    endif
-    return cfile
+    return s:eval_includeexpr(expand('<cfile>'))
   elseif len(results) > 1
     let pre = '+' . join(map(results[1:-1], 'escape(v:val, " ")'), '\|') . ' '
   endif
```

(as you can see from this diff `:sandbox` should also only be used if it was set from a modeline)

**Comment by tpope** [comment]
I forgot about `git commit -v` when I split things into 2 functions. I think `fugitive#StatusCfile()` should fall back to `fugitive#Cfile()`, which if I'm not mistaken already handles the `c/` style prefixes.

If after that's done you really need that modeline sandbox thing I'll entertain it. What are you doing that can't be done in the sandbox?

**Comment by blueyed** [comment]
Sounds good!

> If after that's done you really need that modeline sandbox thing I'll entertain it. What are you doing that can't be done in the sandbox?

Nothing in particular AFAIK, but it's more a matter of completeness.
With vim-smartinclude I was first trying it with `:sandbox` always, and then without - but that's actually not what should be done when it comes from a modeline.
Feel free to keep it into the sandbox at first - especially given that the `redir`-check is probably not complete, i.e. for localized versions?!

**Comment by tpope** [comment]
Yeah the `redir` stuff is a huge can of worms I'd rather not open if possible.

**Comment by blueyed** [comment]
Understood, thanks!

I've noticed though that there is a ~1s delay when using it now.

Not sure if it is because of `:find`, but I think it would be good if `:find` could be skipped if it is coming from an includeexpr.  What do you think?

**Comment by tpope** [comment]
The primary purpose of `'includeexpr'` is generating the name of **include**d ('#include`/`import`/`requre` etc.) files, and the primary purpose of `'path'` is a list of directories to looks for included files in (that's why it defaults to `/usr/include`). If you don't want it to hunt through `'path'`, return an absolute or `./` relative path. That will work with the built-in `gf` too.

**Comment by tpope** [comment]
By the way, the whole idea behind the `<Plug><cfile>` thing is to decouple `gf` logic from file inclusion logic in an abstract, chainable way. Here's an example where eRuby chains to both Ruby and HTML (or whatever secondary type you're using):
https://github.com/vim-ruby/vim-ruby/blob/6959e10b399715418bcca90c4643da163fdb6330/ftplugin/eruby.vim#L74-L110

**Comment by tpope** [comment]
See also my explanation in the README at https://github.com/tpope/vim-apathy.
