### ISSUE TITLE
some windows blacked out after :Gpedit!

### ISSUE THREAD

**Issue by trinitum** [tpope/vim-fugitive#1086]
I updated the plugin today and found that when I'm running `:Gpedit!` with multiple windows open, some windows are blacked out. Here are the steps to reproduce the problem:
```
# assuming you have it installed there
$ cd ~/.vim/bundle/vim-fugitive/
$ vim README.markdown CONTRIBUTING.markdown -O2
# vim will open with those files in two windows
# then in vim run the following command
:Gpedit! show
# one window shows the output of `git show`, another is blank, <C-L> restores the display
```
I managed to find the commit that introduced the problem, it's 06b3da72, but can't really suggest any solution out of the head.

**Comment by trinitum** [comment]
actually, just after posting this I've found the way to make it work, I just had to replace `redraw` with `redraw!` as in the referenced PR

**Comment by lacygoill** [comment]
I have the same issue after executing `:Gstatus` and pressing `D` in the gitcommit buffer. The referenced PR fixes t

**Comment by trinitum** [comment]
The relevant code has been completely refactored, so I can't pinpoint the exact commit, but the issue has been fixed.
