### ISSUE TITLE
How to return to Gstatus after having done D

### ISSUE THREAD

**Issue by chris-fran** [tpope/vim-fugitive#1089]
I'm new to vim-fugitive. Awesome plugin, loving it more and more by the minute.

I'm trying this workflow where I:

1. `:Gstatus`: See all my changes
2. `C-n`:  select the first (next) change
3. `:Gdiff`: see what changed

Up to this point, I have 3 splits: 1 for `:Gstatus` and 2 for `:Gdiff`.  

4. `do`: to get changes
5. `C-wC-o`:  ????

Here is where the problem come, I want to return to `:Gstatus` but instead it takes me to the file I just `do`'d. 

I'm not sure if I misunderstood something in the documentation or if my workflow is just bad 😅, any help would be appreciated. Thanks a lot!

**Comment by magnocosta** [comment]
Hello @chris-fa,

I will try help you. You can return to `:Gstatus` with navigation commands in vim.

C-w +  Arrow (up, down, left and right)
or
C-w +  Arrow (k, j, h and l)

For example:

if you focus in diff you can use: `C-w + up` or `C-w + k`
if you focus in status you can use `C-w + down` or `C-w + j`
if you need diff mode you can use: `:q`

\o/ \o/ \o/

**Comment by tpope** [comment]
You can also invoke `:Gstatus` (or it's new alias `:G`) again to get back to the status window.
