### ISSUE TITLE
:Ggrep with ':/!*.md' pattern fails

### ISSUE THREAD

**Issue by justinmk** [tpope/vim-fugitive#1090]
Steps to reproduce:

    :Ggrep! foo -- ':/' ':/!*.md'
    fatal: Unimplemented pathspec magic '@' in ':/@*.md'

Bisected to fd83fcaf90023f2bd4b0193eee237b117b37c2be

git version 2.7.4

**Comment by justinmk** [comment]
Thanks, I appreciate that. 

Maybe the `^` alias is for recent git versions. In git 2.7.4 ,

    git grep -E 'foo' -- ':/' ':/^*.md'

returns matches in `*.md` files. Whereas the `!` variant does not.

**Comment by tpope** [comment]
Yeah not sure the exact version but it was definitely added later.
