### ISSUE TITLE
:Glog keyboard navigation

### ISSUE THREAD

**Issue by joshtriplett** [tpope/vim-fugitive#1091]
When viewing a commit with `:Glog`, I'd love to have shorter keyboard navigation than :cn[enter] and :cp[enter] to get to the next and previous commit in the log. Please consider providing keyboard navigation for revision buffers, similar to the keyboard navigation for status and blame buffers, which would allow (for instance) using `n` and either `b` or `p` for this.

**Comment by tpope** [comment]
I recommend unimpaired.vim for that. I think it would be weird to map `:cn` and `:cp` in Fugitive buffers when those are only sometimes relevant.

**Comment by joshtriplett** [comment]
Alright. Thanks again for fugitive!
