### ISSUE TITLE
No highlighting in GDiff buffer

### ISSUE THREAD

**Issue by xaizek** [tpope/vim-fugitive#1092]
After 33b7c1a5b71f5603055b7a56b7b1c478daae52a5 if version in the index contains a modeline that sets `'filetype'`, like this one:
```c
/* vim: filetype=c : */
```
There is no syntax highlighting.

If `noautocmd` is removed or `setlocal nomodeline` is added before
```vim
    silent noautocmd edit!
```
the highlighting is there. Not really sure how to explain this weird behaviour, but it seems that suppressing auto-commands in the presence of modeline prevents Vim from enabling highlighting.

**Comment by tpope** [comment]
Best I can tell this is a misfeature of `doautocmd`. If you call `doautocmd BufReadPost` it sets `'filetype'` but doesn't cascade to `'syntax'`. Pushing a workaround.

**Comment by xaizek** [comment]
Works fine now, thanks.
