### ISSUE TITLE
:Gstatus can't show individual files in an untracked directory

### ISSUE THREAD

**Issue by joshtriplett** [tpope/vim-fugitive#1093]
`git status`, and `:Gstatus`, typically just show a single entry for an untracked directory, not all the individual files in it. That helps when a huge number of untracked files exist, and makes sense as the default. But when trying to add and commit an untracked file (or, alternatively, add it to `.gitignore`), I'd like to see the individual files.

With `git status`, I can use `git status untrackeddir` to see those files. But `:Gstatus` doesn't take an argument.

Could you please provide some means of drilling down into a directory full of untracked files and seeing the individual files?

**Comment by tpope** [comment]
In the long run I plan to rip out the terribly convoluted `git status` output wrapper and replace it with something custom. That will open up more possibilities. Until then I'm not engaging in any more turd polishing.

As a possible workaround, you can press `<CR>` to navigate via netrw and stage files individually with `:Gwrite`. Or you can turn on `status.showUntrackedFiles=all` globally if that suits you better.
