### ISSUE TITLE
:Gvdiff No Longer Showing Three Panel Merge

### ISSUE THREAD

**Issue by jherdman** [tpope/vim-fugitive#1094]
I'm using a combo of NeoVim 0.3, and Fugitive. I've been using Fugitive's :Gvdiff command as my mergetool for quite some time, which I've configured as so:

```
# gitconfig
[mergetool "fugitive"]
  cmd = nvim -f -c \"Gvdiff\" \"$MERGED\"
[merge]
  tool = fugitive
```

I recently updated my copy of vim-fugitive, and now merge conflicts look like this:

![screenshot from 2018-09-10 11-56-41](https://user-images.githubusercontent.com/3300/45309210-37bc3780-b4f1-11e8-9018-63d26d83df62.png)

This is the result of doing `git mergetool` or using :Gvdiff on a given file that has a merge conflict.

My Vim config is here: https://github.com/jherdman/dotfiles/blob/master/config/nvim/init.vim

I've tried stripping it down to its bare minimum and the problem persists.

I'm using Git 1.9.1.

**Comment by tpope** [comment]
What are the buffer names?

**Comment by jherdman** [comment]
Here's a sample:

![screenshot from 2018-09-10 12-57-41](https://user-images.githubusercontent.com/3300/45312191-650ce380-b4f9-11e8-9942-e46beb0a7c2d.png)

**Comment by tpope** [comment]
Those look correct.

* Try manually reloading the buffers with `:e` and see if they remain empty. Also see if it outputs an error or status message.
* Try `git cat-file blob :2:config/ember-try.js` and make sure there really is content in the index.

**Comment by jherdman** [comment]
My Vim-fu is a bit weak, so I had to use bufexplorer to open the fugitive buffers, but they were empty with no errors or status message.

`git cat-file blob :2:config/ember-try.js`, for example, does have content.

**Comment by tpope** [comment]
So `:Gdiff` works in a regular buffer, correct? It's just conflicts giving you trouble? I'm struggling to think of a reason that would happen.

I think you're gonna have to do a `git bisect` to find which commit broke it.

**Comment by jherdman** [comment]
No, `:Gdiff` isn't working either.

**Comment by tpope** [comment]
Well then lots could be going wrong. What's your `'shell'`?

**Comment by jherdman** [comment]
If you're asking what shell I'm using in my terminal it's ZSH.

**Comment by tpope** [comment]
I'm asking what shell you're using in Vim, which is the same unless you overrode it. Check `:set shell? shellcmdflag?`.

**Comment by jherdman** [comment]
Ah, apologies. I learned something new today.

```
shell=/bin/zsh
shellcmdflag=-c
```

**Comment by tpope** [comment]
That should be fine.

If you're not comfortable digging into the plugin itself, I still think using `git bisect` to find the commit that broke it is going to be your best bet.

**Comment by jherdman** [comment]
I'll give it a try and see what happens. Many thanks for the help so far!

**Comment by ChromeHearts** [comment]
@tpope I think there is an issue with the fugitive codes at master.  I had similar issue after upgrading to the latest master codes.  Gdiff would show empty on the remote buffer side.

@jherdman 
I downgraded my fugitive to v2.4, then the issue was gone.

**Comment by tpope** [comment]
That narrows it down but not nearly enough, a lot has changed since 2.4.

**Comment by tpope** [comment]
I just found and fixed a bug with older Git versions. Try again on the latest.
