### ISSUE TITLE
P in Gblame opens an empty buffer on old vim

### ISSUE THREAD

**Issue by idbrii** [tpope/vim-fugitive#1095]
`P` in Gblame opens an empty buffer after 4bf30ce907f74cbf442b41f85c25967c397a3413 instead of reblaming at the parent commit (issue does not occur on 0fe0964).

My vim is old (what included by default on my ubuntu running on Linux Subsystem For Windows):

    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:43:18)
    Included patches: 1-52
    Extra patches: 8.0.0056

Does not occur on my more recent version of vim (8.1).

**Comment by tpope** [comment]
I just tried on my "old" machine and did find an issue, but it was due to the Git version rather than the Vim version. Can you try the latest and see if it's fixed?

**Comment by idbrii** [comment]
Can confirm it's fixed on 6cd8ff77f03b08ae133e35fabd87122a50231c36

Using git version 1.9.1.

Thanks!
