### ISSUE TITLE
less-based :Git commands unscrollable

### ISSUE THREAD

**Issue by moritzschaefer** [tpope/vim-fugitive#1098]
Reproduce: 

Go in a git repo and run
`:Git log` 

Expected:
The git log is loaded into vi buffer which is browsable as normal

Observed:
Only the initially viewable part of the git log is accessible. The rest is cut off and can't be reached (i.e. scrolling is not possible).

Is this a bug or expected? Is there a workaround already?

**Comment by justinmk** [comment]
If you're using Nvim, the `:terminal` buffer starts in normal-mode. Hit `i` to enter terminal-mode, then interact with `less` as usual. With Vim 8.1 `:terminal` it might be similar.

**Comment by tpope** [comment]
If you want to load it into a buffer, use `:Git!`. `:Git` is more for minimal output commands like `checkout` or `branch`.

It might make sense to use `:terminal` for GUI Vim.
