### ISSUE TITLE
Termguicolors makes :Gblame coloring completely random

### ISSUE THREAD

**Issue by rezadril** [tpope/vim-fugitive#1104]
As in title, it seems like the colors are chosen randomly, sometimes even no colors are shown.

Disabling termguicolors solves the issue, but also makes vim a pain in the arse to use.

**Comment by tpope** [comment]
The commits get individual colors. Is that what you're talking about?

**Comment by rezadril** [comment]
Yep, is that intentional? Sometimes (I'm using white theme) they are unreadable.

**Comment by tpope** [comment]
Intentional yes. I haven't run into readability issues myself but it also doesn't seem like a big deal as you don't really need to read the SHAs. What terminal are you using, and does it support 256 colors?

I'd be open to adding an option to disable the commit colors.

**Comment by tpope** [comment]
`let g:fugitive_dynamic_colors = 0`
