### ISSUE TITLE
Question: is  there any way to keep diffing a file to the first revision?

### ISSUE THREAD

**Issue by rjshrjndrn** [tpope/vim-fugitive#1108]
Hi,
Thank you for this AWESOME plugin. It's the inevitable in my workflow now.

I use `Gdiff ~` to check the diff b/w the last revision. But is there any way I can keep diffing till the first revision? something like `[q` for the quick fix. (I use unimpaired also.)

**Comment by tpope** [comment]
If you use `:Glog`, then `]q` will take you to the first revision. You'll have to invoke `:Gdiff` separately.

**Comment by rjshrjndrn** [comment]
Thank you for the response.
I know that solution, but my question was to keep on diffing against the current file with revisions, one by one. 
like when I'm in `:Glog` and `]q` will navigate me to older revisions one by one, is there any way to `:Gdiff and `do something` will diff the previous version, and keep on going till the first revision diffing one by one against current file.

**Comment by rjshrjndrn** [comment]
@tpope  gentle reminder
