### ISSUE TITLE
GVim and neovim(-qt) support difference in Windows (question)

### ISSUE THREAD

**Issue by habamax** [tpope/vim-fugitive#1111]
Hi, 

On GVim8 whenever I Gcommit, Glog I can see running/flashing cmd windows.
The same thing on neovim-qt runs smoothly, without any additional cmd windows.

Do I miss some crucial configuration or it should be like that?

Thx!

PS,
I have vim-dispatch installed.

**Comment by tpope** [comment]
That's just how GVim works on Windows. The part about neovim-qt is new to me.
