### ISSUE TITLE
Git time Machine feature for Fugitive

### ISSUE THREAD

**Issue by sidhartharya10** [tpope/vim-fugitive#1112]
I would love to see something similar to git-timemachine in emacs, in vim-fugitive.

**Comment by Axnyff** [comment]
What are the features you want?

If you just want to browse the revision of a file, `:Glog` does it perfectly.
It will feel your quickfix list with all the revision of your current file and update your buffer while you navigate your quickfix list

**Comment by sidhartharya10** [comment]
I see. Sorry i didn't investigate it properly. But it's the same feature.
