### ISSUE TITLE
Vim 7.4: E713: Cannot use empty key for Dictionary

### ISSUE THREAD

**Issue by matthewd** [tpope/vim-fugitive#1113]
Hey! 👋🏻

```
Error detected while processing function <SNR>81_ProjectionistDetect..FugitiveTreeForGitDir:
line    6:
E713: Cannot use empty key for Dictionary
```

Since a202238b5d5070d429260c47559585718de69930, I get the above on Vim 7.4 when using `:DiffGitCached` in a `gitcommit`.

I should really just upgrade the vim on my straggling boxen, but I figured it's probably worth a quick report anyway. :heart:

**Comment by tpope** [comment]
See if it still happens after upgrading Projectionist.

**Comment by tpope** [comment]
Do you have a `/.git` in the root of your file system?

**Comment by matthewd** [comment]
Nope, no `.git`s anywhere odd.

I've just noticed it's not only happening for `:DiffGitCached`, though... just opening `vim` [with no filename] gets the error too, as does using any non-git-controlled file. (Oops, I probably should've noticed that sooner.)

In the simple no-actual-filename case, the call is coming from `s:ProjectionistDetect`, where `file` is `'/home/matthew'` and `dir` is `''`. That all sounds like expected behaviour to me... I suspect either this conditional: https://github.com/tpope/vim-fugitive/blob/a202238b5d5070d429260c47559585718de69930/plugin/fugitive.vim#L105 or the caller: https://github.com/tpope/vim-fugitive/blob/a202238b5d5070d429260c47559585718de69930/plugin/fugitive.vim#L217-L221 just needs to consider that we might not actually have a git dir at all, in which case there's no worktree lookup to be done. (And while the needless lookup is harmless on 8.0+, the caching gets tripped up on 7.4's no-empty-keys "feature".)

**Comment by matthewd** [comment]
🙇 

Perfect, thanks so much for all you do! :heart:

**Comment by Magicrafter13** [comment]
I get a very similar error in Vim 7.4, however it's not caused by another plugin (as far as I can tell by the output).
tried `:Git`
```
Error detected while processing function fugitive#Command[2]..fugitive#Config:
line   37:
E713: Cannot use empty key for Dictionary
```
If I type `:Git ` and press tab, it's even worse.
```
Error detected while processing function fugitive#Complete[6]..<SNR>70_Aliases:
line    2:
E713: Cannot use empty key for Dictionary
Error detected while processing function fugitive#Complete:
line    6:
E715: Dictionary required
E745: Using a List as a Number
E116: Invalid arguments for function sort(s:Subcommands() + keys(s:Aliases(dir)))
E15: Invalid expression: sort(s:Subcommands() + keys(s:Aliases(dir)))
```
Checked issue #419 and ran `git config --get-regexp '^alias[.]'` as suggested, however it produced no output in my terminal.

Just so we're clear, there is no git repo in this directory yet, in fact I discovered this issue because I tried using vim-fugitive to run `Git init`...
