### ISSUE TITLE
Question/Bug: Dispatch is not working with Gpull

### ISSUE THREAD

**Issue by rjshrjndrn** [tpope/vim-fugitive#1114]
Hi,
Thank you for this awesome plugin. I use
Neovim
Dispatch
[Neovim-Dispatch adapter](https://github.com/radenling/vim-dispatch-neovim)
and Fugitvie.

Gpush is popping up a terminal and pushing the code, asynchronously. But Gpull is not doing that.. Am I doing anything wrong?

**Comment by tpope** [comment]
`:Gpull` is synchronous because I believe that having files change out from under you asynchronously would be a bad user experience. `:Gfetch`, which doesn't change files, is asynchronous.
