### ISSUE TITLE
git branch not always shown

### ISSUE THREAD

**Issue by Dea1993** [tpope/vim-fugitive#1116]
Description:
after upgrading vim-fugitive from version 2.3-1 to 2.4-2,
when i open source code file with vim 8.1.0470-1 (and vim-airline 0.9-1), git branch is not shown.
some files show git branch, but in others file (on the same repo, and on the same branch) git branch isn't shown (i've attached some screenshot, to prove this).
downgrading vim-fugitive to version 2.3-1, solve the problem

Additional info:
* vim-fugitive: 2.4-2
* vim: 8.1.0470-1
* vim-airline: 0.9-1

Steps to reproduce:
not every source code has this problem, but i can reproduce this, trying opening a file

![schermata da 2018-10-16 11-24-53](https://user-images.githubusercontent.com/5217483/47350493-47b16480-d6b6-11e8-9256-b124c4651cfc.png)
![schermata da 2018-10-16 11-24-31](https://user-images.githubusercontent.com/5217483/47350496-47b16480-d6b6-11e8-918a-ad6d7f1d74da.png)
![schermata da 2018-10-16 11-24-11](https://user-images.githubusercontent.com/5217483/47350497-4849fb00-d6b6-11e8-81e5-94cb46f1ef41.png)

**Comment by Dea1993** [comment]
this is my .vimrc
`https://hastebin.com/ujonajemas.sql`

**Comment by tpope** [comment]
Upgrade Airline.

**Comment by Dea1993** [comment]
if i disable:
`syntax on`
and 
`filetype indent on`
git branch is shown

**Comment by tpope** [comment]
Then a new version needs to be released. HEAD works.
