### ISSUE TITLE
`:Gread` in a file with a conflict causes error

### ISSUE THREAD

**Issue by teoljungberg** [tpope/vim-fugitive#1118]
While performing a `git rebase`, one might encounter a conflict. I would try to remove that conflict with `:Gread`, but the contents of the buffer is replaced with the following:

```
fatal: Not a valid object name :0:path/to/conflicted/file
```

**Comment by tpope** [comment]
It should probably echo an error rather than overwrite the buffer, but `:Gread` is expected to fail for exactly the same reason `git checkout conflicted-file` will fail. I'm not sure what "remove that conflict" would even mean.

**Comment by teoljungberg** [comment]
Sounds reasonable!
