### ISSUE TITLE
Show full diff with merge commits

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-fugitive#1121]
This would be useful with `:Gedit` etc for `commit` types, but also e.g. with the `K` (keywordprg) function in the git-blame buffer (for when `:Gblame --first-parent` is used (#1120)):

https://github.com/blueyed/vim-fugitive/blob/0ce9d915619562fd1eca6789a96d90db4c85c22a/autoload/fugitive.vim#L2955

From `git-log(1)`:

> -m
> This flag makes the merge commits show the full diff like regular commits; for
> each merge parent, a separate log entry and diff is generated. An exception is
> that only diff against the first parent is shown when --first-parent option is
> given; in that case, the output represents the changes the merge brought into
> the then-current branch.

**Comment by mroutis** [comment]
@blueyed , have you found a work around for this?

**Comment by tpope** [comment]
I've tentatively added `-m --first-parent` to the standard commit view. I had been considering the more involved change of showing all parents with `-m`, but I did some testing today and this routinely results in diffs of several megabytes on larger projects, which is not practical to display in Vim.

**Comment by mroutis** [comment]
Thanks, @tpope !
