### ISSUE TITLE
Looping with Gblame

### ISSUE THREAD

**Issue by lunchboxsushi** [tpope/vim-fugitive#1122]
Hi,

Currently I'm testing out Fugitive as a git wrapper, and I'm having a performance issue for most commands. As an example `Gblame`, then press enter on a file to open it. I will get a looping program that looks like the image below

![image](https://user-images.githubusercontent.com/10443153/48729201-081e5f80-ec05-11e8-9a2a-b474ae934a09.png)

It seems it keeps executing a command to read the blame commit and puts it back onto the screen, vim flashes a little bit during this time and moving around is really slow & laggy.

I installed latest today via Plug and don't have any other git tools aside from base installation of Git.

Running on Windows 10 build 1607

I'm still really new to Vim and unsure of how to debug this issue. If there are any logs / traces or additional information let me know and I'll be happy to supply.

**Comment by tpope** [comment]
Not sure I follow. You're saying it's repeatedly spawning a program when Vim is just sitting there idle? I don't know how Fugitive could be doing that.

**Comment by blueyed** [comment]
Sounds like every subshell/command opens a cmd.exe / whatever window?!

**Comment by tpope** [comment]
That's how Vim works on Windows, believe it or not.

**Comment by lunchboxsushi** [comment]
I'll try to disable all my plugins but `Fugitive` I wonder if something is interfering with it perhaps `NERDTree-git plugin`?

**Comment by lunchboxsushi** [comment]
Appears to work correctly without any issues when (ctrlp)[https://github.com/ctrlpvim/ctrlp.vim] is active it will keep re-opening some program and closing within milliseconds so I can't see the process, I will investigate further in their repo about this issue

**Comment by lunchboxsushi** [comment]
perhaps this related to https://github.com/tpope/vim-fugitive/issues/1012#issue-312145275 as he also had `ctrlp` in his plugins.

**Comment by tpope** [comment]
Yeah it might be something like NERDTree-git. I feel pretty confident at this point it's not Fugitive.

**Comment by lunchboxsushi** [comment]
Issue with ctrlp plugin
