### ISSUE TITLE
Git stash -p (feature request)

### ISSUE THREAD

**Issue by huangyingw** [tpope/vim-fugitive#1123]
Is it possible to implement the git stash -p(interactively) in fugitve ?
Like Gstatus, use the v-mode to select the diff chunk, and then press "-", then this chunk would be stashed, 
like answer "yes" in the Interactive stash process.

**Comment by tpope** [comment]
Official solution to this which I just pushed is to to stage the changes you don't want stashed, and use `czw` to invoke `git stash --keep-index`. If "changes you don't want" feels weird, try staging everything and selectively unstaging.

The problem with stashing the visual selection, other than it being harder to implement, is that a single visual selection is extremely limiting, constraining you to a single set of adjacent changes.
