### ISSUE TITLE
GPush/GPull is stuck when it's asking for a new server fingerprint for ssh

### ISSUE THREAD

**Issue by iamkarlson** [tpope/vim-fugitive#1125]
I'm pretty sure it's gonna be end by timeout or whatever but it's really confusing when you are pushing/pulling on the new machine.

**Comment by tpope** [comment]
Neovim?

**Comment by iamkarlson** [comment]
yep

**Comment by iamkarlson** [comment]
do you need any logs or other stuff?

**Comment by tpope** [comment]
Neovim breaks `:!`. You can work around it by installing dispatch.vim and vim-dispatch-neovim.
