### ISSUE TITLE
:Gpull fails

### ISSUE THREAD

**Issue by zumgruenenbaum** [tpope/vim-fugitive#1127]
Hi,
thanks for the awesome plugin!

I only have an issue with `:Gitpull`. After entering the command, vim freezes. However, after entering `:q` twice(!), I get:

`|| remote: HTTP Basic: Access denied`
`|| fatal: Authentication failed for 'remote repository'`

with remote repository being the (correct) GitLab repository.

In the shell, `git pull` asks for my Gitlab username and works fine.

Have I missed something?

**Comment by justinmk** [comment]
If you're using Neovim, see https://github.com/neovim/neovim/wiki/FAQ#-and-system-do-weird-things-with-interactive-processes

**Comment by zumgruenenbaum** [comment]
Thanks for your fast response.
No, I'm using vim-gnome.

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by zumgruenenbaum** [comment]
Any ideas? Have been searching through half the internet...

**Comment by justinmk** [comment]
The link I posted above mentions this: http://vimhelp.appspot.com/gui_x11.txt.html#gui-pty

**Comment by zumgruenenbaum** [comment]
Ok, I tried it with terminal vim and it worked. So I have to accept that the command doesn't work with gvim, I guess. Thanks for your help! :)
