### ISSUE TITLE
"Gblame" window width problems

### ISSUE THREAD

**Issue by phmarek** [tpope/vim-fugitive#1129]
Hi, the blame window behaves a bit strange.

Take a versioned file with multiple screen pages of content and run ":Gblame" on it, to get a left-hand split. Now resize the blame information to eg. 12 characters width (to only show the git hash, for example), and then scroll the main source window.

The left-hand "blame" window's horizontal position jumps wildly around, just from scrolling -- for special effects, try to use the mouse wheel.

I'd really like to have the blame window stay at the same horizontal position.

Tested with NVIM v0.3.1 and vim-fugitive=2.4-1 (Debian testing).

**Comment by tpope** [comment]
I can reproduce in Neovim but not regular Vim. Sounds to me like a Neovim bug with `'scrollbind'`.
