### ISSUE TITLE
Commit silently fails when git name and email are not set

### ISSUE THREAD

**Issue by bitc** [tpope/vim-fugitive#113]
If `user.name` and/or `user.email` are not set in the git config, then `git commit` can potentially fail, with this message:

```
$ git commit

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident  <me@myhost.(none)> not allowed
```

If this is the case, then the fugitive `:Gcommit` command (and also typing `C` from within `:Gstatus`) will also silently fail, printing only the text `fugitive:` in the vim status line.

An explanation or warning should be printed to the user instead of silently failing.

**Comment by vectorstorm** [comment]
I get this as well.  It happens reliably for me on Ubuntu 14.10, with git 2.1.0, and vim-nox 7.4.213.  Latest fugitive gives me this message:

> fugitive: 

As in the initial report from several years ago.

I presume that it's a slight difference in error message formatting.

(Regardless, this obviously isn't a high urgency fix;  just caused me a few minutes of confusion.)

**Comment by Tylerc230** [comment]
I can confirm that I am seeing this on git version 2.3.1

**Comment by clddev** [comment]
why it show that how to resolve it

**Comment by tpope** [comment]
Full output is now shown.

**Comment by rastogiakash** [comment]
> I also got this error when using github client for windows. When i firt created my account and downloaded the client, i had not entered an email address. I had to run this to get it to work:
> 
> git config --global user.email "[you@example.com](mailto:you@example.com)"

--------------------------------------------------------------------------------------------------------

thanks man it worked for me....

---------------------------------------------------------------------------------------------------------
