### ISSUE TITLE
:Gstatus buffer loses highlighting when staging/unstaging files

### ISSUE THREAD

**Issue by bezhermoso** [tpope/vim-fugitive#1130]
Hi,

`gitcommit` highlighting is active when the buffer is loaded on `:Gstatus`, but the highlighting seems to go away as soon as I stage/unstage files via `-`.

`:set {syntax,filetype}?` still reports `gitcommit`. However I have to execute `set syntax=gitcommit` to get the colors back.

I've disabled every other plugin + customizations & issue still persists.

On Neovim v0.3.1

**Comment by bezhermoso** [comment]
I narrowed it down to `edit!`

I have an `after/syntax/gitcommit.vim` that doesn't get called:

```vim
let s:commentchar = systemlist("git config --list 2>/dev/null | grep -i '^core.commentchar' | awk -F= '{print $2}'")

if !empty(s:commentchar)
  let s:git_comment_syntax = "syn match gitcommitComment \"^" . s:commentchar[0] . ".*\""
  exec s:git_comment_syntax
endif
```

Any suggestions how I can make it work?

**Comment by bezhermoso** [comment]
Made it work with:

```vim
autocmd BufNewFile,BufRead,BufEnter */.git/index setlocal filetype=gitcommit
```

**Comment by tpope** [comment]
Usually these sorts of bugs trace back to third party plugins or other funky autocommands. If you've ruled those out I'm not sure what it could be.

`BufEnter` fires for a million different things and isn't great for this, but I don't have a better workaround.
