### ISSUE TITLE
fugitive: No Gbrowse handler found for ...

### ISSUE THREAD

**Issue by eloehr** [tpope/vim-fugitive#1134]
Having trouble getting :Gbrowse to work.  With my actual domain replaced with 'mydomain', I see the following error:

fugitive: No Gbrowse handler found for 'git@git.mydomain.com:MyProject/myproject.git'

My config:

.vimrc (with my actual domain replaced with 'mydomain'):
let g:fugitive_gitlab_domains = ['https://git.mydomain.com']

I believe rhubarb is installed as 

   :echo g:fugitive_browse_handlers

 yields

   [function('rhubarb#FugitiveUrl')]

Ideas?

**Comment by tpope** [comment]
Rhubarb only handles GitHub. You need the one for GitLab.

**Comment by rlue** [comment]
In case anyone's confused: he's talking about [this one](https://github.com/shumphrey/fugitive-gitlab.vim).

**Comment by jclsn** [comment]
Maybe include the features from https://github.com/shumphrey/fugitive-gitlab.vim ?

**Comment by jclsn** [comment]
Oh you need both. Nevermind
