### ISSUE TITLE
Gstatus breaking

### ISSUE THREAD

**Issue by dhruvasagar** [tpope/vim-fugitive#1137]
I am on git version `2.20.1` and performing any operation within the `:Gstatus` window is breaking the the status window. As soon as you perform any action, formatting gets changed (just indentation of the files), and the window is no more of `gitcommit` filetype, it turns into `conf` filetype. Although further operations do work, the syntax highlighting is broken as a result and is a bit annoying.

Seems it is somewhat similar / related to #430

**Comment by tpope** [comment]
No I can reproduce it and it's baee3bbfe87784985a410924a2b3a0008d6b8424 that broke things.
