### ISSUE TITLE
Allow rewording commits in `Gstatus` window

### ISSUE THREAD

**Issue by teoljungberg** [tpope/vim-fugitive#1143]
With the new `:Gstatus` window we get a list of the local and unpushed commits, I'd like a way to reword one of those commits if I find a spelling or formatting error easily.

I thought `git commit --amend` and friends would work (`ce`, `cw`, `cwa`) relatively to the commit under the cursor. I could also see introducing a new mapping `cr` (commit reword?) would be beneficial.

Is this something we'd like to consider for the new status window to be able to do?

**Comment by tpope** [comment]
I don't really have a shortage of `:Gstatus` related ideas right now. What's your proposed implementation?

**Comment by teoljungberg** [comment]
In plain `git(1)` I'd do it as `git commit --amend -c SHA`. I'm guessing we could do the same as for `cf` in `:Gstatus` to fill in SHA if there is one under the cursor.

Which command would be preferred to do so with out of the ones we have? Or should we create a new  to not break any of the existing ones?

**Comment by tpope** [comment]
`git commit --amend -c SHA` amends the **most recent** commit to use the message from SHA. This is not what you requested nor is it useful behavior.

**Comment by teoljungberg** [comment]
I misread the man page, I'll tinker on this for a bit and open a PR when I figure it out.

**Comment by teoljungberg** [comment]
Looks like Magit doesn't have this behavior either, my guess is that it'll be resolved by having rebase'ing in place:

https://github.com/tpope/vim-fugitive/issues/797
