### ISSUE TITLE
Gstatus freezes vim only sometimes

### ISSUE THREAD

**Issue by deltaskelta** [tpope/vim-fugitive#1145]
As I mentioned in #1141 I am having some freezing issues with Gstatus. I am running typescript and I noticed that it happens particularly when I am in the Gstatus window and try to diff a javascript file. 

I realize this is probably an environment issue somewhere (IDK where to look yet) but I wanted to make and resolve this issue here in case anyone else comes searching with the same problem.

**Comment by tpope** [comment]
How far does it make it before it hangs? Does it open one of the two diff windows?

Does `<CR>` to open the file without diffing work?

**Comment by deltaskelta** [comment]
`<CR>` opens the file without error. It doe snot open any diff windows, the cursor goes to the status bar and then it gets stuck.

![screenshot 2018-12-31 01 46 48](https://user-images.githubusercontent.com/9424192/50549310-f5845500-0c9d-11e9-9fcc-9215e2fdfff0.png)

the only way I can get out of it without killing vim is to ctrl-c and I see this in the status bar...

![screenshot 2018-12-31 01 47 24](https://user-images.githubusercontent.com/9424192/50549315-18166e00-0c9e-11e9-847a-fb645747acf9.png)

**Comment by tpope** [comment]
Try disabling that BufKill plugin.

**Comment by deltaskelta** [comment]
still freezes, but I was able to narrow it down to this plugin https://github.com/jaawerth/neomake-local-eslint-first 

I don't use it, it just flew under my radar. removed :)
