### ISSUE TITLE
Gitcommit window doesn't replace Gstatus window

### ISSUE THREAD

**Issue by sudo-nice** [tpope/vim-fugitive#1146]
**This happens in Neovim, I didn't try it with Vim.**

Before the last changes, Gitcommit window used to replace Gstatus window, but now when I hit <kbd>cc</kbd> in Gstatus window, I get three windows open, instead of two:

![scr](https://i.imgur.com/Qw48cw0.png)

**Comment by tpope** [comment]
Deliberate change. With the new visual style I figured sharing the window no longer made sense.
