### ISSUE TITLE
Strange Split Behavior on Commit

### ISSUE THREAD

**Issue by amadeus** [tpope/vim-fugitive#1148]
This issue is best described in a video:

[video example](http://wtf.amadeus.wtf/monosnap/screencast_2019-01-01_10-57-00.mp4)

Essentially I am using `cc` from the `Gstatus` window to start writing a commit message. I get the commit split underneath `Gstatus`. But then as I type the commit message it remove the split.

I am using MacVim, not sure if this is an artifact from that?

A) Should `Gstatus` be removed when starting `cc` like from before? Seems like it should be that way - but that change might be intentional?
B) The delayed removal seems a bit arbitrary?

**Comment by tpope** [comment]
The change was deliberate. The thing that is arbitrarily closing the status window is your autocomplete plugin.

**Comment by amadeus** [comment]
P.S. Loving the updates! My concerns with unstaged vs untracked were quelled due to sorting!
