### ISSUE TITLE
:Gcommit doesn't show confirmation message when closed with mapping

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1149]
If I close `:Gcommit` buffer with a command like `:wq` or `:x` I see a commit confirmation message like:
```
[master e325e0e] Commit title
 1 file changed, 1 insertion(+), 1 deletion(-)
```
Depending on `cmdheight` I may even need to hit-enter to hide the message.

When closing the commit buffer with `ZZ` (or any other mapping) I don't see the confirmation. The message seem to flash line-by-line and only the last line or nothing at all is displayed in the end.

**Comment by tpope** [comment]
This is consistent with how `ZZ` itself (or its equivalent `:xit`) works compared to `:wq`. I don't think there's anything we can do about it.
