### ISSUE TITLE
Interactive rebase feedback

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1150]
I've been playing with the new (awesome) interactive rebase and have a few bugs and usability issues to report. It felt a bit early to create separate issues for each, let me know if you want that for some of them.

1. Commit names displayed in the todo list are unabbreviated. Related to that – since the file is naturally line-based maybe it makes sense to `setlocal nowrap` it? Maybe even in `vim-git`?
2. If todo buffer is unmodified and is closed with mapping (like `ZZ`) and not a command, interactive rebase progress is reported inline at the cursor position. This looks kinda ugly, maybe there is a way to work around this.
3. There is no message or any kind of visual confirmation when rebase completes successfully – only Vim's standard "git-rebase-todo written" message if there were any changes.  Something like `:Gcommit` confirmation message with text output from the original git rebase would be great.
4. Having rebase state displayed in `:Gstatus` is great. Maybe it also worth to have it in `vim-flagship`?
5. On conflict when the first file is auto-opened it doesn't have fugitive properly initialized, at least none of the commands are available. `:e %` fixes that.
6. With the current approach cleaning up rebase state when needed is a problem. In practice I encountered it in two scenarios. First is when I `:cq` out of `:Grebase -i` out of habit expecting it to cancel. Another is when I ended up with rebase-todo being the last window (of either Vim or even just a tab) and closed it – rebase didn't continue. In both cases the repo was left in initial rebase state which was rather unexpected. I don't see an easy solution to this. Maybe if we can definitely confirm that the current rebase state is our initial state, we can reliably `--abort` it where possible. But since it is impossible to cover all cases, maybe it's not worth it. The last window case seem to be very practical to me, I often move a window to a new tab to focus on it.
7. `rebase.missingCommitsCheck` git option is not respected. In particular, "error" value is ignored.
8. There seems to be no easy way to cancel the rebase once the buffer is open. The easiest way I think is emptying the buffer before closing. But it is consistent with `:Gcommit` and I don't have good ideas other than a separate command for that.

```
git 2.20.1
vim 8.1
```

**Comment by odnoletkov** [comment]
> > If todo buffer is unmodified and is closed with mapping (like `ZZ`) and not a command, interactive rebase progress is reported inline at the cursor position. This looks kinda ugly, maybe there is a way to work around this.
> 
> If this is happening it's too fast for me to see. You're sure it's not happening for `:x` too?

It is happening for `:x` and closing caused by any other commands, but since the cursor was on the command line area the rebase progress is also reported there on that line and actually looks rather nice.
 
> > On conflict when the first file is auto-opened it doesn't have fugitive properly initialized, at least none of the commands are available. `:e %` fixes that.
> 
> Not sure what that would be about. Try adding `nested` to the autocommands and see if that fixes it.

Adding `nested` to `fugitive_merge/BufEnter` fixed it.

> > With the current approach cleaning up rebase state when needed is a problem. In practice I encountered it in two scenarios. First is when I `:cq` out of `:Grebase -i` out of habit expecting it to cancel. Another is when I ended up with rebase-todo being the last window (of either Vim or even just a tab) and closed it – rebase didn't continue. In both cases the repo was left in initial rebase state which was rather unexpected. I don't see an easy solution to this. Maybe if we can definitely confirm that the current rebase state is our initial state, we can reliably `--abort` it where possible. But since it is impossible to cover all cases, maybe it's not worth it. The last window case seem to be very practical to me, I often move a window to a new tab to focus on it.
> 
> I was able to fix the separate tab issue. Not sure I understand what all else you're asking for.

Closing rebase todo as the last window of a separate tab now works right. But if it is the last window of the whole Vim instance, the Vim just closes and rebase doesn't happen, leaving repo in initial rebase state.

**Comment by odnoletkov** [comment]
> > `rebase.missingCommitsCheck` git option is not respected. In particular, "error" value is ignored.
> 
> Please do investigate.

Git performs rebase-todo validation only after running a sequencer initially (not even after `--edit-todo`):

https://github.com/git/git/blob/b21ebb671bb7dea8d342225f0d66c41f4e54d5ca/sequencer.c#L4626-L4716

There are checks for:
1. General format
2. Command names
3. Referenced commits exist
4. `rebase.missingCommitsCheck`

Since we bypass this flow we miss all these checks.

So to have that we can't just `--continue` when handling closing of the todo buffer for the initial rebase run.

I see two options:
1. Use `git rebase--interactive --check-todo-list`. But that's non-public API I guess.
2. Restart rebase with edited todo we have:
```
mv .git/rebase-merge/git-rebase-todo $tmp
git rebase --abort
git -c sequence.editor='mv $tmp .git/rebase-merget/git-rebase-todo' rebase -i
```

**Comment by tpope** [comment]
> > > If todo buffer is unmodified and is closed with mapping (like `ZZ`) and not a command, interactive rebase progress is reported inline at the cursor position. This looks kinda ugly, maybe there is a way to work around this.
> > 
> > 
> > If this is happening it's too fast for me to see. You're sure it's not happening for `:x` too?
> 
> It is happening for `:x` and closing caused by any other commands, but since the cursor was on the command line area the rebase progress is also reported there on that line and actually looks rather nice.

A well placed `:redraw` or `:echo` might fix it. Probably right before `:make`.

> > > With the current approach cleaning up rebase state when needed is a problem. In practice I encountered it in two scenarios. First is when I `:cq` out of `:Grebase -i` out of habit expecting it to cancel. Another is when I ended up with rebase-todo being the last window (of either Vim or even just a tab) and closed it – rebase didn't continue. In both cases the repo was left in initial rebase state which was rather unexpected. I don't see an easy solution to this. Maybe if we can definitely confirm that the current rebase state is our initial state, we can reliably `--abort` it where possible. But since it is impossible to cover all cases, maybe it's not worth it. The last window case seem to be very practical to me, I often move a window to a new tab to focus on it.
> > 
> > 
> > I was able to fix the separate tab issue. Not sure I understand what all else you're asking for.
> 
> Closing rebase todo as the last window of a separate tab now works right. But if it is the last window of the whole Vim instance, the Vim just closes and rebase doesn't happen, leaving repo in initial rebase state.

Calling `--abort` on exit might be sensible when appropriate. If there are queued up changes, I think leaving the rebase pending is the least worst option.


> > > `rebase.missingCommitsCheck` git option is not respected. In particular, "error" value is ignored.
> > 
> > 
> > Please do investigate.
> 
> Git performs rebase-todo validation only after running a sequencer initially (not even after `--edit-todo`):
> 
> https://github.com/git/git/blob/b21ebb671bb7dea8d342225f0d66c41f4e54d5ca/sequencer.c#L4626-L4716
> 
> There are checks for:
> 
> 1. General format
> 2. Command names
> 3. Referenced commits exist
> 4. `rebase.missingCommitsCheck`
> 
> If these errors are ignored the process fails and stops on the corresponding step, but the error message is rather general like 'error on line X'.
> 
> Since we bypass this flow we miss all these checks.
> 
> So to have that we can't just `--continue` when handling closing of the todo buffer for the initial rebase run.
> 
> I see two options:
> 
> 1. Use `git rebase--interactive --check-todo-list`. But that's non-public API I guess.
> 2. Restart rebase with edited todo we have:
> 
> ```
> mv .git/rebase-merge/git-rebase-todo $tmp
> git rebase --abort
> git -c sequence.editor='mv $tmp .git/rebase-merget/git-rebase-todo' rebase -i
> ```

I really don't want to do the abort dance for the aforementioned reasons about worktree churn. If `--check-todo-list` has been historically stable I think it would be acceptable. It would probably also not be unreasonable to roll our own checks. If we're collapsing and re-expanding SHAs, making sure none are missing shouldn't be too hard.

I am also considering adding functionality for manipulating the todo list directly to `:Gstatus`. If that works out, it would render half or more of this moot.
