### ISSUE TITLE
Setting diff.submodule config option breaks inline diffs in :Gstatus

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1151]
Here I'm toggling inline diffs with `diff.submodule = log`:

[![asciicast](https://asciinema.org/a/oIPgtmJ5NdZ0pYsnRqBPuKluy.svg)](https://asciinema.org/a/oIPgtmJ5NdZ0pYsnRqBPuKluy)

Toggling submodule path doesn't do anything and actual submodule output is included in the previous file. Also toggling on/off leaves the submodule part inline which makes me think there may be other problem with calculating file positions.

With non-default values the standard file header is missing from the diff output for submodules:
```diff
$ git -c diff.submodule=log diff
diff --git a/.config/git/config b/.config/git/config
index 5d651ae..a550772 100644
--- a/.config/git/config
+++ b/.config/git/config
@@ -23,6 +23,7 @@
 [commit]
        verbose = true
 [rebase]
+       some = change
        missingCommitsCheck = warn
        autoSquash = true
 [interactive]
Submodule .vim/pack/max/start/vim-fugitive 054ac50..d948ec3:
  > Support expanding inline diffs in :Gstatus
  > Fix :Gstatus toggle on Unstaged heading
  > Fix issue loading conflict buffers on :Grebase -i
  > Extract function for reloading individual :Gstatus
```

For default (short) value it works fine since the standard diff file header is present:
```diff
$ git -c diff.submodule=short diff
diff --git a/.config/git/config b/.config/git/config
index 5d651ae..a550772 100644
--- a/.config/git/config
+++ b/.config/git/config
@@ -23,6 +23,7 @@
 [commit]
        verbose = true
 [rebase]
+       some = change
        missingCommitsCheck = warn
        autoSquash = true
 [interactive]
diff --git a/.vim/pack/max/start/vim-fugitive b/.vim/pack/max/start/vim-fugitive
index 054ac50..d948ec3 160000
--- a/.vim/pack/max/start/vim-fugitive
+++ b/.vim/pack/max/start/vim-fugitive
@@ -1 +1 @@
-Subproject commit 054ac509758f18992b8357159e80c4d03daf1505
+Subproject commit d948ec3376d9f9806b1c35da758f901725f192ec
```

A quick fix could be forcing `--submodule=short` format for `git diff` or even better using `git diff-index --patch` which I believe is more stable and suitable for processing.

Supporting customized submodules output would be great too if possible. At least for the `log` format, not sure about `diff`. I think these are possible formats for the submodule header:
```
Submodule path/to/submodule FROM..TO:
Submodule path/to/submodule FROM..TO (rewind):
Submodule path/to/submodule FROM...TO:
```

**Comment by tpope** [comment]
I've started by tightening up the parser. I think forcing `short` would make sense because the end goal is staging hunks, and a log isn't a hunk.
