### ISSUE TITLE
Display Staged above Unstaged in :Gstatus

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1154]
\+ Matches `git status` order
\+ Makes you aware of existing index content before adding to it which is somewhat destructive operation
\+ In the most important 'stage and commit' flow when staging hunks/files they move to the top out of the way and you don't face them again later

\- Need to scroll through Staged section before can start staging (fix with map to jump between sections)?

**Comment by tpope** [comment]
See #1142. I intend to add maps to jump at some point, though I don't think that will be enough to change my mind.
