### ISSUE TITLE
:Gstatus very slow

### ISSUE THREAD

**Issue by amadeus** [tpope/vim-fugitive#1155]
I did a bisect and found that as of d948ec3376d9f9806b1c35da758f901725f192ec, `:Gstatus` is incredibly slow on one of my repos (it's a pretty large mono repo with a pretty big history).

A video example of the time it takes:

http://wtf.amadeus.wtf/monosnap/screencast_2019-01-03_17-37-33.mp4

**Comment by tpope** [comment]
Is `git diff` and or `git diff --cached` slow? We could mitigate the issue by only running those commands if the respective section is empty.

**Comment by amadeus** [comment]
They appear to be quite fast:

http://wtf.amadeus.wtf/monosnap/screencast_2019-01-03_17-53-31.mp4

**Comment by tpope** [comment]
Check `top` or something and figure out what's actually slow.

**Comment by amadeus** [comment]
Oh, interesting, just found a thing. If I do `:Gstatus` from a sub directory it's slow. If I do it from the root, it's fast again
