### ISSUE TITLE
:Gblame lose colors after executing :syntax on

### ISSUE THREAD

**Issue by mars90226** [tpope/vim-fugitive#1156]
`:Gblame` buffer loses colors after executing `:syntax on`. This means it loses colors after reloading .vimrc.

**Comment by tpope** [comment]
This can probably be fixed by extracting a `syntax/fugitiveblame.vim`. Though regardless I'd recommend a `if !exists('g:syntax_on')` guard because rebooting the syntax engine every time you reload your vimrc is just overkill.

**Comment by mars90226** [comment]
I'm currently using something similar: `if !exists('syntax_on')` in my .vimrc. I opened the issue because I think others may encounter this problem just like me. This problem may be mentioned in the FAQ section in README

**Comment by tpope** [comment]
`syntax/fugitiveblame.vim` added.
