### ISSUE TITLE
[feature request] populate cmd line with path under cursor and :Gcommit --amend --only

### ISSUE THREAD

**Issue by sim590** [tpope/vim-fugitive#1157]
As of right now, doing `cw` calls `:Gcommit --amend --only` with no arguments. It would be nice if, like ideas mentioned in #303 (what seems to be already in `master`), `cw` could put the file path under the cursor in the command line like so:

```
:Gcommit --amend --only some-file.cpp
```

Also, if one would use the visual line mode, multiple paths could be appended to the line. Wouldn't that be cool?

**Comment by tpope** [comment]
Since when does `git commit` take a hash argument?

**Comment by tpope** [comment]
So `cw` is the re**W**ord commit map. It's literally the only commit map I would say should never take filenames.

**Comment by sim590** [comment]
From [the doc](https://github.com/tpope/vim-fugitive/blob/master/doc/fugitive.txt#L46), it's for issuing `--amend --only` flags. I understand that you use it to reword, but git's documentation says it can be used to add only some paths (hence `--only` flag) to the commit.

I see two relevant use cases:

* Rewording as you suggest
* Adding some path to the last commit while not including what's already staged. That file path may be some file that you have forgotten to add in the last commit and you just realized that in the middle of staging multiple (parts of) files for the next commit.

If `cw` would be used with the cursor on a line not containing a path, then the usual *reword* behaviour would occur. Otherwise, other the behaviours I mentioned in my initial comment would occur.

What do you think?

**Comment by sim590** [comment]
If that's feasible, then another mapping could do that I guess.

Personally, I was always doing that manually (on the command line) since I didn't realize before that fugitive had `cw`. Today I saw `cw` and `cf` in the docs. Since `cf` had a similar behaviour to what I imagined, then I thought why now `cw`?

**Comment by tpope** [comment]
"Let me make sure I'm not accidentally on the same line as a filename before pressing the reword button" is terrible UX, man. Stick it on visual mode `ca` and `ce`. I guess you're fixating on `--only` but that's already the default if filenames are given.

**Comment by tpope** [comment]
I will be scrapping that terse mapping table in favor of some more helpful descriptions before the next release.

**Comment by sim590** [comment]
Oh, so if I understand correctly, you can already use `ca` and `ce` with visual mode and `--only` flag would be implied. Then, that's all fine. Indeed, a better description of the mappings and their usage would be great.

Thanks for clarification !

**Comment by tpope** [comment]
The visual mode maps aren't there yet, but I'll likely implement them before the next release.
