### ISSUE TITLE
Gstatus not being wiped out

### ISSUE THREAD

**Issue by sodapopcan** [tpope/vim-fugitive#1158]
`Gstatus`'s `bufhidden` is set to `delete` instead of `wipe`.  I'm not sure if this is intentional or not but it (or something, at least) is causing the `Gstatus` buffer to appear my jumplist.

As an aside: I'm loving the recent work you've been doing on fugitive—great quality of life improvements.  Thank you!

**Comment by tracyone** [comment]
same herer

**Comment by tpope** [comment]
Is this news? As far as I can remember it's always been `delete`.

**Comment by sodapopcan** [comment]
I just checked and, yes, it has always been `delete`—I shouldn't have suggested a cause without looking into it further.  My bad.

The issue stands, however, in that `Gstatus` is now showing up the jumplist when it never did before.  I reported it firstly to see if you even consider it a bug and, if so, if you knew off the bat what was up.

If it's not something that bothers you but you wouldn't mind being fixed, I'd be happy to dig into it.

**Comment by tpope** [comment]
I don't need you to dig into changing the word `delete` to `wipe`, but if you want to figure out why the buffer list changed, have at it. It might be related to no longer using a preview window. You can get the old behavior with `:Gstatus!`.

**Comment by sodapopcan** [comment]
I just meant "dig in" to see if such a change would have side effects elsewhere or anything like that—a bit of hyperbole for sure, but I wasn't trying to be a smartass or anything.

I failed to notice that the original status window was a preview window, so that makes sense that it wouldn't appear in the jumplist.  All in all, having `bufhidden=wipe` actually makes it behave like the `Gcommit` buffer which _does_ appear in the buffer list but is wiped when closed.

Again, if this behaviour doesn't bother you then that's cool, but I very much like the new status window but find it bothersome to hit it when using `<c-o>`/<c-i>`.

**Comment by tpope** [comment]
The reason for `:Gcommit` replacing the `:Gstatus` window was almost entirely to do with their visual similarity and the slick effect transitioning between them produced. Functionally, I think it was pretty much a wash, as closing the window was *usually* what you would want, but it only saves you a single `q` versus the larger annoyance when leaving it open was desired. And with the additional functionality of the new status buffer, "usually" is increasingly questionable.

**Comment by tpope** [comment]
@sodapopcan the `:Gstatus` window should have a separate jump list regardless of whether or not it's a preview window. Are you navigating to another file in that window, or something?

**Comment by sodapopcan** [comment]
Sorry to come back to this but I finally was able to reproduce what was happening:  It's being set to the alternate file after close.   So open any file, `:Gstatus<CR>q<c-^>`, you get taken to the status window.

I use a mapping so updating it to call`:keepalt Gstatus` works for me, but I thought I'd share.

**Comment by tpope** [comment]
More precisely, `:split` sets the alternate file. which is kind of strange, but that's Vim for you.

**Comment by bradwood** [comment]
> Sorry to come back to this but I finally was able to reproduce what was happening: It's being set to the alternate file after close. So open any file, `:Gstatus<CR>q<c-^>`, you get taken to the status window.
> 
> I use a mapping so updating it to call `:keepalt Gstatus` works for me, but I thought I'd share.

Using this also ensures that the status buffer does not show up when you toggle to the alternate buffer using `<c-^>` which I often do. This is probably obvious but I thought I'd mention it here anyway as this was the issue I was googling a solution for when I came across this thread.
