### ISSUE TITLE
Commit window has nomodifiable set 

### ISSUE THREAD

**Issue by sim590** [tpope/vim-fugitive#1160]
Sometimes (not always?), when doing `cc`, from the `:Gstatus` window, the commit window has `nomodifiable` set. I have to issue `:set modifiable` to start editing my commit message.

**Fugitive version**: 8c89c8d

**Vim version**

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec  8 2018 11:23:48)
Included patches: 1-570
```

**Comment by blueyed** [comment]
(I've also noticed this recently, when every new window was `nomodifiable`, but have not investigated back then)

**Comment by blueyed** [comment]
Ah, my issue was likely fixed in 07f4f8d.

**Comment by blueyed** [comment]
@sim590 
I assume it fixed your issue also.

**Comment by sim590** [comment]
It sounds like it. I'll test it out.

**Comment by tpope** [comment]
This definitely solves the every window issue and hopefully solves the commit message one too. That one's been driving me nuts.
