### ISSUE TITLE
Various issues after recent update

### ISSUE THREAD

**Issue by artemave** [tpope/vim-fugitive#1162]
Bundling all issues into one ticket in case they turn out to be caused by the same problem.

1. `:e README.md`:
![image](https://user-images.githubusercontent.com/23721/50777690-8cec3800-129c-11e9-80fe-4ad4c4aaca04.png)
1. `:w` that README.md:
![image](https://user-images.githubusercontent.com/23721/50778144-827e6e00-129d-11e9-9ff2-56eedc8ed879.png)
1. `:Gstatus`:
![image](https://user-images.githubusercontent.com/23721/50777722-a55c5280-129c-11e9-9765-b228da56e8b3.png)
1. `:Gblame`:
![image](https://user-images.githubusercontent.com/23721/50778273-d2f5cb80-129d-11e9-99b6-644a1730b0d0.png)

I've turned off all plugins except Vundle and Fugitive. I do have other config - https://github.com/artemave/myrcs/blob/master/.vimrc - but I can't see anything suspicious there.

`vim-fugitive` version:
```sh
git show HEAD
commit c448104332b095251a468765b4c58fa103b0b5fa
Author: Tim Pope <code@tpope.net>
Date:   Sun Jan 6 02:37:30 2019 -0500

    Fix :Gread deleting too much due to closed folds
```

Feels like I am missing something stupidly obvious here - please help!

Thanks
Artem

**Comment by tpope** [comment]
https://github.com/artemave/myrcs/blob/master/.vimrc#L75-L77

`fugitive#buffer().type()` is a quasi-internal API that I've removed. Delete that map and use the built-in `-` instead.

**Comment by artemave** [comment]
> Feels like I am missing something stupidly obvious here

I knew it! Thanks a lot :)
