### ISSUE TITLE
Gstatus, option to force 'split' rather than auto-choosing split/vsplit based on width

### ISSUE THREAD

**Issue by bluz71** [tpope/vim-fugitive#1163]
Hello,

I notice that [a4de0238bb](https://github.com/tpope/vim-fugitive/commit/a4de0238bb2d54475ac8ec38b70d4d0a860dbfd1) changed `Gstatus` layout quite radically.

That's mostly fine, I can get used to the flow. However, the auto split/vsplit for the`:Gstatus` window is a problem for my little retina Macbook (12inch). I really want to always force the `:Gstatus` window to be a full width split, not a vsplit since I really don't have enough width real-estate.

At the moment Fugitive appears to make the decision itself based on the width of the terminal, 160 characters? I use full-screen tmux, but I really only only have enough room for two splits, not three (three needed since I like side-by-side vdiffs not above-and-below sdiffs).

Is there an option to force always force a horizontal split for the status window no matter the terminal width? I can't seem to find such an option; apologies if it already exists.

If not, maybe `:Gsstatus` and `:Gvstatus` commands to allow users to force horizontal and vertical splits, similar to how `ds` and `dv` are provided to allow users to do horizontal or vertical diffs?

**Comment by sudo-nice** [comment]
`:rightbelow Gstatus` or `:botright Gstatus` could work for you.

**Comment by bluz71** [comment]
@sudo-nice,

Unfortunately no, both of those commands still create a vsplit when the terminal window is wide. The `vsplit` is happening inside `s:Status` function.

**Comment by bluz71** [comment]
Thanks Tim.

Note, I do think both horizontal and vertical splits are valid for `Gstatus` depending on the workstation being used. On a big 4K monitor the vertical split would be more space efficient.

Maybe down the road on option could be to allow users to specify their preferred status layout, something like:

```viml
let g:fugitive_layout = { "window": "botright 16split"  }
```
```viml
let g:fugitive_layout = { "window": "aboveleft 50vsplit"  }
```

Maybe, maybe not.

Nevertheless, thanks for update.

**Comment by blueyed** [comment]
Just a sidenote: if using a setting this might also default to something based on `&columns` / `&lines`.

**Comment by teoljungberg** [comment]
For those times where I want a vertical `:Gstatus` - I can always use `:vertical Gstatus` or `:vertical G` for shorts.

**Comment by bluz71** [comment]
@teoljungberg,

Outstanding tip, works perfect for those that want vertically split Git status.

If Tim is so inclined that would be worth adding to the `Gstatus` documentation.

**Comment by igorline** [comment]
> For those times where I want a vertical `:Gstatus` - I can always use `:vertical Gstatus` or `:vertical G` for shorts.

@tpope, please, add this to readme! At first I felt uncomfortable but now cannot get back!
Thanks for suggesting @teoljungberg

**Comment by traviswaelbro** [comment]
> For those times where I want a vertical `:Gstatus` - I can always use `:vertical Gstatus` or `:vertical G` for shorts.

Similar to this, you can use `:tab Gstatus` or `:tab G` to open it in a new, full screen tab.
