### ISSUE TITLE
After resolve rebase conflict, Grebase --continue report error

### ISSUE THREAD

**Issue by SolaWing** [tpope/vim-fugitive#1164]
Such as the title, Grebase --continue will echo
```
|| Please supply the message using either -m or -F option.
|| error: could not commit staged changes.
```

and can't success

it's fine using terminal's `git rebase --continue`

**Comment by tpope** [comment]
Known issue. You can `:Gcommit` to get past it.

**Comment by alextes** [comment]
Is there something we can do to help this issue along? Perhaps you can link or describe the known issue @tpope ?

**Comment by tpope** [comment]
Further discussion in #1139. It's a priority, I've just been busy.
