### ISSUE TITLE
:Gstatus parsing of CRLF warning

### ISSUE THREAD

**Issue by mihaicristiantanase** [tpope/vim-fugitive#1165]
Hi,

I found that **Gstatus** does not properly parse **git-status** when the CRLF warning is showing.
This is output of **git-status**:
<img width="609" alt="git-status" src="https://user-images.githubusercontent.com/7289591/50893481-9f37b480-1409-11e9-842e-1b797466772f.png">

And this is the output of **Gstatus**:
<img width="474" alt="fugitive-bad-parsing" src="https://user-images.githubusercontent.com/7289591/50893492-a52d9580-1409-11e9-8504-90226c6b4eb0.png">

**Comment by tpope** [comment]
Fixed in 75ca90739bf5959fc99a9e498f1a400796be5232.

**Comment by mihaicristiantanase** [comment]
I've updated and it works. Thanks!
