### ISSUE TITLE
Gstatus window not updated after pushing

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1166]
New status window doesn't auto-reload after pushing with the <kbd>-</kbd> map – it displays stale status. Need to <kbd>R</kbd> manually. Rebasing with the same map in Unpulled section works just fine – status is updated automatically.

**Comment by tpope** [comment]
Are you using dispatch.vim? What adapter?

**Comment by odnoletkov** [comment]
no dispatch.vim – doesn't update
dispatch.vim synchronous – doesn't update
dispatch.vim w/ tmux – updates

**Comment by odnoletkov** [comment]
5a1c8bb didn't fix it for me, same behavior
```
$ git submodule status *fug* *dis*
 9abd7cf09a5b00b3194a71f84e2911b280f30b1e .vim/pack/max/start/vim-dispatch (v1.6-11-g9abd7cf)
 b8a6fd204c6fffad573439b6200aadf0d256a730 .vim/pack/max/start/vim-fugitive (v2.5-71-gb8a6fd2)

$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jan  6 2019 22:28:49)
macOS version
Included patches: 1-700
```

**Comment by odnoletkov** [comment]
Updated to the latest vim-fugitive and vim-dispatch. 'no dispatch.vim' case is fixed – thanks! But synchronous adapter still doesn't work, so:

no dispatch.vim – updates
dispatch.vim synchronous – doesn't update
dispatch.vim w/ tmux – updates
```
 a795955b64a2eb15c1f05ae1434a89cc8ca16611 .vim/pack/max/start/vim-dispatch (v1.6-12-ga795955)
 ddc5e1a21a9981fd55933dacbb72857de2090bfe .vim/pack/max/start/vim-fugitive (v2.5-74-gddc5e1a)
```

**Comment by tpope** [comment]
Ugh, what a tangled mess of special cases. Latest *should* fix it.

**Comment by odnoletkov** [comment]
All cases work as expected in the latest – thanks!
