### ISSUE TITLE
Gstatus split above no matter what

### ISSUE THREAD

**Issue by mirko1593** [tpope/vim-fugitive#1169]
I set `set splitbelow` in my vimrc file, both `:split` and `:Gsplit` respect that. however, `:Gstatus` still put split window above, no matter what. Even with command line `:belowright Gstatus`.
any idea what's going wrong?

**Comment by tpope** [comment]
It defaults to `:topleft` now, which I *think* makes sense given its ephemeral nature. But `:belowright Gstatus` not working is a bug.

**Comment by coot** [comment]
I would disagree; If one is using `splitbelow` option and suddenly a window pop up in a wrong place is an unexpected behaviour.

Another feature that got lost, is that previously `:Gstatus` did not split window in half, but a fixed number of lines (like `:Gcommit`).

**Comment by tpope** [comment]
I am officially rescinding the impulsive `splitbelow` mandate.

The fixed number of lines wasn't a design decision but a consequence of using the preview window with `:pedit`, a built-in I hijacked more for "reuse the same window" practicalities than any sort of thoughtful design. As such I don't consider changes to it a regression in the strictest sense.

The big thing that has changed is that you can now expand the diff inline with `=`, which means it's no longer universally appropriate to minimize window size, and that we shouldn't personally impose a window size default, meaning the Vim default of 50-50 takes precedence.
