### ISSUE TITLE
Gstatus doesn't work like it used to, is confusing

### ISSUE THREAD

**Issue by noahlz** [tpope/vim-fugitive#1170]
On v2.4 the Gstatus output looked different.

```
  1 # On branch FIXBUG                                                                                                                  
  2 # Changes not staged for commit:                                                                                                          
  3 #   modified:   environments/prod.rb                                                                                                
  4 #                                                                                                                                         
  5 no changes added to commit     
```

Why did it change, what am i doing wrong?

**Comment by tpope** [comment]
The old version was as ugly as it was constraining, surprised that anyone would miss it. Anything in particular throwing you off about the new version?

**Comment by noahlz** [comment]
...it doesn't work at all?

I don't see a list of modified files, for example.

I just see `branch-name HEAD`

Do I need a specific version of git or vim for this to work? Old version works.

**Comment by noahlz** [comment]
The new version doesn't display the list of modified files.

It just has `branch-name HEAD`

do I need a minimum git version or something?

**Comment by tpope** [comment]
Literally just that one exact line? I don't know how that would even be possible.

**Comment by noahlz** [comment]
I might have a too-old version of git or vim?

**Comment by tpope** [comment]
Well `Head:` output would certainly be possible.

It's parsing `git status --porcelain --branch -z`. What does `git status --porcelain --branch` look like?
