### ISSUE TITLE
:Gstatus commits list in local branch

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1172]
New `:Gstatus` is a lot less useful when working in a local branch. With no upstream set it doesn't display any commits in the bottom. While pushing is meaningless in that scenario rebasing is still very useful so it would be great to have appropriate list of commits to work with.

One option I see is to show unpushed commits:
```
git rev-list HEAD --not --remotes
```

Another is to list commits unique to current branch:
```
git rev-list HEAD --not --exclude=<branch> --branches
```

While this problem is not unique to fugitive, in other interfaces like command line it is easier to fix by giving more arguments.

**Comment by odnoletkov** [comment]
Since `:Gstatus` currently doesn't use arguments it could take rev-list style args for limiting list of displayed commits, for example:
```
:G --not --remotes --since=1week master..
```
Without arguments it can default to current behaviour of `@{U}...`.

I see a couple of shady cases:
* If resulting list doesn't have `HEAD` at the top probably shouldn't display Unstaged/Staged area
* For open ranges like `:Gstatus master` probably need to limit number of commits listed

Other than that new commit/rebase/navigation maps are just crying to be applied in log-style view. Can't wait to finally ditch tig completely.

**Comment by tpope** [comment]
Have you considered setting your local branch to track something?

**Comment by odnoletkov** [comment]
Yes I currently work around by setting local branch to track either local
or remote master. It is a small inconvenience and in general I think
relying on upstream setup – rebase onto `..@{u}` and push to `@{u}..` – is
the right thing to do. But working with local branch seems to be an
important use case worth a special case to make `:G` much more useful out
of the box without additional setup.

**Comment by sim590** [comment]
@odnoletkov If that is of any interest to you, (I'm not sure if that can answer what you want to do), you could have mappings [like those][maps]. The first two are pretty straightforward. The second one will reestablish the upstream as `origin/branchname` if you have an origin upstream. May be they could be more fancy, but that's what I have right now. Again, I really don't know if I understood your concern so I'm sorry if I'm talking for nothing.

[maps]: https://github.com/sim590/dotfiles/blob/master/vim/ftplugin/fugitive.vim#L6-L8

**Comment by odnoletkov** [comment]
@sim590 thanks, I've been using utility similar to this to create and manage a "temporary upstream". If there is already an upstream for the branch it stores it in the temporary upstream's upstream so I guess it can be considered fancy :)

**Comment by somini** [comment]
> @odnoletkov If that is of any interest to you, (I'm not sure if that can answer what you want to do), you could have mappings [like those](https://github.com/sim590/dotfiles/blob/07c23cddcc4664c8348450a5359eb5e7ecf3aec3/vim/ftplugin/fugitive.vim#L6-L8).

Thanks for this. I hacked something based on this, but interactive, with tab completion.

```vim
command! -nargs=? -complete=custom,FugitiveCompleteRemoteBranches GitUpstream call s:vimrc_git_upstream(<f-args>)
function! FugitiveCompleteRemoteBranches(A, L, P) abort
	return fugitive#repo().git_chomp('rev-parse', '--symbolic', '--remotes')
endfunction
function! s:vimrc_git_upstream(...)
	if a:0
		let l:upstream = a:1
	else
		call inputsave()
		let l:upstream = input({
					\ 'prompt': 'Set Upstream To: ',
					\ 'completion': 'custom,FugitiveCompleteRemoteBranches',
					\ })
		call inputrestore()
		echo ' '
	endif
	if !empty(l:upstream)
		echo fugitive#repo().git_chomp_in_tree('branch', '-u', l:upstream)
		call fugitive#ReloadStatus()
	endif
endfunction
```

The next step would be to define the command only on Git repos, like the "official" `Gstatus` etc. That would require a Pull Request.

I'm thinking this could be enhanced to do a push setting the upstream, if the string you supply is not really a branch, but this seems overkill.

**Comment by tpope** [comment]
You can use a `User Fugitive` autocommand. Drop the interactive prompt and it's basically a one-liner:

```
autocmd User Fugitive command! -buffer -nargs=?
      \ -complete=custom,FugitiveCompleteRemoteBranches
      \ GitUpstream Git branch -u <args>
```

**Comment by somini** [comment]
It is indeed simpler to use the `Git` command, and the `User Fugitive` autocmd, but I like my interactive prompt, and that auto-completion function is not narrow enough.

Ended up with this:
https://gitlab.com/somini/dotnvim/blob/43514e950dc2bf35da3e3b20a359ee3fa7275dec/init.vim#L856-949

**Comment by tpope** [comment]
Instead of

```viml
echo fugitive#repo().git_chomp('reset', '--quiet', '--', FugitivePath(@%, ''))
```

try

```viml
echon system(FugitivePrepare('reset', '--quiet', '--', expand('%:p'))
```

`FugitivePrepare()` has way better argument handling than `git_chomp` (eliminating the awkward `FugitivePath()` call) and additionally repaces the `:cd` shenanigans in `git_chomp_in_tree` with the much cleaner `git -C`. I'm deprecating `git_chomp` and `git_chomp_in_tree` for that reason (but probably won't rip them out any time soon).

**Comment by somini** [comment]
I did those changes, and it appears the `chomp` in `git_chomp` matters.
Using a raw `system`, the whitespace before and after goes nuts. The `chomp` functions neatly cleanup that mess.

I had success with `systemlines(FugitivePrepare(...))[0]`, to add things to the status line.

**Comment by tpope** [comment]
All `git_chomp` does is `substitute(result, '\n$', '', '')`. `echon` should achieve the same result, if not, you can do that substitute by hand.

**Comment by tpope** [comment]
I've found `:Git branch -u origin` to be a pretty effective solution. I could indeed see providing a standard map for it, but I'll hold off on that till we have a bigger picture regarding branch management.

Note that `:G` takes arguments now, so solutions of that nature are a no-go.

**Comment by tpope** [comment]
Latest commit may be of interest.

**Comment by odnoletkov** [comment]
While we are at it, I found some other problems with the current workaround ('set upstream of the local branch to something'):

1. In active projects (where master is updated frequently) setting upstream for local branches to `origin/master` doesn't really work. You quickly get to 100+ 'unpulled' commits which a) fill most of the status buffer b) cause status slowness

2. Setting upstream to local `master` is very limited: a) relies on you not using/updating master much b) doesn't work well if you work on multiple local branches in parallel

3. I've learned that 'branchless' flow is actually a thing in Git. Checkout a version into a 'detached HEAD' state, add some commits and send them to PR/code review – don't really need a branch for any of that. This is actually well supported by the CLI – you only have to specify the base branch explicitly when rebasing such temporary unnamed branch. Obviously w/o a branch at all there is no way to set upstream to enable :Gstatus rebasing.

Magit resolves the visual part of (1) by folding all push/pull sections except 'Unmerged into <upstream>' by default. It also shows 'Recent commits' section for 'no upstream' and 'detached HEAD' cases – this helps somewhat but not ideal.

I don't have many new suggestions in addition to the OP to resolve all these problems. Having 'Recent commits' would definitely help. This can be further extended to allow configuration (Vim option or, better, git config) which git-rev-list args to use to fill this section.

**Comment by tpope** [comment]
> While we are at it, I found some other problems with the current workaround ('set upstream of the local branch to something'):

No longer a workaround, I'm promoting it to best practice.

> 1. In active projects (where master is updated frequently) setting upstream for local branches to `origin/master` doesn't really work. You quickly get to 100+ 'unpulled' commits which a) fill most of the status buffer b) cause status slowness

Slowness on loading the status? We're currently parsing the output of `git log` and then immediately reassembling it into something almost identical - this is as low as low hanging fruit can hang. There's a hard cap of 256 commits; surely acceptable performance for that is within reach?

> 3. I've learned that 'branchless' flow is actually a thing in Git. Checkout a version into a 'detached HEAD' state, add some commits and send them to PR/code review – don't really need a branch for any of that. This is actually well supported by the CLI – you only have to specify the base branch explicitly when rebasing such temporary unnamed branch. Obviously w/o a branch at all there is no way to set upstream to enable :Gstatus rebasing.

This seems like a good low effort workflow for one-and-done scenarios but if you're going to rebase maybe attach your head first? 🤔 

> Magit resolves the visual part of (1) by folding all push/pull sections except 'Unmerged into ' by default. It also shows 'Recent commits' section for 'no upstream' and 'detached HEAD' cases – this helps somewhat but not ideal.

I loathe the idea of "just grab a fistful of commits and show them" but will begrudgingly add it once every other option has been thoroughly vetted and eliminated.

**Comment by rgrinberg** [comment]
Here's another situation when the current fugitive summary is less than useful. When using the [official cli client](https://github.com/cli/cli) for github, one can usaully check out a PR with:

```
$ gh pr checkout #1234
```

This will set the push remote to the origin of the PR. So that pushing to it will update the PR directly.

I would find it very useful if fugitive's summary would display all the commits in the current branch.

**Comment by tpope** [comment]
What does "all the commits in the current branch" even mean? The entire history of the branch?

**Comment by rgrinberg** [comment]
Given the command `$ gh pr checkout 1234`, it would mean all the commits in PR `1234` - so `$base..HEAD`

**Comment by tpope** [comment]
And what the hell is `$base`?

**Comment by rgrinberg** [comment]
I had a look, and it seems like `gh` doesn't store that anywhere. The closest we have is `gh pr diff 1234` which will display the diff. By convention, I would assume that the base is usually `master` or `main`. So it would be nice to add a custom section that would show `master..HEAD` for example.
