### ISSUE TITLE
:Gstatus can't see diff of renamed file

### ISSUE THREAD

**Issue by WojciechKo** [tpope/vim-fugitive#1175]
Given we have a file that was renamed and it's content was slightly changed, then all of the changes was staged in git.
Then when we enter `:Gstatus` and press `a` on this file we can't the difference between old and new file. It would be awesome to be able to see output as we can see after `git diff --staged`

**Comment by somini** [comment]
This also affects mappings like `O` that open the file (should open the new file), `s` that stage the file (should stage both the old and the new).

**Comment by tpope** [comment]
This rabbit hole runs deep, I gave up for now on staging individual hunks. Let me know if you find any other oversights.
