### ISSUE TITLE
:Gstatus is super slow

### ISSUE THREAD

**Issue by sgottfried** [tpope/vim-fugitive#1176]
Fugitive has been really slow for me lately on the latest version.
`:Gstatus` takes about 10 seconds to load up.
I usually use it on NeoVim (0.3.4), but I also tried on Vim 8.1.280 and see the same results.

I've tried the following:
- Removing all other Vim plugins.
- Removing all of my Vimrc.

`git status` is almost instantaneous, so I don't think Git is the bottleneck.
Any other suggestions to getting this to work better? Is it an actual bug?

**Comment by blueyed** [comment]
Windows?  (forking is slow there AFAIK, i.e. many `system()` calls would slow it down)

**Comment by sgottfried** [comment]
@blueyed No, Mac.

**Comment by tpope** [comment]
In addition to `git status`, it's now making calls to `git config --list`, `git diff`, `git diff --cached`, `git log ..@{u}`, and `git log @{u}..`. Check the times on those.

**Comment by sgottfried** [comment]
Here are the times I got for all of those:

git status             0m0.072s
git config --list   0m0.618s
git diff                   0m1.938s
git diff --cached   0m0.015s
git log ..@{u}      0m0.012s
git log @{u}        0m0.012s

I don't see anything out of the ordinary, and I'm noticing the same behavior on Fugitive with a small repository (3 files) as I am with this larger one.

**Comment by sgottfried** [comment]
Looks like this is the culprit:
```
FUNCTION  fugitive#BufReadStatus()
Called 1 time
Total time:   7.032126
 Self time:   0.001309
```

I can provide more details if needed.

**Comment by tpope** [comment]
That function only has a self time of 1ms, it's not the root cause. You're going to have to dig deeper.

A previous performance issue was running `git --git-dir=... diff` in the current working directory rather than the repository root, resulting in a massive diff against the wrong directory. I'd expect something else vaguely in that category.

**Comment by sgottfried** [comment]
Ok, I sorted everything inside of this function by time and found these lines taking the longest

```
2.765254   0.000125     let b:fugitive_diff = { 'Staged': split(system(fugitive#Prepare('diff', '--no-ext-diff', '--no-prefix', '--cached')), "\n"), 'Unstaged': split(system(fugitive#Prepare('diff', '--no-ext-diff', '--no-prefix')), "\n")}
1.418862   0.000072     let output = split(system(fugitive#Prepare(cmd)), "\1")
1.388922   0.000035       let unpushed = s:QueryLog(push . '..' . head)
1.377905   0.000021       let unpulled = s:QueryLog(head . '..' . pull)
```
I assume that first one is running `git diff --no-ext-diff --no-prefix --cached` and then `git diff --no-ext-diff --no-prefix`, but that isn't taking too long.

I also almost always run Vim/NeoVim in the root directory of my project if that helps.

**Comment by tpope** [comment]
Looks like about 1.3 seconds of overhead per shell invocation. You can confirm by checking for delay when executing `:echo system('echo test')`.

My guess is something in your dot files is adding a tremendous amount of overhead to spawn a shell, possibly exacerbated by `:set shellcmdflag=-ic` -- a popular but problematic practice.

**Comment by sgottfried** [comment]
You were right!  It was something in my dotfiles.
`set shell=/bin/bash\ --login`.  I can just manually run that in cases where I need it.
Thanks for the help!

**Comment by cideM** [comment]
I still experience slow `Gstatus` both on my Macbook Pro and my Linux machine (Arch). It happens with and without `tmux` and in both `fish` and `bash`.

Below is from MacOS

```
FUNCTION  fugitive#BufReadStatus()
Called 1 time
Total time:   3.927840
 Self time:   0.001335
...
1   1.130618   0.000066    let output = split(system(fugitive#Prepare(cmd)), "\1")
1   0.572143   0.000028   let config = fugitive#Config()
1   0.553910   0.000020   let unpulled = s:QueryLog(head . '..' . pull)
1   0.551203   0.000018    let unpushed = s:QueryLog(push . '..' . head)
1   1.101052   0.000155     let b:fugitive_diff = { 'Staged': split(system(fugitive#Prepare('diff', '--no-ext-diff', '--no-prefix', '--cached')), "\n"), 'Unstaged': split(system(fugitive#Prepare('diff', '--no-ext-diff', '--no-prefix')), "\n")}
```

and linux
```
FUNCTION  fugitive#BufReadStatus()
Called 1 time
Total time:   2.343363
 Self time:   0.001187
    1   0.674351   0.000049     let output = split(system(fugitive#Prepare(cmd)), "\1")
    1   0.330782   0.000022     let config = fugitive#Config()
    1   0.330373   0.000016       let unpulled = s:QueryLog(head . '..' . pull)
    1   0.332766   0.000021       let unpushed = s:QueryLog(push . '..' . head)
    1   0.663102   0.000091     let b:fugitive_diff = { 'Staged': split(system(fugitive#Prepare('diff', '--no-ext-diff', '--no-prefix', '--cached')), "\n"), 'Unstaged': split(system(fugitive#Prepare('diff', '--no-ext-diff', '--no-prefix')), "\n")}
```

**Comment by tpope** [comment]
What's `:set shell? shellcmdflag?`?

**Comment by tpope** [comment]
For reference, easy way to test another shell is `env SHELL=/bin/bash vim`.

**Comment by PrestonKnopp** [comment]
I just fixed a similar issue with the tips from above. I had installed nvm (Node Version Manager) which is run for every shell to setup node and can take up to a couple seconds. After removing nvm, Gstatus and other shell stuff became super snappy again.

Posting this in case someone else runs into it.

**Comment by tpope** [comment]
Nvm should only slow things down if you've done one of the following:

* Activated it in a non-interactive shell config file (e.g., '.zshenv') instead of an interactive one (e.g., '.zshrc') as recommended.
* Added `-i` to `'shellcmdflag'`. People do this so that shell aliases work on `:!`, but it breaks all sorts of things in the process. Turn your aliases into shell scripts instead.

**Comment by PrestonKnopp** [comment]
Ah, I'm embarassed, I did `set shell=/bin/bash\ -l` and forgot after using a different computer. I'm going to take some time and cleanup my config files.

> Turn your aliases into shell scripts instead.

That's a great idea. I'm going to do that now.

Thank you for taking the time to reply and for the tip!
