### ISSUE TITLE
:Gstatus always uses 50 % of screen

### ISSUE THREAD

**Issue by RobertBuhren** [tpope/vim-fugitive#1177]
Hi,

due to the recent change in :Gstatus, this command now always occupies 50 % of the screen. Even if there is only a single unstaged file. Trying to see the diff of that file (using "D") is kinda painful as it only uses 50% of the screen. Is it possible to decrease the space used by :Gstatus ?
Regards,
Robert

**Comment by tpope** [comment]
With inline diffing on `=` keeping it tiny by default doesn't make sense anymore. You can force your own height with `:10Gstatus`.

**Comment by RobertBuhren** [comment]
Thanks ```:10Gstatus``` is what I was looking for.
