### ISSUE TITLE
Gstatus: Gwrite fails after dp on unstaged file: E382: Cannot write, 'buftype' option is set

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-fugitive#1181]
Given an untracked file, `dp` in `:Gstatus` will add it:

```
Unstaged (3)
? minimal.init.vim
…
```

=> `A minimal.init.vim`

`dp` on it again will open a diff buffer (`/tmp/nvimmoxgqj/2`), apparently using `:!hub diff --no-ext-diff minimal.init.vim` (visible in the command line).

But `:Gw` there fails:
```
Error detected while processing function <SNR>155_Write:                           
line   79:
E382: Cannot write, 'buftype' option is set
```

```
  buftype=nowrite                                                                  
        Last set from ~/.dotfiles/vim/plugged/vim-fugitive/autoload/fugitive.vim
```

It works on a modified file, where the diff gets opened on the first `dp`, where `buftype` is also `nowrite`.

**Comment by blueyed** [comment]
The problem is the following code: https://github.com/tpope/vim-fugitive/blob/552baf98b31c5f07eefdab5a67a20767c5b94547/autoload/fugitive.vim#L3034

Line 4 is not what it expects:
```
diff --git i/minimal.init.vim w/minimal.init.vim
new file mode 100644
index 0000000..5ded35f
--- /dev/null
+++ w/minimal.init.vim
```

**Comment by blueyed** [comment]
It does not appear to be controlled through some config setting (https://github.com/git/git/blob/1d4361b0f344188ab5eec6dcea01f61a3a3a1670/diff.c#L3353-L3360), and appears to be an older issue then likely.

**Comment by tpope** [comment]
Yep, looks like the function needs to be updated to account for a potential `new file mode` line.

**Comment by tpope** [comment]
This is actually the correct behavior because `git apply` won't actually won't on untracked files like this. `error: untracked: already exists in index`
