### ISSUE TITLE
restore foldtext when fugitive buffer is closed/not visible

### ISSUE THREAD

**Issue by habamax** [tpope/vim-fugitive#1182]
Is it possible to restore `foldtext` to the value it was set before fugitive made it `fugitive#Foldtext()`?

It hijacks my own foldtext when I reuse `Gstatus` window (like with `:e other-file`)

BTW, it fugitive#Foldtext looks no different to the default for me.

![image](https://user-images.githubusercontent.com/234774/51737615-1a51c980-209e-11e9-9638-853a19e2c0ff.png)

**Comment by tpope** [comment]
It's hard to restore without resorting to hacks because it's a window local option. Since it doesn't do much for the new `:Gstatus`, I'm okay to nix the setting for the time being.
