### ISSUE TITLE
GBlame and GDiff settings

### ISSUE THREAD

**Issue by amgoyal** [tpope/vim-fugitive#1183]
Is there any settings/options for making GBlame to open in horizontal split and not in vertical split. 

And is there any way i can get the list of files in a commit hash, my current workflow is
1. Glog --%
 2.  :cw to open a list of commits in quickfix window
 3.  Navigate to a commit, hit enter and its info as well affected files are shown
 4.  Focus on a file path
 press O (cap o) to open diff in new tab
 5.  :tabclose to just close the tab and get the previous state before the diff

In this workflow it will be very helpful if files in a commit are shown in one window , as summary or something like that, so that i don't have to search for the file diff line in a commit.

**Comment by tpope** [comment]
Horizontal splitting seems weird given the use of `'scrollbind'`, but since we're not using `!` for anything else I suppose we could put it there. I'll look into it.

You might appreciate `:set foldmethod=syntax` in the commit buffer. That will collapse each file's diff into one line.

**Comment by tpope** [comment]
The new way to do this is `:%Gblame`, which opens a new split that isn't coupled to the original buffer.
