### ISSUE TITLE
Feature Request: Make GStatus's window size and location more configurable.

### ISSUE THREAD

**Issue by bradwood** [tpope/vim-fugitive#1185]
Hi all,

I looked through the docs but I couldn't see a setting for this. It would be cool if one could set granular details about the `:G` window, including whether it's left or right, top or bottom, and the number of columns/rows the window should occupy when it is opened.

I know it currently follows the system-wide split setting, but I'd like to be able to set this differently for the status window.

Is this doable with the current version and, if not, can this feature be added please?

thanks

Brad

**Comment by romanorac** [comment]
I use this shortcut to open the split below, but I am not sure how to change the size.
`nnoremap <Leader>gs :belowright :Gstatus<CR>`

**Comment by tpope** [comment]
I'm inclined to recommend a map for the time being. Providing a configuration option would make it impossible to, for example, *ever* get a horizontal split if you've configured vertical.

**Comment by tpope** [comment]
I'm inclined to recommend a map for the time being. Providing a configuration option would make it impossible to, for example, *ever* get a horizontal split if you've configured vertical.

**Comment by bradwood** [comment]
cool @romanorac 's map will do it for me -- cheers
