### ISSUE TITLE
Gstatus suddenly can't use preview window.

### ISSUE THREAD

**Issue by hoclun-rigsep** [tpope/vim-fugitive#1193]
Hello, been using this for several months now in new job; you have my thanks.

Twice now it has happened that all the sudden Gstatus gives an error that "there is no preview window" and then loads in a new regular window. 

This error only appears in that repository; when I switch to a new one or a different one it behaves as normal. 

This is using vim 8.0 on Windows 7 Cygwin. I tried deleting viminfo and all views, and moving my vimrc, but nothing helped which isn't surprising because as I mentioned, it works fine in any other repo. 

I can't think of anything I was doing which could have precipitated this. Last time it happened I deleted .git and cloned again but I'd rather not have to keep doing that! Any ideas?

**Comment by hoclun-rigsep** [comment]
Additional info: :verbose Gstatus gives me:

Not found in runtime path: "indent/gitcommit.vim"

**Comment by tpope** [comment]
It no longer uses a preview window by default. (You can get one with `:Gstatus!` if you really want one.) That error only occurs on `<C-W>P` or `:wincmd P`. Are you calling one of those?

**Comment by hoclun-rigsep** [comment]
I was using fugitive from before those changes, and not calling either of those things. 

Now I have upgraded--nice changes to the status window! However Gstatus! still gives E441: There is no preview window, and this still only happens in the one repository .

**Comment by hoclun-rigsep** [comment]
What motivated the change away from preview window anyway?

**Comment by tpope** [comment]
Try `:pedit .git/index` and see if that loads the status in a preview window.

The change was motivated by the inline diffing, which means a tiny window no longer makes universal sense. It was always a terrible misapplication of the preview window anyways.

**Comment by hoclun-rigsep** [comment]
It does in a new/different repository. In this one it loads the status in a normal window.

**Comment by hoclun-rigsep** [comment]
Confirmed. :pedit doesn't work on a regular file either. I would just love to know what could be different across repositories that would cause this...

Thanks for the attention today and all your great work.

**Comment by tpope** [comment]
As first steps:

* Test from multiple filetypes
* Check for a project `vimrc`
* Try renaming the directory to see if some weird autocommand is triggering off of it
* Re-clone the repository
