### ISSUE TITLE
Feature Request: add :Gdiffrev ~n

### ISSUE THREAD

**Issue by lecheel** [tpope/vim-fugitive#1198]
Hi all, 
    does someone like me want to :Gdiff master~(n), unfortunately sometime file commit long time ago can not show on Gdiff with this n, for example like tig foo.cpp which will show delicate history with foo.cpp. is this workflow make sense please consider this feature Request

Thanks
Lechee

**Comment by tpope** [comment]
`:Gdiff master~3` already works. I am not sure what you are asking for.

**Comment by lecheel** [comment]
here is same question on stackoverflow  (https://stackoverflow.com/questions/16802629/diff-of-current-and-previous-version-using-vim-fugitive) and someone using revision hash with :Gdiff $hash
```vim
git log -1 --skip='2' --pretty=format:"%h" ' . @%```

**Comment by tpope** [comment]
It's tedious but you can basically achieve this by calling `:Gdiff !^` for each file in `:Glog`. `!` means "the commit you're currently looking at".

**Comment by lecheel** [comment]
Thanks tpope 
not actually same here is example 
![image](https://user-images.githubusercontent.com/148137/52675357-90d93d00-2f61-11e9-80ab-0eaadefce6a1.png)

**Comment by tpope** [comment]
Look at the buffer names (i.e., the `fugitive://` URLs) and see if you spot a difference.
