### ISSUE TITLE
Gstatus inline diff mappings

### ISSUE THREAD

**Issue by dhruvasagar** [tpope/vim-fugitive#1199]
Hi,

I think the mappings `<`, `>` should be reversed, i.e. `<` to hide and `>` to show. Let me know what you think / motivation behind the current mappings.

**Comment by tpope** [comment]
`<`, along with `(`, `[`, and `{`, is generally referred to as an open bracket, and it opens the diff. If you have a better mnemonic then do share.

**Comment by dhruvasagar** [comment]
Fair enough, I don't have better a mnemonic, my suggestion was purely from the standpoint that `>` reflects better with the direction of the expansion / showing. But I can get used to it.

**Comment by odnoletkov** [comment]
This direction choice felt weird for me too. Every UI with directional indicators I know use “right” for “expand”. Examples are macOS Finder, Xcode.
I guess it’s because lower level content is usually indented to the right and can extend beyond the parent item on the right but never on the left side. Diff content also likely extends beyond the path so visually appears to the right of the current position.

**Comment by tpope** [comment]
They use right to represent a closed section, and right closes :).

I use `=` exclusively anyways. I added `<` and `>` to be complete but as shifted keys they mostly don’t seem worth bothering with?

**Comment by odnoletkov** [comment]
I never use them either. Seems like they provide no extra value over <kbd>=</kbd> unlike <kbd>s</kbd>/<kbd>u</kbd> compared to <kbd>-</kbd>

**Comment by dhruvasagar** [comment]
I am making the transition to `=` as well, however I discovered `<` and `>` first so wanted to pointed this out since it felt a bit awkward.

**Comment by tpope** [comment]
The only reason I provided `<` and `>` is the niche use of collapsing/expanding multiple files in a mixed state, either in visual mode or acting on the section header.

**Comment by tpope** [comment]
I [ran a poll](https://twitter.com/tpope/status/1153818304567365633) and my initial decision lost by a wide margin. I've made peace with the inverse by thinking of the operations as "extend" and "retract" rather than "open" and "close".

**Comment by dhruvasagar** [comment]
Very interesting :)
