### ISSUE TITLE
:Gstatus lists untracked files listed in global gitignore

### ISSUE THREAD

**Issue by kiryph** [tpope/vim-fugitive#1201]
I have created a global gitignore file for `.DS_Store` files and similar
```
[core]
    excludesfile = ~/.config/git/ignore_global
```
```
~/.config/git
❯ cat ignore_global
.DS_Store
._.DS_Store
.Spotlight-V100
.*.swp
.*.swo
tags
*.pyc
*.orig
*~
.idea/*
ls-R
```
Running `$ git status` does not show untracked `.DS_Store` files in any repository.

However, the new `:Gstatus` lists them.

Why does this happen?

**Comment by tpope** [comment]
It's using `git status --porcelain` under the hood. Does that change things?

**Comment by kiryph** [comment]
Sorry to have bothered you and raised this issue:
it was a misconfiguration on my side: I had defined `$XDG_CONFIG_HOME` in my vimrc and changed the value to a temporary directory for testing purposes. Therefore, `git` did not consider my `~/.config/git/config`.
