### ISSUE TITLE
Inline Gstatus diff not available where there is a space in the path name

### ISSUE THREAD

**Issue by gbarta** [tpope/vim-fugitive#1202]
I am stuck with a project that contains spaces in some folder names.  I noticed that the new Gstatus inline diff will not be created for such files when pressing = or < or > in the Gstatus window.  Simply nothing happens. Filenames without spaces work correctly.

A bit of debugging suggests that it is because git diff adds a trailing \x9 tab character to the ```--- filename.txt``` line in diffs where the filename contains a space.  This prevents the line being understood by fugitive when it is processing the diff.

I searched for some explanation of this behaviour in git, but didn't find anything.

Also, I really like the inline diff functionality - thank you!

**Comment by tpope** [comment]
Strange. Luckily we don't need to understand it to work around it.
