### ISSUE TITLE
Gstatus doesn't differentiate dirty vs new commits in submodules

### ISSUE THREAD

**Issue by idbrii** [tpope/vim-fugitive#1204]
When looking at submodules, the new Gstatus doesn't differentiate between submodules with uncommitted changes (I need to go into the submodule and commit    >>stuff) and committed changes (I can just commit the submodule). I need to open the diff to be able to tell what I should do.

Example:

    Unstaged (8)
    M multi/vim/bundle/fugitive
    M multi/vim/bundle/work

    Unstaged (8)
    M multi/vim/bundle/fugitive
    @@ -1 +1 @@
    -Subproject commit 131a62d6d4ab354f8850fd87ce0498d366a45e20
    +Subproject commit 02c26619c4d42d874216943eb9ad69cff371a109
    M multi/vim/bundle/work
    @@ -1 +1 @@
    -Subproject commit 12119156c058a62f782438ca1706c18b81f9c9be
    +Subproject commit 683a4ca05c9718fd76e3b49dc29e0dd9a3aa8e11-dirty

It would be nice for dirty submodules to use `*` (I can't think of a better symbol and `D` is taken)  instead of `M` so I don't need to examine diffs.

Tested on 02c26619c4d42d874216943eb9ad69cff371a109.

**Comment by tpope** [comment]
How are these shown in `git status --short`? The manpage mentions `?` and a lowercase `m` which I would expect to bubble up.

**Comment by idbrii** [comment]
Gstatus displays quite different information from --short. Here's three different submodules (`codi` is a folder not added to git).

    $ git status 
    On branch local
    ...
    	modified:   multi/vim/bundle/fugitive (new commits)
    	modified:   multi/vim/bundle/ripple (untracked content)
    
    Untracked files:
      (use "git add <file>..." to include in what will be committed)
    
    	multi/vim/bundle/codi/


    $ git status --short
     M multi/vim/bundle/fugitive
     ? multi/vim/bundle/ripple
    ?? multi/vim/bundle/codi/

    :Gstatus
    Unstaged (3)
    M multi/vim/bundle/fugitive
    M multi/vim/bundle/ripple
    ? multi/vim/bundle/codi/

Gstatus only uses a single character, whereas git uses two. For some reason, it's also not using the same character for untracked content.

Tested on macOS, git version 2.15.1, MacVim 8.1.577, 02c26619c4d42d874216943eb9ad69cff371a109

**Comment by odnoletkov** [comment]
There is not enough information on submodules status in git status --porcelain=v1. There is more info in --porcelain=v2 but it is significantly different

**Comment by tpope** [comment]
Looks like `--porcelain=v2` was added in 2.11. We would need a backwards compatible fallback if we wanted to support that.

I'm going to change it to show dirty submodules as `?` in the unstaged (not untracked) section.  Hopefully that will be good enough.

**Comment by odnoletkov** [comment]
That didn't help – different submodules changes are still reported `M`. Docs say for --porcelain=v1 (compared to --short):

> Any submodule changes are reported as modified M instead of m or single ?.

Here is the full picture:
```
$ git status --short
m submodule/modified-content
M submodule/different-head
? submodule/untracked-files

$ git status --porcelain=v1
M submodule/modified-content
M submodule/different-head
M submodule/untracked-files

$ git status --porcelain=v2
1 .M S.M. 160000 160000 160000 <sha> <sha> submodule/modified-content
1 .M SC.. 160000 160000 160000 <sha> <sha> submodule/different-head
1 .M S..U 160000 160000 160000 <sha> <sha> submodule/untracked-files

$ git --version
git version 2.22.0
```

**Comment by tpope** [comment]
Dang, I keep forgetting `--short` != `--porcelain=v1`. I think we probably do need a `--porcelain=v2` implementation for newer versions of Git, preferably implemented by someone with actual submodules handy, because I clearly ain't got time for that.
