### ISSUE TITLE
Gblame changes working directory to repository "root"

### ISSUE THREAD

**Issue by scanny** [tpope/vim-fugitive#1205]
Thanks very much for this package Tim, I use it every day and love it :)

I recently started working on a project that has multiple packages in the same git repo. Like subdirs foo, bar, baz each have their own setup.py and are separately installable. I tend to work on one at a time and keep that as my `pwd`. When I run `:Gblame`, the working directory changes to the `..` directory which is the repository root; so it's like I also ran `:cd ..` each time I run `:Gblame`.

I could see why this would make sense for git interaction purposes and I never even noticed it on any of my other projects because they all are single-package repositories. But I was wondering if maybe there was a way to push the working dir and pop it back to what it was after the command or something like that.

I just do a `:cd foo` after each `:Gblame` and that works okay, I just notice that I pause for a second before a Gblame to ask myself if I want it bad enough :)

**Comment by tpope** [comment]
This was fixed in 50cf1b3bd110f8c25b3b89029630989af7f5faa5. Are you on the latest?

**Comment by scanny** [comment]
That did it! I should have checked that first, so sorry to bother you with that and thanks very much! :)
