### ISSUE TITLE
I want an option to run fugitive on PWD instead of current buffer path

### ISSUE THREAD

**Issue by kyoh86** [tpope/vim-fugitive#1206]
I'm using the vim

* With changing directory (:cd) to the roots of repositories for each project.
* Without argument. i.e. `$ vim`.

Then,

* I often call fugutive in the empty buffer (to operate "current project") and an error "Not an editor command" popped up.
* Opening a file which is in other project for reference, I call fugitive and am disappointed that it is not for "current project".
    * Git checkout
    * Gstatus
    * and so on...

So I want an option to run fugitive on PWD instead of  current buffer path.
I understand that is not major use-case, but I would appreciate if you could investigate with this matter.

**Comment by kyoh86** [comment]
I found #311.
It' so rad...!
I'm sorry for my stupid proposal.

**Comment by mezhaka** [comment]
@kyoh86 I was thinking about the same thing for a while.  I also first need to open some file to do Gstatus, but I don't get it why did you close it and I have read the #311, but I still don't understand how to use it. 
 Could you, perhaps, explain it to me?

**Comment by kyoh86** [comment]
@mezhaka 
FYI, My partial vimrc:

```
  function! FugitiveReDetect()
    unlet! b:git_dir
    call fugitive#detect(getcwd())
  endfunction

  augroup fugitive-ov
    au BufNew * call FugitiveReDetect()
    au BufNewFile * call FugitiveReDetect()
    au BufRead * call FugitiveReDetect()
    au CmdwinEnter * call FugitiveReDetect()
    au DirChanged * bufdo call FugitiveReDetect()
    au VimEnter * call FugitiveReDetect()
  augroup END
```

But sometimes, I find "Not an editor command" yet.
Maybe I should remove fugitive auto-commands, but I don't know how to do it.
