### ISSUE TITLE
Gstatus - fails on commit - E45: 'readonly' option is set (add ! to override)

### ISSUE THREAD

**Issue by spinlock99** [tpope/vim-fugitive#1207]
Expectation: fugitive will open a writeable buffer for git commit messages.

Behavior: fugitive opens a read-only buffer for git commit messages.

Steps to Recreate:

1. Stage Changes
2. Open - `:Gstatus`
3. Commit Staged Changed - `cc`
4. Edit Commit Message
5. Save Commit Message - `:w`

**Comment by alg** [comment]
I'm seeing this too. I thought I was going crazy.

Truth be told, recently half of other files started to open in RO mode, but that happened after I updated my plugins in bulk. Fugitive is among them. I verified that the COMMIT_EDITMSG is RW and if I open it directly with vim, it is opened as such.

I disabled Fugitive just now. Will see if any files open in RO mode now.

**Comment by tpope** [comment]
I can't reproduce this, but the latest commit might fix it.

**Comment by alg** [comment]
I confirm. After the upgrade to the latest this morning, it's gone on my side.

@tpope Could it possibly affect the opening of other files (via FZF for example) so that they are "randomly" opened in RO, you think?

**Comment by tpope** [comment]
For sure a possibility.

**Comment by spinlock99** [comment]
Thank you!

Upgrading fixed this issue for me too.

**Comment by kianjr** [comment]
I'm still having this issue with commits automatically opening in read only

**Comment by soumilgurjar** [comment]
I'm having this issue as well. I have the latest version of the fugitive plugin and vim version 8.2 installed with homebrew. And I have checked that the COMMIT_EDITMSG is RW. Any suggestions on what else I could try to fix this?
