### ISSUE TITLE
:Gstatus is not updated after :Gpush (Windows)

### ISSUE THREAD

**Issue by habamax** [tpope/vim-fugitive#1209]
OS: windows 10
Vim ver: 8.1.952

Both Gui and cmdline versions.

### Steps to reproduce:

1. open `:Gstatus`.
2. make a commit
3. `:Gpush`

In some previous versions of the plugin successfull `:Gpush` affected Gstatus window. Now I have to manually refresh Gstatus window:

![vim-fugitive-push](https://user-images.githubusercontent.com/234774/53003607-66dfb900-3440-11e9-8040-7d97c450ac84.gif)
 
On a debian though, Gstatus window is updated after `:Gpush`.

**Comment by habamax** [comment]
Well, if I remove vim-dispatch package -- then Gstatus window is refreshed after `:Gpush`.

**Comment by habamax** [comment]
Is there a way to not use `:Make` in `:Gpush` other than uninstalling vim-dispatch?

**Comment by tpope** [comment]
The status window doesn't autoreload on Windows because it can be slow and invasive there. Sounds like what you really want is an option to turn that on.

**Comment by habamax** [comment]
Well, thx :)

I actually asked if it is possible for Gpush to use regular :make instead of Distpatch :Make? Grebase for example updates Gstatus window without any problems...

With your changes I get Gstatus updated (with `let g:fugitive_autoreload_status = 1`). But it almost hangs my Gvim window as it tries to do smth more than just a single Gstatus refresh (which I usually do with `R`).

It constantly spawns and kills cmd windows with commands I cannot see...

PS

it took about 7 minuts of flashy windows to finish.

**Comment by habamax** [comment]
In my case, using regular `:make` in `s:Dispatch` solves the issue -- it works fast and updates Gstatus window fast, nothing hangs :)

**Comment by tpope** [comment]
Oh, the `FocusGained` callback is probably getting triggered repeatedly. Try the latest and see if that fixes it.

Your request for a "work around a bug" option has been reviewed and denied.

**Comment by habamax** [comment]
> Oh, the `FocusGained` callback is probably getting triggered repeatedly. Try the latest and see if that fixes it.
Yep it is way faster now,  but I have a feeling that s:AutoReloadStatus is called more than once.

> Your request for a "work around a bug" option has been reviewed and denied.
you're the boss

**Comment by habamax** [comment]
> BTW, "work around a bug" is twice as fast as the latest.

Nope, that is not true. It is about the same.

**Comment by tpope** [comment]
Dispatch only recently added support for `ShellCmdPost`, so it's probably making a duplicate call on both that and `QuickFixCmdPost c*file`. I'll be removing the latter in the near future.
