### ISSUE TITLE
Gmove stopped expanding # on <tab>

### ISSUE THREAD

**Issue by schnittchen** [tpope/vim-fugitive#1210]
Not sure this is really an issue on vim-fugitive. Maybe there is a better way to accomplish what I need, too...

Previously, I would enter `:Gmove %<tab>`, and vim would expand the % to the current buffer's path. This allowed me to edit both the name and the directory nesting of the file.

Now I need to know know the full target path or tab my way through from the top :(

**Comment by tpope** [comment]
I didn't realize the old completion did that, and I wouldn't be opposed to bringing back. However, there are lots of ways to accomplish what you want.

* `:Gmove %:h/basename`
* `:Grename basename`
* `:Gmove <C-R>%`

**Comment by schnittchen** [comment]
Thank you @tpope, in particular for mentioning `:Gmove <C-R%>`. This will be my go-to for a while.
