### ISSUE TITLE
Can't discard whole Staged/Unstaged sections

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1211]
Unlike other maps – <kbd>s</kbd>, <kbd>u</kbd> and <kbd>-</kbd> – discard map <kbd>X</kbd> does nothing for section headers. The relevant code just doesn't exist. Is this intentional?

**Comment by tpope** [comment]
Because of the way the undo message is displayed, it's limited to one file at a time. Honestly I wanted to limit such a dangerous feature to zero files at a time.
