### ISSUE TITLE
GBrowse from GBlame

### ISSUE THREAD

**Issue by tenderlove** [tpope/vim-fugitive#1214]
Hi,

When I'm viewing a blame, often I want to look at the commit on GitHub.  I'd like something like `GBrowse`, but it navigates to the commit that corresponds to the sha that's under my cursor.  I didn't see any shortcuts for doing this in the docs, so I made one:

```
augroup fugitive_ext
  autocmd!
  " Browse to the commit under my cursor
  autocmd FileType fugitiveblame nnoremap <buffer> <localleader>gb :execute ":Gbrowse " . expand("<cword>")<cr>
augroup END
```

I guess this is a "feature request" or a "did I not read the docs completely?" request.

Thanks!

**Comment by tenderlove** [comment]
Btw, the main reason I want to view the commit on GitHub is because I'd like to figure out what PR the commit goes with and look at the PR.  I'm working on a thing to do that too, but I thought I'd mention why I want to view the commit on GitHub rather than just look at the diff locally.

**Comment by tpope** [comment]
There's no direct way to do this without also temporarily navigating to the commit object. It would be a pretty reasonable behavior to put on `:.Gbrowse`, though, especially if paired with #1171. Let's centralize further discussion there.

**Comment by tpope** [comment]
This is now supported on 2 interfaces:

* `:.GBrowse` - this might switch to opening GitHub's blame view if support for that is ever implemented.
* `:GBrowse <cfile>` - this won't change to that, so it's the preferred interface if you're creating a map or otherwise wrapping it.
