### ISSUE TITLE
Inline diff does not work inside GStatus on Mac

### ISSUE THREAD

**Issue by talha131** [tpope/vim-fugitive#1217]
I have tried in both

1. NVIM v0.3.4
1. VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 26 2019 00:45:42)

On macOS 10.14.4 Beta.

My steps to reproduce are

1. Open a file that is in Git repository
1. `:GStatus`
1. `<C-n>` to jump to the first file
1. Press `=` 

Expected behavior is that an inline diff will open but nothing happens at all. The GStatus windows does not hang. I can move around and when I press `q` the window closes.

It's `=` that is not working.

I have tried commenting out `diffopt` in [my vimrc](https://github.com/talha131/dotfiles/blob/master/vim/vimrc), which is set to

```
set diffopt+=internal,algorithm:patience
```

But commenting it out did not fix the issue.

My shell is

```
if has('mac')
    set shell=/usr/local/bin/bash
    set shellcmdflag=-c
endif
```

**Comment by tpope** [comment]
It's probably not a Mac issue. Start by checking `:echo b:fugitive_diff` and see if it contains a normal looking diff.

**Comment by sambazley** [comment]
I'm having the same problem on Arch. `b:fugitive_diff` contains color codes. After disabling colors in my .gitconfig, `=` works.

**Comment by tpope** [comment]
What was the exact line in your config that broke it?

**Comment by sambazley** [comment]
```
[color]
	ui = always
```

**Comment by tpope** [comment]
Yeah don't use `always`. Use `auto` or `true`. Fugitive can override it but you're setting yourself up for other issues.

**Comment by talha131** [comment]
Thank you @tpope for the quick fix.

@sambazley Now that you mention it my gitconfig also has color set to `always`. Thank you for the tip.
