### ISSUE TITLE
Unknown function: <SNR>103_StatusDo

### ISSUE THREAD

**Issue by sQVe** [tpope/vim-fugitive#1218]
_Thank you for this awesome plugin!_ :pray: :beers:

The `a` keybinding is currently broken and outputs `Unknown function: <SNR>103_StatusDo`. The change that introduced this is: https://github.com/tpope/vim-fugitive/commit/f259fd5d6dfcae66264a0649dd757bce6c4ad148.

I'm unsure on what the intent was with changing the `a` keybinding so I'm not creating a PR for this.

**Comment by sQVe** [comment]
@tpope The new commit changed the binding of `a`. Before `a` had the same behavior as `=` where it now has the same behaviour as `-`.

Was this intended?

**Comment by tpope** [comment]
Yes, `a` is unofficial, undocumented, and subject to my whims.
