### ISSUE TITLE
Gpush: could not read Username for 'https://github.com': No such device or address

### ISSUE THREAD

**Issue by zubairakram** [tpope/vim-fugitive#1219]
Gpush command not working and showing error
```
|| fatal: could not read Username for 'https://github.com': No such device or address  
```
however ```git push``` command from terminal is working properly.
I'm using neovim ```NVIM v0.3.1``` on ubuntu 18.04

**Comment by t1meshift** [comment]
`NVIM v0.3.5` on Manjaro Linux, I have the same thing.

**Comment by tpope** [comment]
When you use it in the terminal, does it prompt for a username or password?

**Comment by lacygoill** [comment]
Yes, it does on xterm, st, and urxvt. The issue is specific to Nvim.

**Comment by tpope** [comment]
Discussed in #911. It's a Neovim limitation. At least they fixed it hanging Vim.

My recommended workaround is to use credential caching or ssh keys or any other mechanism to stop it from asking for the password every single time.

**Comment by lacygoill** [comment]
@tpope I will try the ssh keys mechanism as a workaround; thank you very much.

**Comment by tpope** [comment]
adba9c6345af58b31bcba8599b5bb162575d5755.
