### ISSUE TITLE
[Question] How to yank the commit hash of line under cursor ?

### ISSUE THREAD

**Issue by rjshrjndrn** [tpope/vim-fugitive#1220]
Hi, Thank you for this awesome plugin.
Have a small question.
How to copy the commit hash of a line under the cursor. It'll be very helpful while cherrypicking

Thanks.

**Comment by srasku** [comment]
You can do it using `:Gblame`. That shows the hash for every line.

**Comment by rjshrjndrn** [comment]
That is what I use. But for that, I have to use a couple of keystrokes. I was checking for single keystroke; something like `"y<C-G>`

**Comment by rjshrjndrn** [comment]
@tpope if this is the only way I shall close the ticket?

**Comment by tpope** [comment]
If you're looking to get the hash that appears in `:Gblame` without actually opening `:Gblame`, there's no direct way to do that, no.

**Comment by rjshrjndrn** [comment]
Thanks, @tpope @srasku

**Comment by idbrii** [comment]
You could map something like this (which also shows how non trivial it is):

```
:let @" = systemlist("git -C ".. shellescape(expand('%:p:h')) .." log --no-merges -n 1 -L ".. line(".") ..":" .. shellescape(resolve(expand("%:t"))))[0]->split()[1]
```
