### ISSUE TITLE
:Gstatus with rebase / merge conflicts

### ISSUE THREAD

**Issue by dhruvasagar** [tpope/vim-fugitive#1223]
I tried looking through the current issues to find something related but I did not.
The issue I have is, in case I do a `rebase (git pull --rebase)` or even a `merge` and there were conficts, it's not indicative of the fact that i'll need to run `git rebase --continue` after resolving the conflict. This is required because the Status window looks same whether it was a ebase conflict, a merge conflict or any other such as a cherry-pick conflict etc. In my understanding the command need to continue from a resolved state to finishing the rebase / merge / cherry-pick etc are different and so there needs to be some way of indicating that in the status window (older status window did not suffer from this since it is explicit about such things)

Kindly let me know if I am missing something obvious or if this is a valid issue.

**Comment by dhruvasagar** [comment]
@tpope any thoughts ?

**Comment by tpope** [comment]
I guess the first question is how do we determine what hints to show? I don't think parsing `git status` is feasible.

Note the status buffer does look different during a rebase, and for the other cases, I believe `git commit` is always adequate. (I didn't even realize `git cherry-pick --continue` was a thing till you drew this to my attention.)

**Comment by dhruvasagar** [comment]
`git rebase --continue` is always the better approach, especially since there may be multiple conflicts for multiple commits, `git commit` actually is dangerous and can leave you in a bad state where you end up loosing (more like they are deferenced) commits. Similar argument holds true for most other such conflicted states.

**Comment by tpope** [comment]
Emphasis on "for the other cases". If there's a `Rebasing` section you should call `git rebase --continue`.

**Comment by dhruvasagar** [comment]
I hadn't noticed any `Rebasing` section, will have a look and close this.

**Comment by dhruvasagar** [comment]
There's no `Rebasing` section within the `:Gstatus` window, so this is still something that needs to be addressed from fugitive's perspective.

**Comment by tpope** [comment]
I'm not sure how I'm supposed to respond when you tell me a feature I spent hours implementing and use regularly doesn't exist.

**Comment by dhruvasagar** [comment]
Well then my bad, will try updating the plugin maybe I don't have this change yet.
