### ISSUE TITLE
vimdiff when using Gblame to look at a commit

### ISSUE THREAD

**Issue by aste4** [tpope/vim-fugitive#1224]
Hello,

When looking at Gblame to see what lines were changed when - i select the a given commit (from the Gblame window that gets created) using **o** and gives me the diff using git diff. I have a hard time reading the diff in that format. Is it possible to somehow invoke a vimdiff on the selected commit and the previous one? 

i.e i use Gblame, and then look at commit 255. Then I would like to do a vimdiff between commit 254 and 255. Similar how the blame functionality work on github.

Is this possible with vim-fugitive?

Thank you

**Comment by tpope** [comment]
Press `<CR>` in the diff to open the file, then call `:Gdiff !^` to diff against the previous commit.

**Comment by KiranHappy** [comment]
> 
> 
> Press `<CR>` in the diff to open the file, then call `:Gdiff !^` to diff against the previous commit.
> 
> Edit: `dd` is now mapped to open the diff.

both solutions not working into vim 7.4.629

'dd' gives below error
E21: Cannot make changes, 'modifiable' is off

**Comment by tpope** [comment]
Press `<CR>` in the diff to open the file, then call `dd` to diff against the previous commit.
