### ISSUE TITLE
indistinguishable :Gdiff colors 

### ISSUE THREAD

**Issue by bam80** [tpope/vim-fugitive#1225]
Maybe it's not fugitive fault, but anyway - can't read text in diffs:
![image](https://user-images.githubusercontent.com/233979/53814603-f0c77000-3f70-11e9-9735-83d225dfbffc.png)
Reported to Vim: https://github.com/vim/vim/issues/4071

Any advise here?

**Comment by tpope** [comment]
It's not just you, the defaults are pretty unreadable. Your best bet is to install another color scheme.

**Comment by bam80** [comment]
Thanks. Any advise which ones is certainly readable at least? What do you use?
Actually, I like default colors(maybe a little too contrast but anyway), just that diffs in-acceptable..
Tried Solarized scheme but would like to see something else.

**Comment by bam80** [comment]
> It's not just you, the defaults are pretty unreadable. Your best bet is to install another color scheme.

Well, maybe mention it in the Readme then
