### ISSUE TITLE
Want to use s:command s:EditRunComplete outside of autoload/fugitive.vim

### ISSUE THREAD

**Issue by huangyingw** [tpope/vim-fugitive#1227]
Could u help to change the signature of these two functions ? 
Or, I change, and create a pull request to you ?

**Comment by tpope** [comment]
I consider `s:command()` an implementation detail and will be keeping it private. You should be able to achieve identical results with `autocmd User Fugitive command! -buffer ...`.

I do plan to open the completion functions up but I am still contemplating the API. Check back in a month. I recommend using `fugitive#Complete()` in the meantime, it has most of what you want.

**Comment by huangyingw** [comment]
I don't know how to use fugitive#Complete() 
This is my version of autoload/fugitive.vim 
https://github.com/huangyingw/vim-fugitive/blob/dev/autoload/fugitive.vim

I have lots of changes like these:

````
+call s:command("-bang -bar -nargs=* -complete=customlist,s:EditRunComplete Gdi :execute s:Gdi(<f-args>)")
+function! s:Gdi(...) abort
+    let worktree = Cd2Worktree()
+    let arg1 = (a:0 >= 1) ? a:1 : ''
+    let output = 'gdi.diff'
+
+    if expand('%:t') != 'index'
+        let output = expand('%:p') . '.diff'
+
+        if a:0 == 0
+            silent exec '!~/loadrc/gitrc/gdi.sh ' . '"HEAD" "' .  expand('%:p') . '" 2>&1 | tee ' . '"' .  output . '"'
+        else
+            let arg1 = (a:0 >= 1) ? a:1 : ''
+            silent exec '!~/loadrc/gitrc/gdi.sh ' . '"' .  arg1 . '" "' .  expand('%:p') . '" 2>&1 | tee ' . '"' .  output . '"'
+        endif
+    else
+        let arg1 = (a:0 >= 1) ? a:1 : ''
+        silent exec '!~/loadrc/gitrc/gdi.sh ' . '"' .  arg1 . '" 2>&1 | tee ' . '"' .  output . '"'
+    endif
+
+    if bufexists(output)
+        exe "bd!" . output
+    endif
+
+    call OpenOrSwitch(output, 'vs')
+    call s:DiffClean()
+endfunction
````

Everytime, you have updates, I have to do very carefully merge :)
My plan is to move my customization into a seperate file.
What's your suggestion to do this?
