### ISSUE TITLE
. command populates only part of the file

### ISSUE THREAD

**Issue by bam80** [tpope/vim-fugitive#1228]
>.                       Start a : command line with the file under the cursor prepopulated.

So I'm on fist file in the commit window.
Pressing . populates only it's git repo part to the command line:
![image](https://user-images.githubusercontent.com/233979/54078032-446bed80-42d2-11e9-9ca5-e2ff30a0e945.png)

**Comment by tpope** [comment]
I really only intended "under the cursor" to apply to the status buffer. At first glance this seems like a reasonable enhancement, though I wouldn't count on me personally implementing it any time soon. What sort of use cases did you have in mind?

**Comment by bam80** [comment]
It was about opening the working dir version of the file.
But now I found the same could be done by :Gread, after opening it's commit's version from the hunk.
Only cursor resets that way, unfortunately.

**Comment by tpope** [comment]
This will happen once I change commit buffers to be of `fugitive` file type.
