### ISSUE TITLE
first and consequences quickfix window results are opening in different windows

### ISSUE THREAD

**Issue by bam80** [tpope/vim-fugitive#1229]
It's not Fugitive-specific, but it would be fine to solve it somehow:

1. Let's say I have two horisontal windows, with upper one is active.
2. :Glog command populates the upper active window with the first quickfix's result(commit is loaded there):
![image](https://user-images.githubusercontent.com/233979/54090593-d5040580-4386-11e9-89c5-1b22d43a3916.png)
3. Now I go to the quickfix window and press Enter on any other result (e.g., second one).
IT IS OPENED IN OTHER WINDOW THAN THE FIRST ONE, SWITCHING THE BUFFER THERE ALSO:
![image](https://user-images.githubusercontent.com/233979/54090654-66737780-4387-11e9-9908-52f0117dfd6a.png)

It would be convenient to load all the results in the same window the first result was loaded.
Is there a way to achieve that?

The same common problem was already discussed but still no solution:
https://stackoverflow.com/questions/25069247/how-can-i-get-quickfix-to-open-results-in-the-previously-focused-window

**Comment by tpope** [comment]
I believe Vim always uses the previously focused window. I don't think there's an easy way to change it.
