### ISSUE TITLE
Feature request: add a range to :Gdiff

### ISSUE THREAD

**Issue by bam80** [tpope/vim-fugitive#1232]
So it could be possible to diff not only single file but all the files from a range at once.

Also, :Gdiff could be run on a selection of files from :Gstatus buffer.

**Comment by tpope** [comment]
This sounds like a variant of the request in #837, to which my response is basically the same. Concatenating multiple files in one buffer for the purposes of vimdiff sounds clunky and awkward.

**Comment by bam80** [comment]
But we could have a choice at least.
Otherwise, we just loosing vimdiff variants of very useful git commands

**Comment by bam80** [comment]
As alternative variant not involving files concatenation,
maybe we could have mappings for loading next/previous file in the commit to the vimdiff windows?

**Comment by bam80** [comment]
@tpope what do you think about the alternative variant?

**Comment by tpope** [comment]
I do like next/previous idea. It's been discussed in #132. The devil is in the details.
