### ISSUE TITLE
keep .git/index in buffer list after close ?

### ISSUE THREAD

**Issue by huangyingw** [tpope/vim-fugitive#1233]
I am using this buffer plugin to list all buffers: https://github.com/jeetsukumaran/vim-buffergator

when I use vs to open .git/index file, in multiple windows, and check my buffer lists, yes, it is in the buffer list.

while suppose my current window is in another file, say .gitignore, and I run :only to close all other windows, thus, .git/index is closed.
and I check my buffer list, the .git/index disappear from my buffer list. 
while other regular buffers are still there.

could you somehow keep the .git/index in buffer list even after close ?

**Comment by tpope** [comment]
This should work.

```viml
autocmd FileType fugitive set bufhidden=
```

The default was changed to `bufhidden=delete` because most people (or at least a vocal minority) seem to favor hiding it by default. I have no preference.

**Comment by huangyingw** [comment]
thank you very much
