### ISSUE TITLE
Appreciation!! Thanks awesome.

### ISSUE THREAD

**Issue by rajaravivarma-r** [tpope/vim-fugitive#1234]
I just pulled in the new changes. And the inline diffing in the status window is out of this world. I was recently looking into vimagit just for staging hunks without going through each file diff. This change is awesome. Thanks a lot and sorry for wasting your precious time. Please close this issue as soon as you see the thanks message. ❤️

**Comment by gotcha** [comment]
I concur, excellent work that is a pleasure to use !


@rajaravivarma-r  Very good idea to use issue to send thanks

**Comment by tpope** [comment]
Always good to hear, thanks!

**Comment by bam80** [comment]
@tpope well done, well done.. )
