### ISSUE TITLE
Fugitive always adds (useless) :A commands from projectionist

### ISSUE THREAD

**Issue by bfrg** [tpope/vim-fugitive#1235]
Fugitive always adds the `:A`, `:AD` and `:AE` commands from vim-projectionist, even if no projections were defined for the git project (no `g:projectionist_heuristics`, `.projections.json` or `.git/info/projections.json`).

Is this intentional?

If not, a simple check if the file `.git/info/projections.json` is readable should be enough:
```diff
diff --git a/plugin/fugitive.vim b/plugin/fugitive.vim
index 9d23a7d..2c235eb 100644
--- a/plugin/fugitive.vim
+++ b/plugin/fugitive.vim
@@ -234,7 +234,9 @@ function! s:ProjectionistDetect() abort
     if exists('+shellslash') && !&shellslash
       let base = tr(base, '/', '\')
     endif
-    call projectionist#append(base, FugitiveCommonDir(dir) . '/info/projections.json')
+    if filereadable(FugitiveCommonDir(dir) . '/info/projections.json')
+      call projectionist#append(base, FugitiveCommonDir(dir) . '/info/projections.json')
+    endif
   endif
 endfunction
```

**Comment by tpope** [comment]
It was deliberate. `:A` isn't completely useless as it takes an argument. But personally I like it because it gives me a universal `:Pcd`.

**Comment by gotcha** [comment]
> It was deliberate. `:A` isn't completely useless as it takes an argument. But personally I like it because it gives me a universal `:Pcd`.

Can you expand what you mean by "universal Pcd" ?

**Comment by tpope** [comment]
I want Projectionist features like `:Pcd` to be available on every single project, even if I don't have any other projections. And the way I see it, every single Git repository is a project of some sort.

**Comment by gotcha** [comment]
In other words, if both `vim-fugitive` and `vim-projectionist` plugins are installed, `:Pcd` will work from any file of a git checkout and `cd` to the git repository root.

@tpope Thanks for the detail.
