### ISSUE TITLE
Feature Request: Discard Multiple items

### ISSUE THREAD

**Issue by chris542** [tpope/vim-fugitive#1236]
Before `U` became `X`, I remember `U` could discard multiple items at once.
But `X` doesn't allow this.

When I visually select items under 'Unstaged', and hit `X`, it only discards the first one.

**Comment by tpope** [comment]
I limited it to one because echoing that "undo" message doesn't really scale well to multiple items. I don't remember, did it just show you a whole bunch of undo messages in a row?

**Comment by chris542** [comment]
I don't recall any "undo" message you're referring to..? When I press `X`, the changes discards without prompting me any "undo" messages. It just disappears.
When I visually select multiple items, it only discards the top one.

If you mean, `To restore, :Git cat-file blob 978894 > filename.ext`, it only prompts once as it only discards one item at the moment.

**Comment by tpope** [comment]
Yes, the `To restore` message. Spamming several of those seems like it would be a terrible experience.

**Comment by chris542** [comment]
Would it be possible to omit the message if it was a multiple discard?
By the way, love your all vim plugins :) so helpful!

**Comment by tpope** [comment]
Possible, sure. But then if you select a bunch of files and accidentally press the `X` key, you're screwed. I don't think Fugitive should provide a "delete a bunch of changes on a single keypress with no way to undo" feature.

If you press `.` with multiple files selected, they'll all appear on the `:` command line, and you can type out `:Git checkout` or whatever. You can even `au FileType fugitive xmap <buffer> gX .Git checkout<CR>` to get your own personal "shoot myself in the foot" map if you want. But until we have a better undo solution, it's not going in Fugitive proper.
