### ISSUE TITLE
Is there a way to open :Gstatus in a vertical split?

### ISSUE THREAD

**Issue by joaqo** [tpope/vim-fugitive#1237]
I am really loving the new Gstatus, and I'm starting to use it a lot. Opening it in a vertical split would be much more efficient use my monitor space though, but I haven't found a way of doing it.

**Comment by tpope** [comment]
It supports `:vertical`.

**Comment by jsatk** [comment]
Is there a way to set this as the default?

**Comment by tpope** [comment]
It's not configurable, but you can wrap `:vertical Gstatus` in a map or command.

**Comment by jsatk** [comment]
Thanks @tpope!

**Comment by mahemoff** [comment]
Is there any way to vertically split when the status is the only window? Even if it was launched with `vertical Gstatus`, it will still split horizontally if it becomes the only window.

**Comment by tpope** [comment]
If you mean changing the `<CR>` behavior, no, but there are other other maps.

**Comment by mahemoff** [comment]
Right, I did mean for `<CR>`. Thanks, I'll check the other maps.
