### ISSUE TITLE
Report: Gblame temp file remain to MRU history

### ISSUE THREAD

**Issue by tsuyoshicho** [tpope/vim-fugitive#1239]
Gblame temp file do not need reusing.

Suggestion:
Please these buffer no record to history...and I don't have ideas.

like vim-gnupg?

https://github.com/jamessan/vim-gnupg/blob/32360c8f20a91564dbb0b9b59343248acddc7b42/autoload/gnupg.vim#L617-L623

Regard.
Thanks.

**Comment by tpope** [comment]
We already set `bufhidden` and `nobuflisted`. I'm not sure what the problem you're having is or what you're asking for.

**Comment by tsuyoshicho** [comment]
Thanks sure...I see.
