### ISSUE TITLE
"modifiable" is set for "other" buffers in :Gdiff

### ISSUE THREAD

**Issue by wincent** [tpope/vim-fugitive#1241]
This behavior was a little surprising to me so I'm creating this issue to ask whether it is intended. Say I have a merge conflict in a file and I run `:Gvdiff`: I see three buffers:

- Left: `fugitive:///Users/glh/code/wincent/.git//2/README.md`
- Center: `README.md`
- Right: `fugitive:///Users/glh/code/wincent/.git//3/README.md`

"Left" and "Right" here show me the files according to the target branch (ie. the one I currently have checked out) and the merge branch (ie. the one I am trying to merge in) respectively, and "Center" shows me what I currently have in my working copy, which basically means the file + the merge conflict markers inserted by Git.

Now, I'd expect "Left" and "Right" to be `'nomodifiable'` and `'readonly'` but they are not. I'm supposed to edit the "Center" file to resolve the conflicts (ie. by hand, or by `:diffget`/`:diffput`, or mappings etc) and produce the desired result, but I'm not supposed to edit `//2` or `//3`.

I think I can hack around this with an autocmd that sets `'noma'` on `//1` and `//2`, but I thought I'd sanity check here first: is the lack of `'nomodifiable'` here an oversight or an intended behavior? I'm seeing it in both Vim (Homebrew-built v8.1 with patches: 1-577) and Neovim (v0.3.4) on current HEAD of "master" (bd0b87d36ad80e) in this repo; this is with a clean `~/.vim` directory containing nothing but vim-fugitive.

**Comment by tpope** [comment]
The behavior is intentional, as Git does allow you to modify those index entries, although it would certainly be weird to do so.

**Comment by wincent** [comment]
Ok. I'll stick with this then:

```
autocmd BufReadPost fugitive:///*//2/*,fugitive:///*//3/* setlocal nomodifiable readonly
```
