### ISSUE TITLE
Wrong working directory with git worktree

### ISSUE THREAD

**Issue by a-m-s** [tpope/vim-fugitive#1245]
If I do `:Gstatus` in a git worktree then the status looks absolutely correct, but `:pwd` reports the directory of the main tree, not the current worktree. This causes unexpected confusion.

The same is true for commit objects and such, although fugitive clearly knows which worktree is active because further calls to `:Gstatus` show the correct context.

All is well when working with files within the worktree.

**Comment by tpope** [comment]
Fugitive doesn't change the working directory. You can check `:echo FugitiveWorkTree()` to see what it thinks the root is. I'm guessing you've got some sort of auto-chdir plugin in the mix which is changing to the wrong directory.

**Comment by a-m-s** [comment]
Apologies, you're quite right. It looks for .git and has been there so long I forgot it was there.

Sorry for the noise.

**Comment by a-m-s** [comment]
For anybody else finding this, I ditched the other plugin and added this to my `.vimrc`:
```
let g:origdir = getcwd()
function! Auto_git_cd()
  try
    Gcd
  catch
    exe "cd" g:origdir
  endtry
endfunction
autocmd BufEnter * call Auto_git_cd()
```
(I feel like that ought to be a one-liner, but my vim-fu isn't strong enough.)
