### ISSUE TITLE
Question: Any way to stop :cn jumping to top of file?

### ISSUE THREAD

**Issue by sambanks** [tpope/vim-fugitive#1246]
Hi There

Awesome plugin. Cycling through previous commits with quickfix is amazing. I was wondering if it was possible to stop it from jumping to the top of the file on every :cn? Have checked the help for quickfix but couldn't see anything that relates.

Thanks
Sam

**Comment by tpope** [comment]
There's not any way to do this with `:cnext`, no.

**Comment by sambanks** [comment]
Ok thanks for confirming

**Comment by sambanks** [comment]
For anyone else looking I just added shortcuts:

```" Cycle through git history without jumping
map <Leader>n :cn<CR> <Bar> <C-o>
map <Leader>p :cp<CR> <Bar> <C-o>
```

**Comment by tpope** [comment]
`<C-o>` returns to the file you came from. It's not what you or anyone wants.

Also that's not how `<Bar>` works.

**Comment by sambanks** [comment]
You would know better than me, but the way I read the docs I thought:

`:help map_bar`

```
Since the '|' character is used to separate a map command from the next
command, you will have to do something special to include  a '|' in {rhs}.
There are three methods:
   use	     works when			   example	~
   <Bar>     '<' is not in 'cpoptions'	   :map _l :!ls <Bar> more^M
...
```
and with `<C-o>` you are inded correct, will figure a different way thanks.

**Comment by sambanks** [comment]
```
function GitScroll(direction)
    let l:save_pos = getpos('.')
    if a:direction == 'n'
        :cnext
    elseif a:direction == 'p'
        :cprevious
    endif
    call setpos(".", save_pos)
endfunction

" ** Keyboard Mappings **
" Cycle through git history without jumping lines
map <Leader>n :call GitScroll('n')<CR>
map <Leader>p :call GitScroll('p')<CR>

```

**Comment by tpope** [comment]
That will jump to the same line number (but not necessarily the same line).

**Comment by sambanks** [comment]
True, but that is good enough for my purposes :)

Thanks for the help (and the great plugin)

**Comment by tpope** [comment]
P.S. `<Bar>` is for the `:` command line. It's using it after `<CR>` that's wrong.

**Comment by sambanks** [comment]
Ah ok thanks
