### ISSUE TITLE
Disable folding altogether in Gdiff

### ISSUE THREAD

**Issue by 3N4N** [tpope/vim-fugitive#1247]
I want to disable folding in `Gdiff` window. I cannot find any option for that setting.

**Comment by tpope** [comment]
Vim automatically turns on folding when diffing buffers. It's not a Fugitive specific behavior. I imagine the right autocommand could disable it afterwards.

**Comment by TamaMcGlinn** [comment]
[This SO question](https://stackoverflow.com/questions/5017009/confusion-about-vim-folding-how-to-disable) has some tips, none of them quite complete. You need to add this to your vimrc:

```
set nofoldenable             " disable folding
au WinEnter * set nofen " really disable folding
au WinLeave * set nofen
```
