### ISSUE TITLE
How to jump between hunks in a commit when using `Glog --`

### ISSUE THREAD

**Issue by ArifRoktim** [tpope/vim-fugitive#1249]
When using the inline diff via `Gstatus`, you can jump between hunks with with `<C-N>` and `<C-P>`. This doesn't seem to apply when viewing commits via `Glog --`. Instead, I just go up/down one line. Possible bug?
![glog](https://user-images.githubusercontent.com/23637819/56334388-13e76100-6166-11e9-94f9-4e40c49f2a3f.png)  
Sorry if this is a duplicate issue. I searched and couldn't find a duplicate.

Thanks, Arif

**Comment by tpope** [comment]
The "bug" is that the documentation is a bit vague, currently this is only supported for `:Gstatus`. Long term I do want to unify commit buffers and the status buffer, so this will probably be supported eventually.

**Comment by tpope** [comment]
Eventually is here.
