### ISSUE TITLE
Provide a way to continue blaming on the parent of a commit for :Gblame

### ISSUE THREAD

**Issue by ehsan** [tpope/vim-fugitive#125]
:Gblame is really awesome, especially the fact that it reblames on a commit when pressing enter on it.  It would be really helpful if there was a way to continue the blame on the parent of a commit though, so that you could go over a line, press some key ('p' maybe?) and reblame on the parent of the commit, so that you can continue the blame back in the history.

**Comment by dellis23** [comment]
For other googlers: it's capital `P`.  You can find the reference here: https://github.com/tpope/vim-fugitive/blob/master/doc/fugitive.txt 

You can also view it in vim with `:help fugitive`.
