### ISSUE TITLE
Jumping between groups in Gstatus (suggestion)

### ISSUE THREAD

**Issue by sodapopcan** [tpope/vim-fugitive#1252]
I know you are inundated with stuff but these two `Gstatus` changes have been on my mind for a few months now so I'm just brain-dumping.

1. With `J` and `K` now jumping files/commits in `Gstatus` (though I know it's still experimental), it'd be cool if `<C-N>` and `<C-P>` were re-purposed to jump between Staged, Unstaged, and Unpushed groups—I would see it was jumping to the first file in each group, though it could always be smart and remember the last object-under-the-cursor for each group, reset after each new invocation of `Gstatus` (though this isn't necessary)

2. Have the cursor autojump to the first file/commit of the first group on invocation of `:Gstatus`

If these are at all appealing, I'd be happy to do the grunt work of a preliminary implementation, otherwise, feel free to close.

**Comment by tpope** [comment]
"Experimental" in this case really means I don't want to officially commit to them until I'm positive I won't need them for something else (rebase stuff is potentially going to need a lot of maps), and I'm certainly not giving the old maps away before that.

The top section isn't strictly read only, and there's nothing magical about the first section, so that's not going to happen. Now that I think of it, one really cool behavior would be for `s` and `u` to jump to the "Unstaged" and "Staged" sections when you're sitting at that top section. That seems like it would be up your alley.

**Comment by sodapopcan** [comment]
I do know that the top section isn't readonly, but 99% of the time I'm am staging/unstaging and the other 1% of the time I can first just hit `gg`.  Of course, I understand this is based strictly my own use-case and don't have a good understanding of how other people work—I should very likely tweak my own workflow to make better use of the top section.

I also get that you don't want to commit to the `J` and `K` mappings (I actually still use `<C-N>`/`<C-P>` myself) but yes, mappings for direct jumps to each section would certainly up my alley.

All-in-all, these are minor tweaks that have been on my mind and I just wanted to share—I'm otherwise *very* happy with the state of the status window.

**Comment by somini** [comment]
> 2. Have the cursor autojump to the first file/commit of the first group on invocation of :Gstatus

I'm using in something like this on `ftplugin/fugitive.vim`:

```vim
nmap <buffer> <silent> gg ggj
nmap <buffer> <silent> <nowait> j <C-n>
nmap <buffer> <silent> <nowait> k <C-p>
" h to stage/reset
nmap <buffer> <silent> <nowait> h -

augroup ft_gitcommit_status
	autocmd BufEnter <buffer> call <SID>select_first()
augroup END

let s:selected = 0
function! s:select_first()
	setlocal cursorline
	if !s:selected
		" Only once this script is sourced
		" Go to the first file
		" This picks up the horizontal shortcuts already
		execute 'normal' "gg"
		let s:selected = 1
	endif
endfunction
```

**Comment by tpope** [comment]
I've added some section jump maps I'm optimistic will solve the problem.
