### ISSUE TITLE
Gstatus performance is slow, especially on Windows

### ISSUE THREAD

**Issue by tankorsmash** [tpope/vim-fugitive#1254]
In addition to `git status`, it's now making calls to `git config --list`, `git diff`, `git diff --cached`, `git log ..@{u}`, and `git log @{u}..`. Check the times on those.

_Originally posted by @tpope in https://github.com/tpope/vim-fugitive/issues/1176#issuecomment-455367299_

---

I've opened a new issue to focus on purely the Windows portion. I went and compared performance on `v2.4`  (with the old :Gstatus) to `master`, and the old one performs noticeably better. 

I tried all those `git config --list` etc commands and they're all near-instant, but I believe most of the time is spent on the Windows Explorer opening and closing the cmd windows. I'm not sure what else to provide though.

The only delay every happens when the cmd window is opening and closing, and while it does happen a few times in v2.4, it happens significantly more in master and slows down the workflow. It's not a gamebreaker, but given how smooth it worked before, I'd like to see if it could be improved.

I do have a number of untracked files, but in this gif, I `:Gstatus`, then hit `P` on a tracked file, then close it with `q` without making any changes and then a ton of cmd windows open up: https://i.imgur.com/4rO1qQ0.gif

**Comment by tpope** [comment]
The repeated cmd window thing sounds like a `FocusGained` loop, which [should now be disabled on Windows](https://github.com/tpope/vim-fugitive/blob/16b7a060a3e20b8e159783f42ce4aa79a158208c/autoload/fugitive.vim#L2076-L2078). You're on the very latest?

**Comment by tankorsmash** [comment]
I just confirmed, `16b7a06` is the commit I'm on, and it was the same as the commit in the gif (given no updates were in the last few days).

I just tried `:Gstatus` out on a repo with only 7 listings as untracked, and it seemed like a comparable amount of time was spent waiting for those windows to open and close.

**Comment by tpope** [comment]
Something else is probably causing a loop then. Try disabling the rest of your config to see if it's another plugin or something in your vimrc triggering it.

[For general slowness, see my comment here.](https://github.com/tpope/vim-fugitive/issues/637#issuecomment-487735274)

**Comment by tankorsmash** [comment]
Without any plugins beyond colorscheme, vimplug and fugitive on master, the performance is consistent with all of them enabled: https://i.imgur.com/RuIR8hL.gif

It's a bummer I can't give you more information. I'll just stick with v2.4 and maybe I can figure out something that causes that loop. Thanks!

**Comment by tpope** [comment]
You can try commenting out the autocommands inside the autoload file and see if that fixes it.

**Comment by tpope** [comment]
Actually that GIF looks like about 10 commands, which, with Fugitive needing 5 per `:Gstatus` load, sounds like it's being reloaded twice. Debugging autocommands can probably get it down to 5. My linked comment talks about getting it down further.

**Comment by asknet** [comment]
I have same issue as well

**Comment by amadeus** [comment]
I'm on macOS in a somewhat sizeable repo and updating Gstatus takes up to 2 seconds to render properly. I don't mind that latency - except it's a bit annoying that it happens on focus. Would be nice if I could perhaps disable those focus/bufdelete/shelcmdpost autocommands completely, and just rely on manual updating with `R` or invoking Gstatus manually.

Although I will say - `git status` is super quick in terminal or via `:!git status`, so maybe there's more room for improvement?

**Comment by tpope** [comment]
Quoting myself from #637 for posterity:

> Batching commands sounds really hard, but please by all means investigate. I would accept a solution that batches only on Windows, if that makes things any easier.
>
> For a quick win, the two calls to diff could each be skipped if the relevant section of git status is empty. And the two calls to log could be cached based on the timestamps of the two refs being compared.

@amadeus running 5 commands (or 10 if there's a double reload bug) will certainly be slower than a single `git status` invocation, though 2 seconds sounds high. Use scriptease.vim to to `:Time call system('git status')` and see how much that accounts for. Possibly your shell is adding a lot of overhead.

**Comment by tpope** [comment]
Almost forgot to mention, [there is an option for turning autoreload off](https://github.com/tpope/vim-fugitive/blob/5d99841b22928f1597d447c68de844989bf9a804/autoload/fugitive.vim#L2062).

**Comment by tpope** [comment]
I believe the double reload bug is fixed, and I've made reloading smarter and less invasive all around.

I think the big win to shoot for is using jobs to run the 5 commands simultaneously.

**Comment by tpope** [comment]
I tested on a modern Windows machine and `:edit` in the `:Gstatus` window of the vim-fugitive repository took about 300ms. While I still hope to bring further improvements with job support, I think the current performance is totally acceptable now.

**Comment by tankorsmash** [comment]
Just pulled the latest, adba9c6, and confirmed it's about that fast too. Thanks for resolving!

**Comment by Trial-In-Error** [comment]
I was having a similar issue; turned out I had (previously, as a shortcut) set vim's shell to `zsh -i`, which cost about 1 second per invocation in zsh/ohmyzsh plugin setup. Yikes. Moved aliases to `~/.zshenv`, changed my vim config to use `zsh` non-interactively, and resolved my issue.

**Comment by tpope** [comment]
My official recommendation for shell aliases in Vim is "don't". Every solution introduces some sort of compromise.

**Comment by Trial-In-Error** [comment]
Yeah... I'll take that into consideration. Pretty much the only one I care about is a vanity alias that changes the terminal colors using escape codes; it's not uncommon that I'll be using a new set of terminal color mappings, enter vim, and decide that they're unusable for editing.

**Comment by tpope** [comment]
The status window uses jobs with an argument vector now so this should be resolved for pretty much everyone. I also implemented my parallel proposition on the `parallel-status` branch, but I'm not seeing any additional performance gains, so I probably won't merge it unless someone chimes in to the contrary.
