### ISSUE TITLE
vim-fugitive freezes up computer after writing to a file is triggered

### ISSUE THREAD

**Issue by Guzzii** [tpope/vim-fugitive#1255]
Hi there. I recently upgraded to the latest master. Every time I write a buffer to file (:w) in a big git repo, the plugin spins up 16 threads doing `git status -uno -ignore-submodule ....`. And it freezes up my laptop for 5 mins, which makes the plugin un-usable. Before the update, it didn't have this performance issue. I tried to not load vim-fugitive. Everything works fine. I am using Neovim 0.3.5. Any clue?

**Comment by tpope** [comment]
`ignore-submodule` appears nowhere in the Fugitive source code. It's probably some other plugin that integrates with Fugitive, not Fugitive itself.

**Comment by Guzzii** [comment]
Thanks @tpope . That's really helpful. It seems like it is airline that caused this issue.
