### ISSUE TITLE
can't load workdir file version from ":Git! diff" buffer

### ISSUE THREAD

**Issue by bam80** [tpope/vim-fugitive#1256]
in `Git! diff` buffer, pressing Enter on `+` changed lines seems loads the file in index (fugitive:///home/bam/play.it/.git//0/play.it-2/src/20_dependencies.sh), whereas I expect it should load the workdir version of the file - the version diff was done with

**Comment by tpope** [comment]
Works for me. Try toggling `diff.mnemonicPrefix` both on and off and see if that affects it.
