### ISSUE TITLE
dp in GStatus results in blank Gstatus split until :redraw!

### ISSUE THREAD

**Issue by cromwellryan** [tpope/vim-fugitive#1258]
`dp` on an unstaged change in Gstatus results in the Gstatus pain going blank. `:redraw!` resolves the issue. 

I usually use tmux + iterm. Video below is Mac Terminal.

Video: https://www.dropbox.com/s/lh74jb8zw4fvrr8/vim-fugitive%20diff%20from%20status.mov?dl=0

Vim version: 8.1.1100

`.vimrc`:

```

" quick leader
let mapleader = ","
nnoremap ; :
vnoremap ; :

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Vundle goodness
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set nocompatible " be iMproved
filetype off     " required!
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'tpope/vim-fugitive'

call vundle#end()
```

**Comment by tpope** [comment]
I missed this because I have "Disable save/restore alternate screen" enabled. Even with `:redraw!` it's a really harsh screen flash, should probably swap that `:!` out for a `system()` at some point.
