### ISSUE TITLE
Gdiff sort of breaks on "new" files

### ISSUE THREAD

**Issue by chreekat** [tpope/vim-fugitive#1261]
If I'm on a branch that introduced a new file, `Gdiff master` in that file will break some of the automatic cleanup that normally happens around Gdiff. The buffer holding the "other version" doesn't have bufhidden=delete set, and the original buffer doesn't have `diff` reset automatically.

What *does* happen is this: vim complains `fatal: Not a valid object name 317e11dd1c61fbd062e8b22ea787c20846036147:blah.txt`, and opens a blank buffer.

I think what I would *like* to happen is the first bit (`fatal: blah blah`), but then no extra buffer opens whatsoever. At the very least, it would be nice if the usual cleanup still took effect after closing the version from the other commit.

**Comment by chreekat** [comment]
Oh yeah, and this doesn't happen with `Gdiff` alone. Adding a commit, like `Gdiff master`, is what triggers it.

Hmmm, that may be enough of a clue for me to figure out where to look for the problem myself....

**Comment by tpope** [comment]
Turns out Fugitive wasn't activating at all for these buffers, whoops!

**Comment by chreekat** [comment]
Success!

I now realize this has plagued me for years, but I only actually understood the nature of the problem yesterday. Haha

**Comment by tpope** [comment]
Original issue is a bit of a journey, so please clarify the exact symptoms you are experiencing.
