### ISSUE TITLE
Missing FugitiveTreeForGitDir

### ISSUE THREAD

**Issue by heliostatic** [tpope/vim-fugitive#1263]
```
Error detected while processing function <SNR>174_Browse[14]..<SNR>174_Relative[1]..fugitive#Path[5]..<SNR>174_Tree:
line    1:
E117: Unknown function: FugitiveTreeForGitDir
E15: Invalid expression: FugitiveTreeForGitDir(a:0 ? a:1 : get(b:, 'git_dir', ''))
```

I'm getting this error consistently in neovim and vim. I tried removing all plugins except for `vim-fugitive`, managed with `vim-plug`, but the error persisted.

Plugin commit: `41a734e`
Neovim: `0.3.7`

**Comment by tpope** [comment]
This sounds like you have a new `plugin/fugitive.vim` and an old `autoload/fugitive.vim`.

**Comment by heliostatic** [comment]
Thanks, some digging led me to a `/pack` directory which had the old autoload. `rm`ed and all is well.
