### ISSUE TITLE
[Question] git diff previous version of the file

### ISSUE THREAD

**Issue by rjshrjndrn** [tpope/vim-fugitive#1264]
Hi,

Thank you for this awesome plugin.
one small question.

If I open a file can I see the difference with last commit(or nth commit) of the file ?.
I know there used to be one command like `Gdiff ~n`. But this is not working in latest fugitive.

Once again thank you for this fantabulous plugin.

**Comment by tpope** [comment]
It's deprecated, but `~n` still works (a bare `~` doesn't, you have to use `~1`).

The new syntax is `!~n:%` or for `:Gdiff` you can shorten it to `!~n`.

**Comment by rjshrjndrn** [comment]
so are you saying that, If I use `:Gdiff ~1` then the file show no changes unless `HEAD^` changed the file?
In that case, is there any way to compare the file with previous change ?

Thank you.

**Comment by tpope** [comment]
You can use `:0Glog` to find the most recent commit to change the current the current file, and then call `:Gdiff !~` to diff against the previous commit.

**Comment by rjshrjndrn** [comment]
So,
`:Gdiff 2~` doesn't make any sense in a file. 
Whenever I use `:Gdiff n~` I tried to compare the current file with nth revision (I think most people does the same in that context).

can you kindly explain, if I'm wrong

**Comment by tpope** [comment]
I removed support for `~n` entirely, so problem solved!
