### ISSUE TITLE
Tabcompletion for :Gpush --<Tab> does not work

### ISSUE THREAD

**Issue by kiryph** [tpope/vim-fugitive#1265]
I like to use tab-completion or `<C-d>` to see what short or long git options can be given to `:Gpush` and `:Gpull`.

I already can do this for `:Gcommit` by typing one of

a) short and long options (single hyphen)
- `:Gcommit -<Tab>`
- `:Gcommit -<C-d>`

b) only long options (double hyphen)
- `:Gcommit --<Tab>`
- `:Gcommit --<C-d>`.

The latter one gives following nice list:
![Screenshot 2019-06-12 at 09 14 57](https://user-images.githubusercontent.com/371756/59330742-9289f600-8cf2-11e9-9d15-a16442d23c77.png)

However, this does not work for `:Gpush` and `:Gpull` where I would like to see something similar as with zsh:
![Screenshot 2019-06-12 at 09 21 01](https://user-images.githubusercontent.com/371756/59331133-6de24e00-8cf3-11e9-9a28-3397427e2edd.png)

In particular, I was hoping I can tabcomplete`:Gpush --force` to do a force-push. I admit it does not save many keystrokes for this particular example but it is always reassuring when tabcompletion works.

**Comment by tpope** [comment]
It would be nice, although every command we tab complete adds to the maintenance burden. The tab completion in zsh is 8k lines for crying out loud, almost twice as big as the entirety of Fugitive. Finding a way to scrape it rather than maintain by hand would make this a lot more tenable.

Personally *this* particular case has never bothered me because I use `:Gpush -f`. But I would kill for `:Grebase --continue`.

**Comment by tpope** [comment]
Took me a while to figure out how to get terse usage instructions but looks like `git push -h` is what would need to be parsed.

**Comment by kiryph** [comment]
Do you know the hidden option `--git-completion-helper` for git commands?

For example:
```
❯ git pull --git-completion-helper
 --verbose --quiet --progress --recurse-submodules --rebase --stat --log
 --signoff --squash --commit --edit --ff --ff-only --verify-signatures
 --autostash --strategy= --strategy-option= --gpg-sign
 --allow-unrelated-histories --all --append --upload-pack= --force --tags
 --prune --jobs --dry-run --keep --depth= --unshallow --update-shallow --refmap=
 --ipv4 --ipv6 --no-verbose -- --no-quiet --no-progress --no-recurse-submodules
 --no-rebase --no-stat --no-log --no-signoff --no-squash --no-commit --no-edit
 --no-ff --no-verify-signatures --no-autostash --no-strategy
 --no-strategy-option --no-gpg-sign --no-allow-unrelated-histories --no-all
 --no-append --no-upload-pack --no-force --no-tags --no-prune --no-jobs
 --no-dry-run --no-keep --no-depth --no-update-shallow --no-ipv4 --no-ipv6

❯ git push --git-completion-helper
 --verbose --quiet --repo= --all --mirror --delete --tags --dry-run --porcelain
...

❯ git rebase --git-completion-helper
 --onto= --no-verify --quiet --verbose --no-stat --signoff --ignore-whitespace
...
```

My git version is `2.21.0`. I tried to figure out since when this helper option exists: following commit for git looks like it: https://github.com/git/git/commit/b9d7f4b4dbebea34ca8d02be8889884fc3fb90c7
The commit date is in February 2018. This means version 2.17 or 2.18 should have it.

I admit that this looks like a quite recent addition. However, it still can be used when available.

**Comment by tpope** [comment]
Recent is totally fine for a non-essential enhancement. But why does the damn thing require a Git repository just to print out a bunch of options? Contrary to the note, `git rebase --git-complete-helper` includes `--continue` regardless of the repository state. This isn't a deal breaker but it makes it more complicated than a one liner.

**Comment by kiryph** [comment]
Thanks for the update!
