### ISSUE TITLE
Gw succeed but throw an error (no such file or directory)

### ISSUE THREAD

**Issue by daisukixci** [tpope/vim-fugitive#1266]
Hello, 
First thanks for your work it's great.

When I use :Gw it works (as I can see the result with Gstatus) but it shows
"FILEPATH_IM_IN" 311L, 11904C writtenchmod: cannot access 'fugitive:///PROJECT_PATH/.git//0/FILEPATH_IM_IN': No such file or directory

How can i fix that ?

**Comment by tpope** [comment]
This looks live you have another plugin calling `chmod` on save.

**Comment by daisukixci** [comment]
Thank you that was that. 
I got this conf into my vimrc
```
" automatically give executable permissions if file begins with #! and
" contains '/bin/' in the path
"
function MakeScriptExecuteable()
    if getline(1) =~ "^#!.*/bin/"
        silent !chmod +x <afile>
    endif
endfunction

au BufWritePost * call MakeScriptExecuteable()"
```
Do you see a possible way to keep this working with your plugin ?

**Comment by tpope** [comment]
Add something like `&& @% !~# '^\a\a\+:'` to the conditional. That will prevent it from firing on buffer names that look like URLs (start with two or more letters followed by a colon).

**Comment by daisukixci** [comment]
Thanks a lot !
