### ISSUE TITLE
Why are fugitive commands defined on initially opening Vim?

### ISSUE THREAD

**Issue by lifecrisis** [tpope/vim-fugitive#1267]
Vim version v8.1.1145 with patch 8.1.1365 added.
Latest version of fugitive.

To reproduce:

1. `cd` into a repository and run `vim` with fugitive installed, no arguments
2. Try running... `:Gdiff`, for example.  Or try `:echo exists(':Git')` to see that the command is defined.

I can only get this behavior when opening Vim in a git repository.  Also, you can open Vim like above and run `:new` and you'll see that the commands are not defined, as expected.  It's only in the first buffer that I get the incorrect behavior.

I like to do tests like `if exists(':Git') ...` to check if a file is in a repository.  Thus, this problem occasionally breaks things for me.

**Comment by tpope** [comment]
Added by popular demand, I hate it too. You can compensate by checking `!empty(bufname(''))`.
