### ISSUE TITLE
Always preserve cursor position in the viewport

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1268]
When I'm staging hunk below the cursor moves down and stays below the cursor. That way viewport (visible lanes range) and cursor position in it are stable. It is convenient because I can keep staging without having to manually adjust viewport. For example I can <kbd>zt</kbd> once to reveal as much of the hunk I'm reviewing as possible and staging keeps this layout.

Contrary when I'm unstaging hunk from below the cursor moves above the cursor. This makes cursor position in viewport unstable – it keeps moving to the bottom until it reaches `scrolloff`. The hunk I'm reviewing next becomes invisible and I have to keep <kbd>zt</kbd> to reveal it.

Can this be changed to always preserve relative cursor position in the viewport?

**Comment by tpope** [comment]
Try moving [this viewpoint adjustment](https://github.com/tpope/vim-fugitive/blob/0f20c35b626b0b5e80428099a3a4cd9469683f86/autoload/fugitive.vim#L2274) after the reload later in the function and see if that does what you want.

**Comment by odnoletkov** [comment]
1. Unstaging is better because now I always have the 'current' hunk revealed
2. Doesn't work when cursor is not on the hunk header but on the file
3. Cursor position in viewport still changes often
4. Staging is worse because now the cursor position in viewport is not always stable

My main issue is cursor jumping unexpectedly after performing an action. I have to spend extra effort to find it again and understand on which hunk/file I'm about to act next.

So I've tried mapping <kbd>-zt</kbd> and it turns out to be almost exactly what I want. Next step was not forcing top position but preserving current offset:
```diff
diff --git a/autoload/fugitive.vim b/autoload/fugitive.vim
index 916201b..dc12ba0 100644
--- a/autoload/fugitive.vim
+++ b/autoload/fugitive.vim
@@ -2271,12 +2271,18 @@ function! s:Do(action, visual) abort
     if status < 0
       execute record.lnum + 1
     endif
-    call s:StageReveal()
   catch /^fugitive:/
     return 'echoerr v:errmsg'
   finally
     if reload
+      let pos = line('.') - line('w0')
       execute s:ReloadStatus()
+      while line('.') - line('w0') > pos && line('w0') < line('w$')
+        execute "normal! \<C-E>"
+      endwhile
+      while line('.') - line('w0') < pos && line('w0') > 1
+        execute "normal! \<C-Y>"
+      endwhile
     endif
   endtry
   return ''
```

Need to handle `scrolloff` but otherwise what do you think?

**Comment by tpope** [comment]
Looks like a bug crept into the reveal logic, can you asses the latest? I would expect staging to be acceptable, but unstaging might need some work.

Any tweaks you have *probably* belong inside `s:ReloadStatus()`.
