### ISSUE TITLE
Gcommit -v -s no longer working: "fugitive: error: There was a problem with the editor 'false '"

### ISSUE THREAD

**Issue by crapp** [tpope/vim-fugitive#1271]
Hi, 

I've updated fugitive today and now can no longer run "Gcommit -v -s" it gives me the following error message

> fugitive: error: There was a problem with the editor 'false '

Do you need any additional information? Gstatus / Gblame work as expected.

**Comment by tpope** [comment]
Does it fail with all flags, or just that particular combination?

See if you can find the first broken commit. It's probably 3d252dac21f2937d79b3c7d37c1ce38bdd6c2d82 or cf9c04af06885bf9d4064d8fa8e1ab8a62cba9cb.

**Comment by crapp** [comment]
Thanks a lot for your work, works perfectly!
