### ISSUE TITLE
Git push to upstream automatically

### ISSUE THREAD

**Issue by chris542** [tpope/vim-fugitive#1272]
Hey Tim, always appreciate using your wonderful plugins.

I love to mix using all sorts of plugins, and for git, I use vim-fugitive, vim-merginal and gv.

On vim-merginal, I can see the list of branches, and when I push the branch, it automatically detects whether it has upstream or not. If it doesn't it pushes with --set-upstream origin flag automatically.

After I have upstream on my branch, I try using :Gpush, but it fails.

Is it possible to add git push to detect upstream?

Thanks

**Comment by tpope** [comment]
`:Gpush` calls `git push` with the arguments you give it. Are you asking for it to do something else?

**Comment by chris542** [comment]
Is it possible when `git push` encounters an error requiring for `--set-upstream`, it does it automatically?

**Comment by tpope** [comment]
Not that I know of but I’m no `git push` expert.

**Comment by chris542** [comment]
Okay i'll try to find myself a workaround :)

**Comment by 0xMH** [comment]
@chris542 Have you found any workouts?

**Comment by chris542** [comment]
@0xMH i have this in my vimrc

nnoremap <silent> <Leader>gp :exec "Gpush origin " . fugitive#head()<cr>

**Comment by tpope** [comment]
Consider `:Git -c push.default=current push` as a more organic, robust equivalent.

**Comment by chris542** [comment]
Thanks master tpope
