### ISSUE TITLE
when specify objects, ! means "the commit owning the current file"

### ISSUE THREAD

**Issue by cracker-ww** [tpope/vim-fugitive#1273]
what does this mean? how a commit OWN the current file? Could you guys help me understanding this? I can't find any docs and nothing found with google

**Comment by odnoletkov** [comment]
It's a Fugitive concept. For files and directories in working copy and in index it is HEAD commit. For blobs and trees with commit-relative URLs like 'fugitive://path/to/.git//$commit/path/to/file' it is $commit.

**Comment by cracker-ww** [comment]
great, thanks for your explanation!

**Comment by gh-liu** [comment]
Still do not fully understand it , could you please provide some examples to help me better understand the concept?

**Comment by 04thegost** [comment]
what kind of concept do you want?

**Comment by tpope** [comment]
Call `:Gedit master~10:path/to/file`. Now you're looking at `path/to/file` as it existed in `master~10`. The commit owning the current file is `master~10`.

**Comment by gh-liu** [comment]
> Call `:Gedit master~10:path/to/file`. Now you're looking at `path/to/file` as it existed in `master~10`. The commit owning the current file is `master~10`.

Got it, thank you for your explanation.
