### ISSUE TITLE
New command: Close Gstatus window

### ISSUE THREAD

**Issue by somini** [tpope/vim-fugitive#1274]
The old `:Gstatus` windows were `previewwindow`s, so you could close from other buffers with `pclose`. The new status is not.

Can we get a command (or even a snippet) that performs the same function? I tried an ugly hack by registering the buffer names on a `t:` variable, but this is hideous and to keep the list current, I started messing about with (nested) `autocmd` and gave up.

**Comment by tpope** [comment]
Close any window with a `w:fugitive_status` variable and you should be good to go.

**Comment by somini** [comment]
In case anyone stumbles on this issue:

```
function! s:close_fugitivestatus()
	for l:idx in range(winnr('$'))
		let l:winnr = l:idx + 1
		if !empty(getwinvar(l:winnr, 'fugitive_status'))
			execute l:winnr.'close'
		endif
	endfor
endfunction
command! GstatusClose call s:close_fugitivestatus()
```

You can then call `GstatusClose` anywhere you need.
This can be called when starting editing a commit, to avoid having both status and commit windows at the same time; append it to `ftplugin/gitcommit.vim`

**Comment by gerardbm** [comment]
Thanks, @somini. That was very useful. I added 2 lines to toggle (open/close) this window pressing <kbd>Ctrl</kbd>+<kbd>s</kbd>:

```viml
function! s:ToggleGstatus() abort
	for l:winnr in range(1, winnr('$'))
		if !empty(getwinvar(l:winnr, 'fugitive_status'))
			execute l:winnr.'close'
		else
			Gstatus
		endif
	endfor
endfunction

nnoremap <C-s> :call <SID>ToggleGstatus()<CR>
```

**Comment by AchmadFathoni** [comment]
> Thanks, @somini. That was very useful. I added 2 lines to toggle (open/close) this window pressing Ctrl+s:
> 
> ```viml
> function! s:ToggleGstatus() abort
> 	for l:winnr in range(1, winnr('$'))
> 		if !empty(getwinvar(l:winnr, 'fugitive_status'))
> 			execute l:winnr.'close'
> 		else
> 			Gstatus
> 		endif
> 	endfor
> endfunction
> 
> nnoremap <C-s> :call <SID>ToggleGstatus()<CR>
> ```

I can open git status with this but hitting Ctrl+S again doesn't close it. Any updates?

**Comment by gerardbm** [comment]
> ```viml
> function! s:ToggleGstatus() abort
> 	for l:winnr in range(1, winnr('$'))
> 		if !empty(getwinvar(l:winnr, 'fugitive_status'))
> 			execute l:winnr.'close'
> 		else
> 			Gstatus
> 		endif
> 	endfor
> endfunction
> 
> nnoremap <C-s> :call <SID>ToggleGstatus()<CR>
> ```

Rename `Gstatus` to `Git`, because vim-fugitive have been updated last week. `Gstatus` is now a deprecated function.

**Comment by 3N4N** [comment]
There is a break missing in the for loop.

**Comment by alecunsolo** [comment]
For my future self: I implemented the toggle logic in lua for my `init.lua` configuration
```lua
vim.keymap.set('n', '<leader>gg', function()
  local windows = vim.api.nvim_list_wins()
  for _, v in pairs(windows) do
    local status, _ = pcall(vim.api.nvim_win_get_var, v, 'fugitive_status')
    if status then
      vim.api.nvim_win_close(v, false)
      return
    end
  end
  vim.cmd [[Git]]
end, { desc = '[G]it to[G]gle' })
```

**Comment by xuanhung1509** [comment]
Your solution works great @alecunsolo. I'd like to modify it a bit.
```lua
local toggle_fugitive = function()
  local winids = vim.api.nvim_list_wins()
  for _, id in pairs(winids) do
    -- you can omit the underscore `_` if it's the second variable. 
    local status = pcall(vim.api.nvim_win_get_var, id, "fugitive_status")
    if status then
      vim.api.nvim_win_close(id, false)
      return
    end
  end
  vim.cmd("Git")
end
```
