### ISSUE TITLE
Preserve original cursor position when exiting Gstatus

### ISSUE THREAD

**Issue by petobens** [tpope/vim-fugitive#1276]
Consider the following minimal vimrc:
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/tpope/vim-fugitive
filetype plugin indent on
```
Now, as in the GIF, open vim (or nvim) inside a git dir and do:
1. Run `:vs` to generate a split
2. Press `<C-w>h` to move to the right split window
3. Run `:Gstatus`
4. Press `q` to exit the Gstatus.

After 4. the cursor is now on the left window (I expect it to be on the right one).

![fugitive cursor](https://user-images.githubusercontent.com/2583971/60758003-0795d600-9fe8-11e9-8d01-fef5e87d8f3e.gif)

**Comment by tpope** [comment]
Change `:Gstatus` to `:leftabove split` and `q` to `:q` and the same thing happens. I don't think there's anything special about the `:Gstatus` window that it should behave differently from all other windows.

**Comment by petobens** [comment]
Ok. Thanks anyway

**Comment by tpope** [comment]
Nothing to stop you from making your own `q` map, fyi
