### ISSUE TITLE
Gstatus window not updated after commit

### ISSUE THREAD

**Issue by petobens** [tpope/vim-fugitive#1277]
Consider  the following minimal init.vim:
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/tpope/vim-fugitive
filetype plugin indent on
```
Now, as in the GIF, do
1. Open nvim in a modified git dir
2. Run `:Gstatus` and then stage (with `-` mapping) and create a commit (with `cc` mapping) for some change (in my example adding the `foo.txt` file).
3.  Close the commit message window with `:wq`.
After 3. I expect the gstatus to reflect that the `foo.txt` is actually commited. Instead the gstatus window shows it as "staged" (and only upon closing the Gstatus window and reopening this goes away):

![fugitive-foo](https://user-images.githubusercontent.com/2583971/60823807-c7b52700-a17e-11e9-80c2-eba5fafaa3c5.gif)

**Comment by tpope** [comment]
Opened a Neovim bug, fingers crossed.

https://github.com/neovim/neovim/issues/10452

**Comment by petobens** [comment]
Oh I see. Thank you!

**Comment by petobens** [comment]
The only difference with your report is that I'm using a newer vim version (latest master).  When running your code I  get the following:
```viml
let older_time = reltime()
sleep 1m
let newer_time = reltime()
echo reltimestr(reltime(newer_time, older_time))

0.000000
```
No idea if this is relevant or not though

**Comment by tpope** [comment]
Wow, that means my workaround of looking for a very large number wont even work.

**Comment by blueyed** [comment]
(At least with the example) you might want to switch start/end.

**Comment by tpope** [comment]
The point is to check *which* is newer.

**Comment by justinmk** [comment]
> Wow, that means my workaround of looking for a very large number wont even work.

fwiw, that regression has been on master only for a few days, so it's safe to ignore it after https://github.com/neovim/neovim/issues/10452 .

**Comment by tpope** [comment]
@petobens can you check if the latest Neovim fixes it?

**Comment by petobens** [comment]
It does! Thanks to all :)
