### ISSUE TITLE
:0Glog is not working

### ISSUE THREAD

**Issue by rjshrjndrn** [tpope/vim-fugitive#1278]
No logging or diffing is working after last two updates

When I do `:0Glog`
```
Error detected while processing function <SNR>119_Log:
line   36:
E42: No Errors
Press ENTER or type command to continue
```

and opens up an empty quickfix window.

```
git version 2.22.0
hub version 2.12.1

nvim --version
NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.8/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

**Comment by tpope** [comment]
Does your filename have spaces or weird punctuation in it?

**Comment by tpope** [comment]
Can you clarify which commit is still working for you?

**Comment by rjshrjndrn** [comment]
I don't have any spaces or puctuations
 file name: `alertrules.nodes.yml`
This is the file: https://github.com/rjshrjndrn/sunbird-devops/blob/release-2.0.0/ansible/roles/stack-monitor/templates/alertrules.nodes.yml

Sorry, I couldn't figure out exact commit. I did `PlugUpdate` to update the plugin

**Comment by tpope** [comment]
I've made things more robust. If that doesn't fix or at least reveal the issue, you may need to hunt down the offending commit.

**Comment by rjshrjndrn** [comment]
Ah, Just updated again. And it's working. 
Thank you for your time.
