### ISSUE TITLE
[ Question ] Is there any way to format :0Glog window

### ISSUE THREAD

**Issue by rjshrjndrn** [tpope/vim-fugitive#1281]
Hi,
Thank you for this lifesaver plugin.

One small question, is there any way to format the `:0Glog` window

Current output for `:0Glog` is

`fugitive:///home/rajeshr/Documents/projects/public-devops/.git//347195889e7f3a60c42ec4036414e17940aef61c/ansible/roles/stack-monitor/templates/prometheus.yml|| Issue #000 feat: enabling nginx scrapping`

I think this make much better readbility.

`347195889e7f3a60c42ec4036414e17940aef61c || Issue #000 feat: enabling nginx scrapping`

**Comment by tpope** [comment]
Vim patch 8.0.1782 adds support for overriding what is displayed in that first column via a "module" field. I just added supported for it a few days ago. (The bug you reported was because I accidentally broke things on Vim versions *without* that patch.) So upgrade to a compatible version and you'll be good to go.

**Comment by rjshrjndrn** [comment]
oh.. okay.
Can you please point me to some documentation or how-to?
Sorry for being a noob.

Thank you

**Comment by tpope** [comment]
How to upgrade Vim depends on how you installed it.

**Comment by rjshrjndrn** [comment]
Sorry,

I am using Neovim 0.3.8
So is there any way to do that? you mentioned that you added support for
"modules" in the plugin. To be honest I didn't understand that.

**Comment by tpope** [comment]
I have no idea if that patch is in Neovim or not.

**Comment by rjshrjndrn** [comment]
Thank you. I'll check that out

**Comment by rjshrjndrn** [comment]
Hi, I Updated to development build, and the `:0Glog` is working flawlessly. Thank you
