### ISSUE TITLE
Can't commit neovim

### ISSUE THREAD

**Issue by eemed** [tpope/vim-fugitive#1283]
Im running neovim v.0.3.8. When I open Gstatus and try to commit with cc I get this message at the bottom
> fugitive:            [--git-dir=<path>] [--work-tree=<path>]  [--namespace=<name>]

Committing works if I start vim from the project root.
I tried this with 2 different VMs.

**Comment by tpope** [comment]
What version of Git?

**Comment by eemed** [comment]
git version 1.8.3.1

**Comment by tpope** [comment]
Fugitive recently switched to using `git -C` to change to the project root, which requires Git 1.8.5 or newer. I'll add an error message to make this clearer.

**Comment by tpope** [comment]
Actually I think I might roll this back because you can work around with a wrapper script:

```sh
#!/bin/sh

if [ -C = "$1" ]; then
  cd "$2"
  shift 2
fi
exec /usr/local/bin/git "$@"
```
