### ISSUE TITLE
Gblame broken in recent commits

### ISSUE THREAD

**Issue by bothyhead** [tpope/vim-fugitive#1284]
Gblame has been throwing an error for me in the past few days.  I'm using GVim for Windows, ver 8.1 with Patch 1 applied.

fugitive commit: c33d7fcb9f

For example, running GBlame on:

C:\Users\Firstname Surname\vimfiles\plugged\vim-fugitive\plugin\fugitive.vim

Throws this error:

E492: Not an editor command: keepalt leftabove vsplit:C:\Users\Firstname Surname\AppData\Local\Temp\VIAB851.tmp.fugitiveblame

Note: 

1) There is a space between in the windows path Firstname[space]Surname
2) The E492 error does include a space between vsplit: and C:\users\...

Thanks

p.s. the same commit works fine on Linux

**Comment by tpope** [comment]
Thanks for the heads up.

**Comment by bothyhead** [comment]
Thanks for the quick fix!

Dave
