### ISSUE TITLE
Commit doesn't get added when exiting with :wqa

### ISSUE THREAD

**Issue by bzf** [tpope/vim-fugitive#1285]
First off, thanks for this plugin! It's the best tool for interacting with `git` that I've ever used!

I did updated my plugins a few days back (not sure what version I was on before) and noticed that I started to lose commit messages when adding files with `:Gwrite`, calling `:Gcommit -v`, typing out my message and then closing with `:wqa`.

It seems to work if I do `:wq` at the end instead, but I'm not sure if this is a bug or if something is wrong on my end so wanted to ask about it. It also works if I commit directly from the command line using `git commit -v`.

I managed to get it down to this configuration file to reproduce it, seems like setting `autowrite` causes the issue. Removing it fixes it.

```vim
set autowrite

call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-fugitive'
call plug#end()
```

I found [this issue](https://github.com/tpope/vim-fugitive/issues/1283) that sounded similar, but after updating the plugin and trying it out, it stills seems to fail to commit.

I'm running macOS 10.14.5 (Mojave) and am using `neovim`.

<details><summary>System details</summary>
<p>

```sh
$ git --version
git version 2.22.0
$ nvim --version
NVIM v0.3.7
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190529-65312-1cx5evh/neovim-0.3.7/build/config -I/tmp/neovim-20190529-65312-1cx5evh/neovim-0.3.7/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190529-65312-1cx5evh/neovim-0.3.7/build/src/nvim/auto -I/tmp/neovim-20190529-65312-1cx5evh/neovim-0.3.7/build/include
Compiled by brew@Mojave-2.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.7/share/nvim"

Run :checkhealth for more info
```
</p>
</details>

Thanks!

**Comment by tpope** [comment]
Can confirm a regression appears to have been introduced. It would help if you or someone could bisect to the breaking commit. It was probably introduced in the last month or so.

**Comment by bzf** [comment]
I did a `git-bisect` and landed on https://github.com/tpope/vim-fugitive/commit/14649fb858f2145ff15ff38cca1e7f51ffbbbfba. Running `git revert  14649fb` and removing the `if &autowrite` conditional seems to fix it.

**Comment by tpope** [comment]
Thanks! I don't fully understand why it breaks things but it's easy enough to work around.

**Comment by bzf** [comment]
Awesome, thanks for the quick help! 👏
