### ISSUE TITLE
Silence command echo after closing commit window

### ISSUE THREAD

**Issue by petobens** [tpope/vim-fugitive#1286]
If I do the following steps:
1. Edit some file in a git repo
2. Open `:Gstatus` and stage the file with `-`
3. Open the commit window with `cc`
4. Write a commit message (something like `Blah`) and close the commit message window with `:wq`

After 4 I get the following output echoed in the commandline:
```
[master 4e16ac2] Blah
 1 file changed, 1 insertion(+)
```
I believe this started after https://github.com/tpope/vim-fugitive/pull/1115 (but I'm not sure). Anyways: can that echo be silenced/suppressed? Thanks!

**Comment by tpope** [comment]
This has always been the intended behavior. You can silence it with `:silent wq`.
