### ISSUE TITLE
Gpush doesn't push (win10, vim)

### ISSUE THREAD

**Issue by habamax** [tpope/vim-fugitive#1289]
With the recent fugitive updates I am unable to push changes with `:Gpush`:

![image](https://user-images.githubusercontent.com/234774/61222296-16386780-a723-11e9-9196-476daadcbc5c.png)

I can do it from the cmd line though.

PS, I have the latest vim-fugitive installed as of now 4da9fb8f43869125f6e1bb1ff8dd27f315623835

**Comment by habamax** [comment]
So, I have tried to do the same in Neovim -- and with the same plugins installed (I have common .vim for both) -- it works.

So this issue is (G)vim related.

Just in case my version is:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 12 2019 22:01:42)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-1674
Compiled by appveyor@APPVYR-WIN
Huge version with GUI.  Features included (+) or not (-):
+acl                +cscope             -hangul_input       +multi_lang         +smartindent        +user_commands
+arabic             +cursorbind         +iconv/dyn          +mzscheme/dyn       +sound              +vartabs
+autocmd            +cursorshape        +insert_expand      +netbeans_intg      +spell              +vertsplit
+autochdir          +dialog_con_gui     +job                +num64              +startuptime        +virtualedit
+autoservername     +diff               +jumplist           +ole                +statusline         +visual
+balloon_eval       +digraphs           +keymap             +packages           -sun_workshop       +visualextra
-balloon_eval_term  +directx            +lambda             +path_extra         +syntax             +viminfo
+browse             -dnd                +langmap            +perl/dyn           +tag_binary         +vreplace
++builtin_terms     -ebcdic             +libcall            +persistent_undo    -tag_old_static     -vtp
+byte_offset        +emacs_tags         +linebreak          -postscript         -tag_any_white      +wildignore
+channel            +eval               +lispindent         +printer            +tcl/dyn            +wildmenu
+cindent            +ex_extra           +listcmds           +profile            -termguicolors      +windows
+clientserver       +extra_search       +localmap           +python/dyn         +terminal           +writebackup
+clipboard          -farsi              +lua/dyn            +python3/dyn        -termresponse       -xfontset
+cmdline_compl      +file_in_path       +menu               +quickfix           +textobjects        -xim
+cmdline_hist       +find_in_path       +mksession          +reltime            +textprop           +xpm_w32
+cmdline_info       +float              +modify_fname       +rightleft          -tgetent            -xterm_save
+comments           +folding            +mouse              +ruby/dyn           +timers             
+conceal            -footer             +mouseshape         +scrollbind         +title              
+cryptv             +gettext/dyn        +multi_byte_ime/dyn +signs              +toolbar            
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL   -DFEAT_XPM_W32   -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /Zl /MT -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_GUI_MSWIN -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86t.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python37.dll\" -DFEAT_MZSCHEME -I "C:\Program Files\Racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_a36fs8.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_a36fs8.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl528.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=24 -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby240.dll\" -DFEAT_HUGE /Fd.\ObjGXOULYHTRZAMD64/ /Zi
Linking: link  /nologo /opt:ref /LTCG:STATUS /HIGHENTROPYVA:NO oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:AMD64 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib netapi32.lib  /machine:AMD64  libcmt.lib oleaut32.lib user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python37.lib   "C:\Tcl\lib\tclstub86.lib" winmm.lib WSock32.lib xpm\x64\lib-vc14\libXpm.lib /PDB:gvim.pdb -debug

```

**Comment by tpope** [comment]
What is `:set shell?` in both Vim and Neovim? What Git did you install?

**Comment by habamax** [comment]
vim:   shell=C:\WINDOWS\system32\cmd.exe
neovim:   shell=cmd.exe

``
git --version                                                                                                  
git version 2.22.0.windows.1
```
installed from scoop

**Comment by tpope** [comment]
Also check `:set shellcmdflag?`.

Does Neovim return 1 for `:echo has('win32')`?

**Comment by habamax** [comment]
vim
```
:set shellcmdflag?
  shellcmdflag=/c
```

neovim
```
:set shellcmdflag?
  shellcmdflag=/s /c

:echo has('win32')
1
```

**Comment by tpope** [comment]
Try doing `:set shellcmdflag=/s\ /c` on plain Vim. and see if that fixes it.

**Comment by habamax** [comment]
the same error

![image](https://user-images.githubusercontent.com/234774/61236248-2f9bdc80-a740-11e9-80e9-9e334f1e8000.png)

**Comment by tpope** [comment]
Check `:set shellquote? shellxquote? shellxescape? shellslash?` and look for differences. Try the values from Neovim on Vim.

**Comment by habamax** [comment]
it is `shellxquote`

In neovim it is `set shellxquote=\"`

in vim it is `set shellxquote="("`

I have changed it to what neovim has and now `:Gpush` works.
This is strange.

**Comment by habamax** [comment]
Hmm, but this now makes `:Gcommit` crazy:

![image](https://user-images.githubusercontent.com/234774/61237175-899da180-a742-11e9-82eb-88461a31da45.png)

**Comment by habamax** [comment]
Well, I have put all those settings from neovim to vim -- `:Gpush` works but `:Gcommit` fails.

![image](https://user-images.githubusercontent.com/234774/61237812-fa918900-a743-11e9-84d7-deaa4110c63a.png)

Basically for gpush to push `shellxquote` should be set to `"` -- now commit fails. If I change `shellxquote` to `(` or make it empty then `Gcommit` works and `Gpush` fails.

**Comment by habamax** [comment]
I have downgraded vim to version 8.1.1657 and there is no error -- with default settings (no shellxquote mangling) I can Gpush and Gcommit as before. Not sure what has changed in vim to cause that kind of problem to fugitive.

**Comment by habamax** [comment]
And the next available release in https://github.com/vim/vim-win32-installer/releases is 8.1.1661.
I have just installed it and it has that error.

**Comment by tpope** [comment]
The short answer is that shell escaping on Windows is a nightmare. In the near future, I hope to move to using `job_start(['cmd', 'args'])` to avoid the shell entirely, but that's probably a month or so out. My recommendation would be to stick with that old version of Vim a little while longer if you can.

But one last thing: can you try deleting these 2 lines <https://github.com/tpope/vim-fugitive/blob/4da9fb8f43869125f6e1bb1ff8dd27f315623835/autoload/fugitive.vim#L51-L52> and see how that affects things? It probably won't fix `:Gcommit` but if we're lucky it will get `:Gpush` to work everywhere.

**Comment by habamax** [comment]
Ok, that is no problem for me to use older version.

as for the last thing -- I have deleted the lines you have mentioned and:

1. Gcommit works
2. Gpush works in one case and doesn't work in another

## Gpush doesn't work
1. GStatus
2. Stage with `s`
3. Commit with `cc`
4. GPush

I can see `:Dispatch git -C "C:/Users/maksim.kim/vimfiles" push` -- there is a path in git command. 

## Gpush works
From the previous "Gpush doesn't work" there is unpushed commit.
1. exit vim
2. enter vim and Gstatus to see unpushed commit
3. Gpush

Gpush works and I can see a command like `:Dispatch git push` -- there is not path in the command

**Comment by tpope** [comment]
It passes `-C "worktree"` if the work tree is not the current directory. It used to use `:cd` instead, that's why you're seeing it after upgrading Fugitive. Unfortunately, that's just one of the things it uses quotes for, so bringing back `:cd` would only mitigate the problem, not fix it.

I can't/won't bring back `:cd` for reasons, but I am pushing another mitigation that should help.

**Comment by habamax** [comment]
Thanks, hope the thing with job will be more robust and easier.

Your new fix works for my case (I don't have spaces in the path) but probably will fail for smth like `C:/Users/John Smith/git project/`

**Comment by tpope** [comment]
Yes, it will also break for `:Gcommit %` where the current filename has a space in it, `git log --pretty=format:%H` which we use in `:Glog`, all sorts of things really. There's only so much I can do to compensate when your Vim is broken.

**Comment by tpope** [comment]
Closing, let me know if you figure out anything actionable.

**Comment by habamax** [comment]
Thx for your work  @tpope!

Looking forward for your job-aware implementation.

BTW, it is still strange that 8.1.1657 has no this issue, they have probably changed some defaults.

**Comment by habamax** [comment]
Btw, I found out that `Gpush` works if no vim-dispatch is installed.

**Comment by habamax** [comment]
@tpope see https://github.com/vim/vim/issues/4682#issuecomment-511766292

Looks like you don't have to add double quotes to the path component of `git -C` if you slice job_start to smth like: 

     let job = job_start(['C:\WINDOWS\system32\cmd.exe', '/c', 'git', '-C', 'C:/Users/maksim.kim/my docs', 'push'])

**Comment by habamax** [comment]
So in job.vim of dispatch plugin you use request.expanded which is a (shellescaped?) string.

If it would be possible to have it in a list of elements -- then it should work (for path with spaces too):

```
function! dispatch#job#handle(request) abort
...
  if exists('*job_start')

    let expanded= ['git', '-C', 'C:/Users/maksim.kim/my docs', 'push']

    let job = job_start(split(&shell) + split(&shellcmdflag) + expanded, {
          \ 'mode': 'raw',
          \ 'callback': function('s:output'),
          \ 'close_cb': function('s:closed'),
          \ 'exit_cb': function('s:exit'),
          \ })
```

**Comment by tpope** [comment]
It should have been obvious but I didn't realize this was dispatch.vim related.

`:Dispatch` and `:Make` accept shell code, there's no mechanism to pass a list. But there's other things we can do. Try the `win32-job-escape` branch on dispatch.vim.

**Comment by habamax** [comment]
Yes! It works. Path with spaces works too!

**Comment by tpope** [comment]
Great, pushing to master.

**Comment by habamax** [comment]
Thx a lot!
