### ISSUE TITLE
Glog broken in neovim

### ISSUE THREAD

**Issue by redlolgeerf** [tpope/vim-fugitive#1290]
Glog opens a split with `|| zsh:1: command not found: LANG=en_US.UTF-8` in it.

fugitive 469a73f3d97ef0ec10d3e3aa580487c6e0acffdc
nvim v0.3.7
git 2.7.4

**Comment by tpope** [comment]
What do you get if you do `:echo system('git log -1')`?

**Comment by redlolgeerf** [comment]
`:echo system('git log -1')` works fine. I found out, that I have this in my vimrc, which breaks fugitive
`  let g:fugitive_git_executable = 'LANG=en_US.UTF-8 git'` 
Without it everything works.

**Comment by tpope** [comment]
Oh dang, this used to be a common practice (which I did not endorse) to compensate for parsing issues in the old `:Gstatus`. I'm going to add an error message about it.
