### ISSUE TITLE
ssh_askpass error on macos and neovim

### ISSUE THREAD

**Issue by gnujeremie** [tpope/vim-fugitive#1292]
Hi,

I updated the plugin and can't push/pull anymore with :Git push/:Git pull. I have this error : 
```
:!env GIT_TERMINAL_PROMPT=0 git push
ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
git@gitlab.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

shell returned 128
```

So I installed ssh-askpass using homebrew, but the error remains.

```
$ which ssh-asskpass 
$ /usr/local/bin/ssh-askpass
```

I am using neovim, it works fine with vim. Am I doing something wrong ?

Thanks.

**Comment by tpope** [comment]
Googling suggests that particular error might be VS Code related. Do you have that installed?

**Comment by gnujeremie** [comment]
Nope.

**Comment by tpope** [comment]
Check `:echo $GIT_ASKPASS` and `:echo $SSH_ASKPASS`, and see if anything comes back from `:!git config --list|grep askpass`.

**Comment by gnujeremie** [comment]
```:echo $GIT_ASKPASS``` and ```echo $SSH_ASKPASS``` return nothing.

```
:!git config --list|grep askpass

shell returned 1
```

**Comment by gnujeremie** [comment]
Ok found a way to fix it :

- Installed ssh-askpass following these instructions https://github.com/theseal/ssh-askpass
- Installed xquartz ```brew cask install xquartz```, needed for the creation of ```/usr/X11R6``` (impossible to create it manually, even using sudo).
- symlinked ssh-askpass ```sudo ln -s /usr/local/bin/ssh-askpass /usr/X11R6/bin/ssh-askpass```

Now it works. Seems a bit complicated though, and a lot to install.

**Comment by tpope** [comment]
Yeah screwing around in `/usr` is definitely not the way to go. You'd want something like `git config --global core.askPass ssh-askpass`.

It's been on the todo list to provide an askpass default for a while now. Can you try `:Gpull` (*not* `:Git pull`) with the changes I just pushed and see if that works out of the box?

**Comment by gnujeremie** [comment]
I'll try as soon as i can and i'll let you know

Le 18 juillet 2019 22:32:19 GMT+02:00, Tim Pope <notifications@github.com> a écrit :
>Yeah screwing around in `/usr` is definitely not the way to go. You'd
>want something like `git config --global core.askPass ssh-askpass`.
>
>It's been on the todo list to provide an askpass default for a while
>now. Can you try `:Gpull` (*not* `:Git pull`) with the changes I just
>pushed and see if that works out of the box?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tpope/vim-fugitive/issues/1292#issuecomment-512975885

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tpope** [comment]
Default askpass is in place.

**Comment by aasutossh** [comment]
I am using Manjaro KDE with neovim. I am getting following error on pushing(using ssh).
```
ssh_askpass: exec(/usr/lib/ssh/ssh-askpass): No such file or directory
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights                                                                                                                                   
and the repository exists.
```

**Comment by tpope** [comment]
What does `:echo exepath('ssh-askpass')` report?

**Comment by aasutossh** [comment]
Nothing. I don't get any output.

**Comment by tpope** [comment]
How about `:echo $SSH_ASKPASS`?

**Comment by aasutossh** [comment]
Sorry, I should have mentioned earlier. Both `:echo $GIT_ASKPASS` and `:echo $SSH_ASKPASS` doesn't output anything.

**Comment by tpope** [comment]
Try `:Git --no-pager push`

**Comment by aasutossh** [comment]
> `:Git --no-pager`

Asks for ssh password. Thanks.

**Comment by Whiskas101** [comment]
I tried `:Git --no-pager push`

It doesn't seem to prompt you for a passphrase, using the default `:term` terminal doesn't cause this same issue.

The only output is: 
git@github.com: Permission denied (publickey).            fatal: Could not read from remote repository.                                                                       Please make sure you have the correct access rights       and the repository exists.    

I am not sure what's the correct approach to fixing this
