### ISSUE TITLE
Ggrep doesn't appear to work properly any more in NeoVim or Vim 8

### ISSUE THREAD

**Issue by matthewbdaly** [tpope/vim-fugitive#1297]
I'm running Neovim (built via Homebrew) on Mac OS X Mojave at work. I'm using vim-plugged to manage my plugins.

Today I ran `PlugUpdate` to update my installed plugins and the `Ggrep` command doesn't appear to work properly anymore. Running the initial command shows a list of the matching items and the prompt `Press ENTER or type command to continue` in the quickfix window, as usual, however on pressing Enter it closes without opening the usual window of matching items.

I've tried deactivating all the other plugins I'm using and commenting out all the rest of the configuration, and that doesn't appear to make any difference. If I load Vim 8 with the same configuration, it does seem to work as expected, so this appears to be NeoVim-specifc.

**Comment by matthewbdaly** [comment]
I've run `git bisect` locally and it looks like the issue was introduced by the commit [0a758c22b313bde965714ce4027d36bf14224093](https://github.com/tpope/vim-fugitive/commit/0a758c22b313bde965714ce4027d36bf14224093).

**Comment by matthewbdaly** [comment]
Correction: It does look like it's still happening in Vim 8

**Comment by tpope** [comment]
Sounds shell related. What `:!` command does it show when it runs? What is `:set shell?`?

**Comment by matthewbdaly** [comment]
I'm using Bash, but with Byobu, and with GNU screen as the backend.

**Comment by tpope** [comment]
When you call `:Ggrep`, what is the first line it prints?

**Comment by matthewbdaly** [comment]
When I called `:Ggrep ItemView`, the first line was as follows:

`:!git --no-pager grep -n --no-color --full-name --column ItemView 2>&1| tee /var/folders/84/7h9vrm_12hvg0m84hmc30q_10hy17g/T/nvim1cNmwv/451`

**Comment by tpope** [comment]
Oh, you said "opening the usual window". It has never opened a window. It used to use `:grep`, which means you could hack it to do so with `autocmd QuickFixCmdPost`. Now it doesn't and you can't. Nowadays I'm of the mind that's a clunky hack that isn't worth supporting, but I suppose I'd entertain a patch that fired off synthetic `QuickFixCmdPost` events, I guess.

**Comment by tpope** [comment]
I went ahead and added synthetic events. I may end up ripping them out if `:Ggrep` becomes async or for any other arbitrary reason.

**Comment by matthewbdaly** [comment]
Ah, I'd forgotten it didn't do that by default and that I'd specifically activated that behaviour.

It seems to open the quickfix window with that, but I'm now home and on a different machine. Will check it on my work laptop tomorrow, just to make sure.

**Comment by matthewbdaly** [comment]
Yes, that resolved the issue on my work laptop.
