### ISSUE TITLE
Provide package build compatible with Vim 8+ package support?

### ISSUE THREAD

**Issue by wohali** [tpope/vim-fugitive#1302]
With #922 done, is it possible to provide a ZIP/tarball download of this plugin compatible with the new Vim 8 package/plugin architecture as part of your release process?

I wouldn't have asked the author of pathogen about this if he hadn't put a (soft) deprecation notice on that repo. :wink:

**Comment by tpope** [comment]
I've been debating it. Does anyone else do so? Is there a naming convention for zip files? My read is the community has largely rejected the gratuitous nested structure in favor of just installing in `~/.vim/pack/default/start`. But I'm open to doing it as long as we don't create too much confusion.

**Comment by tpope** [comment]
Open to pursuing further if we can get a concrete plan in place.
