### ISSUE TITLE
How to show 3-windows instead of 4 when using nvim+fugitive as git mergetool?

### ISSUE THREAD

**Issue by c02y** [tpope/vim-fugitive#1306]
When I open the file containing conflict markers and execute `:Gvdiffsplit!` (a lot of info on the internet mentioned that `Gdiff` will would be smart enough to open 3 windows, but it just opens 2, I think maybe the vim-fugitive gets updates and changes it, since the I `Gdiff` it ask me to open 3 windows using `Gvdiffsplit!`), it opens 3 windows, and this is what I want:
~~~
  ╔═══════╦═══════╦════════╗
  ║       ║       ║        ║
  ║ LOCAL ║ MERGED║ REMOTE ║
  ║       ║       ║        ║
  ╚═══════╩═══════╩════════╝
~~~
instead of 4-windows which is not what I want:
~~~
  ╔═══════╦══════╦════════╗
  ║       ║      ║        ║
  ║ LOCAL ║ BASE ║ REMOTE ║
  ║       ║      ║        ║
  ╠═══════╩══════╩════════╣
  ║        MERGED         ║
  ╚═══════════════════════╝
~~~

I googled how to use vim as git mergetool, and some of them (such as https://www.grzegorowski.com/using-vim-or-neovim-nvim-as-a-git-mergetool/ or https://stackoverflow.com/questions/7309707/why-does-git-mergetool-opens-4-windows-in-vimdiff-id-expect-3) mentioned settings like this:
~~~
git config --global mergetool.fugitive.cmd 'nvim -f -c "Gdiff" "$MERGED"'
git config --global merge.tool fugitive
~~~
or 
~~~
git config --global mergetool.fugitive.cmd 'nvim -f -c "Gvdiffsplit!" "$MERGED"'
git config --global merge.tool fugitive
~~~
then `git mergetool` will open vim in 3-windows, but it open 4 windows instead of 3

How can I make vim open 3 windows when using vim+fugitive as git mergetool?

---------------------
**UPDATE**:
Sorry about this, it is my problem, didn't check `git config -l`, local config in .git/config overwrites the global in ~/.gitconfig
~~~
git config --global mergetool.fugitive.cmd 'nvim -f -c "Gvdiffsplit!" "$MERGED"'
git config --global merge.tool fugitive
~~~
is the right config.

**Comment by ianchanning** [comment]
Could you add this as an example in the readme? It's by far the best `mergetool` there is:

```
git config --global mergetool.fugitive.cmd 'nvim -f -c "Gvdiffsplit!" "$MERGED"'
git config --global merge.tool fugitive
```
