### ISSUE TITLE
Error detected while processing BufReadCmd Autocommands for "index{,.lock}"

### ISSUE THREAD

**Issue by jjohnson338** [tpope/vim-fugitive#1307]
Hi,

I've recently started seeing this error on both my Win10 comps when trying to execute a fugitive command. Think it might be related to the [defx-git](https://github.com/kristijanhusak/defx-git) plugin I've recently switched to, but I'm not seeing any git commands that should do anything other than query state in that plugin.

```
Error detected while processing BufReadCmd Autocommands for "index{,.lock}":
fugitive: sh /s: No such file or directory
```

**Comment by jjohnson338** [comment]
After doing a little bit of research, this [documentation](https://git-scm.com/docs/git-status#_background_refresh) seems to suggest that the git option `--no-optional-locks` should be used when running (potentially) multiple background git status operations.

`git --no-optional-locks status`

I added that to my local copy of defx-git, but the two still seem to be colliding.

**Comment by tpope** [comment]
Try removing this catch clause https://github.com/tpope/vim-fugitive/blob/79b1f16a7adf38ed5e202e5317cc1eabc9399528/autoload/fugitive.vim#L1872-L1873 and see if the error message includes more context.

**Comment by jjohnson338** [comment]
Here's the result of removing the catch
```
Error detected while processing function fugitive#BufReadStatus:
line 13:
E605: Exception not caught: fugitive: sh: /s: No such file or directory^@
```

**Comment by tpope** [comment]
Try doing `:echo system(FugitivePrepare(['status', '--porcelain', '-bz'])` and see if there's an error message in the result.

**Comment by jjohnson338** [comment]
With `:echo system(FugitivePrepare(['status', '--porcelain', '-bz'])` I get:
```
E116: Invalid arguments for function system
```

But with  `:!echo system(FugitivePrepare(['status', '--porcelain', '-bz'])` I get:
```
sh: /s: No such file or directory

shell returned 127
```

**Comment by tpope** [comment]
There was a typo, I missed a `)`. But that second example suggests your shell config is completely broken. What does `:!echo hello` do?

**Comment by jjohnson338** [comment]
I just rechecked my vimrc and, sure enough some defx config I copied in last night included a line that set the shell to `sh`. Removed that, and the plugins are working.

Appreciate your help. Really sorry for the trouble.
