### ISSUE TITLE
Open real file and line touched in a diff

### ISSUE THREAD

**Issue by albfan** [tpope/vim-fugitive#1309]
The whole idea is to look for some change in commits, through Glog, open any of the touched files and jump to line modified (if it still exists).

After inspecting a commit if you want to jump to a file you can do:

- move cursor to diff
`<CR>` (to open the file diff)
:Gedit to open that file (or a new file if file diff was to delete, you know)

Is there a way to jump to a file (and the hunk if it still exists in the file) directly from a commit buffer?

If there's no way right now to do it but seems interesting I can code it to add to fugitive buffer.

All the cases were you cannot jump (line was modified) file do not exist in current checkout, will show a message with the error.

**Comment by tpope** [comment]
Added just a few days ago, `:.Gblame --reverse` will take you to the commit that *removed* a line, or to the line in the work tree if it still exists. It's also mapped as `1<CR>`.
