### ISSUE TITLE
[Question] Glog usage

### ISSUE THREAD

**Issue by sodapopcan** [tpope/vim-fugitive#1312]
I recently started trying out the "new" `:Glog` in lieu of a dedicated `git-log` plugin.

I love how it loads the history into the qf list—and loads the diffs into the current window—so I don't have to switch context on navigation mappings (every day, all day, Imma `]q`ing and `[q`ing)

My question is: what is your recommended way (if you have one) of reseting this state? 
 IE, how do I cleanly get back to the file I was last editing after browsing the project history?

When running commands on the current file, we have `:Gedit` with no args or, in the case of a diff, we have `ZZ` or, in the case of a three-way diff, `:only`.

I also felt this pain with `:Ggrep`... I had a very hacky solution to get around this which I used for a couple of years before ditching it for something else.

I really love using [gv.vim](https://github.com/junegunn/gv.vim) buuuuut I'm always up for dropping a dependency if I can.

Thanks!

**Comment by tpope** [comment]
I don't really have better suggestions than "press `<C-O>` a bunch" or "open a new tab before you start". Given your focus on "resetting the state", you might want to investigate some sort of snapshotting with `winsaveview()` or even sessions. This is not my wheelhouse.

Big picture, I've always found `:Glog` pretty awkward, and furthermore big logs do not work well with the performance characteristics of the quickfix list. It's part of why I've started transitioning the name to `:Gclog`, so it doesn't sound like *the* definitive way to view the logs. I think the future is something more like `:Git log`. `:Git log --graph --oneline` is in the same ballpark as gv.vim. Use `o` to open a commit and `<C-W>q` or whatever to close it. Possible improvements include async loading, more robust syntax highlighting/map support for more esoteric formats, and maaaaaaaaaaaybe some sort of 2 pane workflow like gv.vim provides. (Of course, this also sacrifices your beloved `[q`/`]q`).

**Comment by sodapopcan** [comment]
Thank you very much for the explanation—that all makes sense to me!

**Comment by odnoletkov** [comment]
I use some custom navigation built around the jumplist. One of the maps is 'jump to prev/next *unlisted* buffer from the jumplist'. Since fugitive service buffers are unlisted this map resolves this problem for me. So after going through a bunch of fugitive buffers I just <kbd>[J</kbd> to jump back to where I started from
```vim
function s:Jump(dir, map)
    let [list, pos] = getjumplist()
    if a:dir < 0
        let list = reverse(list)
        let pos = len(list) - 1 - pos
    endif
    let list = map(list, a:map)
    let cnt = index(list, 1, max([pos, 0])) - pos
    if cnt > 0
        execute "normal! ".cnt.(a:dir > 0 ? "\<C-I>" : "\<C-O>")
    endif
endfunction

function s:JumpOtherBuffer(dir)
    call s:Jump(a:dir, 'v:val.bufnr != '.bufnr('%'))
endfunction
nnoremap <silent> [j :call <SID>JumpOtherBuffer(-1)<CR>
nnoremap <silent> ]j :call <SID>JumpOtherBuffer(1)<CR>

function s:JumpOtherListedBuffer(dir)
    call s:Jump(a:dir, 'v:val.bufnr != '.bufnr('%').' && get(get(getbufinfo(v:val.bufnr), 0, {}), "listed")')
endfunction
nnoremap <silent> [J :call <SID>JumpOtherListedBuffer(-1)<CR>
nnoremap <silent> ]J :call <SID>JumpOtherListedBuffer(1)<CR>
```

**Comment by zhangddjs** [comment]
Hi Boss, once I run `:h Git` to check the document, it don't show the usage of such like `:Git log --graph --oneline` , is it possible to add the useful usage to the help document also haha
