### ISSUE TITLE
:Gsplit opens only two panes

### ISSUE THREAD

**Issue by AckslD** [tpope/vim-fugitive#1313]
When I do `:Gdiff` (or `:Gvdiff` or similar) I only get two panes. If I understood it correctly there should be three. Is this true? If so is this a known issue? If it is an unknown issue I can try to minimize my `init.vim` (I'm using neovim) which reproduces the issue.

**Comment by tpope** [comment]
Is there a warning message at the bottom of the screen?

**Comment by AckslD** [comment]
@tpope thanks for your reply!
There is no warning message.
I was following this to get started https://medium.com/prodopsio/solving-git-merge-conflicts-with-vim-c8a8617e3633, but when I do `:diffget //3<CR>` I get the error `E94: No matching buffer for //3` which make sense since there is no third buffer.

**Comment by tpope** [comment]
Version 3.0 brought a backwards incompatible change requiring the use of `:Gdiffsplit!` for merge conflicts. There's a warning message explaining it but it is sometimes obscured by a weird old `feedkeys()` hack which I just removed.

P.S. `d3o` is equivalent to that `:diffget` command. You don't need the recommended maps.

**Comment by AckslD** [comment]
Thanks a lot @tpope! Works great :)
