### ISSUE TITLE
Ignore commits in :Gblame

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1316]
Git [has added](https://github.com/git/git/commit/ae3f36dea16e51041c56ba9ed6b38380c8421816) support for ignoring commits in `git blame` in 2.23.0:
* `--ignore-rev` to ignore single commit (repeatable)
* `--ignore-revs-file` to ignore commits listed in file
* `blame.ignoreRevsFile` config option

Some ideas on how this can be supported in :Gblame
* <kbd>I</kbd> in blame window to ignore commit under the cursor (can be used multiple times)
* <kbd>gI</kbd>/<kbd>gi</kbd> to add commit under the cursor to file specified in `blame.ignoreRevsFile`
* If `blame.ignoreRevsFile` is not set use `.git/info/blame-ignore` and assign it to the option in local git config

Also other problems I've discovered why playing with this:
* `:Gblame --ignore-rev REV` currently opens horizontal blame – you have to use `:Gblame --ignore-rev=REV` argument format
* It would be great if calling :Gblame from the blame window itself will perform as if it was called from the source window

**Comment by tpope** [comment]
First question: If you press `<CR>` on an ignored commit line, where does it jump to in the diff?

**Comment by odnoletkov** [comment]
So I'm on a line blamed to commit A. When I `:Gblame --ignore-rev=A` there are two possible outcomes:
* This line can be blamed to another commit. So now blame shows this line is blamed to B. `<CR>` brings me to this B commit's diff – on appropriate line of the diff
* Line can't be blamed to other commit. In this case blame still shows A for the line. `<CR>` opens A with cursor on appropriate diff line

Seems to be working as expected in both cases.

**Comment by tpope** [comment]
I've made the existing functionality work with the new options. I'm not interested in adding new features when the paint is still wet.

**Comment by jubalh** [comment]
Sorry for the question here.

Is there a way to have `:Git blame` always use the `.git-blame-ignore-revs` if present so I don't have to call it each time via `--ignore-revs-file=.git-blame-ignore-revs` ?

**Comment by tpope** [comment]
> Sorry for the question here.
> 
> Is there a way to have `:Git blame` always use the `.git-blame-ignore-revs` if present so I don't have to call it each time via `--ignore-revs-file=.git-blame-ignore-revs` ?

Yes, set the `blame.ignoreRevsFile` option in Git. That will also set the default in `git blame`.

> I can do `:command Gblame Git blame --ignore-revs-file=.git-blame-ignore-revs` but since `.git-blame-ignore-revs` AFAIK is a default file name I thought maybe fugitive could read that default file.

It's not a default file, just a convention.
