### ISSUE TITLE
E464: Ambiguous use of user-defined command for :G

### ISSUE THREAD

**Issue by scottstanie** [tpope/vim-fugitive#1319]
I'm trying to use `:G` to see the git status, but getting the ambiguous use error. The only other command I see that starts with 'G' is `GLVS`, but even when I run `delcommand GLVS`, I get the same `E464: Ambiguous use of user-defined command for :G`.

Is this supposed to work as it says in the README `Bring up an enhanced version of git status with :G`, and I have some setting preventing it? Or do you need to do `Gstatus` for the git status command?

(I'm using vim 8.0)

**Comment by tpope** [comment]
`Ambiguous use` means the command isn't defined. Sounds like FAQ entry 1.

**Comment by scottstanie** [comment]
Sorry, to clarify- just the `:G` command gives the error. I can run `:Gstatus`, `:Gst`, `:Gw`, and all others seem to be defined, but the single G described in the README gives the error (as well as running `g?` to search, but `:G<tab>` shows them all.

**Comment by tpope** [comment]
`:G` is relatively new, are you on the latest?

**Comment by scottstanie** [comment]
ah, I was on the fugitive.vim mirror from vim.org. 
switched Vundle to use the git url instead and it's all up to date and pretty. Thank you!
