### ISSUE TITLE
Create an output to slack

### ISSUE THREAD

**Issue by JLineaweaver** [tpope/vim-fugitive#1320]
I really like Gbrowse as a feature, but sometimes it would be nice to quick share code in slack or other IMs.  I think a cool edition would be to add a command like :Gslack or :Gim that copies to your clipboard the following:
1. The github link from Gbrowse
2. Any highlighted text formatted with ```

Here are two eamples

No highlighted text:
https://github.com/user/repo

Highlighted text:
https://github.com/user/repo#Lnumber
```
Highlighted Text
```

The code snippet could be first or the link first either way.  Wouldn't mind taking a crack at this, but haven't written any vim script before.  Would love to hear some thoughts or tips how to take this on.

**Comment by tpope** [comment]
`:Gbrowse!` copies the URL. I don't think Slack specific backtick syntax has a place in Fugitive.

**Comment by JLineaweaver** [comment]
Makes sense.  The three tick syntax should be the same for slack, discord, Microsoft teams, and others which is why I thought it could be useful.  Also not actually opening the browser, but giving the user a quick way to share what code they were talking about in an instant message.

**Comment by tpope** [comment]
`:Gbrowse!` doesn't open the browser.
