### ISSUE TITLE
Closing `:Gstatus` with multiple splits / vsplits

### ISSUE THREAD

**Issue by dhruvasagar** [tpope/vim-fugitive#1321]
If you have mutliple split /vsplit windows open and you open the `:Gstatus` window, when you close the `:Gstatus` window by either using the deprecated <kbd>q</kbd> or <kbd>gq</kbd> or <kbd>\<C-W>q</kbd>, the cursor does not jump back to the originally focused window. I find this annoying.

**Comment by tpope** [comment]
That's Vim for you.
