### ISSUE TITLE
Reload status after :terminal finishes

### ISSUE THREAD

**Issue by assembler** [tpope/vim-fugitive#1323]
When i use `P` to go through list of diffs for each file and review them, it asks the "Stage this hunk [y,n,q,a,d,K,g,/,e,?]?" after each change which is normal. However, when i reach the end (e.g. by responding with "y"), the patch window wont go away - it just stays there forever. I can only close it with `:q`, which leaves the original `:Gstatus` list out of date. If i press `R` to refresh it, it says that refreshes are automatic, so i have to do `:e` to actually refresh it and see the applied patches.

**Comment by assembler** [comment]
I can see now that using inline diff (with `=`) is much more convenient option.

**Comment by tpope** [comment]
While `=` is indeed recommended, reloading after a terminal finishes would still be ideal. The naive way - `autocmd BufDelete !*` - does not work. Does anyone know an autocommand we can tap into?

**Comment by justinmk** [comment]
Nvim has TermClose, but IIRC for Vim Bram was waiting for use-cases to justify it.

**Comment by tpope** [comment]
🙄

**Comment by tpope** [comment]
Turns out `BufDelete` does fire, it's just the rules for whether `!*` matches the buffer name are ... strange.
