### ISSUE TITLE
Make Gpush / Gpull async

### ISSUE THREAD

**Issue by Skallwar** [tpope/vim-fugitive#1324]
I have no idea about the feasibility of this, but I think it would be a nice addition for low internet connection or just a lot of commits to push / pull

**Comment by odnoletkov** [comment]
See https://github.com/tpope/vim-fugitive/issues/450

**Comment by tpope** [comment]
Yes, `:Gpush` is async with dispatch.vim, and `:Gpull` isn't because it changes your work tree.
