### ISSUE TITLE
`:Gcommit -c` resets author

### ISSUE THREAD

**Issue by joshklod** [tpope/vim-fugitive#1325]
`git commit -c <commit>` reuses the commit message _and authorship info_ from `<commit>`.

`:Gcommit -c <commit>` only reuses the commit message, and resets the authorship info.  The correct date appears in the commit message editing window, but the resulting commit has the current date.

`:Gcommit -C` works as expected.

**Comment by tpope** [comment]
We use `-F` to pass in the message and that's incompatible with `-c`. A possible fix would be to instead set a custom `GIT_EDITOR` which overrides the message file.

**Comment by tpope** [comment]
Try the `job` branch, it should solve this.
