### ISSUE TITLE
Open Gstatus on the current window

### ISSUE THREAD

**Issue by gunar** [tpope/vim-fugitive#1328]
I would like to open `Gstatus` without a new split (i.e. on the current window). Is it possible?

Thank you for the amazing work Tim!! I use `vim-fugitive` extensively every day, and it's a joy to learn new features over time.

**Comment by qstrahl** [comment]
I'm pretty sure `:Ge :` does this

**Comment by gunar** [comment]
Perfect, thank you @qstrahl
