### ISSUE TITLE
Add commit annotations

### ISSUE THREAD

**Issue by thiderman** [tpope/vim-fugitive#133]
# Add annotations to fugitive

I have recently been experimenting with a very analog feature. Any time I do :Gwrite, I jot down a little note describing what I just did. When it's time for me to commit, I look at my little notes to remind me of what I have down.  Almost all the time, the notes could've been the body of the commit message.  This saves me the time of diffing the staged files to refresh my mind of what exactly I have done.
It works nice, but it's inefficient since I write it on paper.
### So, I propose a feature:

Add a function that takes one argument: an annotation string. The string is stored somewhere, and when it's time to commit the body of the commit message is made out of the string(s) you have stored.
### I have some thoughts about the implementation:
- At least for me, the function would almost always be called in tandem with :Gwrite. Maybe adding a second optional argument to :Gwrite for the annotation strings? Or, add a wrapper that calls them both?
- "annotations" might not be a very good term since **git annotate** is a deprecated name for **git blame**. Naming suggestions are very welcome!
- How are the strings stored?
  1. As variables within vim would be the cleanest, but it would not carry between sessions.
  2. As a file within the repo. Would carry across vim sessions, but could feel clutter-ish.
  3. A user-defined location (~/.local/share/fugitive?)
  4. Some other magic way within git that I am not wizard enough to know about.
  5. All of the above, with user configuration to choose which.
#### P.S.

I wasn't sure if I should have sent you a PM or opened an issue, but I chose the latter so that others could give feedback as well.

**Comment by CaptainQuirk** [comment]
Hi richo,

I'm using [vim-bookmarks](https://github.com/MattesGroeger/vim-bookmarks) for this. I add an annotated bookmark and when it's time to commit, I can display the list of annotations and stage/commit chunks accordingly.

**Comment by tpope** [comment]
Agree with #912 that a notes feature would supersede this.
