### ISSUE TITLE
Is there a way to disable default mappings

### ISSUE THREAD

**Issue by albertnetymk** [tpope/vim-fugitive#1331]
Some of my own mappings in vim collide with the ones defined in fugitive. I wonder if there's a way to disable some or all default mappings.

**Comment by tpope** [comment]
`let g:fugitive_no_maps = 1` disables the global maps.

**Comment by albertnetymk** [comment]
Super; thanks for the prompt reply. Do you think if it makes sense to add that in the doc and maybe along with it, a few more words on how to provide custom mapping to those functionalities?

**Comment by tpope** [comment]
Documented the option. Defining your own maps is laid out in https://github.com/tpope/vim-fugitive/issues/1080#issuecomment-521100430. I'm not ready to commit that to the documentation.

**Comment by albertnetymk** [comment]
Super; thank you very much.
