### ISSUE TITLE
Redundant jump when opening :Gstatus

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1333]
After opening `:Gstatus` the cursor is on the first line and <kbd>CTRL-O</kbd> moves it to the second line. Need to use it twice to go back to where I came from. Jumplist looks like:
```
 …
   2     1    0 previous/file
   1     2    0 Merge: origin/master
>
```

**Comment by tpope** [comment]
Probably fixable with a well placed `keepjumps`.
