### ISSUE TITLE
Gdiffsplit: maps "cw" (amend commit) inconsistently

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-fugitive#1339]
I was confused by "cw" being mapped after using ":Gdiff stash" in the fugitive buffer.

The mapping is not present with only ":Gdiffsplit" (or ":Gdiff :0" (which appears to be the default behavior)).

1. I cannot see how "amend the last commit" is a suitable action for when in a fugitive diff buffer.  (it caused to amend the last commit when I've meant to use the builtin "cw" (accidentally))
2. the maps should be consistent for all diff buffers (i.e. also for ":Gdiff stash" etc) likely?

vim-fugitive 26f6037 (initially with b97a9ab)

**Comment by tpope** [comment]
I'm moving away from map micromanagement and towards having a single set of maps for all read only buffers. Reading between the lines, your underlying complaint is "accidentally invoking `cw` on the wrong side of a diff is *extremely* inconvenient", which, fair point, I'll think on it. Perhaps `cw` should behave like `cf` and require and additional `<CR>` for confirmation.

**Comment by blueyed** [comment]
Yes, confirmation would be good.

Additionally it should also be on the `:Gdiff` then, no?

**Comment by tpope** [comment]
The command is irrelevant, only the destination matters. If the buffer is `'nomodifiable'`, you'll get the full spread of maps.
