### ISSUE TITLE
Option to restore push/pull/fetch output

### ISSUE THREAD

**Issue by amadeus** [tpope/vim-fugitive#1340]
First off, I want to say that I've been really enjoying all the new updates and improvements to Fugitive, so thank for your continued great work, it's definitely appreciated!

One area, however that I do have a request about, is restoring the live output for push, pull and fetch.

One major reason for this is because a few repos I work on are very large, and all these commands tend to be a pretty slow. Having to just sit for a couple seconds in locked up silence while I wait with no real confirmation or status as to what's going on AS it happens, isn't great. Also, for cases like fetch, I find it really helpful to see the output of what branches were just fetched.

The fetch problem is slightly helped the `-P` and `-p` variants, but they are both additional typing I need to remember (I usually forget to add it and then the info is lost forever). Also because these repos I work on are pretty slow, I still have to sit awkwardly and wait. I think some visual information as things are happening is really useful and feels better.

I also understand this is probably a niche request, I have weird needs, and I see how in most cases, like small projects or personal repos, it's nicer to hide it, but it would be really nice to get it back if possible, perhaps as an option or something.

**Comment by tpope** [comment]
Are you referring to the fact that `:Git push` calls `:Gpush` now?

**Comment by amadeus** [comment]
Yeah that might be the source of the change. I would often use `:Git fetch` or `:Git push`

**Comment by tpope** [comment]
`:Gpush` uses Dispatch's `:Make` if available and `:silent make!` if not. Both of these should show live output by default if `'shellpipe'` contains `tee` - the default everywhere but Windows, I believe. Are you on Windows?

You can always see the output afterwards with `:copen`.

**Comment by amadeus** [comment]
I am on macOS, calling `set shellpip?` shows: `shellpipe=2>&1| tee`

[video example](https://cdn.discordapp.com/attachments/365662117191352320/624675648484540425/example.mp4)

This particular fetch wasn't too bad, but that was due to nothing to fetch. It tends to be more of an issue with pushes or pulls that trigger rebases.

**Comment by tpope** [comment]
Vim? Neovim? MacVim? With or without dispatch.vim installed?

If there's nothing to fetch, of course there will be no output.

**Comment by amadeus** [comment]
MacVim - I don’t have Dispatch installed. I can try with that thought.

**Comment by zoomido** [comment]
I'm also having this problem on Neovim [NVIM v0.4.3] (I'm running neovim in a linux box which I ssh into if that matter) when running :G push or :G pull.
`shellpipe=2>&1| tee` and I've tried with & without vim-dispatch. No automatic ouput unless I manually run :copen. Is this the intended behaviour, and if so, can it be set to automatically open when done?

**Comment by tpope** [comment]
`:Git pull` now synchronously echoes output. `:Git fetch` and `:Git push` remain asynchronous and are captured by the quickfix list. Long term these will probably change to be synchronous as well, but only after adding a general purpose async mechanism.

In the mean time, you could probably rig up `QuickFixCmdPost` to automatically open the window when done. Alternatively, `:Git --no-pager push` currently sidesteps the async behavior, but this **will probably change**.

**Comment by FinallyFinancialFreedom** [comment]
`:Git --no-pager push` is great. i need to see the output
