### ISSUE TITLE
20Gstatus isn't remembered.

### ISSUE THREAD

**Issue by WooterTheTroubleshooter** [tpope/vim-fugitive#1341]
I use `Gstatus` to resolve merge conflicts, so when I have conflicts I used to open vim, type `:Gstatus`(`:G` now) and use `dv` to resolve the conflicts one by one.

Since `Gstatus` is not in a preview window any more, the status window does not close on `Gwq`, which is very helpful. However, when using `dv` the split starts at 50%. (Which I understand may be helpful if using `Gstatus` to do inline diffs).

To workaround the height, I have found in the issues that `20Gstatus` can be used to open a small `Gstatus` window. To do this, one must first open a file and then type `20Gstatus`. On the first `dv` the split respects the height, but after the second `dv` the split is back at 50% having me resize the split everytime after `dv`.

Is there a setting to set the splitlocation that `Gstatus` can use? Or have the size set to Gstatus persist?

I also found that `Gstatus!` invokes the old behavior, but since the window does not close after `Gwq` I find resizing the diff the smallest annoyance of the two.

**Comment by tpope** [comment]
Vim provides `'winfixheight'` and `'noequalalways'` to give you more control over window sizing. Apply them as you see fit.

**Comment by WooterTheTroubleshooter** [comment]
`'winfixheight'` seems to be working out. Thank you!

**Comment by tpope** [comment]
So don't use `:Gwq`? `:Gw` should be adequate.
