### ISSUE TITLE
Gstatus issues

### ISSUE THREAD

**Issue by dortin7** [tpope/vim-fugitive#1343]
The first thing I wanna say, I love all of your plugins, also I really appreciate this most recent update, so here is a very small list of issues that I found related to `:Gstatus`:

```
Neovim: 0.4.2
SO: GNU/Linux Solus 4
```

- [x] ~~Can't open :Gstatus on neovim's welcome screen~~
![image](https://user-images.githubusercontent.com/20261354/65392036-cc2cbd00-dd35-11e9-9d98-282e137a468c.png)
~~I need to open a file, even if I'm in a git project folder.~~
~~This is really important since it gives me quick access to recently edited files that I'm working on~~

- [x] Can't recover deleted files pressing `X`, here is the error
```
fugitive: error running `git -C /my/project/folder --literal-pathspecs hash-object -w -- ./my-deleted-file`: fatal: Cannot open './my-deleted-file': File doesn't exist
```
So I manually need to do `git checkout -- my-deleted-file`
PD: In previous versions, it worked perfectly by pressing `U`

- [ ] When I'm fixing conflicts it does not mark the conflicted files, which is very confusing, so I need to do a `git status` in another terminal window to check them out
![image](https://user-images.githubusercontent.com/20261354/65392215-e5366d80-dd37-11e9-9899-25ef2db15b2c.png)

- [x] A number with `-` character stage all files, you can try it typing `3-` on the fugitive status window. To avoid that behavior I need to do something like `V2j-`

**Comment by justinmk** [comment]
@dortin7 you might want to try Nvim 0.4.2, the latest stable release. 
binaries here: https://github.com/neovim/neovim/releases

**Comment by dortin7** [comment]
@justinmk Thanks, I was testing my issues with the appimage for neovim 0.4.2, but unfortunately they are not working yet :(

**Comment by justinmk** [comment]
ok, that at least rules out any problems fixed since 0.3.8.

> Can't open :Gstatus on neovim's welcome screen

You need to use `:G`, see https://github.com/tpope/vim-fugitive/issues/1338 .

**Comment by dortin7** [comment]
@justinmk Thanks! I'm going to strike out that checkmark in the description.

Just remembered one point:
- A number with `-` character stage all files, you can try it typing `3-` on the fugitive status window. To avoid that behavior I need to do something like `V2j-`

**Comment by tpope** [comment]
> * [ ]  Can't recover deleted files pressing `X`, here is the error
> 
> ```
> fugitive: error running `git -C /my/project/folder --literal-pathspecs hash-object -w -- ./my-deleted-file`: fatal: Cannot open './my-deleted-file': File doesn't exist
> ```
> 
> So I manually need to do `git checkout -- my-deleted-file`
> PD: In previous versions, it worked perfectly by pressing `U`

Fixed.

> * [ ]  When I'm fixing conflicts it does not mark the conflicted files, which is very confusing, so I need to do a `git status` in another terminal window to check them out

Conflicted files are shown with a `U` sigil. Furthermore, non-conflicted files during a merge are staged, so I am strongly inclined to believe your screenshot of a bunch of unstaged files is user error, until demonstrated otherwise. Did you accidentally invoke `:Git reset` by pressing `U`?

> * [ ]  A number with `-` character stage all files, you can try it typing `3-` on the fugitive status window. To avoid that behavior I need to do something like `V2j-`

Wow, my first ever off by 2 error.

Note that I'm strongly considering deprecating a count here, for symmetry with commands like `X` which use the count for other purposes.

**Comment by dortin7** [comment]
@tpope 
> Conflicted files are shown with a U sigil. Furthermore, non-conflicted files during a merge are staged, so I am strongly inclined to believe your screenshot of a bunch of unstaged files is user error, until demonstrated otherwise. Did you accidentally invoke :Git reset by pressing U?

That screenshot is from a git rebase with another branch, when the commit order is something like this:

-> Commit
-> Commit
-> Commit with conflicts (my screenshot)
-> Previous commit
-> Previous commit

Maybe I'm very used to the previous version and I'm not getting the new fugitive status window right?

**Comment by tpope** [comment]
If the screenshot is from a rebase why does it say `master` in the statusline?

**Comment by dortin7** [comment]
Cause I was rebasing from another branch to master, however, I was checking my zsh history, I made a `gstp` (`git stash pop`) instead of `gst` (`git status`) with this plugin https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/git/
