### ISSUE TITLE
Nvim: Gstatus Doesn't Update When Writing Index Buffer From Diff Split

### ISSUE THREAD

**Issue by raisin-loaf** [tpope/vim-fugitive#1345]
I think I'm a super edge case here cause I imagine most people stage hunks using the inline diff view from `:G` but muscle memory compels me to highlight the file, `D` and then `do` the sections I want into the index copy before `:w` to stage the changes. Previously this would cause the GStatus window to refresh, showing the staged changes, however now that only happens if I make it the active window or manually `:call fugitive#ReloadStatus`.

I've gone back through the commit history and it seems to have started from [here](https://github.com/tpope/vim-fugitive/commit/3684c01ef4bbf3ad1d5cae258bae0bd044054e9e) but my current knowledge of VimL is almost zero so I can't make any useful suggestions. This isn't a problem in regular Vim, of course.

Feel free to tell me using inline diff is what I should be doing, and many thanks for your wonderful work. 🙂

**Comment by tpope** [comment]
Does it work in vanilla Vim?

**Comment by raisin-loaf** [comment]
> Does it work in vanilla Vim?

It does, yes. 😉

**Comment by tpope** [comment]
What is `:version`?

**Comment by raisin-loaf** [comment]
Vim, where everything is working fine:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 21 2019 04:10:35)
Included patches: 1-197, 322, 377-378, 550, 649, 651, 703, 706-707
Extra patches: 8.1.1401, 8.1.1382, 8.1.1368, 8.1.1367, 8.1.1366, 8.1.1365, 8.1.1046, 8.1.0613, 8.1.0547, 8.1.0546, 8.1.0544, 8.1.0540, 8.1.0539, 8.1.0538, 8.1.0506, 8.1.0208, 8.1.0206, 8.1.0205, 8.1.0189, 8.1.0177
, 8.1.0067, 8.1.0066
```

Nvim is `v0.4.2`. I've tested each release back to `v0.3.4` and the problem was apparent with them all.

Thanks!

**Comment by tpope** [comment]
If you call `:Git add somefile`, does that reload the status?

**Comment by raisin-loaf** [comment]
Yup - after hitting Enter to continue the GStatus window updates to show the file is staged.

**Comment by tpope** [comment]
OS?

**Comment by raisin-loaf** [comment]
Sorry - I should've included all this to start with. It's Debian 9.11

**Comment by tpope** [comment]
Does `:echo g:fugitive_autoreload_status` report a value or an error?

**Comment by raisin-loaf** [comment]
I get:

`E121: Undefined variable: g:fugitive_autoreload_status`

**Comment by tpope** [comment]
Does the status window reload when you return focus to it?

**Comment by raisin-loaf** [comment]
Yes, it does. If I `CTRL-w j` down from the index window the status window updates.

**Comment by tpope** [comment]
Okay, this is actually the current intended behavior: Writing *any* buffer marks the associated status buffer dirty, and refocusing that buffer reloads it. I was initially confusing this with the `:Gwrite` behavior of eagerly reloading. There are two remaining mysteries: why it worked on older Fugitive versions, and why it continues to work in vanilla Vim. I'm guessing there is something in your config triggering it - either a direct call to `fugitive#ReloadStatus()` or something indirect like a shell command triggering `ShellCmdPost` - and I leave it to you to diagnose.

I don't think I want to change this behavior as reloading the status buffer can be slow, so doing it on very single write could get pretty painful. You can presumably force it with a `BufWritePost` autocommand if you really want to. Maybe one day we can make it asynchronous.

**Comment by raisin-loaf** [comment]
> Okay, this is actually the current intended behavior: Writing any buffer marks the associated status buffer dirty, and refocusing that buffer reloads it.

Ah! So I've gotten used to special treatment all this time. 🙂 

> I'm guessing there is something in your config triggering it - either a direct call to fugitive#ReloadStatus() or something indirect like a shell command triggering ShellCmdPost - and I leave it to you to diagnose.

I get the same behaviour loading Nvim with a minimal vimrc (just enabling Fugitive) and I'm pretty confident I've not configured any manual calls to `ReloadStatus()` but I'll have a look around.

> You can presumably force it with a BufWritePost autocommand if you really want to.

That's probably something I should've thought of before bothering you, right?

Thank you for your time. 🙂
