### ISSUE TITLE
Gcommit: use echom to keep output in message history?

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-fugitive#1347]
I think it would be good to have the history of commits in the output of `:messages` - just for information, but especially for errors.

Currently it uses `:echo` there.

Just replacing it with `:echom` does not work, since it would display newlines as "^@", but it could e.g. loop over the lines calling `:echom` on them separately, or use another trick.

Maybe it makes sense to only keep the first line for non-errors (so that you have the commit hash in the history, but not too many extra lines).

**Comment by justinmk** [comment]
> since it would display newlines as "^@",

That's a feature IMO. Though less useful since :messages wraps the line anyway.

**Comment by blueyed** [comment]
> That's a feature IMO.

Hmm, does not look too good though?!
```
[32bit d7bae2dce] fixup! WIP: ci: Travis: simplify 32bit build^@ Date: Wed Sep 25 04:09
:19 2019 +0200^@ 1 file changed, 6 deletions(-)
Press ENTER or type command to continue
```

In contrast to:
```
[32bit 094e04204] fixup! WIP: ci: Travis: simplify 32bit build
 Date: Wed Sep 25 04:09:19 2019 +0200
 1 file changed, 6 deletions(-)
Press ENTER or type command to continue
```

In this case the second output is more readable obviously.

> Though less useful since :messages wraps the line anyway.

With `:mess` it still has the "^@" there.  (just to be clear)

**Comment by tpope** [comment]
Feels super arbitrary, why `:Gcommit` and not the dozen or so other commands that Fugitive supports?

**Comment by blueyed** [comment]
My motivation was to have messages for repo-modifying actions there.  When using git from the shell I like being able to scroll up to find previous commit hashes for git-reset etc (they are displayed in the prompt).

Anyway, you can always stick to reflog etc I guess when needed.
