### ISSUE TITLE
how to stage after D on Gstatus?

### ISSUE THREAD

**Issue by thisguychris** [tpope/vim-fugitive#1349]
Hi @tpope 👋 
Thank you for the 3.0 update! I love the inline diff! I know that you can stage visual selection via `-`. However, I was wondering what kind of workflow works when you do a G then press D on a file, I've tried doing `do`, `dp` but it doesn't stage the file, it just seems to discard a change?

**Comment by tpope** [comment]
Staging happens when you write the buffer on the left.

**Comment by thisguychris** [comment]
@tpope I guess the question is, what's a typical workflow if you're in diff mode (D after G)? How do I stage visual selection? doing a `dp` seems to discard it?

**Comment by tpope** [comment]
The Vimcast in the README covers it.

**Comment by thisguychris** [comment]
@tpope sorry about this, I did check the readme and saw the vimcast (I thought 3.0 had a different workflow because it seems it's not working on my machine), it turns out doing a `dp` on visual mode just drops the hunk? If I do a `diffput` on a visual it does the correct thing. Is this a bug?

**Comment by thisguychris** [comment]
nevermind, I thought `do` was analogous with `diffget`, it turns out `do` is a range less command, so it can't stage in visual mode.
