### ISSUE TITLE
Gblame doesn't reset scrollbind after closing

### ISSUE THREAD

**Issue by adamse** [tpope/vim-fugitive#1350]
1. Opened a file
2. `:Gblame`
3. Close blame window with q
4. File window still has `scrollbind`

**Comment by tpope** [comment]
This is one of those things a rogue autocommand could wreck havoc on. Try with a stripped down config.

**Comment by adamse** [comment]
Here's what I think must have happened:

1. open file
2. :Gblame
3. :split
4. close blame
5. The (new) split window still has scrollbind

**Comment by tpope** [comment]
That would explain it! I don't think there's anything Fugitive can+should do in this case.

**Comment by adamse** [comment]
For my reference: cursorbind is the other option that confuses things when this happens.
