### ISSUE TITLE
E492: Not an editor command: Gcommit

### ISSUE THREAD

**Issue by pappasam** [tpope/vim-fugitive#1353]
The command "Gcommit" is not present in the latest master. This breaks any functionality that relies on it. It worked yesterday, so a recent change broke it.

```vimL
:Gcommit
" Output: E492: Not an editor command: Gcommit
```

I'll look into it later if I have time, but putting the issue here in case someone else is able to get to it first.

**Comment by liujoey** [comment]
It was introduced from 1b292303c2ba26887e8550c2b54428a9c918e009
:Gstatus doesn't work neither.
But :G command works.

**Comment by tpope** [comment]
It's present if you edit a file. The blank buffer support is in flux.

**Comment by tpope** [comment]
There's something else going on.

**Comment by b-v** [comment]
For future reference, the command `:Gcommit` has been replaced by `:Git commit` as shown in the documentation [here](https://github.com/tpope/vim-fugitive/commit/4a24804adc25f915520c57a5504c45ca70e590e6).
