### ISSUE TITLE
Gstatus & Gblame not available

### ISSUE THREAD

**Issue by dhruvasagar** [tpope/vim-fugitive#1354]
Hi,

I looked through the source but couldn't figure out why, however I notice that it works for me at the commit c1244ea7d0445977cf63d3ba5d12ba553f9739bc.

**Comment by dhruvasagar** [comment]
NOTE: I wrote my own plugin manager so I understand that it's possible that the issue is how I load (uses packages) the plugin, however the fact that it works perfectly fine at the commit c1244ea7d0445977cf63d3ba5d12ba553f9739bc is what leads me to believe the issue is possibly in fugitive itself. Any thoughts you can share would help.

If you'd like to look at my plugin manager it's https://github.com/dhruvasagar/packup

**Comment by tpope** [comment]
#1355
