### ISSUE TITLE
Gcommit not recognized as a command

### ISSUE THREAD

**Issue by bothyhead** [tpope/vim-fugitive#1355]
This is the first bad commit: 49287b6e874cf31bf3fc2e239be21b096ff4cc3e

**Comment by bothyhead** [comment]
I can reproduce this on both Windows and Linux

**Comment by bothyhead** [comment]
Ah, I see you have already responded to this in another user's ticked. I will close my ticket.

**Comment by tpope** [comment]
Literally just closed the same goddamn issue. #1353
