### ISSUE TITLE
Reverse blame jump doesn't work for the boundary edge case

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1359]
Lets say I'm at commitA:file blob. If I <kbd>1\<CR\></kbd> on a line which happens to be reverse-blamed to an *immediate* child of commitA – commitB – I'm taken to a commitA instead of commitB.

This happens because in that situation `git blame --reverse commitA..` blames this line to `^commitA` – with the leading `^`. (My understanding is boundary commit can't be displayed directly – only with `^`)

There is a condition currently that explicitly skips leading `^` for the reverse blame. So the jump doesn't work properly. Removing this condition resolves the issue:
```diff
diff --git a/autoload/fugitive.vim b/autoload/fugitive.vim
index 4716578..d45678f 100644
--- a/autoload/fugitive.vim
+++ b/autoload/fugitive.vim
@@ -4684,7 +4684,7 @@ function! s:BlameCommitFileLnum(...) abort
   let commit = matchstr(line, '^\^\=\zs\x\+')
   if commit =~# '^0\+$'
     let commit = ''
-  elseif line !~# '^\^' && has_key(state, 'blame_reverse_end')
+  elseif has_key(state, 'blame_reverse_end')
     let commit = get(s:LinesError('rev-list', '--ancestry-path', '--reverse', commit . '..' . state.blame_reverse_end)[0], 0, '')
   endif
   let lnum = +matchstr(line, ' \zs\d\+\ze \%((\| *\d\+)\)')
```

Not sure what was the original intention of that condition and if this breaks something else

**Comment by tpope** [comment]
I don't remember, if you're confident this is the correct decision send a PR.
