### ISSUE TITLE
Jump to blamed commit directly from the "old" line in diff

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1360]
Currently if I press <kbd>\<CR\></kbd> on an "old" line (staring with `-`) in the diff it brings me to this line in the old version of the file. This has a nice symmetry with behavior for "new" lines. But I find I actually never want to anything with this old file version. I always just <kbd>\<CR\></kbd> again to get to the previous commit which changed that line. In other words for the "old" lines I just always <kbd>\<CR\></kbd><kbd>\<CR\></kbd>.

Can we skip the intermediate step with the old file version and jump directly to the previous commit for the line from "old" lines of the diff? Or am I missing an important use case for the current behavior?

**Comment by tpope** [comment]
No.
