### ISSUE TITLE
Focus for Gdiffsplit changed unexpectedly

### ISSUE THREAD

**Issue by kaihowl** [tpope/vim-fugitive#1361]
After 645406f592745b84f3c1b6f789114d3d4dac142c was merged, the focus behavior for diffs triggered via `dd` in a `:GStatus` window changed.

__Reproduction__
Given a repository with a single unstaged change, opening the git status window with `:G` or `:Gstatus`, then navigating to the unstaged change with `ctrl-n`, then pressing `dd`.

__Old behavior__
Two-way diff opens up, cursor briefly jumps to the right file (the current working copy's version of the file with the unstaged changes) and then focusses on the left file.

__New behavior__
Two-way diff opens up, files are correctly displayed as before, yet the focus remains on the right file and does not jump back.

Is this an intended change or a side effect? Should I simply adapt my workflows? Or is this something that I have to configure myself somehow?

Thank you so much for this awesome vim plugin! I cannot think of using git without fugitive. :heart:

**Comment by kaihowl** [comment]
Furthermore, saving the buffer for the staging area (left hand side), used to update the still open `:Gstatus` buffer. This is not necessarily linked to the commit mentioned above, though. If necessary, I can bisect that problem separately and also provide more detail.

**Comment by tpope** [comment]
This is intended, as I wanted to make it consistent with the behavior during a merge conflict.

This might one day come back as a flag - `did`, `div`, etc - but I want to do that with some sort of dispatcher, not by doubling the number of maps.

**Comment by tpope** [comment]
> Furthermore, saving the buffer for the staging area (left hand side), used to update the still open `:Gstatus` buffer. This is not necessarily linked to the commit mentioned above, though. If necessary, I can bisect that problem separately and also provide more detail.

I made the decision that updating on writing the index buffer but not the worktree buffer was more confusing than helpful, and compromised on having both *lazily* update when the status buffer is re-focused. I'm not sure this was the right decision.

**Comment by kaihowl** [comment]
Thank you for the detailed and quick answers. I will just update my workflow and adapt to the new style. Your reasoning makes sense to me. For the lazy update I also fully agree. This makes it more consistent and predictable.
