### ISSUE TITLE
Run `:Gedit` upon opening Vim?

### ISSUE THREAD

**Issue by jesseleite** [tpope/vim-fugitive#1363]
In my dotfiles install script, I `vim +PlugInstall +qa` to open vim, run `:PlugInstall`, then quit.

I figured I could do similar with `vim +Gedit` to run `:Gedit` upon opening vim, but I get this instead:

![Screen Shot on 2019-10-02 at 12-02-35](https://user-images.githubusercontent.com/5187394/66060984-8ed1e780-e50c-11e9-859d-ff14d24ea320.png)

Yet, I can manually run `:Gedit`.  Curious why this might be?

**Comment by tpope** [comment]
Short answer is use `vim +G`.

**Comment by jesseleite** [comment]
My bad 😳, ran `:PlugUpdate`.  Now I can `vim "+Gedit :"`.

PS. @tpope, Do you see any issue with using `:Gedit :` over `:Gstatus` so that the status buffer opens in the current window?

**Comment by tpope** [comment]
No issue, it's a deliberate feature.
