### ISSUE TITLE
Gdiff and .tex files

### ISSUE THREAD

**Issue by choufleur** [tpope/vim-fugitive#137]
Thanks a lot for fugitive. Sorry, this is probably a completely stupid issue.
when I Gdiff a .tex file, vim does open two buffers correctly, but I have to set diff set scrollbind set wrap in each of them, because these variables are not on as they probably should. This does not happen with non .tex files as far as I know. On the other hand this does not seem to be a vimdiff issue, running vimdiff on these two .tex files displays everything correctly. Any clue of what is going on ?

**Comment by tpope** [comment]
Report back if still an issue.
