### ISSUE TITLE
:Gpush returns a Dispatch error (Win10, Neovim v0.4, Powershell)

### ISSUE THREAD

**Issue by thekpaul** [tpope/vim-fugitive#1375]
After solving #435 by prepending forward slash, the `:Gpush` that worked before returns the following error message:
```
Error detected while processing function fugitive#Command[17]..<SNR>106_PushCommand[1]..<SNR>106_Dispatch:
Can't open errorfile C:\Users\????\Appdata\Local\Temp\nvimJDL4mu\44
```

Neovim's version is 0.4.2 and PowerShell configs are:
```vim
if has('win32')
    set shell=powershell
    set shellquote= shellpipe=\| shellxquote=
    set shellcmdflag=\ -NoLogo\ -ExecutionPolicy\ RemoteSigned\ -Command
    set shellredir=\|\ Out-File\ -Encoding\ UTF8
endif | "Set Default Shell Application to PowerShell
```

**Comment by tpope** [comment]
Does it work if you change the conditional to `&shellcmdflag =~# '^/\|-Command'`?

**Comment by thekpaul** [comment]
No, it returns error message "Unknown Option: ^/|-Command".

**Comment by tpope** [comment]
Change the *conditional*.

**Comment by thekpaul** [comment]
Oh right, my bad. Now I get a different error `103_PushSubCommand[1]` instead of the `106` earlier.

**Comment by tpope** [comment]
That's not an error, it's one entry in a stack trace.
