### ISSUE TITLE
Glog very slow on a large repo

### ISSUE THREAD

**Issue by amadeus** [tpope/vim-fugitive#1380]
I am noticing that when invoking `:Glog` on an internal repo that is very large, the quickfix shows immediately, but then MacVim completely locks up for a very long time. I haven't let it actually finish, but pressing `<c-c>` seems to stop it, and then I can navigate the quickfix as expected, although not all the commits show, many of them do.

I ran a quick profile and noticed these results

```
FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
  983  64.828486  64.088202  <SNR>126_QuickfixSet()
    1  71.643366   4.662833  <SNR>126_QuickfixStream()
19641   1.583629   1.279499  <SNR>126_LogParse()
 1977   0.709139   0.537294  FugitiveExtractGitDir()
 1976   0.796506   0.529938  fugitive#Find()
19641              0.304130  <SNR>126_LogFlushQueue()
 3966              0.241814  IsGitBuffer()
 1978   0.341097   0.222194  MyRelativePath()
    1              0.204746  gitgutter#all()
 3958   0.908568   0.186836  FugitiveGitDir()
 3954              0.130405  FugitiveIsGitDir()
  987   1.314895   0.126745  fugitive#Head()
 1976              0.058726  fugitive#CommonDir()
 3955              0.050583  <SNR>34_Tree()
 1978              0.043652  lightline#link()
  994   0.145713   0.041712  MyMode()
 5928              0.040221  <SNR>126_Slash()
 3958              0.029634  <SNR>34_Slash()
  994   1.850874   0.024603  MyFugitive()
 1978              0.024147  <SNR>29_TruncatePath()
```

This might just be because there are so many commits? However, I use another plugin that utilizes fugitive under the hood - (https://github.com/junegunn/gv.vim) and invoking GV loads up the entire commit history with almost no delay (there are around 40,000 commits in the repo), so I'd imagine that the quickfix could be populated with this full list instantaneously?

**Comment by tpope** [comment]
Unfortunately that's not Fugitive, it's Vim itself. Adding an item an item to the quickfix list appears to scale linearly with the number of existing buffers, which means adding n items to the quickfix list exhibits O(n^2) complexity. Check out these times I just measured on a big repository and see for yourself:

* `:Glog  -8000`: 1.8 seconds
* `:Glog -16000`: 8.4 seconds
* `:Glog -32000`: 45.8 seconds

I even tried making it asynchronous, but that doesn't help, because it's CPU bound.

For large history operations, I recommend using `:Git log` instead.

**Comment by ilan-schemoul** [comment]
> linearly

quadratically*

> For large history operations, I recommend using :Git log instead.

Git log is also really slow for a very large number of commits. Git log -8000 or Git log -500 did the trick for me :) (for the record/future googlers)

**Comment by tpope** [comment]
> > linearly
> 
> quadratically*

I said linearly _per item_. The 10th item takes twice as long to add as the 5th item.

Resulting in quadratic aka O(n^2) complexity for the list as a whole.

> Git log is also really slow for a very large number of commits. Git log -8000 or Git log -500 did the trick for me :) (for the record/future googlers)

For a big enough history it will be slow no matter what you do. For Neovim, https://github.com/tpope/vim-https://github.com/tpope/vim-fugitive/pull/2245 removed the bottleneck in Fugitive, making Git itself the limiting factor. For vanilla Vim, I haven't measured but there's maybe room for a similar improvement.
