### ISSUE TITLE
Inconsistent Home Directory expansion in Vim.

### ISSUE THREAD

**Issue by Parakleta** [tpope/vim-fugitive#1382]
Vim has a special expansion rule for `~/[path...]:p` which effectively gets the realpath (i.e. symbolic links resolved) whereas all other uses of `:p` do not.  This presents a problem in my case because my home directory is `/home/<user>/` but `/home` is a symlink to `/usr/home` which means `~/:p` resolves to `/usr/home/<user>/` but `/home/<user>/:p` is unchanged.

This specifically interacts with the worktree code where the worktree directory is stored as an absolute (but not real/resolved) path in the `gitdir` file but fugitive cannot match it to the working directory.

As a work-around I changed the following:
https://github.com/tpope/vim-fugitive/blob/395d94764438571380ecccba4186ea0a11b35053/plugin/fugitive.vim#L169
to:
```vim
let s:worktree_for_dir[dir] = resolve(worktree)
```

I expect there's probably a better place to make this change, but I'm not so familiar with this code.

**Comment by tpope** [comment]
Not seeing the `~` connection, but regardless of the true cause, you've got the right idea for the solution. The only caveat is we need to `resolve()` before converting backslashes to slashes, in case anyone ever actually uses a symbolic link on Windows.

**Comment by Parakleta** [comment]
You're right, there isn't directly a connection to `~`, I got confused with my testing.

It feels to me that this change is probably not going to be sufficient.  There are places where you compare paths by their string representation and without calling resolve at some point on every path there will be circumstances where the comparison will fail when it should not.

I was specifically trying to solve the case that `url` and `tree` didn't match in this piece of code:
https://github.com/tpope/vim-fugitive/blob/b09c5d2523f9964add241a04862c2f8bbd7d428f/autoload/fugitive.vim#L804-L814
but it feels like the kind of problem that will pop up randomly elsewhere given that only relative or `~/...` style absolute urls will expand to the realpath using `:p`, and every other url (including `~<user>/` style absolute urls) need to have `resolve()` called on them at some point in their life.

**Comment by tpope** [comment]
We call `cd .` during detection, which has the deliberate side effect of forcing symlink resolution for the current filename. So it should be fine for any edited file.

https://github.com/tpope/vim-fugitive/blob/b09c5d2523f9964add241a04862c2f8bbd7d428f/plugin/fugitive.vim#L195
