### ISSUE TITLE
barebone

### ISSUE THREAD

**Issue by annata83** [tpope/vim-fugitive#1383]
Hi, I use a bare-bone git repo to manage my dots files. The command I use is /usr/bin/git --git-dir=$HOME/.dots --work-tree=$HOME within an alias call dots, so by doing dots status just works in the tarminal. 
Is it posible to make it work with Fugitive?

**Comment by tpope** [comment]
No idea, does it work with the `git` command?

**Comment by annata83** [comment]
No because literally the repo is created like this:
```
git init --bare $HOME/.YOURALIAS
alias config='/usr/bin/git --git-dir=$HOME/.YOUR-ALIAS/ --work-tree=$HOME'
config config --local status.showUntrackedFiles no
echo "alias config='/usr/bin/git --git-dir=$HOME/.YOUR-ALIAS/ --work-tree=$HOME'" >> $HOME/.bashrc
```
So to manage this type of repo I always have to use the designated alias, git wont reconize the project folder as a git repo. 

I haven't find a way to do it.

**Comment by tpope** [comment]
This isn't supported then, no.
