### ISSUE TITLE
Window page scroll only moves two lines in windows alone in a tab?

### ISSUE THREAD

**Issue by kenny-evitt** [tpope/vim-fugitive#1385]
In a window alone in its tab, in normal mode, `<C-f>` only scrolls by two lines. I've noticed this since installing this plugin.

This issue seems similar:

 - [Gdiff and scroll binding · Issue #203 · tpope/vim-fugitive](https://github.com/tpope/vim-fugitive/issues/203)

I'm not having problems with multiple windows scrolling simultaneously tho. In fact, I'm only seeing this problem in windows that are alone in a tab. If I open another window in a tab, then window page scrolling works as expected.

I've been opening a lot of windows via `:G ...` commands.

I admit this all rather vague! I would love some advice on how to investigate this further.

**Comment by tpope** [comment]
You mean the window created by `:G log` or whatever? What is the result of `:verbose nmap <C-F>`?

**Comment by tpope** [comment]
Oh and what is the result of `:verbose set window?`.

**Comment by kenny-evitt** [comment]
I'm seeing the weird scrolling behavior in *all* windows (that are alone in a tab), not just those created by fugitive commands.

`:verbose nmap <C-F>` outputs `No mapping found`. Both `:verbose set window?` and `:verbose set window` output `window=4`.

**Comment by tpope** [comment]
That `'window'` value sounds like the problem. You'll have to track down what's setting it. Closing because this doesn't sound like a Fugitive bug.

**Comment by kenny-evitt** [comment]
@tpope Thanks for your help!
