### ISSUE TITLE
Preview full commit message for the current line

### ISSUE THREAD

**Issue by roblevy** [tpope/vim-fugitive#1387]
Similar, but not quite the same as #405.

In VSCode, the [details hover](https://github.com/eamodio/vscode-gitlens#hovers-) allows you to see the full commit message for what you're hovering on. I find this really useful because my team sometimes uses the second "paragraph" of commit messages to justify decisions they've made.

The Vim-friendly mouse-less equivalent would be a floating window (like an autocomplete window) showing the full commit message for the current line.

I notice the mapping `<leader>gb` is not mapped to anything at the moment. Could be useful??

**Comment by tpope** [comment]
I'd say the preview window - available on `p` - is a pretty good equivalent. The paint is still wet on the floating window stuff. I'll look at it eventually.

**Comment by jmdevin** [comment]
With the release of 8.2 I'm wondering if this could be reopened. I submit [this image](https://i.redd.it/5nanw9p2dy341.png) as an example of what this feature could look like.

**Comment by tpope** [comment]
I've never been one to chase bleeding edge Vim features, it's high effort and low reward. I will evaluate popups probably when they land in the upcoming Ubuntu stable release in April.

P.S. the variable width font in that screenshot looks ridiculous, Emacs should be ashamed.

**Comment by blayz3r** [comment]
Bump

**Comment by tpope** [comment]
The `p` map works with `'previewpopup'`. I think that might be good enough?

**Comment by jmdevin** [comment]
As I understand it, the `p` map works only in fugitive buffers such as the one opened by `:Git blame`; so one would need to first do `:Git blame` and then `p` on the line in question.

I would think a map which works directly from any buffer of a git-tracked file would be better, such that doing `<some-map>` would open the popup-preview window similar to [this](https://i.redd.it/5nanw9p2dy341.png) (Trigger Warning). Essentially, open the window that one would get by doing `:Git blame` and then `p`, but without the intermediate step of doing `:Git blame`.

**Comment by tpope** [comment]
`:0,3Git blame` does what you want. It's an implementation detail, not an official interface, but I don't see it changing any time soon.

**Comment by jmdevin** [comment]
That's good enough for me. If I might ask, how exactly does that work? Why does it blame the current line? I don't really understand how the range `0,3` produces that.

**Comment by tpope** [comment]
It works that way because I programmed it to work that way. There's nothing magic about `0` other than it has no valid meaning in this context, and there's nothing magic about `3` other than it was the third thing I added as a special case.

**Comment by jmdevin** [comment]
Ah, got it. I think I should have figured that out. Thanks.
