### ISSUE TITLE
Error detected while processing function fugitive#BufReadStatus

### ISSUE THREAD

**Issue by ln2max** [tpope/vim-fugitive#1388]
When I type `:Gstatus` in a particular repo:
```
Error detected while processing function fugitive#BufReadStatus:
line   23:
E684: list index out of range: 0
```

Doing `git status` on the command line works without issue.

When I `cd` to another repo elsewhere on my system, open vim, and do Gstatus, the problem does not appear.

How can I troubleshoot the issue with the repo?

**Comment by tpope** [comment]
What is the output of `git status --porcelain=v2 -b`?

**Comment by ln2max** [comment]
```
$ git status --porcelain=v2 -b
warning: could not open directory 'public_html/': Permission denied
# branch.oid 630ea9c08012b00bba5668b87144b778a3c29db3
# branch.head interactive-help
# branch.upstream upstream/interactive-help
# branch.ab +0 -0
```
This is the branch I'm working on:
https://github.com/lncm/noma/pull/75

**Comment by tpope** [comment]
I bet that warning is tripping up the parser. I'll make it more robust. I'd still recommend fixing the permissions.

**Comment by tpope** [comment]
@odnoletkov I reworked the v2 porcelain parsing, keep an eye out for regressions.

**Comment by ln2max** [comment]
That fixed it, woops, thanks!

**Comment by odnoletkov** [comment]
@tpope tested it a bit – found no issues so far.

The v1 parser also breaks with this warning. But at least it handles it gracefully and falls back to `FugitiveHead`. So the only visible problem is upstream missing. Do you want to leave it as is?

**Comment by tpope** [comment]
Easy enough to fix.
