### ISSUE TITLE
Error when committing (Windows 10)

### ISSUE THREAD

**Issue by mg979** [tpope/vim-fugitive#1391]
I get this error (got with `:redir`):
```
".git\COMMIT_EDITMSG" 
".git\COMMIT_EDITMSG" [Unix] 14L, 377C scritti
".git\COMMIT_EDITMSG" [Unix] 14L, 377C scritti

fugitive: failed to run `cmd /c "set GIT_EDITOR=false& git commit -F "D:\Gianmaria\Dropbox (Personale)\Linux\vimrc\pack\dropbox\opt\vim-packs\.git\COMMIT_EDITMSG" "--cleanup=strip" --no-edit --no-interactive --no-signoff > C:\Users\Gianmaria\AppData\Local\Temp\VIGB6B3.tmp"` with shell=C:\WINDOWS\system32\cmd.exe shellcmdflag=/c shellredir=>%s 2>&1 shellxquote=( shellxescape="&|<>()@^
```

It only happens in this repo and in gvim, not in git bash mintty, I suppose it's because of the space in the filename, or the parenthesis, or both.

The commit fails (nothing is committed).

**Comment by tpope** [comment]
Those parentheses probably need to be escaped with `^`. Feel free to attempt, but I'm hoping to render this obsolete by switching from `system()` to `job_start()` in the next month or so.

**Comment by mg979** [comment]
I had fixed it like this, it works on my PC but I don't know for the rest

```diff
-      return s:SystemError('cmd /c "' . prefix . s:gsub(cmd, '[<>]', cmd_escape_char . '&') . redir . '"')
+      return s:SystemError(prefix . s:gsub(cmd, '[<>]', cmd_escape_char . '&') . redir)
```
