### ISSUE TITLE
Error staging change after staging rename

### ISSUE THREAD

**Issue by Anfid** [tpope/vim-fugitive#1392]
Accidentally found error, trying to add staged renamed file, that was later changed again in `:G` view.

Steps to reproduce:
1. Create (or use existing) repo with commited non-empty file
2. Rename that file
3. Stage rename, to git identifies it as a rename, not delete and create
4. Change file contents
5. Try to stage new change

Trying to reproduce this again, got the following error in neovim:

```fugitive: error running `git -C /home/<me>/tmp --literal-pathspecs add -A -- ./src/may.rs ./src/main.rs`: fatal: pathspec './src/main.rs' did not match any files```

`$ git status` output:

```
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	renamed:    src/main.rs -> src/may.rs

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   src/may.rs
```

`:G` view contents:
```
Head: master

Unstaged (1)
M src/main.rs -> src/may.rs

Staged (1)
R src/main.rs -> src/may.rs
```

**Comment by tpope** [comment]
@odnoletkov this sounds like a porcelain v2 thing?

**Comment by odnoletkov** [comment]
@tpope doesn't look like a v2 problem – at least when I try the old parser I get the same error. This line is the culprit: https://github.com/tpope/vim-fugitive/blob/b09c5d2523f9964add241a04862c2f8bbd7d428f/autoload/fugitive.vim#L3257
It tries to add both old and new path and `git add` just doesn't like non-existent paths.
