### ISSUE TITLE
Reblame issues

### ISSUE THREAD

**Issue by allopislozano** [tpope/vim-fugitive#1393]
Hi there Tim, first, your plugins are awesome! Thanks for that

I have an issue with reblaming. I fire :Gblame and the side window opens with the commit. There is a line that was changed so I want to reblame there to see the state of that line in the previous commit. If I use `p` to reblame at parent, I get a quickfix window with the parent commit, which is nice, but neither the file nor the side window change, which I would expect. 

Now if I use `~` the file and the blame window are correctly updated but the quickfix window is not shown. Why is this called reblame at grandparent?  It is reblaming at the parent commit, not at the grandparent

I think maybe the functionality is there but might be a bit unintuitive

**Comment by odnoletkov** [comment]
You mixed lowercase and uppercase P. Lowercase <kbd>p</kbd> shows commit under the cursor in the preview window. Uppercase <kbd>P</kbd> does the 'reblame at Nth parent'

**Comment by allopislozano** [comment]
Facepalm! thank you @odnoletkov
