### ISSUE TITLE
changing the window layout when doing merge

### ISSUE THREAD

**Issue by skylite21** [tpope/vim-fugitive#1394]
When I have the following in my .gitconfig:
```
[merge]
  tool = vimdiff
[mergetool]
  prompt = true
[mergetool "vimdiff"]
  cmd = nvim -d $LOCAL $REMOTE $MERGED -c '$wincmd w' -c 'wincmd J'
```

Then the mergetool will open in the folliwing layout:

```
+-----------+----------+
|           |          |
|   LOCAL   |  REMOTE  |
|           |          |
+-----------+----------+
|                      |
|        Merged        |
|                      |
+----------------------+
```
Can I achieve the same layout when using fugitive?

The only config I could find was this one:
```
[mergetool "fugitive"]
  cmd = nvim -f -c \"Gvdiffsplit!\" \"$MERGED\"
```
But this gives me three vertical windows

If this can be achieved I would love to know how!

Thanks

**Comment by tpope** [comment]
You should be able to achieve this with something similar to `-c "Ghdiffsplit :3|Gvdiffsplit :2"`.
