### ISSUE TITLE
Should `:Gdiff` Close with `gq`?

### ISSUE THREAD

**Issue by atomdmac** [tpope/vim-fugitive#1395]
The `vim-fugitive` functions that I use most often are `:Glog`, `:Gblame`, and `:GCommit`, all of which have windows that can be closed with `gq`.  However, I noticed recently that `:Gdiff` cannot be closed in this way.  (I have to use `:q` instead.)

Is this behavior intentional?  The inconsistency with the other commands seems strange to me but there could very well be a reason for it that I'm unaware of.

**Comment by tpope** [comment]
With no argument, `:Gdiff` opens a buffer that can be edited, and `gq` is a valid editing operation, so we can't map it without sacrificing other functionality.

`:Gcommit` does not in fact have a `gq` map either, for the same reason.

**Comment by atomdmac** [comment]
@tpope Thanks for the clarification!

(P.S.  When I said `:Ccommit`, I meant `:Gstatus`)
