### ISSUE TITLE
Glob completion failure blocks additional completion

### ISSUE THREAD

**Issue by rbong** [tpope/vim-fugitive#1396]
Example: completing stashes. `stash@<tab>` completes to `stash@\{0}` but `stash@\{<tab>` results in an error. If the glob didn't fail the stash would complete.

I wanted to submit a PR but there's several different solutions with pros/cons that need to be weighed, and might be mixed together. What I tried and what I found:

- Try sanitizing user strings before turning them into globs. This will not allow users to use wildcards (unsure if intentional). This is probably required to some degree no matter what since a trailing `*` currently gets turned into `**`. However it will probably get pretty complex if you want to sanitize everything. Example: `{` and `\` need to get escaped but `\{*` should not be escaped to `\\\{*`. `:help pattern` lists 40+ errors and some are not explained.
- Catch all globbing errors and return an empty list. This will cause any legitimate future completion errors to fail silently but it will definitely handle all cases.

**Comment by tpope** [comment]
On macOS it errors for `stash@{` but not for `stash@\{`. On Linux it errors for neither. Both platforms return zero matches for `stash@\{`. Does this mean you're on Windows?

**Comment by rbong** [comment]
I'm on Linux. Both `stash@{` and `stash@\{` give errors for me. Apologies if this is environment specific... I thought this was happening for a while.

**Comment by tpope** [comment]
What do`:e {<Tab>` and :e`\{<Tab>` do? For me it is exactly the same: an error for only the first on macOS and neither on Linux.

**Comment by rbong** [comment]
@tpope only `:e {` gives an error

**Comment by tpope** [comment]
What about `:call glob('\{')`?

**Comment by rbong** [comment]
That does not give an error.

**Comment by tpope** [comment]
That's the only globbing we do. What error are you even getting?

**Comment by rbong** [comment]
`E220: Missing }.`

Also happens with `vim -u NORC`. On vi 8.1.2311 with huge features.

**Comment by rbong** [comment]
Completing `stash@\{` is fixed by a2d76c4.
