### ISSUE TITLE
:Gdiff hangs on Ubuntu 18.04 with vim 8

### ISSUE THREAD

**Issue by gidgid** [tpope/vim-fugitive#1397]
I'm using Vim 8, Ubuntu 18.04 and zsh (oh-my-zsh) & vim plug
When I open a file with a merge conflict and invoke `:Gdiff` vim suddenly hangs until I kill it using Ctrl + C

I tried without success:
- `:set shell=bash`
- removed my global `.gitconfig`
- removed all plugins besides vim fugitive
- shellcmdflag is only -c
- updated vim fugitive

Any ideas what I may have missed?

**Comment by tpope** [comment]
Check if there's a child `git` process running.

**Comment by gidgid** [comment]
Not sure if there are other ways to check this (I'll be happy to know if there are) but I tried the following and could not see any running git processes:
- `ps aux`
- `ps -A`
- using htop
- `pstree`
- inspected the specific git repository but could not find anything weird there (but I may be missing something) - it also happens on every repository so it's most likely not a specific repository issue

The same problem also happens on my mac so maybe this is some vim configuration problem?

**Comment by tpope** [comment]
You can use `px auxf` to see if Vim has any child processes.

**Comment by gidgid** [comment]
I'm assuming you meant `ps auxf`
Ran it and didn't see any vim child processes
Anything else I should check?

**Comment by gidgid** [comment]
I kept digging into it and wanted to pour more information and it seems like all the diff capabilities suspend my vim (`:Gdiff` or `:Gdiffsplit`)

**Comment by tpope** [comment]
Does `:Gsplit` fail the same way? It does essentially the same thing except it doesn't enable diff mode.

**Comment by gidgid** [comment]
Just checked, `:Gsplit` works fine.
I also tried using just vimdiff without Vim fugitive as a mergetool to resolve the merge conflict and it also works fine, so it seems like the problem is only with the `:Gdiff` command

**Comment by tpope** [comment]
You say this is happening during a merge conflict; does it happen outside of one? Does it happen on both `:Gdiffsplit` and `:Gdiffsplit!`?

**Comment by gidgid** [comment]
All the different `diff` command seem to not work for some reason. They don't work during a merge conflict or without a merge conflict
I also check `Gdiffsplit!` which doesn't work as well

**Comment by ezpuzz** [comment]
I have hanging `Gdiff` on windows + Vim8 and I see continuous process spawning of git in process monitor.

**Comment by tpope** [comment]
@ezpuzz If there's any way you could figure out the arguments of that git process it could potentially narrow things down.

Other things to test:

* `:Gdiffsplit :0:%`
* `:Gdiffsplit HEAD:%`
* `:noautocmd Gdiffsplit`

**Comment by gidgid** [comment]
The first 2 commands (`:Gdiffsplit :0:%` and `:Gdiffsplit HEAD:%`) make my vim suspend but the last one does work (i.e. no suspend) - anything else I should check?

**Comment by tpope** [comment]
That strongly suggests to me another plugin or your vimrc has an autocommand that's hanging. Try disabling plugins and see if you can isolate it.

**Comment by gidgid** [comment]
I'm using vim-plug and removed all the plugins except from fugitive & vim plug.
I ran `:PlugClean` and verified no other plugins are in my  vim plug directory
`:Gdiff` keeps suspending though

**Comment by gidgid** [comment]
I cleaned out my entire `.vimrc` file and just left the plugins and now it works - so its probably something that is massed up with my configuration. I'll do a binary search and try and isolate the problem

**Comment by gidgid** [comment]
Found it! apparently I had some old code in my `.vimrc` related to some experiments I did with ctags a while back. Once I removed it, `:Gdiff` is working again
Thanks a lot for your help - it is highly appreciated
