### ISSUE TITLE
Glog and Gclog error fatal: unrecognized argument: --no-patch

### ISSUE THREAD

**Issue by benyaminl** [tpope/vim-fugitive#1398]
Hello, I used fugutive on neovim and using git on centos 7.7 I think it should run like this
http://vimcasts.org/episodes/fugitive-vim-exploring-the-history-of-a-git-repository/
I've problem with fugitive where I can't use Glog and Gclog on it. 
Is there maybe something I did wrong or such? Thanks

I'm using git 1.8.3.1

Thanks

EDIT: It seems the version 1.8.3.1 have problem with fugitive, I tried to install local git that's newer, uhm is there anyway to specify a local git? Thanks

**Comment by tpope** [comment]
Looks like `--no-patch` was added in 1.8.4. Does changing it to `-s` fix it?

**Comment by benyaminl** [comment]
Anyway how to pull it? Do I need to update my plug? 
--
