### ISSUE TITLE
Return to central/main window when closing Gstatus

### ISSUE THREAD

**Issue by roblevy** [tpope/vim-fugitive#1399]
A very common use case for me has me opening `Gblame`, or [`Twiggy`](https://github.com/sodapopcan/vim-twiggy), which both create narrow windows to the left of my main window, making some changes then opening `Gstatus` to stage and commit.

When I close `Gstatus` with `gq` (or with `:q`) I'm always returned to the narrow `Gblame` window, instead of to the main window where my code is.

It would be good if closing `Gstatus` returned you to the window you were in last.

I don't know enough about Vim to know whether this is even vaguely possible, but I thought I should ask about it anyway.

**Comment by tpope** [comment]
I don't think there's a good way to override the behavior of `:q`. You could certainly try with autocommands, but doing window management in autocommands tends to create more problems than it solves.

Remapping `gq` is much easier. Something like this would work.

```vim
nnoremap <buffer><nowait> gq :exe 'wincmd p<Bar>' . winnr() . 'wincmd c'<CR>
```

Try sticking that in `after/ftplugin/fugitive.vim`. At this time I don't think I want to change Fugitive's default to differ from Vim's default behavior.
