### ISSUE TITLE
Is there a Gdiff that looks like github PR compare branches?

### ISSUE THREAD

**Issue by jessebett** [tpope/vim-fugitive#1400]
I'm trying to increase my usage of this plugin beyond staging and committing. I need to rebase a project to get some features in the upstream master into my fork. So I thought this would be a good use of `git merge` and then `:Gdiffsplit` to handle the merge conflicts. Is this incorrect? Must I have used `:Gmerge`? I'm asking because trying to use `:Gdiffsplit` after the merge is a complete nightmare. There are many changes that are getting shown by `:Gdiffsplit` which I am not interested in and expected to be automatically merged.

What I am interested in are exactly the differences captured by the github compare branches view (when you create a new PR). Is there a way to get vim-fugitive to give me a diff that looks like that?

**Comment by jessebett** [comment]
Let me make this more concrete with an example. 

I want to compare my branch to the upstream master branch. When I do this with github the view looks like this:
![Screen Shot 2019-11-14 at 5 04 36 PM](https://user-images.githubusercontent.com/4240549/68900309-8c64cf00-0701-11ea-8272-f771c61880f4.png)

but, when I do `:Gdiffsplit` on the same file and branch (no funny business with merging yet) I see this:
![Screen Shot 2019-11-14 at 5 08 17 PM](https://user-images.githubusercontent.com/4240549/68900351-a7cfda00-0701-11ea-85b1-caa5e7099d41.png)

I understand that the latter is more correct. But what github's compare is doing is what I actually want. I only care about that one addition on line 62. Can you explain what github's compare branches is doing to ignore all those other differences? and how can I get this behaviour in fugitive?

**Comment by tpope** [comment]
What does it say at the bottom of the screen after you call `:Gdiffsplit`?

**Comment by jessebett** [comment]
@tpope not sure what you mean (I have some theme stuff at the bottom, not sure I'm looking in the right place):
![Screen Shot 2019-11-15 at 11 51 19 AM](https://user-images.githubusercontent.com/4240549/68960670-a1437000-079e-11ea-9534-3b178acba882.png)

Above screengrab is directly after calling `:Gdiffsplit specific/branch`. I've made some changes since the above, so it doesn't look the same as the github branch compare posted earlier.

Sorry if this is a documented feature that I've missed...

**Comment by tpope** [comment]
My question assumed a merge conflict as originally mentioned. It *sounds* like you want to diff against the merge base, `:Gdiffsplit ...branch`.
