### ISSUE TITLE
Gblame stopped working as a toggle

### ISSUE THREAD

**Issue by shmerl** [tpope/vim-fugitive#1401]
I updated vim-fugitive recently (haven't updated in in a while), and now doing `:Gblame` stopped working as a toogle. What happens is that doing ti second time, it for a brief moment tries to close it, and then opens it back right away.

Though it could be some neovim glitch.

**Comment by shmerl** [comment]
Nope, happens with latest neovim unstable too.

**Comment by tpope** [comment]
This was a deliberate change in 3a01f4b819b2a923074d28c3d874dc7acfb4efc5. If you want a toggle, use something like

```vim
nnoremap <Leader>gb :if &filetype ==# 'fugitiveblame'<Bar>quit<Bar>else<Bar>Gblame<Bar>endif<CR>
```

**Comment by shmerl** [comment]
Ah, thanks for the tip. Why was it removed?

**Comment by shmerl** [comment]
Any suggestion how to bind it to F5? I tried doing this:

```
nnoremap <F5> :if &filetype ==# 'fugitiveblame'<Bar>quit<Bar>else<Bar>Gblame<Bar>endif<CR>
```

But doesn't behave right.

**Comment by tpope** [comment]
> Ah, thanks for the tip. Why was it removed?

The final bullet in #1316 prompted me to pull the trigger. `:Gblame` has gotten a lot more powerful, and as a consequence reblaming has gotten a lot more useful. Plus, with the addition of an optional filename argument, it was weird that something like `:Gblame README` could actually close an unrelated blame window instead.

> Any suggestion how to bind it to F5? I tried doing this:
> 
> ```
> nnoremap <F5> :if &filetype ==# 'fugitiveblame'<Bar>quit<Bar>else<Bar>Gblame<Bar>endif<CR>
> ```
> 
> But doesn't behave right.

Looks like `<Bar>` (a.k.a `|`) isn't playing right with `Gblame`. Good thing I said "something like". This one seems to work better:

```viml
nmap <expr> <F5> &filetype ==# 'fugitiveblame' ? "gq" : ":Gblame\r"
```

This leverages the `gq` map to also return to the work tree version. Use `":quit\r"` if you want a simple window close instead.

**Comment by shmerl** [comment]
That works, thanks! I'll take a look at using reblame more effectively.
