### ISSUE TITLE
Status buffer doesn't update after write the index file

### ISSUE THREAD

**Issue by l-qing** [tpope/vim-fugitive#1404]
# Reproduce steps:
1. `:Gstatus` open the status buffer
2. `:Gdiff` open the index buffer
3. switch to index buffer
4. `:diffget` pull across the change from the working copy
5. `:write` write the index buffer

# Result:
The status doesn't update.
The current file only in the 'Unstaged' section.

# Expect:
The current file appear in the 'Staged' section.

# My temporary solution:
Add this in my .vimrc
```
autocmd BufWritePost         fugitive://*//[0]/*  call fugitive#ReloadStatus()
```
It can solve my problem.
I don't know if there is a better way

# Environment:
| Ubuntu | 18.04  |
|:------:|:--------:|
| vi |  8.0.1453 |
| vim-fugitive |  13fdeb5fa7f464266163f405f42322e6fb0d3067 |

.vimrc :
```
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
call vundle#end()
```

**Comment by tpope** [comment]
This was a deliberate change. The old behavior was to immediately update the status window for *some* writes. The new behavior is to update the status window for *all* writes, but only after the status window regains focus.

**Comment by l-qing** [comment]
@tpope thanks for your reply!

**Comment by l-qing** [comment]
I found the commit for this change.
This is because this line was deleted in `fugitive#FileWriteCmd`.

`call fugitive#ReloadStatus()`
https://github.com/tpope/vim-fugitive/commit/3684c01ef4bbf3ad1d5cae258bae0bd044054e9e#diff-4c8459efc2f0fea43a9d26047a9e5e06L1702
