### ISSUE TITLE
A command for force pushing

### ISSUE THREAD

**Issue by mrded** [tpope/vim-fugitive#1405]
Can we get a command for: `git push --force-with-lease`, something like `:Gpushforce`?

It's very useful if you do amending to last commit.

Thanks.

**Comment by tpope** [comment]
I'll add `:Gpushforce` when Git adds `git pushforce`.

**Comment by mrded** [comment]
Do ‘git write’ and ‘git read’ command exist?

**Comment by tpope** [comment]
Are you really too stupid to try `:Gpush --force-with-lease`? You're embarrassing yourself.

**Comment by mrded** [comment]
Thank you for the plugin anyway.

**Comment by thomaspeitz** [comment]
For all users searching for a solution. Add this to your vimrc:

```
command Gpushforcewithlease :Gpush --force-with-lease
```

The word after the command is your shortcut. I choosed `GpushF`.

**Comment by tpope** [comment]
You can also create, say, a `pushf` alias in your Git config and then `:Git pushf` or `:G push` will call it. (`:Gpush` is softly deprecated in favor of `:Git push` or `:G push`.)
