### ISSUE TITLE
Cannot use `:Gpush` because I have define `:Make`

### ISSUE THREAD

**Issue by vbarrielle** [tpope/vim-fugitive#1407]
Hello,

I have the following line in my vimrc: `command Make tabnew | make | cw`, but it seems to conflict with fugitive's implementation of `:Gpush`. It looks like fugitive will check for the existence of a `:Make` command and execute it when calling `:Gpush`. In my case this means I'm compiling my project when I'm trying to push.

I can workaround this by changing my alias, but I was wondering, where is the `:Make` fugitive is checking for coming from?

**Comment by tpope** [comment]
The idea is that you or a plugin can define a drop-in `:make` replacement and Fugitive will use that instead. In practice the main plugin that does this is dispatch.vim.

With a bit of tweaking, your command can be made to fit the interface, although it will also mean `:Gpush` will open a new tab, probably not what you want:

```vim
command -bang -nargs=* exe 'make<bang> ' . <q-args> | tabnew | cw
```

**Comment by vbarrielle** [comment]
Thanks for the explanation and workaround.
