### ISSUE TITLE
s:DirCheck incorrect

### ISSUE THREAD

**Issue by daaku** [tpope/vim-fugitive#1408]
I was finding that fugitive kept thinking I wasn't in a valid git repo, or that the open file didn't belong to a git repo. It would happen sometimes, and I haven't been able to narrow down the exact scenarios. I guess one consideration is the PWD when I started vim, but like I said I'm not sure.

I know this is the problem because this patch makes it work as expected:
```diff
diff --git a/autoload/fugitive.vim b/autoload/fugitive.vim
index 8f25832..67edca6 100644
--- a/autoload/fugitive.vim
+++ b/autoload/fugitive.vim
@@ -73,6 +73,7 @@ function! s:throw(string) abort
 endfunction

 function! s:DirCheck(...) abort
+  return ''
   if !empty(a:0 ? s:Dir(a:1) : s:Dir())
     return ''
   elseif empty(bufname(''))
```

What information can I provide you with to identify the underlying issue? Would be great to get rid of this local janky patch of mine.

**Comment by tpope** [comment]
The entire purpose of `s:DirCheck()` is to give an error message. Changing the function to never give an error message doesn't really demonstrate anything.

What Fugitive command is triggering the error?

**Comment by daaku** [comment]
Pretty much any command refuses to work, and it goes down the `else` path of that function. `Gstatus` for example. I guess a more appropriate title for the bug report is that something in `!empty(a:0 ? s:Dir(a:1) : s:Dir())` isn't validating my git repo as expected.

Is there any debug/context information I can provide to help diagnose?

**Comment by tpope** [comment]
What do `:echo FugitiveGitDir()` and `:echo b:git_dir` report in a buffer where the commands give that error?

**Comment by daaku** [comment]
`:echo FugitiveGitDir()` outputs nothing and `:echo b:git_dir` errors out with `E121: Undefined variable: b:git_dir`. After I apply my hack and skip `DirCheck`, they still have the same output, but `Gstatus` works as expected.

**Comment by tpope** [comment]
Is this in a file that belongs to a repo or a blank buffer?

**Comment by daaku** [comment]
A file that belongs to a repo.

**Comment by tpope** [comment]
Try with `:Gblame`.

**Comment by tpope** [comment]
What does `:echo getftype('.git')` return?

**Comment by daaku** [comment]
With or without my patch `:Gblame` gives this error: `fatal: not a git repository: ''` -- clearly my "fix" isn't very good :grinning:

`:echo getftype('.git')` returns `dir`.

**Comment by tpope** [comment]
Does `:echo expand('%:p')` give a path that's inside the Git repository (no symlinks or anything complicating things)? What does `:echo FugitiveExtractGirDir(expand('%:p'))` report?

**Comment by daaku** [comment]
`:echo expand('%:p')` gives a path inside the Git repository, no symlinks or anything unusual -- just standard files.

`:echo FugitiveExtractGitDir(expand('%:p'))` returns the associated `.git` dir I'd expect it to.

**Comment by tpope** [comment]
`FugitiveExtractGitDir()` is used to [set `b:git_dir`](
https://github.com/tpope/vim-fugitive/blob/671a85dabaed7e21aa7e435adfdad9b9461cb7d8/plugin/fugitive.vim#L241-L246) when [the buffer is loaded](https://github.com/tpope/vim-fugitive/blob/671a85dabaed7e21aa7e435adfdad9b9461cb7d8/plugin/fugitive.vim#L310). If `FugitiveExtractGitDir(expand('%:p'))` finds the Git dir, there's very little left that could be going wrong. You could try sticking some debugging statements inside `FugitiveDetect()` to confirm it's being called and that it's looking at the correct absolute path. `:echo` statements can get lost try something like `let g:last_fugitive_detect = a:path`.

**Comment by daaku** [comment]
I'm still debugging, and my vimscript foo is not the best, but here's what I see happening:

1. I open the file inside my repo (with PWD being the repo for added simplicity)
1. I call `:Gstatus`
1. It triggers `autoload/fugitive.vim`
1. It calls `s:StatusCommand`
1. It calls `s:DirCheck`

It fails here as best as I can tell. `FugitiveExtractGitDir` isn't called per my `echom` scattered around. Still debugging..

**Comment by daaku** [comment]
`FugitiveGitDir` is trying to return the `b:git_dir` before the associated `autocmd` is run (which apparently it never is for my case)...

**Comment by tpope** [comment]
`BufReadPost` fires immediately after any file is loaded. Not running implies something severely wrong with your setup. Try with a stripped down vimrc and no other plugins.

**Comment by daaku** [comment]
It was indeed! This was the offending line (though I don't quite know why):

```
autocmd BufNewFile,BufRead * if expand('%:t') == 'haproxy.cfg' | set filetype=haproxy
```

So sorry for wasting your time!
