### ISSUE TITLE
Cursor position moves to top on buffer change

### ISSUE THREAD

**Issue by hovnatan** [tpope/vim-fugitive#1409]
When fugitive buffer opened, move around, open some folds, with `:Gedit` if I switch to another buffer then come back to the fugitive buffer my folds are all closed and cursor position is moved to top. Is it possible to change this behavior?

**Comment by tpope** [comment]
Probably not, but I'd be happy to be proven wrong.

**Comment by hovnatan** [comment]
How is that when fugitive buffer is opened in a split then moving around the windows keeps the cursor position?
