### ISSUE TITLE
Option to choose password imput method

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [tpope/vim-fugitive#1410]
vim-fugitive's README says that it configures password input method automatically if it finds `ssh-askpass` or `git-gui`. But, for example, on Arch `git-gui` is a part of the `git` package. I really prefer to input me password through terminal and not through GUI. `:Git --paginate push` isn't convenient for me.

**Comment by tpope** [comment]
Note that `:Gpush` is not guaranteed to run in a terminal. I'm assuming it is on your current setup or you wouldn't be asking. I have aspirations to unify things and eliminate the possibility entirely in future versions. The recommended solution, mentioned *before* `:Git --paginate`  in the FAQ, is ssh keys and/or credential caching. If you won't use that, I quite frankly could not care less what you "really prefer".

That being said, I pushed a change to not override `core.askPass` if you set it in your Git config to an empty string. Knock yourself out, while you still can.
