### ISSUE TITLE
Problem with Gcommit editor using xonsh

### ISSUE THREAD

**Issue by meatballs** [tpope/vim-fugitive#1411]
Using `Gcommit` gives:

```
error: There was a problem with the editor 'false'
```
I'm using neovim 0.3.8, the latest version of fugitive and my default shell is [xonsh](https://xon.sh/).

I've tried setting the EDITOR environment variablewithin my xonsh config and tested that it works using `edit`. I've also tried setting the git `core.editor` config setting. Neither made any difference.

If I `set shell=/usr/bin/bash` in my `init.vim` everything works fine (but I don't want bash in my neovim terminal buffers).

**Comment by tpope** [comment]
Long term I intend to axe all shell shenanigans that tend to trip up non POSIX shells by switching to jobs. Short term feel free to investigate and send a PR. This is likely the relevant code:

https://github.com/tpope/vim-fugitive/blob/42c6fd1440cd886b0418a4902c89d0a108043750/autoload/fugitive.vim#L1256-L1263

**Comment by meatballs** [comment]
I think I've tracked this down to a bug in xonsh where it always returns an exit code of zero. I've raised an issue:
https://github.com/xonsh/xonsh/issues/3402
