### ISSUE TITLE
Unwanted tree traversal when opening files

### ISSUE THREAD

**Issue by cespare** [tpope/vim-fugitive#1412]
Hi! Thanks for the great plugin.

Recently I started using the [keybase filesystem](https://keybase.io/docs/kbfs) to store a few text files. When I open such a file in vim with the fugitive plugin installed, I get a keybase error warning about my attempted access of file that I don't have permission to read.

To be specific, if I edit a file

    /keybase/private/cespare/x.txt

I get the following warning from keybase:

    cespare does not have read access to /keybase/private/head

When I use strace, I can see a typical normal git tree traversal looking for the root directory:

```
stat("/run/user/1000/keybase/kbfs/private/cespare/HEAD", 0x7fff36ad77c0) = -1 ENOENT (No such file or directory)
lstat("/run/user/1000/keybase/kbfs/private/.git", 0x7fff36ad8b70) = -1 ENOENT (No such file or directory)
stat("/run/user/1000/keybase/kbfs/private/HEAD", 0x7fff36ad77c0) = -1 EACCES (Permission denied)
lstat("/run/user/1000/keybase/kbfs/.git", 0x7fff36ad8b70) = -1 ENOENT (No such file or directory)
stat("/run/user/1000/keybase/kbfs/HEAD", 0x7fff36ad77c0) = -1 ENOENT (No such file or directory)
lstat("/run/user/1000/keybase/.git", 0x7fff36ad8b70) = -1 ENOENT (No such file or directory)
stat("/run/user/1000/keybase/HEAD", 0x7fff36ad77c0) = -1 ENOENT (No such file or directory)
lstat("/run/user/1000/.git", 0x7fff36ad8b70) = -1 ENOENT (No such file or directory)
stat("/run/user/1000/HEAD", 0x7fff36ad77c0) = -1 ENOENT (No such file or directory)
lstat("/run/user/.git", 0x7fff36ad8b70) = -1 ENOENT (No such file or directory)
stat("/run/user/HEAD", 0x7fff36ad77c0)  = -1 ENOENT (No such file or directory)
lstat("/run/.git", 0x7fff36ad8b70)      = -1 ENOENT (No such file or directory)
stat("/run/HEAD", 0x7fff36ad77c0)       = -1 ENOENT (No such file or directory)
lstat("/.git", 0x7fff36ad8b70)          = -1 ENOENT (No such file or directory)
stat("/HEAD", 0x7fff36ad77c0)           = -1 ENOENT (No such file or directory)
```

The problem is the stat of `/run/user/1000/keybase/kbfs/private/HEAD` which is someone else's private directory in the kbfs model.

Investigating a little, I found that one way to disable this warning is to comment out this BufNewFile autocmd: https://github.com/tpope/vim-fugitive/blob/b48a572475488572b738bf9c49726d63f7fa5e34/plugin/fugitive.vim#L310

Specifically, the tree walking happens during FugitiveExtractGitDir.

To me, it doesn't seem ideal to go looking for a git directory each time I open a file. Would it be reasonable to lazily initialize this data when actually performing a fugitive operation? (I'm probably missing something.)

For now, my workaround was to `git init` an empty repo inside `/keybase/private/cespare`.

**Comment by tpope** [comment]
I've also seen this too, and my solution has sadly been to minimize my use of the Keybase filesystem. Looks like things have been dialed back a teensy bit since I last tried; the following appears to be an adequate workaround:

```vim
let $GIT_CEILING_DIRECTORIES = resolve('/keybase/private')
```

The `resolve()` call is something that could and should be handled by Fugitive itself.

> Would it be reasonable to lazily initialize this data when actually performing a fugitive operation?

It would be extremely unreasonable to re-architect Fugitive because a fake filesystem gives a GUI error when a stat(2) call returns `ENOENT`.

**Comment by cespare** [comment]
Oh neat, TIL about `GIT_CEILING_DIRECTORIES`. Thanks.

> It would be extremely unreasonable to re-architect Fugitive because a fake filesystem gives a GUI error when a stat(2) call returns `ENOENT`.

(`EACCES`.)

I'm not suggesting that fugitive should change its behavior specifically for keybase.

Keybase made me aware of the fact that fugitive resolves a git dir every I open a file, even though 99.99% of the time I won't be using fugitive functions. I was surprised that fugitive does this and it seems undesirable. That's why I titled this issue "Unwanted tree traversal when opening files", not "Make fugitive avoid keybase permission warnings".

**Comment by tpope** [comment]
The statusline indicator alone is enough to nix the lazy initialization idea.

**Comment by cespare** [comment]
Sure, I get that it's too late to fix now.
