### ISSUE TITLE
`:Git diff` with diff-highlight?

### ISSUE THREAD

**Issue by riceissa** [tpope/vim-fugitive#1415]
I have a habit of using `:Git diff %` as I work to check changes I've made. New versions of Fugitive open a temporary split window in which to display the diff. The problem I have with this is that the new diff does not use `diff-highlight` to show within-line changes. This makes it mentally taxing for me to see what changed within a line. `:!git diff %` does work, but does not change directories before performing the diff. Is there some way to get the old `:Git diff` behavior, or some other way to show within-line changes?

**Comment by tpope** [comment]
`:Git -p diff` runs the command with `:terminal`, which sounds close enough to what you want.

**Comment by riceissa** [comment]
`:Git -p diff` runs `git -p diff`. The git manual says the `-p` flag "overrides the `pager.<cmd>` configuration options". This is a problem since `diff-highlight` is specified via the git pager option (i.e. `git -p diff` does not use `diff-highlight`).

**Comment by tpope** [comment]
I'm deprecating `:Git -p`, because it clearly does not solve the problem I intended to solve. I'm not sure what to replace it with, if anything. My short term recommendations for you are to either make your peace with an inferior alternative `:Git diff --word-diff`, or to directly invoke `:!git diff` or `:terminal git diff`.

**Comment by tpope** [comment]
Git's `--paginate` is essentially "disable Git's own pagination and just use the system default", which makes it a perfect fit for *forcing* a temp buffer. We're the system, in a manner of speaking, and a temp buffer is how we paginate. And with that behavior in place, I've experimentally enabled `:terminal` for any command with a custom pager configuration. Let's see if it breaks anything for anybody.
