### ISSUE TITLE
"Press ENTER to continue" spam when focusing status buffer

### ISSUE THREAD

**Issue by simias** [tpope/vim-fugitive#1416]
Vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov  7 2019 22:30:47)
Fugitive version: 6d4564a05e6d974ae05623338a4579ae63ba4243
[vimrc](https://github.com/tpope/vim-fugitive/files/3960228/vimrc.txt)

As far as I can tell the problem only occurs in gvim, I can't reproduce it from the terminal.

In many situations while using fugitive I get prompted to "Press ENTER or type command to continue" without any obvious reason. One of the most egregious examples is when I simply move the focus back to a fugitive status buffer (be it by switching to the buffer inside of vim or simply de-focusing and re-focusing the gvim window using my WM) I get prompted three times in a row:

![gvim-fugitive](https://user-images.githubusercontent.com/7925386/70791305-24a0b300-1d97-11ea-8b1e-46f5705ba03b.png)

Searching on the web I see that it's a common problem in vim, generally caused by the execution of background commands, in particular if they generate output or errors. That being said none of the fixes I've attempted so far have helped:

* `set cmdheight=2` didn't change anything, nor did `set shortmess=a` (or both at the same time).
* Nothing is added to `:message` when those prompts appear.
* I get the same issue with a freshly created test repo containing only one file and no commits.

I realize that this is most likely a configuration error on my side or maybe a conflict with another plugin but I genuinely have no idea how to debug this, so any help would be appreciated.

**Comment by simias** [comment]
Oh, something that might be helpful: after reading `:help hit-enter` I tried playing with `v:scrollstart`. Here's what it contains after I get the first "Press ENTER to continue" prompt after focusing the status buffer:

```
v:scrollstart          function fugitive#ReloadStatus[11]..<SNR>51_ReloadWinStatus[11]..<SNR>51_ReloadStatusBuffer[6]..fugitive#BufReadStatus[18]..<SNR>51_NullError[1]..<SNR>51_SystemError line 10
```

**Comment by tpope** [comment]
If you suspect a configuration error or a plugin conflict (both reasonable suspicions), you should start by stripping down your config and disabling other plugins.

Based on that `v:scrollstart`, you might also try `:call system('git status')` and see if that gives a press enter prompt.

**Comment by simias** [comment]
Calling "git status" does give the prompt:

![prompt](https://user-images.githubusercontent.com/7925386/70812525-0f904800-1dc8-11ea-8bbd-649f49000d84.png)

I'll try to bisect my vimrc to see if I can isolate the root cause.

**Comment by tpope** [comment]
Calling `system()` should never give that prompt; this is definitely something in your setup. It might be related to unusual values of `:set shell? shellcmdflag?`or other shell options.

**Comment by simias** [comment]
In case anybody stumbles upon this issue in the future: the problem was having `!` in `guioptions`

**Comment by tpope** [comment]
If I ever manage to replace `system()` with `job_start()` this will become moot.
