### ISSUE TITLE
The mapping 'p' to jump to patch in preview window fails when previewpopup is not empty

### ISSUE THREAD

**Issue by jmdevin** [tpope/vim-fugitive#1418]
### Vim Version
8.2
Included patches 1-19
`v:version` 802
### Issue
When the option 'previewpopup' is not empty, the default-mapped `p` (jump to patch or blob in preview window) throws E994 and then opens an empty preview-popup window.
### Steps to Reproduce
1. With vim-fugitive installed, open a git-tracked file in vim.
2. Do `:Gblame` on a line of the file.
3. Press `p` with cursor on any line.
4. See the following message:
```vimscript
Error detected while processing function fugitive#BufReadCmd[71]..<SNR>16_ReplaceCmd:
line 21:
E994: Not allowed in a popup window
```
**(Note: for the original reporter this always showed line 21)**
5. An empty preview-popup window opens.
### Expected Behavior/Suggested Fix
Either a regular preview window should be opened instead of a preview-popup window regardless of the value of `previewpopup` (if that is possible) or the preview-popup window should be supported.

**Comment by tpope** [comment]
`line X`?? What is X????? I think temporarily disabling `'previewpopup'` is the way to go, but I'd like to do a cursory inspection of what's going wrong (without needing to compile Vim 8.2).

**Comment by jmdevin** [comment]
Well, X was meant to be whatever line you happened to be on when you hit `p`, but I'm redoing this now and it actually says `line 21` in the error message regardless of what line I'm on. I didn't realize that at first.

**Comment by tpope** [comment]
https://github.com/tpope/vim-fugitive/blob/6d4564a05e6d974ae05623338a4579ae63ba4243/autoload/fugitive.vim#L1562 is line 21. Try changing `silent` to `silent!` and see if anything else fails.

**Comment by jmdevin** [comment]
No difference. Same message and behavior.

And to be sure, I edited the file, saved it, closed and reopened vim and tried again. No difference.

**Comment by tpope** [comment]
It still says line 21? Try deleting the line entirely.

**Comment by tpope** [comment]
Just to make sure, you're on the latest version of Fugitive?

**Comment by jmdevin** [comment]
Whoops, it changed to say line 12, not 21. I'll learn to read. Latest version of fugitive.

Now changing line 12's `silent` to `silent!` did get rid of the error message entirely. The preview-popup now just opens empty without complaint.

**Comment by tpope** [comment]
Try calling `:pedit somefile.gz`, where `somefile.gz` is a valid `.gz` file. Does that work?

**Comment by tpope** [comment]
Try `:pedit https://www.google.com/`too.

**Comment by jmdevin** [comment]
`:pedit somefile.gz` works for me. It opens in a preview-popup window fine.

`:pedit https://www.google.com/` does not work; it gives E994 with a reference to some netrw functions.

**Comment by tpope** [comment]
Please file a Vim bug for the latter, and followup when a solution is decided upon.

As an interim solution, you're also welcome to explore changing `ReplaceCmd()` to use `silent execute '$read' temp` when `&buftype =~# 'popup'`.

**Comment by jmdevin** [comment]
Something weird to add, although it's still a vim bug so it won't reopen this. `:pedit https://www.google.com/` works if you first open it with `previewpopup` empty, then close it, set previewpopup to something, and open it again.

**Comment by tpope** [comment]
Presumably because the buffer is already in memory, so `BufReadCmd` doesn't get invoked again. Might be affected by `:set hidden?`.

**Comment by tpope** [comment]
I was worried about file encoding issues with the `read` solution but it looks like `read ++edit` addresses this, so we can probably ditch the conditional and use that for everything. (`gzip.vim` uses `$read ++edit` and `netrw.vim` uses `file`/`edit!` just like Fugitive, which explains why one works and one breaks.)

**Comment by jmdevin** [comment]
You were right, `https://www.google.com/` remained as an unlisted buffer in the buffer list. Not with `set hidden` though, that was off.

**Comment by tpope** [comment]
`'bufhidden'` then.

**Comment by jmdevin** [comment]
Ah, `'bufhidden'` was it.

**Comment by tpope** [comment]
Too easy, I hope it didn't break anything.
