### ISSUE TITLE
Glog hide whitespaces

### ISSUE THREAD

**Issue by dihak** [tpope/vim-fugitive#1420]
How to hide the whitespaces diff after entered a commit in Glog command?

**Comment by tpope** [comment]
What is a whitespaces diff?

**Comment by dihak** [comment]
![image](https://user-images.githubusercontent.com/10445482/71382127-1e1d0180-2609-11ea-8e54-3fb070174faa.png)

**Comment by tpope** [comment]
Not supported, but see #1109.
