### ISSUE TITLE
BUG with ":G rebase -i" when using "reword" after a "fixup"

### ISSUE THREAD

**Issue by adithyaov** [tpope/vim-fugitive#1424]
To Reproduce:

Make the file structure below:
```
git init
echo 1 > f1 && git add -A && git commit -m "Add f1"
echo 2 > f2 && git add -A && git commit -m "Add f2"
echo 3 > f3 && git add -A && git commit -m "Add f3"
echo 4 > f4 && git add -A && git commit -m "Add f4"
echo 5 > f5 && git add -A && git commit -m "Add f5"
```
At this point you have 5 files and 5 commits,
**Commits: Add f1, Add f2, Add f3, Add f4, Add f5**

Open neovim: `nvim`

Open a new buffer: `:new`

Type: `:G rebase -i HEAD~4`

You'll have the following in the rebase buffer
```
pick 75dc365 Add f2
pick 1006165 Add f3
pick 71c557e Add f4
pick 74cf595 Add f5
```

Change it to:
```
pick 75dc365 Add f2
fixup 1006165 Add f3
reword 71c557e Add f4
pick 74cf595 Add f5
```

Save and close the rebase buffer: `:wq` (Make sure not to close neovim)

You'll be treated with a reword buffer like so,
```
Add f4
```

Change the commit message to something else like so,
```
Make f4
```

Save and close the reword buffer: `:wq`

Now check your commits!

Expected commits,
**Commits: Add f1, Add f2, Make f4, Add f5"**

Actual commits,
**Commits: Add f1, Make f4, Add f5"**

This does not happen when you do the same thing in the terminal. There seems to
be some bug in `vim-fugitive`

Neovim version: 0.3.5
OS: Ubuntu 18 on Windows WSL

**Comment by adithyaov** [comment]
Please let me know where the problem might be. I'll try solving it and submit a PR :-)

**Comment by tpope** [comment]
It's almost certainly in [this mess](https://github.com/tpope/vim-fugitive/blob/3bf602b13d86b7aef57fec4a2df29467b61435cb/autoload/fugitive.vim#L3605-L3613). When `git rebase` stops we need to deduce from the aftermath whether to call `git commit`, `git commit --amend`, or nothing at all. This is even harder than it sounds.

**Comment by adithyaov** [comment]
@tpope Thank you for replying. I agree that it's certainly not easy to find a proper solution. I'll get back to you if I find a decent fix!

**Comment by tpope** [comment]
The `job` branch replaces the so called mess with a generic `git` runner capable of invoking an editor. Give it a try, hopefully it renders all this moot.

**Comment by adithyaov** [comment]
Awesome! Will give it a try and let you know :-)
