### ISSUE TITLE
It looks like in Windows OS, if `set shell=powershell`, some problems will occur?

### ISSUE THREAD

**Issue by Freed-Wu** [tpope/vim-fugitive#1426]
If it cannot be compatible with `set shell=powershell`, it will be great to point out the fact in help txt. Or when in fugitive buffer `let s:shell=&shell | set shell&`, when leave fugitive buffer, `let &shell=s:shell`, so user can use their favourite shell?

Thank you!

**Comment by tpope** [comment]
> If it cannot be compatible with set shell=powershell, it will be great to point out the fact in help txt.

It can be compatible. As far as I know it *is* compatible. "Some problems will occur" isn't really a helpful bug report.

> Or when in fugitive buffer let s:shell=&shell | set shell&, when leave fugitive buffer, let &shell=s:shell, so user can use their favourite shell?

So the shell you use varies depending on whether you're using Git? That sounds like a terrible misfeature.

**Comment by Freed-Wu** [comment]
I am sorry. The picture is as follow:

When `set shell&`, it is displayed rightly.
![Image 4](https://user-images.githubusercontent.com/32936898/71709341-7c2fbd00-2e31-11ea-81b8-e2e7804d786d.png)

When `set shell=powershell`, it will be shown strangely.
![Image 5](https://user-images.githubusercontent.com/32936898/71709349-8a7dd900-2e31-11ea-992b-53935e859493.png)

> So the shell you use varies depending on whether you're using Git? That sounds like a terrible misfeature.

You are right.

**Comment by tpope** [comment]
What you you get if you do `:echo system('git status --short')`?

**Comment by Freed-Wu** [comment]
```
set shell=cmd
echo system('git status --short')
```

![Image 2](https://user-images.githubusercontent.com/32936898/71796821-9f06df00-3086-11ea-98b3-946883bb0e34.png)

```
set shell=powershell
echo system('git status --short')
```

![Image 1](https://user-images.githubusercontent.com/32936898/71797243-286ae100-3088-11ea-9144-08223c8fedff.png)

**Comment by tpope** [comment]
Try with `:echo system("echo test")`.

**Comment by Freed-Wu** [comment]
```
set display+=uhex
set shell=powershell
echo system('test')
```

```
<ff><fe>t<01>e<01>s<01>t<01>
<01>
<01>
```

OMG... But why?

**Comment by tpope** [comment]
That's between you, PowerShell, and Vim.

**Comment by tpope** [comment]
Can you try `:Git status` and see if that output if mangled as well? If so, can you try the `'job'` branch and see if that fixes it?

**Comment by tpope** [comment]
Vim has better PowerShell support now. See #1783.
