### ISSUE TITLE
[Feature request] List files of selected commit/fugitive object

### ISSUE THREAD

**Issue by kristijanhusak** [tpope/vim-fugitive#1427]
I'm not sure if this is already possible, i wasn't able to find it.

This would be useful for example from `Glog` or `Gblame`. You open up Glog, select a certain commit, trigger a command or a mapping and your quickfix list populates with all the files that were changed in that commit. Then you can select each file separately and preview it. [Lazygit](https://github.com/jesseduffield/lazygit) has this where you go to the `Commit files` section, press Enter and you get all the files listed with ability to preview it.

I can try to build this myself, just want to check with you if you would consider adding such a feature.

**Comment by tpope** [comment]
This would fall under the sprawling #132 umbrella. Try the work in progress branch there with `:Git difftool --name-only ! !^@`. `!` is Fugitive syntax for "the currently edited commit" and `^@` is Git syntax for "all the parent commits".

**Comment by kristijanhusak** [comment]
@tpope I tested related issue that you merged, and it is more less OK for me, but i would like to suggest a different solution.

Would it be possible to show a certain commit in a 'Gstatus' fashion, but much simplified in terms of functionality (read only, no staging or any other actions obviously)?

**Comment by tpope** [comment]
I do hope to one day unify the commit view with the status view, but this is largely a cosmetic change. The functionality is already there. Press `<CR>` on a `diff --git` line to open the corresponding diff. Collapsing/expanding on `=` is missing, but you can get a similar effect with syntax folding.

**Comment by kristijanhusak** [comment]
Syntax folding does the trick, thanks!
