### ISSUE TITLE
Gbrowse can't open refs 

### ISSUE THREAD

**Issue by mellery451** [tpope/vim-fugitive#1428]
GBrowse has been giving me errors like this with certain branches (like `release` and `master` specifically):

```
Error detected while processing function fugitive#BrowseCommand:                                                                                 
line  144: 
E484: Can't open file /Users/ME/SOMEREPO/.git/refs/heads/release
```
Sure enough,  `master` and `release` are not there in refs/heads...but `develop` is.

Is this pilot error or possibly something wrong with my git config?

**Comment by tpope** [comment]
Sounds like a case of [packed refs](https://git-scm.com/docs/git-pack-refs). I wasn't sure if a checked out branch could ever be packed. Based on how long it took someone to report this, it seems to be rare but possible.

**Comment by mellery451** [comment]
Thanks - you are probably right about the packed refs in my repo. Trying the latest commit, I now get:
```
  fugitive: rev-parse /Users/ME/SOMREPO/.git/refs/heads/master: fatal: Needed a single revision
```
Thoughts?

**Comment by tpope** [comment]
The problem with "rare but possible" is that it's not always obvious how to test. See if the latest does it.

**Comment by mellery451** [comment]
yep - working now. Thanks!
