### ISSUE TITLE
Core dump with very new vim

### ISSUE THREAD

**Issue by fourjay** [tpope/vim-fugitive#1429]
For the most part a "heads up"
updated vim from github over the new years break, and fugitive now coredumps on commit
Vim: Caught deadly signal ABRT
                              Vim: Finished.
Aborted (core dumped)
I rolled back vim several times, eventually to (vim) commit ae7dba896975051a3f0b7123faa08dac5635972d
before the issue cleared up
To verify, pulled the the latest vim, make distclean and the core-dump reappeared.

**Comment by tpope** [comment]
Is ae7dba896975051a3f0b7123faa08dac5635972d the last working commit? Is it broken on 257a396879ff67a0482841a39237f30a8e1e27c5?

**Comment by fourjay** [comment]
I'll do some sort of bisect, but the commit was random, mostly inspired by roughly when I remember last doing a pull from upstream git.

**Comment by tpope** [comment]
If you get a chance, also try it on the `job` branch. That's includes a generic command runner that replaces the `:Gcommit` specific implementation. If it works, then this might be moot in the nearish future.

**Comment by fourjay** [comment]
Thanks
Manually incrementing, failure starts with commit 1a47ae32cdc19b0fd5a82e19fe5fddf45db1a506
Last working commit 257a396879ff67a0482841a39237f30a8e1e27c5
the vim-job branch does not help

**Comment by tpope** [comment]
Christ, I want my evening back. Isolated the issue and reported a Vim bug at <https://github.com/vim/vim/issues/5450>. The double autocommand can be caused by having vim-git installed. Please verify the same conditions triggered the issue on your machine, or add a comment if you find some other cause.
