### ISSUE TITLE
Use <C-A>/<C-X> to start interactive rebase

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1431]
Since these are now available by default to cycle between commands (since Vim 8.2), starting a rebase with them seems natural. \<C-A\> can start with 'edit' command (as <kbd>rm</kbd> does) and \<C-X\> can use 'drop' (as <kbd>rd</kbd>).

**Comment by justinmk** [comment]
> these are now available by default to cycle between commands (since Vim 8.2)

In which mode? What Vim 8.2 feature (or commit) are you referring to exactly?

**Comment by odnoletkov** [comment]
Vim 8.2 has updated ftplugin for git-rebase-todo. You can cycle pick/edit/reword/squash/fixup/drop commands using <C-A>/<C-X>

**Comment by bam80** [comment]
So it's not a feature of Vim 8.2 but rather the new runtime.
Didn't find mention about it in official release: https://www.vim.org/vim-8.2-released.php, so maybe fix the OP a bit..

**Comment by kiryph** [comment]
The commit was https://github.com/vim/vim/commit/c08ee7476b19f9b4de5df287797af87c4e3fba0a#diff-3c141623316cb059094327dce45015d6

**Comment by tpope** [comment]
Clever but a poor fit imho. Two of the six commands won't on the top most commit.
