### ISSUE TITLE
Add a way to edit branch description

### ISSUE THREAD

**Issue by coot** [tpope/vim-fugitive#1434]
```
git branch --edit-description
```
Opens editor to edit branch description. One can display it with
```
git config branch.<branch-name>.description
```
Antoher way to edit it is to use
```
git config branch.<branch-name>.description "Branch description"
```
It would be nice to edit it without running another vim (or another vim instance inside vim's terminal).

**Comment by tpope** [comment]
Try #1433

**Comment by coot** [comment]
#1433 is awesome :), thanks!
