### ISSUE TITLE
Interactive rebase clobbers :Glog?

### ISSUE THREAD

**Issue by x-yuri** [tpope/vim-fugitive#1436]
I might be using it (`fugitive`) wrong, since I started just a couple of days ago, so please tell me if that's the case.

Steps to reproduce:

1. Start `vim`.
2. `:Glog`. It opens quickfix list with a history, and another window with the latest commit. The latter being active.
3. `rw`. It opens 2 more windows. One with a `git rebase` todo list. Another with the commit under the cursor in the former.
4. `ZZ` (save and close the todo list). Todo list and quickfix list disappear. And another window appears where I'm supposed to write a message.
5. `ZZ` (save and close)

As a result I'm left with 2 windows: 1) commit from `:Glog`, 2) commit from interactive rebase. And quickfix list is empty. I'd expect quickfix list to be preserved, and no leftover windows from interactive rebase.

Or is there another easy way to say which commit I want to reword?

**Comment by tpope** [comment]
Rebase overwrites the quickfix fix with the output of the rebase command, most usefully with any merge conflicts. This will be changing soon: see #1433.

`:Glog` isn't "wrong" but it's awkward to work with for most tasks. Usually it's easier to kick off `rw` from the `:Gstatus` window, assuming it's an unpushed change.

**Comment by x-yuri** [comment]
> Usually it's easier to kick off rw from the :Gstatus window

But that will let me reword just the last commit, won't it? Is there other easy way to reword an arbitrary commit? Let's say I'm inspecting commits before pushing them, and see that I want to reword one of them (not the last one), what do I do?

Also, you seem to not notice that there's a leftover window after interactive rebase. Supposedly the one that shows commit that was under the cursor in the git rebase todo window.

**Comment by tpope** [comment]
> > Usually it's easier to kick off rw from the :Gstatus window
> 
> But that will let me reword just the last commit, won't it? Is there other easy way to reword an arbitrary commit? Let's say I'm inspecting commits before pushing them, and see that I want to reword one of them (not the last one), what do I do?

It will let you reword any commit in the `Unpushed` section, based on what line the cursor is on.

> Also, you seem to not notice that there's a leftover window after interactive rebase. Supposedly the one that shows commit that was under the cursor in the git rebase todo window.

`rw` should only ever open one window: the rebase todo file. I don't understand what you mean by the "commit under the cursor" here, because `rw` doesn't work in the quickfix list, and the other window only contains a single commit. There's nothing that could be the "commit under the cursor" when the whole buffer is one commit.

**Comment by x-yuri** [comment]
> It will let you reword any commit in the Unpushed section, based on what line the cursor is on.

What are preconditions for the section to be present? Probably the branch must exist remotely. That is often not the case for me. I generally don't push unless I have to. And often the history (commits) I start with differs from the final result. That is, I commit often (think quick provisional commits). Occasionally I rebase (amend the history). So if I were to push the first commits, I might need to change them in the future. Not a big deal, just describing my workflow. And I might adapt my workflow to fugitive.

> rw should only ever open one window

Sorry, my bad, I had [`auto-git-diff`][auto-git-diff] plugin installed as well.

[auto-git-diff]: https://github.com/hotwatermorning/auto-git-diff

**Comment by tpope** [comment]
The branch needs to have a configured upstream. It works pretty well for your workflow if you configure the upstream to be master, but that has the side effect of changing the push destination as well. I *thought* the concept of a push remote would solve this, but it's literally just a remote, you can't specify a different branch name. I don't know why anyone would want to do that.

What *I* want is basically to always show a sections for `master` in addition to the usual suspects, but `master` is just a convention, which means this needs to be configurable, sigh.

**Comment by x-yuri** [comment]
> I thought the concept of a push remote would solve this, but it's literally just a remote, you can't specify a different branch name.

Even if one could, that would again mean "changing the push destination as well", wouldn't it?

> I don't know why anyone would want to do that.

Would want to specify a different branch name? I don't know either. Even if it were possible, it wouldn't solve my case, I think. Because of the side effect.

> What I want is basically to always show sections for master in addition to the usual suspects

Do you mean `master..HEAD`? What suspects?

> but master is just a convention, which means this needs to be configurable, sigh.

I'm not sure what you want, but if I could tell `fugitive` what I consider upstream, that would make `:Gstatus` more usable for me. E.g. `fugitive` could have a `g:default_upstream = 'master'` variable which can be changed. Or a way to affect one `:Gstatus` buffer. `:Gupstream dev`? `:Gsetupstream dev`? But you don't seem to like adding settings, do you?

On the other hand, at the moment I'm using `:Glog` to change history. Seems pretty good so far. The most annoying thing at the moment is that I need to update `:Glog` after (interactive) rebase, and find the commit I was at. That is, the current commit is not preserved after `:Glog`. But I can probably live with that.

While I'm at it, thanks for your work. A number of years ago I considered installing `fugitive`, but decided that it wouldn't make much difference. It appears I was wrong. The most impressive feature I know right now is an ability to edit files in the index (i.e. stage changes not as is). With `fugitive` it's much easier. Not to mention that editing patches (`git add -p` + `e`) sometimes fails (a `git` bug?). And all in all, `fugitive` makes for a more streamlined experience. No extra `vim` instances when specifying a commit message, changing a rebase todo, etc.

**Comment by tpope** [comment]
In the process of drafting a much longer response I think I figured out the solution.

- Set the upstream of branches where I'm using this workflow to the forked branch, typically `master`. Set `branch.autoSetupMerge=always` to make this happen by default when forking.
- Use `push.default=current` so push ignores the upstream and uses the the current branch name remotely for the default push.
- Change Fugitive to show unpushed and unpulled commits for both the upstream and the default push target. Four sections seems excessive, but they do all have their own uses.
- If/when I'm done with local rebasing against `master` and ready for the branch to live on its own, use `:Git push -u` to change the upstream from `master` to the default push target.

> While I'm at it, thanks for your work.

Thanks!

**Comment by x-yuri** [comment]
Thanks for the idea. Another option I see is to not fork unless I have to push. Then I can see unpushed commits in `:Gstatus`. We'll see how it'll work out...

**Comment by x-yuri** [comment]
To be honest it's only now that I'm trying to adopt your suggested workflow. To recap, I'm trying to make `:Gstatus` list all the branch's commits.

To do it manually I have to set upstream to `origin/master` (`git branch -u origin/master`). And add `push.default=current` to `.git/config` or `~/.gitconfig`. So that when I do `git push`, it would push `b1` to `origin/b1` (not to `origin/master`).

`branch.autoSetupMerge=always` is supposed to obviate the need to perform the first step (`git branch -u`). And it kind of does, but in a weird way. When I do `git checkout -b b1` from `master`, it adds:

```
[branch "b1"]
	remote = .
	merge = refs/heads/master
```

That is, the upstream is the branch `master` of the local repository. Correct me if I'm wrong. But well, `Gstatus` does start showing the branch's commits. But then, `git push` does nothing, because it tries to push to the same branch of the same repository. Am I doing something wrong?

> Change Fugitive to show unpushed and unpulled commits for both the upstream and the default push target. Four sections seems excessive, but they do all have their own uses.

From what I can see Fugitive does that by default. Is there a way to configure it?

**Comment by tpope** [comment]
> `branch.autoSetupMerge=always` is supposed to obviate the need to perform the first step (`git branch -u`). And it kind of does, but in a weird way. When I do `git checkout -b b1` from `master`, it adds:
> 
> ```
> [branch "b1"]
> 	remote = .
> 	merge = refs/heads/master
> ```
> 
> That is, the upstream is the branch `master` of the local repository. But well, `Gstatus` does start showing the branch's commits. But then, `git push` does nothing, because it tries to push to the same branch of the same repository. A [demo](https://gist.github.com/x-yuri/5e98d54f827c5e7afd3015de19e169e7). Am I doing something wrong?

You need to explicitly create the branch from `origin/master` rather than allow it to default to `master`, which is admittedly annoying. I recently gave in to creating an alias for it:

```
[alias]
	cb = checkout @{upstream} -tb
```

> **UPD** On second thought you probably assume that if I push the branch to the remote repository, then I don't care about the pushed commits (don't need them listed), which is not the case. I'd like to have all the branch's commits, pushed or not. And `:Git push -u` (the last step) would probably rather be `:Git push -u origin HEAD` or something.

You'll continue to see the commits in the `origin/master` section until they're merged in. At that point, yes, I'm assuming they're moot.

> > Change Fugitive to show unpushed and unpulled commits for both the upstream and the default push target. Four sections seems excessive, but they do all have their own uses.
> 
> From what I can see Fugitive does that by default.

Correct, that bullet point has been implemented.

> Is there a way to configure it?

Not currently. Suggestions welcome.

**Comment by x-yuri** [comment]
> Is there a way to configure it?
>> Not currently. Suggestions welcome.

As far as I know Fugitive has no configuration options. And you're not in favor of adding them. It's just that your phrase, "Change Fugitive to show...", sounded like there's is an option I can specify to change Fugitive's behavior. That's why I asked.

But if you're asking about not showing unneeded sections, at this point I have no ideas other then to add some option :) But it's only recently that an unneeded section appeared in one of my repos, so maybe it will urge me to come up with some ideas :)
