### ISSUE TITLE
Ggrep doesn't work

### ISSUE THREAD

**Issue by TheCoder49** [tpope/vim-fugitive#1437]
![git](https://user-images.githubusercontent.com/54935354/72806558-b84a8680-3c55-11ea-91fb-72f263aad498.PNG)

This is the output I get when I run `:Ggrep neki`.
I am using GVIM version 8.2 on windows and git version 2.23.0

**Comment by tpope** [comment]
What is `:set shell? shellcmdflag?`.

**Comment by TheCoder49** [comment]
`:set shell?`
`shell=C:\Windows\system32\cmd.exe`

`:set shellcmdflag?`
`shellcmdflag=/c`

**Comment by tpope** [comment]
Does `:Glog` work? Does `:Git diff` work?

Does `:Ggrep` work on version 3.1?

**Comment by tpope** [comment]
Also check `:set shellquote? shellxquote? shellxescape? shellpipe? shellredir?`.

**Comment by TheCoder49** [comment]
`:Glog` works
`:Git diff` doesn't work ... it can't open that tmp file

`set shellquote=`
`set shellxquote=(`
`set shellxescape="&|<>()@^`
`set shellpipe=>%s 2>&1`
`set shellredir=>%s 2>&1`

**Comment by tpope** [comment]
Please try on Fugitive 3.1.

**Comment by tpope** [comment]
I guess another good question is how did you install Git? The cygwin version behaves very different from the msysgit version for example, and I don't think it will work with GVim.

**Comment by TheCoder49** [comment]
It doesn't work on Fugitive 3.1

I have both git versions installed, but vim uses cmd in the back, so it should be using the msysgit version...

**Comment by tpope** [comment]
`:echo exepath('git')` should confirm which binary it is using. `:Git --version` and `:Git --exec-path` might also be enlightening.

**Comment by TheCoder49** [comment]
`echo exepath('git')` gives `C:\Program Files\Git\cmd\git.EXE`
`:Git --version` gives `git version 2.23.0.windows.1`
`:Git --exec-path` gives `C:/Program Files/Git/mingw64/libexec/git-core`

**Comment by TheCoder49** [comment]
An interesting observation is that if I run Vim (not gVim), it works as it should.

**Comment by tpope** [comment]
Does it show anything interesting in the cmd.exe window that pops up?

**Comment by TheCoder49** [comment]
You mean when I run as Vim?
No window pops up.

**Comment by tpope** [comment]
I mean where you run in GVim, where a window pops up.

**Comment by TheCoder49** [comment]
Down in the taskbar a few window icons flash for a moment, but no window pops up for me to see.

**Comment by tpope** [comment]
I just tried on a Windows machine and that is what I saw. The flashing task bar is what `:grep` and `:make` typically do, and the foreground window is what `:!` does. I switched from `:grep` to `:!` a while back, but that was before 3.1, so we should both be seeing `:!` behavior. I don't know enough about Windows to speculate why our experiences differ, but it might be worth stripping down your config to see if something in there is causing it, but frankly, that's kind of a long shot. You could also try much older versions of Fugitive.

I do plan to switch it again to use jobs, as hinted at in #1433. No idea if it will take 2 weeks or 6 months to finish knocking it out, but it will certainly render this obsolete when it does. Do report back if you figure anything out, but I've already spent as much time as I can justify on a one-user bug report on a legacy implementation.

**Comment by TheCoder49** [comment]
I have found the culprit.
The `!` in the `'guioptions'` is responsible for not opening the terminal window when executing `Ggrep` and is also the reason why the command fails.
If I remove the `!` from `'guioptions'`, the command starts working too.

Hopefully it will help someone else with simmilar problem :)
