### ISSUE TITLE
Two questions on output targets

### ISSUE THREAD

**Issue by Thermatix** [tpope/vim-fugitive#1438]
I have two questions:

1. Would it be possible to redirect command output to a single pane so you get almost a stream of command output?

2. Would it be possible for use in Neovim to direct the output of commands that open up another program (diff, commit, etc) to a floating window? I ask because I find floating windows to be less disruptive and seem to have better performance

**Comment by tpope** [comment]
> I have two questions:
> 
> 1. Would it be possible to redirect command output to a single pane so you get almost a stream of command output?

I don't think I like the sound of that. But the way it works is about to be completely overhauled by #1433. Try that branch for a bit and see if the reduced number of "press enter" prompts satiates you.

> 2. Would it be possible for use in Neovim to direct the output of commands that open up another program (diff, commit, etc) to a floating window? I ask because I find floating windows to be less disruptive and seem to have better performance

By "other program" do you mean other window? What little I know about Neovim floating windows suggests they would be a terrible fit. Is there usage information for them in the help? All I'm seeing is API docs.

**Comment by Thermatix** [comment]
For the first one, I like to see the output of git status when I'm making commits so I can see what I want to add to a commit without overwitting the output, I suppose it would be nice if I could have a pane that constantly shows the output of git status so I can see what changes I've added & what needs to be added.

For the second one this is an example of Fzf in a floating window ->  https://www.reddit.com/r/neovim/comments/djmehv/im_probably_really_late_to_the_party_but_fzf_in_a/

My thought was, `Git commit` or `Git rebase master -i` and then it opens up a floating window with an editable buffer, do your commit stuff and then `:wq` and it closes and executes the commit

**Comment by tpope** [comment]
> For the first one, I like to see the output of git status when I'm making commits so I can see what I want to add to a commit without overwitting the output, I suppose it would be nice if I could have a pane that constantly shows the output of git status so I can see what changes I've added & what needs to be added.

This is effectively what `:Gstatus` (or just `:G`) already does. It reloads after every `:Git` command. It doesn't reload on every buffer write for performance reasons, but if you want it to, you can force it with

```
autocmd BufWritePost * call fugitive#ReloadStatus()
```

> For the second one this is an example of Fzf in a floating window -> https://www.reddit.com/r/neovim/comments/djmehv/im_probably_really_late_to_the_party_but_fzf_in_a/
> 
> My thought was, `Git commit` or `Git rebase master -i` and then it opens up a floating window with an editable buffer, do your commit stuff and then `:wq` and it closes and executes the commit

What happens if I'm drafting a commit message and I need to look back at the code to come up with a good summary? Can I move the floating window or temporarily hide it without closing the buffer? This is what I mean by "usage information." I can't find anything in Neovim's manual for how I actually *use* floating windows.

**Comment by jheroy** [comment]
> What happens if I'm drafting a commit message and I need to look back at the code to come up with a good summary? Can I move the floating window or temporarily hide it without closing the buffer? This is what I mean by "usage information." I can't find anything in Neovim's manual for how I actually _use_ floating windows.

There is another plugin https://github.com/voldikss/vim-floaterm 
It can hide and show again without closing the buffer.
For now, I can use command `:FloatermNew vim -c ":Gstatus" +only` open a floating git status window like this
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/504766/99046656-0a3a0f80-25ce-11eb-8095-8162f6ee1367.png">

But some other feature, like preview diff in Gblame window, I can't find a way to do that. It could be nice  if fugitive can support floating window natively.

**Comment by tpope** [comment]
> > What happens if I'm drafting a commit message and I need to look back at the code to come up with a good summary? Can I move the floating window or temporarily hide it without closing the buffer? This is what I mean by "usage information." I can't find anything in Neovim's manual for how I actually _use_ floating windows.
> 
> There is another plugin https://github.com/voldikss/vim-floaterm
> It can hide and show again without closing the buffer.
> For now, I can use command `:FloatermNew vim -c ":Gstatus" +only` open a floating git status window like this

Sounds to me like what you really want is a plugin called floatbuffer, which does the same thing but lets you use a Fugitive buffer directly rather than a Rube Goldberg machine.

> But some other feature, like preview diff in Gblame window, I can't find a way to do that. It could be nice if fugitive can support floating window natively.

This is supported in Vim with `'previewpopup'`; I barely had to do anything to enable it. Neovim, on the other hand, expects me to reinvent the wheel, best I can tell.

**Comment by pencilcheck** [comment]
Thanks for the code snippet!!
`:FloatermNew vim -c ":Gstatus" +only` dunno why but I can't add `<CR>` in the -c as it will always say something about .zshrc unmatched ".

**Comment by ernstwi** [comment]
This gets me part of the way there. But `cc` opens the commit message editor in a new split behind the floating window, so more to do obviously.

```
function! Float(buf)
    " Define the size of the floating window
    let width = 150
    let height = 80

    " Get the current UI
    let ui = nvim_list_uis()[0]

    " Create the floating window
    let opts = {'relative': 'editor',
                \ 'width': width,
                \ 'height': height,
                \ 'col': (ui.width/2) - (width/2),
                \ 'row': (ui.height/2) - (height/2) - 5,
                \ 'anchor': 'NW',
                \ 'style': 'minimal',
                \ }
    let win = nvim_open_win(a:buf, 1, opts)
endfunction

function! FloatFile(filename)
    let bufnr = bufadd(a:filename)
    call Float(bufnr)
endfunction

command! GitFloat call FloatFile('.git/index')
```

**Comment by mahmoudajawad** [comment]
@ernstwi, if I'm following you correctly, creating similar code for to handle `cc` then override default binding with the custom command, would do it, would it?

**Comment by ernstwi** [comment]
That could work, sure. If status and commit is covered that goes a long way as a quick hack, but I'm sure there is more functionality to consider.
