### ISSUE TITLE
Ggrep shows full path instead of relative

### ISSUE THREAD

**Issue by bricerebsamen** [tpope/vim-fugitive#1439]
Ggrep is the number one reason why I'm using fugitive and sometimes it doesn't work as expected: it returns the global path to the files instead of the relative path (from the working directory).

I'm on Ubuntu 14.04 with git 2.24 and I just updated fugitive to 3.1.

when I call Ggrep, in the terminal it shows the relative paths, but when it opens the quickfix window with the results it shows the global paths. When I select a result, it opens the global path too. This messes up a number of other commands I have :(

Is this a bug? is there an option to force relative path?
LMK what other info I can provide and thanks for your work

**Comment by tpope** [comment]
`:Ggrep` feeds the quickfix list absolute paths so that it handles the case where the working directory differs from the work tree. Vim generally resolves these to relative paths automatically. Does Ubuntu 14.04 mean you are running a 6 year old Vim?

**Comment by bricerebsamen** [comment]
I'm running vim 8 (pi-rho)

the weird thing is that sometimes it shows the relative paths and sometimes the global paths...

**Comment by tpope** [comment]
I'm going to chalk this up as a quirk of your old but at least not 6 year old Vim. You're welcome to try to tweak it to conditionally use relative paths.

**Comment by tpope** [comment]
But also, your other commands should probably do `expand('%:.')` if the really can't deal with absolute paths. That's probably an easier fix.

**Comment by tpope** [comment]
You're in luck.

**Comment by bricerebsamen** [comment]
71038e8 seems to solve my issue, thanks very much
