### ISSUE TITLE
:Dispatch error

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1440]
> Error detected while processing function dispatch#compile_command[52]..dispatch#compiler_options:
line   13:
E666: compiler not supported: git
Error detected while processing function dispatch#compile_command:
line   52:
E171: Missing :endif

https://github.com/tpope/vim-fugitive/commit/5bcb42164e7b2af3ad1d1ead654e5fb4f06023c2 is to blame

**Comment by tpope** [comment]
Damn, I forgot the `git` compiler was local to my machine. Reverting for now.
