### ISSUE TITLE
Can't :Gcommit, window with escape sequence characters shown

### ISSUE THREAD

**Issue by Kazy** [tpope/vim-fugitive#1443]
Hello. Since the merge of https://github.com/tpope/vim-fugitive/pull/1433, :Gcommit doesn't work aymore. Here is a screenshot on a fresh git repository, with everything in `.git/hooks` removed.

![2020-01-24-095044_screenshot](https://user-images.githubusercontent.com/59063/73056331-13b38900-3e8f-11ea-947b-b1419f2e5acc.png)

And on a minimal `init.vim` with only `fugitive`:

![2020-01-24-095806_screenshot](https://user-images.githubusercontent.com/59063/73056785-29757e00-3e90-11ea-925a-16ba947b1283.png)

I'm on Linux running NVIM v0.5.0-328-ge53e86075 (build during the last week I believe). Using `let g:fugitive_pty = 0` as suggested in the merge request thread fixes it, but I'm not sure that's the expected behaviour on Linux.

Let me know if you need any other information, and thanks a lot for your plugins !

**Comment by tpope** [comment]
Do you have `$GIT_EDITOR` set?

**Comment by Kazy** [comment]
I don't, should it be ? I do have `$EDITOR` set to `nvim`.

**Comment by tpope** [comment]
Don't set it. Fugitive sets it, to intercept requests for an editor, and it looks like it's having no effect, with a child nvim spawning instead.

What is `:echo g:fugitive_git_executable` and `:echo g:fugitive_git_command` (that second one might not exist)? And if you call `which` on the results, does it point at the binary in `/usr/bin`, or something else?

**Comment by Kazy** [comment]
`g:fugitive_git_executable` is set to `git` and `g:fugitive_git_command` to `hub`. `which git` is `/usr/bin/git` and `which hub` is `/usr/bin/hub`.

**Comment by tpope** [comment]
Check `:echo $GIT_EDITOR`, I bet it's set even if you didn't set it.

**Comment by Kazy** [comment]
Unless I missed something, it isn't.
![2020-01-24-10-54-06](https://user-images.githubusercontent.com/59063/73060382-fe8f2800-3e97-11ea-8de1-a458993ee580.gif)

**Comment by tpope** [comment]
The root cause is almost certainly https://github.com/neovim/neovim/issues/11751. See if you can confirm with this variant:

```
let g:jobopts = {'stdout_buffered': 1, 'pty': 1, 'env': {'GIT_EDITOR': 'true'}}
call jobwait([jobstart('env', g:jobopts)])
echo join(filter(copy(g:jobopts.stdout), 'v:val =~# "^GIT_EDITOR="'), "\n")
```

**Comment by Kazy** [comment]
Wether I run each command or I put them in a script and source the file, both printed nothing. If I add `let $GIT_EDITOR = 'false'` right before (to do something similar to what you did in the issue you opened), `GIT_EDITOR=false` is printed. 

I guess this does reproduce the bug ?

**Comment by tpope** [comment]
That `env` feature is brand new. What does `:echo has('patch-8.0.0902')` report?

Also check `:echo g:_fugitive_last_job.cmd`.

**Comment by Kazy** [comment]
`echo has('patch-8.0.0902')` returns 1. If I do `:Gcommit` then `Ctrl-C`, `g:_fugitive_last_job.cmd` is:
`['hub', '-c', 'advice.waitingForEditor=false', '-c', 'color.advice=false', '-c', 'color.branch=false', '-c', 'color.diff=false', '-c', 'color.grep=false', '-c', 'color.interactive=false', '-c', 'color.pager=false', '-c', 'color.push=false', '-c', 'color.remote=false', '-c', 'color.showBranch=false', '-c', 'color.status=false', '-c', 'color.transport=false', '-c', 'color.ui=false
', 'commit']`

**Comment by tpope** [comment]
Didn't notice on my initial testing but looks like environment variables are broken entirely for pty jobs. Added a comment to the issue.

**Comment by Kazy** [comment]
Thanks for the fix and taking the time for troubleshooting this !
