### ISSUE TITLE
GCommit error detected while processing function fugitive#Command: line 82 invalid argument pty

### ISSUE THREAD

**Issue by BlueDrink9** [tpope/vim-fugitive#1444]
Running `Gcommit` results in

> error detected while processing function fugitive#Command: 
> line 82 
> invalid argument pty

Minimal repro with `vim -u NORC --cmd "set nocp" --cmd "set rtp+=C:\Path\To\vim-fugitive"`, then `Git commit` or `Gcommit`.

I saw you introduced changes to this section [yesterday](https://github.com/tpope/vim-fugitive/commit/cd7db1d57cc991b27d9c9ce6552faea3075ada61)

**Comment by tpope** [comment]
What Vim version?

**Comment by BlueDrink9** [comment]
Thanks, confirming this worked. Sorry for not getting back to your question.
