### ISSUE TITLE
`:Git branch` shows only the last line of gits output

### ISSUE THREAD

**Issue by AlxHnr** [tpope/vim-fugitive#1445]
All other branches are shown as empty lines. Reproducible using Neovim's appimage _(0.4.3)_ with `-u NONE` and fugitive as the only plugin.

Expected output _(before 8d6f973)_:

```
* master
  development
  branch-a
  branch-b
```

Output after 8d6f973:

```



  branch-b
```

I've seen other Git commands with similar messed-up output but don't remember the steps to reproduce those.

**Comment by tpope** [comment]
Sounds very similar to https://github.com/neovim/neovim/issues/11722. Can you test if those symptoms line up?

**Comment by AlxHnr** [comment]
That was the problem. This issue does not occur with the current nightly neovim appimage.
