### ISSUE TITLE
fugitive#detect() removed

### ISSUE THREAD

**Issue by mkoura** [tpope/vim-fugitive#1448]
In https://github.com/tpope/vim-fugitive/commit/cd7db1d57cc991b27d9c9ce6552faea3075ada61 the `fugitive#detect()` was removed. There is an advice to _Contact the author if you have a reason to still use it_. I'm using a function for following symlinks:
```vim
  function! MyFollowSymlink(...)
    if exists('w:no_resolve_symlink') && w:no_resolve_symlink
      return
    endif
    if &ft == 'help'
      return
    endif
    let fname = a:0 ? a:1 : expand('%')
    if fname =~ '^\w\+:/'
      " Do not mess with 'fugitive://' etc.
      return
    endif
    let fname = simplify(fname)

    let resolvedfile = resolve(fname)
    if resolvedfile == fname
      return
    endif
    let resolvedfile = fnameescape(resolvedfile)
    let sshm = &shm
    set shortmess+=A  " silence ATTENTION message about swap file (would get displayed twice)
    redraw  " Redraw now, to avoid hit-enter prompt.
    exe 'file ' . resolvedfile
    let &shm = sshm

    unlet! b:git_dir
    call fugitive#detect(resolvedfile)

    if &modifiable
      " Only display a note when editing a file, especially not for `:help`.
      redraw  " Redraw now, to avoid hit-enter prompt.
      echomsg 'Resolved symlink: =>' resolvedfile
    endif
  endfunction
```
what can I use to replace `call fugitive#detect(resolvedfile)`?

Thanks

**Comment by tpope** [comment]
I would expect this function to cause `E13: File exists` when you write the file, does it not? The solution to that would be to `:edit` the file again, and that would also eliminate the need for `fugitive#detect()`.

**Comment by mkoura** [comment]
Thanks @tpope, that worked. I also found your older comment https://github.com/tpope/vim-fugitive/issues/147#issuecomment-506960242 and testing https://github.com/aymericbeaumet/symlink.vim
