### ISSUE TITLE
Gblame breaks current scroll binding settings

### ISSUE THREAD

**Issue by dianlujitao** [tpope/vim-fugitive#1449]
vimdiff splits are bound by default, after starting Gblame from one split, the split is bound with the blame window but not with the other one.

It's desirable to synchronous the blame window with all existing bound windows, or restore previous status before Gblame.

EDIT: To be precise, this is the current behavior:

Suppose there're 2 vimdiff splits _s1_ and _s2_. Before `:Gblame` both of them has `cursorbind` set. After launching `:Gblame` from _s1_, _s2_ becomes `nocursorbind` while _s1_ and the blame window have `cursorbind`. After closing the blame window with `gq` _s1_ becomes `nocursorbind` too.

**Comment by tpope** [comment]
Sounds like #1327. But doesn't this play poorly with diff folding?

**Comment by dianlujitao** [comment]
Thanks for your response! That patch essentially solved my issue, from my point of view it should be *fine* because the poor UX of Gblame with folding is not arisen from it.

A common scenario of Gblame from vimdiff for me is to quick check commit history around the cursor when resolving conflicts, and the window gets closed once the trunk is fixed.

Ofc the best fix might be implementing folding for Gblame.
