### ISSUE TITLE
Gdiffsplit takes 20 seconds to close the pane

### ISSUE THREAD

**Issue by timothy-truckle** [tpope/vim-fugitive#1450]
Closing left/right window after calling Gdiffsplit takes about 20 seconds before it closes.

what i did:

- disabled all other plugins
- Gdiffsplit on changed file
- Gdiffsplit on unchanged file
- closed from both panes
- PluginUpdate yesterday/today
- used a backup copy of my .vim from January 29th, and it worked again fine with all plugins enabled

**Comment by tpope** [comment]
You disabled other plugins, but did you disable your `.vimrc` and everything else in `.vim`? There haven't been any changes to `:Gdiffsplit` lately that I would expect to cause this, but do report back if you can reproduce this by swapping in an older Fugitive version.

**Comment by timothy-truckle** [comment]
Hello Mr. Pope, i was hoping the problem will go away, unfortunately it still
persists. I tested this in neovim and with vim-fugitive updated today. I think
a large number of lines between (curly) braces
(the long php class spans ~1500 lines between curly braces)
may be a cause  for the problem. 

It works fine if i checkout fim-fugitive tag 3.1 in ~/.vim/bundle/vim-fugitive

current version (after :PluginUpdate vim-fugitive)

Gdiffsplit close times: ttc == time to close in seconds, taken by hand

Language | diff | lines | ttc | additional Information                                                                                                                                           
------------------------------------------------------
php | none | 1552 | 117 | one class, 55 methods, class spans 1532 lines
php | none | 555 | ~2,5 | one class, 25 methods, class spans 520 lines
C | none | 669 | ~0.95 | 15 functions, longest spans 96 lines
C | none | 1415 | ~2.2 | 44 functions, longest spans 74 lines
C++ | none | 738 | ~1.73 | 19 functions, longest spans 300 lines
css | none | 378 | ~0.5 | ~200 definitions, longest spans 20 lines
html/php/js | none | 427 | ~2.0 | --

Maybe this gives you some useful hints. Thank you.

**Comment by tpope** [comment]
Try with different values of `'foldmethod'`, and also with folding turned off entirely.
