### ISSUE TITLE
Allow to diff in a new tab on diffing in :Gstatus

### ISSUE THREAD

**Issue by lourenci** [tpope/vim-fugitive#1451]
First off, thanks for the plugin.

I'd like to perform a diff on the file under the cursor in `:Gstatus` without waste part of my screen with the `:Gstatus` window. Is there some way to perform this diff in a new tab? I just found these maps in the docs:

```
dd                      Perform a |:Gdiffsplit| on the file under the cursor.
dv                      Perform a |:Gvdiffsplit| on the file under the cursor.
ds|dh                Perform a |:Ghdiffsplit| on the file under the cursor.
```

**Comment by koroliov** [comment]
you definitely can open a new tab with the buffer you want to see diffs for and run :Gvdiffsplit. Also it must work, if you press dv and close the status window with either :q or gq, the diff window will remain, I did it just yesterday

**Comment by lourenci** [comment]
This is not practical.
Most of the time, I want to diff more than one file, so closing `:Gstatus` will make me have to open it again. It's so simple with another tab, I could simply close the tab to be in `:Gstatus` again.

**Comment by tpope** [comment]
`:Git difftool -y <file>` opens a diff in a new tab. There's no map for it, but you could implement your own on top of the `.` map.

**Comment by lourenci** [comment]
Can I open a PR for that, @tpope? Thanks for the library.

**Comment by tpope** [comment]
I want to retool maps such that the big leader keys like `d` and `c` bring up an interactive popup window, and until that happens, I'm not really interested in continuing to pile onto the existing mess. I recommend implementing such a map locally using `autcocmd User FugitiveIndex`.

**Comment by sflip** [comment]
Sorry for necrobumping, but I want to have create a mapping just like you suggested, @tpope,  and fail to do so.

I want the mapping to open a diff in a new tab for the file under cursor. The problem is that I don't know **how to get this filename**:
```
augroup custom_fugitive_mappings
    au!
    au User FugitiveIndex nnoremap <buffer> dt :tab Gdiffsplit <filename>
augroup END
```
Is there a fugitive-way to get `<filename>`? In the `:help fugitive-revision` I didn't find anything. I'd prefer to call some fugitive function for this, instead of hacking something with `getline('.')`. 

Any help would be appreciated.

**Comment by tpope** [comment]
Fugitive index buffers remap `<C-R><C-F>` to do this, and there's an equivalent `<Plug>` map of `<Plug><cfile>`.

**Comment by Andoku** [comment]
@tpope @sflip 
So what's the best way to open diffs in tab from :Git?
I didn't quite understand about <C-R><C-F>, can you elaborate please?
This feature will be really useful, because it is easier to examine diffs in full window.

**Comment by tpope** [comment]
Plugging into the original proposition it would look something like

```vim
au User FugitiveIndex nmap <buffer> dt :Gtabedit <Plug><cfile><Bar>Gdiffsplit<CR>
```

**Comment by Andoku** [comment]
@tpope Perfect, thanks a lot. Why not to add it into plugin? I think it's super useful.

**Comment by andrescuco** [comment]
Would love to see this put into fugitive, I think it makes a lot of sense.

**Comment by meijieru** [comment]
> Plugging into the original proposition it would look something like
> 
> ```viml
> au User FugitiveIndex nmap <buffer> dt :Gtabedit <Plug><cfile><Bar>Gdiffsplit<CR>
> ```

It doesn't work in the staged sections.

**Comment by PhilippFeO** [comment]
> Plugging into the original proposition it would look something like
> 
> ```viml
> au User FugitiveIndex nmap <buffer> dt :Gtabedit <Plug><cfile><Bar>Gdiffsplit<CR>
> ```

What is the benefit of using an Autocommand on `FugitiveIndex` over creating the mapping via `ftplugin/fugitive.{vim,lua}`?
