### ISSUE TITLE
dv splits a window, when another vim-diff split already exists

### ISSUE THREAD

**Issue by koroliov** [tpope/vim-fugitive#1452]
Hi, thank you for the plug-in, and let me ask about this issue, could you suggest something with it:
Until today it used to work this way (step by step): 

- I pressed dv in the status window (with the cursor being on a file name)
- fugitive would split the window below into the two diff windows and place the cursor on one of them (image 1)
-  I returned to the status window and pressed dv either on another file name or the same one
-  fugitive would kind of use the two already existing diff windows below the status one (image 1)

![image-1](https://user-images.githubusercontent.com/1567580/73597545-b75b0400-4535-11ea-91e9-ee94d63c5276.png)

But today (presumably) (and I didn't update fugitive before I noticed this (so it may be something with a new version of vim))  it started to behave this way: 
- I pressed dv in the status window (with the cursor being on a file name)
- fugitive split the window below for the two diff windows and place the cursor on one of them (like at image 1 above)
-  I returned to the status window and pressed dv either on another file name or the same one
-  fugitive split a window once again, creating 3 windows below the status one (image 2 below)

![image-2](https://user-images.githubusercontent.com/1567580/73597642-b8406580-4536-11ea-9e86-4df24f6dec8e.png)

Also this doesn't happen, if I return to the status window from the left one, not from the right one. Then fugitive "reuses" the existing split and does not open the extra window.

I tried to isolate this by staring vim with `vim --noplugin -u NONE` then `packadd vim-fugitive`, but it output many error lines this: 
```

--- Autocommands ---
line  371:
E10: \ should be followed by /, ? or &
```

And when I started vim with `vim --noplugin` that is with my vimrc file, then used `packadd vim-fugitive`, then `:20Gstatus`, fugitive said `fugitive: file does not belong to a Git repository`. That is, I wasn't able to isolate the issue too much.

Also if this could be of any use to you, I use:
```

vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 27 2020 00:00:00)
Included patches: 1-158
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version without GUI.  Features included (+) or not (-):
```

**Comment by tpope** [comment]
> I tried to isolate this by staring vim with `vim --noplugin -u NONE` then `packadd vim-fugitive`, but it output many error lines this:
> 
> ```
> 
> --- Autocommands ---
> line  371:
> E10: \ should be followed by /, ? or &
> ```

You're in compatibility mode. Use `-N`.
 
> And when I started vim with `vim --noplugin` that is with my vimrc file, then used `packadd vim-fugitive`, then `:20Gstatus`, fugitive said `fugitive: file does not belong to a Git repository`. That is, I wasn't able to isolate the issue too much.

Reload the buffer.

> Also if this could be of any use to you, I use:
> 
> ```
> 
> vim --version
> VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 27 2020 00:00:00)
> Included patches: 1-158
> Modified by <bugzilla@redhat.com>
> Compiled by <bugzilla@redhat.com>
> Huge version without GUI.  Features included (+) or not (-):
> ```

Brand new Vim version is indeed a probable culprit. Here's where the diff is actually closed if you want to try to troubleshoot what is going wrong:

https://github.com/tpope/vim-fugitive/blob/3221cdfbde27da59dfb593c07487e8be1a3ad36b/autoload/fugitive.vim#L4325-L4327

**Comment by koroliov** [comment]
For someone who's experiencing the same issue I can suggest a quick dirty solution: simply switch to the left window before you move to the status window. If you have mappings for moves between windows this can take just a single extra key stroke <kbd>h</kbd>, like here: <kbd>Ctrl</kbd><kbd>h</kbd><kbd>k</kbd> which can be achieved with these mappings in the vimrc file:

    nnoremap <C-J> <C-W>j
    nnoremap <C-H> <C-W>h
    nnoremap <C-K> <C-W>k
    nnoremap <C-L> <C-W>l

**Comment by koroliov** [comment]
It has been fixed in:

> 1c1014a Continue running commands on Vim exit

Thank you
