### ISSUE TITLE
Output is not terminal when "cc" in Gstatus window

### ISSUE THREAD

**Issue by run2cmd** [tpope/vim-fugitive#1454]
After some update I started to experiance below problem when I do "cc" in Gstatus window to enter commit message. It says `Vim: Warning: Output i not to a terminal` and the only way to get out of it is to press Ctrl+c.

I use Gvim 8.2.200 for Windows.

Here is log output.
```
Calling shell to execute: "(git -C c:/code/aurora_commons/accounting --literal-pathspecs config -z --get-regexp "^alias[.]") >C:\Users\pbugala\AppData\Local\Temp\VIo7107.tmp 2>&1"Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal

Executing CursorHold Autocommands for "*"
autocommand if exists('*ale#engine#Cleanup') | call ale#cursor#EchoCursorWarningWithDelay() | endif
```

**Comment by tpope** [comment]
What is `:echo $GIT_EDITOR`?

**Comment by run2cmd** [comment]
Both the same from inside GVIM and from CMD on Windows

```shell
C:\Users\pbugala>echo %GIT_EDITOR%
C:\\Windows\\vim.bat
```

**Comment by tpope** [comment]
Then https://github.com/vim/vim/issues/5485 is to blame. To work around, I recommend removing that environment variable and instead setting the `core.editor` Git configuration option.
