### ISSUE TITLE
Doesn't work with tildes in the path

### ISSUE THREAD

**Issue by arkku** [tpope/vim-fugitive#1455]
If any directory name in the repository's path contains `~` tildes, fugitive seems to stop working.

Steps to reproduce:

``` sh
mv myrepository 'my ~ repository'
cd 'my ~ repository'
vim myfile -c Gstatus
```

**Comment by arkku** [comment]
The reason why this is relevant is that Apple's unchangeable iCloud drive path internally contains a directory named `com~apple~CloudDocs`, and this breaks fugitive even if accessed via a symlink.

**Comment by tpope** [comment]
```sh
```

**Comment by tpope** [comment]
This is working fine for me:

```sh
cd /tmp
mkdir 'foo ~ bar'
cd 'foo ~ bar'
git init
vim myfile -c Gstatus
```

Are you sure the tilde is the relevant factor?

**Comment by arkku** [comment]
Turns out the problem was the combination of my cargo-culted `wildignore` setting and tilde in the path. Either of them was fine without the other, so I didn't think to look further. Anyway, solved by removing the offending `set wildignore` from my `.vimrc`, sorry for the trouble.

FWIW, the line was:

    set wildignore+=*/.git/*

**Comment by tpope** [comment]
With that option set, `:edit /tmp/foo~bar/.git/config` is a no-op. I'd call that a Vim bug. You can work around it by backslash escaping the tilde, but this is inconsistent with `fnameescape()`'s behavior.  `:exe 'edit' fnameescape(filename)` should always work, as I understand it.

If you or anyone else wants this fixed, I'd recommend reporting it upstream.
