### ISSUE TITLE
Gblame in conflict with minibufexpl

### ISSUE THREAD

**Issue by jerryyin** [tpope/vim-fugitive#1456]
I have both `fugitive` and `minibufexpl`([fholgado/minibufexpl.vim](https://github.com/fholgado/minibufexpl.vim)) installed. When running `Gblame` they two seems to run into compatibility issues and yield the follow error:

> Error detected while processing function fugitive#Command[25]..<SNR>61_BlameSubcommand:
line  183:
E201: *ReadPre autocommands must not change current buffer

I opened vim's debug logging and the relevant log is below:

> Calling shell to execute: "(git -C /root/tensorflow-upstream --literal-pathspecs --no-pager -c 'blame.coloring=none' -c 'blame.blankBoundary=false' blame --show-number --contents - -- tensorflow/core/kernels/conv_ops.cc > /tmp/verC6g6/3.fugitiveblame 2> /tmp/verC6g6/3.err) < /tmp/verC6g6/4"
Executing ShellFilterPost Autocommands for "*"
autocommand call fugitive#ReloadStatus(-2, 0)

> [sy:git] Updating signs.
[sy:git] sy#repo#get_diff()
Reading viminfo file "/root/.viminfo" marks
not found in 'runtimepath': "syntax/minibufexpl.vim syntax/minibufexpl/*.vim"
not found in 'runtimepath': "indent/minibufexpl.vim"
not found in 'runtimepath': "ftplugin/minibufexpl.vim ftplugin/minibufexpl_*.vim ftplugin/minibufexpl/*.vim"
[sy:git] Update is already in progress.
[sy:git] Update is already in progress.
Error detected while processing function fugitive#Command[25]..<SNR>61_BlameSubcommand:
line  183:
E201: *ReadPre autocommands must not change current buffer
--- Signs ---

From the log it looks like the `Gblame` command requires a implementation of sytax/indent/ftplugin of another (`minibufexpl`), therefore I'm filing as an issue here. 

To reproduce, install both plugins, and run `Gblame`.

**Comment by tpope** [comment]
Cannot reproduce with both plugins installed, but I don't have whatever this `[sy:git]` plugin is.

The root cause is something changing a buffer during a `BufReadPre`. I don't see any evidence it's us, nor is there anything we can do if it's *not* us, so I think this probably isn't a Fugitive bug.

**Comment by jerryyin** [comment]
As an updated information, I did a text replacement from `BufReadPre` to `BufRead` and the `Gblame` is working again. Any thoughts in isolating what is writing the buffer?

**Comment by tpope** [comment]
A text replacement where? All your plugins?

**Comment by jerryyin** [comment]
A text replacement in `vim-fugitive/autoload/fugitive.vim`.

**Comment by tpope** [comment]
Figure out which of the things you changed fixed it.

**Comment by jerryyin** [comment]
After some further debugging it does look like this breaks because Gblame bring on the new buffer using `BufReadPre`, and at the same time `minibufexpl` will update buffer based on `AutoUpdate` (to update the buffer status, which is a write.) Based on the latest information it doesn't look like it is the issue of the `minibufexpl` because the plugin's basic functionality is to bring updated information of all buffers. Therefore, I think if `fugitive` can use `BufRead` instead of `BufReadPre` this issue can be avoided.

**Comment by tpope** [comment]
Fugitive can't use `BufRead` instead of `BufReadPre`. Did you figure out which of the things you changed was relevant?

**Comment by jerryyin** [comment]
Thanks for the response it looks like edit goes in parallel with yours. I was talking about [this line](https://github.com/tpope/vim-fugitive/blob/master/autoload/fugitive.vim#L2195)

**Comment by tpope** [comment]
See if emptying this function out fixes it. If so, see if you can figure out which line is causing the error.

https://github.com/tpope/vim-fugitive/blob/083f3c23ccad22b5d2bdabcbb8a076e8c695686b/autoload/fugitive.vim#L2162-L2174

**Comment by jerryyin** [comment]
Nice, I should have narrowed this further. I figured that 2166:`setlocal bufhidden=delete nobuflisted` is the culprit.

**Comment by jerryyin** [comment]
Gentle ping, mind reopen this issue for tracking purpose?

**Comment by tpope** [comment]
I still need a way to reproduce this. Does this happen with *only* Fugitive and minibufexpl installed? Your debug log suggests you had other plugins installed.

**Comment by jerryyin** [comment]
Yes, this happen with only `Fugitive` and `minibufexpl` installed. I have reproduced again with only those two installed. The updated log on my end does not have `[sy:git]` lines in it.

I'm using VIM 8.2 with latest of fugitive and latest of minibufexpl.

**Comment by tpope** [comment]
Do you have any configuration options set for minibufexpl? How are you opening its window, if at all?

**Comment by jerryyin** [comment]
Thanks for asking. I have zero other configurations for either fugitive or minibufexpl. However, I did narrow it down to another .vimrc setting that is key to reproduce this: `set autochdir`. I'm only able to reproduce the problem with this setting on.

**Comment by tpope** [comment]
So minibufexpl is, and I say this without exaggeration, the worst plugin in all of Vim history. It abuses autocommands in all sorts of extremely fragile ways that routinely break other plugins. Whenever I see an autocommand or window related bug report, on any plugin, I always reply with "try disabling other plugins", and minibufexpl is *the* reason I do so. Thank goodness it's popularity declined after Vim got tabs or I probably would have quit the industry by now. (It's possible the fork is better behaved than the original. It's certainly not worse behaved, that would be impossible.)

Meanwhile, this is from the documentation for `'autochdir'`:

> Note: When this option is on some plugins may not work.

Knowingly or not, you've combined the world's most broken Vim plugin with the world's most broken Vim option. Fugitive never had a chance.

I'm going to try moving `'buflisted'` to `BufReadPost`, but if that causes other problems, I will not hesitate to revert. Until proven otherwise, this is a minibufexpl bug, not a Fugitive bug.

**Comment by jerryyin** [comment]
Thank you! I appreciate the time and effort to address it. Believe it or not, I've been using `minibufexpl` for ten years, and I'm seeing an increasing number of use case where it broke something else. It is this time the fugitive conflict make me abandoned it for a tab based solution. If there is any problem in the newest commit, feel free to revert it. I'm no longer a `minibufexpl` user now.
