### ISSUE TITLE
[neovim] Warning messages are sometimes flushed to commit message buffer

### ISSUE THREAD

**Issue by jaekyeom** [tpope/vim-fugitive#1458]
I'm using neovim v0.4.3.

In `:GStatus`, I pressed `C` (which is deprecated now) and this happened:

![image](https://user-images.githubusercontent.com/6262727/73836078-dae1bf80-4851-11ea-882f-23b96466f4f1.png)

It's not deterministically reproducible, but it looks like the default content for that buffer and the warning message are mixed up.

I know that `C` is deprecated, but the message still shouldn't be there.

**Comment by tpope** [comment]
Seems like this is incompatible with the new `:Git`. Luckily there's an easy fix.
