### ISSUE TITLE
:Gstatus buffer shows binary data

### ISSUE THREAD

**Issue by PhilRunninger** [tpope/vim-fugitive#1463]
Tim, thanks for the fantastic plugin.

I don't know the circumstances under which this happens, except that it's never the first time during a Vim session. After `:Gstatus`, staging, committing, and then `gq` to close the window, subsequent `:Gstatus` commands occasionally will display a buffer full of binary characters. My workaround has been to issue a `:bwipeout` command, followed by another `:Gstatus`. My initial thought is to replace the `bdelete` commands with `bwipeout` in [these lines](https://github.com/tpope/vim-fugitive/blob/0e6f72b005312225ffb47290500941d59eb1f0f7/autoload/fugitive.vim#L1960-L1962), but then I noticed there are several other instances, too many for me to feel comfortable changing. I'd rather leave that decision up to the expert.

**Comment by tpope** [comment]
`gq` isn't the only sanctioned way to close the buffer so this wouldn't really fix anything, just sweep it under the rug.

Does `:edit` in the `:Gstatus` buffer *without* `:bwipeout` fix it? If not, what are the first few lines of `:9verbose edit`? I'm expecting to see `Executing BufReadCmd Autocommands for "index{,.lock}"`.

**Comment by PhilRunninger** [comment]
Thanks. Next time it happens, I'll report back.
