### ISSUE TITLE
diffing loaded json file just diffs with itself

### ISSUE THREAD

**Issue by gfixler** [tpope/vim-fugitive#1464]
Full discloure: I'm in tmux in MSYS2 on a Windows 10 box, but everything has been great for months. Now I'm noticing that `:Gdiff` on this big JSON file is loading the file twice, and diffing them, which of course shows no differences, because they're both the same file. This works whether I `:Gdiff`, or pop up `:Gstatus`, and `d`, `gh`, or `gv` on the file.

I've tried another repo - diffing files there worked fine - and making a new file with some edits in this repo - diffing worked fine. It seems to be this particular JSON file. If I stage it, then I can diff that just fine. If I then unstage it, it starts loading up two copies of the same, modified file again, which show no differences. If I don't load the file into the buffer and :Gstatus, then `d`, `gh` or `gv` on the file, it works. `git diff` on this file out in the terminal works fine.

Any idea what I can test here?

**Comment by tpope** [comment]
What does "loading the same file twice" mean? Are you saying that it's the same *buffer*, with the same `bufname('')` and the same `bufnr('')`, or are you saying it's two different buffers with distinct `bufname('')` and `bufnr('')` values but the *contents* are the same?

What is "`d`, `gh`, or `gv`"? I'm guessing you mean `dd`, `dh`, and `dv` but that's meeting you more than halfway.

**Comment by gfixler** [comment]
Apologies. Yes, I meant `dd`, `dh`, and `dv`. It loads the same buffer in both splits. They share the same `bufname` and `bufnr`, the latter being 1.

**Comment by tpope** [comment]
Try all of the following in the JSON buffer and report back on which work:

* `:Gdiffsplit`
* `:Gdiffsplit!`
* `:Gdiffsplit :0`
* `:Gdiffsplit! :0`
* `:Gdiffsplit :0:%`
* `:Gdiffsplit! :0:%`
* `:Gdiffsplit HEAD`
* `:Gdiffsplit! HEAD`
* `:Gdiffsplit HEAD:%`
* `:Gdiffsplit! HEAD:%`

**Comment by gfixler** [comment]
Only 2 worked, and by worked, I mean, whether the JSON file was staged or unstaged, these created 2 splits, with unique contents, `bufnr`, and `bufName`, and proper visual diff colors:

* `:Gdiffsplit HEAD`
* `:Gdiffsplit! HEAD`

The splits contained my JSON file on the right, and fugitive file on the left, pathed to the .git//<hash>, with a diff header at the top, and diff @@ lines scattered throughout. All 4 variants - with `!` and without, file staged or unstaged - yielded those same 2 splits (JSON at right, long git hash path on the left).

All of the rest of the commands, with the file staged or unstaged, created 2 splits with the same `bufnr`, `bufName`, and contents.

**Comment by tpope** [comment]
This is the exact behavior you get if you call `:Gdiffsplit` on a path that belongs to a repo but lives outside of it (for example, a temp file generated by `:Git --paginate`). Does the file have a weird name? Are there symlinks involved in anything you are doing?

**Comment by gfixler** [comment]
Just came back from talking with the devs, after noticing the path was pointing to another drive. You're right. This is the first repo I lazily started in our project, instead of my home folder. The project is a junction (apparently a Windows symlink?). I work on the D drive, but that fugitive path I was getting in the right split was to the F drive.

**Comment by gfixler** [comment]
Well, it sounds like symlinks and junctions are a known issue, and I've just tested things in my home space, and they work, so I'm closing this out. Thanks for your help!
