### ISSUE TITLE
Can't :Gcommit because of 'invalid key'

### ISSUE THREAD

**Issue by tankorsmash** [tpope/vim-fugitive#1466]
![image](https://user-images.githubusercontent.com/1312390/74482144-fa946b80-4e81-11ea-805f-8f4a47e607c5.png)

The error reported is (unmatched quote is from the message):

```
error: invalid key: "color.advice
fatal: unable to parse command-line config
```
I'm running gvim 8.1 with patches 1-677; `git version 2.24.1.windows.2`, and the latest vim-fugitive

It seems like it could be related to issue #1444, but I don't have any strange binary readout in my Gstatus, since it looks normal.

**Comment by tpope** [comment]
How did you install Git? This sort of error can happen when you do something weird like mix a Cygwin Git with cmd.exe (to name just one of many examples).

**Comment by tankorsmash** [comment]
It's been a little while since I installed it, but it was likely through https://git-scm.com/downloads. How can I check to see if there's some sort of conflict.

Something may have installed incorrectly on my system, because even running `git commit -a` from the terminal throws a strange error:

```/usr/bin/cut: you must specify a list of bytes, characters, or fields
Try '/usr/bin/cut --help' for more information.```

So this may just be on my end altogether.

**Comment by tpope** [comment]
All of this sounds like you have 2 different UNIX environments installed and they are interacting badly.

**Comment by tankorsmash** [comment]
Yeah, seems like it. I just tried out vim-fugitive 2.4 instead of the latest and it's working, so worst case I can downgrade if I can't sort my envs out.

I'll close this issue, thank you!

**Comment by tpope** [comment]
#1433 fundamentally changed how `:Git` worked.

You might have luck upgrading to Vim 8.1.0902 or newer, as that allows passing in environment variables rather than needing to construct a shell command.

**Comment by tankorsmash** [comment]
I'll try updating vim to that, thank you. I just narrowed down the breaking commit to https://github.com/tpope/vim-fugitive/commit/cd7db1d57cc991b27d9c9ce6552faea3075ada61, whereas [the one before](https://github.com/tpope/vim-fugitive/commit/cd7db1d57cc991b27d9c9ce6552faea3075ada61~) works.

**Comment by tpope** [comment]
That commit had some junk in it that was reverted. Try df3ac9d278c13e06888e0270ae7296377ec05ee7 (last good commit?) and e144a9f55986317a0c1dd78bb83748396d0a7e5e (first bad commit?).

**Comment by tankorsmash** [comment]
Grabbed the [latest v8.2 build](https://github.com/vim/vim-win32-installer/releases/download/v8.2.0251/gvim_8.2.0251_x86.exe), which works with vim-fugitive's `master`, before I saw your comment just now. The updater uninstalled 8.1 it seems like. 

Thank you for helping me work through this, it's now resolved via updating vim.
