### ISSUE TITLE
Feature request: Option to allow deleting directories from the staging area.

### ISSUE THREAD

**Issue by roosemberth** [tpope/vim-fugitive#1467]
As a user, when my cursor is on an untracked directoty in the staging area; I would like to press 'X' to delete said directoty.

Current behaviour: Error message: "fugitive: will not delete directory" appears.

**Comment by tpope** [comment]
Deleting a file displays "To restore" instructions that let you undo if you pressed the key by accident. There's no good equivalent for directories so the operation is disabled. I will not be adding a "let me shoot myself in the foot with a single keypress" option. If you want this behavior you'll have to implement it your own map.

One day I want to add an `x` map that prompts for confirmation. For that map I'd be okay to allow deleting directories.

**Comment by kecerud** [comment]
@tpope nearly 3 years later, do you still think this would be a worthwhile addition? (x map prompt that is)

**Comment by tpope** [comment]
Yes, but it remains at the bottom of the priority list. I'll confess I don't get the use case. (Who creates and deletes untracked directory hierarchies so often that they need to be able to delete them with a single keystroke?)

**Comment by roosemberth** [comment]
My two cents:

After working in a feature, I remove all temporary files or directories used during the development of such feature I may have created. I do it all from vim and it just feels odd to 'drop' files from vim but have to 'Ctrl-Z + git status + rm foo bar baz + fg' for directories. To be clear, I'm not looking to 'git clean'.

I must say, although dropped files are stored as git objects I don't think I'd ever find myself in need to restore a dropped file.

On 18 February 2023 05:34:53 CET, Tim Pope ***@***.***> wrote:
>Yes, but it remains at the bottom of the priority list. I'll confess I don't get the use case. (Who creates and deletes untracked directory hierarchies so often that they need to be able to delete them with a single keystroke?)
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/tpope/vim-fugitive/issues/1467#issuecomment-1435480780
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Johannesklint** [comment]
I would love this feature!
I often create and deletes directories. The reason for doing that is that our tests creates mocks automatically, and sometimes you try out things, and then you want to delete those mocks (directories) that was recently created.
