### ISSUE TITLE
Follow symlinks (and act on the target repository)

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-fugitive#147]
If I edit ~/.pentadactylrc (not in Git) which is a symlink into ~/.dotfiles/pentadactylrc (in Git) I would like `:Gcommit` et al to work on it, too.

This should be possible if fugitive would follow symlinks and recognize that the file itself is located in a git repository and add appropriate parameters to invocations of git, i.e. '--git-dir'.

**Comment by blueyed** [comment]
@wilywampa 
You can use `call fugitive#detect(resolvedfile)` instead.

I've added it to my method: https://github.com/blueyed/dotfiles/blob/ab2850675bbfcf0db18dbf81a31b90e65aaae7f8/vimrc#L1247-L1278

**Comment by AssailantLF** [comment]
I made a Windows compatible version of the MyFollowSymlink function. It's really messy and inefficient, and needs to be ran from the buffer of the symbolic file, but seems to work for simple cases. Hopefully others may find it useful, or can improve upon it:

    function! MyFollowSymlink(...)
      let lit = a:0 ? a:1 : '%:p'
      let fpath = expand(lit)
      let recur = a:0 > 1 ? a:2 : 10
      if !recur
        return
      endif
      let matstr = '<SYMLINK..\s\+' . expand(lit.':t') . ' ['
      " check if it's a symlink
      if (match(system('dir ' . fpath . '*'), matstr) == -1)
        " check if parent dir is symlink
        call MyFollowSymlink(lit.':h', recur-1)
      else
        " extract symlink path
        let substr = '.*<SYMLINK..\s\+' . expand(lit.':t') . ' \[\(.\{-}\)\].*'
        let fpath = substitute(system('dir ' . fpath . '*'), substr, '\1', "")
        " figure out current file's path
        let resolvedfile = filereadable(fpath) ?
              \fpath : findfile(expand('%:t'), fpath, '**')
        exec 'file ' . resolvedfile . ' | w! | doautocmd BufReadPost'
      endif
    endfunction

**Comment by burgerga** [comment]
It's quite confusing because gitgutter does follow the symlink, so I can see the changes but not act on them ;)

**Comment by dalejung** [comment]
@burgerga gitgutter handles the symlink internally. i just patched my local vim-fugitive to do the same and it fixes my use case. https://github.com/dalejung/vim-fugitive/commit/21b91d4c18dcdf2a6292a172ab09776d41a6b715 if you want to try.

**Comment by burgerga** [comment]
@dalejung Works for me, thanks! ;)

**Comment by jez** [comment]
@dalejung I tried patching my local vim-fugutive as per your linked commit, but none of the commands now work. It seems that every call to `s:buffer().path()` now returns `''`.

I'm a little surprised. Does your "use case" involve all fugitive commands, or just a few? I only tried `:Gblame` and `:Gwrite`, but neither worked. Was there no other configuration (except the changes in that commit) on your end to get it working?

**Comment by HaleTom** [comment]
There is a pending PR to resolve this: #814   Windows users please test!

FYI, this is how [airline resolved the issue](https://github.com/vim-airline/vim-airline/pull/1202/files).

**Comment by hanyk** [comment]
https://github.com/aymericbeaumet/symlink.vim

**Comment by gotcha** [comment]
@hanyk Thanks for the hint ! symlink.vim seems to fix the issue I used to have.

**Comment by tpope** [comment]
I haven't personally tested it, but https://github.com/aymericbeaumet/symlink.vim seems like the way to go.

**Comment by c02y** [comment]
> 
> 
> Using `file` instead of `edit` appears to work.
> 
> I have adopted the following from the Reddit thread mentioned (http://www.reddit.com/r/vim/comments/yhsn6/is_it_possible_to_work_around_the_symlink_bug/c5w91qw) and the comments above:
> 
> ```
> " Follow symlinks when opening a file
> " Sources:
> "  - https://github.com/tpope/vim-fugitive/issues/147#issuecomment-7572351
> "  - http://www.reddit.com/r/vim/comments/yhsn6/is_it_possible_to_work_around_the_symlink_bug/c5w91qw
> " Echoing a warning does not appear to work:
> "   echohl WarningMsg | echo "Resolving symlink." | echohl None |
> function! MyFollowSymlink(...)
>   let fname = a:0 ? a:1 : expand('%')
>   if getftype(fname) != 'link'
>     return
>   endif
>   let resolvedfile = fnameescape(resolve(fname))
>   exec 'file ' . resolvedfile
> endfunction
> command! FollowSymlink call MyFollowSymlink()
> 
> autocmd BufReadPost * call MyFollowSymlink(expand('<afile>'))
> ```
> 
> This works OK (but unconditionally/automatically) and requires `w!` the first time when writing (which could be considered as some kind of safety-net).
> If a swap file is present already, you will get two warnings.
> 
> _edit_: removed BufNew from the autocmd line..!

It seems this code snippet has a bug, when you open a link directly, and save it like :w for the first time, it will say "E13: File exists (add ! to override)"
