### ISSUE TITLE
ftplugin interfering with Gdiff

### ISSUE THREAD

**Issue by mondO** [tpope/vim-fugitive#1473]
Hi, relatively inexperienced vim user here. 

Every time I try to use :Gdiff with Python files I get the following error, for example when I'm trying to open a file `$PROJECT_ROOT/subdir/file.py`:

```
UpdateLastColumn failed to find bufnr 2 in w:BufKillList
UpdateLastColumn failed to find bufnr 2 in w:BufKillList
Error detected while processing /home/mond0/.vim/after/ftplugin/python.vim:
line    6:
E484: Can't open file fugitive:///mnt/c/Users/mondo/Documents/workspace/project_root/.git//0/subdir/file.py
```

I know this has something to do with a small ftplugin I wrote to change the indentation settings to match my organization's settings when the python file contains my organization's name:
```
"~/.vim/after/ftplugin/python.vim
if match(readfile(expand("%:p")),"ORG_NAME")!=-1
    setlocal softtabstop=2
    setlocal tabstop=2
    setlocal shiftwidth=2
endif
```
The snippet above is the only content of `python.vim`, and commenting it out fixes my issue with Gdiff. However, I would like to keep the functionality it implements, and I don't understand why it's causing Gdiff to fail- it seems like it's interfering with the path Gdiff is looking for?

I can reproduce this error on both my home environment (running on WSL) and on my work environment, and I do not get the error when editing other kinds of files.

**Comment by mondO** [comment]
I get the same odd screwed up paths on my work environment.
```
UpdateLastColumn failed to find bufnr 2 in w:BufKillList
UpdateLastColumn failed to find bufnr 2 in w:BufKillList
Error detected while processing /home/mondo/.vim/after/ftplugin/python.vim:
line    6:
E484: Can't open file fugitive:///home/mondo/project_root/.git//0/subdir/file.py
```

**Comment by tpope** [comment]
You're calling `readfile()` on a file that doesn't exist. It's more than just Fugitive buffers that will break this: any new Python file will as well. You probably want to use `getline()`, or perhaps `search()` with the `n` flag.

**Comment by mondO** [comment]
Thanks for the help, Tim!
