### ISSUE TITLE
:Gblame mapping doesn't close split on second toggle

### ISSUE THREAD

**Issue by mschwager** [tpope/vim-fugitive#1474]
Here's my map:

```vim
" Map Ctrl+b to open git blame
:map <C-b> :Gblame<CR>
```

Hitting `ctrl + b` once opens `:Gblame` as expected. When I hit `ctrl + b` again it appears to quickly close the vertical split then re-open it. So it's impossible to close the window unless I switch to it and do `:q`. It looks like the behavior changed in `v3.1` - if I use `v3.0` the behavior works as expected.

Any idea what could be going wrong?

**Comment by tpope** [comment]
This was a deliberate change. I wanted to enable the ability to re-blame with varying options, that is, allow you to first call `:Gblame` and then later call `:Gblame -w` to see the blame with whitespace changes ignored. This was incompatible with toggling.

Here's a lightly tested map that implements the old toggling behavior:

```viml
function! s:BlameToggle() abort
  let found = 0
  for winnr in range(1, winnr('$'))
    if getbufvar(winbufnr(winnr), '&filetype') ==# 'fugitiveblame'
      exe winnr . 'close'
      let found = 1
    endif
  endfor
  if !found
    Git blame
  endif
endfunction

nmap <silent> <Leader>b :call <SID>BlameToggle()<CR>
```

Note that `:Gblame` is very softly deprecated in favor of `:Git blame`, so I've used the new form here.

**Comment by mschwager** [comment]
Good to know! Thanks for the updates.

Would it make sense to include a command for the old functionality? E.g. in Taglist and Gundo there's `:TlistToggle` and `:GundoToggle`, respectively. Something like `:GblameToggle` (or `:Git blame-toggle`) would be awesome. Toggling the Git blame functionality seems like a common enough workflow. It'd be great to provide a command out of the box similar to the above code snippet.

Thanks again for making `vim-fugitive`, I use it every day.

**Comment by tpope** [comment]
I'm phasing out `:Gblame` because I want fewer commands, not more, and I don't think I want to invent "fake" Git subcommands. I also think a toggle is better suited to a global window than a context dependent one like `:Git blame`, and as a consequence don't really want to implicitly endorse it by making it a first class feature. Thanks to your issue it should be pretty easy for users that want it to find this solution; I think that's good enough.
