### ISSUE TITLE
:Gstatus all vertical 

### ISSUE THREAD

**Issue by danielo515** [tpope/vim-fugitive#1477]
Hello, I just started using vim fugitive.
I was wondering if it is possible to open al the duffs from a git status at the right of the status window? I know there is dv for opening on a vertical split, but it opens the split above the current git status. 
Something like this 
```
| status | index  |  current |
```

Thanks!

**Comment by tpope** [comment]
It reuses the existing window. So if you want it vertical, open it vertically with `:vert Git`.

**Comment by danielo515** [comment]
Cool, I'll try that. But that command doesn't seem to produce the same interactive window as Gstatus does, but I'll try anyway

**Comment by tpope** [comment]
If `:Git` with no arguments isn't opening a status window, that sounds like you're on an old version of Fugitive.

**Comment by danielo515** [comment]
Yep, it works like you described. Thank you very much

**Comment by danielo515** [comment]
The proposed work flow is quite good. However my desired work flow is to open the git status into a new tab with vertical layout.
Right now, I have to create a new tab, vertical split it, open git status and swap the status window with the left empty (it gets open on the right side).
Is that the only way of getting the desired work flow? Is a way to do it just with fugitive commands?

**Comment by danielo515** [comment]
@tpope respecting the original window split is not good enough.
I am using the following mapping as a workaround:

```
:nnoremap <leader>gs :tabedit +Gstatus<bar>only<bar>leftabove vsplit
```

The problem with that map is that  I have to leave an empty buffer to the right or the vertical split will not be honored by gstatus. Isn't really a way to tell gstatus to always open the diff on a vertical right split? I don't want to open gstatus into my current window layout, I always open it on a new tab that I can close when I'm done with my git related stuff.
