### ISSUE TITLE
:Gbrowse should refer to the specific line being highlighted

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-fugitive#148]
When opening a file in Github via `:Gbrowse` I would like to have the anchor being added to the URL which would refer to the currently selected line in Vim.

**Comment by danfinlay** [comment]
Another example (for total noobs like I felt a minute ago), this is the same as a ranged replace. So opening and highlighting lines 98 through 120 would be: `:98,120.Gbrowse`.
