### ISSUE TITLE
:G command allow to see a number of previous commits

### ISSUE THREAD

**Issue by coot** [tpope/vim-fugitive#1483]
It would be nice if `:10G` showed 10 previous commits.  Currently the history is only shown when origin and current local branch do not agree (or one is rebasing).

This is useful when one wants to fixup a commit, it would allow to use `cf` and `ri` normal commands.

**Comment by tpope** [comment]
You can achieve what you want with `:Git log --oneline -10`. The syntax highlighting is underwhelming but the maps in question still work.

The status buffer is essentially a fake file; it can't in its current form be given different behavior based on parameters.

**Comment by coot** [comment]
ok, thanks for the tip.
