### ISSUE TITLE
{range}GBrowse in Windows expands # in url to alternate filename

### ISSUE THREAD

**Issue by tailoric** [tpope/vim-fugitive#1484]
When using the `:GBrowse` with selected range to open a link with lines in the browser the `netrw#BrowseX()` function call expands the `#` in front of the line numbers with the alternate filename (see `:help :_#`) which results in   
`https://github.com/tpope/vim-fugitive/blob/master/autoload/fugitive.vimC:/path/to/alternate/file.txtL5812-L5814`

instead of 
`https://github.com/tpope/vim-fugitive/blob/master/autoload/fugitive.vim#L5812-L5814`

I personally managed to fix it locally by adding
```vim
let url = fnameescape(url)
```
[before the two lines that call `netrw#BrowseX()` and `netrw#NetrwBrowseX()`](https://github.com/tpope/vim-fugitive/blob/master/autoload/fugitive.vim#L5812-L5814)

I can create a pull request for that if needed, although I have limited to no experience with vim plugin development so I don't know if this can cause problems elsewhere. 
Testing my fix on my Windows and Ubuntu machine however has not resulted in any problems for that specific functionality.

**Comment by tailoric** [comment]
After some more testing I think this problem is caused by me having `shellslash` activated on Windows 
when setting it to `noshellslash` in that buffer the error is not appearing.

However with my "fix" of escaping the `#` now it results  in the following url
`https://github.com/tpope/vim-fugitive/blob/master/autoload/fugitive.vim/#L5812-L5814`
which still works for linking to the lines but adds an unnecessary character.
Perhaps it would be a better idea to force noshellslash before executing `netrw#BrowseX()` and recover the old setting after the browse is done?

**Comment by tailoric** [comment]
fixed it for myself by removing shellslash setting in my vimrc

**Comment by tpope** [comment]
Unfortunately the primary purpose of `'shellslash'` isn't aesthetics, it's to interop with UNIX shells. For example, see `:help shellescape()`:

```
shellescape({string} [, {special}])			*shellescape()*
		Escape {string} for use as a shell command argument.
		On MS-Windows, when 'shellslash' is not set, it will enclose
		{string} in double quotes and double all double quotes within
		{string}.
		Otherwise it will enclose {string} in single quotes and
		replace all "'" with "'\''".
```

Setting this option when using `cmd.exe` will cause escaping problems; you've done the right thing by removing it.

**Comment by idbrii** [comment]
I believe this is actually a bug in netrw. 

I'm able to use shellslash and Gbrowse by installing [tyru/open-browser.vim](https://github.com/tyru/open-browser.vim) and adding a Browse command so Gbrowse will use it:

    command! -nargs=1 Browse OpenBrowser <args>
