### ISSUE TITLE
fatal: Unable to create '/<path_to_repo>/.git/index.lock': File exists.

### ISSUE THREAD

**Issue by ioanniswd** [tpope/vim-fugitive#1489]
Getting this error consistently when attempting to perform an interactive rebase with the commit under the cursor set to `reword`:

```
fatal: Unable to create '/<path_to_repo>/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
could not detach HEAD
```

Rebasing from the terminal works.

#### Steps to reproduce:
1.  Run `:Gstatus`
2.  Move cursor to a commit hash
3.  Press `rw`
4. Run `:wq`

Using `git bisect` found this commit c989c1f59ea00a2fe719e37eb782a4eb95c430e9 to be the culprit.

**Comment by tpope** [comment]
* Does that `index.lock` file exist when before you restart the rebase?
* Does the issue happen if you use `:Git rebase -i <commit>` when the status window isn't open?
* What version of Git?

**Comment by ioanniswd** [comment]
- No, it does not exist
- It does not happen with `:Git rebase -i <commit>` when status window isn't open (it does however happen if status window is open)
- git version 2.11.0

**Comment by tpope** [comment]
The issue is that the rebase and the status buffer reload are competing for that lock, but I don't really understand how that's possible since both operations are synchronous. 8e90d82eb4f4bd71de1dafd5f3ae4bfaca1a79bd fixes it for versions with `--no-optional-locks`. That option was added 2.5 years ago, while your Git version is 3.5 years old.

One thing to try: rearrange all windows such that when you `:wq` the rebase todo, a window that's not the status buffer takes the focus. That would at least confirm the source of the problem.

**Comment by ioanniswd** [comment]
Rearranged the windows and issue does not occur, so it is confirmed.

Also, upon further investigation, this might correlate with the number of commits. Tried it on a different repo with far fewer commits (with two different laptops) and the issue does not appear. It only appears on the big repo (~90K commits). Could something being slowed down due to repo size  be the source of this issue?

**Comment by tpope** [comment]
Bigger repos being slower and more likely to trigger a race condition would certainly make sense.

It's a bit of a shot in the dark, but can you see if the `job-status-check` branch fixes it?

**Comment by ioanniswd** [comment]
Shot missed. Still getting the same error.

**Comment by tpope** [comment]
Try the slightly less blind `race-condition` branch.

**Comment by ioanniswd** [comment]
Works like a charm!
Thanks a lot.
