### ISSUE TITLE
Unable to setup default layout

### ISSUE THREAD

**Issue by Shatur95** [tpope/vim-fugitive#1490]
If I use the following commands:
```vim
:G
<C-w> L
cc
```
I have the following layout:
![image](https://user-images.githubusercontent.com/22453358/76402831-a307f380-638c-11ea-92ce-cbe1adb1ac3a.png)

But when I trying to make such layout by default by creating `after/ftplugin/fugitive.vim` with the following content:
```vim
wincmd L
```
with this commands:
```vim
:G
cc
```
I have the following layout:
![image](https://user-images.githubusercontent.com/22453358/76402620-5b816780-638c-11ea-9a31-dfcad49ec1bc.png)

Is this a bug, or am I doing something wrong? This windows have different types: `gitcommit` and `fugitive`.

**Comment by tpope** [comment]
The `FileType fugitive` event triggers every time the status window reloads. And it reloads every time you run a `:Git` command, including `:Git commit`. You'll need to find another way.

**Comment by Shatur95** [comment]
Is there any other way to set default window open options?

**Comment by tpope** [comment]
You can use `:botright vert G`. Like the `:split` command it wraps, it's not configurable, but you can wrap `:botright vert G` in a command or a map if you'd like to avoid typing it out each time.

**Comment by Shatur95** [comment]
But this will only configure for the Gstatus command. Commands like `:G rebase -i @~3` will still open horizontally :(
Therefore, I am trying to set defaults for the entire window type.

**Comment by tpope** [comment]
`:vert G rebase -i` opens vertically.

**Comment by Shatur95** [comment]
Yes, I know, but for this I need to type `:vert` every time :(

Now I figured it out in this way:
![изображение](https://user-images.githubusercontent.com/22453358/76470079-6a9dff00-63f8-11ea-9302-05e045541b6f.png)

fugitive.vim
```vim
wincmd L
```
git.vim
```vim
wincmd J
setlocal spell
```
But I can’t figure out how to place the commit message under / below the fugitive window with filetype settings.
