### ISSUE TITLE
vim-fugitive is Slow

### ISSUE THREAD

**Issue by benlieb** [tpope/vim-fugitive#1492]
New user here, using MacVim. All the commands I've tried so far take about 2 seconds or more to produce output. Some take up to 5 or more. It's too bad that I'm so impatient, because I've already found myself going back to the command line.

 I've read a couple of issues here about it, and I wonder if there's anything that I can do in my env to help things.

**Comment by tpope** [comment]
Nine times out of ten this is a shell issue. Don't add `-i` or `-l` to `'shell'` or `'shellcmdflag'`. If you're using zsh, don't put anything heavy in `.zshenv`. And if you're using a slow, non-standard shell, avoid using it in Vim by doing `:set shell=/bin/bash`.

**Comment by benlieb** [comment]
Thank you for your feedback, but I'm quite sure what you mean. Do you mean a vim setting or a env var setting?

I'm using a standard bash shell on Mac.
