### ISSUE TITLE
Gstatus doesn't remember the cursor location

### ISSUE THREAD

**Issue by ilnli** [tpope/vim-fugitive#1494]
When running Gstatus and then exiting the status window, it lands the cursor on the very first opened window and not to the one from where Gstatus was run. It would be nice if it can remember the last location of the cursor as that will help with fast switching between the status window and back.

(For me it always lands the cursor to the NERDTree window)

**Comment by tpope** [comment]
Fighting Vim's window management is high effort and low reward. If you want to pick that fight, you're on your own. I also don't think there's any advantage to doing it inside Fugitive instead of externally, so I don't see any reason to ship it as part of Fugitive.
