### ISSUE TITLE
Setting fugitive-summary preview height

### ISSUE THREAD

**Issue by Irubataru** [tpope/vim-fugitive#1495]
As `:{windowheight}Git` isn't supported with the latest commit (9a4d730270), would it be possible to give an idea how one would accomplish this now?

Also maybe something to add to the README or the Wiki?

Anyway, awesome plugin :heart:

**Comment by tpope** [comment]
I think creating the split first and then loading the status within it would work: `:10split|0Git`.

**Comment by Irubataru** [comment]
That does seem to work, thanks!

Could you explain why you have to do `0Git` and not just `Git` or `1Git` for that sake?

**Comment by tpope** [comment]
As mentioned in the documentation, `:0Git` does `:edit` rather than `:split`.

**Comment by moll** [comment]
For the sake of discussion, unless I'm mistaken, these days `:Git` and `:0Git` seems to call `:resize` to fit all displayed lines. So opening a split before `:0Git` doesn't particularly achieve what @Irubataru was after. I suspect `:resize` gets called also when the summary buffer is updated/refreshed.

**Comment by moll** [comment]
> For the sake of discussion, unless I'm mistaken, these days `:Git` and `:0Git` seems to call `:resize` to fit all displayed lines. So opening a split before `:0Git` doesn't particularly achieve what [@Irubataru](https://github.com/Irubataru) was after. I suspect `:resize` gets called also when the summary buffer is updated/refreshed.

Hmm, on further inspection, I think I'm mistaken. Sorry about that! The `resize` commands within Fugitive seem to be restricted to `:Git blame` and it was instead my attempt to resize `:Git`'s window that probably created a situation where Vim itself was constantly resizing it somehow to its max height.
