### ISSUE TITLE
when i `:G clone git@github.com:foo/bar.git`, it always be downloaded in `$HOME`

### ISSUE THREAD

**Issue by Freed-Wu** [tpope/vim-fugitive#1496]
OS: Linux-5.4
vim: gvim-8.2.0114

when i `:!git clone git@github.com:foo/bar.git`, it will be downloaded in the current directory.
but when i `:G clone git@github.com:foo/bar.git`, it always be downloaded in `$HOME`...

why this phenomenon occur? does it exist a variable to disable this phenomenon? Thank you!

**Comment by tpope** [comment]
`:G` always operates in the root of the current repository if one is present. Do you have `~/.git`?

**Comment by Freed-Wu** [comment]
you are right! i use git to backup my `~/.zshrc`. so what should i do to avoid this phenomenon?

**Comment by tpope** [comment]
Using a `./` path, for example `:G clone git@github.com:foo/bar.git ./bar`, will force Fugitive to translate the path to be relative to the current directory.
