### ISSUE TITLE
Calling feedkeys can pollute the buffer

### ISSUE THREAD

**Issue by przepompownia** [tpope/vim-fugitive#1497]
I have mapping that execute `<C-o>:q<CR>` from insert mode. Yes, it doesn't make sense and I will replace `<C-o>` to `<ESC>`. 

Anyway, please test closing `Gcommit` buffer this way. 
The line `":redraw!|call fugitive#Resume()|silent checktime\r"` is then added into the last used buffer. 

This behavior should not occur anyway.

**Comment by tpope** [comment]
Feel free to investigate adding `<C-\><C-N>` to the feedkeys call.
