### ISSUE TITLE
":Git gui" wrong locale

### ISSUE THREAD

**Issue by phmarek** [tpope/vim-fugitive#1498]
When starting the `git gui` frontend via `:Git gui`(1) the program is run with a `C` locale; that means that all non-ASCII data is broken.
That means file contents in a `diff` are badly displayed, files with such characters in names can't be added or committed.

How about using `LANG=C.utf8` instead, or not changing the locale for that one subcommand at all?

Ad 1: The advantage over using `:!git gui` is that it's using the repository of the currently active buffer.

**Comment by tpope** [comment]
What is `:echo g:fugitive_git_executable`?

**Comment by phmarek** [comment]
`env LANG=C git` in my `init.nvim` because of #228

**Comment by tpope** [comment]
Buddy, that issue is from 8 years ago. Time to move on.

**Comment by phmarek** [comment]
I guess that means I should just remove the workaround in `init.vim`... ack, thanks.
