### ISSUE TITLE
Fugitive cannot extract or detect git repository

### ISSUE THREAD

**Issue by wookayin** [tpope/vim-fugitive#1499]
On a git repository (e.g. `fugitie.vim`), open any file:

```
:Gstatus
fugitive: file does not belong to a Git repository
```

Indeed, it is a git directory, but `FugitiveGitDir` returns nothing. Because of this, all fugitive commands do not work.
```
:echo FugitiveExtractGitDir(expand("%"))
$HOME/.dotfiles/vim/plugged/vim-fugitive/.git

:echo ">>>" . FugitiveGitDir()
>>>
```

Envs:

- neovim 0.4.3, vim 8.1
- macOS 10.14
- git version 2.20.1
- fugitive: master (9a4d730)

**Comment by tpope** [comment]
My first piece of advice is to try with all other plugins disabled and your vimrc stripped down. The Git dir is detected when the buffer is loaded, and another plugin could be interfering with the autocommands that do so.

**Comment by wookayin** [comment]
Thanks @tpope for your reply. Here is a minimal reproduction of the bug (without any interference from other plugin):
```
vim -u NONE autoload/fugitive.vim
:source ~/.vim/plugged/vim-fugitive/autoload/fugitive.vim
:source ~/.vim/plugged/vim-fugitive/plugin/fugitive.vim
:Gstatus
```
Error:
```
fugitive: file does not belong to a Git repository
```

**Comment by tpope** [comment]
You're calling `:source` *after* it the buffer has already loaded. This won't work. Call `:source` first and then `:edit` the file.

**Comment by wookayin** [comment]
Gotcha, it works with the NONE vimrc if we open a buffer after fugitive has been loaded. I can confirm that in this case **the buffer variable `b:git_dir`** is set, and all fugitive commands rely on this variable (which is good to know for me).

This is the autocmd you mentioned, in which `b:git_dir` is set:
```
autocmd BufNewFile,BufReadPost * call FugitiveDetect(expand('<amatch>:p'))
```

And I found that the existence of any other `BufReadPost` autocmds in vimrc make the invocation of the above autocmd (`FugitiveDetect`) not happen. For example:

```
augroup OpenFoldAuto
  autocmd!
  autocmd BufReadPost * exec "if foldclosed('.') != -1 | normal zO | endif"
augroup END
```

Other trivial `BufReadPost` autocmds do not interfere, but some specific autocmds causes the problem (I don't know why). Do you think it is a vim bug or a misuse of mine?

**Comment by tpope** [comment]
You have an unclosed `if` statement. `normal` consumes the entire line, including ` | endif`. Use `exe 'normal zO'`.
