### ISSUE TITLE
Make conflict diff only show conflicts

### ISSUE THREAD

**Issue by jrwrigh** [tpope/vim-fugitive#1501]
When I'm resolving a conflict, I'll often use `:Gdiffsplit!` to get a visual representation of the changes being made. However, the page that shows this is cluttered with changes that _don't_ conflict, they just differ. 

In my example below, the blue box is non-conflicting changes, while the pink box is the start of the actual merge conflict.
![image](https://user-images.githubusercontent.com/20801821/77240478-cd875700-6bab-11ea-8c0f-d9d202752867.png)

I recognize that this is probably the expected outcome of the command I'm using, but if I'm going to use vim as a mergetool (insert obligatory [vimcast reference](http://vimcasts.org/episodes/fugitive-vim-resolving-merge-conflicts-with-vimdiff/)), I'd like it to work well. And the current functionality doesn't _seem_ to match up with the vimcast (though I could just be interpreting it wrong). 

I'm not sure where `vimdiff` ends and `fugitive` begins, so I don't know what exactly could be feasibly done for fixing this exact issue. But even without all the useful +green/-red highlighting, it'd be nice to have the three panel view that's scroll synced and either has a way of jumping between conflicts (similar to `]c`/`[c`) or only shows the conflicts (similar to how `:Gdiff` only shows the parts of the code that differ).

**Comment by tpope** [comment]
This can all be blamed on vimdiff. There's not much Fugitive can do. If you can get past the visuals, you can use `:Git mergetool` to get a list of conflicts in the quickfix list (and optionally use Unimpaired's `]q`/`]q` to jump between them). Personally, I start with `:Git mergetool`, and only invoke `:Gdiffsplit!` if I run into a really hairy conflict that's hard to reason about.

**Comment by jrwrigh** [comment]
Foreword: I already wrote up half of this before you responded and don't want to the work to go to waste. Maybe someone will see this and make it happen. ¯\_(ツ)_/¯

I've created an example setup of a minimal three-panel merge conflict view:

![image](https://user-images.githubusercontent.com/20801821/77240648-c3665800-6bad-11ea-8a97-a5b127d89707.png)

The center contains the standard `diff3` conflict style markers. I've lined up the target and merge files to align with their respective portions of the `diff3` conflict on the working file.

The pink box represents the target, blue is the merge, and green is the incoming changes. If coloring were on the table, it'd be cool to those respective boxes be highlighted in three different colors. 

When you start editing the working copy, the highlighting would probably go away for the middle file (because differentiating between the three sets of files at that point isn't really possible), but the outer files could keep the highlighting to show what the original conflicts were (which I find myself wanting to know fairly regularly).

**Comment by jrwrigh** [comment]
If anyone else finds this, I created a quick function & command. This will A) Remove the diff syntax highlighting while B) still retaining the scroll lock and C) the three panel view.

```vim
function RemoveDiffHighlights()
    :highlight clear DiffAdd
    :highlight clear DiffDelete                                                                                                                                                                                                               
    :highlight clear DiffChange
    :highlight clear DiffText
endfunction

:command! RemoveDiffHi call RemoveDiffHighlights()
``` 

It ain't the prettiest, but it works pretty well.

**Comment by tpope** [comment]
What I do is change the color scheme so the diff highlighting is subtle - extremely dark red/green for example - so that I can see it if I am looking for it but otherwise tune it out.

**Comment by jrwrigh** [comment]
That's actually really smart. Thanks for the tip!

[Relevant code:](https://github.com/tpope/tpope/blob/94b1f7c33ee4049866f0726f96d9a0fb5fdf868f/.vim/after/colors/tpope.vim#L70-L78)

```vim
  hi DiffChange guibg=#5f005f
  hi DiffAdd    guibg=#00005f
  hi DiffRemove guibg=#005f5f
  hi DiffText   guibg=#5f0000
  if &t_Co == 256
    hi DiffChange ctermbg=53
    hi DiffAdd    ctermbg=17
    hi DiffDelete ctermbg=23
    hi DiffText   ctermbg=52
  endif
```

![image](https://user-images.githubusercontent.com/20801821/77241668-1d214f00-6bbb-11ea-8089-645f24e54b22.png)
 *Hex values are slightly off because website really doesn't want to display f values for whatever reason

**Comment by odnoletkov** [comment]
@jrwrigh FYI there is [recent work](https://lore.kernel.org/git/5fe4bec2da21a_19c92085f@natae.notmuch/T/#m768f7f7a5f58741f7fdc3440714c30607e98dfa2) to implement this feature in Git
