### ISSUE TITLE
How to disable the preview window in GFiles and exiting with ESC?

### ISSUE THREAD

**Issue by eyaleizenberg** [tpope/vim-fugitive#1503]
1. Is there a way to disable the preview pane when doing GFiles?
2. Is there a way to close GFiles with ESC?

Thanks.

**Comment by tpope** [comment]
I don’t know what GFiles is but it’s not Fugitive.

**Comment by gotcha** [comment]
@eyaleizenberg GFiles is fzf see https://github.com/junegunn/fzf.vim#commands

**Comment by eyaleizenberg** [comment]
🤦‍♂ my bad, thank you!
