### ISSUE TITLE
Issuing Gpush does not update Gstatus window

### ISSUE THREAD

**Issue by cridemichel** [tpope/vim-fugitive#1504]
Hi,
first of all thank you very much for this great and very useful tool!
I noticed that Gstatus window is regularly updated by Gwrite or Gcommit but issuing Gpush
it is not, is a known bug or is there anything odd in my configuration?

best Cristiano

**Comment by tpope** [comment]
This can happen with older versions of dispatch.vim (including the latest stable version, I believe). Report back if updating doesn't fix it, or if you're not using dispatch.vim at all.

**Comment by cridemichel** [comment]
Dear Tim,
thank you for the prompt reply,
I am using latest releases of macvim and vim-fugitive but
I am not using dispatch.vim,

best 
Cristiano

**Comment by tpope** [comment]
Does it reload when you refocus the status window?

**Comment by cridemichel** [comment]
yes it does

Cristiano De Michele
cristiano.demichele@gmail.com

**Comment by tpope** [comment]
This was not the intended behavior, but I think it's good enough for now. High up on the priority list is rethinking how `:Gpush` works.

**Comment by cridemichel** [comment]
ok thank you for pointing it out

Cristiano De Michele
cristiano.demichele@gmail.com
