### ISSUE TITLE
Unable to find ctag inside .git

### ISSUE THREAD

**Issue by jnumbers** [tpope/vim-fugitive#1505]
I followed your blog regarding using git hooks for ctags. However, now fugitive is unable to find my tag inside .git/tags

I simply get the following error:
E433: No tags file
E426: tag not found: PARSEX

If I move the tag file outside of .git it works perfectly fine.

What am I possibly doing wrong? How can I debug this?

**Comment by tpope** [comment]
The blog post is out of date. Support for `.git/tags` has been removed. I recommend moving the tags file as you have discovered works.
