### ISSUE TITLE
difftool not showing diffs on non-recent commits

### ISSUE THREAD

**Issue by jericdeleon** [tpope/vim-fugitive#1506]
I just got into vim and I'm trying to out difftool, and I noticed some unexplainable behavior when comparing 2 commits that are more than 1 commit apart:

1) When the comparison is simple (one commit length), difftool works as expected:
    - Context: `tpope/vim-fugitive`, `:G difftool ccf5828 9a4d730`
      -  shows 2 files changed, with 2 hunks each. Pressing `Enter` for each quickfix item shows the file, focused on the hunk
      - running `dd` on the shown file shows the correct diff

2) When the comparison is not simple (2 or maybe more commits apart), weird behavior occurs:
    - Context: `tpope/vim-fugitive`, `:G difftool ccf5828 0e35c9b`
      - shows 3 files changed, same as above but 1 additional hunk on `README.markdown`, which came from the more recent commit
      - Pressing `Enter` -> `dd`  for the `README` quickfix (more recent commit) behaves as expected
      - Pressing `Enter` -> `dd` for the other files (non recent commit) show the file, but `dd` output is different:
        - no changes appear, and the whole file is folded
        - if I force my way through by expanding it, I can see the changes but they appear on a split window, and the output is not pretty

I may also just be using the feature wrong.
Am I doing something incorrectly?

**Comment by tpope** [comment]
`:Git difftool` populates the quickfix list and walks away. `dd` is an unrelated feature that diffs against the direct ancestor. See #132 for additional context.
