### ISSUE TITLE
Changes do not reflect for non-existent files, when do `:Git checkout branch`

### ISSUE THREAD

**Issue by hnkz** [tpope/vim-fugitive#1507]
# For example
1. I'm currently on branch `a` and have also branch `b` .
2. branch `a` has file `a.txt` but branch `b` does not have this one.
3. opening `a.txt` and doing command `:Git checkout b`, `a.txt` still opens.

# Desired Behavior
I think `a.txt` should be closed on this situation.

**Comment by tpope** [comment]
What does "closed" mean?

**Comment by hnkz** [comment]
When open only `a.txt` I think vim should ends or show new file. While open other files I think `a.txt` screen should close. My explanation may be vague sometimes because of I'm not fluent in English

**Comment by tpope** [comment]
I think having an open file silently disappear when you run a `:Git` command would be very confusing. One of the following two options would be more appropriate:

* Do the same thing as `:!git checkout b`: leave the file as is and display `E211: File "a.txt" no longer available`. (This is what is currently happening, but the error message is getting lost somehow.)
* Reload the buffer, so it's still there but empty.

I would entertain a pull request that implemented one of these.

**Comment by hnkz** [comment]
Thanks! I'm going to try your options!
