### ISSUE TITLE
"Press ENTER or type command to continue" after commit from Gstatus

### ISSUE THREAD

**Issue by ckoehler** [tpope/vim-fugitive#1510]
Neovim 0.4.3
vim-fugitive master (while testing, it was on 2e67f82b79dac66fb7eea1ed2ca4881a5f265568)
Empty config except for:
```
call plug#begin('~/.config/nvim/plugged')
Plug 'tpope/vim-fugitive'
call plug#end()
```

Based on some posts I've found, I also tried to throw in a:
```
set shortmess=a
```

But every time I commit something that would result in the output to be more than a line or two, I get the "Press ENTER or type command to continue" prompt.
I type `:Gstatus`, then `cc` to commit what is changed. Type the message, hit `ZZ` to save and close, and that message appears (see screenshot).

What am I missing?

<img width="499" alt="Screen Shot 2020-04-07 at 10 22 00" src="https://user-images.githubusercontent.com/64594/78694407-d1102300-78b9-11ea-89b4-81fc526ef4c0.png">

**Comment by tpope** [comment]
Working as intended. Modern versions of Fugitive don't selectively suppress output just to avoid an extra keypress. `:Git commit --quiet` will achieve what you want. I don't think I want to change the `cc` map to enforce that on everyone.

**Comment by ckoehler** [comment]
Fair enough, thanks!

**Comment by nhooyr** [comment]
```viml
  function! s:ftplugin_fugitive() abort
    nnoremap <buffer> <silent> cc :Git commit --quiet<CR>
    nnoremap <buffer> <silent> ca :Git commit --quiet --amend<CR>
    nnoremap <buffer> <silent> ce :Git commit --quiet --amend --no-edit<CR>
  endfunction
  augroup nhooyr_fugitive
    autocmd!
    autocmd FileType fugitive call s:ftplugin_fugitive()
  augroup END
```

For anyone in the future.

**Comment by 3nuc** [comment]
If you use neovim with a lua config see https://github.com/3nuc/dotfiles/blob/16e9ffb5cff2114c3addb25245c521fbcb77bffe/.config/nvim/ftplugin/fugitive.lua

Just create a ftplugin/fugitive.lua file and it'll work

**Comment by tpope** [comment]
@3nuc you mixed up `ca` and `ce`. Also you accidentally used Lua; not sure what that's about.

**Comment by 3nuc** [comment]
@tpope Ah, right - thanks! Fixed and edited my previous comment.

>Also you accidentally used Lua; not sure what that's about.

I just meant to show future readers of this issue how to emulate nhooyr's vimscript solution above, just in lua.
 Neovim contributors have been working on making it possible to configure nvim with lua instead of vimscript (so there's `init.lua` instead of `init.vim`)
See https://github.com/nanotee/nvim-lua-guide
