### ISSUE TITLE
Ggrep opens new tab when target not in current file

### ISSUE THREAD

**Issue by samuelrey** [tpope/vim-fugitive#1512]
As a user, it's confusing to be taken away from my current file when searching for a term. In my experience, the command doesn't open the Quickfix List either. It's unclear whether this is the intended behavior of Ggrep.

![ggrep](https://user-images.githubusercontent.com/9016717/79013837-6dd2fa80-7b1e-11ea-8b1c-ab4a4e654a9b.gif)

**Comment by samuelrey** [comment]
It seems that it will open the new tab & not Quickfix List _even if_ the target string exists in the current file.

Sometimes it will do the advertised "Open QL", but it's not consistent.

**Comment by tpope** [comment]
`:Ggrep` is `:grep` for `git grep`. That's it. It doesn't open the quickfix window, nor does it advertise itself as doing so.
