### ISSUE TITLE
Trying to view root commit from blame opens file instead of commit

### ISSUE THREAD

**Issue by FallenWarrior2k** [tpope/vim-fugitive#1514]
As the title says, if you open `:Git blame` for a file that still has lines from the initial commit, trying to view the initial commit with `p` will open the file as it was at the root commit, instead of the root commit itself.

Of course an extremely rare occurrence, but I just had it happen to me on a new project, so I thought I'd point it out. If that's somehow intended or unfixable, feel free to ignore.

**Comment by FallenWarrior2k** [comment]
Also, many thanks for this awesome extension. Really helps streamline Git workflow in Vim.

**Comment by tpope** [comment]
Intended. Fugitive jumps directly to the file when it hits a boundary commit, "boundary" meaning "stop here regardless of whether we found the true commit or not". And Git treats the root commit as a boundary commit. In other words, Git is saying "this line has been here for as long as the repository has existed, we don't know the true origin", and Fugitive is saying "well if we don't know the origin, then showing the commit is worthless, show the boundary version of the file instead."

You can tell Git blame to not treat the root commit as a boundary with `--root` flag or the `blame.showRoot` config option.

**Comment by FallenWarrior2k** [comment]
Alright, thank you for the explanation, that makes sense. I apologize, I should've investigated some more instead of opening an issue right away.

**Comment by tpope** [comment]
Very fair question, this behavior is undocumented (because it takes so many dang words to explain and I don't want to screw up the flow of the documentation for something 99% of people will never notice).
