### ISSUE TITLE
The index buffer does not refresh automatically: how to refresh it?

### ISSUE THREAD

**Issue by wookayin** [tpope/vim-fugitive#1517]
`:Gdiffsplit` is great because we can directly edit on the index. I am using some plugins ([vim-gitgutter](https://github.com/airblade/vim-gitgutter/)) to add hunks to the index *inside vim*, or often add some patches manually via command line (`git add -p`), and a problem here is that the index buffer does not know these external changes.

Things tried but did not work:

- Search issues with similar keywords
- `fugitive#ReloadStatus()`: this is for status, not for the index buffer.
- Doing `:e` on the index buffer would make the content refreshed. However, I would like to have it done automatically (upon some autocmd events or whatever).

Is there any autocmd events I can use or fugitive vim functions/commands?

**Comment by tpope** [comment]
If you want to reload the staged buffer, you'll need to switch to the window, call `:e`, and switch back. `fugitive#ReloadStatus()` isn't magic; it just does the same thing with the status window.

**Comment by wookayin** [comment]
For gitsigns.nvim and/or neovim users (2023 version), here's a better version than https://github.com/wookayin/dotfiles/commit/5c7ab2347c8e46b3980c0f6a51fe6477ad8675ba:

```lua
local function reload_fugitive_index()
  for _, buf in ipairs(vim.api.nvim_list_bufs()) do
    local bufname = vim.api.nvim_buf_get_name(buf)
    if vim.startswith(bufname, 'fugitive://') and string.find(bufname, '.git//0/') then
      vim.api.nvim_buf_call(buf, function()
        vim.cmd.edit()  -- refresh the buffer
      end)
    end
  end
end
```

Call this function after your hunk actions or the `GitSignsUpdate` autocmd event (see `:help gitsigns-event`). For git-gutter users, `GitGutterStage`.

**Comment by zldrobit** [comment]
Thanks to @wookayin's script, I translated the function into Vimscript:
```viml
function s:reload_fugitive_index()
  for w in getwininfo()
    if bufname(w.bufnr) =~ "^fugitive://.*\.git//0/"
      exec w.winnr . "windo e | wincmd p"
    endif
  endfor
endfunction
```
Note that if the function is used as cmd in `GitGutterStage` autocmd (for git-gutter), the mapping have to be `nested`, i.e.,
```viml
autocmd User GitGutterStage nested call s:reload_fugitive_index()
```
Hence, the `BufReadCmd` and `FileReadCmd` autocmd in `git-fugitive` can be triggered to read the `fugitive://*` index file.

**Comment by tpope** [comment]
Y'all might want to follow [#2207](https://github.com/tpope/vim-fugitive/issues/2207). I'm working on making reload async, which would enable making this automatic refresh the default.

**Comment by benelan** [comment]
Here is another option for `gitsigns.nvim` users:

```lua
vim.api.nvim_create_autocmd({ "User" }, {
  pattern = "GitSignsUpdate",
  group = vim.api.nvim_create_augroup("gitsigns_update_fugitive", {}),
  callback = function(args)
    if vim.g.loaded_fugitive and vim.fn.exists("*FugitiveDidChange") then
      vim.fn["FugitiveDidChange"](args.data and args.data.buf or nil)
    end
  end,
})
```

Reference:

https://github.com/tpope/vim-fugitive/blob/64d6cafb9dcbacce18c26d7daf617ebb96b273f3/plugin/fugitive.vim#L217-L227

**Comment by benelan** [comment]
I personally open the fugitive status buffer in it's own tab via `:tab G`, so I don't need the status updated until I enter the buffer. A more performant solution for this use case is adding the following to `ftplugin/fugitive.vim` instead:
```vim
autocmd BufEnter <buffer> if exists("*FugitiveDidChange") |
            \ call FugitiveDidChange() | endif
```
