### ISSUE TITLE
git-gui--askpass is not a git command

### ISSUE THREAD

**Issue by wizicer** [tpope/vim-fugitive#1518]
After installing version after `V3.2`, I got following error message in windows with GVIM mode only. (works in vim correctly)

![image](https://user-images.githubusercontent.com/2389606/79677265-102b6600-8222-11ea-87ae-afb9a3d6b10a.png)

I found code maybe relative to https://github.com/tpope/vim-fugitive/blob/master/autoload/fugitive.vim#L4721

```vim
function! s:AskPassArgs(dir) abort
  if (len($DISPLAY) || len($TERM_PROGRAM) || has('gui_running')) && fugitive#GitVersion(1, 8) &&
        \ empty($GIT_ASKPASS) && empty($SSH_ASKPASS) && empty(FugitiveConfigGetAll('core.askpass', a:dir))
    if s:executable(s:ExecPath() . '/git-gui--askpass')
      return ['-c', 'core.askPass=' . s:ExecPath() . '/git-gui--askpass']
    elseif s:executable('ssh-askpass')
      return ['-c', 'core.askPass=ssh-askpass']
    endif
  endif
  return []
endfunction
```

I temporarily add following code to my vimrc to `fix` it now:

```vim
let $GIT_ASKPASS = 'no'
```

**Comment by tpope** [comment]
Do you normally have to enter a password? Does your workaround enable you to enter it?

**Comment by wizicer** [comment]
Thanks for your quick reply, I'm using ssh mode for my repos, so no password is needed during sync.
I presume this workaround would remove password process.

I presume this issue is caused by one space was not escaped in my path to git binary: 
```
C:\Program Files\Git\mingw64\libexec\git-core\
```

I tried change following line: (with double quotes)
```vim
      return ['-c', 'core.askPass="' . s:ExecPath() . '/git-gui--askpass"']
```
However, without lucky, it did not work. I'm not familiar with vim scripting system enough to resolve this issue.

**Comment by tpope** [comment]
Ohhhh yeah something is going wrong with shell escaping. Does `:Git commit -m "Test message"` work, or do you get an error about the file `message` not existing?

**Comment by tpope** [comment]
Also try `:Git --no-pager push` and/or `:Git --no-pager fetch`.

**Comment by wizicer** [comment]
Both `:Git commit -m "Test message"` and `:Git --no-pager fetch` fail with same message.
BTW, `:Git -p fetch` works as expected.

I just starting to doubt it may related to `job`.

**Comment by tpope** [comment]
Same message as the original issue? What version of Vim?

**Comment by tpope** [comment]
Oh, and I overlooked that you're on 3.2. Can you try the `:Git --no-pager fetch` on master as well?

**Comment by wizicer** [comment]
Sorry for late response due to busy days.
VIM version is `8.0 2016 Sep 12`
All above commands executed in latest master.
Why I mentioned 3.2 is because at that version, everything was working right.

**Comment by tpope** [comment]
What is `:set shell? shellcmdflag?`.

Can you upgrade to Vim 8.2?

**Comment by wizicer** [comment]
response of `:set shell? shellcmdflag?` is
```
shell=C:\Windows\system32\cmd.exe
shellcmdflag=/c
```

my trouble upgrading to Vim 8.2 is I got error when executing `:PlugInstall` like following:
```
    fatal: could not create leading directories of '"C:\Users\xxx\AppData\Local\.vim\plugged\vim-fugitive"': Invalid argument
```
With quick search, I didn't find a way to workaround it, so I stopped at vim 8.0.

**Comment by tpope** [comment]
Okay, that's got some serious quoting issues too. Sounds like one of the following is true:

1. You've got something seriously weird in your Vim config that's just wrecking havoc on all sorts of shell escaping things. You should try with a stripped down config.
2. Vim 8.2 has different shell escaping semantics from Vim 8.0. Fugitive supports Vim 8.2 while `:PlugInstall` supports 8.0. You should report that issue to the vim-plug maintainer.

My money is on 1, but either way, I don't think there's anything to be done on my side.

**Comment by wizicer** [comment]
Thanks for your important advice, I'll try to strip my config down to find out the issue.
Thanks again for your quick response and expert advice. :+1:
