### ISSUE TITLE
Add global variable to control whether :Gcommit opens in a tab or not

### ISSUE THREAD

**Issue by thisisrandy** [tpope/vim-fugitive#1519]
There's apparently been some back and forth about this over the years in e.g. #513 and #1011. b680699 left open in tab behavior for `Gcommit -v` in, but at some other point that I can't immediately track down, `Gcommit -v` reverted to opening in a split.

I don't enjoy typing the extra four keystrokes to prefix it with `tab `, so it would be great to see one of two things happen:
1. If the change to make `Gcommit -v` open in a split was a regression, which seems possible since I'm having trouble finding a relevant commit, then please add the open in tab behavior back in.
2. Otherwise, add open in tab support back in the form of a global variable. Ideally, I would think this variable could apply to both verbose and normal commits, so something like `g:fugitive_commit_opens_tab = 0` means use splits, `1` means tab for verbose only, and `2` means all the time.  

(after a bit more digging) Okay, I actually just happened upon d0dceb9, which seems to have soft deprecated Gcommit. There's not an issue attached, but I think I understand why this was done, i.e. for naming scheme consistency. So I guess this is more properly a request for a behavior change to `Git commit -v` to match the old `Gcommit -v` behavior. And let's be honest: I'm still going to use `Gcommit` (`Gco<tab>` is shorter than `G com<tab>`), so it would be helpful if their behavior didn't diverge in any way.

**Comment by tpope** [comment]
I'd recommend defining your own `:Gcommit` command that calls `:tab Git commit`, or something like that. Fugitive won't override it with its own `:Gcommit`.

```vim
command! -bang -nargs=* Gcommit tab Git<bang> commit <args>
```

Or if you're really into saving keystrokes, consider a map to `:tab Git commit -v<CR>`.

Making one option flag of one subcommand force a `:tab` that can't be overridden isn't something I'm willing to add an option for. `:Git` is intended to be consistent and predictable.

**Comment by thisisrandy** [comment]
Okay, that's fair. Thanks for the suggestion.

**Comment by idbrii** [comment]
For future readers, here's a more complete `:Gcommit` based on [the current definition](https://github.com/idbrii/vim-fugitive/blob/71b485dd2f2ca78610da7b695ea300f27b405684/plugin/fugitive.vim#L432-L434) but modified to go through `:Git` since that's the public API.

It adds completion and whatever it is that `<range>` does.

    command! -bang -nargs=* -range=-1 -complete=customlist,fugitive#CommitComplete Gcommit tab <range>Git<bang> commit <args>

And I'll add an alternative to opening a tab: make the commit window use maximal screen height. Great when committing from a vertical split so you can still see the other window.

    command! -bar -bang -nargs=* -range=-1 -complete=customlist,fugitive#CommitComplete Gcommit <range>Git<bang> commit <args>|wincmd _

**Comment by tpope** [comment]
That's gonna burn you when you use `:Git commit -m`! Proper fix would be to check if the buffer number changes. "Good enough" fix would be to check if the file type is `gitcommit`.

**Comment by idbrii** [comment]
You're right. Using -m produces `error: switch `m' requires a value`.

I fixed it by copying how fugitive defines the command and adding a wrapper around fugitive#Command:

    function! s:GitCommit(line1, line2, range, bang, mods, args) abort
        let bufnr = bufnr()
        exec fugitive#Command(a:line1, a:line2, a:range, a:bang, a:mods, a:args)
        if bufnr != bufnr()
            wincmd _
        endif
    endf

    command! -bang -nargs=? -range=-1 -complete=customlist,fugitive#CommitComplete Gcommit call s:GitCommit(<line1>, <count>, +"<range>", <bang>0, "<mods>", "commit " .. <q-args>)

Thanks!

**Comment by tpope** [comment]
That'll work. `fugitive#Command()` isn't official but is very unlikely to change.
