### ISSUE TITLE
"file does not belong to a Git repository" when run in a neovim :terminal buffer

### ISSUE THREAD

**Issue by apaleslimghost** [tpope/vim-fugitive#1520]
presumably because the `bufname` is something like `term://.//1234/path/to/shell`. ideally (for me) it would find the repo from the pwd of the terminal, but since that's not available from the `bufname` i don't know how it'd get that

**Comment by tpope** [comment]
`getcwd()` should do the trick, no? Shouldn't be that hard to wire this up to `TermOpen` on nvim and `TerminalOpen` on vim.

**Comment by apaleslimghost** [comment]
`getcwd` doesn't seem to reflect the CWD of the terminal though (at least in Neovim). that's what i'd expect given the usual behaviour of looking at the location of the active buffer, not vim's `pwd`

**Comment by tpope** [comment]
If you expect to be able to start a shell with `:terminal`, call `:cd` inside the shell, and then have `:Git` on the outside know about it, then no, it won't know about the new working directory. I think that's fine. Lots of tools behave that way.

**Comment by apaleslimghost** [comment]
okay, using `getcwd` is fine in that case

**Comment by QiBaobin** [comment]
@tpope , thanks for the great project.  I just want to open the Git status window from terminal buffers, do you think it makes sense to make below change? Thanks!

```
M plugin/fugitive.vim
@@ -18,7 +18,7 @@ function! FugitiveGitDir(...) abort
       return g:fugitive_event
     endif
     let dir = get(b:, 'git_dir', '')
-    if empty(dir) && (empty(bufname('')) || &buftype =~# '^\%(nofile\|acwrite\|quickfix\|prompt\)$')
+    if empty(dir) && (empty(bufname('')) || &buftype =~# '^\%(nofile\|acwrite\|quickfix\|prompt\|terminal\)$')
       return FugitiveExtractGitDir(getcwd())
     elseif (!exists('b:git_dir') || b:git_dir =~# s:bad_git_dir) && empty(&buftype)
       let b:git_dir = FugitiveExtractGitDir(expand('%:p'))
```

**Comment by tpope** [comment]
I guess it will do. It doesn't cover cases like `:e term:///etc//bash` or `:call term_start('bash', {'cwd': '/etc'})`. The former could be covered by parsing it out of the `term://` URL (making sure to account for relative vs absolute, platform differences, etc.). The latter, I don't think is accessible to us. Dynamic `getcwd()` it is.
