### ISSUE TITLE
{range}Glog behaves in a strange way

### ISSUE THREAD

**Issue by cideM** [tpope/vim-fugitive#1521]
I created a [dummy repository](https://github.com/cideM/foo). If I run `git log -L 25,26:bar` I get

```
$ git log -L 25,26:bar
commit f3fc05258ce0acc6b52d8d904a01f66c61cab67f
Author: Florian B <yuuki@protonmail.com>
Date:   Tue Apr 21 15:09:03 2020 +0200

    commit

diff --git a/bar b/bar
--- a/bar
+++ b/bar
@@ -6,0 +27,2 @@
+w okdaaopwdk
+awd
 foo $
```

I would expect to see more or less the same if I visually select these two lines and then run `Glog`, which gives me a prompt that looks like so

```
:'<,'>Glog
tree e60697eeb8acdf828ed18317f3111054847c303a
parent ff920412ea50dfa7e2c8f79178ad0d67e35abb8d
author Florian B <yuuki@protonmail.com> Tue Apr 21 15:09:03 2020 +0200
committer Florian B <yuuki@protonmail.com> Tue Apr 21 15:09:03 2020 +0200

commit


diff --git a/bar b/bar
index 66ca549..f8b282b 100644
--- a/bar
+++ b/bar
@@ -1,5 +1,48 @@
 hi
 
-hello
+hello dajwiodjawoid
 
 lol
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+dkawp okda
+w okdaaopwdk
+awd
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+dakwpodka
+wdok
```

It gives me way too much info.

Strangely, the quickfix list also looks weird:
```
f///h/t/f/.g//f3fc05258ce0acc6b52d8d904a01f66c61cab67f|| commit
f///h/t/f/.g//f/bar|27| commit
```
The second entry `commit` is the same commit as the first but the second one looks like
```
hi

hello dajwiodjawoid

lol




















dkawp okda
w okdaaopwdk
awd


















dakwpodka
wdok
```

It's the file without the commit info.

Am I using the range version of `Glog` wrong?

**Comment by tpope** [comment]
Short answer: if you want "more or less the same" as `git log`, use `:Git log`. There is a bug here but I don't think the fix will be satisfying.

P.S. Providing a test repo to demonstrate is great, but the goal should be to clearly illuminate the problem, not shroud it in 50 lines of garbage keyboard mashing with a commit history containing duplicate messages.

**Comment by cideM** [comment]
Hm yes my example was pretty crappy, apologies for that.
