### ISSUE TITLE
How do I abort "Git commit --amend"

### ISSUE THREAD

**Issue by tjaartvdwalt** [tpope/vim-fugitive#1522]
I stage some files, and amend them to my previous commit

```
Git commit --amend
```

the commit message pops up, and I decide that I changed my mind, so I try to exit without saving the commit by typing `:q!`

I expect the commit to be cancelled, and my repo to be returned to the state before I started the commit, but instead it apears that the commit completed successfully.

Is there something I am missing here?

**Comment by tpope** [comment]
Delete the contents of the buffer and then `:wq`. This is the same as with calling `git commit --amend` from the command line.

**Comment by ivangreene** [comment]
Clearing the buffer and write+quit works. However, I'm more in the habit of using `:cq`, which does abort with `git commit --amend`, but not with fugitive's `Git commit --amend`. Any thoughts on handling exit with error code?

**Comment by tpope** [comment]
`:cq` exits Vim entirely. Doesn't really fit with the workflow of opening a commit message in a split.
