### ISSUE TITLE
How to set wrap in fugitive#Diffsplit ? 

### ISSUE THREAD

**Issue by huangyingw** [tpope/vim-fugitive#1523]
during the diff split view, it would be much comfortable, if fugitive#Diffsplit could automatically wrap the long line. 
to achieve this, I have been trying adding lots of `windo set wrap` or `set wrap` in fugitive#Diffsplit, but this doesn't help...

However, if I add `syntax off` in the beginning of fugitive#Diffsplit, it works.
So, I have to seek help here, how to set wrap in fugitive#Diffsplit ?

**Comment by tpope** [comment]
`'`wrap'` does not play well with `'scrollbind'`. `:diffsplit` turns it off automatically, so `:Gdiffsplit` does as well. I will not be making `:Gdiffsplit` configurable in ways `:diffsplit` is not, so you're on your own for this one.

**Comment by qazip** [comment]
I am also interested in this. This is specially annoying for text files (for example, markdown), in which you type wrong lines.

If someone manages to "hack it", please let me know how!

**Comment by tpope** [comment]
You might look into `autocmd OptionSet diff`.

**Comment by gerardbm** [comment]
My maps to achieve this:

```vimscript
nnoremap <Leader>gh :Gsdiff<CR>:windo set wrap<CR>
nnoremap <Leader>gv :Gvdiff<CR>:windo set wrap<CR>
```

My default settting is `set wrap`, so the idea was to recover the setting after using `Gsdiff` and `Gvdiff`.

**Comment by gerazov** [comment]
+1 for this - it's also necessary for merging Latex files :+1:

**Comment by gerardbm** [comment]
> +1 for this - it's also necessary for merging Latex files 
> 
> @gerardbm - how do you prevent this from messing up `coc-explorer`?

I'm not using coc-explorer at the moment. I sometimes use CtrlP and NERDTree from Vim; or vifm and FZF from the shell.

It would be good if you provided a screenshot with the issue. How does it mess up?

**Comment by gerazov** [comment]
Sure. This is how it looks like with no wrapping:

![vim_3way_diff](https://user-images.githubusercontent.com/15214418/115837895-60329f00-a419-11eb-8ae3-c9aa234d5acd.png)

And this is how it looks when I execute: `:windo set wrap`

![vim_3way_diff_wrap](https://user-images.githubusercontent.com/15214418/115837916-658fe980-a419-11eb-97e8-b8f5ae38230c.png)

It's necessary for the Markdown but the file explorer is really messed up, and this persists if I toggle it, or even kill its window and restart it. If I toggle it before enabling wrap then it doesn't get affected.

**Comment by chenlijun99** [comment]
The diffopt `followwrap` was introduced with patch-8.2.2490 to achieve this.

**Comment by MarcelRobitaille** [comment]
I am using:

```vim
autocmd OptionSet * set wrap
```

Naive, but I always want wrap on.

**Comment by barsv** [comment]
> The diffopt `followwrap` was introduced with patch-8.2.2490 to achieve this.

i didn't understand it at first. now i do. it's possible to enable it with `:set diffopt+=followwrap`
