### ISSUE TITLE
Going back to Normal mode from Insert mode inside commit window closes status window ?

### ISSUE THREAD

**Issue by Melandel** [tpope/vim-fugitive#1524]
Hello,

I noticed the following scenario on my gvim 8.2:
* `:G`
* `cc`
* `iblablabla<Esc>`
* the status window is now closed

Also, this scenario works too:
* `:G`
* `cc`
* `<Esc>`
* the status window is still open

How can I keep the status window open from before to after making a git commit?

**Comment by tpope** [comment]
That's not Fugitive, that's some other badly behaved plugin or something in your vimrc.

**Comment by Melandel** [comment]
Thanks!
