### ISSUE TITLE
Show output of successful Gpush

### ISSUE THREAD

**Issue by borisbrodski** [tpope/vim-fugitive#1525]
Please, provide a way to see the output of successfully executed commands, like `Gpush`.

My use case: Wenn pushing to a Gerrit Review server, the server replys with some useful information, like in the example below:

```
$ git push origin HEAD:refs/for/master
Enumerating objects: 39, done.
Counting objects: 100% (39/39), done.
Delta compression using up to 4 threads
Compressing objects: 100% (12/12), done.
Writing objects: 100% (20/20), 1.43 KiB | 146.00 KiB/s, done.
Total 20 (delta 10), reused 0 (delta 0)
remote: Resolving deltas: 100% (10/10)
remote: Processing changes: refs: 1, updated: 1, done
remote:
remote: SUCCESS
remote:
remote:   http://gerrit-server/c/MyProject/+/5765 Fixing some tests
remote:
To http://gerrit-server/a/MyProject
 * [new branch]            HEAD -> refs/for/master
```

**Comment by tpope** [comment]
`:copen`

**Comment by borisbrodski** [comment]
Ok, this was really an easy one.

But considering, that with many year of vim experience and digging into fugitive documentation I wasn't able to find this simple command, I would suggest to add this little advice to documentation.
Idealy to each command, that fills `copen` buffer, but at least to some common section. `Gpush` section was the first one where I tried to find the answer to my problem.

Current fugitive documentation doesn't mention `copen` at all.

I could contribute, if you provide me with some simple guidelines.

**Comment by tpope** [comment]
`:copen` is mentioned under `:help quickfix` and near `:help :cwindow`, both of which are mentioned in the help for `:Git_push`. Balancing helpfulness vs bloat in the documentation is a delicate art, but this one will hopefully be moot soon, as I plan to remove the default quickfix behavior (but only after I finish implementing optional, opt-in quickfix behavior).

**Comment by languitar** [comment]
Just one more aspect why seeing the output is helpful: Services such as Github and Gitlab output a link to directly create a merge request after pushing to a new branch. Somehow automatically revealing this link would be pretty nice.

**Comment by tpope** [comment]
After 10 months of failing to implement optional, opt-in quickfix behavior, I have gone ahead and removed the old quickfix behavior anyways. `:Git push` now behaves like most other commands.

**Comment by onionka** [comment]
@languitar you could use this:

```
nmap <leader>gp :Gpush<cr>:copen<cr>
```

**Comment by languitar** [comment]
This should be outdated with modern version of fugitive. I get the output directly now without quickfix.

**Comment by anton-fomin** [comment]
In case someone else is looking here instead of the docs. There is a `-p` flag to `Git` command.
So can be done with `Git -p push`

https://github.com/tpope/vim-fugitive/blob/master/doc/fugitive.txt#L30
