### ISSUE TITLE
Glog Fails When Used From "Outside of Git Repository"

### ISSUE THREAD

**Issue by levouh** [tpope/vim-fugitive#1527]
**Fugitive Version**: Latest
**Vim Version**: 8.2.579
**OS**: Linux

**Steps to Reproduce**:

Given a directory structure like:

```
/
└── git_repo
     ├── .git
     ├── baz
     └── bar

└── foo
```

I can do:

```
$ vim /foo
```

note that `/foo` is _not_ inside of a Git repository, and within Vim:

```
:Glog -- /git_repo/bar
```

which then splits out the error message:

> fugitive: file does not not belong to a Git repository

However, if I do:

```
:e /git_repo/baz
```

followed by:

```
:Glog -- /git_repo/bar
```

or

```
:Glog /git_repo/bar
```

everything works just fine. So it seems that the problem is that the value of `b:git_dir` is being evaluated based on `%`, rather for the target file.

Let me know if any more information is needed, or if I am simply doing something wrong.

**Comment by tpope** [comment]
If `:Glog` always took one and only one argument this might make sense. But `:Glog -- /git_repo1/bar /git_repo2/baz` has no sensible interpretation. Also it does not generalize well to other commands, as not all commands take filename arguments.
