### ISSUE TITLE
How do I view difference between unstaged version and nth version of the file?

### ISSUE THREAD

**Issue by rationalthinker1** [tpope/vim-fugitive#1528]
Please note that I am not talking about 2 or 3 commits ago but a file nth revision ago?

I tried `Gvdiff ~2`, `Gvdiff !~2`, `Gvdiff HEAD~2`, but none of them seem to work.

**Comment by tpope** [comment]
The `~` notation is commits. Git offers no primitive for previous revisions of a file. Use `:Git log %` or `:Glog %`, select the commit you want, and navigate to the file.

**Comment by justinmk** [comment]
I have a nasty but super useful mapping for this:

https://github.com/justinmk/config/blob/644f44cd2a11bad70b84cc0d6d0fb94da417fb3f/.config/nvim/init.vim#L540

Hit `5Ud` to compare the current buffer to the version 5 commits ago. Unfortunately "5 commits ago" is relative to the entire repo, although in practice it seems easier to reason about...

**Comment by rationalthinker1** [comment]
I wrote this small function that seems to work
```
function! PreviewRevision(n)
	let l:commit = system('git log ' .  expand('%') . ' | grep "commit" | cut -d" " -f2 | sed -n ' . a:n . 'p')
	execute "normal! :Gvdiffsplit " . l:commit . " <bar> :NERDTreeClose"
endfunction
```
and then run the command `:call PreviewRevision(1)`
