### ISSUE TITLE
Gblame Immediately Re-Opens Window

### ISSUE THREAD

**Issue by jls83** [tpope/vim-fugitive#1530]
I'm running into an issue where invoking `:Gblame` while inside a blame buffer is closing then immediately re-opening the buffer. I'm using NeoVim v0.4.3, but I confirmed the same behavior on Vim v8.0.1365. See this asciinema video for a demonstration: https://asciinema.org/a/327353

I found issue #511 while searching for the problem. Though it's obviously unrelated, I'm including the outputs of the `echo` commands referenced in that issuehere:
* `echo b:fugitive_blamed_bufnr` returns `E121: Undefined variable: b:fugitive_blamed_bufnr`
* `echo b:fugitive_blamed_arguments` returns `E121: Undefined variable: b:fugitive_blamed_arguments`
* `echo w:fugitive_leave` returns `call setwinvar(bufwinnr(1),"&scrollbind",0)|call setwinvar(bufwinnr(1),"&cursorbind",0)|call setwinvar(bufwinnr(1),"&wrap",1)|call setwinvar(bufwinnr(1),"&foldenable",1)`

Let me know if you need anything else!

**Comment by tpope** [comment]
#1474
