### ISSUE TITLE
:0Glog not commit correct commits

### ISSUE THREAD

**Issue by kernelheap** [tpope/vim-fugitive#1532]
:0Glog correctly populates the quick fix list with the commits of the current buffer. It also correct shows the previous revisions of the file correctly as the quickfix list is traversed with :cnext and :cprev. 

However, pressing enter on an item in a quickfix list opens a buffer with wrong commit information. To debug this, I made a fresh test user, just downloaded the fugitive plugin. No other plugins or vim configuration was used. 

Git Version : 2.17.1
vim version: 8.0 on Mac.

**Comment by tpope** [comment]
Cannot reproduce, and this doesn't really make sense as pressing enter does exactly the same thing as `:cnext`/`:cprevious`. What is "wrong commit information"?

**Comment by kernelheap** [comment]
I know what's wrong. It didn't make sense because fugitive is incorrectly mapping `<CR>` after executing `:0Glog`. Thats why pressing `<CR>` after executing `:0Glog` resulted in some random commit (sometimes a random file) getting opened in a new fugitive buffer.

Here is the `<CR>` mapping set by fugitive after executing `:0Glog` : 

<img width="628" alt="Screen Shot 2020-05-09 at 3 58 17 PM" src="https://user-images.githubusercontent.com/935165/81486982-fde38d00-920d-11ea-81d0-d21f56c467b1.png">

**Comment by tpope** [comment]
Well that explains the discrepancy, at least. That map should not exist in the quickfix buffer.

* What does `:verbose set filetype?` report in the quickfix window?
* If you delete [this line](https://github.com/tpope/vim-fugitive/blob/caf3b1d5696e8d39a905e48f1e89d8c0c565168c/plugin/fugitive.vim#L367), does the problem go away?

**Comment by kernelheap** [comment]
- filetype is `qf` in the quickfix window
- Deleting the line doesn't change anything as expected. 

Pressing `<CR>` in qf window is working as expected (like you said). Pressing `<CR>` in the file buffer opens the blame commit.

I guess, everything is working as intended. It's just that intuitively, I was expecting the current commit to show up (similar to `:Glog`) and not the blame commit. But the blame commit is pretty useful too since it changes with the line in the file buffer. All good. Thanks!

**Comment by tpope** [comment]
`C` is mapped to jump to the current commit.

**Comment by kernelheap** [comment]
Yup. that works. Don't have to run `:Glog -- %` anymore. Very handy. Thanks a lot.
