### ISSUE TITLE
Gdiff et al could create nomodifiable buffers

### ISSUE THREAD

**Issue by craigemery** [tpope/vim-fugitive#1534]
If I forget to bang the command I start editing the diff buffer & that's very annoying.
Is there a flag for making the diff buffer not modifiable?
If not, could there be?

**Comment by tpope** [comment]
Use case number one of calling `:Gdiffsplit` with no arguments is editing that diff buffer to selectively stages changes. Fugitive does not offer a configuration option to disable this tent pole feature, but you can use something like `autocmd BufReadPost fugitive://*//0/* setlocal readonly` to achieve whatever behavior you desire for those particular buffers.
