### ISSUE TITLE
Call :GStatus on a remote netrw file

### ISSUE THREAD

**Issue by jmriego** [tpope/vim-fugitive#1535]
I'm trying to edit a remote repository using netrw but when I can't get it to work.

It always says `fugitive: file does not belong to a Git repository`. I have tried both opening directly with a `scp://...`, opening netrw and changing the directory to the one with the repo and no luck.

The variable `b:netrw_curdir` seems to be defined with the right path. Is there some specific instructions I should do? Or is this not supposed to be the way to edit remote files?

Thanks in advance!

**Comment by tpope** [comment]
This is not supported. It wouldn't be *impossible* to get it to work, but it would take a lot of work, and it would probably be too slow to be usable, as `:Gstatus` runs several Git commands every time the buffer loads.

**Comment by jmriego** [comment]
That's fine, I understand how difficult it must be to do that.

Sorry to annoy you about this, but I can see some other tickets related to netrw like #409 and I'm trying to figure out what the best way of working remotely is.

Do you mind letting me know what that ticket #409 was about or anything in the docs I can check?

**Comment by tpope** [comment]
That's related to local directories, not ssh.
