### ISSUE TITLE
Gdiff not working

### ISSUE THREAD

**Issue by pianocomposer321** [tpope/vim-fugitive#1536]
To reproduce:

1. `git init` in terminal
2. `nvim`
3. Add

```
def main():
    pass

if __name__ == '__main__':
    main()
```
to main.py.

4. `:Gwrite`
5. `:Gcommit` with message `initial commit`
6. `:Git checkout -b feature`
7. change
```
def main():
    pass
```
to
```
def main():
    print("Hello, fugitive!")
```
8. `:Gwrite`
9. `:Gcommit` with message `add print to main function`
10. `:Gdiff master`

Expected behavior:
fugitive-vim opens the master's version of the main.py file in diffsplit with the feature version.

Actual behavior:
Absolutely nothing.

Am I doing something wrong?

**Comment by tpope** [comment]
This probably isn't the problem, but verify that using `:Gdiffsplit` instead doesn't change anything. Also try with a `master:%` argument, and with no argument at all.

**Comment by pianocomposer321** [comment]
I tried all of those already. The same result - that is, nothing.

**Comment by pianocomposer321** [comment]
idk if it's relevent, but I'm using neovim on ubuntu 20,04 on wsl 1 with the sleep command disabled b/c of libg6 dependency issues. See https://www.how2shout.com/how-to/how-to-upgrade-ubuntu-18-04-lts-to-20-04-lts-on-wsl-windows-10.html (the section at the bottom that says "Error- sleep: cannot read realtime clock: Invalid argument").

**Comment by pianocomposer321** [comment]
I figured out what the problem is. It's this line in my init.vim:

`au FileType python cd %:h`

I deleted it for now b/c it's not totally necessary, but if you fix it so it doesn't cause problems that would be great!

**Comment by pianocomposer321** [comment]
I'll close the issue now b/c I got the problem solved.

**Comment by pianocomposer321** [comment]
One thing that might solve the problem with the autocmd: Is there a way to disable all autocmds for the current buffer? So the diff window (the RO one) wouldn't have any user-defined autocommands execute for it.

**Comment by tpope** [comment]
The solution to a broken autocommand is not to throw the baby out with the bathwater. There is no guarantee `%:h` is a valid directory, even without Fugitive in the mix.

**Comment by pianocomposer321** [comment]
> There is no guarantee `%:h` is a valid directory, even without Fugitive in the mix.

`%:h` is expanded to the head, or parent directory of the current file. So unless the file is at the root directory (a place where I would never put a file, and I don't know anybody who would), it will always be valid.

> The solution to a broken autocommand is not to throw the baby out with the bathwater.

I was trying to think of something that would solve the problem and that was just the first thing that came to mind. The other idea I had was to have a separate filetype for the diffsplit, but that would most likely mess up syntax highlighting etc, so I thought just disableing user defined autocmds might do the trick. I understand if that seems a little much.

**Comment by tpope** [comment]
It could be a `http://` URL. It could be a file inside a zip file or tar archive. It could be `/dir/file` where `/dir` doesn't exist. It could be nothing at all. Try `:setfiletype python` in an unnamed buffer and see what happens.

You are not being nearly imaginative enough in your failure cases. Fugitive is just one of many. This is on you to guard against.

**Comment by pianocomposer321** [comment]
> Fugitive is just one of many. This is on you to guard against.

Fugitive may be just one of many, but it happens to be the only case in which I've run into an issue. Anyway, that line was mostly for back when I was using GUI vim so it would set the right cwd after opening from the right-click menu. Now that I'm using terminal vim inside wsl, I normally start vim from the root directory of my project, so that line isn't really necessary. But I'm still interested if you know of any way that I could work around the issue. I realize that having the plugin disable autocmds is definitely overboard because many users probably have autocmds that they rely on and would still apply to the vimdiff file. But if you know of a way to temporarily (or just restricted to the current buffer) disable autocmds, could you let me know?

**Comment by tpope** [comment]
Adding an `if isdirectory(expand('%:h'))` guard to your autocommand should be good enough.

**Comment by pianocomposer321** [comment]
Just to clarify: the above will work for the fugitive diff buffer as well as the above cases (editing from https:// URL, inside tar archive, etc.), right?

**Comment by tpope** [comment]
Yes.

**Comment by pianocomposer321** [comment]
Thanks, @tpope, works like a charm!

Awesome plugin btw, I recently added git to my workflow, and it's benefits are innumerable. I would never have been able to make the transition without this plugin!
