### ISSUE TITLE
这里的中文乱码如何解决？

### ISSUE THREAD

**Issue by StephenWu5** [tpope/vim-fugitive#1538]
![image](https://user-images.githubusercontent.com/32475322/82720782-5ffdc100-9ce9-11ea-9a34-6c739721c473.png)

**Comment by StephenWu5** [comment]
![image](https://user-images.githubusercontent.com/32475322/82720795-7ad03580-9ce9-11ea-8a85-c17058bad453.png)

**Comment by tpope** [comment]
Can you provide a link to an example repository that demonstrates the problem?

**Comment by StephenWu5** [comment]
已解决
