### ISSUE TITLE
'file does not belong to a Git repository", but it does!

### ISSUE THREAD

**Issue by mgedmin** [tpope/vim-fugitive#1539]
I've a git repository that is unfortunately not public.  When I open `docker/nginx.conf` in vim and try to `:Gblame`, I get this error

    fugitive: file does not belong to a Git repository

`:!git blame docker/nginx.conf` works fine.  `:Gblame` works fine for other files in the same directory.  `docker/nginx.conf` is a regular file and not a symlink.  `./.git` is a regular directory and not a file/symlink. `./docker` is a regular directory and not a symlink.  I can reproduce this with the latest git master of vim-fugitive.

I'd be happy to provide more information, if you tell me what information could be useful.  I'm utterly baffled.

**Comment by mgedmin** [comment]
I've tried `:debug Gblame`, and (wow is the vim debugger bad!  worse than pdb!) I can see that b:git_dir is not being set for this buffer for some reason.

If I manually `:call FugitiveDetect(expand("%:p"))`, then b:git_dir gets set (correctly).

Hmm, if I :10verbose e docker/nginx.cfg, I see a bunch of BufRead/BufEnter/BufWinEnter autocommands being executed, but no BufReadPost.

This looks like a problem with my vim configuration/plugins, and not vim-fugitive's fault.

**Comment by mgedmin** [comment]
The annoying thing is that when I do `:10verb e docker/nginx.cfg`, I can see

```
Executing BufRead Autocommands for "*"
autocommand call FugitiveDetect(expand('<amatch>:p'))
```

but then I can also see my ~/.vim/ftdetect/nginx.conf do

```
Executing BufRead Autocommands for "nginx.conf"
autocommand set filetype=nginx
```

and yet at the end of the process b:git_dir is unset, and `:verb set ft?` claims ft is blank and was never ever set.  How is that even possible?

**Comment by mgedmin** [comment]
Let the record show that it was a brown-paper-bag-worthy bug in my ~/.vim/ftdetect/apache.vim:

```vim
" autodetect from content?
au BufRead,BufNewFile *.conf,*.conf.j2
      \ if join(getline(1, 10), "") =~ "<VirtualHost" |
      \    setf ft=apache                   " <------ | is missing on this line!!!
      \ endif
```

**Comment by tpope** [comment]
Oh yeah the way Vim handles (or fails to handle) a missing `endif` in an autocommand is infuriating.
