### ISSUE TITLE
Unable to backspace in authentication prompt

### ISSUE THREAD

**Issue by GideonWolfe** [tpope/vim-fugitive#1541]
If I attempt to log in and accidentally mistype, I get

![fugitive](https://user-images.githubusercontent.com/32942052/83070749-c43dbf00-a020-11ea-8bdb-4e2ae40e2813.png)

**Comment by tpope** [comment]
I don't think this is fixable. Please use one of the multiple methods Git provides to avoid typing your password every single time.

**Comment by GideonWolfe** [comment]
Switched to SSH so not an issue anymore. Thanks for the great plugin.
