### ISSUE TITLE
unknown switch 'b' error

### ISSUE THREAD

**Issue by AvinashDesai** [tpope/vim-fugitive#1542]
I am running into issue while doing :G

Error detected while processing BufReadCmd Autocommands for "index{,.lock}":  
fugitive: error: unknown switch `b'^@usage: git status [options] [--] <filepattern>...^@^@    -v, --verbose         be verbose^@    -s, --short           show status concisely

**Comment by AvinashDesai** [comment]
git version 2.12.0

**Comment by tpope** [comment]
Can you verify that's what is reported by `:Git --version`? Guessing you have a `$PATH` issue.

**Comment by AvinashDesai** [comment]
looks like git is lower than 1.8.5 as per fugitive
Here is the error I get for :Git --version
Error detected while processing function fugitive#Command[123]..<SNR>127_UserCommandList:
line   20:
E605: Exception not caught: fugitive: Git 1.8.5 or higher required to change directory
Error detected while processing function fugitive#Command:
line  123:
E171: Missing :endif

**Comment by AvinashDesai** [comment]
when I do :!git --version I see it is 
git version 1.7.0.7

**Comment by tpope** [comment]
Check `:echo $PATH`, and `echo $PATH` in your shell. These will probably differ, figure out why.

**Comment by AvinashDesai** [comment]
Thanks for the help @tpope Found the issue in my setup.

**Comment by AkashicSeer** [comment]
I am getting this error when I try to use
git init -b main 
Anyone know why or how to fix this I am using git 2.25

**Comment by robin-a-meade** [comment]
@AkashicSeer  "git [2.24](https://git-scm.com/docs/git-init/2.24.3) doesn't have option `-b/--initial-branch`. It was added in [git 2.28](https://git-scm.com/docs/git-init/2.28.0). You need to upgrade to use the option." — https://stackoverflow.com/a/64787736

**Comment by karmadice** [comment]
I have git 2.43.2, but I am still getting **error: unknown switch `b'**
