### ISSUE TITLE
Dot map in commits

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1544]
When editing commits <kbd>.</kbd> currently fills command line with

    :<cursor> <pwd>

It would be great if instead it filled it with something more useful like

    :<cursor> <commit>

or even

    :Git <cursor> <commit>

**Comment by tpope** [comment]
The help text you tried to change under #1550 is correct. The file under the cursor is the priority. It should be using the filename from the diff your on. And it will automatically if I ever manage to convert it to a Fugitive file type.

And like in the status buffer, it can fall back to a commit in a few specific contexts where there is no relevant filename.
