### ISSUE TITLE
OptionSet diff is not invoked on closing the diff window

### ISSUE THREAD

**Issue by lakshayg** [tpope/vim-fugitive#1545]
Thanks for creating and maintaining this plugin!

I am using this plugin along with `vim-signify` on `NVIM v0.4.3`. I want to disable the markers displayed by vim-signify in the SignColumn when I call `Gdiffsplit`. To achieve this I added this to my `init.vim`

```
augroup Vimrc
  autocmd!
  autocmd OptionSet diff if &diff | setlocal signcolumn=no | else | setlocal signcolumn=auto | endif
augroup END
```

After this autocmd, when I do `Gdiffsplit`, it successfully hides the sign column but when I close the diff window, signcolumn is not restored even though &diff is now set to 0.

After some googling, I came across https://www.reddit.com/r/vim/comments/axzhlb/using_optionset_to_toggle_ale_onoff_not_working/ which seems to indicate that this might be a fugitive issue.

Here's a minimal init.vim to help reproduce the issue
```
call plug#begin()
Plug 'tpope/vim-fugitive'
call plug#end()

syntax enable
filetype plugin indent on

augroup Vimrc
  autocmd!
  autocmd OptionSet diff echom "OptionSet diff" v:option_new v:option_old
augroup END
```

Calling Gdiffsplit will print the following message but closing the diff window will not add any new messages. Instead of using Gdiffsplit, if I just do `set diff` and `set nodiff`, the command is called both the times as expected
```
OptionSet diff 1 0
OptionSet diff 1 0
```

**Comment by tpope** [comment]
Does `:diffoff` trigger it?

**Comment by lakshayg** [comment]
Yes, it does

**Comment by lakshayg** [comment]
Thank you so much for fixing it
