### ISSUE TITLE
FugitiveHead() - statusline

### ISSUE THREAD

**Issue by cherrry9** [tpope/vim-fugitive#1546]
I'm trying to get a fancy-looking vim status line with separators around each module.
If I'm inside a git repository it will display:
![prev](http://0x0.st/ifC4.png)
If Im outside a git repo it will display:
![prev](http://0x0.st/ifCt.png)
My attempt to implement this (this is minimal vimrc to reproduce my problem):
```vim
call plug#begin('~/.config/nvim/bundle')

Plug 'tpope/vim-fugitive'

call plug#end()

set statusline=▒
set statusline+=%t

let branch = FugitiveHead()
if !empty(branch)
	set statusline+=░▒▓
	set statusline+=▓▒░
	set statusline+=%{FugitiveHead()}
	set statusline+=░▒▓█
else
	set statusline+=░▒▓█
endif
```
error:
```
Error detected while processing /home/jan/.config/nvim/colors/statusline.vim:
line  134:
E117: Unknown function: FugitiveHead
E15: Invalid expression: FugitiveHead()
line  135:
E121: Undefined variable: branch
E116: Invalid arguments for function empty
E15: Invalid expression: !empty(branch)
line  134:
E117: Unknown function: FugitiveHead
E15: Invalid expression: FugitiveHead()
line  135:
E121: Undefined variable: branch
E116: Invalid arguments for function empty
E15: Invalid expression: !empty(branch)
```
(Function 'FugitiveHead()` works in vim prompt but if I put it in my configuration, it will cause the error.)
How can i fix it?
neovim version: NVIM v0.4.3
fugitive version: 27a5c3abd211c2784513dab4db082fa414ad0967

**Comment by tpope** [comment]
`FugitiveHead()` is only available after the plugin is loaded. You can't call it directly from your vimrc. You should should write a function that returns a string with *everything* you want in the statusline, and then `:set statusline+=%{MyFunction()}`.
