### ISSUE TITLE
Ggrep search in the old path when copy one project to another path.

### ISSUE THREAD

**Issue by swordligit** [tpope/vim-fugitive#1547]
I have a git project in path A, and copy the whole project to path B.
When I Ggrep in the path B, the results are still searched in path A.

Is this a bug, or I have to reset some environment variable?

**Comment by tpope** [comment]
This is probably an issue with `core.worktree` in your `.git/config`.

**Comment by swordligit** [comment]
You are right, the git project A was created by 
`git worktree add ...`
Then I randomly copy the A to B.
But, there is no `core.worktree` variable in the A, followings are
some related config:
```
git config -l

color.ui=auto
cola.spellcheck=false
merge.tool=meld
diff.tool=meld
diff.submodule=log
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=ssh://192.168.1.3/my-soft
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
gui.wmstate=normal
gui.geometry=943x467+85+47 206 212
merge.tool=bc
diff.tool=meld
diff.renamelimit=5154
```
There is no `core.worktree`.
But anyway, this should be the root cause.
