### ISSUE TITLE
fugitiveblame autocmd failing (empty commit buffer & potentially ignored mapping)

### ISSUE THREAD

**Issue by PiCT0** [tpope/vim-fugitive#1548]
I have tried to debug this myself but I can't find where the issue is (and my lack of knowledge in Vim plug-in implementation didn't help). To give some context, I was trying to create a more dynamic experience of `:Git_blame` where the commit responsible for the current line would automatically pop-up in the preview window. To do so, I thought I'd be able to leverage `p` by having the following `~/.vim/after/ftplugin/fugitiveblame.vim`:
```
autocmd CursorMoved <buffer> normal p
```
However, while the preview window does appear with the right pseudo-file name ("`fugitive:///path/to/repo/.git//<SHA>`"), the buffer itself is empty. From that point, any attempt to use `p` manually will also bring me to the properly-named empty buffer.

Furthermore, because I planned to have the "real-time" commit preview, I wanted to make the blame window narrower so added the another `autocmd` to `~/.vim/after/ftplugin/fugitiveblame.vim`:
```
autocmd BufEnter <buffer> normal C
```
which also fails but at least gives an error message:
```
Error detected while processing BufEnter Auto commands for "<buffer=2>":
E21: Cannot make changes, 'modifiable' is off
```
This makes me think that there might be a race condition between this `autocmd` running and the mappings from `s:BlameFileType()` being registered and that `C` might be trying to _delete from the cursor position to the end of the line_, hence the output. This however wouldn't explain the issue with the first `autocmd`.

Is this an issue with fugitive or am I doing something wrong? Thanks

---

I'm using 27a5c3abd2 with
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 18 2020 18:29:15)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK2 GUI.
```

**Comment by tpope** [comment]
`:help autocmd-nested` for the first issue.  Your diagnosis for the second issue is probably correct. You're welcome to try reordering things and sending a PR, but my recommended solution would be to copy the implementation of the `C` mapping and just use that directly, as it's unlikely to change.
