### ISSUE TITLE
symlinked files are not working

### ISSUE THREAD

**Issue by astropanic** [tpope/vim-fugitive#1549]
I manage my dotfiles with [stow](https://www.gnu.org/software/stow/) like [here](https://www.theguild.nl/how-to-manage-dotfiles-with-gnu-stow/) described.

My ~/.dotfiles are managed via Git.

`ls -la ~/.config` produces `nvim -> ../.dotfiles/neovim/.config/nvim`

If I edit my vim config with:

`nvim ~/.config/nvim/init.vim` and issue a `:Gblame` I'm getting

~~~
fatal: no such path `neovim/.config/nvim/init.vim` in HEAD
~~~

Is there a way I can use this plugin from within a symlinked file?

**Comment by tpope** [comment]
Not supported, as Git doesn't support it either: `git blame ~/.config/nvim/init.vim` does not work.
