### ISSUE TITLE
Glog extremely slow with large repository

### ISSUE THREAD

**Issue by dianlujitao** [tpope/vim-fugitive#1551]
When working with large git repos, say https://github.com/torvalds/linux which contains nearly 1 million commits, `:Glog` could be extremely slow. I have read the suggestions from https://github.com/tpope/vim-fugitive/issues/1380 and https://github.com/tpope/vim-fugitive/issues/1475 . `:Git log` reads **full** history into a normal buffer instead of quickfix list, but it doesn't accelerate that much compared with the native command-line `git log`. Is it possible to replicate that performance?

**Comment by tpope** [comment]
If you want to improve the performance of `:Glog` you're going to have to send a patch to Vim. I dove into the source a while back and found code that did a string comparison of the filename of each new quickfix entry to every other buffer name, one by one. So performance is `O(n^2)` with respect to the number of buffers, in other words, very bad. I didn't think to make a note of where that code was so I can't offer further help.
