### ISSUE TITLE
Git Status stage window showing rgd values instead of commit message

### ISSUE THREAD

**Issue by gozes** [tpope/vim-fugitive#1553]
<img width="1708" alt="Screenshot 2020-06-17 at 10 33 31" src="https://user-images.githubusercontent.com/632922/84882317-f45c0900-b086-11ea-8cc2-02b57515b48b.png">
Not what else I can add besides that I update fugitive yesterday afternoon  and this starting happing today

OS: MacOS
Default Shell: Fish
your can see all my config in https://github.com/gozes/dotfiles

**Comment by tpope** [comment]
* Try with bash: `env SHELL=/bin/bash vim`
* Try with a stripped down `.gitconfig`.

Report back with your results.
