### ISSUE TITLE
Gibberish when calling Git from VimEnter

### ISSUE THREAD

**Issue by Moshem123** [tpope/vim-fugitive#1554]
I'm trying to load both NERDtree and fugitive on vim startup using this:
```
function! MosheTest()
    NERDTreeToggle
    if filereadable(expand(".git/index"))
        rightbelow Git
    endif
endfunction
autocmd VimEnter * if !argc() | call MosheTest() | endif
```
However, the `Git` window opens with weird characters:
![image](https://user-images.githubusercontent.com/17252601/85076808-9552dd00-b1c9-11ea-9035-fc4feac5e278.png)
If I comment out `rightbelow Git`, open git and manually run `:Git`, the window buffer is displayed the way it should.
How can I fix that?
BTW, is there a different, official way of opening fugitive with NERDTree on startup?
Thanks

**Comment by Moshem123** [comment]
Fixed it by adding a timer of 500 ms before executing the function:
```
function! MosheTest(timer)
    NERDTreeToggle
    if filereadable(expand(".git/index"))
        rightbelow Gstatus
        wincmd l
    endif
endfunction
autocmd VimEnter * if !argc() | let timer = timer_start(500, 'MosheTest') | endif
```

**Comment by tpope** [comment]
`:help autocmd-nested`

**Comment by Moshem123** [comment]
> `:help autocmd-nested`
Can you elaborate? Where do I nest autocmd?
I read the help page, as I understand, nesting is when I perform an autocmd that triggers itself? I know it might be off-topic but I'd love an explanation here.
Thanks :)

**Comment by tpope** [comment]
You mark your `VimEnter` nested so it will call Fugitive's autocommands recursively.
