### ISSUE TITLE
Checking out specific version immediately after `Git tag` and `Gclog`

### ISSUE THREAD

**Issue by adah1972** [tpope/vim-fugitive#1556]
I did a few experiments. And I have found:

- `coo` does not work in the quickfix window opened by `:Gclog`: it causes "E21: Cannot make changes…".
- `coo` does not work in the window opened by `:Git tag`: I see the command `:Git checkout --` flashing at the screen bottom, but it does not check out the tagged version that the cursor is on.

After playing for a while, I found out that `coo` *does* work in the window opened by `<CR>` in the quickfix window by `:Gclog`. I found it out only accidentally, after I started writing on this issue.

May I ask for a feature enhancement that `coo` (or similar) can work immediately after `:Gclog` and `:Git tag`? Or did I miss anything?

**Comment by tpope** [comment]
We don't own the quickfix window. It would be bad form for us to define maps in it. I recommend using `:Git log` instead. Using the quickfix list was a mistake.

I do want to support `coo` with `:Git tag`, along with similar commands like `:Git branch`. Supporting this would require making the "commit under cursor" behavior aware of what command was run. Not a high priority but I'll get to it eventually.

**Comment by adah1972** [comment]
I did not expect the behaviour difference between `:Git log` and `:Glog`/`:Gclog`... Anyway, problem is solved.

You may want to emphasize the usage in the documentation. Reading the documentation again, I cannot find any trace about `:Git log`. Since `:Gclog` and `:Gllog` are described in the documentation, people may fail to notice that the generic `:Git` command can be a better option in some circumstances, though I am not sure whether it is a small percentage or not.

Feel free to close this issue, or keep it as a reminder.

**Comment by tpope** [comment]
The `:Git tag` request remains valid, but as it affects me personally I don't really need the issue tracker to remind me.
