### ISSUE TITLE
Support setting default remote

### ISSUE THREAD

**Issue by jarifibrahim** [tpope/vim-fugitive#1557]
Running `Gbrowse` on a detached head state **without remote "origin"** fails with 
```
fugitive: No Gbrowse handler installed for '.'
```

It would be very useful if there was a way to set the default remote. I have `origin` which points to my fork of the project and `upstream` which is the main repo. I usually push on `upstream` and very rarely use `origin`. 

`vim-fugitive` assumes `origin` is the default remote (which is a fair assumption) but in my case, it is not the case.

I propose adding a `default_remote=origin` config option so that I can change this to `default_remote=upstream`

The Gbrowse command seems to be failing for me because the following code returns empty remote since I don't have a `origin` remote on my repository
https://github.com/tpope/vim-fugitive/blob/27a5c3abd211c2784513dab4db082fa414ad0967/autoload/fugitive.vim#L589

**Comment by tpope** [comment]
Run `git fetch -v` with a detached head. What remote does it fetch from?

**Comment by jarifibrahim** [comment]
> Run `git fetch -v` with a detached head. What remote does it fetch from?

It doesn't do anything. No error, no output.

**Comment by tpope** [comment]
The point I was trying to make, before losing track of this issue, is that `git fetch` also defaults to `origin` with no way to change it. Fugitive isn't assuming the default remote, it's using Git's official definition of the default remote. I see no reason for Fugitive to be more flexible than Git in this regard.
