### ISSUE TITLE
Support for vertical diff splits

### ISSUE THREAD

**Issue by nmokkenstorm** [tpope/vim-fugitive#1558]
Hey,

First of all thanks for the work on this amazing plugin, it has been an essential part of my workflow for a while now.

:Gdiff and :Gdiffsplit currently open two buffers in a horizonal alignment, but I'd love to have an option to have them vertically aligned, much alike the difference in behaviour between :vsplit en :split. If this is already possible I couldn't find this as an available option within the Readme.md.

I'm by no means an expert on vim and/or vimscript. I'd be willing to look into sending in a PR if that's something that'd be appreciated, but as the contribution guidelines mention something about not being shy about asking first I figured I'd do that first.

For what it's worth, I'm using vim 8.0.1453 on both Mac and Ubuntu under WSL.

**Comment by nmokkenstorm** [comment]
Nevermind, after a bit of digging I found [this](https://github.com/tpope/vim-fugitive/issues/510). For any future readers, the magic trick is `:set diffopt+=vertical`

**Comment by tpope** [comment]
See also `:Gvdiffsplit`.

**Comment by Reminance** [comment]
> See also `:Gvdiffsplit`.

nice, solve my problem too, thanks for the contribution!
