### ISSUE TITLE
tmux + vim-fugitive + vim-dispatch: should the tmux pane be closed on successful git push?

### ISSUE THREAD

**Issue by rionda** [tpope/vim-fugitive#1561]
Hi,

I'm not sure whether I'm expecting the wrong behavior or what. I have fugitive and dispatch installed. When I do a `:Gpush`, I was expecting the tmux pane that gets open to close automatically if there are no errors, but that does not seem to be the case. Should it be closing? And if it supposed to close and doesn't, how can I debug why it is not closing?

Thanks.

**Comment by tpope** [comment]
The tmux pane (not the quickfix window) should close automatically on success _or_ failure. My best guess is that some option in your `.tmux.conf` is altering the behavior. Try stripping down `.tmux.conf` and report back with your results.

**Comment by rionda** [comment]
@tpope: Thanks. Actually it seems that the issue is in the following code in my `.vimrc`, which I had with the goal of starting a server automatically if one was not started already:

```vim
if empty(v:servername) && exists('*remote_startserver')
    call remote_startserver('VIM')
endif
```

I'm just wondering whether fugitive/dispatch should be "resilient" to something like the above code.

**Comment by tpope** [comment]
It should be resilient against that. We do [use the server if available](https://github.com/tpope/vim-dispatch/blob/1206e1474fc613caeb1ba56d36b71d7f9f7760ac/autoload/dispatch.vim#L250-L254), so that's probably what's hanging. Any ideas why that might be?

**Comment by rionda** [comment]
The value returned by the code you linked to is 
`/Applications/MacPorts/MacVim.app/Contents/MacOS/Vim --servername VIM --remote-expr "DispatchComplete(2)`, which seems to make sense, and if I run it it seems to hang, but I have no clue how to debug it further from either the server or the client, so any hint is appreciated. Thanks.

**Comment by tpope** [comment]
Sounds like the remote server is broken. Which raises the question of why are you starting it when it doesn't work? Does some subset of functionality work?

**Comment by rionda** [comment]
I was using for TeX-PDF back synchronization using skim (a PDF viewer) and [vimtex](https://github.com/lervag/vimtex) (it allows to click on a word in the PDF and have the Vim cursor moved to the corresponding word in a LaTeX file), and for this feature to work, the server must be running. But I just checked and it does not work anymore, so indeed the remote server may be broken. I wonder whether it is a MacVim issue. I'm going to try with (non-Mac)Vim.

**Comment by tpope** [comment]
Last I heard the remote server was explicitly unsupported on MacVim without the GUI running, but this may be out of date.

**Comment by rionda** [comment]
Then I bet that's the issue (I'll check later). I understand that it is not a fugitive/dispatch problem then. Thank you for the help
