### ISSUE TITLE
Open or close all inline diffs in :G

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1563]
The best way I found to do that in the current version is to `<` or `>` on both 'Staged' and 'Unstaged' section headers. This is tedious even if you use `gu` and `gs` maps.

Is there a better way to open/close all inline diffs?

If no, can I propose making `<` and `>` anywhere else (outside of sections) to do that?

**Comment by nhooyr** [comment]
I think an option to have all inline diffs open by default would be nice too. Then u can just use vim's folding to open/close diffs.

**Comment by nhooyr** [comment]
I think https://github.com/jreybert/vimagit may be a better fit for this anyway.

See also https://github.com/tpope/vim-fugitive/issues/569

**Comment by nhooyr** [comment]
Tried it out but got weird errors when reopening vimagit sometimes about the magit window being incorrect or unmodifiable.

Writing some viml to automate this for vim-fugitive.

**Comment by nhooyr** [comment]
```viml
  augroup nhooyr_fugitive
    autocmd!
    autocmd FileType fugitive normal guk>gUk>gsk>gg0zM
  augroup END
```

Will also need to use my branch from https://github.com/tpope/vim-fugitive/pull/1565 until it's merged.

**Comment by nhooyr** [comment]
```viml
  augroup nhooyr_fugitive
    autocmd!
    autocmd FileType fugitive normal guk>gg
    autocmd FileType fugitive normal gUk>gg
    autocmd FileType fugitive normal gsk>gg
  augroup END
```
For some reason with them all in the same `:normal`, it doesn't expand diffs if you only have a single stage section and no unstaged/untracked. Separating them out makes things work as expected.

🤷

**Comment by tpope** [comment]
"Anywhere else" is bad, but adding that behavior on the `Head:` line aka line 1 sounds reasonable. I'll implement it.

I'm also tempted to add maps like `z<` to collapse all diffs in the current section. When I want to collapse everything that's usually the core of what I'm after: I'm done with the section and want to collapse it all. But I'm not sure that justifies 3 more maps that don't really have a great mnemonic.

**Comment by odnoletkov** [comment]
Cool, `<` on the `Head:` would work for me. The main use case is staging multiple files with large hunks – I often get lost after performing several actions while not seeing section headers. Folding everything down helps by showing high-level perspective.

What do you think about `<` on already closed file closes all other files in the section? That way `<<` anywhere in the section will always fold it up.

**Comment by tpope** [comment]
> What do you think about `<` on already closed file closes all other files in the section? That way `<<` anywhere in the section will always fold it up.

My gut reaction is this is like 3% too clever, but I might warm up to it some day.

**Comment by tpope** [comment]
I think the following would be a reasonable interface, actually:

* `1<`: collapse the current file
* `2<`: collapse all files in the section
* `<`: first one, then the other, as was initially proposed

This gives us a natural, intuitive interface, plus idempotent variants for those that need them.

Currently `2<` is interpreted as "collapse 2 lines worth of diffs", which is basically worthless, as inline diffs are like 8 lines at a minimum. `2>` isn't quite this worthless but is still extremely niche, I'm fine to reclaim it. And changing the existing `=` makes no sense, but we could still add `1=` and `2=`.

**Comment by odnoletkov** [comment]
I like that!

Agree `<<<` is bad because if you are in a single expanded file in a section `<<` will unexpectedly become `<<<` and collapse everything.

**Comment by Hubro** [comment]
My use case is that I usually leave the Fugitive status window open in a different tab. Often when I switch focus to my Fugitive tab, I already have a few inline diffs opened, some staged, some unstaged. I basically want to quickly reset my view back to that of a freshly opened Fugitive status window, i.e. close all inline diffs.

Currently, the quickest way to do this is to close the status window and re-open it.

Typing `:e` doesn't affect the inline diffs. Would it be intuitive to add `:e!` to also remove all inline diffs?

**Comment by tpope** [comment]
> Typing `:e` doesn't affect the inline diffs. Would it be intuitive to add `:e!` to also remove all inline diffs?

I'm not sure, but it's trivial to implement, so I guess we can try it.

On a related note, my plans to retool commit buffers to use the `fugitive` file type recently hit a wall when I discovered that diffs against merge ancestors routinely contain thousands of files on large and active projects. The most obvious route forward is to allow collapsing not just all files in a section but the section itself. So add that as another challenge to the design here.
