### ISSUE TITLE
Support for Rebase --interactive against from merge-base

### ISSUE THREAD

**Issue by brianfiszman** [tpope/vim-fugitive#1564]
This is a very useful command I often use to rewrite the feature branch history whenever is needed.

The command is the following where the **fork-point** from of the **feature-branch** would be **develop**:
`git rebase -i $(git merge-base $(git branch --show-current) <fork-point>)`

The shortcut for this command could be **rI**

**Comment by odnoletkov** [comment]
Since Git 2.24 there is a special option to achieve this: `git rebase -i --keep-base`

**Comment by brianfiszman** [comment]
Oh, great! Thanks for telling me! :-D

Is there a shortcut for that in fugitive? If there isn't I would gladly add it if you don't mind of course.

**Comment by tpope** [comment]
The current rebase map pattern `r<some-letter>` isn't really amenable to covering every conceivable option combination, but I will keep this in mind for future designs. In the meantime, creating your own map that calls `:Git rebase -i --keep-base` is a simple exercise I will leave to reader.

**Comment by brianfiszman** [comment]
> The current rebase map pattern of `r<some-letter>` isn't really amenable to covering every conceivable option combination, but I will keep this in mind for future designs. In the meantime, creating your own map that calls `:Git rebase -i --keep-base` is a simple exercise I will leave to reader.
Yeah @tpope thanks, I did that with fzf. 
Like this...
```
nnoremap <Leader>ri :call fzf#run({
      \ 'source': 'git branch',
      \ 'sink': function('<sid>read_branch_into_rebase')
      \})<CR>


function! s:read_branch_into_rebase(branch)
  execute 'Grebase -i --keep-base'.a:branch
endfunction

```

Anyway, hope to see that feature some day ;-) Cheers!
