### ISSUE TITLE
Fugitive doesn't allow to partially stage unversioned files

### ISSUE THREAD

**Issue by x-yuri** [tpope/vim-fugitive#1567]
I intend-to-add a file with `I`, then visually select a line, press `s`, but the whole file is added. As I can see `fugitive` doesn't event [try][1] to partially apply it. And you can't unstage lines from such (staged) file. Are you planning to correct this?

I see a workaround. After adding the whole file, one can press Enter on one of its non-"-" lines (if my memory serves me right), which will open the index version of the file. You edit it as you see fit, save, and the changes you wanted are staged. Do you have a better suggestion?

On a side note, I believe Fugitive lacks some kind of tutorial/introduction. Like with `vim`, you've got a user, and a reference manuals. `doc/fugitive.txt` sounds like a reference manual. Or the Introduction section should be expanded.  I've just learned from the source code that `:0Git` doesn't do a split :) Only to find that it's documented :)

[1]: https://github.com/tpope/vim-fugitive/blob/master/autoload/fugitive.vim#L3734

**Comment by tpope** [comment]
> I intend-to-add a file with `I`, then visually select a line, press `s`, but the whole file is added. As I can see `fugitive` doesn't event [try](https://github.com/tpope/vim-fugitive/blob/master/autoload/fugitive.vim#L3734) to partially apply it. And you can't unstage lines from such (staged) file. Are you planning to correct this?

It's not supported because Git, to the best of my knowledge, does not provide a straightforward way to do so. Any patch fed to `git apply` referencing a file added with `git add -N` will fail. One possible solution would be to take the full selection, strip off the leading `+` characters, feed that to `git hash-object -w`, and hand the resulting hash to `git update-index`.
 
> I see a workaround. After adding the whole file, one can press Enter on one of its non-"-" lines (if my memory serves me right), which will open the index version of the file. You edit it as you see fit, save, and the changes you wanted are staged. Do you have a better suggestion?

Not really.

> On a side note, I believe Fugitive lacks some kind of tutorial/introduction. Like with `vim`, you've got a user, and a reference manuals. `doc/fugitive.txt` sounds like a reference manual. Or the Introduction section should be expanded. I've just learned from the source code that `:0Git` doesn't do a split :) Only to find that it's documented :)

I've been leaning on the Vimcasts to fill that niche, but they're pretty dated at this point. I don't really have the bandwidth to do much else.

**Comment by x-yuri** [comment]
> It's not supported because Git, to the best of my knowledge, does not provide a straightforward way to do so.

I just tried, and it [does][1], but it might be [version-specific][2].

[1]: https://gist.github.com/x-yuri/7e3d3c1cb243ceedf1fc7eb93b7e0d23
[2]: https://github.com/magit/magit/issues/4026
