### ISSUE TITLE
Is there a way to make the status window reusable by Gclog?

### ISSUE THREAD

**Issue by x-yuri** [tpope/vim-fugitive#1568]
`:0Git | Gclog` creates 2 more windows (for the list and for commits). I'm struggling to make it reuse the window with `git` status for commits. Is there a way? I tried setting `modifiable swapfile buftype= noreadonly` before `Gclog`, but to no effect.

**Comment by odnoletkov** [comment]
Try `:Gedit : | Gclog`

**Comment by x-yuri** [comment]
Where's the catch, if you please? After all, the point is not so in making `Gclog` take over the tab after `:0Git`, as in just making `:Gclog` take over the tab. And this makes me wonder about the difference between `:0Git` and `:Gedit :`...

**Comment by tpope** [comment]
`:Git` flags the current window as a status window. Other Fugitive commands respect that flag and preserve it as a status window, choosing another window to reuse or creating a new one if no other window exists. `:Gedit :` creates a regular Vim window with no special behavior. Use whichever suits you.

**Comment by x-yuri** [comment]
Do you think this is okay?

```viml
nnoremap <Leader>fl <Cmd>unlet! w:fugitive_status <Bar> Gclog<CR>
```
