### ISSUE TITLE
Key binding in :Gblame window stopped to work moving from pathogen to build in addon method of vim

### ISSUE THREAD

**Issue by mowgli** [tpope/vim-fugitive#1569]
Since some recent updates, the bindings in :Gblame window stop working.

I do often use that and using <cr> to jump to the displayed patch. But since some time (days/weeks) it stopped to work.

**Comment by mowgli** [comment]
Strange, it need to be some trouble with vim as I cannot find a working commit in the past.

The last vim update was from 8.2.0510 to 8.2.0716.

**Comment by mowgli** [comment]
I found the error but I don't know how to solve it. It is how fugitive is installed.

Until recent I installed vim-fugitive using pathogen inside of `~/.vim/bundle`. Recently I changed that to use the built in method of vim installing it to `~/.vim/pack/fugitive/start/vim-fugitive`.

So it seems that when using the build in addon method of vim would prevent fugitive to effectively be used.

**Comment by tpope** [comment]
What is `:set filetype?` inside of the blame window?

**Comment by mowgli** [comment]
`filetype=fugitiveblame`

As it should be if I see that correct.

**Comment by tpope** [comment]
That is correct. Report back with the output of each of the following:

```vim
verbose nmap o
verbose nmap A
verbose set foldmethod? modifiable?
```

**Comment by mowgli** [comment]
Deployed to `~/.vim/bundle/fugitive/start/vim-fugitive`:
```
n  o           &@:<C-U>exe <SNR>165_BlameCommit("split")<CR>
        Zuletzt gesetzt in ~/.vim/bundle/fugitive/start/vim-fugitive/autoload/fugitive.vim Zeile 189

n  A           &@:<C-U>exe 'vertical resize '.(<SNR>165_linechars('.\{-\}\ze [0-9:/+-][0-9:/+ -]* \d\+)')+1+v:count)<CR>
        Zuletzt gesetzt in ~/.vim/bundle/fugitive/start/vim-fugitive/autoload/fugitive.vim Zeile 189

  foldmethod=manual
        Zuletzt gesetzt in ~/.vim/bundle/fugitive/start/vim-fugitive/autoload/fugitive.vim Zeile 5618
  modifiable
        Zuletzt gesetzt in ~/.vimrc Zeile 339
```

Deployed to `~/.vim/pack/fugitive/start/vim-fugitive`:
```
Kein Mapping gefunden

n  A           &@:<C-U>exe 'vertical resize '.(<SNR>165_linechars('.\{-\}\ze [0-9:/+-][0-9:/+ -]* \d\+)')+1+v:count)<CR>
        Zuletzt gesetzt in ~/.vim/pack/fugitive/start/vim-fugitive/autoload/fugitive.vim Zeile 189
        
  foldmethod=manual
        Zuletzt gesetzt in ~/.vim/pack/fugitive/start/vim-fugitive/autoload/fugitive.vim Zeile 5618
  modifiable
        Zuletzt gesetzt in ~/.vimrc Zeile 339
```

Hope, that helps

**Comment by tpope** [comment]
What is `~/.vimrc Zeile 339`?

**Comment by mowgli** [comment]
```
autocmd BufRead,BufWinEnter * let &l:modifiable = (&readonly ? 0 : 1)
```

**Comment by tpope** [comment]
There's your problem. Fugitive doesn't define the maps in modifiable buffers because they override commands used for modification. The reason it's not happening in Pathogen is likely some subtle difference in load order.

**Comment by mowgli** [comment]
Could you elaborate the problem a bit more please, @tpope?

Usually I want to stay with the readonly/modifiable solution as I found my think fingers often to write to readonly buffers with a hassle to get that beast closed afterwards. So the current solution is a very good solution for it.

On the other hand, it is absolutely not clear, why it should have that side effect to fugitive and why it happens to some but not all mappings. (I tried to get it from the code but was unable to see it.)

And last, is there a way to solve that? Ok, staying with the current solution is ok for me, keeping pathogen in place. But in the end, there should be no different, using native method than pathogen.

**Comment by tpope** [comment]
Long story short this will work:

```
autocmd BufRead * if &readonly | set nomodifiable | endif
```

Turning *off* `'modifiable'` is fine. It's only turning *on* `'modifiable'` that's the problem.
