### ISSUE TITLE
[Question] Checkout a branch?

### ISSUE THREAD

**Issue by itainoam** [tpope/vim-fugitive#1572]
What's the easiest way to checkout branch?

`:Git checkout [tab]` is not very helpful when there are many branches (it's not even sorted by most recent)

It would have been nice to `:Git branch` and then `coo` to checkout the branch.

Thank you!

**Comment by ccchapman** [comment]
@itainoam This may be of use: https://github.com/stsewd/fzf-checkout.vim

**Comment by itainoam** [comment]
Thanks @ccchapman! 
I'm looking to stay within the confines of fugitive. I assume there's an idiomatic way, just like checking a commit, but I didn't figure it out.

How do you people checkout a branch with fugitive?

**Comment by Avishayy** [comment]
Well, it isn't within fugitive, but I can recommend [Twiggy](https://github.com/sodapopcan/vim-twiggy)

**Comment by tpope** [comment]
`coo` on `:Git branch` is on the todo list.
