### ISSUE TITLE
Glog removes first newline character

### ISSUE THREAD

**Issue by eduardoarandah** [tpope/vim-fugitive#1573]
First newline character is removed from `:Glog` command

Check screenshot (follow numbers)

```
version: vim 8.2 and nvim 0.4.3
Ubuntu 18
version: commit 1da7c133b109cd329060174a104e325e4d6bcc82
```

![image](https://user-images.githubusercontent.com/4065733/88856468-2bf7be00-d1ba-11ea-8efc-c271119fde39.png)

**Comment by tpope** [comment]
Try `git log --oneline`. Git itself is doesn't like the format of your messages. This is not a Fugitive problem.
