### ISSUE TITLE
fugitive doesn't handle :cq properly

### ISSUE THREAD

**Issue by JasonMFry** [tpope/vim-fugitive#1574]
If I'm _not_ in fugitive making a commit, but want to cancel that commit, `:cq` cancels the commit. If I'm in fugitive making a commit and do the same, it cancels the commit but completely closes vim, closing all tabs, buffers, etc. Any chance the behavior can change to merely cancel the commit and close the buffer without killing vim?

One may argue that outside of fugitive `:cq` cancels the commit and quits vim, but I've always assumed it quits vim b/c there is only one buffer open so quitting that buffer quits vim. But if I'm in a complex setup (multiple tabs, windows, buffers, etc), if `:cq` in fugitive inside of that complex setup quits vim, it's rather surprising.

**Comment by tpope** [comment]
`:cq` quits Vim. This is not a configurable or overridable behavior. Fugitive has no power over it.
