### ISSUE TITLE
Feature request: move to previous window after "gq" command in various fugitive buffers

### ISSUE THREAD

**Issue by lifecrisis** [tpope/vim-fugitive#1575]
Greetings:

Try this out...

1. `vim`
2. `:vsp`
3. `:wincmd l`
4. `:Git`
5. `gq`

You will notice that you are moved to the window on the left instead of to the previous window on the right.

Could `gq` be modified to move us to the previous window if it is open?

Thanks,
lifecrisis

**Comment by tpope** [comment]
#1399
