### ISSUE TITLE
Please provide an alias :Gmv for :Gmove

### ISSUE THREAD

**Issue by joshtriplett** [tpope/vim-fugitive#1576]
Since the underlying command is `git mv`, my fingers keep wanting to type `:Gmv` rather than `:Gmove`. Would you consider providing an alias `:Gmv`?

**Comment by tpope** [comment]
`:Gmove` is already deprecated in favor of `:GMove`.

**Comment by joshtriplett** [comment]
@tpope OK, but I don't think that invalidates the request. Could I request an alias `:Gmv` for `:GMove`, then?

**Comment by tpope** [comment]
`:GMove` takes one argument, `:Git mv` takes 2. It's debatably more confusing than helpful. But you can add one to your own config without involving Fugitive at all.
