### ISSUE TITLE
Discrepancy between `:Git browse` and `:Gbrowse`

### ISSUE THREAD

**Issue by teoljungberg** [tpope/vim-fugitive#1577]
I'm unsure if this falls between vim-rhubarb or vim-fugitive as I have only tested this for GitHub repositories.

If I open a commit from fugitive through `:Gedit SHA`, or navigate to one from `:Git log` or `:Glog`, and then run `:Git browse` to open the commit in my browser it only opens the repository and no the particular commit from the open buffer. Where I would expect it to behave as `:Gbrowse`.

Should commands such as `:Git browse` wrap their sibling `:Gbrowse`? Or what is the planned design for these commands?

**Comment by tpope** [comment]
`:Git browse` is actually `hub browse` and is unrelated to `:GBrowse`. I do plan to one day phase out the rhubarb.vim behavior that configures `:Git` to call `hub`, which should hopefully clear up any confusion.
