### ISSUE TITLE
Fugitive not working in a non-typical deployment

### ISSUE THREAD

**Issue by adah1972** [tpope/vim-fugitive#1578]
Hi Tim,

I am asking for help here. I am working on a repo that has special tool support similar to git submodules, where .git is a file containing the relative path to its real position. Git commands work, but fugitive does not. Specifically, `:Git log` works, but any file-specific commands have weird behaviour. E.g., when I execute `:Gblame`, I got something like:

> fatal: no such path 'README.md' in HEAD

In the beginning, I thought fugitive may not support .git as file, but then I found that fugitive had supported submodules since mid-2019. Would you please give some advice where the problem could be? Do you have some assumptions on the path in the .git file? (The repo I work on use a control directory whose name is not ‘.git’.)

**Comment by tpope** [comment]
The problem is likely that you need to set `core.worktree`. Git commands that create `.git` as a file usually do this for you, but if you did something peculiar, you might need to set it manually.

**Comment by adah1972** [comment]
`core.worktree` does solve the problem. Thanks!
