### ISSUE TITLE
Disable mappings in G[cl]log buffers

### ISSUE THREAD

**Issue by mg979** [tpope/vim-fugitive#1583]
Does it make sense to have them there? they don't have git filetype and I have to think twice before pressing a key inside of them (`<CR>` for example).

**Comment by tpope** [comment]
Are you referring to the quickfix window? The mappings are already disabled there (or more precisely, never enabled).

**Comment by mg979** [comment]
When I do `0Gllog` it loads the revisions for the current file in the location list, and the mappings are also enabled in the buffer with the file at revision (and it's the same filetype of the original file).

**Comment by mg979** [comment]
Do `:0Gllog`, then `:nmap <buffer>` and you can see it.

**Comment by tpope** [comment]
Yes, those are very deliberate, and in many cases were designed with a non-git filetype in mind. `<CR>`, to use your example, calls `:Git blame`, a common operation when you're bouncing around history.
