### ISSUE TITLE
Gdiff errors with Error detected while processing function fugitive#BufReadIndex..<SNR>118_ReplaceCmd:

### ISSUE THREAD

**Issue by noahlz** [tpope/vim-fugitive#1584]
Somehow some code from my project made its way into fugitive "option" :(
```
Error detected while processing function fugitive#BufReadIndex..<SNR>118_ReplaceCmd:
line   43:
E518: Unknown option: ExceptionInInitializerError =>
```

halp `Gdiff` no longer works for me :((

Is there quick fix to reset / repair option.  The plugin source under `.vim/bundle/vim-fugitive` is pristine.

**Comment by noahlz** [comment]
Also 

```
Error detected while processing modelines:
line  116:
E518: Unknown option: ExceptionInInitializerError =>
```

When I first open the file.

**Comment by tpope** [comment]
`ReplaceCmd` has less than 43 lines. Sounds to me like you accidentally pasted project code into `autoload/fugitive.vim`.

**Comment by noahlz** [comment]
Well autoload/fugitive.vim and everything else is pristine (no diff from origin). This is probably some weird edge case due to scala's fun syntax.  It's only one file in my project it turns out, so I can live with it.

**Comment by tpope** [comment]
Oh is that a reference to line 43 of the file? Is there something that looks like a modeline?

**Comment by noahlz** [comment]
Yes, it seems that scala code can look like modelines, what with its : and => and such

**Comment by tpope** [comment]
Do you get a similar error when you open the file normally? If not, is it because modelines are disabled in that buffer?
