### ISSUE TITLE
Gclog: The cursor is not positioned on the first line of the first diff hunk

### ISSUE THREAD

**Issue by ademin** [tpope/vim-fugitive#1588]
**Describe the bug**
According to the documentation:
```
:{range}Gclog[!] [args] Use git-log -L to load previous revisions of the given
                        range of the current file into the |quickfix| list.
                        The cursor is positioned on the first line of the
                        first diff hunk for each commit.  Use :0Gclog to
                        target the entire file.
```

**To Reproduce**
1. Clone a repository, for example: `https://github.com/tpope/vim-fugitive.git`
2. Run `git diff 5dfe858..85e2c73 -- plugin/fugitive.vim | grep  '@@'` inside the repository
3. Have a look at the result: `@@ -437,9 +437,9 @@ unlet s:cmd`
4. Run Vim with Fugitive enabled
5. Cd to the repository root
6. Open buffer with `plugin/fugitive.vim`
6. Do `0Gclog -- %`
7. Switch between commits 5dfe858 , 85e2c73 in the QuickFixBuffer (]q, [q)

**Current behavior**
The cursor is on the first line

**Expected behavior**
The cursor moves to the first diff hunk (line 437)

**Comment by tpope** [comment]
`0Gclog` targets the entire file. The first line of the entire file is always line 1.
