### ISSUE TITLE
[Question] :Gstatus in active window instead of split?

### ISSUE THREAD

**Issue by leocp1** [tpope/vim-fugitive#1589]
Is there a convenient way to have the `:Git` summary open in the active window instead of creating a split window?

**Comment by tpope** [comment]
`:0Git`. It's mentioned in the documentation although not explicitly in every context it works in.

**Comment by allanwind** [comment]
@tpope Hi Tim, any chance you could document the active window (opposed to split) behavior for :0Git?   I read the documentation and re-read after I found this issue, and I still don't grok how I could have figured it out (re mentioned).

If you update the documentation file anyways, should the deprecated section be removed or called something else, as those commands no longer work.
