### ISSUE TITLE
Git add current file

### ISSUE THREAD

**Issue by Bobbbay** [tpope/vim-fugitive#1590]
There should be a definite way to add a current file, and listed in the README/docs. Easiest way would be:

```
:Git add expand('%:p')
```

Where `expand('%:p')` gets the full path of the current file. Sadly, this doesn't work. Therefore, is there a way to add the output of a command?

**Comment by tpope** [comment]
You're overthinking it, `:Git add %`. Or `:Gwrite`, which _is_ listed in the docs.

**Comment by Bobbbay** [comment]
😅 Alright I see it, thanks!
