### ISSUE TITLE
Raise error when push without upstream

### ISSUE THREAD

**Issue by tlelson** [tpope/vim-fugitive#1591]
Perhaps this is a misuse on my part, if so, happy to learn how you'd deal with this and change.
*
When I `:Git push` on a local branch without an upstream, the underlying git command receives a fatal error (code: 128) and returns control to vim without showing received stderr.

However when I `:Git junk` a similar multi-line stderr is received by the underlying git command (code: 1) the error is echoed in the vim command line.
*
If this is not just my problem. I'm happy to have a look at it

**Comment by tpope** [comment]
As of a few days ago, `:Git push` no longer has special handling.

**Comment by tlelson** [comment]
Thanks!
