### ISSUE TITLE
vim-fugitive extensions

### ISSUE THREAD

**Issue by panosl** [tpope/vim-fugitive#1592]
Add a section in the Wiki or in the README, about vim-fugitive extensions.

I just stumbled upon:

https://github.com/stsewd/fzf-checkout.vim
https://github.com/sodapopcan/vim-twiggy

(while browsing the open issues)

and they're both amazing. it will help both @tpope and the users get what they're looking for.

If an extremely good idea is implemented in an extension, maybe it would make sense to move it back into the fold.

That way we're aware of how people are using vim-fugitve and how they're trying to work around its limitations.

**Comment by tpope** [comment]
Twiggy is discussed in #982. The difference in map conventions I mention there are also reasons why I would be reluctant to link to it in official documentation.

fzf-checkout.vim appears to be an independent plugin, not an extension.

More generally, plugins I am willing to link to in the README are generally going to fall under the category of tight integrated enhancements, such as `:GBrowse` handlers.
