### ISSUE TITLE
Support accessing url produced by GBrowse

### ISSUE THREAD

**Issue by skbolton** [tpope/vim-fugitive#1594]
Often throughout the day I am taking a lot of notes and filling in details on tickets. I have found that having urls to code in my notes and tickets is extrememly helpful. My current workflow is to run `:Gbrowse` and then copy the url from the browser and then go into my notes to paste the url.

Ideally there would be a way to get the url that `:Gbrowse` produces without leaving vim so that I can put it one of my notes. Is there a current way that I can make this work?

**Comment by tpope** [comment]
`:GBrowse!` copies to the clipboard.

**Comment by skbolton** [comment]
Apologies I think I kept searching the docs for `Gbrowse` so I didn't see the help
