### ISSUE TITLE
Git Hook output is being concatenated, instead of replacing lines

### ISSUE THREAD

**Issue by pheeria** [tpope/vim-fugitive#1596]
Hi!

Thanks for the plugin.
Everything works great, however there is a small issue with running custom hooks.
I have a TypeScript project, which has some linter rules (ESLint, Prettier) set to run on `git add`.
The linters usually rerender the lines in terminal, creating some loading effect.
However with fugitive all of the lines are appended to one another, resulting in something like this:
<img width="1315" alt="Screenshot 2020-08-24 at 10 41 19" src="https://user-images.githubusercontent.com/15848876/93113831-0c5d1c00-f6ba-11ea-9bb9-81bf77c2a2e9.png">

Is there a way to fix this?

iTerm2: 3.3.12
Vim: 8.2.1624 Huge version without GUI (Tried on previous versions as well, didn't work)

**Comment by tpope** [comment]
Looks like #1446.
