### ISSUE TITLE
Gedit yields 'Unable to open swap file for "fugitive:\\C:\\..."'

### ISSUE THREAD

**Issue by borisbrodski** [tpope/vim-fugitive#1598]
NeoVim 4.4.0, Windows 10, Fugitive 511d3035d4da2453a9cb0188b6020ed7bc8fc18f

Using `Gedit` to open files from other branches yields (for some files!) following error:

```
Error detected while processing function fugitive#BufReadCmd[89]..<SNR>112_ReplaceCmd:
line 6:
E303: Unable to open swap file for "fugitive:\\C:\PATH\TO\REPO\.git\5e850dcdc83...\PATH\TO\FILE", recovery impossible
```

This message also entirely prevents `Gvdiffsplit` from working :(

Some facts:

* After `set noswapfile` everything works as expected
* My `init.vim` doesn't mention `swap`, `swp` or `directory`.
* Cleaning my NeoVim default swap directory `<User>\AppData\Local\nvim-data\swap` doesn't help
* My project directory nor files doesn't contain any non-standard characters. Only `[A-Za-z.]`. No unicode.

PS
Thank you for absolutely amazing plugin!

UPDATE: I tracked it down to the Windows related problem with filenames longer than 260 characters. Although on my System long file names are enabled, it seems to have no effect on the NeoVim swap files. A bugfix for fugitive could be either disable swap files for fugitive buffers or to ignore the error and let Gvdiffsplit open. Thank you.

**Comment by tpope** [comment]
What is `:set directory?`?

**Comment by borisbrodski** [comment]
```
:set directory?
directory=~\AppData\Local\nvim-data\swap\\
```

I added an UPDATE section to the issue description. It seems to be the "too long file name" Windows related problem.

**Comment by tpope** [comment]
Does adding `noswapfile` before `lockmarks` to this line solve the issue?

https://github.com/tpope/vim-fugitive/blob/8080407ae97ba6aab06eadbd09db776ed27883ba/autoload/fugitive.vim#L1644

**Comment by tpope** [comment]
Also try, as a separate experiment, adding `setlocal noswapfile` before that same line.

**Comment by borisbrodski** [comment]
> Does adding noswapfile before lockmarks to this line solve the issue?

YES

> Also try, as a separate experiment, adding setlocal noswapfile before that same line.

YES, it also solves the issue
