### ISSUE TITLE
Gwrite commit message get "fugitive: error: Invalid path '.git/COMMIT_EDITMSG'"

### ISSUE THREAD

**Issue by chaofengc** [tpope/vim-fugitive#1599]
Thank you for absolutely amazing plugin !  
I came across a strange error when I switch to a new machine.

Configuration: Unbuntu 18.04, vim 8.2, fugitive latest.

Using Gwrite to do git commit yields the following error
```
fugitive: error: Invalid path '.git/COMMIT_EDITMSG'^@error: unable to add .git/COMMIT_EDITMSG to index^@fatal: adding files failed
```

The strange thing is when I quit the commit message window, it actually continues to do the commit.
And the old machine with the same configuration works fine.

**Comment by tpope** [comment]
Note that quitting the commit message window is the official way to finish the commit. `:Gwrite` is just a "do what I mean" alias for it.
