### ISSUE TITLE
Remap next and previous hunk

### ISSUE THREAD

**Issue by nomasprime** [tpope/vim-fugitive#1600]
`c` conflicts with a few things for me and the `h` for hunk mnemonic's easier for me.

Is there a way to remap `[c` and `]c`?

**Comment by tpope** [comment]
`[c` and `]c` are Vim built-ins, not Fugitive provided.

**Comment by nomasprime** [comment]
I know but I'd prefer to leave `c` alone for Vim's built-in changes. I'd rather use `h` for VCS.

Also want to use more Vim-like first and last mappings, eg, `<c-h>`, and `<c-c>` always cancels AFAIK.

Thanks anyway.

**Comment by nomasprime** [comment]
Realise I've confused the mappings: `[c` isn't related to changes but diffs, I should try to reuse this.

The only problem is a good map convention for first and last. What would be your suggestion?
