### ISSUE TITLE
Wondering if there's a way to add or get `:Gpullrequest`?

### ISSUE THREAD

**Issue by jsatk** [tpope/vim-fugitive#1601]
There are several commands in Fugitive that work only if `hub` is installed, such as `:Gbrowse`. It'd be neat if there was a way to open PRs using Fugitive as well. Something like `:Gpr` or `:Gpullrequest`. Right now I've aliased `:Gpr` to `:Git pull-request` (and my `git` is really `hub` which wraps `git`).

Is there a way already to do what I'm looking for? If not would you be open to adding it or accepting a PR to add it?

Thanks Tim. I appreciate your hard work.

**Comment by tpope** [comment]
What you have is fine. Aliasing `git` to `hub` has [fallen out of favor](https://mislav.net/2020/01/github-cli/) as it tends to be a bit of a leaky abstraction, so these days I instead call `:Git hub-pr` with this in my Git config:

```
[alias]
	hub-pr = !hub pull-request --browse
```

If you must have a singular `:Gpr` command that's on you to maintain. Every existing command of that nature - `:Gcommit`, `:Grebase`, etc - is deprecated in favor of `:Git` (or `:G`).

**Comment by jsatk** [comment]
Thanks so much @tpope. I had no idea the `:Gthing` commands were deprecated. I must've missed this in release notes.

Thanks for the kind reply. Will read that article. 👍

**Comment by tpope** [comment]
(The deprecation has not made it into a release yet.)
