### ISSUE TITLE
:Gcommit / :Git commit command hanging with no options

### ISSUE THREAD

**Issue by jvlch** [tpope/vim-fugitive#1602]
```git commit``` in my shell (bash) works as expected and brings up nvim as my editor for the commit message

core.editor is set to nvim
env doesn't show any specific GIT_EDITOR var

I tried disabling everything in my .vimrc except 

call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-fugitive'
call plug#end()

Running :G, :Gpush, :Gpull all work, but :Gcommit hangs and errors like so

```
sh: /var/folders/tm/9dn6qzg94cd3rykvkpj2zx4h0000gp/T/nvimv8fbXf/2.sh: No such file or directory
error: there was a problem with the editor 'sh /var/folders/tm/9dn6qzg94cd3rykvkpj2zx4h0000gp/T/nvimv8fbXf/2.sh'
Please supply the message using either -m or F option
```

Using the -m flag succesfully creates a commit
the tmp file does exist at that path, and its contents are:

```
#!/bin/sh
[ -f "$FUGITIVE_TEMP.exit" ] && exit 1
echo "$1" > "$FUGITIVE_TEMP.edit"
printf "\033]51;fugitive:edit\007"
while [ -f "$FUGITIVE_TEMP.edit" -a ! -f "$FUGITIVE_TEMP.exit" ]; do sleep 0.05 2>/dev/null || sleep 1; done
exit 0
```

**Comment by tpope** [comment]
We [create that file](https://github.com/tpope/vim-fugitive/blob/260182c65cae653ac20e6a69ba8cc6124e7ba6c2/autoload/fugitive.vim#L2576-L2581) before Git tries to call it. I don't know what could explain this other than some sort of weird file system delay. You could try throwing a `sleep 1` in there and see if that allows things a chance to catch up.

**Comment by jvlch** [comment]
It must have been my environment.
Gcommit began working again after these steps, without adding any sleep(s)

-PlugClean and PlugInstall
-Restart machine

The first time I ran Gcommit after the restart, it brought up the commit editor instantly, the second time, it took roughly 4 seconds to load the editor. Every attempt since then has been instant. 

Unfortunately I haven't found the root cause, or identified abnormal filesystem issues that could be tied to this, but I'm glad it's working again.

Thanks for the help!
