### ISSUE TITLE
Gclog show author of commit in quicklist?

### ISSUE THREAD

**Issue by cj** [tpope/vim-fugitive#1603]
Is it possible to show the author of the commit in the quicklist when using `'<,'>Gclog`?

**Comment by htammen** [comment]
would like to see the commiter / author as well.
Anyone knows how to achieve this?

**Comment by tpope** [comment]
Undocumented but you can `g:fugitive_summary_format` from the default of `%s` to contain additional `%` expansions as documented in the `git-log` manpage.

**Comment by ericsunplus** [comment]
Add
```
let g:fugitive_summary_format = "%cs || %<(20,trunc)%an || %s"
```
And it works wonderful!
