### ISSUE TITLE
:GMove fails when my current working directory is not the repository root

### ISSUE THREAD

**Issue by mgedmin** [tpope/vim-fugitive#1604]
I've a git repository checked out in ~/src/deployments.  I've chdir'ed into ~/src/deployments/provisioning, started vim, opened a file named roles/fridge/files/etc-postfix-main.cf and tried to rename it by doing

    :GMove roles/fridge/templates/etc-postfix-main.cf.j2

This failed with

> fugitive: fatal: renaming 'provisioning/roles/fridge/files/etc-postfix-main.cf' failed: No such file or directory

---

Some additional experiments showed that if I type the new path relative to the repository root rather than cwd, then 

    :GMove provisioning/roles/fridge/templates/etc-postfix-main.cf.j2

succeeds, which means the error message was misleading: it didn't fail to find the original file, it complained about the destination directory not existing.

Some additional help reading in case I missed anything lead me to conclude that this is working as designed?  Specifically, :h fugitive-object shows `./master` for a file in the working directory versus `Makefile` for a file in the work tree, and experiments show that

    :GMove ./roles/fridge/templates/etc-postfix-main.cf.j2

also succeeds.

I don't think there's a chance of getting an option to interpret file names relative to the working directory by default, leaving the more explicit :(top)path/name syntax for file names relative to the repository root?  But could you make the error message clearer, when :GMove fails due to a missing destination directory?

**Comment by tpope** [comment]
This is a vanilla Git error message. It's confusing in a plain Git context too, even if Fugitive's working directory behavior does compound it. Rewriting Git's error messages would be a "now you have 2 problems" solution, I will not be opening that can of worms.

> I don't think there's a chance of getting an option to interpret file names relative to the working directory by default, leaving the more explicit :(top)path/name syntax for file names relative to the repository root?

This isn't as ridiculous as you might think. As Fugitive has evolved over the years, the difference between how `:Git` and `git` use the current working directory has become an increasingly apparent leaky abstraction. But a configuration option, in addition to being a support nightmare, would only make things leakier. The fix would be to change the default behavior. Maybe someday.

**Comment by mgedmin** [comment]
Oh no, rewriting git error messages would not be a good thing, but I thought you might want to add an explicit for the existence of the destination directory before invoking git mv.

I'm glad to hear about the possibility of a default behavior change.

**Comment by mgedmin** [comment]
This issue is surprisingly annoying, because I always want to insert the current filename with Ctrl-R % and then edit it, but this gives me paths relative to the current working directory, which is not suitable neither for :GMove nor for :GRename.

**Comment by tpope** [comment]
You can use Fugitive's `<C-R><C-G>` map for this. It will insert an absolute path if your CWD isn't the work tree, but both `:GMove` and `:GRename` can handle an absolute path just fine.

Also, you could try this:

```vim
:cnoremap <C-R>% <C-R>=(@% =~# '^/\|\a\+:' ? '' : './') . @%<CR>
```

This will add a leading `./` to relative paths, which generally works basically everywhere.
