### ISSUE TITLE
cursor defaults to first comment on commit screen

### ISSUE THREAD

**Issue by fdelacruz** [tpope/vim-fugitive#1605]
The cursor is landing on first comment, below the empty line where you're supposed to write the commit message after doing 'cc'. For a min i thought this was by design to make you read the comments, but this also happens when using 'ca', to amend the last commit and edit the message. There it also lands on the first comment.

**Comment by tpope** [comment]
Does it happen with `:Git commit`? With `git commit` from the command line?

Fugitive doesn't do anything with the cursor in a commit message, I would be very surprised if it was the culprit.

**Comment by fdelacruz** [comment]
@tpope hi, it happens with both  `:Git commit` and `:!git commit`

**Comment by tpope** [comment]
What about with Fugitive uninstalled?

**Comment by fdelacruz** [comment]
Same issue.
I'll see my way out..

**Comment by MRAAGH** [comment]
I had the same issue and found this thread very helpful.
Solution: run `git commit`, then `gg` and `:q`.
Note that this can not be done using Fugitive, however.

**Comment by tpope** [comment]
You've got an autocommand somewhere that's trying to restore the cursor position from the previous time you edited the file. Probably same for anyone else experiencing this symptom.
