### ISSUE TITLE
Make :G optional?

### ISSUE THREAD

**Issue by jszakmeister** [tpope/vim-fugitive#1607]
I know you're not a fan of optional config settings and I agree that it can add a burden.  In this case, please consider that single character commands are extraordinarily valuable and would be best reserved for users to choose how to best incorporate into their environment.  fugitive's insistence on creating the shortcut `:G` ends up overwriting a custom mapping for grepping.

Yes, I can go back and clobber it with an autocommand, but that's not a great answer either (users of our shared Vim configuration would find it harder to overwrite the mapping as they'd first have to discover that an autocommand is being triggered to replace fugitive's version).  For now, we've resorted to patching out the offending line, but it'd be best not to have to patch it at all.

Thank you for your consideration!

**Comment by tpope** [comment]
You don't need an autocommand, `after/plugin/fugitive.vim` will do just fine. But I agree, the spirit of the `:Git`/`:G` distinction has always been that the first is canonical, while the second is an optional shorthand. We don't need to enter config settings territory to accomplish this.
