### ISSUE TITLE
Stage Hunk from old version of a file

### ISSUE THREAD

**Issue by gfsd3v** [tpope/vim-fugitive#1610]
Hi, first of all thank you for the awesome work. 

Could anyone enlighten me about how to apply a diff hunk from an old version of a file ?

Heres what I'm unsuccessfully doing:

1. Go to file 
2. :Gclog

![image](https://user-images.githubusercontent.com/36668882/95145904-cd6b3500-0752-11eb-829e-7999e3197d07.png)

3. Pressed `<C-r>` on the diff line 
4. Pressed `]c `to go to next diff
5. Pressed `do`/`dp` to apply the diff to the file

![image](https://user-images.githubusercontent.com/36668882/95145978-fbe91000-0752-11eb-9a9c-51573c1400c4.png)

**Comment by tpope** [comment]
If you want to change the worktree file, use `:Gedit` to return to it before attempting to apply the hunk.
