### ISSUE TITLE
Cursor moves to the top of the buffer when performing cnext in 0Gclog

### ISSUE THREAD

**Issue by Sevensidedmarble** [tpope/vim-fugitive#1611]
I don't know if this has to do with Fugitive or just a side effect of `cnext`, but when you move back and forth in the quickfix list (I use unimpaired as well so I usually do `[q` and `]q`), the cursor jumps back up to the top of the buffer. It also takes a realllllly long time in some of my bigger git projects, but I don't know if thats just me.

I would really like the cursor to stay in the same place, so fugitive could work kind of like git-timemachine in emacs. I'd like to just load all the revisions of a file into memory and move between them with a button.

**Comment by tpope** [comment]
It's not jumping to the top of the buffer, it's unloading the old buffer and loading the new one. `:cnext` is little more than `:edit` called with the next filename in the quickfix list.

More generally, the quickfix list is terrible for this sort of thing and I do not recommend using `:Gclog`. It's a mistake I would happily remove if it wasn't so popular. For exploring the history of a file I think `:Git blame` and `:Git log -p %` are better tools.

**Comment by tpope** [comment]
> It also takes a realllllly long time in some of my bigger git projects, but I don't know if thats just me.

If you're talking about the initial `:Gclog` call, it's not just you, the quickfix list scales terribly as the number of filenames increases. Another reason it's terrible for this.
