### ISSUE TITLE
Populate ex-command with git push

### ISSUE THREAD

**Issue by Moshem123** [tpope/vim-fugitive#1613]
Hi, I have no idea what I did but sometimes when I hit a few keys, the ex-command was populated with:
```
:Git push origin hash:refs/head/branch-name
```
I searched the code and found this function:
https://github.com/tpope/vim-fugitive/blob/master/autoload/fugitive.vim#L3673
However, no record of any mapping to this function or other usage, nor in the help documentation.
What could invoke this?
This cmd is super helpful and I'd like to know the mapping or correct usage.

**Comment by Moshem123** [comment]
Found that the mapping is `a` on a fugitive window, but the question stays,
Where is it defined? Why is it not documented?

**Comment by tpope** [comment]
The staging trinity of `-`, `s`, and `u`, when called on a line that isn't a file name, populate the command line with a one of a few different `:Git push` and `:Git rebase` commands. This was an experiment I added to master a while back that has lingered a bit longer than it should. I error on the side of not documenting experiments. It takes effort to do right, and I'd rather not unnecessarily tempt users into building muscle memory for something I can't provide a proper deprecation cycle for.

**Comment by chinwobble** [comment]
@tpope is there anyway I can map 
`git push -u origin my-branch`.

I'm trying this in my vimrc but its not evaluating the function 
```viml
map <leader>gp :Git push -u origin FugitiveHead()<CR>
```

**Comment by tpope** [comment]
`:help map-<expr>`, or use `:execute`.

**Comment by Moshem123** [comment]
@chinwobble 
```
nmap <leader>gp :silent exe 'Git push -u origin ' . FugitiveHead()<CR>
```

**Comment by tpope** [comment]
You don't want `silent`.

**Comment by Moshem123** [comment]
```
" Git push {{{

function! GitPushSetUpstream() abort
  echo "Pushing..."
  exe 'Git push -u origin ' . FugitiveHead()
  echo "Pushed! 🤩"
endfunction

command! Gp call GitPushSetUpstream()
nmap <silent> <leader>gp :call GitPushSetUpstream()<cr>
" }}}

```
