### ISSUE TITLE
macOS problem during commit: "no such file or directory /var/folders/..../..../126.sh"

### ISSUE THREAD

**Issue by orestis** [tpope/vim-fugitive#1616]
Hey there,

I'm seeing this intermittently. When I'm at the `:Git` window and I press `cc`, I would normally get prompted to type in my commit message, `:wq`, then done. However, sometimes, I see this:

<img width="914" alt="Screenshot 2020-10-22 at 13 48 39" src="https://user-images.githubusercontent.com/9217/96862075-abb9bf80-146d-11eb-854a-a943fe4a614a.png">

And indeed, I check that folder and there's no `126.sh` script file to be found. However, the folder does exist and is full of seemingly temp buffers inside.

Note this once this condition is triggered, the only way to fix is to restart the nvim instance.

Some details that may be useful:

* Using VimR 0.34 which uses NeoVim 0.4 AFAIK
* I have more than one VimR (and therefore NeoVim) instances open at any point in time.
* Some instances point to the same working directory
* It doesn't seem to be related to the working directory (of the two instances the point to the same working dir, one is broken, one works fine).

Let me know if I can help debugging this -- it's not easy to reproduce reliably.

**Comment by orestis** [comment]
<img width="914" alt="Screenshot 2020-10-22 at 13 56 42" src="https://user-images.githubusercontent.com/9217/96862642-6cd83980-146e-11eb-8ce0-d26c38e86c8f.png">
Another snapshot from a different VimR instance.

**Comment by dhleong** [comment]
Running into this as well. I believe the problem is in the `s:TempScript` function in `autoload/futigitive.com`. It assumes that the system will never delete the `tempname()` scripts it creates (at least, within the lifetime of the vim proc), but apparently macOS *does* eventually. I believe a fix might be as simple as:

```diff
-  if !has_key(s:temp_scripts, body)
+  if !has_key(s:temp_scripts, body) || !filereadable(s:temp_scripts[body])
```

Happy to submit a PR if this looks right!

**Comment by tpope** [comment]
Not sure what's going on exactly, but cleaning up random temp files while the system is still running seems bad. I would be surprised if this was stock macOS behavior.

Working around a slightly more robust variant of @dhleong's solution, thanks.
