### ISSUE TITLE
Jump to the section header in :G

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1617]
Existing <kbd>gs</kbd>, <kbd>gu</kbd> etc maps jump to the first file in the section. But I find more often I want to jump to the section header – for ex. to stage all files or close all inline diffs.

Since these maps support `v:count` so you can always <kbd>1gs</kbd> to jump to the first file, can we change the non-count map to go to the header?

Or alternatively, keep existing default but support <kbd>0gs</kbd> to jump to the header.

**Comment by tpope** [comment]
If you wanna stage files one by one, `gs` takes you to where you need to be. If you wanna stage _all_ files, you don't need to be anywhere, you can call `:Git add -u` and be done with it. I know `gss` would save some typing, but it's a really awkward workflow to jump to a section heading only to immediately render it obsolete. I would support `0gs` if it was possible, but I won't accept demoting the primary workflow to `1gs`. I could _maybe_ see doing something dumb like `zgs` or `gzs` but I'm not convinced it's worth it.

For folding, at least the section won't disappear out from under us, but it's still not exactly a useful place to end up after performing the single operation. I think additional maps is probably the solution here. So let's file this under #1563.
