### ISSUE TITLE
Exiting Gdiffsplit takes way too long

### ISSUE THREAD

**Issue by karthikiyengar** [tpope/vim-fugitive#1622]
Gdiffsplit takes way too long to quit, wheras Gsplit is instant. I've tried with an empty `.zshrc` :-(
Any suggestions would be appreciated.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8260207/98994961-f12f5100-2530-11eb-810d-224eaa72fbc3.gif)

**Comment by tpope** [comment]
It's probably a slow folding algorithm. Confirm by trying `:set nofoldenable` and also by trying various values of `foldmethod`.
