### ISSUE TITLE
Support `Gswitch`

### ISSUE THREAD

**Issue by swizzard** [tpope/vim-fugitive#1625]
Vim recently(ish) added a `switch` command to reduce the overloading of `checkout`. I can get by with `:G switch` but forget the space ~40% of the time & would love `:Gswitch` for consistency.

**Comment by tpope** [comment]
This would only be consistent with a handful of deprecated commands like `:Gcommit` and `:Grebase`. Going forward, the only `:Gword` commands will be commands like `:Gedit` that wrap a Vim built-in, _not_ a Git built-in.
