### ISSUE TITLE
Using Fold Keys to Open/Close Diffs in :Git

### ISSUE THREAD

**Issue by atomdmac** [tpope/vim-fugitive#1626]
My natural inclination when working with the `:Git` view is to use Vim's default "folding" keys (`za`/`zm`/etc.) to open and close the various file diffs in the `staged` and `unstaged` lists.

Is this possible to do (perhaps with a custom key map)?

EDIT:  It looks like this already sort of works once the diff for a particular file has been expanded.  What would be nice is if I could re-map `<right>` and `<left>` arrows so that I could expand/close the file diffs using the fold keys as well.

**Comment by tpope** [comment]
There's no built-in functionality for this, but maps like `nmap <buffer> za =` in the `fugitive` file type should work as a reasonable approximation.

**Comment by atomdmac** [comment]
@tpope That custom key map worked beautifully.  Thank you!
