### ISSUE TITLE
Amending commits like git-citool does

### ISSUE THREAD

**Issue by aik** [tpope/vim-fugitive#1627]
My usual scenario is `git citool`, then click on the `amend` checkbox, unstange chunks and press `commit` (and then commit unstaged chunks separately as "debug stuff"). I am looking for the same functionality in fugitive but it looks like there is no way to _edit_ a commit, only add to it, what do I miss? Thanks.

**Comment by maln0ir** [comment]
You could achieve this in git by doing `git reset --soft HEAD~1` and then `git reset --patch`. First command moves back one commit, but leave all chunks staged. Second allows to interactively unstage chunks, like `git add --patch`, but the opposite. Also `:Gstatus` has keybindings to stage/unstage chunks.
