### ISSUE TITLE
Do not change windows back and forth when resetting diff options

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-fugitive#1634]
I think restoring diff options would be more robust without changing windows back and forth, which triggers autocommands for example, which might interfere with other plugins, and adds overhead/issues in general, e.g. with regard to what "previous window" refers to etc.

`w:fugitive_diff_restore` could probably get split and used with `setwinvar(w, `&`.…)`

(Some) code ref: https://github.com/tpope/vim-fugitive/blob/e90478511d68cb8a0d8e5dea9c3629e7f0091f8c/autoload/fugitive.vim#L4898-L4909

**Comment by tpope** [comment]
Sounds good to me but we should probably drop the string shenanigans and use a dictionary. And we need to preserve the `:diffoff` fallback, which can't be done with `setwinvar()`, but in this case calling `:diffoff!` at the end will do just fine.

**Comment by tpope** [comment]
Actually I think we can probably ditch all of this for `:diffoff` and `:diffoff!`. I wrote it before [7.3.1294](https://github.com/vim/vim/commit/a87aa8061ce670c38d742b0f7e41cc950d10320f), and I don't care if people running a 7 year old Vim are mildly inconvenienced by the change.
