### ISSUE TITLE
Git blame range

### ISSUE THREAD

**Issue by andrewalker** [tpope/vim-fugitive#1635]
Hi,

I have a vague memory of being able to do `:'<,'>Gblame` on a few lines and that opening the traditional vertical split, but only with those lines filled up. But as I try it now, even with a stripped down configuration and older versions of fugitive, it always opens a horizontal split with those lines. Also, `:'<,'>Git blame` doesn't work at all.

I often work with a big repo, and the time difference between whole file and a few lines is significant.

Is blame on a range deprecated? If not, does it always run on a horizontal split?

Thank you!

**Comment by andrewalker** [comment]
Just saw in the docs that it's supposed to be a in a horizontal split :) Still, when I select a few lines and run `:'<,'>Git blame`, it says "E16: Invalid range". It works with `:'<,'>Gblame`.

**Comment by tpope** [comment]
Are you on `master`? `:Gblame` now is identical to `:Git` with a `"blame "` argument prepended; I'm struggling to see how they could possibly exhibit different behavior.

`:'<,'>Gblame` has never opened a vertical split, but you can get one with the `:vert` prefix if you so desire.

**Comment by andrewalker** [comment]
I wasn't on master, as I was trying to find if it had become horizontal at some point. It turns out it works fine on master. Sorry for the wild goose chase.

Thank you for the quick response, and for the awesome plugin!
