### ISSUE TITLE
[Question] use custom folder instead of `.git` as working directory

### ISSUE THREAD

**Issue by JoeSchr** [tpope/vim-fugitive#1638]
Is there any way to tell fugitive to use a custom folder instead of default `.git` as working directory? 

My usecase is for managing my dotfiles by using a custom `.cfg` folder and a alias `alias config='/usr/bin/git  --git-dir=$HOME/.cfg/ --work-tree=$HOME'` instead of the usual git with .git combo, like described here: https://www.atlassian.com/git/tutorials/dotfiles

I tried starting neovim with `GIT_DIR=$HOME/.cfg neovim` and also tried setting `config.core.worktree=./..` inside `.cfg/config`

Either way I get this error when trying to do `:G`:
`fugitive: working directory does not belong to a Git repository`

Grateful for any help

**Comment by tpope** [comment]
This is unsupported, and unlikely to change. Fugitive is designed to support multiple repositories in a single Vim instance, and I don't think this can be reconciled with a global `GIT_DIR` override. You might have luck by temporarily doing `:echo "gitdir: ./.cfg" > ~/.git`, but I haven't tested.

**Comment by JoeSchr** [comment]
Fair enough

**Comment by JoeSchr** [comment]
Thanks for all your amazing plugins by the way! Keep on trucking!
