### ISSUE TITLE
Hide Help on index

### ISSUE THREAD

**Issue by edugomez102** [tpope/vim-fugitive#1640]
![image](https://user-images.githubusercontent.com/50159560/100997981-e0cc2e00-3552-11eb-8799-8c61a402344b.png)

Is there a way to hide the `Help: g?` in the index of fugitive?
I never noticed it, I guess It could be a new feature but I would rather get rid of it.

**Comment by tpope** [comment]
Disable `advice.statusHints` in Git and the `Help` heading will disappear as well.
