### ISSUE TITLE
Error detected while processing BufReadCmd Autocommands for "index{,.lock}"

### ISSUE THREAD

**Issue by vendion** [tpope/vim-fugitive#1641]
I'm getting an error that is similar to issue #1307 but my reason for not reopening that issue is the output is slightly different.

The error that I am getting is as follows:

```
Error detected while processing BufReadCmd Autocommands for "index{,.lock}":                               
fugitive: failed to run `git -C /usr/home/vendion/Projects/temp-monitor --literal-pathspecs status '--porcelain=v2' -b
z` with shell=/usr/local/bin/elvish shellcmdflag=-c shellredir=>%s 2>&1
```

Vim version: 

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov  3 2020 07:34:53)                                         
Included patches: 1-1943
```

vim-fugitive version: v3.2
Git version: 2.29.2

Following the trouble shooting from the mentioned ticket I get the following:

Running `:echo system(FugitivePrepare(['status', '--porcelain', '-bz']))` produces no error/warning from Vim but also no output. Running it directly in git through my shell I get the following output.

```
[/u/h/v/P/temp-monitor]─[⎇ develop]─[+]─> git status --porcelain -bz
## develop...origin/develop?? test
```

Running `:!echo hello` does work so Vim is able to run shell commands just fine.

**Comment by tpope** [comment]
Does running `:echo system("echo hello")` work?

**Comment by vendion** [comment]
On Thursday, December 3, 2020 4:56:09 PM EST Tim Pope wrote:
> Does running `:echo system("echo hello")` work?

Doing that it does not appear as the output from the system command is getting 
captured, but I can verify that the command is actually being executed by my 
shell as running `:echo system("touch foo")` results in a new file named _foo_ 
being created in my PWD.

**Comment by tpope** [comment]
You'll need to fix `system()` to return output on your setup.

**Comment by vendion** [comment]
Quick question as `system` is a internal Vim command and patching it would take me considerable amount of time. Would overridding the `shell` setting in Vim with `set shell=(path to another shell like bash/sh/zsh/etc)` work here?

In a quick test if I run the following from within vim, the `system()` call seems to work as expected:

```
:set shell=/usr/local/bin/bash
:echo system("echo hello")
```

**Comment by tpope** [comment]
Yes, that will work. You might need to do it in your vimrc rather than interactively to get the full effect.
