### ISSUE TITLE
Target Git repo not updated after :saveas

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#1642]
Currently when I `:saveas /some/new/path` fugitive is still targeting the old repository.

Is it possible to automatically re-detect git repo for the new path?

If not possible, what is the best way to force re-detect manually?

**Comment by tpope** [comment]
You can manually force with `:unlet b:git_dir` followed by reloading the buffer.

**Comment by tpope** [comment]
If I were to try to automate this, my first step would be to peek at both `%` and `<file>` in relevant autocommand events and see if there's a way we can detect a `:saveas`.
