### ISSUE TITLE
CR within a fugitive buffer executes git blame on whole repository

### ISSUE THREAD

**Issue by strottie** [tpope/vim-fugitive#1643]
Versions: Vim: 8.0, vim-fugitive: commit 7bcfe539beee5fe8c542092732b6fd3786c6080e

Sorry if I don't have the right terminology, I'm new to vim-fugitive. By "fugitive buffer" I'm referring to a buffer opened using `:Gvimdiff`, for example. Within these buffers CR is mapped to this:

```
:nmap
n  <CR>        &@:<C-U>0,1Git blame<C-R>=v:count ? " --reverse" : ""<CR><CR>
```

Invariably, whenever I press CR (my preferred down motion) vim-fugitive runs a lengthy command on my huge repo, fills up /tmp and then vim tries to spit out the output as an error, begging for `--more--` until I'm fed up and have to manually `kill` vim.

Checking child processes I see it is internally running `git -C /path/to/repo --literal-pathspecs show --no-color -m --first-parent --pretty=format:tree%x20%T%nparent%x20%P%nauthor%x20%an%x20<%ae>%x20%ad%ncommitter%x20%cn%x20<%ce>%x20%cd%nencoding%x20%e%n%n%s%n%n%b someSHA`

I'm not convinced of the usefulness of having git blame mapped to CR in these fugitive buffers but I'm certain running it on the whole repo was not the intent.

**Comment by tpope** [comment]
It's not running `blame` on the full repo, it's running `show` on the commit `blame` found for the current line, in order to load it into the editor in the same manner as `:Gedit HEAD`. Presumably you landed on a giant commit, perhaps the initial import. It doesn't surprise me that a sufficiently massive commit would fail by filling up `/tmp`, but I could use some clarification as to what is being spit out with a `--more--` prompt? An out of disk space error should be pretty short.

**Comment by strottie** [comment]
Thanks for the clarification, indeed it must be showing the initial giant commit/import. As for the more prompt, it would seem that on error it tries to display the whole output, not just a short error message (both stdout & stderr perhaps). I never actually saw the error message as there were too many screens to "more" through (tried q, C-c, C-z, C-g, nothing could stop the flow, has to kill vim)

This said, could it be modified to get the content of only the current file from the initial commit, instead of the whole repo?

**Comment by tpope** [comment]
Actually I was forgetting that in the special case of the initial commit, it skips the commit and navigates directly to the file as it was initially added. Please check `:Git blame` and see what it's actually trying to navigate to.

**Comment by tpope** [comment]
Error message issue is solved, at least. I think that's all to be done pending further information.

**Comment by strottie** [comment]
Fixing the huge error output works great; I can now kill a long operation without fearing reprisal. The original issue/error is probably not important so I feel this issue is perfectly resolved. Thanks a bunch!
