### ISSUE TITLE
gpg-agent popup borks things up

### ISSUE THREAD

**Issue by ezzieyguywuf** [tpope/vim-fugitive#1645]
I recently set up git to sign all my commits with gpg. When I `:Git commit`, after I type in my message and hit `:wq`, the gpg-agent popup _tries_ to come, but it gets all messed up and my terminal session ends up permanently borked.

I'm happy to provide any additional information that may be needed.

**Comment by tpope** [comment]
What kind of gpg-agent popup?

**Comment by ezzieyguywuf** [comment]
@tpope it seems to be some sort of ncurses interface or something. Here is an image of what it looks like for me (please excuse the spanish locale I can translate any piece of that if you wish):

![image](https://user-images.githubusercontent.com/573684/102097046-6b364c80-3df3-11eb-9693-3f4030a17934.png)

**Comment by pedromss** [comment]
I have that exact same pop when I run `git commit -S` from the terminal, but running `:Gcommit -S` inside neovim (haven't tested with vim, freezes the screen and the popup isn't rendered. I'm not a fan of the popup itself so if there was a way to cancel the popup and simply have a password prompt I'd be happy. 

Haven't dug enough for such an option, either in git config or fugitive

**Comment by ezzieyguywuf** [comment]
My issue was in vim, not neovim, so I guess it's the same in both.

I don't really mind the popup myself, but I'm fine with any solution
honestly.

**Comment by tpope** [comment]
I think this is `pinentry-curses`, and your best bet would be to use `pinentry-x11` or `pinentry-gnome` instead. I don't know if there is a way to force it to use regular password prompt.

**Comment by ezzieyguywuf** [comment]
Thanks y'all for the comments, but i do most of my work remotely and this prefer the tui pinentry.

For now I've just stopped using vim-fugitive, lol

**Comment by odyslam** [comment]
Thanks @ipatch !

**Comment by tpope** [comment]
This workaround in https://github.com/tpope/vim-fugitive/issues/1836#issuecomment-918677504 will probably also work here.

**Comment by tpope** [comment]
Or just use loopback pinentry for everything, maybe.
