### ISSUE TITLE
git status view resolving merge conflicts, using 'x' to select ours/theirs

### ISSUE THREAD

**Issue by butterywombat** [tpope/vim-fugitive#1648]
I'm consulting this doc:
```
                                                *fugitive_X*
X                       Discard the change under the cursor.  This uses
                        `checkout` or `clean` under the hood.  A command is
                        echoed that shows how to undo the change.  Consult
                        `:messages` to see it again.  You can use this during
                        a merge conflict to discard "our" changes (--theirs)
                        in the "Unstaged" section or discard "their" changes
                        (--ours) in the "Staged" section.

```

When I'm rebasing and trying to pick 'ours' (by going to the unstaged section and pressing x on the file), it actually picks 'theirs'. And vice versa. Therefore 'x' seems to mean 'pick' rather than 'discard' in this case. Is this right? This caused so much confusion and time for me when rebasing a confusing history already 😰

**Comment by tpope** [comment]
Give it another read. In the unstaged section, it *discards* **our** changes, which means it *picks* **their** changes by passing `--theirs`. This feature is dumb; I recommend against using it.

**Comment by butterywombat** [comment]
ahh got it, it's clear now (I wonder how I thought unstaged was their changes for some reason 🤦 )

**Comment by TamaMcGlinn** [comment]
It was completely intuitive to me; we are rebasing, so we are making a new commit and naturally the unstaged changes are the ones we are trying to make on top of the new parent commit.

**Comment by tpope** [comment]
Aaaand it turns out this was wired up and documented backwards the whole time. You'll need to `let g:fugitive_conflict_x = 1` to opt into the new behavior, or use the newly documented `2X` and `3X`.

**Comment by TamaMcGlinn** [comment]
Wow, I cannot thank you enough for fixing up a feature you don't use yourself. It's very useful to me.

**Comment by Lakshamana** [comment]
@tpope as of  master  -> `28afd121511db9c4c4d070a0dc3ebb2ed5360328` running :h g:fugitive_conflict_x is not yet documented. Are you willing to accept PRs to document it properly?
![image](https://user-images.githubusercontent.com/29443505/119738095-8606f580-be56-11eb-95ee-9f028c93f4cf.png)

**Comment by tpope** [comment]
`2X` and `3X` are documented. I do not wish to waste the reader's time with this stupid, confusing alternative.

**Comment by xcfw** [comment]
Could somebody clearly explain what ours and theirs mean in this context?
e.g.:
git checkout A
git merge B

git conflict appeared
ours is B or A?

I also think this example should be part of the documentation.
