### ISSUE TITLE
:Gblame fatal: no such path 'folder/file.txt' in HEAD

### ISSUE THREAD

**Issue by jerometremblay** [tpope/vim-fugitive#1650]
I recently upgraded vim to 8.2 and now I have problems with Gblame (it worked fine before). I suspect that some 'current directory' behavior changed, but i don't know what to do.

My repo is in a folder named `~/repo`

In there, i have two files:
```
~/repo/root.txt
~/repo/sub/file.txt
```

Gblame works when I am editing root.txt, but fails when i am editing the deeper file with the error

`fatal: no such path 'sub/file.txt' in HEAD`

While editing file.txt, i can specify it manually `:Gblame file.txt` and it opens the blame in a horizontal split, which is different than the default behavior I am expecting from :Gblame by itself.

Any suggestion or workaround?

**Comment by tpope** [comment]
Is `sub` a submodule?

**Comment by jerometremblay** [comment]
No, just a normal folder.

**Comment by tpope** [comment]
Do you have `'autochdir'` enabled, or a plugin that provides a similar behavior?

Is any file or directory that is remotely related a symlink?

Are you using Git's multiple work tree feature? Is `.git` a plain old Git repository directory?

**Comment by jerometremblay** [comment]
Setting `noautochdir` solved the problem. Now that you mention it, before i upgrade vim it simply didn't work for me.

Is it possible to always specify the full expanded path of the file with `Gblame` so I can leave `autochdir` active?

**Comment by jerometremblay** [comment]
On the command line, i can reproduce the problem. If I have
```
~/repo/dir1/file1.txt
~/repo/dir2/file2.txt
```

and i `cd ~/repo/dir1`, running `git blame dir2/file2.txt` gives me the same error.

This is clearly a git problem, not a fugitive issue. Thanks a lot for your help.

**Comment by tpope** [comment]
Despite the fact `'autochdir'` may as well be renamed to `'breakhalfmyplugins'`, Fugitive _does_ work with it set, as it favors calling `git -C ~/repo` rather than relying on the current working directory. You've got something else wonky in your setup, either on the Vim side or the Git side.
