### ISSUE TITLE
Gbrowse doesn't work on local clones (git clone <path>)

### ISSUE THREAD

**Issue by osa1** [tpope/vim-fugitive#1657]
I have a repo with a GitHub origin. When I do `git clone <repo directory> <new directory>` to clone it in a new directory, `:Gbrowse` doesn't work in the new directory, failing with "No Gbrowse handler installed for '<path>'".

It would be great if this case was handled (when the remote, directly or transitively, is another directory with a GH remote).

**Comment by tpope** [comment]
Is this ... is this a common workflow? I wouldn't say I'm opposed to it, but it feels like a pretty narrow use case.

**Comment by osa1** [comment]
I don't know if it is common but I use it all the time. This feature is very useful when (1) the repo is large and cloning takes minutes  (2) the project is large and building takes minutes. Some example projects are Rust (https://github.com/rust-lang/rust/), LLVM (https://github.com/llvm/llvm-project), and Linux (https://github.com/torvalds/linux).

In my case I'm working on Rust. Because cloning and building takes a long time I use the command in my original message to be able to work on multiple patches simultaneously. (I can't change the branch while one of my patches is building so I need multiple trees)

**Comment by tpope** [comment]
Ah, sounds to me like `git-worktree` would solve your problem and would be a much more elegant workflow for you all around.
