### ISSUE TITLE
can't install via vim plug

### ISSUE THREAD

**Issue by SeeThruHead** [tpope/vim-fugitive#1658]
hi sorry this is probalby the wrong place but I can't seem to install via vimplug

 could not read Username for 'https://github.com': terminal prompts disabled
 
 i don't really understand why I need anything related to github? we don't use github anyway we use gitlab
 
 i've read the faq but i've never had this issue with fugitive in the past, never had to set anything up
 
 thanks

**Comment by rickprice** [comment]
Plugins are loaded from GitHub. That is why you are having errors about it.

I personally would try cleaning all your plugins, and reinstalling.

But if you look at stuff on google about your error and Github you will probably get better help than this.

I have had that error before, but not with Vim plugins. I believe it was with my Git repository.

Frederick

**Comment by tpope** [comment]
Correct, if it's happening on installation, it can't be a Fugitive problem.

**Comment by datashaman** [comment]
I know what's happening here, cos it happened to me too. The clue is that it's trying to login. The repo is public, there should be no need to login to GitHub.

You've typed the name of the plugin incorrectly and it's trying to login to see if you have access to a private repo that has a similar name.

In my case it was `tpope/figutive`. Once I fixed the typo the problem went away.
