### ISSUE TITLE
Error 'fugitive: file does not belong to a Git repository' when a preview window is open in another tab

### ISSUE THREAD

**Issue by koroliov** [tpope/vim-fugitive#1660]
If no preview window is present, `:G` opens the Fugitive status window, everything works as expected.
 
But if I have a preview window already, I create a new tab to work with Fugitive with `:tab split` and in that tab entering `:G` gives only an error 'fugitive: file does not belong to a Git repository'.

I tried to debug it a bit myself, and found that this logic is located at `plugin/fugitive.vim:17`. It doesn't find the `.git` directory, returns an empty string. If I change:

     if empty(dir) && (empty(bufname('')) || &buftype =~# '^\%(nofile\|acwrite\|quickfix\|prompt\)$')

to (notice that `&&` changed to `||`)

    if empty(dir) || (empty(bufname('')) || &buftype =~# '^\%(nofile\|acwrite\|quickfix\|prompt\)$')

It seems to work OK, but I'm not sure if it is safe to do this change. I'm going to use fugitive with my fix for a while to see if any problems surface.

**Comment by tpope** [comment]
What does "have a preview window already" mean precisely? Fugitive hasn't used the preview window in years, it should be irrelevant.

The conditional is correct as is, at any rate.

**Comment by koroliov** [comment]
When I work on a project, I always have a preview window, where I can see some info with Ctrl+x Ctrl+u. It's my own set up, I do in in vimrc. I open it like this (it's set conditionally, depending if I'm being in a sort of 'project directory'):

      new +setl\ previewwindow\ buftype=nofile\ noswapfile

When I try to open the Fugitive status window with `:G` (it doesn't matter whether it's in the same tab, or if I open a new tab) it says `fugitive: file does not belong to a Git repository`.

If I don't open this preview window, even when I'm in the same 'project directory' Fugitive works fine.

But when I do open that window, in this case Fugitive isn't able to find the .git directory for some reason.

I just wanted you to know, that this line intuitively looks wrong:

    if empty(dir) && (empty(bufname('')) || &buftype =~# '^\%(nofile\|acwrite\|quickfix\|prompt\)$')
      return FugitiveExtractGitDir(getcwd())

Why should it extract the git directory only if two conditions are satisfied `if empty(dir) && (`? Isn't it enough that `dir` is empty?

_Also I disabled all other plugins (moved them to the `pack/plug/opt` directory), so I don't think that it has something to do with them._

**Comment by tpope** [comment]
> When I work on a project, I always have a preview window, where I can see some info with Ctrl+x Ctrl+u. It's my own set up, I do in in vimrc. I open it like this (it's set conditionally, depending if I'm being in a sort of 'project directory'):
> 
> ```
>   new +setl\ previewwindow\ buftype=nofile\ noswapfile
> ```

Append `|wincmd p` to defocus that preview window and I would expect things to work as you expect.

> ```
> if empty(dir) && (empty(bufname('')) || &buftype =~# '^\%(nofile\|acwrite\|quickfix\|prompt\)$')
>   return FugitiveExtractGitDir(getcwd())
> ```
> 
> Why should it extract the git directory only if two conditions are satisfied `if empty(dir) && (`? Isn't it enough that `dir` is empty?

If I do this in the shell:

```
    cd ~/repository
    vim /etc/passwd
```

Then Fugitive _should not_ activate, because `/etc/passwd` is not part of a repository. Your change causes it to use `~/repository/.git` as the Git directory, which can lead to confusing failures.
