### ISSUE TITLE
Feature request: Support `git log -L :<funcname>:<file>`

### ISSUE THREAD

**Issue by strottie** [tpope/vim-fugitive#1663]
With the cursor on a function name :Gclogfunc vim-fugitive would run `git log -L :<funcname>:<file>` and present the output similar to :Gclog

Suggested optional arguments: [funcname [file]]

Alternate :Gllogfunc using :Gllog

**Comment by tpope** [comment]
```vim
command! -bar Gclogfunc execute 'Gclog -L :' . expand('<cword>') . ':%'
```

There's a million possible utility commands like this; Fugitive doesn't have room for all of them.

**Comment by strottie** [comment]
Thanks for the recipe!

However, although this is very useful, the output is not similar to the CLI version where the each refpoint is shown as the diff related to the function only and the full function as context. Instead, fugitive displays the full commit diffs and you search the diff for the relevant part (where full function context is missing) or jump to the next quickfix/location line (where the specific revision of the file is loaded but without the actual diff visible).

The quickfix is quite useful as is, but I feel it would be much better if the function-context-diff was shown instead of the whole commit.

Thanks again for the quick response!

**Comment by tpope** [comment]
Try swapping in `.Gclog` then.

**Comment by strottie** [comment]
With .Gclog I get only the jump list of the function in all previous revisions where it was changed (effectively removing the commit diff entries). Interesting...

What's still missing, and very useful from the CLI version, is easy access to the diff applied to that function (with full function context). Of course it would be relatively easy to then run another recipe to Gvdiffsplit with the previous revision of the one being viewed / jumped to, but the way the CLI presents it is so much more direct and cleaner, IMO.
