### ISSUE TITLE
Incredible computer suspend upon use of the cc command to start committing to git

### ISSUE THREAD

**Issue by lopippo** [tpope/vim-fugitive#1666]
Greetings,

I am a happy user of the vim-fugitive plugin in my software development vim-based IDE. I am using GNOME3.38 and vim8.2.

My typical workflow is: edit a file; enter command :GStatus; select the files I want to commit using '-' as many times as required and finally type cc to enter the commit process. 

When I enter that cc command, my whole system goes to suspend (sleep) and I cannot have it awaken. I need to forcefully shutdown without even trying to resume.

Has anybody already seen this weird interaction? This is new to me, because I was using KDE before. But I do not have any KDE setup anymore to check that behaviour.

Note that I have tried to reproduce that behaviour elsewhere but could not find another situation that leads to the same results.

Edit: I have reproduced the problem using not cc but :Gcommit. Same results: the computer goes to suspend. So, it does not seem to be some 'cc' shortcut doing odd stuff...

Edit: I tried another window manager and the results are the same. Really absurd stuff, here...

Sincerely,
lopippo

**Comment by tpope** [comment]
Disable everything in `.git/hooks` and try again. Report back if it's still an issue.

**Comment by lopippo** [comment]
I have to tell you that the behaviour still is there even with .git/hooks renamed to .git/washooks.

**Comment by lopippo** [comment]
I wonder how we could trace the plugin activity and check how the suspend is called starting from the :Gcommit command.

**Comment by tpope** [comment]
* Does it happen with `git commit` in the terminal?
* Does it happen with other commands such as `:Git add`?
* Does it happen with other commands that invoke an editor, such as `:Git notes edit`?
* Does it happen if you bypass the editor with `:Git commit -m "Message"`?

**Comment by lopippo** [comment]
git commit: no problem
:Git add: no problem
:Git notes edit: triggers the problem (nothing evidently apparent in the top processing monitor, although 2-3 kworker threads see their cpu consumption greatly increased). When I kill vim, I get the following message: E482: Can't create file /tmp/vcFYecl/8.exit
:Git commit -m "Message": no problem
I hope that helps you help me:-)

**Comment by tpope** [comment]
What happens if you call `:!sleep 1`?

**Comment by lopippo** [comment]
I guess, you pinpointed it! This is the output of that command:

Failed to suspend system via logind: Access denied
Failed to start suspend.target: Unit suspend.target is masked.

shell returned 1

Press ENTER or type command to continue

The suspend fails, because I have neutralized it using systemctl, as described in a previous message.

I'll look where the sleep command takes over as an alias of suspend.
Thank you for your smart endeavour !

**Comment by lopippo** [comment]
Done! While reinstalling this new system with older backups than my previous system (I did not use vim at all at the time), I have unknowingly imported an old script named sleep.

Please, accept my apologies for your time lost trying to understand the issue.
Yours, most sincerely,
Filippo
