### ISSUE TITLE
`:Gdiff origin/doesnotexist:%` should trigger an error

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-fugitive#1667]
`:Gdiff origin/doesnotexist:%` silently passes, but appears to behave as if `%` was used only.

I think it would be better to get an error, or at least a warning in this case (and with `:Gedit origin/doesnotexist:%` etc)

**Comment by tpope** [comment]
I wouldn't know where to begin adding a proper error flow, but I can at least route it to an invalid location rather than a valid but incorrect one.
