### ISSUE TITLE
Fugitive GStatus not showing DiffChange syntax

### ISSUE THREAD

**Issue by chinwobble** [tpope/vim-fugitive#1673]
This is a great plugin that I've used for a long time!

I just want to ask is it possible to highlight the differences between lines in the `GStatus` screen?

In Github it looks like this:
![image](https://user-images.githubusercontent.com/18226001/107754676-ed041100-6d75-11eb-8e74-deee5975c70c.png)

Notice the highlighting around what was changed in the line.

However in my GStatus screen it just looks like this:
![image](https://user-images.githubusercontent.com/18226001/107754729-ff7e4a80-6d75-11eb-88fb-b222c693ba56.png)

I would like to get fugitive to look similar to that.
Any help would be appreciated

**Comment by tpope** [comment]
Fugitive is just using `syntax/diff.vim` there, so no, probably not, but I haven't researched if there are plugins that enhance the `syntax/diff.vim` highlighting.
