### ISSUE TITLE
Windows: Complete git commands in G even if *.exe is in wildignore

### ISSUE THREAD

**Issue by habamax** [tpope/vim-fugitive#1682]
Currently Gpush and Gpull are deprecated in favor of G command.

I was able to `gpu<tab>` to quickly run either Gpush or Gpull, now I have to write full command: `G pull` or `G push` as there is no tab completion for those subcommands.

Other G subcommands have completions, push and pull have not.

To reproduce:
1. run vim on a file in git repo
2. `:G pu<tab>`

Expected: `push` or `pull` subcommand completion.

**Comment by tpope** [comment]
Subcommand completion is most definitely supported. Here is the code that generates the list of them if you want to investigate what might not be working on your system: https://github.com/tpope/vim-fugitive/blob/eb4d75efb621870393fe174e1647c585544eb732/autoload/fugitive.vim#L2640-L2641

**Comment by habamax** [comment]
> Subcommand completion is most definitely supported

That is true.

But not for `pull` and `push` on Windows (g)vim:

![fugitive-gpull-comp](https://user-images.githubusercontent.com/234774/108636038-e2432d80-7493-11eb-92c1-1a55697956a1.gif)

Works on debian WSL though.

**Comment by tpope** [comment]
Can you take a look in `--exec-path` and see what's going on?

There's also #1629, which I haven't been in a rush to look into.

**Comment by habamax** [comment]
I got list of subcommands where there is no `pull` and `push`:

![image](https://user-images.githubusercontent.com/234774/108636343-a9a45380-7495-11eb-8757-4289b7522375.png)

What I have run:

```
function! Sub(str,pat,rep) abort
  return substitute(a:str,'\v\C'.a:pat,a:rep,'')
endfunction

" this is `git --exec-path` result
let exec_path = 'C:/Users/maksim.kim/scoop/apps/git/2.30.1.windows.1/mingw64/libexec/git-core'
let g:subcommands = map(split(glob(exec_path.'/git-*'),"\n"),'Sub(v:val[strlen(exec_path)+5 : -1],"\\.exe$","")')
echo g:subcommands
```

**Comment by tpope** [comment]
See if you can figure out why `glob()` isn't returning them?

**Comment by habamax** [comment]
Okay.

The issue is that I have `wildignore` ignoring executables...


```
glob({expr} [, {nosuf} [, {list} [, {alllinks}]]])		*glob()*
		Expand the file wildcards in {expr}.  See |wildcards| for the
		use of special characters.

		Unless the optional {nosuf} argument is given and is |TRUE|,
		the 'suffixes' and 'wildignore' options apply: Names matching
		one of the patterns in 'wildignore' will be skipped and
		'suffixes' affect the ordering of matches.
		'wildignorecase' always applies.
```

If I add `glob(exec_path.'/git-*', 1)` the it works for me.

**Comment by tpope** [comment]
`{nosuf}` was added in

**Comment by habamax** [comment]
Thx, works like a charm!
