### ISSUE TITLE
Silently load changes to quickfix

### ISSUE THREAD

**Issue by nkcfan** [tpope/vim-fugitive#1685]
I like to `:Git! difftool` to load changes into quickfix. So I run it automatically by `autocmd User Fugitive`. However this command will open quickfix window and I always `:cclose` it immediatly. So I see a quickfix window flashing.

I prefer it silently write into quickfix. I will use `:colder` or `:cnewer` to navigate and never look at quickfix window itself.

Reading the code, and I think it is hard-coded here
https://github.com/tpope/vim-fugitive/blob/6c4c7c9aebc4c65c13f94597e4c9352dbba21fa5/autoload/fugitive.vim#L635

**Comment by tpope** [comment]
The flicker is triggered by an early `redraw`, which enables displaying earlier entries while later entries are still being generated. I'm pushing a change that disables that behavior on `:silent Git difftool`, which I think is an appropriate if unusual application of `:silent`.

This is not to say I endorse or officially support such autocommand shenanigans.

**Comment by nkcfan** [comment]
It works! Thanks @tpope !
