### ISSUE TITLE
[question]Async Git Push/Pull 

### ISSUE THREAD

**Issue by rjshrjndrn** [tpope/vim-fugitive#1688]
Hi,
Thank you for this awesome plugin.

Recently `:Gpush` changed behaviour not to use `Dispatch`. I know we have to use the `:Dispatch git push`. 
But the feature I am not able to reproduce is the `automatic close of the quick fix window` when I `:Dispatch git push` if it successful. Is there any way to do that. Because I want to see the git push in realtime and will have the quick fix window will be remaining if there is an error.

This feature is especially handy, when we use `git pull`. so that we can see whether we've got changes or not.

**Comment by tpope** [comment]
Here's a `compiler/git.vim` I made to include with Fugitive before deciding I didn't want to take responsibility for it. A matching error in the compiler plugin is what makes dispatch.vim leave the quickfix window open.

```vim
" Vim compiler file

scriptencoding utf-8

if exists("current_compiler")
  finish
endif
let current_compiler = "git"

let s:cpo_save = &cpo
set cpo-=C

if exists('g:fugitive_git_executable')
  execute 'CompilerSet makeprg='.escape(g:fugitive_git_executable, ' "\')
else
  CompilerSet makeprg=git
endif

CompilerSet errorformat=
      \%-G%.%#%\\r%.%\\+,
      \Cloning\ into%.%#\ '%f'...,
      \Клониране\ и\ създаване\ на\ %.%#\ хранилище\ в\ „%f“…,
      \Klone\ nach%.%#\ '%f'...,
      \Clonage\ dans%.%#\ '%f'...,
      \Clonar\ em%.%#\ '%f'...,
      \Klonar\ till%.%#\ \"%f\"...,
      \Đang\ nhân\ bản\ thành%.%#\ “%f”...,
      \正克隆到\ '%f'...,
      \%+Egit:\ %m,
      \%+Eerror:\ %m,
      \%+Wwarning:\ %m,
      \%+Iusage\ %#:\ %m,
      \%+Iупотреба:\ %m,
      \%+IVerwendung:\ %m,
      \%+I\ %#uso:\ %m,
      \%+Ianvändning:\ %m,
      \%+Icách\ dùng:\ %m,
      \%+I用法：%m,
      \%+Efatal\ %#:\ %m,
      \%+Eфатална\ грешка:\ %m,
      \%+Eödesdigert:\ %m,
      \%+Enghiêm\ trọng:\ %m,
      \%+E严重错误：\ %m,
      \%+ECannot\ %.%#:\ You\ have\ unstaged\ changes.,
      \%+ECannot\ %.%#:\ Your\ index\ contains\ uncommitted\ changes.,
      \%+EThere\ is\ no\ tracking\ information\ for\ the\ current\ branch.,
      \%+EYou\ are\ not\ currently\ on\ a\ branch.\ Please\ specify\ which,
      \CONFLICT\ (%m):\ %f\ deleted\ in\ %.%#,
      \CONFLICT\ (%m):\ Merge\ conflict\ in\ %f,
      \CONFLICT\ (%m):\ Rename\ \"%f\"->%.%#,
      \CONFLICT\ (%m):\ Rename\ %.%#->%f\ %.%#,
      \CONFLICT\ (%m):\ There\ is\ a\ directory\ with\ name\ %f\ in\ %.%#,
      \%+ECONFLICT\ %.%#,
      \%+EKONFLIKT\ %.%#,
      \%+ECONFLIT\ %.%#,
      \%+EXUNG\ ĐỘT\ %.%#,
      \%+E冲突\ %.%#,
      \%\\w%\\t%f

let &cpo = s:cpo_save
unlet s:cpo_save
```

**Comment by 3nuc** [comment]
If you're confused what to do with the above code, install dispatch.vim then read this: https://github.com/tpope/vim-dispatch#compiler-switching
You need to register a compiler for dispatch.vim so it knows what to do when you type `:Dispatch git push` (in this case git doesn't mean "git the shell command" but "git the vim compiler definition from compiler/git.vim"
Basically, add the above code to ~/.config/nvim/compiler/git.vim and "Dispatch git push" should be async.

**Comment by rjshrjndrn** [comment]
@sethidden 
If I'm editing a symlinked file, with the use of `moll/vim-bbye` plugin, the original file will be opened, and `:Git push` will follow the file path. Is there any way to do the same with the above code?
