### ISSUE TITLE
:Gbrowse support for locally-firewalled github:enterprise

### ISSUE THREAD

**Issue by suan** [tpope/vim-fugitive#169]
This would be a godsend for our tangled codebase. This issue is similar to #151, but simpler in the sense that the url path is exactly the same as github.com - we just need to make the URL base configurable.

What I envision is a configuration option to set your github:enterprise URL base either in .vimrc or a ~/.fugitiverc. Then when Gbrowse is invoked, fugitive will first check github.com as it does now, but will check whether the configured gh:enterprise URL matches if that fails and invoke that.

Let me know whether you're willing to add such functionality to the codebase, and if you don't plan on working on it, I'll see if I can come up with a patch.

**Comment by gnycl** [comment]
For future readers, the relevant commit here was: https://github.com/tpope/vim-fugitive/commit/41ea90cddf1aa7397f0b4bf87f8534f9d1730814. Although I don't see the `g:fugitive_github_domains` in current documentation, it still works.

You can add this to your vimrc or just run at the vim command-line to set your GitHub Enterprise domain: `let g:fugitive_github_domains = ['git.example.edu']`

**Comment by tpope** [comment]
See [rhubarb.vim](/tpope/vim-rhubarb). Built-in fugitive support for GitHub is deprecated.
