### ISSUE TITLE
:Grename to automatically rename alternate file too?

### ISSUE THREAD

**Issue by bart9h** [tpope/vim-fugitive#1690]
("alternate file" as in https://github.com/vim-scripts/a.vim)

When I :Grename a C/C++ file of my project, I can't use the alternate plugin to get to the correspondent header file anymore.
I have to manually open it, then manually :Grename it too.

It would be very nice if :Grename could automatically rename both the current and the alternate file (if one exists) at once.

Would that be possible (or desirable)?

**Comment by tpope** [comment]
I don't think Fugitive should take responsibility for this anymore than `git mv` should. Implementation/header pairings are just one of countless sets of files that once could conceivably rename simultaneously, and I don't think Fugitive should become a clearinghouse for that.

To eliminate the "manually open it" step, alternate to the header first, call `:GRename` there, then use `CTRL-^` aka `CTRL-6` to return to the implementation file and rename again. You could wrap this workflow in your own function if you want to fully automate it.
