### ISSUE TITLE
`Gdiffsplit` shows empty file in left split in neovim

### ISSUE THREAD

**Issue by MarcelRobitaille** [tpope/vim-fugitive#1692]
Recently (presumably after updating vim-fugitive), `Gdiffsplit` and related commands don't work anymore. They only show an empty file in the left hand side. This happens for every file I have tried. This only happens in neovim, vanilla vim works as expected.

I also get a new (at least I never noticed it before) warning: `Use :Gdiffsplit! for 3 way diff`. I don't want a 3 way diff, only 2 way. I did change `git config --global merge.conflictstyle diff3`, but I didn't think that should affect this. If I do do `Gvdiffsplit!`, I get the same empty files, but now there are two.

Here is a screenshot of the problem (with `Gvdiffsplit`):
![image](https://user-images.githubusercontent.com/8503756/110542826-f035b700-80ff-11eb-835a-14550659d11b.png)

I am using nvim v0.4.4, latest (master) fugitive, and git 2.30.1. Everything works fine on my other computer with the same versions of the software and for the same file.

**Comment by tpope** [comment]
It seems to have mistakening concluded you're a merge conflict which is handled by this code:

https://github.com/tpope/vim-fugitive/blob/601bf2e225af61bd64440f841f6d64dbb3d95be5/autoload/fugitive.vim#L4905

Try running `git ls-files --unmerged -- some/filename` and see if it outputs anything. My guess is it's printing some red herring warning.

**Comment by MarcelRobitaille** [comment]
Thanks for your reply. That command gives no output and exits with code 0.

**Comment by tpope** [comment]
Try `:echo system(FugitivePrepare('ls-files', '--unmerged', '--', expand('%:p'))`, which should be almost identical to what the plugin is actually doing.

**Comment by MarcelRobitaille** [comment]
Ok, that might be a clue. Running that gives:
```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```

I copied the command from `FugitivePrepare('ls-files', '--unmerged', '--', expand('%:p')` and pasted it into `system()` in a new nvim instance with `-u NONE`, which gave no output and exited without error. Maybe it's unrelated to fugitive and there is something very wrong with my config?

**Comment by tpope** [comment]
This smells like `:set shellcmdflag=-ic`. When I set that in Neovim I see that error everywhere, even in `:!ls`.

**Comment by MarcelRobitaille** [comment]
Somehow, there was an unstaged `set shell=bash\ -i` at the bottom of my `vimrc` that I don't remember adding. Really baffled as to how that got there. 

Can confirm that removing that line makes `Gdiffsplit` work as expected. Thanks for your help.
