### ISSUE TITLE
Calling :Git on a symlink to a file that belongs to another repo

### ISSUE THREAD

**Issue by Jasha10** [tpope/vim-fugitive#1693]
Good afternoon,

I have an idea for a possible fugitive feature.

This is motivated by my ~/.bashrc file (and other dotfiles), which are symlinks to version-controlled files, e.g. to ~/stow/bash/.bashrc. (I've been using GNU stow to manage my dotfiles).

The ~/stow directory is under version control, but when I run `vim ~/.bashrc` and then use the command `:Git` on that file, I get an error: `fugitive: file does not belong to a Git repository`. This is because the symlink ~/.bashrc is not itself under version control. But it *points* to something that *is* under version control.

I wonder if it makes sense to have `:Git` and related commands detect that ~/.bashrc points to something that is version controlled, and dereference to the target ~/stow/bash/.bashrc before making a call to `git`.

This would be useful if I have e.g. used vim to open the symlink, made some changes, and then want to commit the changes to the repo that contains the symlink's target.

I haven't totally thought through how such an API would behave (e.g. what if the symlink itself is also version controlled, possibly in a different repo?). But I wanted to share the idea.

**Comment by tpope** [comment]
No, I don't believe that `:Git` should do symlink resolution that `git` does not. See #147 and https://github.com/tpope/vim-fugitive/issues/147#issuecomment-506960242.
