### ISSUE TITLE
Input lag when cursorline is active

### ISSUE THREAD

**Issue by jonwalstedt** [tpope/vim-fugitive#1694]
I get a significant input lag when typing commit messages using vim-fugitive when the cursorline is active. If i turn it of the lag goes away (this is only happening in vim-fugitives git status / git commit window and not in any other windows or buffers.

Steps to reproduce:

```
" .vimrc

" Plugins {{{
let autoload_plug_path = stdpath('data') . '/site/autoload/plug.vim'
if !filereadable(autoload_plug_path)
  silent execute '!curl -fLo ' . autoload_plug_path . '  --create-dirs
      \ "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
unlet autoload_plug_path

call plug#begin('~/.local/share/nvim/plugged')
Plug 'tpope/vim-fugitive'
call plug#end()
" }}}

set cursorline
```

Then :Gstatus
stage a file and commit using cc

Compare writing with cursorline active and inactive (set nocursorline)

**Comment by tpope** [comment]
To be clear, does it happen if you call `git commit` from the command line, leaving Fugitive out of it?

**Comment by jonwalstedt** [comment]
Sorry about that, yes it seems like it does, sorry about that

**Comment by tpope** [comment]
Sounds like not Fugitive then, try with it uninstalled just to be sure. If it still happens, try disabling things like folding and syntax highlighting.
