### ISSUE TITLE
Warn about unsaved buffers when stage or commit?

### ISSUE THREAD

**Issue by vatosarmat** [tpope/vim-fugitive#1697]
I've just made erroneous commit because I forgot to save the changes I've made when reviewing delta. How about check that the buffer is saved before staging and committing it? Vim itself warns about unsaved buffers e.g. when you try to close the last window. Maybe fugitive also could perform that sort of checking?

**Comment by tpope** [comment]
Personally, I use `'autowrite'` to avoid this problem. But if that's not set, we probably should issue a warning from `:Git` similar to what Vim does on analogous commands like `:!`:

```
:!echo 123
[No write since last change]
123
```

Unfortunately, I don't think Vim gives us a good way to do that directly, so we'll need a VimL iteration of what Vim does:

https://github.com/vim/vim/blob/f4fcedc59d4cc5ae6b5270a933e8377030283c1c/src/ex_cmds.c#L1407-L1421

We can iterate over buffers with `for bufnr in range(1, bufnr('$'))`. Figuring out exactly what `bufIsChangedNotTerm` does will require more source diving. This feature isn't hard, but it will take some doing to bring it all together. Any volunteers?

**Comment by vatosarmat** [comment]
With this approach unsaved changes can still be missed if they were made with the `Git`-window already open, e.g. via `do` keys  in `Gdiffsplit` view of a modified buffer.
Anyway, after thinking twice it seems this is not something that requires intervention in `fugitive` internals. The user could either enable `autowrite` or do something like that
```vim
autocmd FileType fugitive call s:TypeFugitive()

function! s:TypeFugitive() abort
    nnoremap <silent><buffer>cc  :vert Git commit \| call ShowUnsavedBuffers()<cr>
    "Maybe also something else
endfunction

function! ShowUnsavedBuffers() abort
  let unsavedBuffers = []
  for buf in getbufinfo({'bufmodified':1})
    if !empty(buf['name']) && empty(getbufvar(buf['bufnr'], '&buftype'))
      call add(unsavedBuffers, [buf['bufnr'], buf['name']])
    endif
  endfor
  if len(unsavedBuffers) > 0
    let leftPad = '    '
    echom 'Unsaved buffers:'
    for [nr,name] in unsavedBuffers
      echom leftPad.nr.' '.name
    endfor
  else
    echom 'All buffers saved'
  endif
endfunction
```
