### ISSUE TITLE
Using git.exe with fugitive in WSL2

### ISSUE THREAD

**Issue by huangzonghao** [tpope/vim-fugitive#1698]
WSL2 is known to have slow git response, and a general practice is to use `git.exe` instead of the linux version of `git`. That's exactly what I am trying to do with fugitive. In my `.vimrc`, I added a line `let g:fugitive_git_executable = '"/mnt/c/Program Files/Git/cmd/git.exe"' `. This tells fugitive to use the windows native `git.exe` for all git purposes. It works fine on native linux directories, such as `~`. But reports the following errors on files located at windows drives that are mounted to linux, such as `/mnt/c`: 
```
Error detected while processing BufReadCmd Autocommands for "index{,.lock}":
fugitive: fatal: cannot change to '/mnt/e/test_git_repo': No such file or directory
Press ENTER or type command to continue
```

However, I have no problem running `git.exe` in those repos directly in terminal.

Anything might be causing this? Or how can I get more details on this error?

Thanks!

**Comment by tpope** [comment]
Because Fugitive doesn't require your current working directory to be the root of the repository, Git is invoked as `git -C /path/to/repo` so that the correct repository is used.  See #691 for further discussion, including a possible workaround.

**Comment by shmup** [comment]
@huangzonghao here is something I'd look into:

https://github.com/tpope/vim-fugitive/issues/691#issuecomment-1227655072
