### ISSUE TITLE
Error during merge conflict resolution; when trying to discard unstaged file deleted in --theirs

### ISSUE THREAD

**Issue by TamaMcGlinn** [tpope/vim-fugitive#1699]
I am resolving a merge conflict using the fugitive status window by pressing X on a file:

```
fugitive: error running `git -C /home/me/repository --literal-pathspecs checkout --theirs -- ./path/to/file.cpp`: error: path 'path/to/file.cpp' does not have their version
```

When picking one version or the other means a deletion, it would be nice if fugitive turned this into `git rm file`.

[Here](https://www.reddit.com/r/git/comments/3j9nyl/how_to_checkout_theirs_for_deleted_files/) is someone with the same issue using the commandline; arguably this should be fixed upstream, in git itself.

**Comment by tpope** [comment]
[We already do that](https://github.com/tpope/vim-fugitive/blob/3eb6f316c09553989e59bb3802da100a6fb7c091/autoload/fugitive.vim#L3652-L3653). If it's not working I need reproduction instructions.

**Comment by TamaMcGlinn** [comment]
Sure, here you go. Put this script somewhere you don't already have a 'test' dir, you just have to press 'X' (cursor is already on the unstaged 'D file') and the error will pop up.

```
#!/bin/bash

# Delete in case you are re-running
rm -rf test/

# Set up two branches, with master modifying a file but develop on a different track deleted this file
mkdir test
cd test
git init .
echo "For convenience, this file is always present" > README.md
touch file
git add .
git commit -m "Initial commit"
git branch develop
echo "modified" > file
git add .
git commit -m "Modified file"
git checkout develop
rm file
git add .
git commit -m "Deleted file"

# Now try rebasing develop onto master
git rebase master

# (I use $EDITOR because I always run bash scripts from within vim, and that points to nvr when I do so, which doesn't cause a vim-inside vim problem)
$EDITOR test/README.md -c Gstatus
```

Expected behaviour is for the file to be reset to the modified version on master, since we are discarding a delete operation.

**Comment by tpope** [comment]
If I press `X` on the file with the `U` status, it successfully throws it away and keeps the file with the `D` status. That is, it deletes the file as expected.

If I press `X` on the file with the `D` status, I get the error message that you describe, It's using `--ours` when it should be using `--theirs` and vice versa. Which suggests to me the whole damn thing is wired up backwards. So much for "intuitive" in #1648.

**Comment by crazyjat** [comment]
There should be a command line switch to ignore these errors.
