### ISSUE TITLE
:Glog fouls up current buffer

### ISSUE THREAD

**Issue by Spidey01** [tpope/vim-fugitive#17]
Note: installed version is a8bd148683c060d37e768bd81496437b2715b200 I have also tested with 
45fe471b44900e37bf764870ca0c81409d4bce19 and get the same behaviour.

$ vim somefile-under-git
:Glog

After returning to the buffer, the o and O commands no longer work. :map o and :map O report the following:
    n  o           *@:<C-U>exe <SNR>17_GF("split")<CR>  
    n  O           *@:<C-U>exe <SNR>17_GF("tabedit")<CR>

It also reports that modifiable has been set, whenever I attempt to edit the current buffer. Haven't noticed any other oddities but, ahem... ;)

**Comment by tandrewnichols** [comment]
> You can use :Gedit (or even <C-^> if you don't navigate anywhere first) to return to the actual file.

Is this in the docs/help somewhere? I've been wondering how to get from the results of Glog back to the working index. I suppose reading the help for Gedit would've told me this, but if it were mentioned under Glog, that might be more expedient to most users.
