### ISSUE TITLE
Some fugitive function are called too many times

### ISSUE THREAD

**Issue by luisiacc** [tpope/vim-fugitive#1701]
When I have a few untracked or/and unstaged files on my git repository I've noticed that some times, navigation in the buffer start been really laggy, so I run a profile while navigating and it was nearly 2 seconds of profiling, and a few fugitive functions where called like 278 times, the self time is very low, but that are a lot if times to be called on 2 seconds, Is this normal behaviour?
I am also using lightline and coc-git.
I leave the .log file here.
[progil.log](https://github.com/tpope/vim-fugitive/files/6151165/progil.log)

**Comment by tpope** [comment]
The 278 number appears to come from updating the statusline 278 times. That seems really high, but I guess it would depend on how long you profiled and what you were doing during that time. My first suggestion would be to disable lightline and just use `FugitiveStatusline()` and see if your results vary. It looks like `FugitiveStatusline()` takes less than a millisecond to run, so it shouldn't cause performance problems unless it's getting called excessively.

**Comment by luisiacc** [comment]
> The 278 number appears to come from updating the statusline 278 times. That seems really high, but I guess it would depend on how long you profiled and what you were doing during that time. My first suggestion would be to disable lightline and just use `FugitiveStatusline()` and see if your results vary. It looks like `FugitiveStatusline()` takes less than a millisecond to run, so it shouldn't cause performance problems unless it's getting called excessively.

The issue is intermitent, it doesn't happen all the time, but the rare thing is that the profiling time was for 2 seconds, and all I did was moving like 30 lines bottom and 50 lines top, moving like that was very laggy.
