### ISSUE TITLE
`:Gmerge` causes "Not an editor command" `silent Gitmergetool`

### ISSUE THREAD

**Issue by zambotn** [tpope/vim-fugitive#1704]
When executing `:Gmerge` I got the deprecation notice (that's okaysh but still I would rather type less than more, even if it comes to a single letter) _but_ then I get "Not an editor command" referring to `silent Gitmergetool`. I suspect the right command would have been `silent Git mergetool` instead. 

I tried to solve adding a <kbd>space</kbd> here: https://github.com/tpope/vim-fugitive/blob/3eb6f316c09553989e59bb3802da100a6fb7c091/autoload/fugitive.vim#L3953 and seems working properly... does it make any sense?

**Comment by tpope** [comment]
This has apparently been broken for over a year. At this point we may as well replace it with a proper error rather than a warning.

>  (that's okaysh but still I would rather type less than more, even if it comes to a single letter)

Having `:Git merge` not call `git merge` is silly and confusing; I'm sure you understand.
