### ISSUE TITLE
Error on StageDiff

### ISSUE THREAD

**Issue by sanderch** [tpope/vim-fugitive#1708]
When I do :G command and then pres "dd" on one of the modified files - the following error appears:

> Error detected while processing function <SNR>120_StageDiff:
> line    4:
> E716: Key not present in Dictionary: sub =\~# '^S'
> E15: Invalid expression: info.sub =\~# '^S'

If I do :Gdiffsplit on a file - it works as expected without errors.

Ubuntu 18.04, NVIM v0.4.4

**Comment by tpope** [comment]
Pushed a fix 11 minutes earlier. :slightly_smiling_face:
