### ISSUE TITLE
Can I get information about local changes from Fugitive for usage in statusline? 

### ISSUE THREAD

**Issue by vatosarmat** [tpope/vim-fugitive#1710]
E.g. count of lines added/deleted/changed. Documented `FugitiveStatusline()` shows only branch name - not very much

**Comment by tpope** [comment]
`FugitiveStatusline()` is limited to fast operations we can do without shelling out to `git`. If you want to roll your own solution, Fugitive does have an API to build a shell command correctly scoped to the current buffer: try `let output = systemlist(FugitivePrepare(['diff', '--stat']))` for example.

**Comment by David-Else** [comment]
If anyone manages to get a `+` sign appearing when the buffer is modified in relation to the git repo plz post here :)

```
system("[[ -n \"$(git status --porcelain " . shellescape(expand("%")) . ")\" ]] && echo -n +")
```
was suggested https://stackoverflow.com/questions/12544512/how-to-add-git-file-status-to-vims-statusline but I imagine that using fugitive would be optimal.
