### ISSUE TITLE
fugitive: file does not belong to a Git repository

### ISSUE THREAD

**Issue by mcepl** [tpope/vim-fugitive#1712]
![screenshot-2021-03-24_15-03-1616594716](https://user-images.githubusercontent.com/198999/112323829-6f0b2200-8cb2-11eb-973d-d22736791a2f.png)

``echo b:git_dir`` says that ``b:git_dir`` is undefined variable.

I have searched through this project for similar tickets, but all of them were kind of special (open from terminal, etc.). This is not the case: I went to to the top of the checkout of ``pytest`` branch of https://gitlab.com/m2crypto/m2crypto/, open file ``src/M2Crypto/BIO.py``, go to the line 188 (``self.bio = m2.bio_new(m2.bio_s_mem())``) and get curious about its origin. So, I run ``:Gblame`` and I got this.

**Comment by tpope** [comment]
It appears to work fine on `master`, and I see no publicly available `pytest` branch. Please clarify.

**Comment by mcepl** [comment]
It's my personal clone, I don't develop on the official project: https://gitlab.com/mcepl/m2crypto/-/tree/pytest

**Comment by tpope** [comment]
Can't reproduce with that either. Are symlinks or multiple Git worktrees involved in any way?

**Comment by mcepl** [comment]
They could be: ``~/repos`` is actually a symlink to ``~/archive/knihovna/repos`` (and ``~/repos/m2crypto`` is obviously a subdirectory).

**Comment by tpope** [comment]
Try using the full, symlink-free path.

**Comment by mcepl** [comment]
```
cd `pwd -P`
vim src/M2Crypto/BIO.py
:Gblame
``
the result is the same.

**Comment by tpope** [comment]
> Actually, no: I get the bug even when :pwd shows the expanded version of the path.

I guess this implies you tried with full, symlink-free path, but if so, please clarify that Vim was never exposed to the symlink version, so we can 100% rule it out. To be really safe, temporarily `rm ~/repos`.

**Comment by mcepl** [comment]
```
m2crypto@stitny (pytest)$ rm ~/repos
m2crypto@stitny (pytest)$ cd
~@stitny$ cd archiv/knihovna/repos/m2crypto
m2crypto@stitny (pytest)$ vim src/M2Crypto/BIO.py
```
same failure

**Comment by mcepl** [comment]
Also
```
m2crypto@stitny (pytest)$ [ `pwd` == `pwd -P` ] && echo CLEAN
CLEAN
m2crypto@stitny (pytest)$
```

**Comment by tpope** [comment]
Fugitive does try to handle symlinks, but symlinks are an extremely leaky abstraction, and it's hard to rule out that Vim isn't getting confused by, say, a symlinked path in `~/.viminfo`. Which is why I ask that you `rm ~/repos` just to be 100% sure.

**Comment by tpope** [comment]
The next thing to try is:

    :echo FugitiveExtractGitDir(expand('%:p'))

If it returns the path to your `.git` directory, but `b:git_dir` isn't set, something is going wrong in `FugitiveDetect()` or the execution thereof. If it returns nothing, something is going wrong inside of `FugitiveExtractGitDir()` itself.

**Comment by mcepl** [comment]
Yup. ``:echo FugitiveExtractGitDir(expand('%:p'))`` gives ``/home/matej/archiv/knihovna/repos/m2crypto/.git`` and ``b:git_dir`` is still undefined.

**Comment by tpope** [comment]
Does it start working if you `:edit` to load the file a second time?

**Comment by mcepl** [comment]
Yup. ``:edit`` helps. Interesting.

**Comment by tpope** [comment]
One explanation is it's getting called with the wrong path the first time. Try `autocmd BufNewFile,BufReadPost * let b:amatch_p expand('<amatch>:p')` in your vimrc and check `:echo b:amatch_p` after the first and second executions.

**Comment by mcepl** [comment]
On the first try ``b:amatch_p`` is undefined. On the second try (when ``b:git_dir`` is actually defined), it is still undefined.

**Comment by tpope** [comment]
And several other obvious things I should have ruled out earlier:

* Does it work with other files in the repo?
* Does it work with other _non-Python_ files in the repo?
* Does it work with files in other repos?
* Does it work if you start Vim with no arguments and `:edit` the file directly?

**Comment by mcepl** [comment]
>     * Does it work with other files in the repo?

The same happens with README.rst in the root of the repository.

>     * Does it work with other _non-Python_ files in the repo?

see above

>     * Does it work with files in other repos?

OK, this is weird: two more repos in the same directory: https://github.com/openssl/openssl and it works perfectly on the first try (``vim README.md``) and https://github.com/python/cpython (``vim README.rst``) and it fails with the same error. Curiouser and curiouser!

>     * Does it work if you start Vim with no arguments and `:edit` the file directly?

Yes, that works always.

**Comment by tpope** [comment]
> On the first try `b:amatch_p` is undefined. On the second try (when `b:git_dir` is actually defined), it is still undefined.

You're doing something wrong here. Make sure it's in an augroup, and that you're not clearing that group.

> OK, this is weird: two more checkouts of two repos in the same directory

Does the problem not happen in other directories?

**Comment by mcepl** [comment]
> > On the first try `b:amatch_p` is undefined. On the second try (when `b:git_dir` is actually defined), it is still undefined.
> 
> You're doing something wrong here. Make sure it's in an augroup, and that you're not clearing that group.

The typo was actually yours (missing `=`), I have originally just blindly copy&paste your code into my `vimrc`. I put the corrected line in a group, and now I get `b:amatch_p` defined always to the full path and name of the edited file (with expanded symlinks). `b:git_dir` is again undefined on the first try, and defined after `:e`.

> > OK, this is weird: two more checkouts of two repos in the same directory
> 
> Does the problem not happen in other directories?

As I said, it works for `openssl` (`/README.md`) and it doesn’t for `cpython` (`/README.rst`).

OK, so a bit more testing and it is `filetype` sensitive: `.md` (`ft=vimwiki` for whatever reason), `.i` (`ft=swig`), and `.info` (`ft=info`) work, `.c` (`ft=c`), `.py` (`ft=python`), and `.rst` (`ft=rst`) don’t.

**Comment by tpope** [comment]
Strip down your config and try again.

**Comment by mcepl** [comment]
You are right: neovim is the root of all evil (well, I don't think so, but this won't persuade you otherwise, I am afraid). The problem is https://github.com/nvim-treesitter/nvim-treesitter and its parsers. When these plugins are removed and treesitter deactivated, fugitive works just fine. Oh well.

**Comment by tpope** [comment]
If you're using a plugin manager, you could try swapping the order in which the 2 plugins are loaded. You could also try adding `let b:fugitive_detect = a:path` to the top of `FugitiveDetect()` to confirm whether it's getting called, and if the path looks correct.

**Comment by mcepl** [comment]
I don't use a plugin manager, just all plugins in my `~/.vim/pack` directory are submodules of the main git `~/.vim` repo. Is there even a predictable order how the plugins are loaded? By alphabet?

**Comment by tpope** [comment]
`'runtimepath'`
