### ISSUE TITLE
Glog question

### ISSUE THREAD

**Issue by Flamme13** [tpope/vim-fugitive#1714]
Hello

After the last update, the output of the files changed in the commit is displayed in the expanded state

How to make the output look the same as before? Only the output of the paths to the changed files, which can be expanded if necessary to see the changes

It's not very convenient to work with big changes now.

![Selection_002](https://user-images.githubusercontent.com/8742198/112467380-0b4b2c80-8d78-11eb-9a13-d891c6ab4c21.png)

If there is a more convenient way to view changes by commits, then I will be grateful for the hint

thank

**Comment by tpope** [comment]
You can `autocmd FileType git set foldmethod=syntax`.

**Comment by Flamme13** [comment]
thank you so much!
