### ISSUE TITLE
Adding -l flag to set shell=/bin/bash\ within init.vim causes error

### ISSUE THREAD

**Issue by jgYro** [tpope/vim-fugitive#1716]
The following error happens when the -l or --login option is added to set shell+/bin/bash\ within init.vim. 

Error detected while processing function airline#extensions#branch#get_head[1]..airline#extensions#branch#head[6]..<SNR>84_update_untracked[42]..airline#async#vcs_clean[6]..airline#async#nvim_vcs_clean:
line   24:
E475: Invalid value for argument cmd: '/bin/bash --login' is not executable

**Comment by tpope** [comment]
That stacktrace reference Fugitive zero times.
