### ISSUE TITLE
`cc`  (commit window on :G) is super slow

### ISSUE THREAD

**Issue by thisguychris** [tpope/vim-fugitive#1717]
`shellcmdflag=-c`
`shell=/usr/bin/fish`

I've also tried setting shell bash. It is still slow.

It seems that fugitive get stuck for about 10 seconds and resume.

If I do `c<space>` and do a -m "commit" it's really fast.

**Comment by tpope** [comment]
Let's take `cc` out of it. Is `:Git commit` slow? If you close the status window first, is it still slow?

Where does it get stuck? Is it before or after the commit message window is visible?

**Comment by thisguychris** [comment]
hey @tpope 👋 

Yes, `:Git commit` is really slow, it's the same speed as doing `cc` It get stuck *before* opening the commit message. However, I also see some *lag* after committing, it shows files that are staged, even though it's already committed.

**Comment by tpope** [comment]
Did you try with the status window closed?

**Comment by thisguychris** [comment]
Hi @tpope you are right. I did it with the status window opened.

If I do a `:Git commit` with status close, **it is very fast**. I guess it only lags when status window is open? Which I use a lot, for patch, diff, etc.

**Comment by tpope** [comment]
The slowness might be the status window reloading. You can try deleting this line to confirm: https://github.com/tpope/vim-fugitive/blob/7de9b5a04b9ab63bba381d3cc2c48331ba8e4e7f/autoload/fugitive.vim#L2377

**Comment by thisguychris** [comment]
@tpope I'm very sorry for wasting your time. When I checked that line of code it wasn't there. I realized I was using an older version of fugitive. 🙇 sorry 1000x.

So I updated fugitive and now it's really fast! I've tried removing that line and re-adding it. It both has the same performance (both are real fast).

However, for some reason, it doesn't reload the status. So i have to call Status again to see the updated screen, otherwise, I still see the staged files.

**Comment by tpope** [comment]
Please explain precisely how to reproduce.

**Comment by thisguychris** [comment]
Hi @tpope  👋 
I've tried to reproduce going back each commit, I have the slowdown on this particular commit. 4e85dd342467fd8a9ec51aa162fae1b6e737a89e

On a blank repo.

1. git init
2. `wget https://downloads.wordpress.org/plugin/amazon-s3-and-cloudfront.2.5.3.zip`
3. `unzip amazon-s3-and-cloudfront.2.5.3.zip`
4. `:G`
5. `s` on `amazon-s3-and-cloudfront` folder
6. `cc` hangs a bit.

Moving a commit forward, this commit seems to fix it? https://github.com/tpope/vim-fugitive/commit/7bee1113e3d1810f4e8d26202eb0644b4d5fba7b

**Comment by tpope** [comment]
I mean how to reproduce the status reload failure.

**Comment by thisguychris** [comment]
hey @tpope the steps I showed is how to reproduce it, (status reload failure) the hanging of status is still prevalent on the latest commit. I have to manually invoke :G again to see the updated status.

I made a gif to demo what I'm seeing

![demo](https://user-images.githubusercontent.com/532797/112725788-e8c23a80-8f54-11eb-9358-3475ce00759a.gif)

**Comment by tpope** [comment]
What if you don't button mash before the `create mode...` lines finish echoing?

**Comment by thisguychris** [comment]
wow @tpope I can't believe you noticed that `jjjj` 😲

But yeah, no difference. It still doesn't reload the status. I have to manually invoke it.

![demo](https://user-images.githubusercontent.com/532797/112726848-68063d00-8f5a-11eb-8c32-837a8ececff3.gif)

**Comment by tpope** [comment]
Why does `Press ENTER or type command to continue` never show up?

**Comment by thisguychris** [comment]
I find it odd too, 

I tried doing an `!ls -al` and it does show `Press ENTER or type command to continue` This only happens on fugitive.

![demo](https://user-images.githubusercontent.com/532797/112727985-09dc5880-8f60-11eb-96e6-aaba6cb58dc8.gif)

**Comment by tpope** [comment]
I see what is happening. When the output pauses, there's a hidden `-- More --` prompt.  If you press space to continue paging through the output, the command successfully finishes and the status buffer reloads. If you press CTRL-C or q, it interrupts the command and you don't get a status reload. This makes perfect sense for CTRL-C, and I would say it's acceptable for q as well.

I am seeing an undesired behavior, though, in that it stops after 1 additional page, instead of continuing through the full list of 1655 files.

**Comment by thisguychris** [comment]
confirmed! Pressing `<space>` and/or `G`, after the output pauses shows the Press Enter to continue. If I see the prompt it does correctly reload. I got bit since it does hide the Enter prompt, and I usually just press `q` instead.

![demo](https://user-images.githubusercontent.com/532797/112729091-62fabb00-8f65-11eb-8429-416c991ebaa3.gif)

**Comment by tpope** [comment]
I'm pushing up a different echo implementation, keep an eye out for regressions.
