### ISSUE TITLE
Weird characters in :Gstatus view

### ISSUE THREAD

**Issue by pbakiewicz** [tpope/vim-fugitive#1718]
My vim-fugitive is up-to-date. I found that I have a problem with weird characters in my :Gstatus view under "Unpushed to origin/main" category.

![image](https://user-images.githubusercontent.com/7620176/112764499-22ed1400-9009-11eb-8ff4-058c96fb7353.png)

Not sure where even I should start debugging it?

**Comment by tpope** [comment]
Try disabling your `.gitconfig`. If it works, try to figure out which part was causing the problem.

**Comment by pbakiewicz** [comment]
Disabling `.gitconfig` did nothing. Maybe it it something to do with gathering terminal output. I found similar problem is with `vim-go` plugin which enables running go scripts and printing results. Here it should print "Hello World":

![image](https://user-images.githubusercontent.com/7620176/112765623-4797ba80-900e-11eb-8bbf-569ce5edd19d.png)

**Comment by tpope** [comment]
What is `:set shell? shellcmdflag?`? If you changed it, does it work with the default setting?

**Comment by pbakiewicz** [comment]
You are right. Problem wasn't connect with fugitive. I use `fish` and that shell was under `:set sh?`. Apparently neovim has some problem with parsing output from fish terminal.

FIX:
Just add `set shell=/usr/bin/bash` to your `init.vim`.

**Comment by tpope** [comment]
That's *probably* something in your Fish config, rather than Fish itself.
