### ISSUE TITLE
Many errors since last update

### ISSUE THREAD

**Issue by mosheavni** [tpope/vim-fugitive#1719]
I'm extremely sorry I cannot offer more details..
I upgraded fugitive to latest version, and when running `cc` inside git status (to commit), and when running `:G pull` and `:G push origin master` there were many errors in messages:
![image](https://user-images.githubusercontent.com/17252601/113000317-60bc7a80-9178-11eb-85ed-cb07d74169ce.png)

My local copy's commit hash: a1cb01da5b2c84ebfbe86a02bfb2e7ef9d830d50

I cannot reproduce and have no idea what caused it.
Thanks.

**Comment by tpope** [comment]
All these errors mention a plugin called `gitstatus`, not Fugitive. I suggest you start there.
