### ISSUE TITLE
G status in new buffer.

### ISSUE THREAD

**Issue by sperezconesa** [tpope/vim-fugitive#1720]
Hello,

The current behaviour (at least what I see) is that when I do `:G` I get a horizontal split with the results of the command. Would it be possible to open the results in a whole new buffer instead? Thanks a lot for your help and keep up the great work!!
Best,
Sergio

**Comment by tpope** [comment]
I don't know what you mean by "whole new buffer", but you can use `:Gsplit :` if you want to open the status a second time rather than reuse an existing window.

**Comment by sperezconesa** [comment]
Sorry, I'll try to explain myself better. When I call `:G` I get this:
![image](https://user-images.githubusercontent.com/27727343/113249013-4c829580-92be-11eb-97b5-257b5a60fdef.png)
But I would like to get this:
![image](https://user-images.githubusercontent.com/27727343/113249190-93708b00-92be-11eb-9c87-19ba06092ec0.png)
Is there a way to do this? Or a init.vim remap to get this result? Thank you very much!
Sergio

**Comment by tpope** [comment]
Use `:0G` or `:Gedit :`. These differ in what happens when you open a file from the status window, by pressing enter for example.

**Comment by sperezconesa** [comment]
Just what I was looking for! Thank you so much!

**Comment by gralco** [comment]
> Use `:0G` or `:Gedit :`. These differ in what happens when you open a file from the status window, by pressing enter for example.

@tpope Can the same be done when writing commit messages? Currently, if I do `:0G` then `cc` for a new commit, it will create a split rather than using the status window; in contrast to doing something like `:0G log` which does not create a split.

I'm looking for a method to have fugitive create a new window for writing the commit message, and not creating a split, preferably without even having to open the status window (e.g. with `:0G commit`).

**Comment by tpope** [comment]
Fugitive finishes the commit when you close the window. How do you do that when you only have one window open?

What happens if you try to commit while the current file has changes, and `'hidden'` is off?

**Comment by gralco** [comment]
> Fugitive finishes the commit when you close the window. How do you do that when you only have one window open?

When I do `:0G` the fugitive status takes over the window, then when I do `cc` it creates a split where I can write my commit message. If at this point I switch to the split with the fugitive status and close it via \<C-w>c, then the commit window becomes the focus and there is now one less split in my view. Once I've completed writing my commit by saving, if I switch my window to edit some file, or if I close the buffer used for writing the commit message, then I get my window back to the state it was in before having written the commit.

I would like to make the commit editor take over the window / split that was in focus when I perform `:0G commit`, without having to close the status split, in the same way `:0G log` behaves.

**Comment by gralco** [comment]
@tpope any suggestions?
