### ISSUE TITLE
Cannot commit with editor (e.g. without -m or -F)

### ISSUE THREAD

**Issue by JoeWoodward** [tpope/vim-fugitive#1721]
I've recently started using vim-fugitive, I normally supply my commit messages using the -m flag. I just tried to write a longer message so tried `:Git commit` which successfully opens the COMMIT_EDITMSG file, however, when I save and close the file a command is printed to the file instead of executed. It's this command here

https://github.com/tpope/vim-fugitive/blob/88f50bba604f353c21dea554bf9932ad5c76265e/autoload/fugitive.vim#L2695

If I'm currently within the git status window I see an error that the buffer is not modifiable, but if I'm in a normal buffer it prints that command into the buffer.

I have tried removing everything from my vimrc file, the only plugin installed is fugitive and still the same issue. 
Is there anything I can do to provide more information? 

M1 macbook air
macvim version 8.2.2576
minpac as package manager
latest version of vim-fugitive
.vimrc -
```
packadd minpac
call minpac#init()
call minpac#add('tpope/vim-fugitive')
```

**Comment by tpope** [comment]
What if you use the `/usr/bin/vim` that ships with macOS?
