### ISSUE TITLE
Add instructions for Neovim

### ISSUE THREAD

**Issue by olleharstedt** [tpope/vim-fugitive#1723]
The correct folder to install into for Neovim is: `~/.local/share/nvim/site/pack/tpope/start`. Can you update the README, please?

**Comment by Leeeooo19888** [comment]
> The correct folder to install into for Neovim is: `~/.local/share/nvim/site/pack/tpope/start`. Can you update the README, please?

**Comment by Leeeooo19888** [comment]
Yep

**Comment by olleharstedt** [comment]
:+1:

**Comment by nchase** [comment]
@olleharstedt as a Neovim user, I think the burden of understanding how to install a package that was written for vim should live with Neovim users (otherwise, everything will have to be explained twice). 

I recommend using a package manager for Neovim. 

For [Packer](https://github.com/wbthomason/packer.nvim), for instance, my vim-fugitive installation was very simple:  `use 'tpope/vim-fugitive'`

**Comment by olleharstedt** [comment]
> For [Packer](https://github.com/wbthomason/packer.nvim), for instance, my vim-fugitive installation was very simple: `use 'tpope/vim-fugitive'`

That's awesome. So awesome it should be part of the README. :D

**Comment by nchase** [comment]
Well @olleharstedt, the README currently says "Install using your favorite package manager, or ..."

I think this falls under the "favorite package manager" part 😄

**Comment by tpope** [comment]
We're also missing instructions for Windows. That brings the number of required variations to 4.

If anything I am starting to think the existing snippet should be removed. I don't want half the README to be installation instructions.  Maybe we could make a wiki page or something.

**Comment by tpope** [comment]
If someone wants to compile a list of popular package managers and installation instructions, that would help. Although it may be a while before I circle back on this.

Note I favor using `https://tpope.io/vim/fugitive.git` as the canonical source and not the corporate boot-licking shorthand that is `tpope/vim-fugitve`.

**Comment by gwerbin** [comment]
> The correct folder to install into for Neovim is: `~/.local/share/nvim/site/pack/tpope/start`. Can you update the README, please?

Note that Neovim also supports `~/.config/nvim/pack/*/start`. Vim has the same behavior but with `~/.vim`. IMO, you should let your plugin manager (if any) take care of `~/.local`, but manage `~/.config` yourself.

It also doesn't have to be `pack/tpope/start`, it could be `pack/aefawef12341343/start`.

For example:

```bash
#!/bin/sh

### Installation script for a Vim 8 or Neovim "package" ###
#
# CC0 license. To the extent possible under law, "gwerbin" has waived all
# copyright and related or neighboring rights to this script.


## User config ##

# This can be anything of the form:
#   - `pack/*/start`
#   - `pack/*/opt`
pack_dir = 'pack/git/start'

# Name of the package
pack_name='vim-fugitive'

# Git URL where the package is hosted
pack_git_url='https://github.com/tpope/vim-fugitive'


## Script ##

set -eu

if command -v nvim >/dev/null 2>&1
then
  vim_config_path = "${XDG_CONFIG_HOME:-$HOME/.config}/nvim"
else
  vim_config_path = "${HOME}/.vim"
fi

pack_dir_abs = "${vim_config_path}/${pack_dir}"
git_clone_dir = "${pack_dir_abs}/${pack_name}

echo "Cloning: ${pack_git_url}  ->  ${git_clone_dir}"

set -x

mkdir -p "$pack_dir_abs"
git clone "$pack_git_url" "$git_clone_dir"
```

**Comment by tpope** [comment]
> Note that Neovim also supports `~/.config/nvim/pack/*/start`. Vim has the same behavior but with `~/.vim`. IMO, you should let your plugin manager (if any) take care of `~/.local`, but manage `~/.config` yourself.

Hadn't thought about this before, but yes, this sounds right. That `site` should have been a big clue.

**Comment by kaddkaka** [comment]
> Note I favor using `https://tpope.io/vim/fugitive.git` as the canonical source and not the corporate boot-licking shorthand that is `tpope/vim-fugitive`.

What's the problem with the github shorthand? One upside is that my almost air-gapped workstation has proxy-access to `github.com` so I wouldn't want it to disappear :3

**Comment by tpope** [comment]
My problem is I don't want people to hard-code a URL I don't control. What happens if I want to change hosting providers?

Actually that's just my problem with a GitHub URL. The shorthand is much worse. Imagine if when email started getting popular, email clients started treating `username` as a shorthand for `username@hotmail.com`, since after all, that was the most popular email provider. That's how stupid and short-sighted having a shorthand for a popular hosting provider is.

**Comment by sevehub** [comment]
> We're also missing instructions for Windows. That brings the number of required variations to 4.
> 
> If anything I am starting to think the existing snippet should be removed. I don't want half the README to be installation instructions. Maybe we could make a wiki page or something.

Wouldn't be better just to expand the existing help pages? A text file in the doc folder (something like fugitive_install_windows.txt) might be sufficient.

**Comment by olleharstedt** [comment]
Using vim-plug worked for me, https://stackoverflow.com/a/75475437/2138090

Closing this.
