### ISSUE TITLE
commit buffers show without folding - bug or feature?

### ISSUE THREAD

**Issue by pavoljuhas** [tpope/vim-fugitive#1725]
I have noticed after 156dbcd738fbf997bfc996760d1f979a4496c746 commit buffers open with unfolded diff blocks and with `foldmethod=manual`.
Is this intentional?

```
$ vim --clean -c "set runtimepath+=$PWD | so plugin/fugitive.vim | Gedit HEAD"
```

I can restore folded commits by adding `after/ftplugin/git.vim` as follows, but having folding on by default was a bit more convenient.

```VimL
if exists('b:fugitive_type') && b:fugitive_type !=# 'blob'
    setlocal foldmethod=syntax
endif
```

**Comment by tpope** [comment]
Feature. Options like `'foldmethod'` are window local, not buffer local, so if you open a Fugitive buffer, then edit another file, that option stays on. Combine that the fact that syntax folding is sloooooooow for many file types, this had the potential to burn people pretty hard. In particular, it was burning me pretty hard when loading a big `:Git log`. So, it's opt-in now.
