### ISSUE TITLE
why revoked 'syntax' foldmethod?

### ISSUE THREAD

**Issue by Shane-XB-Qian** [tpope/vim-fugitive#1735]
perhaps had some reason to revoke that in some bufs, but it should be useful in 'commit' buf,
e.g one commit had multiple (fs) changes, then had-fold looks a bit clear than none-fold.
// though it can manually setl it in user side, just not sure why you revoked it, ok to recover? :)

**Comment by tpope** [comment]
`'foldmethod'` is _window_ local. That means if Fugitive sets it, and you edit a different buffer, it stays set. I've decided Fugitive shouldn't be causing side effects like this. But if you're okay with the side effects, feel free to take over:

```viml
autocmd User FugiitveCommit set foldmethod=syntax
```

**Comment by Shane-XB-Qian** [comment]
well, looks it's a common situation, e.g opened vimdiff -the/its foldmethod was 'diff', but it would reset to 'manual' if one compared buf leave that compared window..
// perhaps this can be done same like that?
// or normally looks few people would re-use same window which was opened for 'commit' buf.

**Comment by tpope** [comment]
Vim has special case `'foldmethod'` handling for `:diffoff`. We _could_ implement something similar, but doing it 100% reliably is way harder than you probably think.

And for the record, in the near future I plan to change commit buffers to behave like the status buffer, with `M filename.txt` lines that can be expanded/collapsed without using folding, rendering this moot.

**Comment by Shane-XB-Qian** [comment]
Well, if you say so.. But if let me choose about these two: the ‘status’ way and ‘commit’ way, then I personally probably preferred ‘fold’, since it had matured wheel already..
// but it actually did not impact too much, so up to you anyway.. :-)
