### ISSUE TITLE
Bare repo

### ISSUE THREAD

**Issue by Deshdeepak1** [tpope/vim-fugitive#1736]
I use git bare repo to manage my dotfiles. But fugitive isn't taking care of those files. 
Is there any workaround

**Comment by tpope** [comment]
Fugitive has bare repo support. You're gonna have to explain what "isn't taking care of those files" means.

**Comment by Deshdeepak1** [comment]
If I open ~/.vimrc with vim, it doesn't shows changes and other git commands don't work. My dot files bare repo is in ~/.dotfiles .

**Comment by tpope** [comment]
If you call `git diff .vimrc`, does it show changes? Do other git commands work?

**Comment by Deshdeepak1** [comment]
I will have to do 
config diff .vimrc ,
I have 
alias config = git --work-tree=~/ --git-dir=~/.dotfiles in fish config.

**Comment by ibhagwan** [comment]
@Deshdeepak1 if you’re using neovim >= v0.5 I came up with a solution to exactly this in #1981
