### ISSUE TITLE
Opening diff (using <CR>) on :Git log --patch -- filename doesn't work

### ISSUE THREAD

**Issue by faisal-shah** [tpope/vim-fugitive#1738]
Related to: https://github.com/tpope/vim-fugitive/issues/1222

1. View a log using :Git log --patch -- filename . This results in a tmp file being generated instead of the usual fugitive:// type of file.
2. The patch shows up properly, showing the differences.
3. Go to the diff line, and hit \<CR> .
4. The diff view shows up in splits - but shows no changes between the files. I checked the contents of the files, and they are both identical to output of git show \<second index hash>. 

If I use :Gclog and navigate to that commit, then hit \<CR> on the diff line of the same file specified above, the diff works and shows the differences. The diff line showing the path and the line below it with the two index hashes are identical to what happens above in the broken case. This is painful to use when there are lots of files in commits, and I'm only interested in one of them.

**Comment by tpope** [comment]
> 4. The diff view shows up in splits - but shows no changes between the files. I checked the contents of the files, and they are both identical to output of git show <second index hash>.

Forget the contents of the buffers. You've got 2 `fugitive://` buffers open now, what is the commit hash in each of them? I would expect one to be the commit hash of the diff you selected, and the other to be the ancestor of that commit.

Note the behavior you expect is not documented or guaranteed. Fugitive's `<CR>` here is basically a very long chain of `elseif` statements that look at the surrounding context and try to guess where you want to jump. But this particular case does work for me.

**Comment by faisal-shah** [comment]
The two fugitive:// buffers are as follows:

fugitive:///<path to git repo base>//<commit hash>/<path to file>
fugitive:///<path to git repo base>//0/<path to file>

I narrowed it down to my customized pretty formatter default. When I use the standard formats, with the exception of 'oneline' and 'reference', it works.

I have format.pretty = %Cred%h%Creset - %C(yellow)%d%Creset %Cgreen(%cr) %C(bold blue)<%an>%Creset%n%<(120,trunc)%s%n%n

**Comment by tpope** [comment]
Sounds like a wontfix? I'm not going to add another `elseif` just to accommodate literally one person's `.gitconfig`.

**Comment by faisal-shah** [comment]
> literally one

I asked the vim-flog maintainer to enforce the option --format=medium when using :Git show. However, this is a limitation of fugitive's ability to interpret the output of Git show. If fugitive can only successfully parse certain output log types - might as well enforce --format=medium or something of the such, no?

**Comment by tpope** [comment]
If a user cares about aesthetics more than `<CR>` then I don't think I should get in their way.

And for a plugin like vim-flog, nothing is stopping it from providing its own `<CR>`.

**Comment by faisal-shah** [comment]
> If a user cares about aesthetics more than `<CR>` then I don't think I should get in their way.
> 
> And for a plugin like vim-flog, nothing is stopping it from providing its own `<CR>`.

I understand where you're coming from. In my opinion if the current implementation of <CR> is unable to work with custom formats specified outside of the environment in which it is being used - then it makes sense to make it robust against such a thing by setting a default format when fugitive.vim invokes the log, show, and whatchanged commands (which are affected by the custom pretty format). This would make it more robust, with no downside to the user (or maintainer :) ).

**Comment by tpope** [comment]
The priority is that `:Git` should match `git` as closely as possible.

**Comment by faisal-shah** [comment]
> The priority is that `:Git` should match `git` as closely as possible.

That is your prerogative sir ... and thank you for your service :)
