### ISSUE TITLE
On `:Gpush` or `:G push` enable to view ssh message

### ISSUE THREAD

**Issue by korney4eg** [tpope/vim-fugitive#1741]
When pushing to GitHub/Lab new branch from terminal there is a message with some info and generated link to create Pull Request, it would be very nice to be able to save it, or show it somewhere to copy it to clipboard and open in browser.

**Comment by tpope** [comment]
You can use [`:Gedit -`](https://github.com/tpope/vim-fugitive/blob/32b0d6266361614a6a07cfe850750e900cd50575/doc/fugitive.txt#L592) to open a temp buffer with the last command's output.
