### ISSUE TITLE
:Git status behaviour

### ISSUE THREAD

**Issue by karakays** [tpope/vim-fugitive#1743]
Why does `:Git status` behave different than `:Gstatus`?

`:Git status` creates new window that contains the output but disappears away on any key press.

Whereas `:Gstatus` allows git operations in the window.

**Comment by tpope** [comment]
`:Git status` is literally `git status`, in the same way that `:Git add` is literally `git add`. `:Gstatus` started out based on `git status` but has evolved over time, to the point where the name is more confusing than helpful. For that reason, the functionality has been moved to `:Git` with no arguments, and `:Gstatus` itself is deprecated. It's a bit of a mess now, but when the deprecated commands are all removed, hopefully it will make more sense.
