### ISSUE TITLE
Can't open fugitive-map when pressing g?

### ISSUE THREAD

**Issue by chuan137** [tpope/vim-fugitive#1745]
What to expect: typing g? and help for mappings is opened in seperate window
What do I get: E21: cannot make changes, 'modifiable' is off

I am using neovim nightly build,  could be related?

**Comment by tpope** [comment]
Doubtful, but not impossible, that it is Neovim related.

* Check `:nmap g?`. You should see `:<C-U>help fugitive-map<CR>`.
* Make sure you are pressing both keys within one second of each other.

**Comment by chuan137** [comment]
> * Make sure you are pressing both keys within one second of each other.

thanks a million, this solved my problem
