### ISSUE TITLE
fugitive can't understand the hunk which delete lines prefix with `--` properly

### ISSUE THREAD

**Issue by kevinhwang91** [tpope/vim-fugitive#1747]
I delete below code and give you two different screenshots:
In fugitive index:
![image](https://user-images.githubusercontent.com/17562139/117942760-ffbebf80-b33d-11eb-8076-d06b5c3a25b3.png)
`---` regard as `DiffAdd` and `DiffText`

delta in shell:
![image](https://user-images.githubusercontent.com/17562139/117943489-c2a6fd00-b33e-11eb-81fc-cd6069ec0984.png)

**Comment by tpope** [comment]
This is just a syntax highlighting issue? I can fix it by being more selective in which parts of `syntax/diff.vim` we use, but watch out for unintended consequences.

**Comment by kevinhwang91** [comment]
Great job!
