### ISSUE TITLE
Out of sync diffs after Gvdiffsplit

### ISSUE THREAD

**Issue by phelipetls** [tpope/vim-fugitive#1750]
After running `:Gvdiffsplit`, lines are not in sync sync due to an extra folded line.

I recorded it [here](https://asciinema.org/a/xF0g5VUdtVHCC96SowVKboIOV).

When I run `:redraw!`, that folded line disappears. I'm not sure what's the fix for this, maybe to add `let post = post . "redraw!"`?

**Comment by tpope** [comment]
Can you narrow down the conditions required to reproduce? I've never seen this.

**Comment by phelipetls** [comment]
I can reproduce this in my machine inside the file `plugin/fugitive.vim` by insertin a line above line 70 and calling `Gvdiffsplit`.

In Neovim, I reproduced it by running `nvim +70 plugin/fugitive.vim -u NONE -c 'packadd vim-fugitive' -c 'normal! Oecho'` and then using `:Gvdiffsplit`, the problem does not happen if I run it with the `-c` flag.

I tried to reproduce it in Vim and the same thing happens, at least on my machine.

**Comment by phelipetls** [comment]
The issue seems to go away (in this particular case) if I comment out this redraw:

```diff
diff --git a/autoload/fugitive.vim b/autoload/fugitive.vim
index 2f298f0..fcd3305 100644
--- a/autoload/fugitive.vim
+++ b/autoload/fugitive.vim
@@ -5453,7 +5453,7 @@ function! fugitive#Diffsplit(autodir, keepfocus, mods, arg, args) abort
     endif
     execute mods 'diffsplit' s:fnameescape(spec)
     let &l:readonly = &l:readonly
-    redraw
+    " redraw
     let w:fugitive_diff_restore = restore
     let winnr = winnr()
     if getwinvar('#', '&diff')
```

But I can't explain why.

**Comment by tpope** [comment]
I can reproduce, and just independently arrived at the same conclusion about `redraw`. That `redraw` was added 01cda4d4432cbec9c580411d6afce2b0d1899439, presumably to fix a different render issue, but whatever that issue was is lost to time. I'll remove it for now and see if any other issues surface.
