### ISSUE TITLE
Close buffer after :Git add --patch?

### ISSUE THREAD

**Issue by hejops** [tpope/vim-fugitive#1752]
Is there a setting/function that can be used to close the new buffer that is populated with the output of a `Git add --patch`? I tried messing around with the simple function below, but `bd` appears to be called at the same time (?) as `Git add --patch`.

```
function! GitAddPatch()
	Git add --patch %
	bd
endfunction
```

(Is there a vimscript equivalent to shell's `command1 && command2`?)

**Comment by tpope** [comment]
It's calling `:terminal` which is asynchronous. I don't know of a good way to run a command afterwards, but if one exists, it probably involves autocommands.

**Comment by odnoletkov** [comment]
@tpope can we add `++close` to the `:terminal` invocation for these `--patch`/`--interactive` commands? It seems to work fine – closes the terminal window properly and status buffer is reloaded as expected.

**Comment by tpope** [comment]
It closes the terminal window without giving you a chance to see what's in it. If there's an error, you can't read the message. It's completely unusable.

**Comment by odnoletkov** [comment]
I thought `--patch` and `--interactive` type of commands resolve all errors inside the interactive session. For example if I try to edit a hunk manually and screw up it would show the error inside the interactive session and ask for choice again. I don't recall seeing any useful output or errors after the interactive session is over, but maybe I'm missing some use case?

**Comment by tpope** [comment]
What if you passed an invalid argument? What if Git crashes?
