### ISSUE TITLE
Git blame format option

### ISSUE THREAD

**Issue by kevr** [tpope/vim-fugitive#1753]
Hi vim-fugutive.

Thanks a lot for your work, tpope and contributors; this tool is absolutely awesome. I'd like to reduce the width of the `:Git blame` buffer to purely commit hashes, so I can fit more of them into my desktop layout.

Is there already a way to modify its format easily? If not, are you guys open to one?

Thanks for your time and attention!

**Comment by tpope** [comment]
`:Git blame` supports the same options as `git blame`. Try `:Git blame -s`, for example.

**Comment by kevr** [comment]
Gotcha. Thanks, tpope!
