### ISSUE TITLE
Git blame for multiple vim windows

### ISSUE THREAD

**Issue by kevr** [tpope/vim-fugitive#1754]
Hello, vim-fugitive.

I'd love to be able to open up a `:Git blame` for multiple windows in my vim instance, so I can look at some files and their blaming side by side for easier comparison.

Is there a particular reason that `:Git blame` only uses one window?

I have noticed that `:Git diff ...` allows a user to open up as many diff buffers as they would like.

Thoughts?

Thanks!

**Comment by tpope** [comment]
This is a limitation of how `'scrollbind'` works. If you had 2 files blamed simultaneously, all 4 buffers would be forced to display the same line number. This is somewhere between "unhelpful" and "confusing", so instead we close the old blame when opening the new one, as a less bad (imo) alternative.

**Comment by tpope** [comment]
Note that if you don't need the split view, you can call `:Git blame <filename>` to open as many blame buffers as you like.

**Comment by kevr** [comment]
Gotcha. Thanks, tpope!
