### ISSUE TITLE
:Gdiff does not find the reference file when \ is not doubled in isfname on Windows

### ISSUE THREAD

**Issue by elmotec** [tpope/vim-fugitive#1762]
Hello,

Just an FYI. Great plugin. Thank you.

I had the following problem on Windows 10. When I run `:Gdiff`, fugitive opens a buffer with the following 2 paths:
```
:buffers
  1  a   "vimfiles\vimrc"               line 0
  2 %a   "fugitive:\C:\Users\...dotfiles\.git\0\vimfiles\vimrc" line 1
```
The first buffer is the original working file, the second I suppose should be the reference file but there was nothing in .git\0. I am not sure how the fugitive:// url is supposed to be resolved. Today I decided to sort it out by removing lines from my .vimrc.

It turns out that the isfname was the culprit as I had redefined it a long time ago to add curly braces as (can't remember why exactly, probably has to do with `${envvariable}`):
```
set isfname=@,48-57,/,\,.,-,_,+,,,#,$,%,{,},[,],:,@-@,!,~,=
```
It should have been removed or defined as:
```
set isfname=@,48-57,/,\\,.,-,_,+,,,#,$,%,{,},[,],:,@-@,!,~,=
```

The tough part is that I did not see any warnings or errors, the backslash is not doubled in the vim doc, and I did not have issues elsewhere. I don't know if it's an issue with fugitive because I don't understand the issue in the first place but maybe it helps someone in the future, maybe you understand what's going on can add a warning or something.

Thanks again.

**Comment by tpope** [comment]
Try this command with both the good and bad values of `'isfname'` and report back what you get in each case:

```vim
echo fnameescape('fugitive:\\C:\Users')
```

**Comment by elmotec** [comment]
Sorry, the old value of `isfname` did _not_ have the baskslash at all, it was as show below. To answer your question:

with `set isfname=@,48-57,/,.,-,_,+,,,#,$,%,{,},[,],:,@-@,!,~,=` (breaks `:Gdiffsplit`)
```fugitive:\\C:\Users```
with `set isfname=@,48-57,/,\\,.,-,_,+,,,#,$,%,{,},[,],:,@-@,!,~,=:` (`:Gdiffsplit` works fine)
```fugitive:\\C:\Users```

I guess it's not super helpful.

**Comment by tpope** [comment]
That rules out one hypothesis. My other guess would be to try the following with both settings:

```vim
diffsplit fugitive:\\C:\Users\...dotfiles\.git\\0\vimfiles\vimrc
```

Be sure to replace `...` with the real path, and include both sets of double backslashes. (The fact there's no double backslashes in your `:buffers` output is the crux of the problem.) My guess is that the double backslashes disappear when `isfname` is wrong.

**Comment by elmotec** [comment]
Spot on. In both case I run:
```diffsplit fugitive:\\C:\Users\...dotfiles\.git\\0\vimfiles\vimrc```

With \\ in isfname, the buffers become:
```diffsplit fugitive:\\C:\Users\...dotfiles\.git\\0\vimfiles\vimrc```
Without:
```diffsplit fugitive:\C:\Users\...dotfiles\.git\0\vimfiles\vimrc```

**Comment by tpope** [comment]
Alright, I think that makes this a wontfix. If Vim is misconfigured in a way that breaks basic argument parsing, there's not much I can do except try to check for this very specific mistake and raise an error. And we do this sort of thing all over the plugin, so there's not even a great place to do that.

For future reference, one backslash in `'isfname'`, as seen in the help, is correct. You need to double the backslash because of the way `:set` parses arguments. See `:help option-backslash`. But in this case, you should `:set isfname+={,}`, because hard coding the full value will get you into trouble if you try to use that same vimrc on another platform.

**Comment by elmotec** [comment]
Ok. thanks for the help getting to the bottom of this.
