### ISSUE TITLE
Error trying to discard staged hunks

### ISSUE THREAD

**Issue by lourenci** [tpope/vim-fugitive#1765]
Were there any breaking changes recently? I've got the feeling I could discard a hunk directly from the staged area. Now, I get the below error. This is not happening from the unstaged area.

<img width="760" alt="image" src="https://user-images.githubusercontent.com/2339362/120203219-daff8e80-c1fd-11eb-84d8-24ac6daf3e3b.png">

**Comment by tpope** [comment]
No recent relevant changes I can think of. I'm assuming this is correct. Feel free to prove me wrong by finding an old commit that works.
