### ISSUE TITLE
cannot push when using gpg subkey as ssh agent

### ISSUE THREAD

**Issue by ranjithshegde** [tpope/vim-fugitive#1766]
I use a gpg key for ssh access/authentication. I use the same key to sign all my commits.
When I work with a repo, commit the changes and push it from any terminal emulator or a TTY, I have no problems.
But when i try to do the same using fugitive` G push` I get the following error 

```
no such identity: /home/ranjith/.ssh/id_rsa: No such file or directory
git@gitlab.com: Permission denied (publickey,keyboard-interactive).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
I have ssh-auth-sock set up like this in my zshrc. 
```
unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi
```
I have tried putting it in my bashrc and in my /etc/environment and have had the issue where fugitive only looks in .ssh dir

What am I doing wrong? Or what am I missing?
On neovim 0.5, if that is relevant

**Comment by tpope** [comment]
Obvious first question is whether `SSH_AUTH_SOCK` is set inside Vim? Check `:echo $SSH_AUTH_SOCK`.

**Comment by ranjithshegde** [comment]
@tpope of course. It points to env-var as declared in bashrc

**Comment by tpope** [comment]
> `no such identity: /home/ranjith/.ssh/id_rsa: No such file or directory`

What is this error? SSH doesn't complain about a missing `id_rsa` by default. Does this happen in your successful terminal based pushes?

> `git@gitlab.com: Permission denied (publickey,keyboard-interactive).`

What is `keyboard-interactive`? `ssh_config(5)` says you opt into it with `KbdInteractiveAuthentication` but gives little other context. Is this part of your whole GPG key setup or a red herring? If it's the latter I'd be inclined to disable it for the time being just to eliminate it as a spanner in the works.

**Comment by ranjithshegde** [comment]
> What is this error? SSH doesn't complain about a missing id_rsa by default. Does this happen in your successful terminal based pushes?
The same commit gets pushed from the terminal when it fails in nvim. It even pushes from a vim terminal buffer. Just not from G commands

> What is keyboard-interactive? ssh_config(5) says you opt into it with KbdInteractiveAuthentication but gives little other context. Is this part of your whole GPG key setup or a red herring?

It is just a gpg subkey with only authentication ability turned on. I havent seen any option for KbdInteractiveAuthentication. Unless gpg inherently has that as a feature (I dont know), I havent enabled it from my end

**Comment by tpope** [comment]
> > What is this error? SSH doesn't complain about a missing id_rsa by default. Does this happen in your successful terminal based pushes?
> 
> The same commit gets pushed from the terminal when it fails in nvim.

That wasn't my question. I was asking if the non-fatal error message `no such identity: /home/ranjith/.ssh/id_rsa: No such file or directory` shows up when you successfully push.

> 
> > What is keyboard-interactive? ssh_config(5) says you opt into it with KbdInteractiveAuthentication but gives little other context. Is this part of your whole GPG key setup or a red herring?
> 
> It is just a gpg subkey with only authentication ability turned on. I havent seen any option for KbdInteractiveAuthentication. Unless gpg inherently has that as a feature (I dont know), I havent enabled it from my end

This isn't a GPG option. It would be found in `~/.ssh/config` or `/etc/ssh_config` (or wherever your distro puts it).

A bigger, more important question: Does successfully pushing involve inputting a password or any other active interaction?

**Comment by ranjithshegde** [comment]
> That wasn't my question. I was asking if the non-fatal error message no such identity: /home/ranjith/.ssh/id_rsa: No such file or directory shows up when you successfully push.

Apologies for the misunderstanding. No the error does not show up on terminal successful pushes.

> This isn't a GPG option. It would be found in ~/.ssh/config or /etc/ssh_config (or wherever your distro puts it).

I have no option to do with interactivity in either of those documents

> A bigger, more important question: Does successfully pushing involve inputting a password or any other active interaction?

My login keyring unlocks /(authenticates?) gpg-agent. So i have never had to type in my password.

I just disabled the login keyring unlocking gpg to see if I am asked for a password interactively when its still locked. 
It does not ask for password by I am thrown part of the above error that relates to not being able to access the repo
```
git@gitlab.com: Permission denied (publickey,keyboard-interactive).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by tpope** [comment]
I'm not seeing any obvious clues as to what's going wrong. My recommended next step would be to `export GIT_SSH_COMMAND='ssh -v'` and see if you spot any suspicious differences in the verbose SSH output between terminal and Fugitive usage. You can also try `-vv`, `-vvvvv`, etc.
