### ISSUE TITLE
Error on `:G diff`, `:G branch` 

### ISSUE THREAD

**Issue by BertrandSim** [tpope/vim-fugitive#1767]
I experience the following error messages when running the following git commands through `:G`.
* `:G diff`
* `:G diff --cached`
* `:G branch`

```
Error detected while processing function <SNR>4_BMRemove:
line    9:
E329: No menu "VILD649.tmp 2^>^&&1) (9)	!C:\WINDOWS\sys...ppData/Local/Temp"
Error detected while processing function fugitive#Command[177]..<SNR>48_RunFinished:
line    5:
E484: Can't open file C:/Users/Bertrand/AppData/Local/Temp/VILD649.tmp
```

(`VILD649.tmp` could be replaced by another temporary file name)

While the three commands listed above trigger the error, I suspect that there are other commands which result in the same error.

By contrast, running `:term git diff`, `:term git diff --cached`,  `:term git branch` shows the expected output from git.

**Comment by tpope** [comment]
That first error is from a runtime file included with Vim. Invoke `:edit $VIMRUNTIME/menu.vim`, search for `s:BMRemove`, and tell me what the contents of that function are. I checked my own copy and line 9 is just `endif`, so I assume you have a different version.

While you're at it, please share the exact version and patch level of Vim your are using, as seen in `:version`.

**Comment by BertrandSim** [comment]
Thanks for the reply. Here are the contents:

```
func! s:BMRemove()
  if s:bmenu_wait == 0
    let name = expand("<afile>")
    if isdirectory(name)
      return
    endif
    let munge = <SID>BMMunge(name, expand("<abuf>"))
```

I'm using (g)vim 8.1.1424, on windows
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 11 2019 23:02:19)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-2424
Compiled by appveyor@APPVYR-WIN
```

**Comment by BertrandSim** [comment]
Update: I also tried with gvim 8.2.1970 windows 64-bit. 

The first error is gone, but the second error persists.

**Comment by tpope** [comment]
```vim
      exe 'silent! aun &Buffers.' . munge
```

This is line 9 from that function, which suggests that `silent!` isn't actually silencing errors? Smells like a Vim bug, but if it's working after an upgrade I guess it's moot.

What is `:set shell? shellcmdflag?`? That `2^>^&&1` in the first error makes me think something is wrong with Vim's shell configuration.

**Comment by tpope** [comment]
Oh, and can you try `:set guioptions-=!` and see if that fixes it?

**Comment by BertrandSim** [comment]
> This is line 9 from that function, which suggests that `silent!` isn't actually silencing errors? Smells like a Vim bug, but if it's working after an upgrade I guess it's moot.

Agreed, to me, the first error is not of primary concern. 

> What is `:set shell?` `shellcmdflag?`

`'shell'` is `C:\WINDOWS\system32\cmd.exe`, `'shellcmdflag'` is `/c`. These are windows defaults. 

> Oh, and can you try `:set guioptions-=!` and see if that fixes it?

That removes the error... I wouldn't call it a 'fix' though.

**Comment by BertrandSim** [comment]
I have also `'shellslash'` set (ie. `set shellslash` in my vimrc). Other 'shell*' options are unchanged.

**Comment by SamOng553996** [comment]
BertrandSim ***@***.***> 於 2021年6月8日 週二 11:08 寫道：

**Comment by BertrandSim** [comment]
Late to reply, but thanks for the fix @tpope ! Much appreciated.
