### ISSUE TITLE
Git log fails on Windows

### ISSUE THREAD

**Issue by mrdubya** [tpope/vim-fugitive#1768]
Only recently started using the fugitive plugin, works a charm on my various unix systems, not so well on Windows though. The main git status works ok (if a bit slow, but I can live with that) but for starters access the git log isn't working.

When I do `Gclog` in gvim there is a pause before the quickfix window opens but all it has is a single empty line. The output of :messages doesn't report anything.  Doing the same in console vim it shows the following in the quickfix window (yep, that is all I get to see):
```
fatal: ambiguous argument '%h': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
```
From a little spelunking around it looks like the problem is with the pretty format in used in `fugitive#LogCommand()`.  I get the same error reported from the command line using `git log --pretty=format:fugitive %h %P\t%H %s`  The command succeeds if the format string is quoted - `git log --pretty="format:fugitive %h %P\t%H %s"`. Hacking the function to add quotes now gets a log but not in the right form so there is more going on here. The output from `Gclog` is now like the following:
```
|| fugitive 4196099 8886d97070cf72c11749301d8e30439dd3600d13 41960996e0c532069533072b3fd820fafe9ce0b3 Eliminate unnecessary redraw to clear up :Gdiffsplit sync issue
```

FWIW `:Git log -20` produces normal log output but I do get more vim errors when I select a commit hash:
```
Error detected while processing BufReadCmd Autocommands for "fugitive://*//*":
fugitive: Missing closing ')' in expression.^@    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException^@    + FullyQualifiedErrorId : MissingEndParenthesisInExpression^@ ^@
```
Vim opens a window for the commit but it is also empty.

I am using Windows 10, latest Git for windows, Gvim recent build, powershell, and current (as of today) fugitive plugin source.

**Comment by tpope** [comment]
What is `:set shell? shellcmdflag?`?

What do you get if you call `:echo shellescape("--pretty=format:fugitive %h %P\t%H %s")`?

**Comment by mrdubya** [comment]
```
shell=PowerShell
shellcmdflag=-NoProfile -ExecutionPolicy RemoteSigned -NoLogo -NonInteractive -Command
```
and
```
"--pretty=format:fugitive %h %P %H %s"
```

**Comment by tpope** [comment]
The argument list you found is passed to `s:QuickfixStream()`, which calls `s:shellesc()` on it, which in turn calls `shellescape()` on each individual argument. Since it appears `shellescape()` is correctly surrounding with double quotes, my guess would be that they are getting butchered somehow when passed to PowerShell. Try this, and report back the result:

```vim
:echo system('git log -1 ' . shellescape("--pretty=format:fugitive %h %P\t%H %s"))
```

**Comment by mrdubya** [comment]
Vim produces no output for the echo command you asked me to try.  However the following does produce output:
```
echo system('git log -1 ' . shellescape("\"--pretty=format:fugitive %h %P\t%H %s\""))
```
Is this a case of quotes being stripped as the string is being passed down through calls so need to be doubled up?

**Comment by tpope** [comment]
> Is this a case of quotes being stripped as the string is being passed down through calls

Looks like it.

> so need to be doubled up?

No, I don't think the solution is to throw more quotes at it till it works. Other users use PowerShell just fine, so my leading hypothesis is something else is wrong with your config. How did you opt-in to PowerShell? Are you setting those 2 shell options in your vimrc? Are you setting any other shell options in the process?

**Comment by mrdubya** [comment]
This is what I have in my vimrc:
```
if has("win32")
  if executable("PowerShell")
    " Set PowerShell as the shell for running external ! commands
    " https://stackoverflow.com/a/33745531
    set shell=PowerShell
    set shellcmdflag=-NoProfile\ -ExecutionPolicy\ RemoteSigned\ -NoLogo\ -NonInteractive\ -Command
    set shellquote=\"
    " shellxquote must be a literal space character.
    set shellxquote= 
  endif
endif
```
Checking all shell related settings reports the following:
```
set shell? shellcmdflag? shellpipe? shellredir? shellquote? shellxquote? shellxescape? shellslash? 
  shell=PowerShell
  shellcmdflag=-NoProfile -ExecutionPolicy RemoteSigned -NoLogo -NonInteractive -Command
  shellpipe=>
  shellredir=>
  shellquote="
  shellxquote=
  shellxescape="&|<>()@^
noshellslash
```
I have changed `s:SystemError()` to echo what is being passed to `system()`. With the above settings it is using the following string:
```
'git --no-pager -c "diff.context=0" -c "diff.noprefix=false" log --no-color --no-ext-diff "--pretty=format:fugitive %h %P      %H %s"'
```
If I do `set shellslash` then this changes to the following:
```
'git --no-pager -c ''diff.context=0'' -c ''diff.noprefix=false'' log --no-color --no-ext-diff ''--pretty=format:fugitive %h %P %H %s'''
```
This stops the git error occurring and fills the log window, but with lines like the following:
```
|| fugitive 4196099 8886d97070cf72c11749301d8e30439dd3600d13 41960996e0c532069533072b3fd820fafe9ce0b3 Eliminate unnecessary redraw to clear up :Gdiffsplit sync issue
```
So a step forward in getting git output, but next issue is the plugin not dealing with the output as expected.

I'll trawl back through previous issues related to powershell to see if anything seems related or if this is something new.

**Comment by mrdubya** [comment]
The issue with the log output with `set shellslash` is that `matchlist()` in `LogParse()` fails to match any of the lines.  My guess at this stage is that the tab between the full commit and parent hashses has been replaced with a space somewhere in the command execution pipeline.

Ok, plan B, change the pretty format strings in LogCommand to use hex sequences for the whitespace. That gets a log listing but VIM now reports:
```
Error detected while processing BufReadCmd Autocommands for "fugitive://*//*":
fugitive: failed to run ` (git -C E:/users/mikew/vimfiles/bundle/vim-fugitive --literal-pathspecs -c 'diff.noprefix=false' show --nocolor -m --first-parent '--pretty=format:tree%x20%T%nparent%x20%P%nauthor%x20%an%x20<%ae>%x20%ad%ncommitter%x2%cn%x20<%ce>%x20%cd%nencoding%x20%e%n%n%s%n%n%b' be9ff95f27d12b7bd46ab5d36f7149cb0864c329 > D:/temp/V1TFA54.tmp) ` with shell=PowerShell shellcmdflag=-NoProfile -ExecutionPolicy RemoteSigned -NoLogo -NonInteractive -Command shellredir=> shellquote=" shellxescape="&|<>()@^ shellslash=1
```
And so it continues ...

**Comment by tpope** [comment]
```vim
    " shellxquote must be a literal space character.
    set shellxquote= 
```

Despite what the comment says, this sets `shellxquote` to an empty string. The stackoverflow answer you copied this from is clearly bogus and you should toss it out and start over.

**Comment by mrdubya** [comment]
Fair point. It has been there a while after cargo culting off the interwebs. To date I have not been a heavy user so no problems appeared - until now. A bit of googling shows confusion on what settings to use for many years, with many solutions to get around problems experienced.

Investigating the effect and interaction of the various shell variables in the latest VIM (8.2.2984) leads me to the following in my vimrc for sane (for now) powershell command behaviour (e.g. for filters such as `%!xxd`):
```
if has("win32")
  if executable("PowerShell")
    set shell=powershell
    set shellcmdflag=-NoProfile\ -Command
    " Override VIM default to capture stderr as well
    set shellredir=>%s\ 2>&1
    set shellpipe=>%s\ 2>&1
    " Force shellescape() to use ' around powershell arguments
    set shellslash
  endif
endif
```

The various shell variable defaults work for cmd.exe or unix shell like shells but not powershell (e.g `help shellquote` talks about shell containing `sh` somewhere, so you would expect using `shell=powershell` would affect it, but VIM actually checks that the shell ends with `sh`). There seems to be gaps in VIM's shell implementation on Windows in order to support using powershell.

To pass powershell arguments with whitespace requires quoting them in `'` quotes. Alternatively they can be escaped with backticks (yep a different escape character to cmd.exe) and then `"` can be used. Or doubling the types of quotes but that requires scripts to do way more than they should be required to do, as you have said ;). Basically what works for for cmd.exe fails with powershell and vice versa which will make life fun.

`shellescape()` only produces valid shell arguments (enclosed in `'`) for powershell when `shellslash` is set. This is a none obvious setting for using powershell and it may be better for VIM to have some other way of using `'` from `shellescape()`.

I retried the plugin with the above shell configuration and it still fails. `:Gllog` fills the location list buffer with UTF-16 encoded log output, including the leading BOM. This is normal for stdout output using powershell. This is why you will see some suggesting setting `shellredir` to something like `| out-file -encoding default %s` but that loses stderr. The rabbit hole is deep.

At this stage using fugitive with powershell as the VIM shell is a bust. It may have worked in the past, with different VIM behaviour, plugin behaviour (nice to see one actively developed for more than 10 years!), or versions of powershell, but as of today it does not. I'll keep digging to see what I find out, plus I'll try and get some changes in VIM to improve powershell support out of the box.

**Comment by tpope** [comment]
You might want to try the config from #1644. Issues like that are the reason I concluded PowerShell could be made to work with Fugitive, but I think you're probably right that the rabbit hole goes much deeper than that.

I'm currently in the process of transitioning from `system()` and `:!` to jobs. Jobs can avoid the shell entirely so finishing that transition should render PowerShell problems obsolete. Unfortunately this transition is its own rabbit hole.

**Comment by mrdubya** [comment]
Ah, the fun of having two versions of PowerShell which behave differently - I haven't used PowerShell Core so exactly what the differences are is unknown to me.

I tried the `Out-File` version of `shellredir` with fugitive, and using `-encoding Default` the plugin seems to be working (still needs `shellslash` for correct argument escapng). Using UTF8 has problems due to the BOM appearing. However, using `Out-File` breaks filter commands so I am damned if I do and damned if I don't use this version of `shellredir`.

Sadly I'll have to fall back to cmd.exe for consistent VIM behaviour until things improve. Thanks for your time.

**Comment by mrdubya** [comment]
FTR there seems to be problems from having to set `shellslash` - the staged and unstaged counts are out by 1 and there are errors looking up entries with file names with forward slashes.
