### ISSUE TITLE
Indistinctive tab (and possibly buffer) names

### ISSUE THREAD

**Issue by heroin-moose** [tpope/vim-fugitive#1769]
Currently each command that stores the result in a temporary buffer (e.g. `Git log` or `Git diff`) gets a pretty indistinctive tab name like "5" or "14" that is derived from a temporary file name. I suggest giving them a proper name like

* [Git Status]
* [Git Log]
* [Git Diff]

and so on. For example, this is already kinda done for a blame window (it's tmpfile is named `N.fugitiveblame`). However for other commands I propose to create a tmpdir with a file inside to give more friendly look (IMO `[Git Log]` looks better than `14.fugitivelog`, but that's of course is up for a debate).

**Comment by tpope** [comment]
Normally these buffers have ugly names that look like `/tmp/vCZciGY/123`, which would correspond to a tab label like `/t/v/123`. The short version suggests to me you've either tweaked the default tab label, or you're using `'autochdir'` or an equivalent plugin. Your proposed change, then, would appear to most people as `/tmp/vCZciGY/123/[Git Status]`, which is nominally more informative but absolutely hideous in my book.

But that's just a rebuttal to your specific proposal. Something like `/tmp/vCZciGY/123.fugitivelog` would be aesthetically acceptable, or we could even bikeshed it a bit into something a bit prettier like `/tmp/vCZciGY/123/fugitive-log`. This does open a can of worms though. If I have a Git alias called `recent` that calls `git log @{upstream}..@`, should the buffer name look like `123.fugitiverecent` or `123.fugitivelog`? What's the buffer name for `:Git --paginate --help`? I am inclined to omit the command from the buffer name to sidestep issues like this, but that does reduce the value of such a change. I'm probably not going to act on this in the near future, but it may get revisited next time there's a big overhaul to how these temp buffers work.

Note that a determined user can generate their own tab label without my help. `FugitiveResult()` returns a dictionary for temp buffers that contains keys like `args` encapsulating what command was run. Try `:echo FugitiveResult()` in a Fugitive temp buffer and you will see what I mean. You can use this in a custom `'tabline'` or `'guitablabel'` to make it look however you like.
