### ISSUE TITLE
MacOS: commit stops working after vim has been running for a long time

### ISSUE THREAD

**Issue by justusthane** [tpope/vim-fugitive#1770]
First of all, I've been a huge fan of your plugins for years. You're doing the lord's work and you're my hero, Tim.

I searched through the issues for this before posting and didn't find anything, so perhaps it's just something weird with my machine. It seems like it would be fairly widespread otherwise. Apologies if that's the case.

Anyway, after vim has been open for an extended period of time (e.g. days), I start receiving the following error whenever I attempt to commit via Fugitive:

```
sh: /var/folders/xf/p072w5cn7xd57zcg5ng5dlq80000gn/T/vVesgoD/9.sh: No such file or directory
error: There was a problem with the editor 'sh /var/folders/xf/p072w5cn7xd57zcg5ng5dlq80000gn/T/vVesgoD/9.sh'.
Please supply the message using either -m or -F option.
```

If I either restart Vim, or simply recreate the file referenced above with the following contents, it works again.
```bash
#!/bin/sh
[ -f "$FUGITIVE_TEMP.exit" ] && exit 1
echo "$1" > "$FUGITIVE_TEMP.edit"
printf "\033]51;fugitive:edit\007"
while [ -f "$FUGITIVE_TEMP.edit" -a ! -f "$FUGITIVE_TEMP.exit" ]; do sleep 0.05 2>/dev/null || sleep 1; done
exit 0
```

Having to quit Vim and lose my buffers was kind of a pain, but since discovering the workaround above it's been downgraded to a very mild annoyance. Just curious if you have any thoughts!

Thanks!

**Comment by tpope** [comment]
Are you on the latest version? This was resolved in #1616.
