### ISSUE TITLE
Vim: Gstatus updates only after saving the index copy

### ISSUE THREAD

**Issue by gmnr** [tpope/vim-fugitive#1771]
I use `Gdiffsplit` to stage hunks of a modified file.
I have read some closed issues about the behaviour change in `Gstatus` that now reloads the changes upon focus rather than upon save.

My problem is that the only changes that `Gstatus` updates are those on the index copy and not the working copy.
Therefore, considered that the default behavious of `Gdiffsplit` puts you into the working copy I use this workflow:

* I have to use the difftools on the working copy (`do` or `dp`)
* move to the index copy (`<C-w>h`) and save (`:w`)
* move to the `Gstatus` window (`<C-w>k`) to update the staging area and commit the hunks

Am I doing something wrong? Is there a way to save both the working copy and the index copy with the same command?

Thank you in advance!

**Comment by tpope** [comment]
The way I would do it would be to `:w` before calling `:Gdiffsplit`. But if you want to save in batch, `:wa` seems like a good solution.
