### ISSUE TITLE
[Question] Browse files changed by a commit

### ISSUE THREAD

**Issue by Irubataru** [tpope/vim-fugitive#1773]
I really love the summary view of fugitive, is there a way to get something like that for commits or commit ranges? The two features I am specifically looking for is
1. Have an interactive list of files I can click (mostly so I can do a diff of what the commit changed)
2. The list of files should be static, i.e. if I click a file it opens in a different window/pane.

So far I have tried
1. Opening the commit object. However this also contains the diffs so navigating to files is inconvenient. Also, clicking a file opens it in the current window and therefore it's hard to quickly browse the various changes I made.
2. `Gclog --name--only`. This gets the list of files in the quickfix window, but the list isn't interactive.

I feel like there's something I'm missing because I assume browsing changes made by a commit is a fairly common scenario.

**Comment by tpope** [comment]
My long term goal is to change the commit object to look and behave similar to the summary view. Until that happens, you can use `foldmethod=syntax` to collapse the diff, a bit clumsy but generally good enough.

I don't understand your use of the verb "clicking" - clicking the mouse doesn't do anything - but you can open the file under the cursor in a new window with `o`.

**Comment by Irubataru** [comment]
Thanks, I'm looking forward to that change.

I was also thinking that "clicking" didn't sound right while writing it but writing "pressing enter on" just made the sentences a bit clunky. It seems to have conveyed my intention though, so I it worked. Thanks for the `o` tip though, together with folding I should be able to pretty much replicate my desired workflow.

**Comment by jamesob** [comment]
Are there any follow-up issues or features planned for this? I'd love to be able to jump right into vimdiffs when browsing hunks under a particular commit - this would be awesome for code review.

If nothing is underway at the moment, I could schedule some time to take a crack at implementing. This would have fugitive absorb my workflow of having `git log | head -n` in one terminal, and then using `PAGER=bat git show <commit>` in another to do code review.

**Comment by tpope** [comment]
Not explicitly called out but it falls under "Open the file under the cursor".

**Comment by zoumi** [comment]
![Snipaste_2022-02-12_13-17-03](https://user-images.githubusercontent.com/5162901/153697960-a0ee3294-cac9-46c0-899a-b840e550e9b2.jpg)
@tpope After press <CR> on the commit ID, fugitive open a buffer with 161448 lines, this operation block vim's window for a long time.

Can we just get a summery window only list the files that are changed?

**Comment by barsv** [comment]
`foldmethod=syntax` makes vim slow for me

**Comment by petar8903** [comment]
5.00 € bonus for winlive248

**Comment by barsv** [comment]
> `foldmethod=syntax` makes vim slow for me

My bad. I've found a fix for it. The issue was that I used the global setting `:set foldmethod=syntax` while i should have used a local setting for the buffer `:setlocal foldmethod=syntax`.
