### ISSUE TITLE
":Git blame" - View commit doesn't work

### ISSUE THREAD

**Issue by Mortivor** [tpope/vim-fugitive#1774]
When I do a ":Git blame" fugitive shows me the blame as expected. But when I hit Enter nothing happens except that my cursor moves one line down. It doesn't show me the commit in question.
I already disabled all my other vim addons one by one, but none of seems responsible for this. Also, I didn't remap the Enter-Key in my .vimrc.
Can anyone help me diagnose?

**Comment by tpope** [comment]
Call `:nmap <buffer>` in the blame window to get a list of local buffer mappings. Is anything there?

**Comment by Mortivor** [comment]
Output is
`n  A           &@:<C-U>exe 'vertical resize '.(<SNR>104_linechars('.\{-\}\ze [0-9:/+-][0-9:/+ -]* \d\+)')+1+v:count)<CR>`
`n  C           &@:<C-U>exe 'vertical resize '.(<SNR>104_linechars('^\S\+')+1+v:count)<CR>`
`n  D           &@:<C-U>exe 'vertical resize '.(<SNR>104_linechars('.\{-\}\ze\d\ze\s\+\d\+)')+1-v:count)<CR>`
`n  gq          &@:<C-U>bdelete<CR>`
`n  q           *@:<C-U>echoerr "fugitive: q is removed in favor of gq (or :q)"<CR>`

**Comment by tpope** [comment]
Long story short, sounds like you need to add `filetype plugin indent on` to your vimrc.

**Comment by Mortivor** [comment]
That worked. Thanks very much!
