### ISSUE TITLE
Get exit code of fugitive

### ISSUE THREAD

**Issue by mosheavni** [tpope/vim-fugitive#1776]
I'm using `G` on functions, and I want to know if the command succeeded or not,
I tried something like this:
```
function! s:MosheGitPull() abort
  echo 'Pulling...'
  Git pull --quiet
  if v:shell_error != 0
    echo 'Failed pulling 😒'
  else
    echo 'Pulled! 😎'
  endif
endfunction
```
However, `v:shell_error` is always 0.

Is there a reliable way to know the command succeeded?
Thanks.

**Comment by mosheavni** [comment]
Found it,
```
  let l:exit_status = get(FugitiveResult(), 'exit_status', 1)
```
@tpope  if you recommend using this differently, please enlighten me.
Thanks.

**Comment by tpope** [comment]
That'll work. Note that if `exit_status` is missing, that doesn't mean it failed, it means it's still running (e.g., when editing a commit message, which will happen if `:Git pull` creates a merge commit).
