### ISSUE TITLE
Can unpushed unpulled be exported?

### ISSUE THREAD

**Issue by mosheavni** [tpope/vim-fugitive#1777]
I want to add to my statusline an indication of unpulled and unpushed changes on my repo,
This information is already retrieved by the main `Git` command, can it be exported just as `FugitiveHead`?
Something like `FugitiveUnpulled` and `FugitiveUnpushed`
I tried implementing it by myself but it's painfully slow:
```
function Unpushed_Unpulled() abort
  if !FugitiveIsGitDir(FugitiveExtractGitDir('%'))
    return 0
  endif
  let fugitive_head = FugitiveHead()
  let g_log_cmd = 'log -n 256 --pretty=format:%h%x09%s '
  " unpushed
  let unpushed_cmd = split(g_log_cmd . 'origin/' . fugitive_head . '..' . fugitive_head)
  " unpulled
  let unpulled_cmd = split(g_log_cmd . fugitive_head . '..origin/' . fugitive_head)

  return printf('↑%d ↓%d',
        \ len(systemlist(FugitivePrepare(unpushed_cmd))),
        \ len(systemlist(FugitivePrepare(unpulled_cmd)))
        \ )
endfunction
```

**Comment by tpope** [comment]
Don't check `FugitiveIsGitDir(FugitiveExtractGitDir('%'))`, check `!empty(FugitiveGitDir())` to avoid hunting for the root of the repository each time. And you can find both numbers you are looking for by calling `git status --porcelain=v2 --branch` and looking for a line like `# branch.ab +2 -0`. But even with both of those changes, it's probably going to be painfully slow.

**Comment by mosheavni** [comment]
@tpope  better than what I used, but every cursor move, there's a blink indicating the command is run,
any way to avoid this?

**Comment by mosheavni** [comment]
ended up with checking `strftime('%s')` and running the cmd only every 10 seconds, this is very useful and does not slow down vim:
```
function Unpushed_Unpulled() abort
  " Don't operate if not on git directory
  if empty(FugitiveGitDir())
    return 0
  endif
  let last_run = get(g:, 'unpushed_unpulled_last_run', 0)
  if last_run != 0 && last_run + 10 > strftime('%s')
    " Return already existing status
    return get(g:, 'unpushed_unpulled_last_status', 0)
  endif

  let unpushed_unpulled_line_string = '# branch.ab '
  let status_output = systemlist(FugitivePrepare([ 'status', '--porcelain=v2', '--branch' ]))
  let unpushed_unpulled_index = match(status_output, unpushed_unpulled_line_string)
  let g:unpushed_unpulled_last_run = strftime('%s')
  let g:unpushed_unpulled_last_status = substitute(
          \ substitute(
            \ substitute(status_output[unpushed_unpulled_index], unpushed_unpulled_line_string, '', ''),
            \ '+',
            \ '↑',
            \ ''
          \ ),
        \ '-',
        \ '↓',
        \ ''
    \ )
  return g:unpushed_unpulled_last_status
endfunction
```

When integrated with lightline:
![image](https://user-images.githubusercontent.com/17252601/123630313-0df96a00-d81e-11eb-91e4-a8a58b76e07c.png)
I love it!
