### ISSUE TITLE
":Git blame" - View commit doesn't work

### ISSUE THREAD

**Issue by Shaiya2688** [tpope/vim-fugitive#1778]
When I do a `":Git blame"` fugitive shows me the blame as expected. But when I hit` Enter `nothing happens except that my cursor disappears and vim stops responding to any keys. It doesn't show me the commit in question until I type `<Ctrl-C>`.
I already disabled all my other vim addons one by one, but none of seems responsible for this. Also, I didn't remap the Enter-Key in my .vimrc.
Can anyone help me diagnose?

**Comment by tpope** [comment]
* Check `:nmap <buffer> <CR>`. It should include `BlameCommit(...)`.
* Check `:Gedit <commit>` works. Use the same commit you are pressing enter on. If that's slow too, it's probably just a really large changeset that's slow to load.

**Comment by Shaiya2688** [comment]
- `:nmap <buffer> <CR>. `  show message:
```viml
n  <CR>        &@:<C-U>exe <SNR>114_BlameCommit("exe <SNR>114_BlameLeave()|edit")<CR>
n  -           &@:<C-U>exe <SNR>114_BlameJump("")<CR>
n  .           &@:<C-U> <C-R>=substitute(<SNR>114_BlameCommitFileLnum()[0],'^$','@','')<CR><Home>
n  A           &@:<C-U>exe 'vertical resize '.(<SNR>114_linechars('.\{-\}\ze [0-9:/+-][0-9:/+ -]* \d\+)')+1+v:count)<CR>
n  C           &@:<C-U>exe 'vertical resize '.(<SNR>114_linechars('^\S\+')+1+v:count)<CR>
n  D           &@:<C-U>exe 'vertical resize '.(<SNR>114_linechars('.\{-\}\ze\d\ze\s\+\d\+)')+1-v:count)<CR>
n  O           &@:<C-U>exe <SNR>114_BlameCommit("tabedit")<CR>
n  P           &@:<C-U>exe <SNR>114_BlameJump("^".v:count1)<CR>
n  gq          &@:exe <SNR>114_BlameQuit()<CR>
n  g?          &@:help :Git_blame<CR>
n  i           &@:<C-U>exe <SNR>114_BlameCommit("exe <SNR>114_BlameLeave()|edit")<CR>
n  o           &@:<C-U>exe <SNR>114_BlameCommit("split")<CR>
n  p           &@:<C-U>exe <SNR>114_BlameCommit("pedit")<CR>
n  q           &@:echoerr "fugitive: q removed in favor of gq (or :q)"<CR>
n  s           &@:<C-U>exe <SNR>114_BlameJump("")<CR>
n  u           &@:<C-U>exe <SNR>114_BlameJump("")<CR>
n  ~           &@:<C-U>exe <SNR>114_BlameJump("~".v:count1)<CR>
n  <2-LeftMouse> &@:<C-U>exe <SNR>114_BlameCommit("exe <SNR>114_BlameLeave()|edit")<CR>
n  <F1>        &@:help :Git_blame<CR>
```

- `:Gedit <commit>`will also block permanently on all commit until I type `<Ctrl-C>`

- I tried it on different git repositories and still had problems.

**Comment by tpope** [comment]
There isn't much to hang on except calls to `git`. Check if a `git` process is running in the background when Vim is hanging.
