### ISSUE TITLE
Fugitive doesn't work well with --separate-git-dir repository

### ISSUE THREAD

**Issue by petRUShka** [tpope/vim-fugitive#1782]
I've initialized repo with following command:

```
git init --separate-git-dir=$HOME/repos/repo.git
```

So I have `.git` file instead `.git` folder. And content of the file is:

```
gitdir: /home/user/repos/repo.git
```

In terminal command like `git status` works perfectly fine, but `:Gstatus` returns almost nothing:

```
Head: master
Push: origin/master
Bare: yes
Help: g?
```

And no more.

Following doesn't work
```
GIT_WORK_TREE=/home/user/repos/repo.git vim
GIT_DIR=$HOME/repos/repo.git vim
```

**Comment by tpope** [comment]
Fugitive requires the `core.worktree` option to work with separate Git dirs.

**Comment by petRUShka** [comment]
Thanks. Calling `git config --add core.worktree $(pwd)` from the directory with code works.
