### ISSUE TITLE
Gstatus: inline preview for untracked file via =/>/< maps

### ISSUE THREAD

**Issue by Jasha10** [tpope/vim-fugitive#1784]
Hello, I'd like to request a feature.

### Abstract
In the `:Gstatus` window, I propose the maps `=` and `>` and `<` to toggle/open/close an inline preview of the untracked file under the cursor.

### Details
This behavior for untracked files would be "consistent" with that of `=` and `>` and `<` for tracked files in the unstaged or staged sections. This being said, `git diff untracked.txt` does not provide useful output, so an inline preview of untracked files would need to be obtained via other means.

**Comment by tpope** [comment]
Git's answer to bringing untracked files into the diff is `git add -N`, and Fugitive exposes this on `I`. Anything more than this and we'd be ceasing to wrap Git and starting to reinvent it. I don't think that's a road I want to go down, at least not right now.

**Comment by Jasha10** [comment]
Thanks for the tip about `git add -N`.
