### ISSUE TITLE
Deprecation warning doesn't display long enough

### ISSUE THREAD

**Issue by togglebyte** [tpope/vim-fugitive#1789]
Would it make sense to use `echom` here so the deprecation warning is available in the message history (`:messages`)?

https://github.com/tpope/vim-fugitive/blob/3e2d5313222d616f680974dcf78aa387c64fd72b/plugin/fugitive.vim#L399

**Comment by tpope** [comment]
AFAIK it's only the `:Gblame` warning that can disappear without acknowledgement. But sure, I want to retrain people so any increase to obnoxiousness is a win.
