### ISSUE TITLE
E1208: Error detected while processing /usr/share/vim/vimfiles/plugin/fugitive.vim

### ISSUE THREAD

**Issue by pzygielo** [tpope/vim-fugitive#1791]
After upgrading `vim` to 
```
$ rpm -qf /usr/bin/vim
vim-enhanced-8.2.3154-1.fc34.x86_64
```
I am getting
```
Error detected while processing /usr/share/vim/vimfiles/plugin/fugitive.vim:
line  527: E1208: -complete used without -nargsline  528: E1208: -complete used without -nargsline  532: E1208: -complete used without -nargsline  536: E1208: -complete used without -nargsPress ENTER or type command to continue
$ rpm -qf /usr/share/vim/vimfiles/plugin/fugitive.vim
vim-fugitive-3.3-1.fc34.noarch
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 12 2021 00:00:00)
Included patches: 1-3154
```

**Comment by tpope** [comment]
This was a sudden upstream change in Vim that blindsided me. The fix is at https://github.com/tpope/vim-fugitive/commit/4cdeff8c33ec2fe0686324bf1846ce158c452754. It hasn't made it into a release yet. I'll try to cut one sooner rather than later but it will still take some time.

**Comment by pzygielo** [comment]
Thanks for checking. Glad to know it's already covered.

**Comment by tpope** [comment]
Hoping to cut a release next week. If you are able, please try `master` and keep an eye out for last minute bugs.

**Comment by tjmgregory** [comment]
You're a hero, thank you!

**Comment by tjmgregory** [comment]
This is my current experience with master `46404ad` and Vim `8.2 (2019 Dec 12, compiled Aug 15 2021 13:04:41)`:
```
Error detected while processing /Users/theo/.vim/pack/theodored/start/coc.nvim/plugin/coc.vim:
line  461: E1208: -complete used without allowing argumentsPress ENTER or type command to continue
```

**Comment by baldurh** [comment]
master is working for me

**Comment by baldurh** [comment]
@tjmgregory see here https://github.com/neoclide/coc.nvim/issues/3215

**Comment by tpope** [comment]
It took a bit longer than expected because I developed a bad case of "one more thing", but Fugitive 3.4 is out! Now let's see how fast we can get it into package managers.

**Comment by tjmgregory** [comment]
> @tjmgregory see here [neoclide/coc.nvim#3215](https://github.com/neoclide/coc.nvim/issues/3215)

My many apologies - a fried head swapping one error for another I'd missed the package name was different! Keep up the excellent work 💪 Thanks for the link!

**Comment by SofijaErkin** [comment]
Thanks @tpope, Great Job!

My vim plugins error while using `vim ~/.vimrc`:

    Error detected while processing /Users/yq/.vim/bundle/vim-fugitive/plugin/fugitive.vim:

    line  410: E1208: -complete used without allowing arguments

    line  411: E1208: -complete used without allowing arguments

fixed with the below:

    cd && cd /Users/yq/.vim/bundle/vim-fugitive/plugin/

    git pull --rebase

Also, thanks @tjmgregory !

**Comment by ewoifuoi** [comment]
Thanks a lot@tpope, that saves me a lot of time
