### ISSUE TITLE
Slow fugitive

### ISSUE THREAD

**Issue by luisiacc** [tpope/vim-fugitive#1793]
The window for `:G` is really slow for me when staging/unstaging, I ran a profile for like 5 seconds and got this:
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    4   1.457033   0.020098  fugitive#BufReadStatus()
    3   1.090913   0.000485  <SNR>111_ReloadStatusBuffer()
   17   1.090172   0.003805  <SNR>111_SystemError()
    2   1.074563   0.000454  <SNR>111_Do()
    2   0.889440   0.000184  <SNR>111_ReloadStatus()
    6   0.604336   0.000281  coc#rpc#request()
    6   0.603943   0.554124  <SNR>66_request()
    2   0.594850   0.000214  CocAction()
    1   0.572826   0.000138  fugitive#Resume()
    1   0.572689   0.028492  <SNR>111_RunWait()
    4   0.533540   0.000835  <SNR>111_NullError()
   11   0.404130   0.003542  <SNR>111_LinesError()
   11   0.400588   0.001562  <SNR>111_ChompError()
    3   0.374039   0.000515  fugitive#ReloadStatus()
    4   0.319814   0.000276  <SNR>111_ReloadWinStatus()
    1   0.319763   0.000222  <SNR>111_ReloadTabStatus()
    8   0.201999   0.000909  <SNR>111_QueryLog()
    2   0.184425   0.000341  <SNR>111_TreeChomp()
    3   0.169838   0.000334  <SNR>111_DoAutocmdChanged()
  134   0.160546   0.158760  <SNR>111_RunTick()

```

Full log:
[asdasdrqwrwqoriqwrqoi.log](https://github.com/tpope/vim-fugitive/files/6833239/asdasdrqwrwqoriqwrqoi.log)

OS: WSL on Windows 10
nvim version : 
```
NVIM v0.6.0-dev+10-g18bfcfe77
Build type: Release
LuaJIT 2.1.0-beta3
```

Fugitive version: `latest` updated today

**Comment by tpope** [comment]
By all accounts, WSL Git is insufferably slow, and seeing `s:SystemError`—a small wrapper around `system()`—suggests that's the bottleneck here as well. A common workaround, from what I've been told, is to use Git for Windows or some other alternative instead, but I don't think anyone's been able to successfully pair a WSL Vim with a non-WSL Git. See #1751 for details.

As long as we're stuck with WSL Git, there's not a lot we can do. One potential optimization would be to cache the 2 calls `git log` which populate the `Unpushed` and `Unpulled` sections. Caching is easy enough, but expiring that cache is tricky. And switching from `system()` to `jobstart()`, which is in progress but stalled at the moment, would eliminate the overhead of calling the shell, but I'm not sure how much overhead that is exactly.

At the end of the day, this is a WSL issue, not a Fugitive issue, but I am open to mitigating where we can.

**Comment by luisiacc** [comment]
Hmm I'm using WSL 1, I know for a fact that that WSL 2 is really slow with git, but I've using it in wsl 1 for about 6 months and it has been pretty fast, this slowness started to show about 3 days ago, it's my bad for not putting that on the issue.

**Comment by luisiacc** [comment]
In fact, now that I check, this is only happening one one repo that I have, on other projects it runs fast, they are all on WSL 1. And in that repo there is no extra git config, no hooks, no nothing.

**Comment by tpope** [comment]
The `git log` calls get skipped if your local and upstream branch are in sync. That could explain a performance difference. Lots of other things could too.

**Comment by tpope** [comment]
Try the latest `master` (which should be faster) and also the `parallel-status` branch (which might be faster still).

**Comment by luisiacc** [comment]
Just tried, it is indeed faster, deactivating the antivirus was also a factor to make it faster.
