### ISSUE TITLE
fugitive: cannot execute Git

### ISSUE THREAD

**Issue by mkhai9x** [tpope/vim-fugitive#1794]
I am using neovim 0.6.0 on macOS
I try other plugins and they are working fine. But I when try vim-fugitive plug and type :Git status  it shows me this error
<code>fugitive: cannot execute Git<code>

Is there any one have a similar issue as mine? Please help

**Comment by tpope** [comment]
This happens when `git` isn't in the `PATH` or some other issue prevents calling it. Check `:echo system('git --version')` and see if you can discern what's going wrong.
