### ISSUE TITLE
Using fugitive with non-standard git directory

### ISSUE THREAD

**Issue by gpanders** [tpope/vim-fugitive#1796]
Hi Tim.

Is it possible to use fugitive with a git directory named something other than `.git`?

Perusing the source code, my hunch is yes, but I haven't been able to get it to work. I've tried manually running `:let b:git_dir = '/path/to/repo/.foobar'` which got me an error saying that `core.worktree is required when using an external Git dir`. I set `core.worktree` to `/path/to/repo` in the git config file, but now any fugitive commands simply say `fatal: not a git repository (or any of the parent directories): .git`.

It looks like something is not happening as expected in the [`s:BuildShell`](https://github.com/tpope/vim-fugitive/blob/master/autoload/fugitive.vim#L496) function. Stepping through that function, it ends up building the command

    git -C /path/to/repo ...

instead of taking the `if` branch that would cause the command to instead be built as

    git --git-dir=/path/to/repo/.foobar ...

This command gets passed back to where it is called in `fugitive#Prepare` (called from `s:NullError` called from `fugitive#BufReadStatus()` from the `index{.lock}` autocmd) which ultimately results in the above error.

`s:BuildShell` checks for `empty(tree)`, which seems to conflict with the requirement that external Git dir's need to have `core.worktree` defined (if I'm understanding the code correctly).

All that said, am I simply missing something simple here, or is this a bug?

Thanks for your time.

**Comment by tpope** [comment]
The logic in `s:BuildShell()` is valid based on the values of `b:git_dir` that Fugitive itself sets. You can try tweaking it if you want and report back on if you can get it to work. But it kind of feels like you're trying to have your cake and eat it too. If `git` doesn't work without a `--git-dir=` argument, shouldn't `:Git` also not work without a `--git-dir=` argument? (`:Git` _doesn't_ support `--git-dir=` currently, but there is a case to be made that it should.)

**Comment by tpope** [comment]
This might work now but I wouldn't be surprised if it falls down on edge cases. Do not rely on assigning the internal variable `b:git_dir` but instead call `FugitiveDetect('/path/to/repo/.foobar')` to initialize the buffer.

**Comment by gpanders** [comment]
Yep, it works. Thanks!
