### ISSUE TITLE
undo accidentally discarded changes

### ISSUE THREAD

**Issue by leosolid** [tpope/vim-fugitive#1797]
Is there a way to re-add your changes after accidentally discarding them with `X`?

**Comment by tpope** [comment]
An undo message is displayed. Check `:messages` if you missed it.

**Comment by TamaMcGlinn** [comment]
If you've already restarted vim and hence lost the `:messages` which tell you how to restore that particular file, then `git fsck --lost-found` and then searching in the `.git/lost-found` directory is the way to go.

To search in that directory, you could use [ripgrep](https://github.com/BurntSushi/ripgrep), or change vim's directory to `.git/lost-found` and use [fzf file contents & name fuzzy search](https://dev.to/iggredible/how-to-search-faster-in-vim-with-fzf-vim-36ko).
