### ISSUE TITLE
Neovim Gedit to view commit doesn't work

### ISSUE THREAD

**Issue by pistachiology** [tpope/vim-fugitive#1798]
When I try to view commit with `:Git blame` it returns error unrecognized git type

![image](https://user-images.githubusercontent.com/10977676/126954942-7879977d-efa1-4e5f-80d3-948a0d66eb95.png)

then, I tried to just view commit with `:Gedit <commit>` its show the same error as above. 
so, I tried to remove all plug inside my vimrc to be minimal as much as possible. somehow it is still not working

Minimal version
```vimrc
filetype plugin indent on
call plug#begin()
Plug 'tpope/vim-fugitive'
call plug#end()
```

Could anyone help me diagnose?

I'm using neovim 0.5.0

**Comment by tpope** [comment]
What shell are you using? Does it work if you use Bash instead? `env SHELL=/bin/bash vim`.

**Comment by pistachiology** [comment]
I'm using fish shell. pretty weird using `vim8` is working with fish shell but `neovim` doesn't. 

btw, set SHELL env to bash and work now thanks!

**Comment by tpope** [comment]
Fish shell _is_ supported. This smells to me you have something in your shell config that is outputting an extra newline at startup. That's what that extra `^@` is.

**Comment by pistachiology** [comment]
Thanks again for pointing out. everything is clear now. My fault accidentally have echo in the shell.

```fish
switch (uname) 
    case Linux
        source "$HOME/dotfiles/fish/linux.fish"
    case '*'
        echo test # <- this line is the problem
end
```
