### ISSUE TITLE
"Git 1.8.5 or newer required" though 2.32.0 is installed

### ISSUE THREAD

**Issue by svenXY** [tpope/vim-fugitive#1801]
Hi, I get
`fugitive: Git 1.8.5 or newer required`
though
`:echo system('git --version')`
returns
`git version 2.32.0`

this is neovim NVIM v0.5.0-dev+1455-gf83c25942
fugitive: latest
on macOS 11.4

**Comment by tpope** [comment]
What is `:echo fugitive#GitVersion()`?

**Comment by svenXY** [comment]
`1:`

**Comment by tpope** [comment]
What is `:echo g:fugitive_git_executable`? It might be unset.

**Comment by svenXY** [comment]
ah, that might be it, a few years ago I had problems with locales and fugitive, that's why I set it to `:echo g:fugitive_git_executable` then, which - up until now - served me perfectly.

**Comment by tpope** [comment]
The old `:Gstatus` could necessitate setting that, but that should be moot now. I recommend removing it from your config and seeing if anything breaks.

There is a recently introduced bug here, though, that I'll fix.

**Comment by svenXY** [comment]
Thanks, it fixed my inherent problem of not being able to use `:Git` at all and also it being the new `Gstatus` works as well.

**Comment by 88523** [comment]
可以可以

**Comment by 88523** [comment]
DICT、FILE、FTP、FTPS、GOPHER、GOPHERS、HTTP、HTTPS、IMAP、IMAPS、LDAP、LDAPS、MQTT、POP3、POP3S、RTMP、RTMPS、RTSP……
