### ISSUE TITLE
Gdiffsplit in existing split

### ISSUE THREAD

**Issue by AUsernameWhichIsNotTaken** [tpope/vim-fugitive#1804]
Thank you for that awesome tool!  Having set diffopt+=vertical I'd like Gdiffsplit to use an existing vertical split to the left or the right of the current window instead of creating a new one.   (I'm aware that the command tells me it will split. ;)   Is that possible?   Where would I start to look in the fugitive code-base to adapt it myself?

**Comment by tpope** [comment]
There is no direct support for this, but you can `:call fugitive#DiffClose()` to close other diff windows beforehand to achieve the same effect.

**Comment by AUsernameWhichIsNotTaken** [comment]
Thank you for your quick feedback! If I understand you right you interpret 'use an existing vertical spilt' as 'use an existing vertical split from a previous diff'.  But my use-case is: i usually work with three vertical splits in a vim-window and I want to git-diff one of the three visible buffer.  And I wish fugitive would take an existing split (:set hidden is set) for the split which I then could delete with my own :Bdelete command which removes the git-diff-buffer but doesn't touch the current split.  Otherwise I always have to fiddle with the splits which I find interrupting.

**Comment by AUsernameWhichIsNotTaken** [comment]
Sow what I basically would like to have is something along the lines of the following pseudo code

<pre>
`if g:fugitive_use_existing_split
  "complain if hidden is of
  winID = get_split_winid_according(split_orientation)
  if winID == 0
    "do what fugitive does now
    return
  endif
  "open fugitive-diff-buffer in window with winID
else
  "do what fugitive does now
endif`
</pre>
which seems for me blessed with ignorance about the vim and fugitive internals easier to do than fixing the broken split layout programmatically around current fugitive diff-behaviour.

**Comment by tpope** [comment]
I will not be adding a configuration option to accommodate your bespoke setup. I would consider a change that adds an API that returns the buffer names that would be opened, which you could then use to open windows however you like.

**Comment by AUsernameWhichIsNotTaken** [comment]
Thank you for your effort.  Since there are more operations (git-log, git-status and not fugitive related) which generate new splits I implemented last night a general solution which opens resulting splits of such operations vertical while keeping the number of vertical splits constant and being smart about the buffer-management...  All the best!
