### ISSUE TITLE
Autosquash rebases should be run with autostash

### ISSUE THREAD

**Issue by kmoschcau** [tpope/vim-fugitive#1806]
I've recently used the fixup/autosquash features a lot more, but soon discovered I have to manually add `--autostash`, when I have some unstaged changes left in the worktree. Would it be sensible for `cF` and friends to add that by default or is that breaking something else?

**Comment by tpope** [comment]
Personally I enable `rebase.autoStash` in my config. I think respecting the user's preferences here is probably the correct behavior.
