### ISSUE TITLE
Neovim+Powershell breaks fugitive

### ISSUE THREAD

**Issue by Tarmean** [tpope/vim-fugitive#1807]
My environment is 

- Windows 10
- Neovim v0.5.0 or Neovim head
-  git version 2.32.0.windows.1
-  and the following config from `:h shell-powershell`

		let &shell = has('win32') ? 'powershell' : 'pwsh'
		let &shellcmdflag = '-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;'
		let &shellredir = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
		let &shellpipe = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
		set shellquote= shellxquote=

Since commit https://github.com/tpope/vim-fugitive/commit/75b2a9a8daf6589f9747ff4f2d068fdea54e92ea most git commands except Gstatus broke for me. The commands briefly do some work and then fail silently.

Without the shellquote setting, an error `fugitive: cannot execute Git` is thrown instead.

**Comment by Tarmean** [comment]
I experimented some more to see if this is solvable and believe there is no way around an extra condition on this line https://github.com/tpope/vim-fugitive/blob/75b2a9a8daf6589f9747ff4f2d068fdea54e92ea/autoload/fugitive.vim#L1613

I'm assuming the check should be for `has('patch-8.2.3079')` rather than something Neovim specific but I don't know enough about vim versioning to be sure. The commands that are executed are

Old behavior:

     (git -C C:/Users/name/vimfiles/plugged/vim-fugitive --literal-pathspecs cat-file blob :0:autoload/fugitive.vim > C:\Users\name\AppData\Local\Temp\nvimvS6TLS\19) 

New behavior

    powershell -NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8; "git -C C:/Users/name/vimfiles/plugged/vim-fugitive --literal-pathspecs cat-file blob :0:autoload/fugitive.vim > C:\Users\name\AppData\Local\Temp\nvimvS6TLS\18"

When vim tries to escape without the necessary patch it wraps the command in quotes, which powershell interprets as a string literal. Therefore no command is executed and the string is returned.

**Comment by tpope** [comment]
Did things 100% work before the change in question? In particular, could you successfully `:Gedit HEAD:filename with spaces`?

**Comment by tpope** [comment]
While I am still interested in the answer to that question for future reference, I think your version constraint proposal is correct regardless.

cc @mrdubya

**Comment by Tarmean** [comment]
The fallback case seems to handle both unicode characters and filepaths with spaces, as far as I can tell everything works correctly.

**Comment by mrdubya** [comment]
If Neovim does not handle setting shell to one of the PowerShell implementations the same way as Vim now does, then there will be issues there I guess. The `shellcmdflag` Neovim suggests would seem to assume using PowerShell Core since I don't believe it works as intended with PowerShell Desktop/Windows, at least not without a lot more system configuration, as indicated here on [Stackoverflow](https://stackoverflow.com/a/65192064). Removing shell sensitivity altogether would make life a lot easier ;)

**Comment by tpope** [comment]
> Removing shell sensitivity altogether would make life a lot easier ;)

The `job-temp-files` branch is more or less ready. I'll likely start pulling in changes within the next few days.
