### ISSUE TITLE
Git execution error from fugitive

### ISSUE THREAD

**Issue by mPanasiewicz** [tpope/vim-fugitive#1809]
Hello,

I've try to use fugitive on neo vim(nvim) latest 0.5 version.
If I use any of commands I get an error `fugitive: cannot execute Git`. No more details.

I've checked the library on vim 8, and it works fine. Do you have any idea what is going wrong in my setup?

Plugins below:
![image](https://user-images.githubusercontent.com/9081428/129024483-08bf7098-b217-44b4-9570-ce91b5bf629e.png)

Thanks!

**Comment by tpope** [comment]
Check `:echo fugitive#GitVersion()`. Given that error, I would expect it to be blank.

Also, report back on the value of `echo g:fugitive_git_executable`. It might be undefined.

**Comment by mPanasiewicz** [comment]
> Check `:echo fugitive#GitVersion()`. Given that error, I would expect it to be blank.
> 
> Also, report back on the value of `echo g:fugitive_git_executable`. It might be undefined.

@tpope You're right. 
`:echo fugitive#GitVersion()` => blank
`echo g:fugitive_git_executable` => returns `E121: Undefined variable: g:fugitive_git_executable`

**Comment by tpope** [comment]
What does `:set shell? shellcmdflag?` report?

What about `:echo json_encode([system('git --version'), v:shell_error])`?

**Comment by mPanasiewicz** [comment]
@tpope Thanks! It works.
`:set shell? shellcmdflag?` => this showed me that I have wrong shell setup. I've changed it in the vim initialization and it works like a charm.

Thank you very much!
