### ISSUE TITLE
Error when running :Gstatus in vim

### ISSUE THREAD

**Issue by edlimerkaj** [tpope/vim-fugitive#1810]
I am trying to use vim-fugitive in nvim text editor. I edited my ~/.config/nvim/init.vim file, by adding the following line: ` Plug 'tpope/vim-fugitive`. I also used :PlugInstall to install the plugin and everything worked great. Also checking with :PlugStatus shows that vim-fugitive is OK and already up to date.

Even though I get the following  error when running the ` :Gstatus ` command

`
 Error detected while processing function <SNR>165_ReloadWinStatus[5]..<SNR>165_ReloadStatusBuffer[6]..fugitive#BufReadStatus[218]..FugitiveConfigGetAll:
  line    1:
  E117: Unknown function: fugitive#ConfigGetAll
  Error detected while processing function <SNR>165_ReloadWinStatus:
  line    5:
`
Running just `:Git` also gives the following errors:

` 
Error detected while processing function <SNR>165_ReloadWinStatus[5]..<SNR>165_ReloadStatusBuffer[6]..fugitive#BufReadStatus[218]..FugitiveConfigGetAll:
line    1:
E117: Unknown function: fugitive#ConfigGetAll
Error detected while processing function <SNR>165_ReloadWinStatus:
line    5:
E171: Missing :endif
`
I am unsure on why I am getting these errors and what can I do to resolve these errors, so I would really appreciate any help I receive about this.

**Comment by tpope** [comment]
Looks to me like you have 2 versions of Fugitive installed: an old `autoload/fugitive.vim` and a new `plugin/fugitive.vim`.
