### ISSUE TITLE
Only map `cp` if no conflict

### ISSUE THREAD

**Issue by dakennguyen** [tpope/vim-fugitive#1811]
Hi,
Just like with `q`, could we also have a check to only map `cp` if no conflict? Like this:
```
    if empty(mapcheck('cp', 'n'))
      call s:Map('n', 'cp',    ":<C-U>echoerr 'Use gC'<CR>", '<silent>')
    endif
```
The context is I want to map `cp` with something else in `fugitive` and `git` filetypes. While I managed to unmap cp in `fugitive`, this mapping always override my mapping in `git`.

Maybe it also makes sense to mapcheck other deprecated mappings also, in case people want to map it with something else. I could make a PR if you think it's okay

**Comment by tpope** [comment]
Sure. But note I only deprecated `cp` because I plan to one day claim all of `c` for the commit operation.

**Comment by tpope** [comment]
For anyone that finds this wanting to unmap something, this should work:

```vim
autocmd User FugitiveTag,FugitiveCommit,FugitiveIndex nunmap <buffer> cp
```

**Comment by dakennguyen** [comment]
Thank you! Love your plugins and can't wait to see the upcoming features 🎉
