### ISSUE TITLE
Showing merge commits when using interactive rebase?

### ISSUE THREAD

**Issue by zoj613** [tpope/vim-fugitive#1812]
Currently, when using interactive rebase via `:Git rebase -i <commit hash>` the merge commits are not shown. I would like to be able to view them and then choose the ones I want to merge into the previous commit. This way I get to keep the information about the date of the merged commit. My git tree for this particular project is littered with merge commits that i'd like to get rid of without completely changing the commit date of the "real" commits inbetween the merges. Any ideas how I can achieve this with vim-fuigitive interactively?

**Comment by tpope** [comment]
Not related to Fugitive really but look into `git rebase --rebase-merges`.
