### ISSUE TITLE
Git push suggestion of getting branch take too long time

### ISSUE THREAD

**Issue by lioaslan** [tpope/vim-fugitive#1813]
Hi,
I use the `Tab` key to enter the command `:Git push orgin some_branch` faster. `Git`, `push`, `origin` is okay but when I type the first character of the branch it takes a long time about 30s-1m to get the full branch name. I don't think it's the performance problem of my computer because it works well in the terminal when I use the `Tab` key.
Thanks for any help.

**Comment by tpope** [comment]
How fast is `git ls-remote origin`? This is what Fugitive uses to complete the branch argument.

**Comment by lioaslan** [comment]
![image](https://user-images.githubusercontent.com/24852182/130013531-727bde88-f7da-4b8b-98e7-c3f9871d3a74.png)
Oh, it takes a long time too. I tested with GitHub repo and GitLab repo. It takes more than 3s. Is there any command that can do that function, like `git branch`?

**Comment by tpope** [comment]
I don't think there is a good drop in replacement. However, `ls-remote` makes more sense for `fetch` and `pull` than it does for `push`. For `push`, we actually want to complete local branches by default, and only complete remote branches on `:Git push origin localbranch:<Tab>`. So, I guess it's your lucky day.

**Comment by lioaslan** [comment]
Thanks. I have updated fugitive. It works faster.
