### ISSUE TITLE
Error :Git merge

### ISSUE THREAD

**Issue by quimortiz** [tpope/vim-fugitive#1817]
Hello! Thanks for the cool Plugin :)
I receive the following when I run
:Git merge

I have checked the commit history and the error appears first in commit 9a2299038ba0f9599708416ac1bea52a75623645 of August 18 2021
Previous commit 809efd3f629704996c7104d36265995f472955f3 is fine 

```
Error detected while processing function fugitive#Command[59]..function fugitive#Command[52]..<SNR>170_MergeSubcommand:
line    1:
E121: Undefined variable: dir
E116: Invalid arguments for function fugitive#Find('.git/MERGE_MSG', dir)) || isdirectory(fugitive#Find('.git/rebase-apply', dir)) ||  !empty(s:TreeChomp([a:options.git_dir, 'diff-files', '--diff-filter=U'])))
E116: Invalid arguments for function filereadable(fugitive#Find('.git/MERGE_MSG', dir)) || isdirectory(fugitive#Find('.git/rebase-apply', dir)) ||  !empty(s:TreeChomp([a:options.git_dir, 'diff-files', '--diff-fi
lter=U'])))
Press ENTER or t
```
I am using 
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Aug 18 2021 18:07:41)
Included patches: 1-3358
in ubuntu 20.04

**Comment by tpope** [comment]
Thanks, I've gotten a bit sloppy with some aggressive refactoring as of late.
