### ISSUE TITLE
Gstatus no unpushed section with git worktrees / bare repo

### ISSUE THREAD

**Issue by spuny** [tpope/vim-fugitive#1818]
I have this problem when i don't see unpushed commits in Gstatus. They just disappear when i create the commit.
I thin this is mainly my problem but i would like to ask for some help.
Cause i can see the section if i normally clone the repo (without --bare flag).

I'm using bare to have nice folder structure and yes i know i can use git worktrees without --bare flag but that makes it really ugly and tbh not so much usable for me.

Thanks in advance

**Comment by tpope** [comment]
Works fine when I try it. Provide exact instructions to reproduce.

**Comment by spuny** [comment]
Instruction to reproduce:
1. Clone repo with `--bare` flag
2. create worktree with `git worktree add <branch>` #master for example
3. open nvim in the newly created folder
4. Make change
5. Commit the change

Expected result:
```
Head: dev
Merge: origin/dev
Help: g?

Unpushed to origin/dev (1)
abe2d68 test
```

What i see in the `--bare` repo
```
Head: dev
Merge: origin/dev
Help: g?
```

As you said it works fine in normally clonned repo. 

I think this is due to the fact that something is missing and vim-fugitive is not able to show the expected results.

**Comment by tpope** [comment]
Why doesn't `git log origin/master` (or whatever `Merge` is) work?

**Comment by spuny** [comment]
Command works, Gstatus is just not showing the Unpushed section

**Comment by tpope** [comment]
```
$ pwd
/tmp/vim-fugitive.git/master
$ git log origin/master
fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

It doesn't work. I followed your instructions exactly and it doesn't work. Fugitive can't figured out what isn't pushed if it can't see what is being pushed to. This is why it's failing.

**Comment by spuny** [comment]
You are right sorry i was in the wrong repo. Thanks for the advice and nudge in right direction. Have a nice rest of the day.

**Comment by rnprest** [comment]
Sorry to comment on this closed issue, but what exactly was the fix here? I've been using fugitive for ages but only recently started using git worktrees, with the exact same workflow/steps that @spuny posted earlier in this issue. Was the consensus just that using worktrees + bare repos will never work with fugitive because git itself doesn't really work with worktrees + bare repos (in reference to showing unpushed commits)?
If so, then why does it feel like every single worktree tutorial I find is using bare repos?

I'd love to know what your current workflow is like @spuny

**Comment by tpope** [comment]
> Sorry to comment on this closed issue, but what exactly was the fix here? I've been using fugitive for ages but only recently started using git worktrees, with the exact same workflow/steps that @spuny posted earlier in this issue. Was the consensus just that using worktrees + bare repos will never work with fugitive because git itself doesn't really work with worktrees + bare repos (in reference to showing unpushed commits)?

That's my working assumption.

> If so, then why does it feel like every single worktree tutorial I find is using bare repos?

Good question.
