### ISSUE TITLE
[Feature Request] `G log --graph` Highlighting

### ISSUE THREAD

**Issue by KSR-Yasuda** [tpope/vim-fugitive#1820]
Buffers for `G log --graph` is applied `syntax` = `git`, though,
default `syntax/git.vim` does not support log graph highlighting.

Being more likely to open git-log-graph buffer,
couldn't Fugitive support it?

I wrote a syntax `gitlog` that supports git-log-graph:
modified the `git`-syntax's regexp to allow line-heading log-graph symbols.

Could you apply the syntax if `G log --graph` buffer is opened?

* [gitlog.vim.gz](https://github.com/tpope/vim-fugitive/files/7063579/gitlog.vim.gz)

![syntax_gitlog](https://user-images.githubusercontent.com/31273423/131057838-9fb340b3-7fa7-4108-aeb2-81af0a807462.png)

**Comment by tpope** [comment]
I've gone ahead and merged this into vim-git `master`. You can claim partial credit for this as the `[\*|\/\\_ ]*` pattern is what got me thinking it might not be a lost cause.

**Comment by KSR-Yasuda** [comment]
Okay, thank you.
If you improve `git` syntax itself, it's much better.

Perhaps `minlines` should be more.
It affecting performance, keep an eye on it if you please.

**Comment by tpope** [comment]
I'm not seeing any issues that would be fixed by increasing `minlines`.

**Comment by KSR-Yasuda** [comment]
Oh, your [`vim-git`](https://github.com/tpope/vim-git.git) works well on even 14,000 lines long log-graph!
(tested `fugitive`'s `G log --graph`).
Thank you, nothing's problem.
