### ISSUE TITLE
View diff in new vertical tab

### ISSUE THREAD

**Issue by ahosseinich** [tpope/vim-fugitive#1821]
until yesterday when using `Gclog` and select a commit, commit details are shown in new window. when hit `O` on a file in commit detail, new tab with vertical diff opened. but today after update the `O` open diff tab in horizontal view. what is the right mapping for vertical diff tab?

**Comment by tpope** [comment]
This was an unintended consequence of an intended simplification of `:Gdiffsplit`. Bringing back the old behavior for now.
