### ISSUE TITLE
Keymap in index is delayed

### ISSUE THREAD

**Issue by kevinhwang91** [tpope/vim-fugitive#1822]
Sinc https://github.com/tpope/vim-fugitive/commit/6b7892dc7b4b18e48a6439d1bad860947ce32d03, the keymap is delayed if I set `g:nremap`'s entry with an empty value.

`cat mini.vim`
```vim
pa vim-fugitive

let g:nremap = {'dq': ''}
```
Reproduce:
1. nvim -u mini.vim
2. Change cwd to a git repo
3. run `:G`
4. press `:`

**Comment by tpope** [comment]
Thanks!
