### ISSUE TITLE
`:Git blame` fails when the `blame.ignorerevsfile` doesn't exist

### ISSUE THREAD

**Issue by nchase** [tpope/vim-fugitive#1823]
I have a global git configuration set up to ignore certain revisions like so:

```
blame.ignorerevsfile=.git-blame-ignore-revs
```

If I try to use vim-fugitive to `:Git blame` files without this file being present in one of my repos, vim-fugitive fails with the following error:

```
fatal: could not open object name list: .git-blame-ignore-revs
```

If I create a blank `.git-blame-ignore-revs`, `:Git blame` works as expected.

Can vim-fugitive fail more gracefully when the file defined by `blame.ignorerevsfile` does not exist? (i.e. can it just continue showing the git blame, in my case?)

**Comment by tpope** [comment]
To be clear, all of `git blame` is broken, but you want `:Git blame` to work anyways? That's gonna be a no. Part of my motivation for replacing commands like `:Gblame` with `:Git blame` was the ability to issue a simple dictate: If you don't like how `git` is behaving, take it up with `git`, not `:Git`.

**Comment by nchase** [comment]
Thanks @tpope – I didn't realize that all of `git blame` was broken. I only use fugitive!
