### ISSUE TITLE
E225: global mapping already exists for ^P

### ISSUE THREAD

**Issue by thisguychris** [tpope/vim-fugitive#1826]
Hi @tpope 👋 

So I'm getting this error, when I invorke `G` without arguments. All Git commands (eg. `:G status` , `G version`) seems to work

```
Error detected while processing BufReadCmd Autocommands for "index{,.lock}"
..function fugitive#BufReadStatus[319]
..BufReadCmd Autocommands for "index{,.lock}"
..function fugitive#BufReadStatus[254]..fugitive#MapJumps[27]..<SNR>61_Map:
line   21:
E225: global mapping already exists for ^P
```

It seems it's being introduced by this commit: If I go a commit before this it seems to be working:
`https://github.com/tpope/vim-fugitive/commit/f3e92c7721505a59738db15e3e80bc5ccff08e36

using:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep  4 2021 15:31:16)
Included patches: 1-3399

**Comment by tpope** [comment]
I can't reproduce this, even when I define a global CTRL-P mapping. What does `:verbose nmap <C-P>` report?

**Comment by thisguychris** [comment]
Hi @tpope 👋 

I'm getting `No mapping found`

I've also updated my repo from the upstream and recompiled vim, to include the latest patches

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep  5 2021 10:15:25)
Included patches: 1-3403

**Comment by tpope** [comment]
Try with a stripped down config: no other plugins and a minimal vimrc.

**Comment by thisguychris** [comment]
Hi @tpope , I apologize for the false alarm, you were right from the start. I have a mapping for C-P. It's inside of one of my custom functions.

```
nmap <C-S-P> :call <SID>SynStack()<CR>
function! <SID>SynStack()
  if !exists("*synstack")
    return
  endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc
```
Having a minimal set of vimrc helped. Sorry if I missed that.

**Comment by tpope** [comment]
Okay, so the issue is that `<C-S-P>` counts as the same map as `<C-P>` as far as `<unique>` is concerned, but a different map as far as `mapcheck()` is concerned.  Given how `<C-S-P>` is the same as `<C-P>` in the terminal, it's not that surprising to find an edge case here. I'm pushing up a change that will prevent this particular error from happening.

**Comment by thisguychris** [comment]
@tpope confirmed! Pulling from the latest update fixes this edge case. Thanks for the quick fix. Hope you had/have a nice weekend.
