### ISSUE TITLE
Auto switch to insert mode when committing.

### ISSUE THREAD

**Issue by theteachr** [tpope/vim-fugitive#1828]
A simple enhancement that puts the editor in `--INSERT--` mode when the commit message buffer is opened (with <kbd>c</kbd> <kbd>c</kbd>).

**Comment by tpope** [comment]
What about `cvc`? What about `cw`? What about directly calling `:Git commit`? What are the boundary conditions for this extremely specific and arbitrary behavior?

**Comment by tpope** [comment]
I guess I don't need the answer to that to say that this feature as requested will not be happening.

If it's the map you care about, you can override it. But be careful to make sure it doesn't edit the summary buffer if there are no changes to commit. I don't think this is worth bothering with just to save a single `i`, but the pieces are there and I can't stop you. One downside of this approach is I want to change `c` to popup a dialog, and when that happens, this will just get in the way. Consider using a different map instead. Example implementation:

```
autocmd User FugitiveIndex,FugitiveObject
      \ nnoremap <buffer> <Leader>c :Git commit|if &filetype ==# 'gitcommit'|startinsert|endif<CR>
```

I'm also adding a `FugitiveEditor` event that triggers on _any_ `:Git` edit: `:Git commit`, `:GIt tag -a`, `:Git rebase -i`, etc. I think using this for `:startinsert` is probably a bad idea, but if you want to shoot yourself in the foot, you have your gun.
