### ISSUE TITLE
`G!` Command Opens a Preview Window with Cursor at EOF

### ISSUE THREAD

**Issue by KSR-Yasuda** [tpope/vim-fugitive#1832]
For example,
`G! log --graph --oneline` shows git log graph in a preview window.

But, once you move to the preview window, cursor position is on the end line of the buffer
(Without moving to the preview window, it displays the head of the buffer, though).

For too long log-graph, syntax highlighting may time out, too.

Only `G!` command has this problem.
`G` command, that opens a normal window, looks not having this issue.

----

For the command using `pedit`, it looks fine redoing `pedit` with jumping to the head (`+0`).
However, it needs preceding `sleep` for some reason.

```diff
--- a/autoload/fugitive.vim
+++ b/autoload/fugitive.vim
@@ -3682,6 +3682,10 @@ function! fugitive#Command(line1, line2, range, bang, mods, arg) abort
       exe 'silent' do_edit '++ff=unix' s:fnameescape(state.file)
       let state.capture_bufnr = bufnr(state.file)
       call setbufvar(state.capture_bufnr, '&modified', 1)
+      if do_edit =~# '\v<pedit>'
+        silent sleep 1ms   "XXX: Without this sleep, it has no effect
+        silent pedit +0
+      endif
       return (after_edit . after)[1:-1]
     endif
     call add(s:resume_queue, [state, tmp, job])
```

**Comment by tpope** [comment]
This is by design. Streaming to the window wouldn't be very useful if you couldn't actually see it stream. The primary use case here is commands like `:Git! push`.  If you don't want it to scroll, use `:Git! -p log --graph --oneline`.

**Comment by KSR-Yasuda** [comment]
Got it. Thank you!

**Comment by sadeghzare2580** [comment]
در تاریخ جمعه ۱۰ سپتامبر ۲۰۲۱،‏ ۰۴:۵۱ KSR-Yasuda ***@***.***>
نوشت:

**Comment by tpope** [comment]
> (Without moving to the preview window, it displays the head of the buffer, though).

I missed this part. That's not the intended behavior; it should scroll immediately. I'll look into it.
