### ISSUE TITLE
Tab completion for :Git ++curwin

### ISSUE THREAD

**Issue by teoljungberg** [tpope/vim-fugitive#1833]
Since ef8e771b25e51917f0f52760f05988e9a5a5b829 and 6dd18b5c98476cd1340e8d87dedd4c34a28915ef fugitive can open a full screened window for :Git's output. It would be nice if `:Git ++cu`<kbd>Tab</kbd> would tab complete to `:Git ++curwin`.

**Comment by tpope** [comment]
This is an incredibly niche feature, but not that hard to tab complete, so _fine_.

**Comment by teoljungberg** [comment]
I agree that it's very niece, it's also interesting that :term ++<kbd>Tab</kbd> doesn't complete those options in vim either.

**Comment by tpope** [comment]
I knew my gut reaction was onto something.

**Comment by teoljungberg** [comment]
If you want to roll it back based on that finding, I'm not going to argue against it.

**Comment by tpope** [comment]
It's fine for now, but as the option handling gets more complicated it may get to be more trouble than it's worth.
