### ISSUE TITLE
No mappings in the git blame window

### ISSUE THREAD

**Issue by tamirzb** [tpope/vim-fugitive#1835]
The bottom line is that my issue seems very similar to #1774, I get the same mappings when I run `nmap <buffer>`.
Unfortunately, the issue is that even adding `filetype plugin indent on` to my vimrc doesn't fix this issue :(

Note that mappings still work in other buffers (e.g. after running `:Gclog`).

Can anyone maybe help my diagnose this?

**Comment by tpope** [comment]
For starters, check `:scriptnames` and see if `ftplugin/fugitiveblame.vim` is in it.

**Comment by tamirzb** [comment]
Ok, so actually it wasn't in `:scriptnames`, which helped me debug and solve the issue.

The issue is that Arch Linux recently updated their vim-fugitive package from v3.2 to v3.4, but forgot to add the ftplugin directory to their package, which was added in v3.3. The bottom line is that it's a bug in the Arch Linux package :/

For reference, here is the script that packages vim-fugitive in Arch: https://github.com/archlinux/svntogit-community/blob/4a403d493b6392a4817b5bfd231f8a6e5d905d8b/trunk/PKGBUILD#L26.

Anyway, thanks for helping me debugging this! I'll make sure to report it to the maintainer of the Arch Linux package.

**Comment by tpope** [comment]
Thanks for getting this fixed. It is probably worth mentioning that Fugitive uses `export-ignore` in `.gitattributes`, so `cp -r -t "${_installpath}" *` should be safe and future-proof.
