### ISSUE TITLE
Issue committing with locked signing key

### ISSUE THREAD

**Issue by danjones1618** [tpope/vim-fugitive#1836]
I currently have my [pinentry](https://wiki.archlinux.org/title/GnuPG#pinentry) program set to `pinentry-curses` for unlocking my signing key

When using fugitive to `:G commit` when the key is locked it will start `pinentry-curses` to request the signing key password.
However, when this happens it renders over `vim` and upon exiting `vim` is looks messed up as the background of `pinentry-curses` is still present. This can be reset by doing `!` to re-render `vim`

Is there any way around this?

**Comment by tpope** [comment]
I would expect this _not_ to work: The interaction model of `:Git` necessitates the use of a dumb terminal, which is `pinentry-tty` territory, not `pinentry-curses`. But it sounds like what is happening is that `pinentry-curses` is getting its hands on Vim's tty and trashing it.

What Vim version? What OS? What is `:echo g:fugitive_pty` (expected to be an undefined variable)?

**Comment by danjones1618** [comment]
That explanation makes perfect sense.
If it's not possible then I'll just switch to `pinentry-tty`

Version: VIM 8.2 (from arch repos)
OS: Arch Linux
`:echo g:fugitive_pty`: Undefined variable

**Comment by tpope** [comment]
Can you tell me if you have `$GPG_TTY` set or are doing anything else similarly nefarious?

**Comment by danjones1618** [comment]
Just `export GPG_TTY=$(tty)`

**Comment by tpope** [comment]
Well that would certainly explain it. You're telling GPG to hijack the current TTY away from Vim, so it's no surprise that the screen gets garbled without Vim knowing about it. I think I'll fix it by blanking out `GPG_TTY` when calling `git`.

**Comment by danjones1618** [comment]
That makes sense. Iirc the rational behind it is to do with ssh-ing into the machine
Thanks!

**Comment by tpope** [comment]
I found a workaround, but it's not pretty. Put this in `/usr/local/bin/gpg` or anywhere else that outranks `/usr/bin` in `$PATH`, and put this in it:

```sh
#!/bin/sh

if [ -n "$FUGITIVE" ]; then
  set -- --pinentry-mode loopback "$@"
fi
exec /usr/bin/gpg "$@"
```

Alternatively, give the script a different name, and configure `gpg.program` in Git to point at it.

**Comment by danjones1618** [comment]
That worked thank you so much!

**Comment by GRiMe2D** [comment]
Hi, I'm trying to use `pinentry-tty` and still cannot sign commits. Also removed `GPG_TTY` definition. 

I don't want to use loopback mode. Is there any option?
