### ISSUE TITLE
[QUESTION] Fugitive commit object view

### ISSUE THREAD

**Issue by levouh** [tpope/vim-fugitive#1838]
When opening the `git log` history with something like `:G log --stat -25 %`, I get exactly what I want; a git history for the current file. Then if I want to follow a specific commit and look at diffs, I can open up the associated _Fugitive_ object with a `<CR>` press on the `SHA`. Once I get there I have a `BufEnter fugitive://` autocommand to issue a `zM` to close all folds based on the `foldmethod=syntax` setup that (presumably) `vim-fugitive` does. This allows me to do something like `O` on each file and view the diff in a new tab.

The problem comes (seemingly) from loading larger diffs (and then folding them), none of which I actually care about viewing (I find the standard vertical diffs hard to read, etc.).

So my question is: when viewing a Fugitive commit object, is there a way to only show the changed _files_ by default (without folding), and still allow `O` and similar actions on them? Ideally something akin to the output of `git log --stat` or `git log --name-only`, etc.

**Comment by tpope** [comment]
This is not currently possible. It's been on the agenda for a quite a while to change the commit buffers to use the `fugitive` file type, which would make it possible to collapse/expand diffs just like in the status buffer. But I've been struggling to figure out the design (particularly with respect to merge commits, if you must know), let alone the implementation.

One comparatively straightforward change that addresses the essence of this request is making it possible to jump directly from the `:Git log` output to the file, without needing to add verbose `--patch` output. The filename in in `--stat` is sometimes truncated, and `--name-only` is impossible to distinguish from the rest of the noise, but `--name-status` will work for this just fine.

**Comment by currybullen** [comment]
Is there anything in the documentation that actually mentions that this is possible to do? I was thinking about this when I was looking at the patch view of a commit too: from there it is also possible to jump to a diff, for example by pressing `O` on a line such as `diff --git a/file b/file`. I stumbled upon it just by pure experimentation, but I think I would not have realized it was possible from the documentation alone.
