### ISSUE TITLE
Respect &splitright for :vertical Git

### ISSUE THREAD

**Issue by teoljungberg** [tpope/vim-fugitive#1839]
When &splitright is set and one does `:vertical Git` - Git is opened in a split on the default left rather than on the right.

Is this something we'd like to have changed in fugitive?

**Comment by tpope** [comment]
`'splitright'` is bad taste, full stop. But yes, we should respect it.

**Comment by teoljungberg** [comment]
Bad taste as it is not a vim default setting?

**Comment by tpope** [comment]
All I'll say is that there are two kinds of `'splitright'` users:

* Those who had a knee-jerk reaction the first time they ever split a window in Vim.
* Those who blindly copied it from someone else's vimrc.

Prove me wrong.

**Comment by teoljungberg** [comment]
I for one think it's more intuitive, but - it is personal taste after all so it's difficult to compare apples to pears.
