### ISSUE TITLE
u works as rf without running it

### ISSUE THREAD

**Issue by YorikSar** [tpope/vim-fugitive#1842]
Docs say:

```
ri                      Perform an interactive rebase.  Uses ancestor of
u                       commit under cursor as upstream if available.

rf                      Perform an autosquash rebase without editing the todo
                        list.  Uses ancestor of commit under cursor as
                        upstream if available.
```

But if I press `u` on a line in "Unpushed to..." section, it fills ex command line with a command for `rf` and doesn't execute it.

Looks like all `feedkeys` calls in `DoStage*` functions miss `"\<CR>"` at the end. Also, `u` should be moved to `rf` or implemented as `ri`.

**Comment by YorikSar** [comment]
By the way, I've just discovered these "rebase" mappings for myself. And they are *awesome*!

**Comment by tpope** [comment]
It's deliberate. I don't think a single key-press should trigger such an aggressive behavior without confirmation. Especially a key like `u`, which most people might not even know has behaviors other than "unstage".

Your confusion makes a good case for ripping this out entirely. But I'll hold off for now.
