### ISSUE TITLE
Feature Request: Automatically jump to first section when performing :G

### ISSUE THREAD

**Issue by David-Kunz** [tpope/vim-fugitive#1846]
Hi @tpope,

Thanks for this great plugin, here's a small feature request.

## Current State

When executing `:G` , you will get the following split ("<<<< CURSOR" denotes the line of the current cursor):
```
Head: testbranch  <<<< CURSOR
Push: origin/testbranch
Help: g?

Untracked (1)
? test/jest.config.js


Unstaged (1)
D Jenkinsfile


Staged (1)
A test/Jenkinsfile
```

Problem: In all of my use cases I want to perform actions on the sections, so I always end up hitting `[[` to jump to the first entry of the first section.

## Proposal

When executing `:G`, you'll automatically jump to the first entry of the first section:

```
Head: testbranch
Push: origin/testbranch
Help: g?

Untracked (1)
? test/jest.config.js  <<<< CURSOR


Unstaged (1)
D Jenkinsfile


Staged (1)
A test/Jenkinsfile
```

Thanks and best regards,
David

**Comment by tpope** [comment]
Won't fix. Being simple and predictable is the priority. You might find `)` slightly easier to press than `]]`.
