### ISSUE TITLE
Feature request: populate `git reset` on pressing `X` on a commit

### ISSUE THREAD

**Issue by dakennguyen** [tpope/vim-fugitive#1847]
Hi TPope,

I'm myself using `Git reset --mixed` quite often, and I noticed that the behavior of `s` is `stage` if object is a file, or `push` to upstream if object is a commit. We also have `u` to `unstage` a file or `pull` a commit also.
Then, similar to these behaviors, is it possible for you to implement `X` to populate `Git reset <cursor-here> <commit-hash>^`, if the object is a commit?

Thank you very much!

**Comment by tpope** [comment]
I'm not sure those alternate `s` and `u` behaviors are long for this world, but as long as they're around I suppose we could throw `X` in there too. I think the cursor position should be the end of the line though. The default usage shouldn't leave an ugly double space in your `:` history, and it shouldn't fight you on more esoteric usages like `:Git reset <commit-hash>^ <path>`.

**Comment by dakennguyen** [comment]
That makes sense for me, too. Thank you!

**Comment by tpope** [comment]
Since `X` is basically `:Git checkout`, I'm already second guessing if `reset` was the correct move here. But it does seem more useful than `:Git checkout <commit-hash>^ .`, or any other natural `checkout` usage, so I'll allow it until a better idea comes along.

**Comment by odnoletkov** [comment]
@tpope what do you think about a dedicated reset map? Some examples with `ct`:

`ctt` --mixed reset commit under the cursor
`ctT` --hard reset (although this is probably too unsafe to map)
`ct<Space>`
`1ct<CR>` `:Git reset @{1}`

**Comment by tpope** [comment]
I want to retool `c` to be some kind of interactive map. Until that happens I'm not digging the existing hole any deeper.
