### ISSUE TITLE
[Feature Request] `Ggrepadd` / `Glgrepadd`

### ISSUE THREAD

**Issue by KSR-Yasuda** [tpope/vim-fugitive#1849]
Could you add `Ggrepadd` / `Glgrepadd` commands, result appending ver. of `Ggrep` / `Glgrep`,
as vim `grepadd` / `lgrepadd` for `grep` / `lgrep`?

**Comment by tpope** [comment]
The current implementation has `:Ggrep` as a bit of syntactic sugar for `:Git grep --open-files-in-pager`, and there's no good way I can think of to extend that to more commands without rethinking the design. Additionally, adding `:Ggrepadd` would have the minor downside of turning `:Ggr` into `E464: Ambiguous use of user-defined command`. Between these two problems, I don't think it's worth it.

Note that the most common use case here—grepping for mulitple things—can also be achieved via `:Ggrep -e pattern1 -e pattern2`.

**Comment by tpope** [comment]
Let me add I am open to hearing further arguments in favor of these commands. They won't be acted on in the near future but might inform future decisions.

**Comment by KSR-Yasuda** [comment]
Okay, I got it's not quite easy request.
At least I'm glad to know the way of giving multiple `git grep` patterns.

Or, perhaps I can use `:grepadd "PATTERN" $(git ls-files)`, if I do want the current quickfix list entries alive.
With quickfix list empowering plugins such as [vim-qfedit](https://github.com/itchyny/vim-qfedit), `grepadd` means more
(e.g. grep PATTERN1 -> Remove the hits for comment lines -> grepadd PATTERN2 -> ...).

I'll manage with the workarounds for now.
Thank you.
