### ISSUE TITLE
Support: Pipe precommit log into a new buffer

### ISSUE THREAD

**Issue by captainko** [tpope/vim-fugitive#1854]
Hi @tpope, first of all, thank you for creating such a badass plugin.

I have a precommit-hook script checking whether I can commit the staged files.
I would like to pipe the precommit output into a new buffer so that I can quickly navigate to the file by typing <kbd>gf</kbd>. I'm kind of new to (neo)vim so if there's a native way for handling it please let me know. Thank you.

This is my result by running `G commit`
![precommit-output](https://user-images.githubusercontent.com/32269291/135636716-a4d68116-ed38-4e80-96d8-a6688317bee9.png)

**Comment by captainko** [comment]
Reading through the help file, I see that fugitive already supports this by `Git -p {args}`

**Comment by tpope** [comment]
You can do this manually by calling `:Gsplit -` after `:Git commit`. If you want to automate it, you can use the `FugitiveChanged` event and check for the `'commit'` command and a failure exit status:

```vim
function! s:AfterGit() abort
  if !exists('*FugitiveResult')
    return
  endif
  let result = FugitiveResult()
  if !filereadable(get(result, 'file', '')) || get(result.args, 0, '') !=# 'commit' || !get(result, 'exit_status')
    return
  endif
  Gsplit -
endfunction

augroup my_fugitive_stuff
  autocmd!
  autocmd User FugitiveChanged call s:AfterGit()
augroup END
```

You can get a lot fancier than `:Gsplit -`.

**Comment by captainko** [comment]
Thanks @tpope, You saved me hours.
