### ISSUE TITLE
Instruction from README.markdown does not work..

### ISSUE THREAD

**Issue by rkouznetsov** [tpope/vim-fugitive#1855]
```
$ git clone https://tpope.io/vim/fugitive.git
Cloning into 'fugitive'...
fatal: unable to access 'http://tpope.io/vim/fugitive.git/': SSL certificate problem: certificate has expired
```
Probably LetsEncrypt certificate expired there...

PS Thank you for this great plugin!

**Comment by tpope** [comment]
Still happening? I can't reproduce. It is indeed possible LetsEncrypt screwed me over for a bit.

**Comment by tpope** [comment]
This is what I see on the certificate. Doesn't *seem* like anything happened recently.

```
Issued On	Saturday, September 11, 2021 at 10:49:02 PM
Expires On	Friday, December 10, 2021 at 9:49:01 PM
```

**Comment by tpope** [comment]
Until there's a second report I'll assume it's a problem on your end, yeah.
