### ISSUE TITLE
Make diff operations async

### ISSUE THREAD

**Issue by notpeelz** [tpope/vim-fugitive#1856]
I cloned a repo which contains [a lot of generated files](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts) (for distribution purposes). After tweaking a couple things and running the build script, a lot of (tracked) files were changed. Then I ran `:G` and my vim froze.  Several vim-fugitive mappings straight up caused my vim to become unresponsive and crash.

Profiling pointed me toward these functions:
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1  10.483934   0.317294  fugitive#BufReadStatus()
    4  10.009052   0.000234  fugitive#Execute()
    5  10.008251   0.012209  <SNR>147_JobExecute()
   13   9.997384   9.996672  fugitive#Wait()
     2   9.989659   0.000039  <SNR>147_LinesError()
```

Turns out `:G` was waiting 10s for this command to finish:
```
git -C /path/to/git/repo --literal-pathspecs diff --color=never --no-ext-diff --no-prefix
```

Running the same command manually confirms it:
```
$ time git diff
git diff  10.56s user 0.22s system 91% cpu 11.741 total
```

Obviously the easy fix would be to not use the git repo itself for storing and distributing so many files, but unfortunately this isn't my repo and I don't have control over that.

Would it be possible to make diff operations async?

**Comment by tpope** [comment]
Let's start by clarifying "crash". Did Vim terminate? What was the error message?

**Comment by tpope** [comment]
I took a look at what would be involved here, and that quickly turned into implementing it.

**Comment by notpeelz** [comment]
> I don't think "hanging", "froze", or "unresponsive" are the right words either. If you can regain control by pressing CTRL-C, then the correct word is "blocking". It's not malfunctioning; it's just waiting on something.

Ah, I was completely stuck because I have my CTRL-C remapped to `:confirm q<CR>`.

> I took a look at what would be involved here, and that quickly turned into implementing it.

Thanks, that patch makes it a whole lot more responsive.
