### ISSUE TITLE
Seeing `E716: Key not present in Dictionary: "stdout"` on latest master

### ISSUE THREAD

**Issue by gibfahn** [tpope/vim-fugitive#1857]
On HEAD (bcf7478e6be9c8e425c0f9fb224821748132d4c3) I see:

```
Error detected while processing function <SNR>108_Do[42]..<SNR>108_ReloadStatus[2]..<SNR>108_ReloadStatusBuffer[6]..fugitive#BufReadStatus[316]..<SNR>108_StageInline:
line   47:
E716: Key not present in Dictionary: "stdout"
E15: Invalid expression: fugitive#Wait(b:fugitive_diff[info.section]).stdout
Press ENTER or type command to continue
```

If I `git reset --hard` to a67854368ea9810936d57e3fea00a4c05bf47c26 (previous commit), then the error goes away.

Using latest Neovim, NVIM v0.5.1 Release

Refs: https://github.com/tpope/vim-fugitive/issues/1563

**Comment by tpope** [comment]
I have narrowed this down to the Neovim bug fixed in https://github.com/neovim/neovim/commit/3c081d028062f793b63b8689f854bbea30e15752. Since it's immortalized in 0.5.0 and 0.5.1, I'll find a workaround.

**Comment by romariolopezc** [comment]
I just installed `neovim-git` and indeed is fixed

Thanks!
