### ISSUE TITLE
fugitive does not play well with custom `isfname`

### ISSUE THREAD

**Issue by t-b** [tpope/vim-fugitive#1858]
I'm a happy vim-fugitive user since many years. But recently I broke it.

I had set

```viml
" Use *nix pattern from documentation without =
set isfname=@,48-57,/,.,-,_,+,,,#,$,%,~
```

in my vimrc (NVIM v0.5.0 on Windows).

But that breaks opening old revisions opened via `Git blame`.

If that is not supported fine with me, just bailing out would be better though.

**Comment by tpope** [comment]
And what does "broken" even mean?
