### ISSUE TITLE
Split is always vertical

### ISSUE THREAD

**Issue by eyalk11** [tpope/vim-fugitive#1860]
Hi,

I use the last version of fugitive.
When either typing `o` or `gO` on the line `diff --index` it always splits vertically which I don't like.
Also `<CR>` split vertically. 

I have : 
```
set splitbelow
set splitright
```
if matters

**Comment by tpope** [comment]
You're sure you correctly tried `horizontal`? I forgot about some nuance in my first comment but `diffopt=horizontal` should force it 100% of the time.

https://github.com/tpope/vim-fugitive/blob/2e66b3ad05d85f09d870f82671b8503cf8fa4297/autoload/fugitive.vim#L6243-L6244
