### ISSUE TITLE
Git blame 'o' - "E21: Cannot make changes, 'modifiable' is off" and no colors in blame window

### ISSUE THREAD

**Issue by bsdmp** [tpope/vim-fugitive#1864]
I'm running latest vim-fugitive on OpenBSD 7,0, vim version:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 11 2021 14:49:56)                                                                         
Included patches: 1-3456                                             

When I use ":Git blame" new vertical window is open, when I select a commit in that window and press "o", it shows  an error:

E21: Cannot make changes, 'modifiable' is off

This message shown for every key binding from documentation in fugitive.txt for ":Git blame".

Also, my TERM is tmux-256color, but I see no colors in :Git blame window.

**Comment by tpope** [comment]
Smells like a broken install. You're missing the `ftplugin/` and `syntax/` directories.

**Comment by tpope** [comment]
You might need `filetype plugin indent on` in your vimrc.

**Comment by bsdmp** [comment]
Yes, it works now, thank you.
