### ISSUE TITLE
Status Window: Inconsistency between `)` and `(`

### ISSUE THREAD

**Issue by somini** [tpope/vim-fugitive#1867]
On the status window, `)` takes you to the start of the line, while `(` takes you to the end of the item.

Technically this doesn't really matter, since the other shortcuts work based on the current line, it's a cosmetic issue only.

**Comment by somini** [comment]
Is it worth it to open a new issue in @neovim?

**Comment by tpope** [comment]
No, regardless of the root cause, Fugitive was doing the wrong thing. I think it comes down to a difference in option defaults between Vim and Neovim.

**Comment by tpope** [comment]
`:help 'startofline'`.
