### ISSUE TITLE
BufEnter Auto Command not Calling ReloadStatusBuffer via ReloadWinStatus

### ISSUE THREAD

**Issue by hurricanehrndz** [tpope/vim-fugitive#1869]
When I enter the Git status (index) buffer after staging changes, no changes are reflected within the index Buffer.

As far as I can tell after entering the index buffer, the ReloadWinStatus function is called but all conditionals that would call ReloadStatusBuffer are skipped.

What is curios is that the AutoCommand for FocusGained does work, but rather than calling ReloadWinStatus, fugitive#DidChange is called. I tested calling said function from BufEnter and that seem to work.

**Comment by tpope** [comment]
What is `:echo b:fugitive_type` in the status buffer? The behavior of that recently changed and could be the culprit.

**Comment by hurricanehrndz** [comment]
Here is the results

```
:ls!
  1  a   "dot_config/nvim/lua/hrndz/theme.lua" line 0
  3 %a-  "~/.local/share/chezmoi/.git/index" line 1
:echo b:fugitive_type
index
```

**Comment by hurricanehrndz** [comment]
Both commits make no difference. The index status is refresh after toggling focus or refreshing via `:e`.

Thanks again for your help

**Comment by hurricanehrndz** [comment]
Changes (hunks) are being stage via GitSigns. So the workflow is as followd:

1. Open File I wish to edit
2. Open Git Status in vsplit
3. Go back to buffer hosting file with changes
4. Stage Hunk via GitSigns keybind
5. Go back to Git status buffer

Status buffer has no updates.

**Comment by tpope** [comment]
Oh, if another plugin is doing the staging behind our back, then that plugin will need to call `fugitive#DidChange()`.

**Comment by hurricanehrndz** [comment]
Okay, sounds perfect! Thanks again for your time, and the amazing work you have done. And that makes total sense.
