### ISSUE TITLE
Add context above/below current hunk in inline diffs

### ISSUE THREAD

**Issue by Hubro** [tpope/vim-fugitive#1876]
Currently the inline diffs in Fugitive show 3 lines above and below each hunk as context. This is sufficient for 90% of cases, so I don't want to change the default, but some times I want a little more context above or below the hunk so I can better orient myself.

Sublime Merge also has 3 lines of context above/below the current change, but the top or bottom border can be dragged to show additional context. For example:

![image](https://user-images.githubusercontent.com/597206/138596069-da54ee1c-de11-4ca8-a86b-1f3db057acfb.png)
![image](https://user-images.githubusercontent.com/597206/138596070-2349e027-b68b-4f15-a9ee-0f63bcad83eb.png)

Is there currently any way to accomplish this with inline diffs in Fugitive?

If not, I would like to request a feature to do this.

2 new commands:

- Add one line of context to top of current hunk
- Add one line of context to bottom of current hunk

Perhaps bind these to `da` (diff above) and `db` (diff below). Users could invoke these like `20da` to add 20 lines of context at the top of the current inline diff.

Closing and re-opening the current inline diff would reset the extra context for each hunk (`==`).

**Comment by mihaicristiantanase** [comment]
You can always do a `:G config diff.context 10` to change the number of lines of context (10 in this case) and a `:G config --unset diff.context` to bring back the default value. The nice thing about this is that the Git status window refreshes immediately to reflect the change. And, if you have only one hunk expanded, it might just be what you were looking for.

It would be nice if these commands reach the plugin as key mappings, but that's for Tim Pope to decide.
