### ISSUE TITLE
Error on ZZ when committing

### ISSUE THREAD

**Issue by mdedonno1337** [tpope/vim-fugitive#1881]
When closing the commit edit message dialog (`Gedit:` -> stage my files -> cvc) with the `ZZ` binding, I have:

```
"~/dotfiles/.git/COMMIT_EDITMSG" 43L, 1767C written
Error detected while processing function <SNR>169_ReloadTabStatus[12]..<SNR>169_ReloadWinStatus[11]..<SNR>
169_ReloadStatusBuffer[6]..fugitive#BufReadStatus[316]..<SNR>169_StageInline:
line   47:
E716: Key not present in Dictionary: stdout
Press ENTER or type command to continue
Error detected while processing function <SNR>169_ReloadTabStatus[12]..<SNR>169_ReloadWinStatus[11]..<SNR>
169_ReloadStatusBuffer[6]..fugitive#BufReadStatus[316]..<SNR>169_StageInline:
line   47:
E15: Invalid expression: fugitive#Wait(b:fugitive_diff[info.section]).stdout
```

This error is not present when quitting the edit mode with `<Leader>q` for example.

**Comment by tpope** [comment]
There's been recent fixes here; are you on the latest Fugitive?

What Vim version?

**Comment by mdedonno1337** [comment]
Should be on master, commit 174fd6a, with neovim 0.4.4

**Comment by tpope** [comment]
That commit isn't a fix for anything; it's just an extra error message for debugging. If it works, that's because it's _missing_ something from master.

What if you remove the `has('nvim-0.5')` from this line?

https://github.com/tpope/vim-fugitive/blob/174fd6a39b7e162ca707c87582d1b7979fba95f4/autoload/fugitive.vim#L266

**Comment by mdedonno1337** [comment]
Working without the `has('nvim-0.5')`.

On master, the issue is only visible if we have the staged hunk expanded.
I usually do a `i` between all the hunks, stage them, keep some of them open to double-check.
