### ISSUE TITLE
Configure fugitive-summary view to always show sections: untracked, unstaged, staged, and unpushed

### ISSUE THREAD

**Issue by sotte** [tpope/vim-fugitive#1883]
Hey there! I've been a daily user for years. So first of all: thanks for the great plugin!

I was wondering if it's possible to customize the fugitive-summary view. I always want to display the sections "untracked", "unstaged", "staged", and "unpushed" even if there are no files/commits for the given section.

**Comment by tpope** [comment]
Not currently supported. I'll keep it in mind for future expansions of configurability.
