### ISSUE TITLE
:Git blame fails in VersionCheck

### ISSUE THREAD

**Issue by keyslapper** [tpope/vim-fugitive#1889]
Just updated from vim-fugitive 3.3 to 3.5 and I'm seeing the following when I try :Git blame:
```
Error detected while processing function fugitive#Command..<SNR>95_VersionCheck..fugitive#GitVersion..<SNR>95_JobExecute:
line   35:
E677: Error writing temp file
Error detected while processing function fugitive#Command..<SNR>95_VersionCheck..fugitive#GitVersion:
line    3:
E171: Missing :endif
Error detected while processing function fugitive#Command..<SNR>95_VersionCheck:
line    3:
E171: Missing :endif
Press ENTER or type command to continue
```

I switched to the v3.4 tag and I'm still seeing the same behavior.  When I switch to v3.3, I don't have any issues.

`VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 22 2018 06:34:52)`
Yes, I know that's an old version of Vim, but I don't have the option of updating it on this host.

I generally use several other plugins, but disabling all of these has not resolved the problem, so I don't think this is a conflict with another plugin.

Thank you - this really is a must-have plugin for me, and I do appreciate the work that goes into it.

Lou

**Comment by tpope** [comment]
Fixed. The goal is to support down to 7.3.000, although that is starting to get untenable and probably won't last for much longer.
