### ISSUE TITLE
Completed remove `q` key map

### ISSUE THREAD

**Issue by QiBaobin** [tpope/vim-fugitive#1890]
Currently we would show a message for `q` is removed if there is no mapping of `q` , it's total useless, and would stop us to use native `q:`, `q/` etc. Why don't we completely remove this setting as we always can lookup key mapping by `?` ?

```
 if empty(mapcheck('q', 'n'))
      nnoremap <buffer> <silent> q :<C-U>echoerr "fugitive: q is removed in favor of gq (or :q)"<CR>
 endif
```

**Comment by tpope** [comment]
>  it's total useless

It has a very clear use: saving people who used to rely on the map from accidentally ending up in macro recording mode, a very confusing mode to be in. At 6 months old, I _guess_ enough time has passed that we can remove it, but there will definitely be infrequent updaters that never saw the error.
