### ISSUE TITLE
Change in behaviour of Gdiffsplit and Gvdiffsplit since 8e4a677

### ISSUE THREAD

**Issue by myitcv** [tpope/vim-fugitive#1894]
Firstly, thank you for all your excellent Vim plugins, @tpope 

### 8e4a677

At 8e4a677 I observe the following behaviour:

1. `:Gdiffsplit` (no args) results in a vertical split with the working tree version on the RHS 
2. `:Gvdiffsplit` (no args) results in a vertical split with the working tree version on the RHS
3. `:Gdiffsplit origin` results in a vertical split with the working tree version on the RHS 
4. `:Gvdiffsplit origin` results in a vertical split with the working tree version on the RHS 

The only surprising behaviour here is the vertical split for Points 1 and 3, because I'm not calling the `v` version of the command. But by accident what I want/need because I always want a vertical split 😄 

### e82332e

At current tip (e82332e) I observe the following behaviour:

1. `:Gdiffsplit` (no args) results in a vertical split with the working tree version on the RHS  (_no change_)
2. `:Gvdiffsplit` (no args) results in a vertical split with the working tree version on the RHS (_no change_) 
3. `:Gdiffsplit origin` results in a **horizontal** split with the working tree version at the **top** (_change emphasised_)
4. `:Gvdiffsplit origin` results in a vertical split with the working tree version on the **LHS** (_change emphasised_)

Notwithstanding the previous surprising behaviour, the additional surprise here are those emphasised changes in points 3 and 4. 

### Issues/bugs?

Focussing on the behaviour observed with e82332e my understanding is that the following are issues:

1. `:Gdiffsplit` (no args) appears to be wrong; it should create a horizontal split
2. `:Gdiffsplit origin` appears to incorrectly place the working tree version at the top; it should be on the bottom
3. `:Gvdiffsplit origin` appears to incorrectly place the working tree version on the LHS; it should be on the RHS

Or am I holding this wrong?

**Comment by tpope** [comment]
These are deliberate and documented changes. See d523feebe99bb93a9309ef83cbac2b71ac408c36, c9aaf78541a02cd9e7a9a1f6fb77e525609cdadd, and a6be4a301c9e095c9eaf14d5d2b6f691c9bb68f8.

**Comment by myitcv** [comment]
@tpope thank you for confirming and referencing the changes themselves.
