### ISSUE TITLE
Staging hunk

### ISSUE THREAD

**Issue by dortin42** [tpope/vim-fugitive#1895]
![imagen](https://user-images.githubusercontent.com/20261354/143892349-b6e4baf3-23ba-4ee1-a995-150b53dbc190.png)

Neovim 0.5.1
Latest version of fugitive

Steps:
- `:G`
- `>` on a modified file
- `-` to stage the hunk

**Comment by tpope** [comment]
Fixed in #1857. Make sure you're on the latest.
