### ISSUE TITLE
MacVim + Vim Fugitive Cursor Bug

### ISSUE THREAD

**Issue by amadeus** [tpope/vim-fugitive#1896]
I am not entirely sure if this issue is related to vim fugitive or MacVim specifically, or some combination thereof, but I find when I do a `git push` the output ends up triggering a weird state with the cursor. I posted an issue about it with MacVim, including a video of it, but thought I would add a post here to see if you might have any insight into what could be going on here:

https://github.com/macvim-dev/macvim/issues/1207

Is vim fugitive doing something here that I should let the MacVim devs know about to fix this?

**Comment by tpope** [comment]
One possibly related thing to try is replacing all occurrences of `sleep!` with `sleep`.

**Comment by amadeus** [comment]
I just tried that and it seemed to have no effect on that bug, unfort

**Comment by tpope** [comment]
A big red flag is the missing "press ENTER" prompt after pushing. Are you on the latest Fugitive? I vaguely recall an old Fugitive bug that could cause this.

Closing until this is demonstrably a Fugitive issue.

**Comment by amadeus** [comment]
Oh yeah, I update my plugins daily, fugitive is def up to date and I've been seeing this issue for a while now.

I don't think it's technically `caused` by fugitive per se, just figured you might have a wee bit of insight into what may be going on, since I'm pretty sure it's related to MacVim's renderer somehow.

Anyways, no worries, thanks anyways for giving it a bit of a think!

**Comment by tpope** [comment]
The lack of "press ENTER" might be a Fugitive bug, and fixing it would likely indirectly solve the cursor issue.

1. What happens when the status window isn't open?
2. What happens when you try it in MacVim in the terminal? That is, try it in `/Applications/MacVim.app/Contents/bin/vim`.
3. Can you reproduce with a different command? `:Git push` is an extremely annoying command to test with.

**Comment by amadeus** [comment]
Did a bit more digging, and ran an environment with fugitive as the only plugin resulted in the `press ENTER` prompt showing up perfectly, so this is definitely not in any way related to fugitive, just some other plugin causing some issues, so will dig more.
