### ISSUE TITLE
Collapse diff view under status?

### ISSUE THREAD

**Issue by harrisoncramer** [tpope/vim-fugitive#1900]
Thank you for this awesome plugin! 

Quick question--when viewing the status of your code, you can hover over a given file that's been staged/unstaged, and get information about the diff by pressing `i`.

<img width="593" alt="Screen Shot 2021-12-05 at 4 01 26 PM" src="https://user-images.githubusercontent.com/32515581/144763768-8a6e8cf1-c453-444a-a014-90c47e465579.png">

Is it possible to collapse this diff again? Here's a screenshot of what I'm referring to. Thanks!

**Comment by tpope** [comment]
`=` toggles inline diff expansion.
