### ISSUE TITLE
adding file to gitignore broken

### ISSUE THREAD

**Issue by darzok0914** [tpope/vim-fugitive#1901]
Hi, I just realized the {number}gI command to add a file into the .gitignore seems to be broken. it opens the .gitignore but doesn't append the files to ignore

**Comment by tpope** [comment]
Works for me. Please provide exact instructions to reproduce.

**Comment by darzok0914** [comment]
sorry I think I was misusing the plugin, this is what I was doing;

Create new files, open git status section, place cursor onto the "untracked" section and do 3gI, it opens the .gitignore but doesn't append the files into it.

I think I got used to staging files by pressing s onto the unstaged keyword so that is stages everything and somehow I applied the same logic here.

**Comment by tpope** [comment]
The count is a flag only. `1gI` is the same as `3gI`. Both operate on the current line only.
