### ISSUE TITLE
E1208: -complete used without -nargs

### ISSUE THREAD

**Issue by diegoulloao** [tpope/vim-fugitive#1904]
I updated to neovim 0.6 and I'm getting this error when opening neovim:

```
Se ha detectado un error al procesar /Users/diego/.vim/plugged/vim-fugitive/plugin/fugitive.vim:
línea  459
E1208: -complete used without -nargs
línea  460
E1208: -complete used without -nargs
línea  464
E1208: -complete used without -nargs
línea  468
E1208: -complete used without -nargs
Pulse INTRO o escriba una orden para continuar
```

**Comment by tpope** [comment]
Upgrade Fugitive.

**Comment by Maxattax97** [comment]
I updated my plugins and I am still having this issue.

**Comment by tpope** [comment]
In all likelihood you botched the upgrade. Open the `plugin/fugitive.vim` from the error message and double check the `Version:` header at the top.

**Comment by Maxattax97** [comment]
Well, `dein`'s really screwed me again, I think it's about time to switch.

I completely reinstalled all my plugins and sure enough, it works. Sorry to bother with my user error!

P.S. I love all your plugins :heart:
