### ISSUE TITLE
Does not work with a symbolic link `.git`

### ISSUE THREAD

**Issue by kevinptt0323** [tpope/vim-fugitive#1906]
### Environment

* Debian 5.10.46
* Vim 8.1

### Reproduction

```sh
mv .git ../git-backup
ln -s ../git-backup .git
```

```
(In vim)
:Git status
:Git blame
```

### Expect
Get status of the git repository.

### Actual
```
fugitive: core.worktree is required when using an external Git dir
```

**Comment by ckclark** [comment]
+1 due to the recent [git-repo change](https://gerrit-review.googlesource.com/c/git-repo/+/323695).

**Comment by tpope** [comment]
Set `core.worktree` to the path to the root of the repository. It's required. That's why the error message says it's required. The fact it appears to work without it for simple operations is irrelevant because Fugitive does more than simple operations.

**Comment by kevinptt0323** [comment]
Thank you. Here's the command I used to fix this issue:
```bash
git config core.worktree \
  "$(realpath --relative-to="$(git rev-parse --git-dir)" \
  "$(git rev-parse --show-toplevel)")"
```

**Comment by myshen** [comment]
> Thank you. Here's the command I used to fix this issue:
> 
> ```shell
> git config core.worktree \
>   "$(realpath --relative-to="$(git rev-parse --git-dir)" \
>   "$(git rev-parse --show-toplevel)")"
> ```

Double check that `core.worktree` is set afterward. If realpath fails you could end up with an error like `fatal: cannot chdir to ''` when running `git rev-parse`
