### ISSUE TITLE
New-Window-Opening Git Commands Fail on 1-Line-Height Window

### ISSUE THREAD

**Issue by KSR-Yasuda** [tpope/vim-fugitive#1907]
`G` commands that opens a new window can fails if the focused window height is too small.

Couldn't you enlarge the focused window height if `G` command fails window splitting?

For example,

1. *`:set noequalalways`*
    - Set not to resize windows on window splitting
2. `:botright G`
    - Open Fugitive status window below
3. `:1 wincmd _`
    - Set the Fugitive status window height 1 line
4. `:G commit --allow-empty`
    - Run a Git command with window open
    - It fails to create new window, due to the available window height

It is natural behavior of window splitting and not a big problem for simple Git commands.

However, it is quite troublesome for complecated Git commands such as `G rebase`:
a new window querying some input goes somewhere.

I often opens `G! -p log --graph` window and `G` window horizontally,
and runs rebase command on the log graph window.

In case, git rebase commands sometimes opens windows in rebase sequence,
and reduces the `G` status window.

Now, if Git tries to open a window on the `G` status window of 1-line height, the new window goes away.
Working git rebase sequence is left unfinished
In fixing git rebase conflict is likely to make this unexpectedly.

```text
+---------------------------------+
|                                 |
|                                 |  <- Run git rebase commands on this window
|   `G! -p log --graph` window    |     This is preview window (because of `G!`),
|                                 |     and is set `windowfixheight`
|                                 |     that makes this problem more likely to happen
+---------------------------------+
|            `G` window           |  <- Gradually this window gets narrowed by git commands to be 1-line height
+---------------------------------+
```

**Comment by tpope** [comment]
If `:Git` fails at splitting, then `:spilt` would also fail at splitting. Do you think that should be fixed too? If not, what makes `:Git` different?

**Comment by KSR-Yasuda** [comment]
`:Git` command does some sequence of operations, while `:split` is just one action.

Especially, `:G rebase` is terrible.
If it fails in the progress of rebasing (for example, on editing message for conflict resolving),
how can user go back to the rebase progress?

In doing complicated operation such as git rebase,
this window splitting error makes the git operation more confused, don't you think?

**Comment by tpope** [comment]
An aborted rebase operation can be recovered from with `:Git rebase --continue`.  Sounds like the real issue is that the `E36` aborts further processing and prevents seeing the Git error message explaining that.

Alas, fixing that is actually harder than a band-aid resize solution, so we'll go with your proposed solution for now.

**Comment by KSR-Yasuda** [comment]
Thank you for the patch.  It will help me a lot.

> An aborted rebase operation can be recovered from with `:Git rebase --continue`.

Now we don't need to discuss this further with your patch avoiding the error itself,
but I wonder whether `git rebase --continue` can recover errors in conflict resolution:
if the window to hear message for the conflict-resolve commit gets lost?

I had occasionally got lost in such cases.
That's why I had raised this issue.
