### ISSUE TITLE
Window Focus Moves Weirdly in Rebasing

### ISSUE THREAD

**Issue by KSR-Yasuda** [tpope/vim-fugitive#1908]
Open `G! -p log --graph` window, and do interactive rebase by shortcut `ri`.
It opens a new window to query rebase-target commits handling.

After editing the window and exiting, *the window focus moves to the next window.*

In case the window is `:terminal` and is active (i.e. not suspended by `<C-w> N`),
Fugitive internal commands is input into the terminal
(Probably Fugitive is calling some `feedkeys()` or such commands?).

![Screenshot](https://user-images.githubusercontent.com/31273423/147304842-f4d7da1b-e8a5-4372-b386-fae98a6b4a0e.png)

----

I think the window focus move is the main problem.

Could you fix it to stay the window that Fugitive command has started?

I suppose perhaps it may be difficult because Fugitive doesn't know how the operating git command open new windows...

**Comment by tpope** [comment]
I can't reproduce the window focus anomaly. With `'splitbelow'` set, Vim always focuses the previous window. I'll leave it to you to troubleshoot your setup.

I can reproduce the `feedkeys()` portion of the problem if I manually rearrange windows. Pushing a fix for that.

**Comment by KSR-Yasuda** [comment]
> I can reproduce the `feedkeys()` portion of the problem if I manually rearrange windows. Pushing a fix for that.

Thank you!  At least, this helps `:terminal`.

> I can't reproduce the window focus anomaly. With `'splitbelow'` set, Vim always focuses the previous window. I'll leave it to you to troubleshoot your setup.

I set `splitbelow` and `splitright`.

Could you try opening git log-graph in *preview window*? (i.e. `:G! -p log --graph`, do not forget `!`)

Opening a normal window             (i.e. simple `:G` command), window focus stays on the log-graph window;
however, *preview* window (i.e. `:G!` command) does not stay but moves to the next window.

I usually open log-graph in preview window because it's useful to refresh the graph...

**Comment by tpope** [comment]
I didn't test with a preview window, that could be what I missed. It's moot, though, as I'm not going to reinvent window focusing for an edge case.

**Comment by KSR-Yasuda** [comment]
Okay, for now, I'm pleased with your fix for `:terminal`:
at least, it doesn't go wrong except window focus.
Thank you.
