### ISSUE TITLE
`:Gdiffsplit` and `:Git blame` scrollbind chaos

### ISSUE THREAD

**Issue by kaddkaka** [tpope/vim-fugitive#1910]
Fugitive version: `da30818d177b1a04f2ed0eb253e1414bdb19e957`
Neovim release: `NVIM v0.6.0`

Is there an intended way to show `gdiffsplit` and the `git blame` gutter at the same time? Currently they seem to be competing about the scrollbind in some way such that the buffers get strangely out of sync.

**Comment by tpope** [comment]
There is not. I don't think syncing 2 diff buffers with a non-diff buffer is even possible in Vim.
