### ISSUE TITLE
Turn off folding for Gdiffsplit

### ISSUE THREAD

**Issue by kaddkaka** [tpope/vim-fugitive#1911]
`:Gdiffsplit` opens a fugitive buffer for the index in split view, but it also folds the content in both the fugitive buffer and original buffer with `foldmethod=diff`. When I add things, the fold gets updated immediately, making it difficult to understand what's going on. I would prefer to not have any folding at all.

How do I disable folding in gdiffsplit?

Using Neovim 0.6.0 and fugitive `da30818d177b1a04f2ed0eb253e1414bdb19e957`

**Comment by tpope** [comment]
It's just `:diffsplit`. See `:help 'diffopt'`.

**Comment by kaddkaka** [comment]
So `:Gdiffsplit` uses `:diffsplit` as implementation to show the split and the options can therefore be controlled via `:diffopt`?

The only options I find related to fold in `diffopt` are `context` and `foldcolumn`, but I'm not sure how they can be used to turn off folding. All help appreciated! :)
