### ISSUE TITLE
[Feat] [neovim] Display diff in a floating window

### ISSUE THREAD

**Issue by protiumx** [tpope/vim-fugitive#1913]
Hi everyone. First of all, thank you for this awesome plugin.
I was wondering if it would be possible to show diffs in a floating window.
Take this as example, using [vim-floaterm](https://github.com/voldikss/vim-floaterm)

![Screenshot 2021-12-29 at 12 23 33](https://user-images.githubusercontent.com/43855513/147657372-edb1a18a-f2fc-41b1-b237-e7ccc6a84bb8.png)

Would it be possible to use [neovim open window](https://neovim.io/doc/user/api.html#nvim_open_win()) to show the diff?

**Comment by tpope** [comment]
I'm not an expert on this API, but my understanding is that is low level, and would require a considerable amount of support code to make it usable. I welcome a demonstration to the contrary.
