### ISSUE TITLE
`vim` freezes on some `fugitive` commands

### ISSUE THREAD

**Issue by x-yuri** [tpope/vim-fugitive#1917]
Steps to reproduce:

`a.sh`:

```sh
mkdir a
cd a
git init
echo a > a && git add a && git commit -m a
echo 'line 1
line 2' > b && git add b && git commit -m b1
echo 'line 11
line 2' > b && git add b && git commit -m b2
echo 'line 11
line 22' > b && git add b && git commit -m b3
```

```
$ sh ./a.sh
$ cd a
$ vim +'Gedit :' +'tabe b' +tabn
```

1. `:G rebase -i --root`
2. Swap the last two commits.
3. `ZZ`
4. `ra`

At this point it freezes. To unfreeze: `o`, `l` or `Enter`.

It happens [here][a] (`:checktime`). A `vim` bug? Apparently it wants to ask me if I want to reload `b`. Not sure how to make it visible to confirm it.

But it doesn't happen with any commit history. E.g. not with this one:

```sh
mkdir a
cd a
git init
echo a > a && git add a && git commit -m a
echo 'line 1
line 2' > b && git add b && git commit -m b1
echo 'line 2
line 1' > b && git add b && git commit -m b2
```

```
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 25 2021 11:17:40)
```

[a]: https://github.com/tpope/vim-fugitive/blob/v3.6/autoload/fugitive.vim#L3817

**Comment by tpope** [comment]
Try `:set autoread`.

**Comment by x-yuri** [comment]
With `autoread` it doesn't freeze.
