### ISSUE TITLE
:Git shows repository created by `repo` as bare

### ISSUE THREAD

**Issue by alevkoy** [tpope/vim-fugitive#1920]
I have .git as a symlink to a worktree stored elsewhere. When I run `:G`, the status buffer shows "Bare: yes" and does not show things like the unpushed commits or modified files. Consequently, the status buffer bindings aren't much use. `git` seems unaffected, and other operations I've tried like `:Gclog` seem to work OK.

I see from some other issues that using `gitdir: other/dir` is preferred to .git as a symlink. I get the same results when I try to use `gitdir`.

### Versions
* vim-fugitive: `b1c3cdf`
* vim: 8.2, patches 1-814
* git: 2.31.0

Also reproduced with vim-fugitive `0e35c9b`, vim 8.1/1-2269, git 2.34.1

**Comment by tpope** [comment]
What does `:echo FugitiveConfigGetAll('core.bare')` show?

**Comment by aswild** [comment]
I discovered a similar (possibly related) issue today, caused by my ".git" directory being a symlink to an actual gitdir somewhere else. In my environment, the .git symlink is set up by the Google `repo` tool (https://gerrit.googlesource.com/git-repo), which uses some unconventional ways of checking out git repos.

Specifically, my setup broke on repo's latest 2.19 release with the commit ["migrate worktree .git/ dirs to symlinks"](https://gerrit.googlesource.com/git-repo/+/2a089cfee4a3eb0c28cfb441861fc1fcb05797d3) - that commit message has some examples of how the symlinks are set up.

After some tracing, it looks like these are some key behaviors when trying to run `:Gdiff`
1. `FugitiveWorkTree` gets called at various points, which in turn calls `FugitiveGitDir`
2. `FugitiveGitDir` calls `FugitiveExtractGitDir`, which does some searching to find the `/.git` directory, and if that dir is a symlink, it calls `resolve` on the path to convert the symlink (which is inside the actual worktree) to its real path (which is separate from the worktree and contains no "link" back to where the worktree lives)
3. The now absolute and resolved path from `FugitiveGitDir` is passed to `s:Tree(path)`, which does logic to find the worktree

In step 3, if the 'gitdir' file exists, such as when using `git worktree`, things are fine, but given the weird way that `repo` sets up things, there's no way for fugitive to find the worktree solely from the .repo/projects/foo.git gitdir. `FugitiveWorkTree` ends up returning an empty string and the rest of `:Gdiff` winds up broken.

If I remove the `resolve` call from `FugitiveExtractGitDir` on line 411, then `:echo FugitiveGitDir()` returns the `<worktree>/.git` path that I expect, and `:Gdiff` works as expected, but `:G` still shows "Bare: yes" when it probably shouldn't.

For me, `:echo FugitiveConfigGetAll('core.bare')` returns `[]` (which seems correct, the .git/config file does not include core.bare)

**Comment by tpope** [comment]
> the rest of `:Gdiff` winds up broken.

Broken how?

**Comment by aswild** [comment]
> Broken how?

When running `:Gdiff` with no arguments, it opens a directory listing in the split pane and then diffs that with the actual file that was open. In my case, the directory listing is provided by the NERDTree plugin, as if I had run `:vsplit .` and then `:windo diffthis`.

When running `:Gdiff HEAD` (or some other git revision), the diffsplit window that's opened is filled with a `git show` like output (according to strace, it's `git show` with a long custom format string which I found in `fugitive:BufReadCmd` line 3059)

I didn't get far enough when tracing to see what exact code path is leading to this behavior, but I suspect that not finding the worktree is the first part where things went wrong.

**Comment by aswild** [comment]
Other interesting notes on reproducing it:

```
git clone https://some-repo
mv some-repo/.git some-repo.git
cd some-repo
ln -s ../some-repo.git .git
vim somefile
```

If I edit somefile, normal git commands work fine. If I run `:Gdiff` I get and error `fugitive: core.worktree is required when using an external Git dir`. Hooray, a proper error message is supported here. But if I edit .git/config (really ../some-repo.git/config) and remove the core.bare = false line entirely, then normal git commands still work, but `:Gdiff` behaves as described above.

I realize this is quite the corner case so I guess what I'm asking is whether this is something fugitive can/should support better, or if the latest release of `repo` is just setting up git directories/worktrees "wrong" and a bug should be filed against that project instead.

Thank you for your time, and for this excellent vim plugin.

**Comment by aostruszka** [comment]
> I realize this is quite the corner case so I guess what I'm asking is whether this is something fugitive can/should support better, or if the latest release of repo is just setting up git directories/worktrees "wrong" and a bug should be filed against that project instead.

Git does not have problem with the way repo sets up repositories (I'm hit by this change in repo too), so I guess this is not a problem with repo.  I'm not sure why we can't take directory where .git is as a work tree (even if it is a symlink), but I don't know git internals enough to speak.

**Comment by tpope** [comment]
Make a separate issue for the `repo` thing. Sounds like it has nothing to do with the titular ":Git shows repository as bare".

Closing this until I have a response from OP.

**Comment by alevkoy** [comment]
As it happens, I also use `repo` and initially discovered this issue in that context. I then reproduced via an experiment outside repo similar to aswild's.

For `:echo FugitiveGetConfigAll('core.bare')`, I have a few different results in different setups:
* vim-fugitive `b1c3cdf` setup listed above, outside `repo`, using `gitdir` or symlink: `false`
  * In this setup, when I try `:G`, instead of seeing a bare repo status buffer, I get the error message, "fugitive: core.worktree is required when using an external Git dir"
 * Same fugitive, vim, git, inside `repo` checkout (symlink): `[]` (bare repo status buffer)
 * vim-fugitive `0e35c9b` setup listed above, outside repo, `gitdir` or symlink: `['false']`
 * Same fugitive, vim, git, inside `repo` checkout (symlink): `[]` (bare repo status buffer)

**Comment by tpope** [comment]
Is there something I can try `repo` out on other than the entire dang source code to Android?

**Comment by alevkoy** [comment]
Something slightly smaller (took me ~5 minutes to download and build): https://chromium.googlesource.com/chromiumos/docs/+/HEAD/developer_guide.md#get-the-source-code
```
cd ~/src/chromiumos
# Without -g minilayout, this will take much longer
repo init -u https://chromium.googlesource.com/chromiumos/manifest -g minilayout
repo sync -j4
cd src/third_party/chromiumos-overlay
vim
```

If I find a smaller `repo` project, I'll let you know.

**Comment by aswild** [comment]
My personal Yocto projects use a smaller manifest than chromiumos, and it's not several GB of prebuilt LLVM toolchains either.

```
cd some-new-empty-directory
repo init -u https://github.com/aswild/yocto-manifests -m newbs.xml
repo sync
```

---
For @alevkoy @aostruszka and any other `repo` users who find this issue, there's a couple workarounds:
1. Roll back to repo version 2.18, delete .git symlinks, and repo sync again
a. `repo forall -c 'rm .git' && git -C .repo/repo checkout v2.18 && repo sync`
b. This will recreate the per-project .git directories rather than .git symlinks
2. Use repo's new worktree mode, which uses "git worktree" to checkout projects (.git is a `gitdir: /foo/bar.git` file)
a. Run `repo init --worktree -u ...`
b. Unfortunately this requires recreating your workspace from scratch, you can't convert an existing one, and
c. worktree mode is still experimental and there's still some bugs (https://bugs.chromium.org/p/gerrit/issues/detail?id=15224&q=component%3Arepo)

**Comment by dramborleg** [comment]
I'm also stuck using google-repo and ran into this just now with Ggrep/Glgrep. When you go to a result it appears to send you to a fugitive buffer rather than the actual file, eg `fugitive:///home/me/top_dir/.repo/projects/currentproject.git/0/path/to/file/file.c` rather than `path/to/file/file.c`.

**Comment by tpope** [comment]
> My personal Yocto projects use a smaller manifest than chromiumos, and it's not several GB of prebuilt LLVM toolchains either.

Perfect.
 
> For @alevkoy @aostruszka and any other `repo` users who find this issue, there's a couple workarounds:
> 
> 1. Roll back to repo version 2.18, delete .git symlinks, and repo sync again
>    a. `repo forall -c 'rm .git' && git -C .repo/repo checkout v2.18 && repo sync`
>    b. This will recreate the per-project .git directories rather than .git symlinks
> 2. Use repo's new worktree mode, which uses "git worktree" to checkout projects (.git is a `gitdir: /foo/bar.git` file)
>    a. Run `repo init --worktree -u ...`
>    b. Unfortunately this requires recreating your workspace from scratch, you can't convert an existing one, and
>    c. worktree mode is still experimental and there's still some bugs (https://bugs.chromium.org/p/gerrit/issues/detail?id=15224&q=component%3Arepo)

Both are solid. I'd steer people who can towards the latter because worktrees are a solid way to achieve what `repo` is trying to do and Fugitive has good support for them.

**Comment by buggo** [comment]
I just did `git config --local core.worktree $PWD` in the repos I work with and that appears to have fixed it. Is this a okay solution or am I missing something?

**Comment by tpope** [comment]
> I just did `git config --local core.worktree $PWD` in the repos I work with and that appears to have fixed it. Is this a okay solution or am I missing something?

This would have been my recommended solution. Only downside is you have to do it in every single repo. (A small shell script could probably automate that.)

**Comment by meuter** [comment]
I use repo to work on and AOSP and I can also confirm that by default with repo 2.19, with nvim 0.6.1, executing `:Git` reports this the repo as bare:

`Head: <some commit id>`
`Bare: yes`
`Help: g?`

Note that `G status` properly reports change in my local repo though.

> I just did git config --local core.worktree $PWD in the repos I work with and that appears to have fixed it. Is this a okay solution or am I missing something?

I can confirm that this works thanks @buggo :-)

**Comment by buggo** [comment]
> > I just did `git config --local core.worktree $PWD` in the repos I work with and that appears to have fixed it. Is this a okay solution or am I missing something?
> 
> This would have been my recommended solution. Only downside is you have to do it in every single repo. (A small shell script could probably automate that.)

I haven't done any extensive testing but `repo forall -c 'git config --local core.worktree $PWD'` seems to work.

**Comment by rfried-nrl** [comment]
@tpope 
I did the `git config --local core.worktree $PWD`
Looks like using :G works, but when I'm typing
:Gvdiff , it tries to compare the diff with the $PWD and not the right file that is opened

**Comment by systemmonkey42** [comment]
I hit an issue a couple of days ago where vim-fugitive reports the error
```
core.worktree is required when using an external Git dir
```
for every submodule of a checked out project.

I finally tracked it down to the following;

In function `s:Tree()`, the call to `s:Readfile( dir . '/config', 10)` only returns the top of the git-config file.

The worktree setting happens to be on line 11 of all the submodules.
(git version 2.36.1)

Increasing that number solves the issue.

This raises the two obvious question;
- how did you choose '10' as an arbitrary limit.  Does your code break if you read the whole file?
- why do all this manual rubbish when git supports returning config parameters and is version independent?  `git config --get core.worktree` works. What is your problem with it?

Thanks.

**Comment by tpope** [comment]
> I hit an issue a couple of days ago where vim-fugitive reports the error
> 
> ```
> core.worktree is required when using an external Git dir
> ```
> 
> for every submodule of a checked out project.
> 
> I finally tracked it down to the following;
> 
> In function `s:Tree()`, the call to `s:Readfile( dir . '/config', 10)` only returns the top of the git-config file.
> 
> The worktree setting happens to be on line 11 of all the submodules. (git version 2.36.1)
> 
> Increasing that number solves the issue.
> 
> This raises the two obvious question;
> 
> * how did you choose '10' as an arbitrary limit.  Does your code break if you read the whole file?

Just a small optimization in the event of a massive config file. I'll bump it to 50.

> * why do all this manual rubbish when git supports returning config parameters and is version independent?  `git config --get core.worktree` works. What is your problem with it?

1. `system('git config --get core.worktree')`, under the best of circumstances, is an order of magnitude slower than reading the file by hand.
2. It's even worse on Windows.
3. It briefly opens a `cmd.exe` window on Windows, which is visually distracting.
4. It's also worse if the user has done `set shellcmdflag=-ic`, or any other of a number of dubious but popular tweaks to shell behavior.
5. User tweaks can also break `system()` entirely. This will cause problems with Fugitive regardless, but it's better those problems happen at invocation time than detection time.
6. Same thing if `git` isn't installed, or not in `PATH`. Better to error during invocation than detection.

**Comment by systemmonkey42** [comment]
> > * how did you choose '10' as an arbitrary limit.  Does your code break if you read the whole file?
> 
> Just a small optimization in the event of a massive config file. I'll bump it to 50.

Thanks for that.

> > * why do all this manual rubbish when git supports returning config parameters and is version independent?  `git config --get core.worktree` works. What is your problem with it?
 
> 2. It's even worse on Windows.

Ugh. That all makes sense, supporting windows is the worst.

**Comment by tpope** [comment]
Symlinks should be supported now, with the caveat that it won't work when editing files in the Git dir itself, for example `COMMIT_EDITMSG`. Do report any other issues. In particular, keep an eye out for issues with the status buffer, which had to move from `.git/index` to a `fugitive://` URL.

**Comment by marado** [comment]
> Symlinks should be supported now, with the caveat that it won't work when editing files in the Git dir itself, for example `COMMIT_EDITMSG`. Do report any other issues. In particular, keep an eye out for issues with the status buffer, which had to move from `.git/index` to a `fugitive://` URL.

I confirm that this solves the issue with `:G Blame` on repo-managed git repositories.
