### ISSUE TITLE
*.tmp.sh: line 5: sleep: command not found

### ISSUE THREAD

**Issue by BertrandSim** [tpope/vim-fugitive#1922]
Hi there, I am using fugitive with the windows shell (cmd).
As windows cmd does not have a sleep executable, the error results.
Each time a git commit is made, this error is shown on numerous lines in the shell.

I believe the relevant lines of code are at
https://github.com/tpope/vim-fugitive/blob/master/autoload/fugitive.vim#L3764-L3769

Cheers

**Comment by tpope** [comment]
Windows doesn't ship with `sh` either but you have that. How did you install Git?

**Comment by BertrandSim** [comment]
That's a good point.. I installed MinGit, as made available on [this repo](https://github.com/git-for-windows/git/releases), filename MinGit-2.xx.0-rc0-64-bit.zip

If it helps, my git version is 2.31.1.windows.1

**Comment by tpope** [comment]
From https://github-wiki-see.page/m/git-for-windows/git/wiki/MinGit:

> MinGit is an intentionally minimal, non-interactive distribution of Git for Windows, with third-party applications as its intended audience.

Seeing as how you're not a third-party application, I'd encourage you to install the regular Git for Windows distribution instead.
