### ISSUE TITLE
Behavior broken when setting `lcd` or opening not from the root directory.

### ISSUE THREAD

**Issue by cladmi** [tpope/vim-fugitive#1923]
Hello,

I have issues in my environment where I use `lcd` to set the working directory to the current file.

```
autocmd BufEnter * silent! lcd %:p:h
```

It seems the path resolution is broken.
If from the repository root I open `directory/name.txt` and executed `:Git blame` I get

```
fatal: no such path 'name.txt' in HEAD
```

Without that `lcd` it works when open from the root directory.

But it seems that if I go in the `directory` and open the `name.txt` file directly, even without my `lcd` change I get the same error.

So somehow it seems like the filepath is not resolved relatively to the root directory of the repository.

This was previously working for me when doing the old `Gblame` some time ago, not sure how old the version was.

---
 
I am running the last version from master 57968b63c266b5d37bb08fa6e3807d230b882781

On ubuntu 20.04
```
git --version
git version 2.25.1
```
```
vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 08 2021 14:21:34)
Included patches: 1-2269
...
```

**Comment by tpope** [comment]
I can't reproduce. My first guess would be you have an old version of Fugitive installed. My second guess would be you have something else in your config causing the problem. Try with a stripped down config and check `:scriptnames` to make sure nothing unexpected is loading.
