### ISSUE TITLE
Alternative to fugitive#detect()

### ISSUE THREAD

**Issue by bogdan** [tpope/vim-fugitive#1924]
I have the same bind to different command based on environment: git repo or basic directory.
It was done like so:

``` viml
function! MyGrep(ending)
  if exists("b:git_dir")
    let cmd = ":Git! grep -w"
  else
    let cmd = ":Ack! -w"
  endif
  call feedkeys(cmd.' '.a:ending)
endfunction

nmap <F3> :call MyGrep('"'.expand('<cword>').'" ')<CR>
```

After the recent update the `b:git_dir` is only set after first invocation of `Git` command. I tried to use `fugitive#detect()` instead but it asked to contact the author. Can you suggest a different way to accomplish that?

**Comment by tpope** [comment]
```vim
if !empty(FugitiveGitDir())
```
