### ISSUE TITLE
When staging by hunk and a file is fully staged, put cursor on first hunk of next file vs next file name

### ISSUE THREAD

**Issue by gibfahn** [tpope/vim-fugitive#1926]
### Versions

- vim-fugitive a93ceff61f070a095c3c712c389247a80897e3b0 (latest master)
- Using neovim v0.6.1 (latest neovim)

### Background

When staging, I'm either staging by file or by hunk. When staging by file, I'm giving each file a quick look then staging the whole thing. When staging by hunk, I'm carefully reading each diff.

When you stage a hunk, fugitive automatically puts the cursor on the hunk marker (`@@ -1,9 +1,9 @@`) for the next hunk, which is great as it lets you tap `s` repeatedly to go through the open hunks.

However, when you stage the last hunk in a file, fugitive puts the cursor on the next file marker (e.g. `M README.markdown`) instead of the first hunk marker in that file. This means you have to constantly be checking 

### Worked Example

1. Modify a couple of files by running this shell snipped in this repo:

```shell
printf '%s\n%s\n%s\n' firstR "$(cat README.markdown)" lastR >README.markdown 
printf '%s\n%s\n%s\n' firstC "$(cat CONTRIBUTING.markdown)" lastC >CONTRIBUTING.markdown
```

2. Open fugitive

<details><summary>Screenshot:</summary>
<img width="508" alt="image" src="https://user-images.githubusercontent.com/15943089/149510459-1dfc1062-d188-4256-9916-cdfee7566416.png">
</details>

3. Go down to `Unstaged (2)` and hit `=` to expand the hunks

<details><summary>Screenshot:</summary>
<img width="514" alt="image" src="https://user-images.githubusercontent.com/15943089/149510520-76abdb08-91db-4dbe-9f23-a7ccbc69611c.png">
</details>

4. Move down two lines to `@@ -1,3 +1,4 @@`, and hit `s` to stage the first hunk

<details><summary>Screenshot:</summary>
<img width="508" alt="image" src="https://user-images.githubusercontent.com/15943089/149510604-dbdade5b-055e-4375-8953-32086dd6bdb7.png">
</details>

5. The cursor has automatically moved to the next hunk (which is excellent). Hit `s` again to stage that one too.

<details><summary>Screenshot:</summary>
<img width="515" alt="image" src="https://user-images.githubusercontent.com/15943089/149510668-dbed7251-aabf-4c9d-8638-4a43f99a7a5c.png">
</details>

6. Note that the cursor is now on `M README.markdown`, so hitting `s` a third time would stage all changes in that file, but we just want to stage hunk-wise. Therefore we have to move one line down to stage only the next (`firstR`) hunk rather than everything in this file.

<details><summary>Screenshot:</summary>
<img width="514" alt="image" src="https://user-images.githubusercontent.com/15943089/149510809-2cc94be5-57c7-4aa7-9122-b98cf0d54d13.png">
</details>

**Comment by tpope** [comment]
I'm not convinced this should be changed. A possible alternative workflow would be to start with everything closed, press `i` to cycle through changes (which expands diffs automatically), and press `s` on the hunks you want to stage.

**Comment by gibfahn** [comment]
>A possible alternative workflow would be to start with everything closed, press i to cycle through changes (which expands diffs automatically), and press s on the hunks you want to stage.

The expanding diffs automatically is nice, but this doesn't really make things any easier. Previously to stage the 4 hunks in the above example (cursor starting in the first hunk) it would be `ssjs`, and with `i` it's `ssis`.

Using `i` and `s` isn't so bad when you're just picking out a few diffs to stage out of a bunch of unconnected changes (when you're mostly not staging things). It's much more painful though when you're staging ~everything, and just using this as a point to do some code review on your changes before submitting.

It looks like this mapping works as a workaround:

```vim
" Stage, go up a line, then skip to the next hunk.
:nmap S sk]c
```
