### ISSUE TITLE
Ggrep -w flag stopped working

### ISSUE THREAD

**Issue by bogdan** [tpope/vim-fugitive#1927]
In previous version of fugitive I was able to call `Ggrep -w` as the analogy of command line `git grep -w`. But it is not current possible: `-w` flag is simply ignored. 

Is there an alternative to that right now?

**Comment by tpope** [comment]
It most definitely is not ignored. `:Ggrep -w Fugitive` in _this_ repository finds 24 results while `:Ggrep Fugitive` finds 284.
