### ISSUE TITLE
Make blame -CC async

### ISSUE THREAD

**Issue by kaddkaka** [tpope/vim-fugitive#1928]
`blame -CC` for a large repo can be very slow (for me it's ~20 s). Currently my Neovim freezes during this operation. Using `-CCC` should be an even heavier operation. It would be nice if that was somehow done asynchronously so that my Neovim can continue to be responsive while waiting for the blame reply.

From `man git blame`
```
-C[<num>]
           In addition to -M, detect lines moved or copied from other files that were modified in the same commit. This is useful when you reorganize your program and move code around across files. When this option is given twice, the command additionally looks for
           copies from other files in the commit that creates the file. When this option is given three times, the command additionally looks for copies from other files in any commit.
```

**Comment by tpope** [comment]
> somehow

I'm open to an implementation.
