### ISSUE TITLE
FugitiveCommonDir: Argument of get() must be a List, Dictionary or Blob

### ISSUE THREAD

**Issue by akemrir** [tpope/vim-fugitive#1930]
Hi

From lastest update, from main branch I've started receiving erros:

![obraz](https://user-images.githubusercontent.com/240986/150285593-0b98700b-e190-4c8b-91bb-9323a3bee6fd.png)

fugitive#head[5]..fugitive#Head[5]..fugitive#Find[31]..FugitiveCommonDir[9]..<SNR>96_ReadFile:
fugitive#head[5]..fugitive#Head[5]..fugitive#Find[31]..FugitiveCommonDir:
ProjectionistDetect[40]..User Autokomend dla "ProjectionistDetect"..function <SNR>96_ProjectionistDetect[11]..FugitiveFind[4]..fugitive#Fin
d[31]..FugitiveCommonDir[9]..<SNR>96_ReadFile:
ProjectionistDetect[40]..User Autokomend dla "ProjectionistDetect"..function <SNR>96_ProjectionistDetect[11]..FugitiveFind[4]..fugitive#Fin
d[31]..FugitiveCommonDir:

I know that they don't exist on my machine.
It looks like it is trying to read it even when commondir  is not present.

**Comment by tpope** [comment]
> It looks like it is trying to read it even when commondir is not present.

Yes it is, inside of a `try`/`catch` which silences any exception. What is up with your Vim? Can you test if this causes an error?

```vim
:try|throw 'x'|catch|endtry
```

**Comment by akemrir** [comment]
I have archlinux vim package
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 16 2022 12:09:56)
Patchset 1-4106 

No, this does not cause any errors.

**Comment by akemrir** [comment]
I've prepared minimal .vimrc and in fact there is something with my setup.
I've found guilty my current statusline config.

I had this:
`autocmd VimEnter * silent! call fugitive#detect(expand('<afile>'))`

So this is not relevant to fugitive directly, I am closing.
