### ISSUE TITLE
Vim Fugitive is slow

### ISSUE THREAD

**Issue by ykolomatski** [tpope/vim-fugitive#1931]
I know there have been several issues raised on this, though fugitive is slow for me. When I open the status window it takes 1-1.5 seconds. Any operations (like staging or unstaging) have a significant delay.

I tested with minimal configuration (only fugitive is installed).

I am using using Vim 8.2 on Windows 10.

**Comment by tpope** [comment]
And how fast is `git status`? If the problem is that Git is slow, there is not much to be done about that.

**Comment by ykolomatski** [comment]
The output is shown almost instantaneously. The time it takes to return from the command is roughly 0.5-1 seconds. Maybe that's the issue?

**Comment by tpope** [comment]
Yeah that's definitely worth investigating.
