### ISSUE TITLE
[Question] diffget all?

### ISSUE THREAD

**Issue by phortonssf** [tpope/vim-fugitive#1932]
While in a 3 way split to solve a merge conflict I can do diffget //2 or 3// to pick each conflict. Is there a way in vim fugitive to accept all changes from one side instead of picking each? ty.

**Comment by tpope** [comment]
I can't think of an elegant native Vim solution, but you can do `:Gread >:2` or `:Gread >:3` in Fugitive. Or you can select the window with the version you want and call `:Gwrite!`.
