### ISSUE TITLE
Keymap <leader>gh not working

### ISSUE THREAD

**Issue by phortonssf** [tpope/vim-fugitive#1933]
While in git status with a merge conflict: i press **dv** on the file.  While picking from the left or right my keybinds dont works as expected.
Trying to rebind **:getdiff 2//<CR>** works for other keys but not **<leader>gh**.   For example:
`nmap <leader>gt :getdiff 2//<CR>` works and takes the left side
`nmap <leader>gh :getdiff 2//<CR>` calls :getdif 3// as i see in the outpurt and takes the right side. 

Leader gh will always call **:getdiff 3//<CR>** even if it is mapped to **:getdiff 2//**. I commented out all my other keybinds to confirm it.

**Comment by tpope** [comment]
`3//` does not appear in the buffer name. You're probably meaning to do `//3` but this is not a guaranteed interface either. The closest thing to guaranteed is this:

```vim
nmap <Leader>gh d2o
```

**Comment by phortonssf** [comment]
My code had it right my comment had it wrong, as you suspected, it was `nmap <Leader>gh :diffget  //3` 
Your suggested change `nmap <Leader>gh d2o` outputs the same thing and outputs  ` diffget //3` where the messages are.  Interestingly `d20` works on its own but when not mapped to  `<leader>gh`.

**Comment by tpope** [comment]
Check `:verbose nmap <Leader>gh`.
