### ISSUE TITLE
FR: Add mapping to stash with message

### ISSUE THREAD

**Issue by ktprograms** [tpope/vim-fugitive#1934]
The command that would be run should be `git stash push -m "<message>"`

Thanks!

**Comment by tpope** [comment]
You can `cz push -m`. A shorter version _might_ happen after further retooling.

**Comment by ktprograms** [comment]
On Sat Jan 22, 2022 at 1:23 AM +08, Tim Pope wrote:
> You can `cz push -m`. A shorter version _might_ happen after further retooling.

Ok, thanks. At least that's shorter than typing out `:G stash push -m`.

**Comment by jbyler** [comment]
My current workaround: edit or create the file `~/.vim/after/ftplugin/fugitive.vim` with this binding:
```
nmap <buffer> czZ :G stash push -m '' .<Left><Left><Left>
```

This creates a new `czZ` binding that pre-populates with the cursor ready to type a message. You can also bind it to something else (e.g. `czz`) to override the default binding, but then you lose the ability to specify a count for `--all` and `--include-untracked`. I'm trying to work out how to fix that but so far I haven't got it yet.

And I suppose the same could be done for `czW` and `czS`.
