### ISSUE TITLE
[Question] Possible to scroll through git blame revisions of current file only in vertical split?

### ISSUE THREAD

**Issue by pkmital** [tpope/vim-fugitive#1939]
Thank you for an incredible plugin! Apologies if this isn't the place to ask a question!

I am trying to open in the quickfix or location list a list of all changes from the current file only, and using `j` `k`, scroll through revisions on the current open file to quickly get a glance of the change history of that file (ideally in a vertical split). 

The current workflow for this is to open `Git blame`, which opens a vertical split with commits on the left side, and the current file on the right side. I can open any of these into a diff if I press <CR>, and it will close the quickfix list, and open the changes in a single file, which also shows all changes of the commit, not just the current file. Then I have to reopen `Git blame`, and try again. The commits also don't have any info on the commits themselves, like `Git log` would have.

Is there a way to get:

* Just the current files changes as opposed to the entire commit's diff
* Scrolling through the history of that file without the quickfix list to close (e.g. just `j` `k` will load those changes
* A view of the commit history ordered by date like `Git log` would show, but only for commits related to the current file
* See the changes in a vertical split (I know about `Gvsplit` but not sure how to use this with the workflow I'm looking for)

Really appreciate any guidance here!

**Comment by tpope** [comment]
You might find a combination of `:Gclog %` and `:Gvdiffsplit!` to be helpful.
