### ISSUE TITLE
Feature Request: Add keybinding for git stash --staged (new in 2.35.0)

### ISSUE THREAD

**Issue by ktprograms** [tpope/vim-fugitive#1941]
Hi, in Git 2.35.0, there is a `--staged` flag to `git stash`, which will stash **only** the staged files. It kind of works in the opposite way to `czw`, since that stashes **unstaged** files. I think `cws` would be a sensible binding for it.

Thanks!

**Comment by tpope** [comment]
Generally speaking I don't chase bleeding edge features, but this is straightforward enough that I would be willing to consider an undocumented version. How does `--staged` interact with `--all` and `--include-untracked`?

**Comment by ktprograms** [comment]
On Wed Feb 2, 2022 at 6:30 PM +08, Tim Pope wrote:
> Generally speaking I don't chase bleeding edge features, but this is straightforward enough that I would be willing to consider an undocumented version. How does `--staged` interact with `--all` and `--include-untracked`?

When running "git stash --staged --all", I get this error:

Can't use --staged and --include-untracked or --all at the same time

Which explains it quite clearly I think.

**Comment by ktprograms** [comment]
Thanks!
