### ISSUE TITLE
function SetPorjectRoot

### ISSUE THREAD

**Issue by zuxfoucault** [tpope/vim-fugitive#1945]
On MacVim and the latest vim-fugitive the Diffsplit failed:
![image](https://user-images.githubusercontent.com/3050531/152633820-33bfc2c4-71ca-4dac-9fe3-105a6fd6edaa.png)

Any suggestion to fix this? Thanks!

**Comment by tpope** [comment]
`SetProjectRoot` isn't a Fugitive function. You'll need to figure out what's going wrong in it.
