### ISSUE TITLE
`:Git difftool HEAD~` results in error

### ISSUE THREAD

**Issue by ezzieyguywuf** [tpope/vim-fugitive#1946]
Steps to reproduce
==================

```sh
git clone https://github.com/ezzieyguywuf/small_git.git
cd small_git
vim -c "Git difftool HEAD~" README.md
```

Expected Outcome
================

Load the diff between HEAD and the previous commit into the `quickfix` list

Actual Outcome
==============

Vim outputs the following error:

```sh
Error detected while processing command line..function fugitive#Command[77]..command line..function fugitive#Command[70]..<SNR>208_DifftoolSubcommand[81]..<SNR>208_ToolStream[39]..<SNR>208_QuickfixSt
ream[7]..BufRead Autocommands for "*":
E788: Not allowed to edit another buffer now
```

Environment:
============

Vim: v8.2
Fugitive: commit a93ceff61f070a095c3c712c389247a80897e3b0
OS: debian testing

**Comment by tpope** [comment]
> `BufRead Autocommands for "*"`

This error isn't happening in Fugitive, it's happening in a badly behaved autocommand. Try with a stripped down config.

**Comment by ezzieyguywuf** [comment]
This was the autocommand that was causing the problem:

```vim
augroup remember_folds
  autocmd!
  autocmd BufWrite * mkview
  autocmd BufRead * loadview
augroup end
```
