### ISSUE TITLE
Problems with xml files

### ISSUE THREAD

**Issue by zmichal-anasoft** [tpope/vim-fugitive#1947]
This error happens only after some time of working  with xml files. With fresh opened file/buffer it works perfectly.

Error detected while processing function fugitive#Diffsplit[141]..function fugitive#Diffsplit[123]..BufReadCmd Autocommands for "fugitive://*//*"..BufRead Autocommands for "* .xml"..function dist#ft#FTxml[23]..FileType Autocommands for "xml": E518: Unknown option: set

After this error, the other diff window is not opened. I must close and reopen the file to see the diff of XML file.

Version of VIM:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 01 2021 01:51:08)
Included patches: 1-2434
Extra patches: 8.2.3402, 8.2.3403, 8.2.3409, 8.2.3428

Version of fugitive:
commit 6c19f1ddfb74b3b21f3d1e830bee1d1ed6a72ece (HEAD -> master, origin/master, origin/HEAD)
Author: Tim Pope <code@tpope.net>
Date:   Wed Feb 2 11:53:01 2022 -0500

**Comment by tpope** [comment]
Not a Fugitive issue. It's whatever `dist#ft#FTxml` is.
