### ISSUE TITLE
Change the order of Untracked/Unstaged/Staged files in status

### ISSUE THREAD

**Issue by K-os** [tpope/vim-fugitive#1950]
I am still using v2.5, because I don't like the order how the new `Gstatus` (or now `:Git`) view displays the files. I really liked the order Staged, Unstaged, Untracked as it was previously. This corresponds to how the `git status` command shows it and it works fine with my workflow: I often have several untracked files, which I don't want to gitignore, but also that I don't want to track. For example, when working with projects, that are not maintained by me so I don't have control over the ignored files.

These untracked files now always appear at the top and push the important files Unstaged and Staged out of the window.

Would it be possible to add a configuration option, to revert to the old display order (or make it configurable)?

**Comment by tpope** [comment]
> I often have several untracked files, which I don't want to gitignore, but also that I don't want to track. For example, when working with projects, that are not maintained by me so I don't have control over the ignored files.

You don't have control over `.gitignore`, but you do have full control over `.git/info/exclude`. Which just so happens to be the default destination for the `gI` map.
