### ISSUE TITLE
Compatibility issues with lunarvim

### ISSUE THREAD

**Issue by codingluke** [tpope/vim-fugitive#1951]
Dear @tpope 
I use vim-fugitive now for years and first have to thank you for all the time you saved me 👍 

I am experimenting a lot with vim and came along LunarVim https://www.lunarvim.org. It is a community driven neovim with lua centered configuration. Unfotunately, they are more into lazygit and seem to have some issues with vim-fugitive which they are not willing to fix. The following link to the issue on the LunarVim repo has a detailed description from @goolzerg.

https://github.com/LunarVim/LunarVim/issues/2219

In the `:Git` view, it is possible to toggle files with `-`. However, the `cc` command, and all other commands starting with `c` are not mapped. The following link to the issue on the LunarVim repo has a detailed description from @goolzerg.

The `E21 Cannot make changes, 'modifable' is off` message showes, as `c` is mapped to the standard "change". So it is not calling your method, instead it is changing the buffer.

I can totally untersand, that is is not in your duty to help out here. 
However, I would be very happy when you would 🚀 

Best Lukas

**Comment by tpope** [comment]
It's this shit:

https://github.com/LunarVim/LunarVim/blob/582b169ecfec6407e41e3775ed7680b6c540b28d/lua/lvim/config/settings.lua#L29

Setting `timeoutlen` to `100` requires all maps to be input in 100ms. It effectively breaks all multi-character maps, unless you're a really fast typer.

Furthermore, if I may call out some nonsense:

> okay, but why the same error is raised when I try to run `:message` command?

The `:message` command isn't raising an error. The `:message` command shows recent messages, including recent errors.

> it seems like the vim-fugitive window is non-modifiable because of some issue

It's not supposed to be modifiable.

**Comment by codingluke** [comment]
Well, this was faster than expected! Thx a lot it fixed it! 🦸
