### ISSUE TITLE
See what actually happened when solving conflicts

### ISSUE THREAD

**Issue by ofirgall** [tpope/vim-fugitive#1952]
Hey, I don't know if its the best place to ask about this, I'm new the (neo)vim and I a have problem with the diff view which helps to solve conflicts.

I'm using `:Gvdiffsplit!` to solve conflicts and it doesn't show what added in the both sides, its just show the conflict.

How it looks in sublime merge:
![smerge](https://user-images.githubusercontent.com/4954051/155768617-de4b754b-2f1b-41b9-a6e9-46fd8a200693.png)

How it look in nvim:
![nvim](https://user-images.githubusercontent.com/4954051/155768665-a33dae01-b6ed-4139-a607-85745c9f626c.png)

If you pay attention you can say sublime merge emphasis what actually changed in the commits, both commits added `aaa` and `bbb` which marked with dark blue color and you can `Hello World` which marked with light blue color.

Can it be done in nvim?

**Comment by tpope** [comment]
This is how Vim's built-in diffing works. A plugin could maybe offer a better diffing experience. I'm unaware of any that do,
