### ISSUE TITLE
Feature request - display unique contributors

### ISSUE THREAD

**Issue by oren0e** [tpope/vim-fugitive#1953]
Hi,
It would be nice if you could somehow display the names of the unique contributors in a given file. Kind of like taking the output of `:Git blame` and outputing the unique names of the contributors from the commit lines. Is this something that is possible to do?

**Comment by tpope** [comment]
This is something you can more or less do yourself without explicit support from Fugitive. Create a script called `git-unique-contributors` that takes a filename argument and outputs the list you desire. Then call it from Fugitive with `:Git unique-contributors %`.
