### ISSUE TITLE
[feature request] Commitizen compatibility

### ISSUE THREAD

**Issue by Salomanuel** [tpope/vim-fugitive#1955]
It would be amazing for Vim-Fugitive to be compatible with Commitizen

https://github.com/commitizen/cz-cli
sample Commitizen usage:
![image](https://user-images.githubusercontent.com/14359139/157054360-9d95fe7f-579b-440c-8bea-57439c532b72.png)

**Comment by tpope** [comment]
Please clarify what would be required to make it compatible.

**Comment by tpope** [comment]
> don't mind the ASCII color codes, it's that TERM=dumb issue that was fixed with regarding husky, I just didn't figure out how to fix it on my side yet

The codes that contain `m` are color codes.  The others do various things like move the cursor around the screen. And you're correct that there's no chance we can support this using the current user interface. We're using `:echo`, which supports pretty much exactly what a dumb terminal does. If Commitizen recognized `TERM=dumb` and fell back to a simpler user interface, then it would work.

> I guess if someone really wanted to they could in their config files replace fugitive's git commit command with something that opens a :term to make it work.

If you set a custom `pager.cz`, Fugitive will use `:terminal` so the pager can do its thing. That's a conceivable workaround.  Although then you'll get a Vim inside of Vim to edit the message, which is disgusting.

Another workaround: change the hook to avoid dumb terminals:

```
[ "$TERM" != dumb ] && exec < /dev/tty && node_modules/.bin/cz --hook || true
```

From the README:

> Why `exec < /dev/tty`? By default, git hooks are not interactive. This command allows the user to use their terminal to interact with Commitizen during the hook.

Indeed, this insults the gods.

**Comment by Skylla54** [comment]
# My Workaround
1.  Adding Lines
2. `:w`
3. `:G`
4. Press `s` for Stage
5. Use the floating Terminal to initalize commotizen
6. Follow the instructions
7. Close the Floating Terminal
8. `Git push`
9. Enough Work for today, zip a coffee ☕

![image](https://user-images.githubusercontent.com/30662393/161399688-84bf0375-557c-400b-865b-da3fd686cdf3.png) 
![image](https://user-images.githubusercontent.com/30662393/161399704-08fc7763-1414-4076-a4c0-18e66df2ed9a.png)
![image](https://user-images.githubusercontent.com/30662393/161399713-f6ea4884-a1d3-4244-8caf-a03cc526258b.png)
![image](https://user-images.githubusercontent.com/30662393/161399719-fa6884b3-6178-4a7e-b8e0-275d35acb688.png)
![image](https://user-images.githubusercontent.com/30662393/161399732-7a9c1fef-486d-4035-87ef-02568b6e9211.png)
![image](https://user-images.githubusercontent.com/30662393/161399754-6ce51d2a-5ff1-43a7-977b-a0e4068f953a.png)
![image](https://user-images.githubusercontent.com/30662393/161399805-ebb3651f-e1b1-4da9-9dda-ace354d603bd.png)
![image](https://user-images.githubusercontent.com/30662393/161399825-c7a91d3e-4b54-4caa-a818-64a53f9237ac.png)
![image](https://user-images.githubusercontent.com/30662393/161399843-33198448-5948-4379-a328-6eb9a28cd022.png)

I dont know whats the name of the Floating Terminal but, I am sure you can look it up in LunarVim.org.
