### ISSUE TITLE
Inline diff instead of splits (side-by-side)?

### ISSUE THREAD

**Issue by simondrake** [tpope/vim-fugitive#1957]
I've been using this plug-in for a long time and it's excellent, thank you for putting in the effort to make it. 

This isn't an issue, more a question, so if there's a more suitable place for it please let me know. 

Whenever I use GitHub/GitLab to review code, I use the inline diff option as opposed to the side-by-side one because I prefer how it looks.

I am exploring using vim for larger MRs, for all the reasons I enjoy coding in it, but I can't figure out how to get the diff to show inline instead of in a split.

Is there a way to have vim-fugitive open diffs in an inline view, instead of a side-by-side view(`Gvdiffsplit`)?

For reference, I usually use a `git review` alias which I've included below

```
[alias]
    files = !git diff --name-only $(git merge-base HEAD \"$REVIEW_BASE\")
    stat = !git --no-pager diff --stat $(git merge-base HEAD \"$REVIEW_BASE\")
    review = !nvim -p $(git files) +\"tabdo Gvdiffsplit! $REVIEW_BASE\" +\"let g:gitgutter_diff_base = '$REVIEW_BASE'\"
    reviewone = !nvim -p +\"tabdo Gvdiffsplit! $REVIEW_BASE\" +\"let g:gitgutter_diff_base = '$REVIEW_BASE'\"
```

**Comment by tpope** [comment]
If by "inline" you mean a unified diff, it sounds like the heart of what you're looking for is `:Git diff $REVIEW_BASE..`.

**Comment by simondrake** [comment]
Thanks for the reply @tpope, but that's not quite what I was looking for.

If I take one of my side-projects as an [example](https://github.com/MyWordOfTheDay/backend) and make some random changes. Running `Gdiffsplit` gives me the following view, from which I can do vim operations such as running a `go to definition` operation on `*Manager` to see where that's defined.

![image](https://user-images.githubusercontent.com/62928647/158166256-b4f533da-0eee-4369-8cab-6360cc54a952.png)

https://user-images.githubusercontent.com/62928647/158166523-c96a5616-ab95-47b1-bea8-927e5609963b.mp4

If I use `:Git diff`, it just opens view akin to if I ran that outside of vim where I can't use the power of vim (e.g. `go to definition`)

https://user-images.githubusercontent.com/62928647/158167028-48a0a87e-4ac3-457f-9076-b7da3ea9de1b.mp4

What I was asking about, is if it's possible to have the format/utility of `Gdiffsplit`, just as a unified/inline diff instead of split.
