### ISSUE TITLE
Avoid adding mappings when no_plugin_maps is true.

### ISSUE THREAD

**Issue by meh** [tpope/vim-fugitive#196]
I use vim as `PAGER` and when doing `git log` in the terminal I can't use `j` or `C-e` anymore to go down, there's probably a way to go down properly but well, it would be better to respect the `no_plugin_maps` variable.

Most standard ftplugins use it to not set mappings.

**Comment by tpope** [comment]
There is `g:fugitive_no_maps` now, and the `<CR>` map is only active in `'momodifiable'` buffers.
