### ISSUE TITLE
Is `core.worktree` really needed when follwed link to .git?

### ISSUE THREAD

**Issue by adamws** [tpope/vim-fugitive#1960]
fugitive currently does not work with [git-repo](https://gerrit.googlesource.com/git-repo/) - https://bugs.chromium.org/p/gerrit/issues/detail?id=15739

`git-repo` creates symbolic link, for example: `.git@	 --> /project/.repo/projects/repository1.git`
but in `/project/.repo/projects/repository1.git/config`, `worktree` is not set.

This results in `fugitive: core.worktree is required when using an external Git dir`

I checked and fugitive follows link correctly and it works as expected when I add `worktree` by hand.
Just wondering if this case can be somehow handled by fugitive if `git-repo` team do nothing about it.

**Comment by tpope** [comment]
Yes, it is. Further discussion around git-repo, including workarounds, can be found in #1920.
