### ISSUE TITLE
Document how to add a browse handler

### ISSUE THREAD

**Issue by tmccombs** [tpope/vim-fugitive#1964]
The documentation for :GBrowse says to install an appropriate plugin to add a handler, however there doesn't seem to be any documentation on how to implement such a plugin (other than looking at the source of an existing plugin). It would be nice to have some guiding documentation on what the options passed to the handler looks like for different types of fugitive objects.

**Comment by tpope** [comment]
The *de facto* documentation is cribbing from [rhubarb.vim](https://github.com/tpope/vim-rhubarb/blob/977b3ccbad1f7e5370354ae409fb2ea4a7ce2058/autoload/rhubarb.vim#L287-L324).

**Comment by tmccombs** [comment]
I looked at the implementation in rhubarb.vim, but there were a few things that confused me:

- What is the purpose of [`let path = substitute(opts.path, '^/', '', '')`](https://github.com/tpope/vim-rhubarb/blob/977b3ccbad1f7e5370354ae409fb2ea4a7ce2058/autoload/rhubarb.vim#L297)? Does the path always start with a `/` only sometimes? Is there any signficance to that?
- Why does it check if the path starts with `.git` before checking the `type`? And what _is_ the `type` in those cases?
- When would you have a path of .git/config or .git/hooks?
- Are line numbers only provided for blob types? If not, what does a line number for another type mean?
- Is commit always provided?

**Comment by tpope** [comment]
> I looked at the implementation in rhubarb.vim, but there were a few things that confused me:
> 
> * What is the purpose of [`let path = substitute(opts.path, '^/', '', '')`](https://github.com/tpope/vim-rhubarb/blob/977b3ccbad1f7e5370354ae409fb2ea4a7ce2058/autoload/rhubarb.vim#L297)? Does the path always start with a `/` only sometimes? Is there any signficance to that?

The goal was that `'/path'` would be a blob, `'/path/'` would be a tree, `'/'` would be the root tree, and `''` would be a commit or other object with no path.  And that this would enable killing of `type` entirely. This never happened. Still, no harm in copying this line. It might happen if I ever break backwards compatibility.

> * Why does it check if the path starts with `.git` before checking the `type`? And what _is_ the `type` in those cases?

Don't know, don't care. :relieved: 

> * When would you have a path of .git/config or .git/hooks?

When editing `.git/config` or `.git/hooks`, or when calling `:GBrowse .git/config` or `:GBrowse .git/hooks`. These are goofy, and probably not worth copying, but you should still guard against `.git` paths and return the base URL or something.

> * Are line numbers only provided for blob types? If not, what does a line number for another type mean?

For now yes. There's a feature request to allow linking to part of a commit diff, and that could end up using these fields too.

> * Is commit always provided?

Yes.
