### ISSUE TITLE
See tags in `:Git log`

### ISSUE THREAD

**Issue by jdevries3133** [tpope/vim-fugitive#1965]
When I look at `git log` in my terminal, it shows the tag next to each commit hash like this:

```
commit 6a469c62632946c62b857db94c534de855a40bf1 (tag: v0.1.7)
```

But in git fugitive's `:Git log`, that information is missing:

```
commit 6a469c62632946c62b857db94c534de855a40bf1
```

This is probably a silly question, but how do I get the tags to show up? Thank you!

**Comment by tpope** [comment]
`:Git log --decorate`. Git has the curious behavior of only doing this by default when connected to a terminal. You can change this default by setting `log.decorate`.

**Comment by IsikcanYilmaz** [comment]
> `:Git log --decorate`. Git has the curious behavior of only doing this by default when connected to a terminal. You can change this default by setting `log.decorate`.

Hey @tpope ! Sorry to bother but could you elaborate on what you mean by "setting log.decorate"? 

many thanks! love your work!

**Comment by jdevries3133** [comment]
He means adding this to your `~/.gitconfig`:

```toml
[log]
    decorate = true
```

**Comment by IsikcanYilmaz** [comment]
@jdevries3133 Thank you very much!
