### ISSUE TITLE
[Feature Request] 3-way diff of file containing conflict markers even when no merge is in progress

### ISSUE THREAD

**Issue by rickyelopez** [tpope/vim-fugitive#1968]
At the company where I work, we often merge feature branches back into mainline branches. When this happens, the person who is running the merge will perform the merge locally into a user branch, commit everything without touching the conflict markers, and then make a PR with that branch. Then all the people responsible for those files go through and fix their conflicts, merging their fixes into that user branch.

What that means for me is that I'm often working with files that include conflict markers, but that are already merged. When I open those files in Neovim to resolve the conflicts, fugitive refuses to show a 3-way diff (which is fair cause there isn't actually a merge in progress).

The request here is for fugitive to be able to show a 3-way diff even when there isn't a merge in progress, if the file contains conflict markers. Where the left pane would should the "before", the right pane would show the "after", and the middle would be the working pane where one can build out the result they want.

Maybe this is already possible and I just can't figure out how to do it?

**Comment by tpope** [comment]
You could probably do something along the lines of:

* `:Gedit >@` to open the committed version of the file.
* `:Gdiffsplit!` to diff against all ancestors.
* `:Gedit` to return to the work tree file
* `:diffthis` to re-enable diffing on that buffer.

**Comment by rickyelopez** [comment]
Just gives me three buffs that are completely folded. If I unfold them, they all just show the same contents. Maybe I'm doing something wrong?

**Comment by tpope** [comment]
Look at the buffer names. They should have commit SHAs in them. Verify first that are different from each other, and second that they match the merge ancestors.

**Comment by rickyelopez** [comment]
Ah ok yeah looks like the hashes it's comparing are of the merges other people have made to resolve conflicts. How can I get it to pick older hashes?

**Comment by tpope** [comment]
`:Gedit >theactualmergecommit` as step 1. Or `:Gdiffsplit! hash1` and `:Gdiffsplit! hash2`.

**Comment by rickyelopez** [comment]
Awesome that works great, thanks!! Any thoughts on the best way to make an alias for this set of commands?

**Comment by tpope** [comment]
You might want `:help :command`. And `:exe` if you want to call a Fugitive command with a non-literal argument.
