### ISSUE TITLE
`git worktree`: `:G` window opens duplicately

### ISSUE THREAD

**Issue by KSR-Yasuda** [tpope/vim-fugitive#1970]
`:G` status window is opened duplicately in `git worktree` directory.

How to Repro
--------------------------------------------------------------------------------

First, prepare a repository and a worktree:

```bash
# Initialize repository
% git init repo
% cd repo

# Prepare `foobar.txt`
% echo foobar > foobar.txt
% git add foobar.txt
% git commit -m "foobar"

# Create worktree `wt` and move to it
% git branch develop
% git worktree add wt develop
% cd wt
```

Then, cd to the worktree and open Vim.

```vim
" Vim current dir is the worktree dir `repo/et`
:e foobar.txt

:G
" Open git status window.
" It shows the current directory `repo/wt`'s status successfully.

:1 wincmd w
" Move back to the `foobar.txt` window

:G
" [Bug]
" It is expected to reuse the former git status window, though,
" it opens newly
" (If `:G` command is run on the git status window itself, works correctly, though).
```

**Comment by tpope** [comment]
Check `w:fugitive_status` and `b:git_dir` and see if they match.

**Comment by KSR-Yasuda** [comment]
> Check `w:fugitive_status` and `b:git_dir` and see if they match.

They all match expectedly.

```vim
" Window of `foobar.txt`
b:git_dir              C:/Users/xxxxxxxx/xxxxxxxx/xxxxxxxx/repo/.git/worktrees/wt
E121: 未定義の変数です: w:fugitive_status
" E121: Undefined variable: w:fugitive_status

" Window of the first `:G`
b:git_dir              /c/Users/xxxxxxxx/xxxxxxxx/xxxxxxxx/repo/.git/worktrees/wt
w:fugitive_status      /c/Users/xxxxxxxx/xxxxxxxx/xxxxxxxx/repo/.git/worktrees/wt

" Window of the second (duplicated) `:G`
b:git_dir              /c/Users/xxxxxxxx/xxxxxxxx/xxxxxxxx/repo/.git/worktrees/wt
w:fugitive_status      /c/Users/xxxxxxxx/xxxxxxxx/xxxxxxxx/repo/.git/worktrees/wt
```

**Comment by tpope** [comment]
`C:/Users` and `/c/Users` do not match. Is this WSL?

**Comment by KSR-Yasuda** [comment]
Oh, that's for sure.

My env is git-for-windows environment (`version 2.35.1.windows.2.7.g158a30d60b.20220224121117`).

`.git` file in worktree dir is set as the `C:\Users`.
I think this is because of that.

```bash
% cd repo/wt
% cat .git
gitdir: C:/Users/xxxxxxxx/xxxxxxxx/xxxxxxxx/repo/.git/worktrees/wt
```

**Comment by tpope** [comment]
That'll do it. You can maybe get around it by changing to a relative path, not sure.

**Comment by KSR-Yasuda** [comment]
Anyway I raised an issue for git-for-windows.

**Comment by tpope** [comment]
Git for Windows is doing the right thing here.  The "correct" solution is to use Git for WSL. Although people say that it's slow...

**Comment by tpope** [comment]
The piece I was missing is that Git for Windows *includes* a copy of Vim. Unlike Cygwin or WSL, this is fairly straightforward to support.
