### ISSUE TITLE
[feature request] Make `:G` consider path in argument

### ISSUE THREAD

**Issue by UnkwUsr** [tpope/vim-fugitive#1972]
In git repository we can type `git status path/to/some/directory` and get list of changed files only in this directory or deeper. Or we can navigate to some directory in repository and run `git status .` from it.

So it would be good to have this functionality in fugitive.

I know that at this time `:G` passes all arguments like it's just a git subcommand. Probably it would be a problem. Then maybe we can handle only `.` specially? Or even assume that all strings starting with `.` is path (like `./path/to/something`)?.

Or is there any other way to open fancy fugitive git-summary buffer with custom path (have not found in help page)?

**Comment by tpope** [comment]
This probably won't ever be supported. `:G` does little more than `:edit .git/index`, where a `BufReadCmd` handles the buffer contents. So it's not just an argument issue, we'd need to completely rethink how that works.
