### ISSUE TITLE
:Git error

### ISSUE THREAD

**Issue by LawranceXcl** [tpope/vim-fugitive#1973]
![image](https://user-images.githubusercontent.com/47016472/162922345-1eb54aa8-74d3-4cce-b958-f047fc724e57.png)
Hi, when I input :Git, get some error, how can i slove it? thks

**Comment by tpope** [comment]
* What is the output of `:version`?
* What is the output of `:echo exists('*ch_close_in')`?

**Comment by LawranceXcl** [comment]
@tpope The picture is the context of the output,thks

**Comment by tpope** [comment]
> * What is the output of `:version`?
> * What is the output of `:echo exists('*ch_close_in')`?

The picture does not contain either of these.
