### ISSUE TITLE
Gdiff 3 buffer view?

### ISSUE THREAD

**Issue by badlandz** [tpope/vim-fugitive#1974]
:Gvdiffsplit and :Gvdiffsplit! only give me two buffers side by side, I'm trying to get that 3 buffer layout (left original, center working copy, right newer merge) view, but don't seem to have it figured out. I only get the 2 buffer layout when I try. Is it an underlying neovim setting, or part of fugitive and a command I don't know yet?

**Comment by tpope** [comment]
It only happens during a merge conflict.
