### ISSUE TITLE
Updating Neovim breaks vim-fugitive

### ISSUE THREAD

**Issue by minh5** [tpope/vim-fugitive#1976]
Recently upgraded to NVIM v.0.7.0 and it seems to be incompatiable with `vim-fugitive`

For instance my bindings for GBrowse is as followed

```
nnoremap <leader>gy :.GBrowse!<CR>
xnoremap <leader>gy :'<'>GBrowse!<CR>
```
But I get this error every time 
```
E119: Not enough arguments for function: fugitive#BrowseCommand
```

Tried going `:Git pull` and got this error

```
Error detected while processing function fugitive#Command[77]..fugitive#PagerFor[16]..FugitiveConfigGetAll:
line    1:
E117: Unknown function: fugitive#ConfigGetAll
Error detected while processing function fugitive#Command[77]..fugitive#PagerFor:
line   16:
E896: Argument of get() must be a List, Dictionary or Blob
Press ENTER or type command to continue
```

I already ran a `PlugUpdate` and `PlugUpgrade` - is there anything else I'm missing? It was working just fine on Neovim 0.5.0.

**Comment by tpope** [comment]
This sounds like you have different versions of `plugin/fugitive.vim` and `autoload/fugitive.vim`. Check `:scriptnames` and make sure those 2 files are from the same installation.

**Comment by Timothee** [comment]
For what it's worth, I received a similar error in a long-running Vim session after I had updated `vim-fugitive` in the background. Restarting Vim was the only thing I needed to do.
