### ISSUE TITLE
:Git branch sorting by last activity

### ISSUE THREAD

**Issue by timsofteng** [tpope/vim-fugitive#1983]
Hello. is it possible to make ability to sort git branches in `:Git branch` by last activity?
`lazygit` sorts it by last checkout.
So imagine you checkout to branch `A`. I goes to top. Then you checkout to `B` and it goes on to and `A` is under `B`.
I find it pretty useful.

**Comment by tpope** [comment]
`:Git branch` is just `git branch`. So dynamic behaviors like this aren't possible.
