### ISSUE TITLE
Anyway to make `:Git show` to do vertical split by default

### ISSUE THREAD

**Issue by adam900710** [tpope/vim-fugitive#1985]
Hi,

The default behavior of `:Git show` is to create a new horizontal window to display the contents.
Which is not really that wide-screen friendly.

Is there anyway to make it spawn a vertically split new window?

**Comment by tpope** [comment]
It's not configurable, but you can `:vert Git show`.

**Comment by adam900710** [comment]
Thanks at least is faster than `:Git show` then change the window to vertical.

**Comment by Davincible** [comment]
Along the same lines, is it possible to set the place (left/right, top/bottom)? I know the `splitright` `splitbelow` are global options that can be set, but how about for one command?
