### ISSUE TITLE
checkout a single file from a specific commit

### ISSUE THREAD

**Issue by smalinux** [tpope/vim-fugitive#1993]
First of all, thank you for this project.
I apologize if this question is too simple.

Assume that I'm stopped at a specific commit using: [fugitive.txt#L72](https://github.com/tpope/vim-fugitive/blob/5b62c75238bf04b3156ffe62f821930827de8578/doc/fugitive.txt#L72)
How I could view another file under the same commit?
I'm using `git checkout hash-id path-to-file` [[link](https://stackoverflow.com/a/11233408/5688267)]
but I'm looking for git-fugitive way to do that.

Thanks

**Comment by tpope** [comment]
Press `<CR>` to view the commit and then `:Gedit !:path-to-file` to navigate to a path in that commit. That `!` is [this `!`](https://github.com/tpope/vim-fugitive/blob/5b62c75238bf04b3156ffe62f821930827de8578/doc/fugitive.txt#L624-L625).
