### ISSUE TITLE
Recent change breaks the rendering of section z in vim-airline 

### ISSUE THREAD

**Issue by mux** [tpope/vim-fugitive#2000]
Ever since I updated my plugins a few weeks ago, the rightmost section of my statusline from vim-airline has been broken with some files. Instead of the usual line/column numbers display, it shows the default black and white statusline somehow. When I open a new file, it somehow fixes the issue. More confusing is that this doesn't happen with all types of files: editing my vimrc works fine for instance, but editing a shell script or a C file triggers the issue.

After commenting out various sections of my vimrc, I narrowed this issue down to the fugitive plugin. I also tried to move the inclusion of this plugin later or sooner in my vim-plug section, which didn't help. Looking at recent releases, it seems it could be due to the lazy initialization changes.

Thanks in advance!

**Comment by tpope** [comment]
Airline should replace its calls to `fugitive#head()` with `FugitiveHead()`. Lazily loading the autoload file means that `exists('*fugitive#head')` is no longer a reliable way to detect Fugitive.

**Comment by mux** [comment]
Thank you so much for the very fast answer! I will open a ticket on vim-airline then.

**Comment by chrisbra** [comment]
Unless I am missing something, vim-airline does already use it:

https://github.com/vim-airline/vim-airline/blob/c4655701431a9c79704c827fd88a4783ec946879/autoload/airline/extensions/branch.vim#L99-L101

https://github.com/vim-airline/vim-airline/blob/c4655701431a9c79704c827fd88a4783ec946879/autoload/airline/util.vim#L145-L150

**Comment by tpope** [comment]
My advice was based on looking at the wrong branch. What's on master should work. `FugitiveHead()` is 4 years old, so `fugitive#head()` support can be dropped entirely at your discretion.

**Comment by tpope** [comment]
If the statusline was rendered before the plugin file was loaded but after the autoload file was loaded, it could cause symptoms like this, because `fugitive#head()` recently changed to throw an error about it being obsolete. That's not the usual load order, but any plugin calling a `fugitive#whatever()` function could cause the autoload file to load early.

So on second thought, the sooner `fugitive#head()` support is dropped, the better.

**Comment by mux** [comment]
That doesn't seem to be the issue here unfortunately, unless I missed something. I removed all the references to `fugitive#head()` in the vim-airline code and I still observe the same behavior.

**Comment by chrisbra** [comment]
Thanks, I have removed that for now. @mux can you please show me what this statusline looks like? Also what is your configuration? Feel free to move this over to the vim-airline repo however.

**Comment by mux** [comment]
I'll get you this ASAP.

**Comment by chrisbra** [comment]
@tpope is fugitive still supporting vim 7.4?

**Comment by tpope** [comment]
Yes.
