### ISSUE TITLE
Commit hash length should be equal in `:G blame` and `:Gclog`

### ISSUE THREAD

**Issue by mambusskruj** [tpope/vim-fugitive#2003]
Sometimes I need to blame the file, copy commit hash from blame window, open the log, search for the hash, and check commits below/above it. 

The thing is that commit hash length in `:G blame` equals 10, but in `:Gclog` hash length equals 9. So it is a little bit confusing.

**Comment by tpope** [comment]
Not a Fugitive thing. `git blame` adds an extra digit to allow room for the `^` on boundary commits.
