### ISSUE TITLE
An empty [No Name] buffer is created

### ISSUE THREAD

**Issue by rockyzhang24** [tpope/vim-fugitive#2004]
To reproduce:

1. First of all, open a tracked but unstaged file
2. Execute `:tab Git`
3. In fugitive index, move cursor to this unstaged file and then execute `dd`
4. Run `:ls` and we can find an empty buffer named `[No Name]`

<img width="1726" alt="Screen Shot 2022-05-31 at 14 57 40" src="https://user-images.githubusercontent.com/11582667/171291164-7e2e7b1c-6290-424b-9f2d-cec5ed5fb77c.png">

Thank you.

**Comment by tpope** [comment]
Can't reproduce. Please try with only Fugitive installed.

**Comment by rockyzhang24** [comment]
Yes, I already tried with only Fugitive installed and the issue happened again. Btw, I use Neovim and built it via the latest commit. Thanks.

**Comment by tpope** [comment]
The issue appears to happen with `:set hidden`, which Neovim sets by default.

**Comment by rockyzhang24** [comment]
Okay, got it. Is it a bug or a feature of `hidden` and should I open an issue in Neovim? Or can it be handled and solved by Fugitive? Thanks.
