### ISSUE TITLE
Git add completion

### ISSUE THREAD

**Issue by holmanb** [tpope/vim-fugitive#2006]
I'm transitioning to vim-fugitive, but `:Git add` completion is a (minor) pain point. Is a `:Git add <tab>` completion helper possible?

I sometimes use a shell script to select which files to add:
```
git ls-files -m -o --exclude-standard	\
	| fzf -m --print0		\
	| xargs -0 -o -t git add
```

This picks up unstaged and untracked files for selection, which I think is a pretty reasonable completion list.

Currently in fugitive it looks like tags and branches are in the completion list:
```
~        origin/blame_color     Variable      
~        origin/buffer_path     Variable      
~        origin/nested/test     Variable      
~        origin/blame_message   Variable      
~        origin/double-status   Variable      
~        origin/http_github_fi  Variable      
~        CONTRIBUTING.markdown  Variable      
[No Name origin/parallel-status Variable                                                                                                                                                 0,0-1          All
:Git add            
```

I did take a look in the existing completion code, however my vim-script skills are probably not high enough quality to add this.

Apologies if this is a duplicate. I tried searching for issues like this, but "add" is pretty non-unique.

**Comment by holmanb** [comment]
Seeing now that `:Git` is >> powerful than `:Git add`, so this request probably doesn't make much sense.

**Comment by tpope** [comment]
It makes _some_ sense. Other commands like `:Git push o<Tab>` have special case completion. In theory the same could be done for `:Git add`. That said, it's a pretty deep rabbit hole that I don't plan to venture down anytime soon.
