### ISSUE TITLE
Pre-process such as formatting code before Gdiffsplit

### ISSUE THREAD

**Issue by extr15** [tpope/vim-fugitive#2007]
Thanks for your great work.
I use `Gdiffsplit` to compare a file between versions, but sometimes the file may have been formatted by some tools, so it's difficult to find what has really changed.
Is there a way to format the code of two versions before passing them to `vimdiff`?
I know this may not relate much to `fugitive`, but I appreciate your advice.

**Comment by tpope** [comment]
`vimdiff` compares the literal contents of the 2 buffers. The closest you could get would be reformatting both buffers to match.
