### ISSUE TITLE
Error raised on startup

### ISSUE THREAD

**Issue by tanducmai** [tpope/vim-fugitive#2008]
After cloning the latest commits for fugitive, I open a file (tracked by Git) with Vim and the following error is raised:

```text
Error detected while processing BufRead Autocommands for "*":
E488: Trailing characters: unlet b:git_dir endif
```

Hope it could be fixed soon. 
Regards

**Comment by leoatchina** [comment]
commit `f60fc79e53324a7ad90ed11c`   donot rise this error
