### ISSUE TITLE
b:git_dir maybe lost

### ISSUE THREAD

**Issue by Shane-XB-Qian** [tpope/vim-fugitive#2010]
after recently (yesterday?) change, `b:git_dir` maybe lost at init,
did not check code very detail, but seems `FugitiveDetect` was going to set `b:git_dir` as well, now the replacement only check and clean it.

**Comment by tpope** [comment]
That was no accident. If you were using it to check for a repo, switch to `!empty(FugitiveGitDir())`.

**Comment by Shane-XB-Qian** [comment]
> That was no accident. If you were using it to check for a repo, switch to `!empty(FugitiveGitDir())`.

i am not using it to check for a repo, but some extr plugins (based on fugitive) would call e.g `FugitiveFind(sha, b:git_dir)`

-- 
shane.xb.qian

**Comment by tpope** [comment]
The Git dir of the current buffer is the default. You can use `FugitiveFind(sha)`.

**Comment by Shane-XB-Qian** [comment]
@junegunn
gv

**Comment by tpope** [comment]
Or if you are trying to use another buffer's repo, you can use `FugitiveFind(sha, bufnr)`.

**Comment by Shane-XB-Qian** [comment]
ok, they may search here, let it them think how to modify.
// to gv, seems default without `g:git_dir` was ok.

**Comment by tpope** [comment]
We used to set `b:git_dir` eagerly. Now we set it lazily, on demand. This is a faster, better experience for everyone. The only downside is that plugins that were using it directly, which was **NEVER OFFICIALLY SUPPORTED OR NECESSARY**, now require a small change to restore functionality. Seems like a good deal to me.

`fugitive#repo()`, on the other hand, was indeed an official API. It was informally deprecated about 4 years ago. It was actually this very issue that convinced me now is the right time to pull the plug. May as well get all the breakages out of the way now, no? It could be temporarily rolled back if it's a significant pain point. But I would want to know _which_ methods on it were in popular use.

**Comment by Shane-XB-Qian** [comment]
repo.dir()
repo.tree()
repo.config()
those 3 should be the most popular ones, 
// but anyway, i did not use these, but i locally tried to mdf some plugins, i saw these 3 is in common.
// but since this changes had been implemented at your side, so perhaps let it be, no worthy to rollback again.

**Comment by Shane-XB-Qian** [comment]
btw: your last commit in those `throw` looks had some incorrect, e.g `FugitiveConfigGet(...).stdout`, looks there is not `stdout`

**Comment by tpope** [comment]
> // but since this changes had been implemented at your side, so perhaps let it be, no worthy to rollback again.

I will leave things as is for now. If this is still a problem 1 month from now, I will be open to rolling back.

> btw: your last commit in those `throw` looks had some incorrect, e.g `FugitiveConfigGet(...).stdout`, looks there is no `stdout`

Fixed, thanks.
