### ISSUE TITLE
Retrieve diffs file-wisely

### ISSUE THREAD

**Issue by jaekyeom** [tpope/vim-fugitive#2011]
Hi,
Following [CONTRIBUTING](../blob/master/CONTRIBUTING.markdown), I'd like to ask you first.

Currently, there are tons of (~88k) diff lines in one of my repositories and it looks that in fugitive's status buffer, opening diffs for a file that appears late in the file list takes some time, even if its own diff size is small.
After some profiling, I realized that the loop over `fugitive#Wait(b:fugitive_diff[info.section]).stdout` was the time-consuming part.
Using the git command similarly to fugitive (`git -c diff.suppressBlankEmpty=false diff --color=never --no-ext-diff --no-prefix`) but directly on the command line takes `2.63s user 0.31s system 99% cpu 2.952 total`, but getting diffs for a specific file path of course takes only like `0.01s user 0.00s system 81% cpu 0.020 total`.

There may be a reason for the design choice of which I'm not aware, and having this many diff lines is not very usual,
but what do you think about changing it to retrieve diff lines file-wisely instead of the current section-wise manner?

**Comment by tpope** [comment]
Is it the loop that's slow or the Git command? Are you trying to get faster than 2.63 seconds, or is that 2.63 seconds just the tip of the iceberg?

**Comment by jaekyeom** [comment]
A very good point.
If my understanding that the diff lines are cached by fugitive is correct and the cached ones are used instantly without waiting when `b:fugitive_diff[info.section]` doesn't contain a key `job`,
then I believe the loop takes extra ~2 seconds (when it's not being profiled) besides the git command.
Some profiling of *re*-opening diffs for a specific file:
```
88004   0.205531   0.205245     for line in fugitive#Wait(b:fugitive_diff[info.section]).stdout
88004              0.238915       if mode ==# 'await' && line[0] ==# '@'
    1              0.000002         let mode = 'capture'
88004              0.144168       endif
88004              0.424440       if mode !=# 'head' && line !~# '^[ @\+-]'
   23              0.000110         if len(diff)
    1              0.000002           break
   22              0.000045         endif
   22              0.000067         let start = index
   22              0.000066         let mode = 'head'
87981              0.228674       elseif mode ==# 'head' && line =~# '^diff '
                                    let start = index
87981              0.341038       elseif mode ==# 'head' && substitute(line, "\t$", '', '') ==# '--- ' . info.relative[-1]
    1              0.000002         let mode = 'await'
87980              0.334267       elseif mode ==# 'head' && substitute(line, "\t$", '', '') ==# '+++ ' . info.relative[0]
                                    let mode = 'await'
87980              0.207387       elseif mode ==# 'capture'
   65              0.000211         call add(diff, line)
87915              0.230145       elseif line[0] ==# '@'
  481              0.001104         let mode = ''
88003              0.144425       endif
88003              0.198531       let index += 1
88004              0.149745     endfor
```

And, to be specific, I hope it gets much faster than 2.63 seconds.

**Comment by tpope** [comment]
The loop could probably be replaced with something more efficient. You can test this yourself: Try `:echo index(b:fugitive_diff[info.section], "diff --git your/file your/file")` and compare how fast that is to expanding `your/file`. (Make sure it returns a big number to confirm it's actually finding the correct line)`.

I'm not inherently opposed to individual diffs but I'm not convinced it's worth it either. We do all the diffing when loading the buffer, so that it's in sync with the status output, and allow it to run in the background. Multiple diffs would add parallelism at the expense of overhead; it would likely be faster for many cases but slower for some.

Are the bulk of these diff lines worthless to you? For example, are they in generated files you don't look at directly? If so you may find `-diff` in `.gitattributes` to be a much more practical solution to the problem.

**Comment by jaekyeom** [comment]
Thanks for the suggestions!

Using `index` was indeed a lot faster:
```

**Comment by jaekyeom** [comment]
Thanks for the comment!

A quick test showed that using `index()` was indeed much more faster (and `start` and `start2` were the same in this case):
```
    1   0.000375   0.000039     call fugitive#Wait(b:fugitive_diff[info.section])
    1              0.004332     let start2 = index(b:fugitive_diff[info.section].stdout, "diff --git " . info.relative[0] . " " . info.relative[0])
88004   0.207471   0.207222     for line in fugitive#Wait(b:fugitive_diff[info.section]).stdout
88004              0.237959       if mode ==# 'await' && line[0] ==# '@'
    1              0.000002         let mode = 'capture'
88004              0.140160       endif
88004              0.454961       if mode !=# 'head' && line !~# '^[ @\+-]'
   23              0.000103         if len(diff)
    1              0.000002           break
   22              0.000042         endif
   22              0.000069         let start = index
   22              0.000061         let mode = 'head'
87981              0.233754       elseif mode ==# 'head' && line =~# '^diff '
                                    let start = index
87981              0.337836       elseif mode ==# 'head' && substitute(line, "\t$", '', '') ==# '--- ' . info.relative[-1]
    1              0.000002         let mode = 'await'
87980              0.329006       elseif mode ==# 'head' && substitute(line, "\t$", '', '') ==# '+++ ' . info.relative[0]
                                    let mode = 'await'
87980              0.208179       elseif mode ==# 'capture'
   65              0.000247         call add(diff, line)
87915              0.228757       elseif line[0] ==# '@'
  481              0.001091         let mode = ''
88003              0.140922       endif
88003              0.203444       let index += 1
88004              0.145807     endfor
    1              0.000192     echom start . " " . start2
```
Can we eliminate this loop if we do not switch to per-file diffing, then? That still will be a huge speed gain for me.

> We do all the diffing when loading the buffer, so that it's in sync with the status output, and allow it to run in the background. Multiple diffs would add parallelism at the expense of overhead; it would likely be faster for many cases but slower for some.

Since there can be many changed files, we probably can't simply launch all the jobs in parallel; managing a pool of workers or limiting the maximum number of concurrent jobs at least add some complexity, I guess.
But do you think there would be a non-negligible overhead as well if the user sets something like `let g:fugitive_num_concurrent_jobs = 1`, or do you consider the complexity as the main issue here?
(On a different note, I'm not that familiar with the internals of fugitive, but per-file diffing might also allow partial update of the status during it's open, maybe?)

> Are the bulk of these diff lines worthless to you?

No, I bulk-open diffs in some different situations (I wouldn't do that in this repo, though).

> If so you may find `-diff` in `.gitattributes` to be a much more practical solution to the problem.

Thanks, I'll check and see if it helps my use cases.

**Comment by tpope** [comment]
> Thanks for the comment!
> 
> A quick test showed that using `index()` was indeed much faster (and `start` and `start2` were the same in this case):
> 
> ```
>     1   0.000375   0.000039     call fugitive#Wait(b:fugitive_diff[info.section])
>     1              0.004332     let start2 = index(b:fugitive_diff[info.section].stdout, "diff --git " . info.relative[0] . " " . info.relative[0])
> 88004   0.207471   0.207222     for line in fugitive#Wait(b:fugitive_diff[info.section]).stdout
> 88004              0.237959       if mode ==# 'await' && line[0] ==# '@'
>     1              0.000002         let mode = 'capture'
> 88004              0.140160       endif
> 88004              0.454961       if mode !=# 'head' && line !~# '^[ @\+-]'
>    23              0.000103         if len(diff)
>     1              0.000002           break
>    22              0.000042         endif
>    22              0.000069         let start = index
>    22              0.000061         let mode = 'head'
> 87981              0.233754       elseif mode ==# 'head' && line =~# '^diff '
>                                     let start = index
> 87981              0.337836       elseif mode ==# 'head' && substitute(line, "\t$", '', '') ==# '--- ' . info.relative[-1]
>     1              0.000002         let mode = 'await'
> 87980              0.329006       elseif mode ==# 'head' && substitute(line, "\t$", '', '') ==# '+++ ' . info.relative[0]
>                                     let mode = 'await'
> 87980              0.208179       elseif mode ==# 'capture'
>    65              0.000247         call add(diff, line)
> 87915              0.228757       elseif line[0] ==# '@'
>   481              0.001091         let mode = ''
> 88003              0.140922       endif
> 88003              0.203444       let index += 1
> 88004              0.145807     endfor
>     1              0.000192     echom start . " " . start2
> ```
> 
> Can we eliminate this loop if we do not switch to per-file diffing, then? That still will be a huge speed gain for me.

We can if we go from "this case" to "all cases". Notably, we need to handle renames (can probably be handled with `info.relative[-1]` as the first argument), adds and deletes (this probably already works, but needs to be verified), and file names with unusual characters like quotes and spaces. Researching the behavior here is the next step.

> > We do all the diffing when loading the buffer, so that it's in sync with the status output, and allow it to run in the background. Multiple diffs would add parallelism at the expense of overhead; it would likely be faster for many cases but slower for some.
> 
> Since there can be many changed files, we probably can't simply launch all the jobs in parallel; managing a pool of workers or limiting the maximum number of concurrent jobs at least add some complexity, I guess. But do you think there would be a non-negligible overhead as well if the user sets something like `let g:fugitive_num_concurrent_jobs = 1`, or do you consider the complexity the main issue here?

Yeah, that sounds like a nightmare to implement and maintain.

> (On a different note, I'm not that familiar with the internals of fugitive, but per-file diffing might also allow partial update of the status during it's open, maybe?)

It would, but in an ad hoc and hard to reason about way. Not exactly keen to open this can of worms either. I'd rather show a stale diff than do nothing at all because a change was present when the status buffer was loaded has since been removed.

**Comment by tpope** [comment]
Curiosity knocked the best of me and I knocked this out.

I am officially ruling out whole concurrent jobs thing. It's just too complex for too narrow of use case. On demand diffing, made to work robustly, I would still consider, as that would benefit everyone. But I don't have a game plan there, or plans to pursue further at this time.

**Comment by jaekyeom** [comment]
Oh wow, I've just checked it out, and opening diffs is very smooth now once the diffs are loaded!
Thank you and your curious mind.

> Yeah, that sounds like a nightmare to implement and maintain.

> I am officially ruling out whole concurrent jobs thing. It's just too complex for too narrow of use case.

I agree.

> On demand diffing, made to work robustly, I would still consider, as that would benefit everyone. But I don't have a game plan there, or plans to pursue further at this time.

I totally understand, and the current solution is still a big improvement for me. I appreciate that.
