### ISSUE TITLE
Gclog triggers a continuous background cmd window executing command in WIN10

### ISSUE THREAD

**Issue by ericsunplus** [tpope/vim-fugitive#2012]
Hi there,

I find a problem on windows on `Gclog`, even with `Gclog -1`.

After executing this command, the patch window will show up with the HEAD commit difference, but the vim is almost losing response because there is a background windows command window keeps opening and closing. A screenshot is  

![image](https://user-images.githubusercontent.com/7379534/173237760-2a82817c-9a47-40cf-b20e-c8d9872082b8.png)

This don't happen on Ubuntu with the same repo so should be a windows specific problem. (WIN10 + VIM 8.2 + Fugitive@92c73bb0).   Any hint or advice on this phenomenom?

**Comment by tpope** [comment]
`--exact-match` appears nowhere in Fugitive's source code. My guess is you've got something else in your config mucking things up.

**Comment by ericsunplus** [comment]
Thanks you @tpope , your answer shed lights on me to do a grep search on my vim plugin directories, turns out `--exact-match` only exist in `vim-airline/autoload/airline/extensions/branch.vim`. I don't update that plugin since 2019, after update it to latest the issue no longer happens.
