### ISSUE TITLE
Providing args for `FugitiveExecute()`?

### ISSUE THREAD

**Issue by tomtomjhj** [tpope/vim-fugitive#2016]
`FugitiveExecute()` itself doesn't preprocess the argument.
So, to make a custom command using `FugitiveExecute()` (e.g., something like [gv.vim](https://github.com/junegunn/gv.vim) and [vim-flog](https://github.com/rbong/vim-flog)),
I would have to write code to parse `<q-args>` and expand `fugitive-object` myself.
It would be great if this functionality is baked in to `FugitiveExecute()` or provided as another API function (i.e. a wrapper for `s:SplitExpandChain()`).

**Comment by tpope** [comment]
You can use the unofficial API `fugitive#Expand()` for this, paired with `<f-args>` if you have multiple arguments. This isn't quite the same thing as what Fugitive does internally, but it's probably good enough for most purposes. There's various edge cases I need to iron out before i can provide an official API. I'll do my best to keep `fugitive#Expand()` stable, despite being unofficial, until a better option is available.

`FugitiveExecute()` is a low level API intended to accommodate a wide variety of use cases, and thus should not be concerned with parsing user input.
