### ISSUE TITLE
sourcehut GBrowse broken

### ISSUE THREAD

**Issue by p00f** [tpope/vim-fugitive#2021]
after https://github.com/tpope/vim-fugitive/commit/8fd6bad4a4dfbad85d57d03e5ba12a00effbfe8c, `:GBrowse` with the sourcehut provider is broken (`%` instead of `~` in the address bar)

**Comment by tpope** [comment]
Can you spare me the trouble of creating an account and show me exactly what a URL looks like and what a URL is supposed to look like?

**Comment by p00f** [comment]
The url looks like `https://git.sr.ht/%p00f/disassembler/tree/main/item/src/instruction.rs`, it should be `https://git.sr.ht/~p00f/disassembler/tree/main/item/src/instruction.rs` taking me to https://git.sr.ht/~p00f/disassembler/tree/main/item/src/instruction.rs
