### ISSUE TITLE
Issue when Staging File

### ISSUE THREAD

**Issue by colin99d** [tpope/vim-fugitive#2023]
When I try to stage a file by pressing the `-` button I frequently get the following error:
`Error detected while processing function <SNR>80_Do[47]..function <SNR>80_Do[42]..<SNR>80_ReloadStatus[2]..<SNR>80_ReloadStatusBuffer[6]..fugitive#BufReadStatus[256]..BufRead Autocommands for "*":`

**Comment by tpope** [comment]
This is a stacktrace without an error message. There's nothing after the `:`?

**Comment by colin99d** [comment]
Sorry about that! The error is `E20: Mark not set`.

**Comment by tpope** [comment]
Fugitive is calling `doautocmd BufReadPost`, which calls every `BufReadPost` (and the synonym `BufRead`) autocommand in your vim config, and one of those is causing this error. Try disabling other plugins and/or your vimrc to isolate the problem.
