### ISSUE TITLE
Tab to toggle detailed change visibility should toggle all-on/all-off

### ISSUE THREAD

**Issue by andmis** [tpope/vim-fugitive#2026]
Say I have two files with staged changes in them. I can press Tab with my cursor on either of the two filenames to toggle whether the detailed change view is visible for that file. I can also press Tab with my cursor on the word "Staged". The way I would expect this to work is: if all of the detail views are visible, hide them all, and if they are all hidden, then show them all. That part works as expected. I would also expect that if *any* detail views are visible, then they are *all* hidden. Instead, Tab seems to toggle the views individually. So if the detail view for file 1 is visible and for file 2 is hidden, then pressing Tab with the cursor on "Staged" will result in the detail view for file 1 becoming hidden, and that of file 2 becoming visible. This is not how "select all" checkboxes usually work – and the "Staged" line functions as a "select all" checkbox in this UX.

**Comment by tpope** [comment]
Fugitive doesn't map Tab; I take it you mean `=`. I think this is not a huge deal in light of the `<` and `>` maps, but I wouldn't say no to a patch that implements the behavior you propose.
