### ISSUE TITLE
Open File Not Commit [feature question]

### ISSUE THREAD

**Issue by novasenco** [tpope/vim-fugitive#2027]
I would like to go to the file on the disk. When you're viewing a commit, you'll see something like this

```
diff --git a/Foo/Bar/Qux/Baz/Taco/Foo.ts b/Foo/Bar/Qux/Baz/Taco/Foo.ts
index Ze34v8j57..b9eg0oej7 6942
--- a/Foo/Bar/Qux/Baz/Taco/Foo.ts
+++ b/Foo/Bar/Qux/Baz/Taco/Foo.ts
@@ -42,2 +42,2 @@ export namespace Foobar {
foo
-bar
+qux
baz
```

The only way to get to `Foo/Bar/Qux/Baz/Taco/Foo.ts` is to select it carefully after `a/` or `b/` and do <kbd>g</kbd><kbd>f</kbd> or manually do `:e ...`. Did I miss a mapping in `g?`, and if not, would it be possible to make `<buffer> gf` map that either understands to just strip off `/[ab]\//` prefix or maybe some mapping that knows how to get to the file associated with the commit chunk under the cursor?

Thanks 😄 awesome plugin of course

---

for clarity, I would like to go to `Foo/Bar/Qux/Baz/Taco/Foo.ts` on disk with a couple of keys instead of `<cr>` or <kbd>Return</kbd> which brings me to `fugitive:///home/nova/FooBarProj/.git/qwerqwerqwerqwerqwerqwe/Foo/Bar/Qux/Baz/TacoFoo.ts`

**Comment by tpope** [comment]
The most straightforward way to do this is to use the `<CR>` map to go to the `fugitive://` buffer and then `:Ge` to get to the file on disk.
