### ISSUE TITLE
commit diffs?

### ISSUE THREAD

**Issue by xmready** [tpope/vim-fugitive#2028]
How can I toggle the diff for a single commit compared against the state of the file just before it was committed? Would love to figure this out, thanks.

**Comment by tpope** [comment]
Not sure I understand the question, but sounds like you might want `:Gedit <commit-sha>`.

**Comment by xmready** [comment]
Yes, this is indeed what I was looking for. Is there a map to open the commit under the cursor with `Gedit` when looking at `Git log` or `Git log --oneline`?

**Comment by xmready** [comment]
Thank you that works! And I just learned you can hit enter on a commit to invoke `Gedit` happy days!
