### ISSUE TITLE
[BUG] `:G` summary screen doesn't show up

### ISSUE THREAD

**Issue by crashmoney** [tpope/vim-fugitive#2032]
In some Git repositories, entering the command `:G` or `:Git` doesn't bring up the summary screen. There's no visible error message. `:G status`, however, still works as expected.

The summary screen seems to work only in cloned repositories. It doesn't load in local repos without a remote origin or similar, even if all Git files are in the standard `.git` folder.

**Comment by tpope** [comment]
Can you reproduce it in a brand new repository created by `git init` in an empty directory? I can't.

**Comment by tpope** [comment]
You can use `:Gedit :` to open the status buffer without any special window behavior. This simplification might be enough to allow a previously hidden error message to shine through.

I need either an error message or the ability to reproduce to proceed on this.

**Comment by crashmoney** [comment]
I think I've found a way to reliably reproduce this error. When the directory is in iCloud, i.e. `Library/Mobile Documents`, it fails. `:Gedit :` also doesn't open any status buffer at all. However, when it's stored locally, i.e. in the home folder, it works. Is there any fix to make the summary screen appear in iCloud directories too? Thank you.

**Comment by tpope** [comment]
I tested with an empty repository and can't reproduce there either. There is a 99% chance this is iCloud locally deleting parts of the repository it doesn't think you're using. Doing anything with ordinary files here is a fantastically bad idea.
