### ISSUE TITLE
Status line rendering broken with lazy initialization on VIM 7.4 and CentOS 7

### ISSUE THREAD

**Issue by macEngine** [tpope/vim-fugitive#2034]
I am using VIM 7.4 and CentOS 7.

The problem is pretty much like [vim airline 2537](https://github.com/vim-airline/vim-airline/issues/2537).

When I open a file for the first time, the problem doesn't happen and the status line is correct. 
When I go the bottom of the file, the status line is broken.

I tried to debug and  here is a discovery of the issue I am seeing:

line 19 of fugitiveline.vim([link](https://github.com/vim-airline/vim-airline/blob/0241bdb804990a965b8a8988a8b37ce16e6e0486/autoload/airline/extensions/fugitiveline.vim#L19)), <code>exists('*fugitive#repo')</code> return false. when it goes to [line 24](https://github.com/vim-airline/vim-airline/blob/0241bdb804990a965b8a8988a8b37ce16e6e0486/autoload/airline/extensions/fugitiveline.vim#L24), VIM resports that <code>fugitive#buffer()</code> does not exist error.

Please note: It seems that VIM 8 doesn't have such issue. <code>exists('*fugitive#repo')</code> return true as I test.

Thanks in advance!

**Comment by tpope** [comment]
Wrong repo.

**Comment by macEngine** [comment]
> Wrong repo.

You mean I should open an issue for vim-airline repo? 

I thought it was related to lazy initialization. Sorry if I misunderstood.

**Comment by tpope** [comment]
Yes. Actually that whole `elseif` is for _old_ Fugitive versions. It should probably be deleted entirely. And the one after it, too.

**Comment by chrisbra** [comment]
@tpope are you saying this:

https://github.com/vim-airline/vim-airline/blob/0241bdb804990a965b8a8988a8b37ce16e6e0486/autoload/airline/extensions/fugitiveline.vim#L19-L28

can be deleted?

**Comment by tpope** [comment]
Yep, like that last change we made it's for Fugitive versions that are now very old.
