### ISSUE TITLE
How to change the order of windows opened by Gdiffsplit?

### ISSUE THREAD

**Issue by MahdiNazemi** [tpope/vim-fugitive#2037]
The documentation says
> With no argument, the version in the index or work tree is used, and the work tree version is always placed to the right or bottom, depending on available width.

IIRC, I have read in answers to some of the issues that `Gdiffsplit` is very similar to (or based on?) `diffsplit`, e.g.,

> It's just `:diffsplit`. See `:help 'diffopt'`.

_Originally posted by @tpope in https://github.com/tpope/vim-fugitive/issues/1911#issuecomment-1002253728_

I have the following line in my `~/.vimrc`:

    set splitbelow splitright

However, the order is still the same as what the documentation says. Is there anything I can do to resolve the issue?

P.S. Vim noob here.

**Comment by tpope** [comment]
Give it an argument, like `>:0`. The zero argument form, which with regular `:diffsplit` isn't useful at all, takes liberties...
