### ISSUE TITLE
Keep alternate file when using `:Gedit :`

### ISSUE THREAD

**Issue by mroavi** [tpope/vim-fugitive#2040]
I use `:Gedit :` for navigation between dirty files (as suggested in https://github.com/tpope/vim-fugitive/issues/1296). This allows me to open files in the same window. However, I noticed that this approach modifies the alternate file. I partially solved this by using `:keepalt Gedit :<CR>` to open the summary window. However, I haven't found a way to map `<CR>` and `gq` such that the alternate file name is kept (e.g. by using `:keepalt`). Any ideas on how to do this?

**Comment by tpope** [comment]
There's no official way to do this. You could probably rig something up by building on top of the `.` map, which puts the filename under the cursor on the command line. Perhaps `.keepalt Gedit`.
