### ISSUE TITLE
Cannot remap `q` to `gq`

### ISSUE THREAD

**Issue by babygau** [tpope/vim-fugitive#2049]
I'm trying to remap `q` to `gq` because I want that old remap, however it's not working either with autocmd or in `after/ftplugin/fugitive.lua`, `after/ftplugin/fugitiveblame.lua`

```
vim.api.nvim_create_autocmd("FileType", 
                            {command = "nmap <buffer> q gq", 
                             group = "smart_q", 
                             pattern = {"fugitive", "fugitiveblame"}})
```

I'm on latest neovim nightly

Related: https://github.com/tpope/vim-fugitive/issues/1221#issuecomment-1235220213

**Comment by tpope** [comment]
I can confirm the original autocmd works. If you wanna change it to something else, you're on your own.

**Comment by alexventuraio** [comment]
@bangedorrunt I make it work by just adding this `nmap <buffer> q gq` to the `fugitiveblame.lua` file.
