### ISSUE TITLE
Jump to patch (o), from ':Git blame' works only once

### ISSUE THREAD

**Issue by KiranHappy** [tpope/vim-fugitive#2053]
Opening `:Git blame` shows list of commits per line correctly.

When we press 'o' onto any commit , it correctly opens it's details into horizontal split.

But if we again go down into Blame window which is already open and press 'o' onto any other commit,
getting error flashed below as 'fugitive : no commit'

For same commit, if we follow process from start then it opens.
i.e. again do ':Git blame' onto file , then hit 'o' onto commit and it opens, as first time we are hitting 'o' inside commit windows.
Again if we go to any other commit it starts giving error of ' no commit'

This used to work perfectly , don't know why not working now ?

I am using 
Windows 10 
gvim = VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 31 2022 22:29:25)
fugitive @ commit = dd8107cabf5fe85df94d5eedcae52415e543f208

**Comment by tpope** [comment]
If we look at [the code](https://github.com/tpope/vim-fugitive/blob/dd8107cabf5fe85df94d5eedcae52415e543f208/autoload/fugitive.vim#L6745-L6750), there's 3 primary reasons the commit might be missing:

1. The file type isn't `fugitiveblame`
2. The line ins't a regular git blame line, and thus doesn't match the regexp
3. The line contains the special value for uncommitted changes (`000...`)

None of these _should_ change after the first `o` invocation, but a misbehaving autocommand could easily screw up the file type. Check `:verbose set filetype?` in that buffer and see if it's still `fugitiveblame`.
