### ISSUE TITLE
:Git commit not respecting core.editor

### ISSUE THREAD

**Issue by AndreasNasman** [tpope/vim-fugitive#2057]
Hi!

I've configured GIt to use Neovim for commit messages with spell checking turned on:

```git
# ~/.gitconfig
[include]
    path = ~/.config/git/gitconfig

# ~/.config/git/gitconfig
[core]
    editor = nvim -c 'set spell'
```

This works fine whenever I run `git commit`. However, `:Git commit` in Neovim and `cc` in vim-fugitive seem to ignore `core.editor`. Can I fix this behavior somehow?

Thanks!
– Andreas

**Comment by tpope** [comment]
```vim
autocmd FileType gitcommit setlocal spell
```

"Respecting" `core.editor` would mean starting an nvim instance inside another nvim instance. Fugitive goes out of its way to avoid such tomfoolery.

**Comment by AndreasNasman** [comment]
If anyone else stumbles on this, here is the Lua version of the autocommand above:

```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = { "gitcommit" },
  command = "setlocal spell",
})
```
