### ISSUE TITLE
:Gvdiffsplit! won't open file in merge UI

### ISSUE THREAD

**Issue by Pustelto** [tpope/vim-fugitive#2059]
Hi, 

I' using the plugin with neovim and when I have a merge conflict I want to solve, everytime I hit `dv` in the unstaged file or type `:Gvdiffsplit!` command, the plugin will move me to the file with conflict markers, but won't open the the UI for the merge (as in the picture below).

![Screenshot 2022-10-02 at 21 57 06](https://user-images.githubusercontent.com/10606260/193511184-f2da23e0-8515-42b2-90e0-96f4ff530a8e.jpg)

![Screenshot 2022-10-02 at 21 58 01](https://user-images.githubusercontent.com/10606260/193510928-ecf98884-2c13-4c74-8615-054dd091495e.jpg)

However when I run `git mergetool` from command line it will correctly open the UI as expected.

![Screenshot 2022-10-02 at 21 59 19](https://user-images.githubusercontent.com/10606260/193511062-07b4bf5a-535a-40ab-92eb-012bdb34b169.jpg)

 I was searching if there is some specific configuration needed to make this work but couldn't any issue similar to mine. I have set nvim as my mergetool in gitconfig, but that didn't solve the issue as well. 

![Screenshot 2022-10-02 at 21 59 54](https://user-images.githubusercontent.com/10606260/193511226-a27baef8-1285-47b8-a598-564fefb96f49.jpg)

From the docs I understood that hitting `dv` on the unstaged file or type `:Gvdiffsplit!` should have the same effect as typing `git mergetool` in the terminal. Is that correct? If so any idea what could be wrong in my case? I have also tried to disable all other plugins (aside from telescope) and it didn't solve the issue as well.

I'm using neovim 0.7.0

Thanks for help 🙏

**Comment by SamOng553996** [comment]
Tomas Pustelnik ***@***.***> 於 2022年10月3日 週一 14:18 寫道：

**Comment by tpope** [comment]
> From the docs I understood that hitting `dv` on the unstaged file or type `:Gvdiffsplit!` should have the same effect as typing `git mergetool` in the terminal. Is that correct? If so any idea what could be wrong in my case? I have also tried to disable all other plugins (aside from telescope) and it didn't solve the issue as well.

Not exactly the same, but you should get a three-way split, yes. What happens when you do `:Gvdiffsplit!`?

**Comment by Pustelto** [comment]
The content is just moved slightly to the right (I tried it to show it on the pic) and `:ls` still shows only one buffer.
![vim_fugitive](https://user-images.githubusercontent.com/10606260/193661109-a5caa7aa-c9b5-49c4-993e-2bd992825001.jpg)

**Comment by tpope** [comment]
Check `:verbose set diff?` before and after. I'm guessing the column shift is it being put into diff mode. But I don't know how that could happen without a split.

Also check `:verbose nmap dp` and `:verbose nmap d2o`. The presence/absence of those maps could provide another clue as to what's succeeding and what's failing.

Finally, check `:messages` for any errors that appear afterwards.

**Comment by Pustelto** [comment]
So it turned out, the telescope plugin was actually a root cause for this. There is an open issue for that: https://github.com/ahmedkhalf/project.nvim/issues/65.

Sorry to bother you with unrelated bugs and thanks for the help and awesome plugin 🙏.
