### ISSUE TITLE
feature request: changed flag in statusline

### ISSUE THREAD

**Issue by stardiviner** [tpope/vim-fugitive#206]
I hope fugitive can give out a flag in statusline indicates that this file in Git or any VCS else is changed (different with file in Vim buffer or Disk). 
I always use fugitive to modify config file, etc, sometimes the file is long, I do not know where I modified.
So a statusline flag will notice me. I do not always go to see git diff. It waste time very much. Because usually I just modify, then commit.

**Comment by xanderdunn** [comment]
An awesome extension of this would be the option to show flags for lines that have been changed within the past x days.  This would be super helpful for debugging.  I know a bug was introduced within the past x days, so now I need to figure out which lines of code caused it.  Having a gutter indicator on the lines that were changed would be amazingly helpful.

**Comment by blueyed** [comment]
See https://github.com/tpope/vim-fugitive/pull/219 for an older PR in this regard.

@stardiviner 
Why have you closed the issue?

**Comment by stardiviner** [comment]
@blueyed sorry, I thought this feature was implemented.

**Comment by zhiyuanzhai** [comment]
Is there any update?

**Comment by tpope** [comment]
My update is that if people are going to nag me about dormant but not abandoned feature requests in the issue tracker then I guess I will have to close them.
