### ISSUE TITLE
Problem with diff + merge key bind.

### ISSUE THREAD

**Issue by vitorlimadev** [tpope/vim-fugitive#2062]
Hello friends!
I was fixing a big merge conflict, when I saw this file:
<img width="1728" alt="Screenshot 2022-10-07 at 06 22 55" src="https://user-images.githubusercontent.com/30941353/194520936-f2a9cf1d-b9af-4e94-bedf-da62b42f9fc5.png">

When I press d3o, this is what it resolves to:
<img width="1728" alt="Screenshot 2022-10-07 at 06 26 39" src="https://user-images.githubusercontent.com/30941353/194521265-82ebe5a4-c847-49dd-be2f-fb54cd06f294.png">

When I press d3o in the first line of the conflict, it resolves like this:
<img width="1728" alt="Screenshot 2022-10-07 at 06 27 50" src="https://user-images.githubusercontent.com/30941353/194521474-f5e925a7-23a2-4a71-9c71-2c0cbaed4f88.png">

I believe the issue is on the fact that instead of choosing the right code chunk by the merge block, it's getting it from the diff. I don't know vim script but I'll try to see if I can find in the code, where this happens.

Thanks for the attention, I love your plugin! <3

**Comment by tpope** [comment]
`d3o` is a paper thin wrapper around the `:diffget` Vim primitive (see `:help :diffget`). It doesn't care about patch hunks, it just operates on the line that the cursor is on.
