### ISSUE TITLE
Binding to throw away all (Unstaged / Untracked) changes 

### ISSUE THREAD

**Issue by TamaMcGlinn** [tpope/vim-fugitive#2063]
When I want to throw away all changes, I intuitively moved my cursor to the header 'Unstaged' and pressed 'X' but was disappointed that it did not work. Instead, we currently need to enter visual mode, `]` to the end of the paragraph and then 'X' - but it will take a long time (for example 20 seconds for about 300 files in my case) because it is saving each file.

It would be nice to have a quick way to do this.

**Comment by tpope** [comment]
`:Git checkout .` or `:Git clean`. Not everything needs to be a single character map, and a massive foot bazooka like this is the last thing that should be one.

**Comment by TamaMcGlinn** [comment]
But but... X is intuitive, and those commands are long to type and remember. And there is no hook at the moment to define this in my own vimrc without clobbering the normal fugitive behaviour. And, like I said in the PR, we can add a dialog asking if you are sure. You're just closing both immediately? Does that mean you don't want discussion or improvement at all?

**Comment by tpope** [comment]
It's such a nonstarter I don't even know where to begin. Why are you deleting hundreds of changed files so often? Whatever you're doing sounds incredibly weird and niche. You might be the only person on the planet that wants it.

Taking the safe, undoable `X` operator and making it unsafe and permanent when used on a section header is about as far from intuitive as you can get.

**Comment by TamaMcGlinn** [comment]
I can make it safe and undoable by just treating it as if X was done on everything inside that header; this would just obviate the `V]` to select the whole section. To satisfy my need, we could also ask when the number of files is more than some constant (200?) whether we want to do it quickly but without undo. Sound good?

**Comment by tpope** [comment]
> I can make it safe and undoable by just treating it as if X was done on everything inside that header; this would just obviate the `V]` to select the whole section.

I could live with this, but ideally it would come in the form of improving the abstraction, and not more special cases.

> To satisfy my need, we could also ask when the number of files is more than some constant (200?) whether we want to do it quickly but without undo.

Absolutely not.

**Comment by TamaMcGlinn** [comment]
After using it for two days, I am quite happy with it saving everything. Anything else I need to modify to get this merged?
