### ISSUE TITLE
FugitiveHead() is unknown function when running from vimrc with vim9script

### ISSUE THREAD

**Issue by rakkur** [tpope/vim-fugitive#2065]
Hi - I created a repo with no plugins except yours and the core vim9 module here:

https://github.com/rakkur/vim9bugs

setup:
- run gvim.exe
- `:PluginInstall`
- restart gvim.exe

works:
- `:echo FugitiveHead()`

doesn't work:
- ALT-R

ALT-R runs the function in the vimrc.  Am I consuming this incorrectly?  I have several mappings that refer to this function and then run dispatch/fugitive commands (works fine without vim9script).

Thank you for this and your other amazing plugins!  I really appreciate all your hard work; it has aided my workflow incredibly.

**Comment by tpope** [comment]
For Vim9 script, you want:

```vim
echo g:FugitiveHead()
```

**Comment by rakkur** [comment]
Thank you so much!  This worked perfectly.
