### ISSUE TITLE
Go to child commit

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-fugitive#2067]
I find I want to go to a child of the current commit almost as often as I want to go to a parent. Like when commit is found via blame and I want to explore it's branch further.

Would be great to have an opposite of the `-` (or rather `~`/`P`) map in commit buffers for that, based on `--ancestry-path` logic. Rough prototype:

    nnoremap <expr> _ ':Gedit '.split(systemlist("TARGET=".FugitiveParse(expand('%'))[0]." sh -c 'git rev-list ^$TARGET~ HEAD --ancestry-path --children \| grep ^$TARGET'")[0])[1:][v:count].'<CR>'

**Comment by tpope** [comment]
The fact you had to throw a `grep` in there really sums it up. If Git doesn't have a primitive for it, I don't think it's a firm enough concept to commit to a map for it.

The use of a count is also a red flag. How do you know you want the second child without seeing the list of children? For the parent maps, it's common to arrive from the commit object, which gives you a chance to see the parents ahead of time. This is still super niche, but at least it's a conceivable workflow. For children, this is exposed nowhere.

**Comment by tpope** [comment]
> > If Git doesn't have a primitive for it, I don't think it's a firm enough concept to commit to a map for it.
> 
> Unlikely that better primitive will ever appear in Git – `--ancestry-path` is naturally tied to traversal.
> 
> At the same time `--ancestry-path` and `--children` seem like pretty firm APIs to me, designed for use cases like this one.

Best I can tell, you're dumping every child, grandchild, and so on, potentially thousands of lines of output for an older commit, and then filtering it to exactly one line which contains the original commit. It's not designed for your use case at all. You're hitting a screw with a hammer and calling it a screwdriver.

>  Shame that you'd need to downgrade to grunt work on the CLI to use this existing Git feature.

The real shame would be if Fugitive endorsed this contrivance by giving it a map.
