### ISSUE TITLE
Gdiff open 2-way compare window not 3-way

### ISSUE THREAD

**Issue by SharePlainCSource** [tpope/vim-fugitive#2068]
Get 2-way compare window:
open conflict file--->call :Gdiff---->Get 2-way compare window
Get 3-way compare window:
call :Git---->move cursor to conflict file---->click "d"----->click "v"---->Get 3-way compare window

Did I do something wrong?Why Gdiff not work?

**Comment by tpope** [comment]
`:Gdiffsplit!` does the 3-way diff. This is documented, and also loudly announced if you call `:Gdiffsplit` during a conflict:

![Screenshot 2022-10-19 22 47 52 lester - vim --servername vim899547 __Scratch_conflict](https://user-images.githubusercontent.com/378/196844606-7f92df90-9d1b-4f4f-81dc-9a52462b57bd.png)
