### ISSUE TITLE
Git blame and gdiffsplit do not work when a file has been moved

### ISSUE THREAD

**Issue by zdc13** [tpope/vim-fugitive#2070]
Git blame cannot browse to the file when it has been moved and modified in the same commit

Gdiffsplit does not work when the file has been moved between the diffed commits

To reproduce:
```
git init
echo test > myfile
git add . && git commit -m "First commit"
echo test >> myfile
mv myfile myfile_moved
git add .  && git commit -m "Second commit"
```
Open the `myfile_moved` in vim and type `:Gitdiffsplit HEAD^` : `fatal: path 'myfile_moved' exists on disk, but not in ...`

Open the file in vim and type `:Git blame`, go to the second line's commit and press P : `fatal: no such path myfile_moved in ...`

**Comment by tpope** [comment]
> Open the `myfile_moved` in vim and type `:Gitdiffsplit HEAD^` : `fatal: path 'myfile_moved' exists on disk, but not in ...`

Fugitive translates `:Gdiffsplit HEAD^` to `:Gdiffsplit HEAD^:%`. I think this is a reasonable behavior. I don't think it's the _only_ reasonable behavior; certainly rename following can be helpful in some cases. But what _exactly_ do you propose? What Git command do we run that will spit out `myfile` given the appropriate input?

> Open the file in vim and type `:Git blame`, go to the second line's commit and press P : `fatal: no such path myfile_moved in ...`

The behavior here is less reasonable; the blame output is aware of the rename so we probably should be too. The `previous` line in `git blame --incremental` could probably serve as the implementation. It won't work with with a count (`2P`) but I am fine to limit this behavior to the count free version.

But I also consider `P` to be extremely low value compared to `<CR>`, which shows you the change in context. So low value, in fact, that I am taking this as an opportunity to remove it from the documentation. Thus I currently have no plans to pursue this improvement. A motivated contributor might start by looking at the `s:BlameJump()` function.

**Comment by zdc13** [comment]
I use P to go back in history to know how a change developed. It allows me to use vim highlight, lsp and linters on the previous file, and to figure out where exactly a bug appeared. To me this as a lot more value than `<CR>`, which seems to only give the diff (just like a git show <commit> would do), which imo is useless to have inside vim itself. Am I misunderstanding the feature? P allows to go back more than a single blame and *then* to use `p` on the commit that caused an issue.

As for the git diff implementation, a more reasonable implementation might be to use a function to find the latest filename for a commit, like so:
```
git log --pretty=tformat:"%H" --name-only --follow HEAD^^.. % | tail -n 1
```

**Comment by tpope** [comment]
> I use P to go back in history to know how a change developed. It allows me to use vim highlight, lsp and linters on the previous file, and to figure out where exactly a bug appeared.

I'm already lost. Do you regularly commit code with syntax errors, not noticing the syntax highlighting acting up? Or do you leave syntax highlighting off until you encounter an issue and turn it on to help with triage? Same for lsps and linters, those are typically used proactively; do you only break them out to track down bugs? Also I wouldn't expect them to work very well on `fugitive://` buffers?

> To me this as a lot more value than `<CR>`, which seems to only give the diff (just like a git show would do), which imo is useless to have inside vim itself.

One thing you're missing it that the diff is interactive, allowing you to jump to the exact commit, file, and line where a change was added or removed. This is similar to `P`, but you pick what removed line to jump to, rather than Fugitive trying to guess.

But even without that, "useless"? Come on man, it shows you exactly what added and what code was removed, first and foremost locally, but also other potentially related changes in the same commit. Surely you can think of a use or two for that?

> Am I misunderstanding the feature? P allows to go back more than a single blame and _then_ to use `p` on the commit that caused an issue.

What do you do when you press `p` on the commit that caused the issue, only to discover it wasn't the commit that caused the issue, but just a commit that changed something unrelated on the same line?

> As for the git diff implementation, a more reasonable implementation might be to use a function to find the latest filename for a commit, like so:
> 
> ```
> git log --pretty=tformat:"%H" --name-only --follow HEAD^^.. % | tail -n 1
> ```

On the example you gave:

```
$ git log --pretty=tformat:"%H" --name-only --follow HEAD^^.. myfile_moved | tail -n 1
fatal: ambiguous argument 'HEAD^^..': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by zdc13** [comment]
>On the example you gave:

Oh yeah my bad, this doesn't work since the HEAD^^ does not exist in my example (and I forgot the `--`), here's a working version:
```
git log --pretty=tformat:"%H" --name-only --follow HEAD^.. --boundary -- myfile_moved | tail -n 1
```

>One thing you're missing it that the diff is interactive, allowing you to jump to the exact commit, file, and line where a change was added or removed. This is similar to P, but you pick what removed line to jump to, rather than Fugitive trying to guess.

Nice, this is actually way more useful than I thought, it's like a selective `:Gdiffsplit`.

>What do you do when you press p on the commit that caused the issue, only to discover it wasn't the commit that caused the issue, but just a commit that changed something unrelated on the same line?

I quit the preview window and continue my search. I use `P` really for iterative search when someone introduced a bug at one point, but I don't know when to find why it was done this way. I find that the cursor is not well positioned most of the time but it's not a big deal since I can just search using vim. I will try using `<CR>` for a bit and see how it holds up, thanks!

LSP and stuff do not work well in a fugitive: buffer, but you can use :%!linter and vim commands on the buffer directly. But that will also work with the diff view when using `<CR>`.

**Comment by zdc13** [comment]
Sorry missed this, you could do:
`git log --pretty=tformat:"" --name-only --follow (target_commit)..(current_commit) --boundary -- myfile_moved | tail -n 1`
if it's empty reverse them
`git log --pretty=tformat:"" --name-only --follow (current_commit)..(target_commit) --boundary -- myfile_moved | tail -n 1`

Btw, I tried using `<CR>` and find it less intuitive than `P`, and somehow can't get the diff I got that one time (only get a patch which jumps to the commit when I `<CR>` again on a line). Going back in history is tedious since I need to find the corresponding `-` to the `+` and `<CR>` on the `-`, so when there is a big change you have to scroll quite a lot.

**Comment by tpope** [comment]
> Sorry missed this, you could do: `git log --pretty=tformat:"" --name-only --follow (target_commit)..(current_commit) --boundary -- myfile_moved | tail -n 1` if it's empty reverse them `git log --pretty=tformat:"" --name-only --follow (current_commit)..(target_commit) --boundary -- myfile_moved | tail -n 1`

You're using `myfile_moved` here, but we only have `myfile`. `myfile_moved` is the end goal.

> Btw, I tried using `<CR>` and find it less intuitive than `P`, and somehow can't get the diff I got that one time (only get a patch which jumps to the commit when I `<CR>` again on a line).

The only time you won't get a diff if it's a boundary commit (e.g. the first commit in the repo).

> Going back in history is tedious since I need to find the corresponding `-` to the `+` and `<CR>` on the `-`, so when there is a big change you have to scroll quite a lot.

How is `P` any better here? If the line moved, you've got to find where it moved to either way. The difference is that with `<CR>`, you have to look thru the changed lines, while with `P`, you have to look thru the entire file (and if it moved to another file, you're SOL).

Here's [one weird trick](https://github.com/tpope/vim-fugitive/blob/01f3e0af928857128eec8d998948b80ed1678c18/doc/fugitive.txt#L418-L424) to easily find the corresponding `-` to the `+`.

**Comment by zdc13** [comment]
>You're using myfile_moved here, but we only have myfile. myfile_moved is the end goal.

My bad, you're right, after more investigating I don't think it's possible to do a forward follow on a file (at least with `git 2.38.1`). It's doable with a recursive script (follow myfile until it gets deleted (`git log --name-status --full-history --follow (target_commit)..(current_commit) --boundary -- myfile`), check all delete commits if it was a move, recurse). But I think only being able to follow backwards is still a big plus. The forward search is way harder since 2 different branches might have renamed the file and been merged (so you would have to present a choice of files to the user, maybe in a quickfix window).

Thanks for the tips on using `<CR>`, will try it again.

**Comment by brunnre8** [comment]
How are you supposed to move from the patch view to the parent blame though?
Or in other words, assuming I am in "blame view" or however you wanna call the buffer with the author / commit sha, what's the recommended way to move to the parent and reblame there?

I use ~ rather frequently to see how a function changed over time in a specific region (and assuming something interesting happened I open the interactive patch view up in a new window)

**Comment by tpope** [comment]
The `-` line takes you to the parent blob. You can blame with `<CR>`.
