### ISSUE TITLE
Git difftool -y running diff against inexistant file

### ISSUE THREAD

**Issue by Melandel** [tpope/vim-fugitive#2071]
Hello,

On Windows 10, using gvim 8.2 and the version dd8107c of fugitive, I have seen the following behavior:

## Steps to reproduce:
* edit `autoload\fugitive.vim`
* run `Git difftool -y HEAD~`

## Expected behavior:
I see the diff between:
1. current version of `autoload\fugitive.vim`, and 
2. previous version of `fugitive:\\C:\foo\bar\vimfiles\pack\plugins\start\vim-fugitive\.git\b411b753f805b969cca856e2ae51fdbab49880df\autoload\fugitive.vim`

## Actual behavior:
I see the diff between:
1. current version of `autoload\fugitive.vim`, and 
2. previous version of the file `fugitive:\\C:\foo\bar\vimfiles\pack\plugins\start\vim-fugitive\.git\b411b753f805b969cca856e2ae51fdbab49880df\autoload\fugitive.vim\autoload\fugitive.vim` - which does not exist/is empty

## Notes
I spammed some `echomsg` in `fugitive` and found out the following:
* `file` variable calculated [here](https://github.com/tpope/vim-fugitive/blob/dd8107cabf5fe85df94d5eedcae52415e543f208/autoload/fugitive.vim#L6544) is `fugitive:\\C:\foo\bar\vimfiles\pack\plugins\start\vim-fugitive\.git\b411b753f805b969cca856e2ae51fdbab49880df\autoload\fugitive.vim`
* `spec` variable calculated [here](https://github.com/tpope/vim-fugitive/blob/dd8107cabf5fe85df94d5eedcae52415e543f208/autoload/fugitive.vim#L6571) is `fugitive:\\C:\foo\bar\vimfiles\pack\plugins\start\vim-fugitive\.git\b411b753f805b969cca856e2ae51fdbab49880df\autoload\fugitive.vim`
* `spec` variable overwritten [here](https://github.com/tpope/vim-fugitive/blob/dd8107cabf5fe85df94d5eedcae52415e543f208/autoload/fugitive.vim#L6573) is `fugitive:\\C:\foo\bar\vimfiles\pack\plugins\start\vim-fugitive\.git\b411b753f805b969cca856e2ae51fdbab49880df\autoload\fugitive.vim\autoload\fugitive.vim`

I confirm that replacing [this](https://github.com/tpope/vim-fugitive/blob/dd8107cabf5fe85df94d5eedcae52415e543f208/autoload/fugitive.vim#L6571-L6574) code:
```vim
    let spec = s:Generate(file)
    if spec =~# '^fugitive:' && empty(s:DirCommitFile(spec)[2])
      let spec = s:VimSlash(spec . s:Relative('/'))
    endif
```

with the following:
```vim
    let spec = s:Generate(file)

    " .git\ -> .git\\
    let spec = substitute(spec, '\.git\\', '.git\\\\', '')

    " not going inside here anymore
    if spec =~# '^fugitive:' && empty(s:DirCommitFile(spec)[2])
      let spec = s:VimSlash(spec . s:Relative('/'))
    endif
```

produces the expected behaviour.

I hope my investigation helps.

Do you think it Is possible to fix this behaviour?

**Comment by tpope** [comment]
> * `file` variable calculated [here](https://github.com/tpope/vim-fugitive/blob/dd8107cabf5fe85df94d5eedcae52415e543f208/autoload/fugitive.vim#L6544) is `fugitive:\\C:\foo\bar\vimfiles\pack\plugins\start\vim-fugitive\.git\b411b753f805b969cca856e2ae51fdbab49880df\autoload\fugitive.vim`

What is the value of `arg` here? You've confirmed the output is wrong, so let's have a look at the input.

Also check `a:arg`, which is what is passed into the function.

**Comment by Melandel** [comment]
`a:arg` is `fugitive:\\\C:\foo\bar\vimfiles\pack\plugins\start\vim-fugitive\.git\\dd8107cabf5fe85df94d5eedcae52415e543f208\doc\fugitive.txt`


`arg` is  `fugitive:\\\C:\foo\bar\vimfiles\pack\plugins\start\vim-fugitive\.git\\dd8107cabf5fe85df94d5eedcae52415e543f208\doc\fugitive.txt`

**Comment by Melandel** [comment]
[this](https://github.com/tpope/vim-fugitive/blob/dd8107cabf5fe85df94d5eedcae52415e543f208/autoload/fugitive.vim#L2058) `file` is `fugitive:\\\C:\foo\bar\vimfiles\pack\plugins\start\vim-fugitive\.git\\dd8107cabf5fe85df94d5eedcae52415e543f208\doc\fugitive.txt`

It's [this](https://github.com/tpope/vim-fugitive/blob/dd8107cabf5fe85df94d5eedcae52415e543f208/autoload/fugitive.vim#L2062-L2064) `substitute` that removes the double backslash into `fugitive:\\C:\foo\bar\vimfiles\pack\plugins\start\vim-fugitive\.git\dd8107cabf5fe85df94d5eedcae52415e543f208\doc\fugitive.txt`
