### ISSUE TITLE
`FugitiveStatusline()` seems to return an empty string

### ISSUE THREAD

**Issue by carlescufi** [tpope/vim-fugitive#2072]
Here's part of my status line in `~/.vimrc`:

```
set statusline+=%=                           " right align remainder
set statusline+=%{getcwd()}\
set statusline+=%{FugitiveStatusline()}\    " git
set statusline+=%-10(%l,%c%V%)               " line, character
set statusline+=%<%P                         " file position
```

For some reason, the Git branch is not displayed at all. I must be doing something wrong but not sure how to debug this?
NOTES:

- I also tried with `fugitive#statusline()`, not sure which one is to be used
- I checked that `!git` works fine in normal mode, and that I am in a Git repo
- I also tried `:call FugitiveStatusline()`, no output
- Functions like `:Git` work just fine
- `set statusline=%<%f\ %h%m%r%{FugitiveStatusline()}%=%-14.(%l,%c%V%)\ %P` does not work either

Thanks!

**Comment by carlescufi** [comment]
Hold on. If I load a file it seems to work. Is it expected that this should only work when a file is open? I'd have thought that launching vim from a Git repo would be enough.

**Comment by tpope** [comment]
Correct, it shows you the repository the current file belongs to.

**Comment by carlescufi** [comment]
> Correct, it shows you the repository the current file belongs to.

Thanks. It'd be great to write that in the doc for future users. I can send a PR if you'd like.
