### ISSUE TITLE
ssh folder not being picked up by vim

### ISSUE THREAD

**Issue by david-engelmann** [tpope/vim-fugitive#2074]
I've setup ssh authentication for ubuntu. I'm able to run `ssh -T git@github.com -i ~/.ssh/id_ed25519` from the ubuntu terminal. I'm also able to run it within vim with `:! ssh -T git@github.com -i ~/.ssh/id_ed25519`. I'm able to `echo $SSH_AUTH_SOCK` in ubuntu and vim. However, when I go to push a commit to the remote branch, I'm still stuck in the username and password flow, see the screenshot below.

![image](https://user-images.githubusercontent.com/81196676/199586986-87c3f487-8d5d-459b-baf0-e84674e100f0.png)

![image](https://user-images.githubusercontent.com/81196676/199587239-310b2601-b405-42a3-bdb2-7a1ef0e167cb.png)

I start up and add the keys to ssh-agent in my .bashrc. I've run similar commands from vim with :! and it's not had any effect. I'm not sure what I'm doing wrong. I've included the .ssh folder in /root and in /home/user_name, even added it in to /etc/ssh. I'm not sure if any variables need to be updated in my vimrc to fix this functionality. Sorry for being a nuisance. Any help would be greatly appreciated!

**Comment by tpope** [comment]
Your remote is an `https` remote. That's why the username prompt has `https://` in it. You'll need to change it to a remote that looks like `git@github.com:user/repo.git` instead. `git remote set-url` can do this, or you can edit `.git/config` directly if you are careful.

**Comment by david-engelmann** [comment]
Updated my .git/config from 
```
...
[remote "origin"]
	url = https://github.com/david_engelmann/DoccanoClient.jl.git
...
```
to
```
...
[remote "origin"]
    url = git@github.com:david-engelmann/DoccanoClient.jl.git
...
```
After that update I was able to push to the remote branch without any prompts. Bless you sir!

**Comment by vande777** [comment]
Getting below error in Ration Application Developer while committing code to GIT. any help would be appreciated.

Can't connect to any URI: git@github.*.com:Temp/JavaRepo.git (git@github.*.com:Temp/JavaRepo.git: Auth fail
