### ISSUE TITLE
Add Patch throws error

### ISSUE THREAD

**Issue by Gurran** [tpope/vim-fugitive#2075]
Steps: 
1. `:G`
2. Move to a file that has changed
3. Type `P` to add patch

Result: Vim throws the following error

![image](https://user-images.githubusercontent.com/42462633/200336796-74b01f27-7244-4a9f-b42a-7cf4d60f5b3d.png)

**Comment by tpope** [comment]
Check `g:terminal_ansi_colors`, sounds like it's set wrong. This is a Vim built-in for controlling the colors in `:terminal`, not Fugitive specific.
