### ISSUE TITLE
`:Git diff` window seems to interfere with current window layout

### ISSUE THREAD

**Issue by carlescufi** [tpope/vim-fugitive#2078]
Sequence of steps to reproduce:

1. Open `vim` in a Git repo
2. Open a terminal with `:term`
3. Change focus to the default window/buffer (`C-w`-`w`)
4. Invoke `:Git diff`
5. Close the window that `:Git diff` opened
6. Back to the terminal
7. The terminal window is now higher than it was, and the lower part of the terminal is unusable

Note, in my `.vimrc` I have: 
```
set splitbelow
autocmd TerminalOpen * setlocal nobuflisted
set termwinsize=25x0
```

**Comment by tpope** [comment]
I get the same behavior if I change `:Git diff` to `:sp /etc/passwd`. This isn't Fugitive related.

**Comment by carlescufi** [comment]
> I get the same behavior if I change `:Git diff` to `:sp /etc/passwd`. This isn't Fugitive related.

Indeed you are right @tpope. Any clue as to how to investigate what is causing this issue?

**Comment by carlescufi** [comment]
Thanks @tpope, much appreciated.
