### ISSUE TITLE
Signed commit

### ISSUE THREAD

**Issue by Antse** [tpope/vim-fugitive#2082]
Hello, 

Thanks for this amazing plugin <3 .

I would like to know if there is a way of signed a commit from vim such as `git commit -S -m 'my message'` or is there an alternative way ? 

I didn't find this in the plugin help

I m not a git expert at all.

Thanks in advance,

**Comment by tpope** [comment]
`:Git commit -S` should work. But you'll need to use a GUI pinentry program, or see #1836.
