### ISSUE TITLE
`git log` can crash systems, if there's a lot of commit

### ISSUE THREAD

**Issue by Ashvith10** [tpope/vim-fugitive#2083]
I am working on a repository with around 310000 commits in a single branch. In such circumstances, Vim will freeze for a good few minutes (at least 5 minutes, in the worst case), possibly because all the texts are loaded in the buffer. This doesn't hurt the system while using `git log` directly from the terminal, as it loads instantly.

**Comment by tpope** [comment]
Unfortunately there's nothing that can be done about this. Vim always loads the entire file into memory. `git log` is using `less` which stops reading after the screen is full.

**Comment by Ashvith10** [comment]
@tpope I have a proposal - why not show `n` number of commits?

```sh
git rev-list HEAD --count
``` will give us the total count of logs, let's call this `total-count` here.

Let's set the pagination number to `n-count`
`range` will be 0 to (total-count - n-count)

```sh
git log --skip=range --max-count=n-count
```
Every time a user presses a mapped button (Space, for example), range increments and the buffer is updated, this would work as a scroll-up effect. Pressing Shift + Space decreases the range, and we get a scroll-up effect.

What do you say?

**Comment by tpope** [comment]
That does not sound to me like a compelling user interface. The advantage of of loading it into Vim is being able to use Vim commands in it, such as `/` for search, etc. Loading it in chunks would default the purpose.
