### ISSUE TITLE
Checkout with coo fails for branch names that start with 4 or more numbers

### ISSUE THREAD

**Issue by emilford** [tpope/vim-fugitive#2085]
Similar to the issue in #1756, using `coo` to open a branch under the cursor that starts with a number (e.g., `1111-feat`) fails with the error `fatal: invalid reference: 1111`. Looking at [this commit](https://github.com/tpope/vim-fugitive/commit/6ae064c5aa1cc24c78abc8d12ec236e99dc01316), we might consider adding a negative look-ahead.

I've minimally tested a change to `'\S\@<!\x\{4,\}\>\S\@!'`, but in the spirit of [don't be shy about asking before patching](https://github.com/tpope/vim-fugitive/blob/master/CONTRIBUTING.markdown), what do you think about this approach? I can test further. If it makes sense happy to open a PR (...or feel free to).

**Comment by tpope** [comment]
Drop the now redundant `\>` and that looks perfect.
