### ISSUE TITLE
How to open the git status window (:Git) on vim startup?

### ISSUE THREAD

**Issue by FabianUntermoser** [tpope/vim-fugitive#2094]
I want to display fugitive's status window when starting vim in a repository.
However in my case the status window is empty/blank.

I'm using this autocommand for testing.
```vimrc
autocmd VimEnter * :Git
```

I presume this is somehow because fugitive is lazy-loaded? However, adding this line in an `after` directory does not solve it.

Any help?

**Comment by tpope** [comment]
`:hep autocmd-nested`

**Comment by FabianUntermoser** [comment]
Thanks a lot. Now upon starting without arguments in a dirty repo, the status window is shown.

```
" show git status window on startup if repo is dirty
silent :!test -n "$(git status --porcelain)"
if !v:shell_error
    autocmd User StartifyReady ++nested :Git
endif
```
