### ISSUE TITLE
feat: configurable git lfs status in :G fugitive buffer

### ISSUE THREAD

**Issue by salkin-mada** [tpope/vim-fugitive#2095]
I wonder if it would be possible to configure _per repo_ to set the fugitive buffer `:G` with `git lfs status`? Meaning:
```
Staged (8)
A .gitattributes (Git)
A .htaccess (Git)
A images/00-najt.png (LFS)
A audio/sined-crop_generator.wav (LFS)
A README.adoc (Git)
A err.html (Git)
```

**Comment by tpope** [comment]
I wouldn't get my hopes up. I would be willing to consider if there was a way to do it with low to modest effort. I'm not seeing support for `git lfs status --porcelain=v2` which is a bad sign.
