### ISSUE TITLE
how to detect if some file is git-tracked?

### ISSUE THREAD

**Issue by pavoljuhas** [tpope/vim-fugitive#2096]
Assuming I edit an existing file in some git worktree, is there a fugitive API to check if that file is tracked by git?

I would like to set the `autoread` option for files that are tracked, but leave it off for untracked buffers.

The docs at `:help User_Fugitive` suggest to check `!empty(FugitiveGitDir())`,
but that returns 1 for both tracked and untracked files.

**Comment by tpope** [comment]
There's no special purpose command for this, but you can wrap any number of Git commands that can check with `FugitiveExecute()`. One possibility of many: `FugitiveExecute(['ls-files', '--', bufnr('')]).stdout !=# ['']`. (Fugitive will translate a buffer number into the appropriate relative path.)
