### ISSUE TITLE
Help/Feature: Fuzzy find git branch completions

### ISSUE THREAD

**Issue by rmzg** [tpope/vim-fugitive#2097]
I'm not sure this is something you want to add inside this plugin, but any suggestions as to how to achieve it by combining other plugins would be most appreciated.

Specifically when I do something like `:Gedit <tab>` I just get a giant list of git branches piped through `more`, I'd like to be able to search this list in some way (preferably fzf style) to find the specific branch I want.

**Comment by rmzg** [comment]
Note: I tried the `wilder` plugin but it can't fuzzy match against "user defined command completions".

**Comment by tpope** [comment]
A third-party plugin certainly _could_ do this. I am unaware of one that does.
