### ISSUE TITLE
g? doesn't show docs

### ISSUE THREAD

**Issue by mibzman** [tpope/vim-fugitive#2098]
When I press `g?`, I get the message `E149: Sorry, no help for fugitive-map`.

Is this a misconfiguration on my end?

**Comment by tpope** [comment]
You need to generate helptags, as seen in the installation instructions in the README.

**Comment by mibzman** [comment]
Thanks, I didn't know that!  On my last computer I installed via vim-plug without having to do that step, but on my new computer I guess it didn't work.

For anyone else in my situation:
I ended up finding my vim plugged files at `~/.config/nvim/autoload/plugged/vim-fugitive`. There I ran `nvim -u NONE -c "helptags doc" -c q` which worked!

Thanks again for the help, I love fugitive!
