### ISSUE TITLE
Does the 3-way diff deprecated ?

### ISSUE THREAD

**Issue by lainegates** [tpope/vim-fugitive#2108]
Recently, I use vim-figutive to merge/rebase git repository. 

I try to follow instruction of  http://vimcasts.org/episodes/fugitive-vim-resolving-merge-conflicts-with-vimdiff/
The video tells that a 3-way diff window will be display. But actually, only a 2-way diff window is displayed.

![image](https://user-images.githubusercontent.com/5265648/216228458-0d242cbd-ec2c-4965-916b-76696def7edf.png)

**Comment by tpope** [comment]
It's been moved from `:Gdiffsplit` to  `:Gdiffsplit!`.

**Comment by lainegates** [comment]
Great!

**Comment by lainegates** [comment]
What should I do if I want to keep "D-diverge2"?

Run `:diffget` on line 5 at right-bottom line?

![image](https://user-images.githubusercontent.com/5265648/216251520-feb28aca-2285-4652-8c49-352fb394a702.png)

 ( I tried `:diffget`/`:diffput` qt line 5, the whole diff message is kept)

The window is a bit different form the instruction that has no diff message like `<<< ... ===== .... >>>`.
http://vimcasts.org/episodes/fugitive-vim-working-with-the-git-index/
