### ISSUE TITLE
[question] How diff file content for "latest-commit / staged / unstaged"?

### ISSUE THREAD

**Issue by lainegates** [tpope/vim-fugitive#2109]
> `latest-commit` is the commit where we start our work
> `staged` means `indexing`
> `unstaged` means `working copy`

When working with VSCode, all file changes will be displayed in "Git" panel.

But with vim-figutive, only changes that are not staged can be read by `:Gdiff`.
For those changes already staged, `:Gdiff` will not display. 

Result is the same with `git diff` in terminal directly.

Is there a way to view diff for all changed that are not committed yet in vim-figutive ?

**Comment by tpope** [comment]
If you want to see both staged and unstaged changes, use `:Git` with no arguments.
