### ISSUE TITLE
Running :Gclog takes an age

### ISSUE THREAD

**Issue by grahamwoodward** [tpope/vim-fugitive#2112]
This might be related to our internal repo but it seems to take 5 mins at least before I'm able to cycle through all the commits that Gclog loads up. The split opens immediately and I see the first 10 or so but the vim window is unusable, I can't :q out...whilst this is happening vim is at 99% CPU

**Comment by grahamwoodward** [comment]
when it finally does finish, if I shift+G to get to the end of the split with the commits in, I've got over 35k in there, which probs explains the time it's taking

**Comment by tpope** [comment]
https://github.com/tpope/vim-fugitive/blob/2febbe1f00be04f16daa6464cb39214a8566ec4b/doc/fugitive.txt#L122-L125

**Comment by tpope** [comment]
> https://github.com/tpope/vim-fugitive/blob/2febbe1f00be04f16daa6464cb39214a8566ec4b/doc/fugitive.txt#L122-L125

**Comment by tpope** [comment]
> I can't :q out...whilst this is happening vim is at 99% CPU

CTRL-C works.
