### ISSUE TITLE
trigger log buffer update on FugitiveChanged

### ISSUE THREAD

**Issue by lafleurdeboum** [tpope/vim-fugitive#2117]
I've been using
``` vim
:Git log --all --decorate --oneline --graph
```
to open a log buffer while I work. I wrote some syntax definitions in `after/plugin/git.vim` to deal with it, and it works beautifully (for some years now !).

I've been looking for a way to let this buffer auto-update on fugitive actions _even when it's not focused_. I never had this to work.

## What I tried
``` vim
function! UpdateGraph() abort
    if &ft =~ 'git'
        if exists("b:gitgraph")
            set modifiable
            normal! ggdG
            :0!git log --all --decorate --oneline --graph
            set nomodifiable
        endif
    endif
endfunction

augroup GitGraph
    autocmd!
    autocmd User FugitiveChanged execute UpdateGraph()
    autocmd User FugitiveChanged echo "fugitive changed"
    autocmd ShellCmdPost <buffer> * execute UpdateGraph()
    autocmd ShellCmdPost <buffer> * echo "command posted"
augroup END
```
If I run a command like `:G checkout HEAD^`, I can see the buffer update and the "fugitive changed" message when I'm in the log buffer, but if I'm in another buffer and the log buffer is visible, it doesn't get updated.

## What I'm asking
The question is two-fold : 
  1. Is this behaviour normal ? I would expect autocmds to fire even when the buffer is not in the foreground.
  2. If it _is_ normal, then I suppose fugitive has a permanent update loop when it's running. Would it possible to trigger gitlog buffers' update when fugitive auto-updates ? Or at least an option to do so ?

**Comment by tpope** [comment]
> The question is two-fold :
> 
> 1. Is this behaviour normal ? I would expect autocmds to fire even when the buffer is not in the foreground.

Look at the code your wrote:

> ```viml
> function! UpdateGraph() abort
>     if &ft =~ 'git'
>         if exists("b:gitgraph")
> ```

These conditions will be true when the log buffer is focused and false when it's not. The autocommand is running and doing _exactly_ what you told it to do.

If you want it to work when the buffer isn't focused, you'll need to temporarily switch focus to the log buffer, then switch back afterwards.

> 2. If it _is_ normal, then I suppose fugitive has a permanent update loop when it's running.

If you call `:Git` during a `FugitiveChanged` event, it _should_ avoid recursive invocation. So something like this could potentially work:

```viml
Git ++curwin log --all --decorate --oneline --graph
```

Alternatively, you could avoid the high level `:Git` entirely, and instead capture the output with `FugitiveExecute(['log', ...])` and create/manage a buffer yourself. This approach is cleaner and gives you total control, but is probably a lot more work.

> Would it possible to trigger gitlog buffers' update when fugitive auto-updates ? Or at least an option to do so ?

Absolutely not.
