### ISSUE TITLE
Diff doesn't work for python files

### ISSUE THREAD

**Issue by sdeleon28** [tpope/vim-fugitive#2119]
Pressing `dd` in the status window or running `:Gdiff` from any buffer gets stuck and I have to `Ctrl-C` out of it te regain control of the buffer. Happens exclusively on python files.

I tried disabling almost everything else from my `.vimrc` (just enough to have nvim running with Fugitive). Still gets stuck.

`git diff script.py` works just fine on the CLI.

I'm running NVIM v0.7.2 on a Mac Studio (Apple Silicon processor), Mac OS Ventura 13.0.1.

Any ideas?

**Comment by tpope** [comment]
If I had to guess, I'd say you have a smudge filter that hangs when called from inside Neovim. Check if Neovim has a child process when it's hanging.

**Comment by sdeleon28** [comment]
That was a separate attempt. Disabling those plugins also exhibits the problem. I'll check for subprocesses when everything is disabled, but if there was no git subprocess running this time around, there's no reason for one to show up in the other test.

Still, I'll run the test and report back.

**Comment by sdeleon28** [comment]
Here's a minimal `init.vim` that can reproduce the behavior:

```
let &runtimepath.=',~/.vim'

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

" Version control
Plug 'tpope/vim-fugitive'
nnoremap <LEADER>gs :aboveleft :10Git<CR>
set diffopt=vertical

call plug#end()

if exists('+termguicolors')
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum]"
  let &t_8b = "\<Esc>[38;2;%lu;%lu;%lum]"
endif
```

My nvim version:

```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@Mac-1656256708179.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

Doing `pgrep -P <nvim-pid>` yields nothing (exit code 1).

To reproduce:

* Create repo with `script.py` file, commit
* Make some changes to `script.py`
* `nvim script.py`
* `:Git`
* `dd` on the file with outstanding changes

Expected result:

* Diff of `script.py` should be presented.

Actual result:

* Nvim hangs

**Comment by tpope** [comment]
I cannot reproduce. I tried Neovim 0.8.2 on macOS and 0.7.2 on Linux.

Python is a popular programming language and Fugitive is a popular Vim plugin. The odds that you've uncovered some previously overlooked bug are essentially nil. This is something peculiar to your setup. I would encourage you to try the following, in order:

* Truly isolate from everything in your home directory by doing `export HOME=/tmp/somedir` and putting your minimal vim config there.
* Check `env` for any non-essential environment variables and unset them.
* Try another version of Neovim.
* Try regular Vim.
* Try other versions of Git.
* Try on a different computer, if you have one.

Another thing you can keep an eye on is whether pressing Enter unblocks it (suggests it's waiting on input) or whether Neovim is heavily using the CPU (suggests an infinite loop).

**Comment by sdeleon28** [comment]
I can confirm high CPU for the nvim process, so we're probably in the infinite loop scenario. I will try the other steps above and report back.

**Comment by sdeleon28** [comment]
For future readers, truly isolating the environment as suggested did fix it. There was something in my `runtimepath` (probably in `autoload`) causing some sort of conflict. I had all of this stuff under `~/.vim` so running `mv ~/.vim ~/.vim-bkp` and re-installing all plugins fixed it.
