### ISSUE TITLE
When a file changes after :Git diff, then L for load, fugitive doesn't stop and C-c needs to be pressed to regain control of Vim

### ISSUE THREAD

**Issue by codebam** [tpope/vim-fugitive#2120]
When a file changes after :Git diff, then L for load, fugitive doesn't stop and C-c needs to be pressed to regain control of Vim

**Comment by tpope** [comment]
Check and see if Vim has a child process when it's hanging. I'm going to need a lot more detail if you require further help.

**Comment by codebam** [comment]
Tried to reproduce just now and couldn't. Not really sure how I was able to run `:Git diff` before Vim noticed the file change.
