### ISSUE TITLE
`Git commit` requires me to quit entirely to continue

### ISSUE THREAD

**Issue by xubury** [tpope/vim-fugitive#2121]
`Git commit` opens a split window for editing commit message. But when I `:wq` to close the window,  seems like `git` still thinks I am editing the message. I have to quit the entire program to complete the commit. Any ideas how to fix it?

**Comment by tpope** [comment]
* Is `git` still running in the background after you close the window?
* What does `:verbose set bufhidden?` output in the commit message window?
* Is the commit message buffer still loaded after `:wq`? Check `:echo bufnr()` before closing it and `:echo bufloaded(<that_number>)` afterwards.

**Comment by xubury** [comment]
1. yes git is still running
2. `verbose set bufhidden` output `wipe` in the commit message window
3. No,`:echo bufloaded(<that_number>)` output 0

**Comment by tpope** [comment]
You can try `:call fugitive#Resume()`. Whether or not that gets the commit to complete will offer a clue as to where the problem lies.

But regardless of the result, you also need to try with a stripped down Vim config, to rule out interference from other plugins.

**Comment by xubury** [comment]
Just solved it... I discovered I have an autocmd that set gitcommit buffer 's `buflisted` to `false`
