### ISSUE TITLE
`:Git blame` color can be improved

### ISSUE THREAD

**Issue by vitaly-zdanevich** [tpope/vim-fugitive#2122]
It looks like random colors:

![image](https://user-images.githubusercontent.com/3514015/222522339-5608fda4-5c9e-40e6-b7c5-18afd59c2f61.png)

But on GitHub I see more meaning:

![image](https://user-images.githubusercontent.com/3514015/222522406-4605e3e3-64ba-4b1f-a142-0fca44f0b972.png)

**Comment by tpope** [comment]
They are random colors. 😌 

See #901
