### ISSUE TITLE
History for a selected lines?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [tpope/vim-fugitive#2124]
Hi, I remember, many years ago, in IntelliJ IDEA it was possible to select a region and get a git history for this region - useful feature to have.

![image](https://user-images.githubusercontent.com/3514015/222756370-ccf0a492-8762-47cb-8863-c7da448537fc.png)

**Comment by tpope** [comment]
I don't know what that does exactly but the description sounds a lot like `:Gclog` with a range.
