### ISSUE TITLE
":G blame": scroll sync only on the left blame side, not on the main code side

### ISSUE THREAD

**Issue by vitaly-zdanevich** [tpope/vim-fugitive#2125]
https://user-images.githubusercontent.com/3514015/222922851-26ab5891-562a-4b85-83b5-de87ef30829a.mp4

**Comment by tpope** [comment]
It's not left vs right, it's whether the window you're scrolling is focused or not. And that's just how `'scrollbind'` works. It is arguably a Vim bug, if you want to try your luck reporting it there.
