### ISSUE TITLE
Recent changes have unexpected "unpushed to *" for bare repository

### ISSUE THREAD

**Issue by fans3210** [tpope/vim-fugitive#2129]
<img width="616" alt="Screenshot 2023-03-07 at 6 52 53 PM" src="https://user-images.githubusercontent.com/6023208/223425807-9babe344-ab81-42c8-a9a8-fc52e74eb1c4.png">
Thanks for this amazing library and I have been using it for years. 
I have been using git worktree with bare repo for a while, after recent update, I noticed that I have some unexpected "unpushed to *" when I'm using ":G" command although those changes were already pushed. I found that it's due to the recent two days' update.
<img width="657" alt="Screenshot 2023-03-07 at 8 44 10 PM" src="https://user-images.githubusercontent.com/6023208/223426125-ee34d1d5-f51f-4aea-ab0d-dfdb89278638.png">
What should I do if I don't want to display the commits already pushed for a bare repo? Would be appreciated if you could provide some tips. Thanks!

**Comment by tpope** [comment]
Please share all `remote` and `branch` sections from `.git/config`.

**Comment by worlddeleteRin** [comment]
Strange still the same issue, i'm on `9b72d0c` commit 🤔

**Comment by tpope** [comment]
Is your issue actually with the bare repo itself? Do you have `Bare: yes` in the status buffer like in the screenshot?

**Comment by tpope** [comment]
_Before_ these recent changes, what did the status window look like when there were unpushed commits? Was there any "Unpushed" section at all? And what were the headers at the top?

**Comment by worlddeleteRin** [comment]
Hm ok mb i'm wrong, it will show on root too 
- Here's is root path of bare repo with status (not inside worktree) (shot 1)
- Here's config, pretty standart (replace repo path with *)
- Here's confirm i'm on last fugitive commit (shot2)


```rust
[core]
	repositoryformatversion = 0
	filemode = true
	bare = true
[remote "origin"]
	url = git@github.com:*/*.git
[branch "master"]
	remote = origin
	merge = refs/heads/master
```
![image](https://user-images.githubusercontent.com/48155364/223565629-92dc0a0a-267e-4643-bb68-62496044cf3d.png)
![image](https://user-images.githubusercontent.com/48155364/223566003-9563fd17-3672-443a-83bd-4749be01309a.png)

**Comment by worlddeleteRin** [comment]
I've tried use plugin on this commit - `fa33145`
Bot root & worktree location status show just plain clear status
![image](https://user-images.githubusercontent.com/48155364/223567199-704edda7-82dd-489e-a44d-3945b4a54ecd.png)`

**Comment by worlddeleteRin** [comment]
> _Before_ these recent changes, what did the status window look like when there were unpushed commits? Was there any "Unpushed" section at all? And what were the headers at the top?

Srry related to this one - actually no .. when i have unpushed commits _before_ i don't see them in status at all 🤔 
So yeah the same on `fa33145` --> unpushed commits not in status
But with new stuff it will always show smth like unpushed even if it's pushed already

**Comment by tpope** [comment]
> Srry related to this one - actually no .. when i have unpushed commits _before_ i don't see them in status at all

This is the heart of the issue. The new commits show `Unpushed to *` as a fallback when `origin/master` doesn't exist. This is mainly intended for the case of a brand new repository. But apparently it's also true with your worktree+bare repo setup.

On a normal repository, if I want to take a look at what's upstream on `master`, I can do `git log origin/master`. When I clone a bare repository and add a work tree, I can't do that. Which raises the question: how _do_ I get access to that? When you want to see what commits are on `origin/master`, what do _you_ do? Is it even possible at all?

**Comment by worlddeleteRin** [comment]
- I definitely should find time & improve my git knowledge 😄  
-  Who uses bare-repo+worktree and face similar issue, that's because with basic config bare repo won't fetch & store remote branches. 
To make it workable u should modify your bare repo `config` file & add fetch rules:
```yml
[remote "origin"]
        // **
        fetch = +refs/heads/*:refs/remotes/origin/*
```
Then just do git fetch & remote branches will be stored locally, fugitive stuff will work as inteded
@tpope Appreciate your work on this project! Thanks for taking your time!
