### ISSUE TITLE
Ability to change the status line text

### ISSUE THREAD

**Issue by Stubbs** [tpope/vim-fugitive#213]
I'd like to be able to change the text that %{fugitive#statusline()} puts in my status line.

**Comment by holomorph** [comment]
This would be nice.

For instance, syntastic provides a configurable format string `syntastic_stl_format` to control the output of `SyntasticStatuslineFlag()`.

**Comment by tpope** [comment]
This might make sense if we had more than 2 things to show but as it stands I see this as low value.
