### ISSUE TITLE
`:G diff`: raw git diff output can be improved, by highlighing file names

### ISSUE THREAD

**Issue by vitaly-zdanevich** [tpope/vim-fugitive#2132]
Currently we have this:

![image](https://user-images.githubusercontent.com/3514015/224268400-1701b993-67c9-47ea-a848-06a5d6459ed3.png)

The same diff region with [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy):

![image](https://user-images.githubusercontent.com/3514015/224268641-b6cd745c-dd15-4489-b3ff-4825ec0b0e38.png)

I love that yellow file name delimiter:

![image](https://user-images.githubusercontent.com/3514015/224268844-c1aca98c-497d-4db3-a2cf-000b4481a591.png)

vs

![image](https://user-images.githubusercontent.com/3514015/224268928-4d7715db-34fb-4e1f-ad5d-f2f6ffc0002d.png)

Or maybe I can integrate **diff-so-fancy**?

**Comment by tpope** [comment]
Fugitive ignores `core.pager`, but it will use `pager.diff`.

**Comment by vitaly-zdanevich** [comment]
I tried this in git config:

```
[pager]
	diff = diff-so-fancy | less --tabs=4 --RAW-CONTROL-CHARS --quit-if-one-screen
```
But got the same raw diff, and without colors :(

**Comment by tpope** [comment]
I don't have `diff-so-fancy` installed, so I can't rule out issues on that end, but `pager.diff` definitely works to invoke a custom pager. Make sure you restart Vim, to avoid any config caching issues, and make sure you are calling `:Git diff` directly.

See also https://github.com/tpope/vim-fugitive/issues/1415#issuecomment-588037704.

**Comment by vitaly-zdanevich** [comment]
> Make sure you restart Vim

Still the same :(
