### ISSUE TITLE
Is it possible: double click -> dv (Gvdiffsplit) the file? 

### ISSUE THREAD

**Issue by kgfly** [tpope/vim-fugitive#2133]
Currently, after G -> double click the file. It opens the file.

Is it possible do some setting so: double click -> dv (Gvdiffsplit) the file? 

Thanks

**Comment by tpope** [comment]
No setting. It would probably be possible to map.

**Comment by kgfly** [comment]
Thanks, @tpope  How to map that? May you please suggest?

**Comment by kgfly** [comment]
Hi @tpope , may you please share how to do the mapping which only works in G status window?

Thank you very much.

**Comment by tpope** [comment]
Make it a `<buffer>` map, and use the `autocmd User FugitiveIndex` event.

**Comment by kgfly** [comment]
Hi @tpope, I have created a pull request. https://github.com/tpope/vim-fugitive/pull/2160. Do you think the reason is strong enough to justify?

**Comment by tpope** [comment]
No.

**Comment by kgfly** [comment]
Thanks, anyway.

"autocmd User FugitiveIndex nmap <buffer> <2-LeftMouse> dv" work for me.

**Comment by kgfly** [comment]
Hi @tpope , may I ask you one more question: do you know why 

"autocmd User FugitiveIndex nmap <2-LeftMouse> dv" only works on terminal vim, not gui vim (gvim)?

I tried on both Windows and Linux. Neither gvim works with the mapping.

Thanks
