### ISSUE TITLE
Unmerged commits not shown on local branch

### ISSUE THREAD

**Issue by jlangeveld** [tpope/vim-fugitive#2137]
After commit 82a9af1 the list of unpushed commits remains empty when using a local branch as the upstream for a branch.

How should I configure my branch to have that list restored?

**Comment by tpope** [comment]
Presumably you're missing something like this:

```gitconfig
[remote "origin"]
	fetch = +refs/heads/*:refs/remotes/origin/*
```

**Comment by jlangeveld** [comment]
Yes, it is - this is a repo without a remote.

I understand the confusion now - in this case it's not about **unpushed** commits, but about **unmerged** commits.
They showed up as **unpushed** in `:Git` when I setup the (local) `master`-branch as the upstream of the new branch.

Which breaks now, because I oftentimes don't have a remote.
Is there a way to restore (something like) the original behaviour?

If it helps, this is my `.git/config`:

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[task "hello"]
	base = master
[branch "task/hello"]
	remote = .
	merge = refs/heads/master
```
