### ISSUE TITLE
Feature request: please allow multi select. Then either discard/stash/stage.

### ISSUE THREAD

**Issue by kgfly** [tpope/vim-fugitive#2138]
One very useful feature of VS code (with gitlen plugin): I can do multi select.  Then either discard/stash/stage.

Eg, I select 1st/3rd file. Then right click. Now I can discard/stash/stage.

![image](https://user-images.githubusercontent.com/12282281/226760032-fe76fc88-5026-4945-b2f1-aeda1f7eaf23.png)

Is it possible to add this support to fugitive? Thank you very much.

**Comment by kgfly** [comment]
One more Q:

s -> Stage (add) the file or hunk under the cursor.
X -> Discard the change under the cursor

What's the shortcut cmd for stash? 

Thanks.

**Comment by tpope** [comment]
The shortcuts for stash include `czw` (`git stash push --keep-index`) and `czs` (`git stash push --staged`). You can stage the changes you want to keep or want to stash and then use one of those maps to do the stash itself. This is effectively a multi-select.

**Comment by kgfly** [comment]
Thanks. I tried czw. I think it's quite different from VScode gitlens.

Says I have 6 files. I want to stash 1/2, discard 3/4, stage 5/6.

When I czw, fugitive stashs all 6 files, is there a way to stash only first 2 files?

Thanks.

**Comment by tpope** [comment]
Stage the first 2 files and `czs`.
