### ISSUE TITLE
Pass additional arguments to `:Git`

### ISSUE THREAD

**Issue by miguel9554** [tpope/vim-fugitive#2140]
Is it possible to pass possible additional arguments available to `git status` to `:Git`? Haven't found anything about this in docs.

In particular I'm interested in passing ` --ignore-submodules=all`,  the command is slow and I believe it is because  `git status` is slow when many recursive submodules are present

**Comment by tpope** [comment]
You can't pass options, but Fugitive _will_ respect your Git config. I don't know the nitty-gritty of how the submodule options work, but `diff.ignoreSubmodules` and `submodule.<name>.ignore` look promising.
