### ISSUE TITLE
`:vert` not working with `:G diff`

### ISSUE THREAD

**Issue by miguel9554** [tpope/vim-fugitive#2141]
It's not configurable, but you can `:vert Git show`.

_Originally posted by @tpope in https://github.com/tpope/vim-fugitive/issues/1985#issuecomment-1114379757_

So trying this for `:G diff` is not working, still is splitted horizontal

Not sure if something wrong with my config/setup or a bug

**Comment by tpope** [comment]
Can confirm it works. It's something on your end.
