### ISSUE TITLE
how to add current buffer's git status info in the status line

### ISSUE THREAD

**Issue by huangyingw** [tpope/vim-fugitive#2143]
I already have the latest fugitive installed.
In my fugitive index, I have output like following:
```
Unstaged (13)
M .tigrc
M error
M install_basic_macos.sh
M jdupes
M neovim
M oh-my-zsh
M readme
```
how to add current buffer's git status info in the status line, like:
[M], [A], [D], [Unstaged], [Staged]

**Comment by tpope** [comment]
Not a supported feature.
