### ISSUE TITLE
Option to merge annotation of adjacent lines from same commit in :Git blame

### ISSUE THREAD

**Issue by nwotero** [tpope/vim-fugitive#2147]
When using Git Blame on Github, adjacent lines modified in the same commit share the same blame annotation. In fugitive's git blame, each line repeats the same annotation. Is it possible to implement the github strategy and expose it as an option to :Git blame?

Example:
![image](https://user-images.githubusercontent.com/5479871/229242895-c54781c2-1916-4168-b957-13b4549f5233.png)

**Comment by tpope** [comment]
I don't see an option for that in the `git-blame` man page.

**Comment by nwotero** [comment]
It isn't a git blame feature, its a UI feature provided by Github, shown by my provided example. Understand if its not something you want as part of the plugin.

**Comment by tpope** [comment]
Yeah I want to wrap `git blame`, not re-imagine it. I did the `:Gblame` -> `:Git blame` transition in part to make clear that at the heart of it we're calling `git` directly, so if you want to bikeshed something, you can take it up with Git, not Fugitive.
