### ISSUE TITLE
fugitive fatal: git process error.

### ISSUE THREAD

**Issue by stardiviner** [tpope/vim-fugitive#215]
I got this error when I use ":Gdiff" mode to put changes into git index file, then use `:w` to save index file.
Then I got bellowing error.

```
fugitive: fatal: Unable to create '/home/chris/Git/dotfiles/.weechat/.git/index.lock': File exists.^@^@If no other git process is currently running, this probably means a^@git process crashed
 in this repository earlier. Make sure no other git^@process is running and remove the file manually to continue.
```

I use `:Gwrite` is fine. and ... I think git is fine too. I can push, etc commands.

**Comment by hbarcelos** [comment]
Hi there.
I'm getting the same error consistently.

I tried removing `.git/index.lock` files, but there usually is none.

Interestingly `:Git add %` works just fine.
