### ISSUE TITLE
colors look to be missing in `log`

### ISSUE THREAD

**Issue by amtoine** [tpope/vim-fugitive#2150]
hello there :wave: :yum: 

i think there is a little issue with `:Git log` in that colors appear to be missing :open_mouth: 

to the left is inside `nvim` and to the right is inside `alacritty` :+1: 
![vim-fugitive-tr](https://user-images.githubusercontent.com/44101798/231537121-76e4fa1a-3a25-47bc-896f-0bbac196df96.png)

> **Note**
> i did run, either with `:G` in `vim` or `git` in my terminal, the following command
> ```shell
> log --graph --branches --remotes --tags --oneline --decorate --simplify-by-decoration
> ```
> this is to have a bunch of colored things :yum: 

to two outputs contain the same information, am i missing something in my config of `vim-fugitive`? :innocent: 

## additional information
- i have this snippet in my `lua/custom/plugins/fugitive.lua` in my [`lazy`-based `nvim` config](https://github.com/goatfiles/kickstart.nvim/blob/main/lua/custom/plugins/fugitive.lua#L1-L7)
```lua
return {
  "tpope/vim-fugitive",

  config = function ()
    vim.keymap.set("n", "<leader>gs", vim.cmd.Git)
  end
}
```
- i use `NVIM v0.8.3` and `alacritty 0.12.0 (5a728195)`

**Comment by tpope** [comment]
It's working as designed. The highlighting in Vim is syntax highlighting. The highlighting in the terminal is from ANSI escape sequences produced by Git when outputting to a terminal.

**Comment by qstrahl** [comment]
> i'm not sure where to look at to change these colors, if you have some pointers, that would be amazing 🤩

You'd likely have to customize the syntax highlighting yourself. Bit of an undertaking, but definitely doable. Check `set syntax?` to see which syntax is being used and give `:help syntax-highlighting` a read.

**Comment by amtoine** [comment]
> > i'm not sure where to look at to change these colors, if you have some pointers, that would be amazing star_struck
> 
> You'd likely have to customize the syntax highlighting yourself. Bit of an undertaking, but definitely doable. Check `set syntax?` to see which syntax is being used and give `:help syntax-highlighting` a read.
> 
> Edit: although if you are just looking to change the highlighting that is already there, you can likely just change the highlight groups; check out `:help :highlight` for that - would be much simpler.
>
thanks for the tips :star: 

i could not find where to change or add colors, but i can always dig into this a bit later :relieved:

**Comment by PhilippFeO** [comment]
> i could not find where to change or add colors, but i can always dig into this a bit later 😌

How deep have you already digged? I would embrace a nice colored `:Git log` output.
