### ISSUE TITLE
Cannot remap '<F1>' consistently

### ISSUE THREAD

**Issue by BrunoMSantos** [tpope/vim-fugitive#2151]
Hey, great plugin!

I'm having difficulty keeping my F1 binding working as intended though. In fact, I've been using the plugin for years now and I've only ever managed to override the key in the git status window with an ft plugin.

However, if I go into `Gllog`'s window (`ft=git`) for instance, an ft plugin override won't work, but if I hit `i` to collapse the diff, then it works. I don't think there's anything special about the `i` case, it's just the one I noticed and I use it as a workaround. If I issue the map command manually within the window, it works right away. My best guess is that somehow mappings can be made by the plugin after loading `after/ftplugin`, but in the `i` hitting case it reloads the plugin without reapplying the maps because we didn't move anywhere but still read the buffer again.

Worse still is that even after manually remapping the key, as soon as I navigate to another fugitive buffer it reapplies the help map, so any workaround might have to be really ugly.

This is reproducible for me with minimal configuration (fugitive + random F1 remap), but for the record, this is what I currently have in `after/ftplugin/git.vim`:
```vim
set nospell                               " Irrelevant, but works ok
nmap <buffer> <F1> :ToggleWhiteSpace<cr>  " It works after `i` toggling the diff
```

What am I doing wrong? And/or would you consider having a way of disabling it within the plugin if need be?

**Comment by tpope** [comment]
Fugitive provides an autocommand that triggers after loading a historical buffer that you can use:

```vim
autocmd Use FugitiveObject nmap <buffer> <F1> :ToggleWhiteSpace<cr>
```

I can and will reorder things a bit so that the ftplugin will work too. But autocommand order can be super fiddly, so it's hard to guarantee that won't need to change again in the future.

**Comment by BrunoMSantos** [comment]
Good to know there's a proper way around it.
