### ISSUE TITLE
Feature: Display commit stats in order see what files are in a commit

### ISSUE THREAD

**Issue by kawas44** [tpope/vim-fugitive#2154]
Hello,

When viewing a commit, it is hard to know which files are in the commit. It would be nice to use the `--stat` option to display a summary of what files are impacted by the commit.

Something like:
```
git show --stat --patch HEAD
```

cheers

**Comment by tpope** [comment]
You can get a similar effect with

```vim
autocmd User FugitiveCommit setlocal foldmethod=syntax foldlevel=0
```
