### ISSUE TITLE
Support custom commands in Git branch window? (open branch log)

### ISSUE THREAD

**Issue by idbrii** [tpope/vim-fugitive#2156]
`:Git branch` opens a list of branches with the `git` filetype. Is there a way to detect git branch buffers to add my own commands? Currently `<CR>` opens the branch's latest commit, but I'd like to open a log:

```
:Git log --no-merges branch-under-cursor ^current-branch
" or
:GV --no-merges branch-under-cursor ^current-branch
```

The `git` filetype and `FugitivePager` autocmd look close, but you can't tell what kind of data will be in that buffer. It doesn't look like User autocmds can pass arguments. Could the buffer have a `b:fugitive_cmd` variable for the name of the git command that created it (branch)?

----

So far I've got this in ~/.vim/after/ftplugin/git.vim

```
if !exists('g:loaded_fugitive')
    finish
endif

function! s:LogBranch()
    let br = expand("<cWORD>")
    if empty(br) || br !~ '\w'
        return
    endif
    
    let cmd = printf("GV --no-merges %s ^%s", br, FugitiveHead())
    return execute(cmd)
endfunction

nnoremap <buffer> <C-CR> <cmd>call <SID>LogBranch()<CR>
```

That works okay, but applies to git log and a lot of other buffers where maybe it doesn't make sense? Maybe I'll stick with that for awhile and see if over applying it is a problem.

**Comment by tpope** [comment]
Have a look at `FugitiveResult(bufnr('')).args`. Note that `FugitiveResult()` will return an empty dictionary if Fugitive didn't create the buffer, so make sure you guard against that.

**Comment by idbrii** [comment]
Thanks, that works great!
