### ISSUE TITLE
Window closes suddenly for some commands

### ISSUE THREAD

**Issue by prajwal-deepsource** [tpope/vim-fugitive#2157]
I've been having a very very weird issue with fugitive on Neovim. If I do `G push` or `G pull`, for example, the command works fine, but the window with the command output disappears instantly after the command completes. The command line bar prints the cwd after this happens. This has been happening with other commands too, and I can't reproduce it deterministically. Any idea what could be going on? My nvim config is available [here](https://github.com/snprajwal/dotfiles/tree/main/.config/nvim/init.vim), if that helps. Thanks!

**Comment by tpope** [comment]
Make sure you're on the latest version of Fugitive. It sounds like you're describing how the quickfix window used to behave, but that got ripped out a couple of years ago.
