### ISSUE TITLE
Bug: :Git buffer has no filetype

### ISSUE THREAD

**Issue by airtonix** [tpope/vim-fugitive#2167]
[Screencast from 2023-05-07 08-15-28.webm](https://user-images.githubusercontent.com/61225/236649303-c9345972-7f7f-4393-92c7-f4be8012dc29.webm)

You can see down the bottom left that the buffer created by `:Git` has no filetype.

So cant: 

- make autocommands for only this kind of buffer
- register my own highlights

**Comment by wookayin** [comment]
In my environments I have `filetype=fugitive` for the :Git buffer. What does `:set filetype` on that buffer give you?

**Comment by tpope** [comment]
Yeah that's correct, and if the filetype wasn't that you wouldn't get syntax highlighting. I'm guessing it's the statusline that is wrong.
