### ISSUE TITLE
a fugitive#commit() and a fugitive#url()?

### ISSUE THREAD

**Issue by gu-fan** [tpope/vim-fugitive#217]
I want the full commit  SHA.  

but when you are on the HEAD, no SHA is showing.

and a function may be better than using  `y<Ctrl-G>` 

and a fugitive#url() is needed , cause `Gbrowse!` is not very useful

and it's even better if there is a fugitive#commit_url() that showing current file's 
commit url.

 this is needed when documenting some commits.

**Comment by tpope** [comment]
You can capture the URL with `:redir` and `:Gbrowse!`. I'd entertain a function interface, but it's gotta be more generic than `commit_url`. I don't want `blob_url`, `tree_url`, `tag_url`, and a million other functions.
