### ISSUE TITLE
`:G help` buffer output is littered with `^H` characters in neovim

### ISSUE THREAD

**Issue by ajpaon** [tpope/vim-fugitive#2171]
I reproduced this with a minimal init.vim:

```
call plug#begin('~/.config/nvim/bundle')
Plug 'https://tpope.io/vim/fugitive.git'
call plug#end()
```

```
:G help reset
```

Result:
![Screenshot_20230522_174603_Termux](https://github.com/tpope/vim-fugitive/assets/5844547/a1848de6-300d-4ce6-8e03-1a7e243b4de7)

This is on neovim 0.10.0 on termux (android). I assume it is due to some weird interaction with neovim's built-in man plugin

**Comment by tpope** [comment]
I don't the Man plugin is to blame, we're only using it for syntax highlighting. I think `man` is outputting those characters thinking it is talking to a dumb terminal rather than a file. `x^Hx` and `_^Hx` are really old codes ways to write boldface and underline. (Imagine what would happen if you typed those on a typewriter.)

Try this:

```
:!git help reset > /tmp/output
:e /tmp/output
```

Do you get the same result?

**Comment by ajpaon** [comment]
Makes sense. Yeah, I see the same with that command.

**Comment by tpope** [comment]
Then this is an issue on your machine. I recommend trying with `man git-reset > /tmp/output` and see if you get the same result. If yes, then it's something wrong with how `man` is configured. If no, then it's probably something in your Git config.

**Comment by ajpaon** [comment]
Ok, it's possible, but here's what I've tried. I commented out everything in `.gitconfig` for these tests:

```
# in bash:
MANPAGER=cat man git-reset # no control characters in output
MANPAGER="nvim +Man!" man git-reset # no control characters, formatting & syntax highlighting works
MANPAGER=less man git-reset # no control characters, formatting visible

MANPAGER=cat git help reset # no control characters in output
MANPAGER="nvim +Man!" git help reset # no control characters, formatting & syntax highlighting works
MANPAGER=less git help reset # no control characters, formatting visible

# in nvim:
:Man git-reset " opens man buffer in nvim: no control characters, formatting & syntax highlighting works
:Git help reset " opens man buffer in nvim: control characters, no formatting or syntax highlighting
```

The last is the only interactive option where the output is wrong, which is why I think it's a bug somewhere in the overlap of fugitive and man.lua

**Comment by tpope** [comment]
> Ok, it's possible, but here's what I've tried. I commented out everything in `.gitconfig` for these tests:
> 
> ```
> # in bash:
> MANPAGER=cat man git-reset # no control characters in output
> ```

Oh they're almost certainly there, `man` is writing them, but the thing about a backspace is it erases, you can't see them in your terminal. Try `MANPAGER=xxd man git-reset`.
