### ISSUE TITLE
cc Freezes Screen

### ISSUE THREAD

**Issue by xeon826** [tpope/vim-fugitive#2173]
Looking at the overview page `:Git` after staging everything, I press `cc` to commit the changes and 1/4 of the time this will freeze the screen, I've tried pressing Ctrl + q and also `set autoread` in my init.vim but the problem persists. I'm using Neovim v0.10.0-dev, Packer, Ubuntu 22.04 jammy, git 2.34.1, and latest vim-fugitive commit. I have no custom configuration for fugitive in place, just the use statement `use "tpope/vim-fugitive"`. If there's anything further I can do to provide diagnostic data, please let me know.

**Comment by tpope** [comment]
Try Ctrl+C. If that doesn't work, check `:map <C-C>` and make sure it isn't mapped.

**Comment by xeon826** [comment]
I did Ctrl+C and it unfreezes the screen then brings up the buffer to write the commit message but after doing `:wq` it just goes back to the `:Git` screen and nothing has been committed. I tried `:map <C-C>` to see if anything else was using it but but there was no mapping found.

**Comment by xeon826** [comment]
I noticed there was another plugin using the cc key binding so I added `nnoremap cc :Git commit<CR>` in my init.vim which I'm hoping will overwrite it.

**Comment by tpope** [comment]
> Another thing I tried was running the commit command without the hotkey so `:Git commit` but it looks like the same thing happens.

Okay, that narrows it down, everything about maps is moot. My first guess would be you have a hook such as `pre-commit` or `prepare-commit-msg` that is blocking, so try disabling those and see if the problem persists.

**Comment by xeon826** [comment]
I noticed nvim was staying constantly at 100% cpu, it was something to do with how I was using nvim's native language server so I switched to coc, the high cpu usage is gone and I haven't noticed this issue happening since.
