### ISSUE TITLE
request: highlight current hunk in status buffer

### ISSUE THREAD

**Issue by mizlan** [tpope/vim-fugitive#2174]
Like the following:

![image](https://github.com/tpope/vim-fugitive/assets/44309097/a507c62b-c546-496d-9978-9fe1d380966b)

### Motivation:

Makes it easier to decipher what exactly will be staged/unstaged/acted on with a keypress like `s` when the cursor is within the diff, by delimiting the region visually more obviously.

**Comment by tpope** [comment]
It's standard diff highlighting. This is something a color scheme can/should do.

**Comment by mizlan** [comment]
I don't think the proper highlight groups are defined. For reference the highlight groups I detect are `['fugitiveUnstagedSection', 'fugitiveHunk']`, neither of which are specific to the *current* hunk. As another example, here is my cursor moving around hunks in Emacs' Magit. There is a clear difference between the highlighting of the current hunk and the other hunks in the same file:

https://github.com/tpope/vim-fugitive/assets/44309097/ebcfe29c-72fe-446e-8f8d-1de75978ab5d

**Comment by tpope** [comment]
I didn't catch that you wanted just the current hunk. That's something that could probably be achieved with `:match`, although we're talking about more than a one liner.
