### ISSUE TITLE
Git cherry-pick screen similar to rebase screen

### ISSUE THREAD

**Issue by tmzhuang** [tpope/vim-fugitive#2175]
Is there a good way to view ongoing cherry-picks similar to the rebase view in the Git pane. For example, this is what the Git pane shows during a rebase:
![image](https://github.com/tpope/vim-fugitive/assets/1159725/787cde36-b7b2-4f82-a50f-77b0823ac62d)

I often compare two branches with something like `g cherry -v sandbox master`:
```
- 20d61daacdcbf7ab6575ba188ce78452fc19e544 IN-51: Correct smoke-test-coverage-analysis workername.
- 126ebd84bced9acdffb9800e3a586ef2fce85b48 IN-51: Fix smoke-test-coverage-analysis using wrong bw_config.
+ d6b3376bbce7d6512a5d13d342d55099abac534b IN-51: Specify --gcov-tool for lcov commands.
+ 622cf50ab1d1c4f907a3a98de7e7c68def71a6e7 Tmp commit.
+ 4882894e4859aa84d1f5ae0394e8feff85e508f5 IN-51: Fix sbreport code coverage module.
+ 308bc31b06942570ae12c9874c70a6743cccf950 IN-51: Adds links to source in ccresult summary.
+ f4b95b842b6b441dd2cab058abce1983c739d5c6 IN-51: Updates infrastructure .gitignores.
+ 99e709b22cd64f98cdec48483602777ff90070e1 IN-51: Serves /srv/www/nfs.
+ 1e66e9484d480e6f75536216fa740576d70aba83 IN-51: Disable nightlies.
+ 76e4e11dd4798991c276d71a4392794ff6ba7b7b IN-51: Updates nfs paths.
+ ce2f2173702b9b7e4901963e8f819c2d35b70fda IN-51: Updates ImageModel.update_unique_image().
+ 6e98e1cb0c961d4ab68e536300c3b62ff2cef64e IN-51: Localize some screendumpy model operations.
+ 0e3a4032e2cfaa1f3871ff9ebb80fa86f5d7b747 IN-51: Fix up systemd service files.
+ 667e0cb2e31ec6222d562dfecae7e554eb8ee804 IN-51: Fix testmnt.sh nfs root path.
+ 5b6f50dadfe2b71dfd4aadd4c0d517a693d30527 IN-51: Fix up some references to /srv/testmnt.
+ 3d7b16abdc06d17ec05578b5262a39061e958d14 IN-51: Remove references to removed module.
+ ae3790a84b184744a6f4688d9cfb60d7d6d48e5f IN-51: Remove symlink step in sync_test_resources.
+ 75b42f9e537b4ce441b6bb0d2682a8c01bcb4280 IN-51: Fix runtime checkout_path for apps01.
+ eff963cff3567e4463bd0345742cdb15c04b6f03 IN-51: Fix automount nfs path in board prep.
+ 36c959f1844e1e1d551ab5bac7562bf8c5e0a1d1 IN-51: Misc fixes in screendumpy.
+ 5fb2f94c37f04e80c63f71612787cd13a77eee0a IN-51: Fix some windows nfs paths.
+ b436b2af160f7bfecefeb8f80fe31c63b194426f IN-51: Fix code coverage runtime path. Enable nightly.
+ 58d6e075ee739ac8c634c5d6475434cdee2a0fe2 IN-51: Fix macos test_nfs issue.
+ b5dcfbcb6b581e84de0282d9fc48e31146023333 IN-51: Fix win32 path substitution in options.
+ ea048944a6c286164f34f1257c7f63b03382b8ff IN-51: Fix sbtest run_tests --rcid param.
+ 3d7435eb18816774bf61a789b1501518800ad6b9 IN-51: Fix infotest.
- 5bda127ce58d29b96e0e1e9bdcea6c1c0b640137 IN-51: Disables board 71.
+ bf7c0e89c915c70a6df53bab356744d12e115ab8 IN-51: Adjust memory_warning logic on sbtest.
```

Then I'll cherry-pick a range of commits with `git cherry-pick d6b3376bbce7d6512a5d13d342d55099abac534b^..3d7435eb18816774bf61a789b1501518800ad6b9`.

I normally do this in a command line, but if it's possible to do with fugitive in vim, I'd like to do that as I already resolve conflicts using vimdiff. If conflicts arise, fugitive doesn't seem to show the state of the cherry-pick.

**Comment by 8164933729** [comment]
- 20d61daacdcbf7ab6575ba188ce78452fc19e544 IN-51: Correct smoke-test-coverage-analysis workername.
- 126ebd84bced9acdffb9800e3a586ef2fce85b48 IN-51: Fix smoke-test-coverage-analysis using wrong bw_config.
+ d6b3376bbce7d6512a5d13d342d55099abac534b IN-51: Specify --gcov-tool for lcov commands.
+ 622cf50ab1d1c4f907a3a98de7e7c68def71a6e7 Tmp commit.
+ 4882894e4859aa84d1f5ae0394e8feff85e508f5 IN-51: Fix sbreport code coverage module.
+ 308bc31b06942570ae12c9874c70a6743cccf950 IN-51: Adds links to source in ccresult summary.
+ f4b95b842b6b441dd2cab058abce1983c739d5c6 IN-51: Updates infrastructure .gitignores.
+ 99e709b22cd64f98cdec48483602777ff90070e1 IN-51: Serves /srv/www/nfs.
+ 1e66e9484d480e6f75536216fa740576d70aba83 IN-51: Disable nightlies.
+ 76e4e11dd4798991c276d71a4392794ff6ba7b7b IN-51: Updates nfs paths.
+ ce2f2173702b9b7e4901963e8f819c2d35b70fda IN-51: Updates ImageModel.update_unique_image().
+ 6e98e1cb0c961d4ab68e536300c3b62ff2cef64e IN-51: Localize some screendumpy model operations.
+ 0e3a4032e2cfaa1f3871ff9ebb80fa86f5d7b747 IN-51: Fix up systemd service files.
+ 667e0cb2e31ec6222d562dfecae7e554eb8ee804 IN-51: Fix testmnt.sh nfs root path.
+ 5b6f50dadfe2b71dfd4aadd4c0d517a693d30527 IN-51: Fix up some references to /srv/testmnt.
+ 3d7b16abdc06d17ec05578b5262a39061e958d14 IN-51: Remove references to removed module.
+ ae3790a84b184744a6f4688d9cfb60d7d6d48e5f IN-51: Remove symlink step in sync_test_resources.
+ 75b42f9e537b4ce441b6bb0d2682a8c01bcb4280 IN-51: Fix runtime checkout_path for apps01.
+ eff963cff3567e4463bd0345742cdb15c04b6f03 IN-51: Fix automount nfs path in board prep.
+ 36c959f1844e1e1d551ab5bac7562bf8c5e0a1d1 IN-51: Misc fixes in screendumpy.
+ 5fb2f94c37f04e80c63f71612787cd13a77eee0a IN-51: Fix some windows nfs paths.
+ b436b2af160f7bfecefeb8f80fe31c63b194426f IN-51: Fix code coverage runtime path. Enable nightly.
+ 58d6e075ee739ac8c634c5d6475434cdee2a0fe2 IN-51: Fix macos test_nfs issue.
+ b5dcfbcb6b581e84de0282d9fc48e31146023333 IN-51: Fix win32 path substitution in options.
+ ea048944a6c286164f34f1257c7f63b03382b8ff IN-51: Fix sbtest run_tests --rcid param.
+ 3d7435eb18816774bf61a789b1501518800ad6b9 IN-51: Fix infotest.
- 5bda127ce58d29b96e0e1e9bdcea6c1c0b640137 IN-51: Disables board 71.
+ bf7c0e89c915c70a6df53bab356744d12e115ab8 IN-51: Adjust memory_warning logic on sbtest.

**Comment by 8164933729** [comment]
#2177

**Comment by tpope** [comment]
Currently there's no support for this. As a first step, I would need to know how Fugitive can get the relevent state. For rebase, we look in `.git/rebase-merge` and `.git/rebase-apply`.

It would also be a helpful point of reference to know how Magit handles this.

**Comment by tmzhuang** [comment]
Seems that during a conflict during a cherry pick, the following files are created in .git: CHERRY_PICK_HEAD, AUTO_MERGE, MERGE_MSG:

`$ cat CHERRY_PICK_HEAD
d7168896af4987ec6b78a3b638c4dfee9d1332da
$ cat AUTO_MERGE
3a946d835c30000bcdd33dba9656b608197bd8ea
$ cat MERGE_MSG
Bleh.

# Conflicts:
#	a`

Not too sure what AUTO_MERGE hash is pointing to, but CHERRY_PICK_HEAD is the commit currently being cherry-picked and the MERGE_MSG gives the list of conflicts. I didn't see any other relevant files in the .git directory that might provide information, but I think these files should be enough to go on?
