### ISSUE TITLE
I want know waht is the colorgroup name which the column on the left of sign column.

### ISSUE THREAD

**Issue by SetsuikiHyoryu** [tpope/vim-fugitive#2176]
Refer to this image:

<img width="1024" alt="image" src="https://github.com/tpope/vim-fugitive/assets/57035251/f3fafaf2-09a6-4203-98ad-f6ac75be5cf9">

**Comment by tpope** [comment]
Whatever that is it isn't Fugitive. Fugitive doesn't provide signs.
