### ISSUE TITLE
Gvdiffsplit is not an editor command

### ISSUE THREAD

**Issue by Legomegger** [tpope/vim-fugitive#2180]
Hello, thanks for this awesome plugin. I used to solve my merge conflicts by `Gvdiffsplit!` command. Now when i open a conflicting file and try to `Gvdiffsplit!` on it, vim says me not an editor command. However I noticed this: If i run `Gdiffsplit` first, then after closing one window, and running `Gvdiffsplit!` it works as expected (opening 3 way vertical diff). Is it a bug or am I missing something?

```
macOS Ventura 13.1
lunarVim, neovim 0.8.8
```

**Comment by tpope** [comment]
I don't know any reason this would happen. Those two commands are defined [at the same time in the same way](https://github.com/tpope/vim-fugitive/blob/ef99f1d90cdb33a52931aed5868785b51fb9411d/plugin/fugitive.vim#L587-L589). Make sure you are running the latest version of Fugitive and if it's still happening report back with the exact error message you are receiving.

**Comment by sscherfke** [comment]
Just for the protocol: I ran into a similar problem and the reason was, that I loaded fugitive lazily (wiht Lazy.nvim) like this:
```lua
  { "tpope/vim-fugitive", event = "VeryLazy" },
```
Changed it to the following and it worked:
```lua
  { "tpope/vim-fugitive", event = "VeryLazy", cmd = { "Git", "Gwrite", "Gdiffsplit", "Gvdiffsplit" } },
```
