### ISSUE TITLE
Streaming of git commands

### ISSUE THREAD

**Issue by instantepiphany** [tpope/vim-fugitive#2183]
I'm here because on large repositories running `:Git log` is extremely slow. 

I've read all the related issues and can improve speed with various options like from/until, oneline, etc.

I understand that it is O^n becaues of how vim works, thanks to your explanation in another issue.

But I noticed that whatever command I use, it is much much faster when I run it in a `:term` instance, compared to via the fugitive plugin. 

I'm a longtime user of vim but don't know the internals. 

My suspicion is that when running `:Git log` the output is only shown once the entire command has finished. 
Whereas when running the same command in a `:term` instance, it streams the output via less as it would in a standalone shell. 

So unless you immediately skip to the end of the output, the term instance appears instant, because it doesn't take long to search the last ~10 commits that can fit on your display. Whereas vim is collectiong millions of lines of shell output in a (memory) buffer, and then putting that into a vim buffer and displaying it.

So my question is, is there a mechanism/api in vim that could allow the output of `:Git log` and similar commands to be streamed instead of waiting for the process?

I know I can just set an alias and limit it to ~500 commits or similar, but I would love the problem to be solved generally (and bring it into parity with how :term instances work).

**Edited:** to clarify I meant `Git log` and other commands that produce many lines by searching ancestors of a given commit, not `:Git` to simply open the status buffer.

**Comment by tpope** [comment]
Streaming is provided on `:Git!` to the preview window. If you try `:Git! log`, you'll see why it's not the default: `git log` spews output faster than we can process it and the UI blocks anyways. This is, to the best of my knowledge, a Vim limitation.

> I understand that it is O^n becaues of how vim works, thanks to your explanation in another issue.

To be clear, that's for the quickfix list, which `:Gclog` uses. `:Git log` shouldn't be _that_ disastrous.
