### ISSUE TITLE
`d2o` or `d3o` don’t work in `Gvdiffsplit` if `diffopt+=linematch:60` is set

### ISSUE THREAD

**Issue by fooness** [tpope/vim-fugitive#2186]
Hello.

I am rather new to vim-fugitive and `git mergetool`, so it took me quite some time to figure out why something expected as `d2o` or `d3o` simply does not work in `Gvdiffsplit` view, either initiated manually or via `git mergetool`, if the option `diffopt+=linematch:60` is set. I’m using neovim `v0.9.1`.

For me, `git mergetool` is configured as follows:

```
[merge]
  tool = vim-fugitive
[mergetool]
  keepBackup = false
  keepTemporaries = false
  prompt = false
[mergetool "vim-fugitive"]
  cmd = nvim -f -c \"Gvdiffsplit!\" \"$MERGED\"
```

Leaving `:help diffopt` here as a reference.

```
						*'dip'* *'diffopt'*
'diffopt' 'dip'		string	(default "internal,filler,closeoff")
			global
	Option settings for diff mode.  It can consist of the following items.
	All are optional.  Items must be separated by a comma.

                […]

		linematch:{n}   Enable a second stage diff on each generated
				hunk in order to align lines. When the total
				number of lines in a hunk exceeds {n}, the
				second stage diff will not be performed as
				very large hunks can cause noticeable lag. A
				recommended setting is "linematch:60", as this
				will enable alignment for a 2 buffer diff with
				hunks of up to 30 lines each, or a 3 buffer
				diff with hunks of up to 20 lines each.

```

Is this something that others can reproduce, and *should* the keymaps `d2o` and `d3o` work with that `diffopt+=linematch:60`?

Thank you!

**Comment by fooness** [comment]
Probably related: https://github.com/neovim/neovim/issues/22696

**Comment by fooness** [comment]
I could reset `diffopt` to its default value when running `git mergetool` …

```
				*:set-default* *:set-&* *:set-&vi* *:set-&vim*
:se[t] {option}&	Reset option to its default value.
:se[t] {option}&vi	Reset option to its Vi default value.
:se[t] {option}&vim	Reset option to its Vim default value.

```

… by changing the relevant line in my git config:

```
[mergetool "vim-fugitive"]
  cmd = nvim -c \"set diffopt&\" -c \"Gvdiffsplit!\" \"$MERGED\"
```

**Comment by tpope** [comment]
`d2o` and `d3o` are themselves maps that Fugitive provides. You should first confirm that they exist by checking `:nmap <buffer> d2o` and `:nmap <buffer> d3o`. If they're there, then make sure you are typing them fast enough. By default, the time out is 1 second, which is a bit tight for 3 keypresses.
