### ISSUE TITLE
My company's "pre-commit" hook produces output I need to review, can `:G commit` output get captured?

### ISSUE THREAD

**Issue by nebbish** [tpope/vim-fugitive#2187]
My company just installed some pre-commit hooks that, among other things, invokes Clang-Tidy in order to validate the "style" of our C++ code.

Here is an example of the output from git commit in a terminal:
```
C:\source>git commit
running clang-format...
running clang-tidy...
43 warnings and 27 errors generated.

   *   *   *

<file>:<ln>:<col>: error: invalid case style for function 'translator' [readability-identifier-naming,-warnings-as-errors]
        CPolicyTranslatorImpl* translator() { return &m_translator; }
                               ^~~~~~~~~~
                               Translator
```

I have reviewed the already existing "pre-commit" related issues -- some related to interaction, or running background, and still popping up the editor....    all of this highlighting that this is a "complicated" flow.

So, this is not about altering that flow in any way -- just about capturing a bit of it for later review.
Is that doable?

Maybe there already is a fugitive command to dump the last command's output into a new buffer.
I could not find it.   If that does not exist -- could that be a way to handle this request?

**Comment by tpope** [comment]
`:Gedit -`

https://github.com/tpope/vim-fugitive/blob/43f18ab9155c853a84ded560c6104e6300ad41da/doc/fugitive.txt#L626

**Comment by nebbish** [comment]
Thanks :D

**Comment by Skallwar** [comment]
Thanks for the answer, I had the same issue.
Is there a way to fill the quickfix list instead?

**Comment by tpope** [comment]
> Is there a way to fill the quickfix list instead?

You can do basically anything with the right autocommand. See https://github.com/tpope/vim-fugitive/discussions/2105#discussioncomment-4745681.
