### ISSUE TITLE
Wrong command `:G1` creates a file unexpectedly

### ISSUE THREAD

**Issue by KSR-Yasuda** [tpope/vim-fugitive#2188]
Running wrong command `:G1` (mistyping `:G!`, open in preview window),
it creates a file and makes the file staged.

For example,
bad command `:G1 -p log --graph --oneline --decorate` creates
a file named `1 -p log --graph --oneline --decorate`, as its command option.

It looks commands `:G[0-9].*` (`:G`, followed by digits) behave the same.

I sometimes mistype `:G!` as `:G1`, dropping shift-key.
I was wondering if this was handled as an error?

**Comment by tpope** [comment]
This appears to be a Vim bug. `:G1` is actually calling `:Gw1`. If I delete the `:Gw` command, it instead calls `:Gr1`, and if I delete `:Gr`, it instead calls `:Ge1`. I don't have time to investigate further. I recommend trying to create a minimal demonstration of the problem and reporting a bug against Vim.

**Comment by KSR-Yasuda** [comment]
Command completion to some of `:G*` commands?
So it looks there is less hope to be fixed.

Then I'll set `command! -nargs=?  G1  <mods> G! <args>` to avoid the bad completion.

Thank you!
