### ISSUE TITLE
`:Gclog` in cygwin vim causes fatal error

### ISSUE THREAD

**Issue by 3N4N** [tpope/vim-fugitive#2189]
```
fatal: Not a valid object name cc69cf356c65b9da1419cfbbf7a5b7fc28ff9b3f;path\file.txt
```
That's the error I get when I run `:0Gclog` on `path/file.txt`.  This happens only on my cygwin build of Vim (msys build, to be exact), not on the native win32 build.

**Comment by tpope** [comment]
How exactly does that error present itself? In the quickfix list? On the command line? When you open a result? Is it highlighted in red? Is there a stack trace or other additional context?

**Comment by 3N4N** [comment]
Sorry I didn't get back to this. It was a one-day effort to try and use Cygwin / MSYS Vim and I ditched it later. Should've at least answered your questions, though. Anyway, closing this since there is a lack of information.
