### ISSUE TITLE
'Git status' inconsistent with '!git status' when manually setting $GIT_WORKTREE and $GIT_DIR in some edge cases

### ISSUE THREAD

**Issue by benelan** [tpope/vim-fugitive#2191]
## Background

I have my dotfiles set up using a bare repo structured similarly to [this guide](https://www.atlassian.com/git/tutorials/dotfiles). I have the following [defined in my shell started scripts](https://github.com/benelan/dotfiles/blob/f1d7b15fb3ae790b1c6512f456fad1b5a9f163dc/.dotfiles/shell/aliases.sh#L262-L272):

```shell
edit_dotfiles() {
    "$EDITOR" "$@" \
        --cmd 'let $GIT_WORK_TREE = expand("~")' \
        --cmd 'let $GIT_DIR = expand("~/.git")'
}
alias G="edit_dotfiles +G +'wincmd o'"
```

## Actual behavior

This works great for the most part and I get the fugitive status for my dotfiles when executing `G`. However, when I run the command from within a different git repo I get the status for that repo instead. Interestingly, `!git status` correctly shows changes for the dotfiles.

## Expected behavior

I expect `Git status` to show changes for the same repo as `!git status` when manually defining the `GIT_WORK_TREE` and `GIT_DIR` environment variables, even if there is a closer git dir.

## Thoughts

I use the conventional `.git/` dir name instead of the `.cfg/` name used in the tutorial linked above, so that's not the issue.

The issue also occurs when executing `edit_dotfiles` in the shell and then `:G` within vim, so it's not startup timing issue.

I  tested using a git submodule and I'm experiencing the same behavior. If I'm within a submodule and open vim with the `GIT_WORK_TREE` and `GIT_DIR` env vars pointed to the parent repo, the fugitive status will still be opened for the submodule. However, if I execute `:!git status`, it will correctly be for the parent repo. 

It looks like the environment variables are considered [here](https://github.com/tpope/vim-fugitive/blob/43f18ab9155c853a84ded560c6104e6300ad41da/plugin/fugitive.vim#L445-L467), but I didn't want to spend too much time poking around since I assume there are a lot of edge cases and legacy knowlege that I'm unaware of. If you don't have the time to look into this and are willing to point me in the right direction, I'm happy to give it a shot. Thanks!

**Comment by ibhagwan** [comment]
@benelan, I also manage my dotfiles with a git repo, I was able to replicate all fugitive commands by overriding `b:git_dir`, discussed in #1981.

Below is my complete solution from [here](https://github.com/ibhagwan/nvim-lua/blob/main/lua/plugins/fugitive.lua)  (in lua, as I'm using neovim), this creates a set of "fugitive commands" starting with `Y`, so instead of `:Git commit` you use `:Yit commit`, etc - this also works when you're inside a sub-repo and even has auto-complete.

```lua
  local yadm_repo = "$HOME/.git"

  -- auto-complete for our custom fugitive Yadm command
  -- https://github.com/tpope/vim-fugitive/issues/1981#issuecomment-1113825991
  vim.cmd(([[
    function! YadmComplete(A, L, P) abort
      return fugitive#Complete(a:A, a:L, a:P, {'git_dir': expand("%s")})
    endfunction
  ]]):format(yadm_repo))

  vim.cmd((
    [[command! -bang -nargs=? -range=-1 -complete=customlist,YadmComplete Yadm exe fugitive#Command(<line1>, <count>, +"<range>", <bang>0, "<mods>", <q-args>, { 'git_dir': expand("%s") })]]
  ):format(yadm_repo))

  local function fugitive_command(nargs, cmd_name, cmd_fugitive, cmd_comp)
    vim.api.nvim_create_user_command(cmd_name,
      function(t)
        local bufnr = vim.api.nvim_get_current_buf()
        local buf_git_dir = vim.b.git_dir
        vim.b.git_dir = vim.fn.expand(yadm_repo)
        vim.cmd(cmd_fugitive .. " " .. t.args)
        -- after the fugitive window switch we must explicitly
        -- use the buffer num to restore the original 'git_dir'
        vim.b[bufnr].git_dir = buf_git_dir
      end,
      {
        nargs = nargs,
        complete = cmd_comp and string.format("customlist,%s", cmd_comp) or nil,
      }
    )
  end

  -- fugitive_command("?", "Yadm",        "Git",          "fugitive#Complete")
  fugitive_command("?", "Yit", "Git", "YadmComplete")
  fugitive_command("*", "Yread", "Gread", "fugitive#ReadComplete")
  fugitive_command("*", "Yedit", "Gedit", "fugitive#EditComplete")
  fugitive_command("*", "Ywrite", "Gwrite", "fugitive#EditComplete")
  fugitive_command("*", "Ydiffsplit", "Gdiffsplit", "fugitive#EditComplete")
  fugitive_command("*", "Yhdiffsplit", "Ghdiffsplit", "fugitive#EditComplete")
  fugitive_command("*", "Yvdiffsplit", "Gvdiffsplit", "fugitive#EditComplete")
  fugitive_command(1, "YMove", "GMove", "fugitive#CompleteObject")
  fugitive_command(1, "YRename", "GRename", "fugitive#RenameComplete")
  fugitive_command(0, "YRemove", "GRemove")
  fugitive_command(0, "YUnlink", "GUnlink")
  fugitive_command(0, "YDelete", "GDelete")
```

**Comment by benelan** [comment]
Thanks for the workaround! It works for dotfiles which is a single repo, but people who work in git submodules may need to create a lot of custom commands.

I also think most people would expect `Git status` and `!git status` to show changes for the same repo without having to create custom commands. But this will definitely help for now, appreciate it!

**Comment by ibhagwan** [comment]
> I also think most people would expect Git status and !git status to show changes for the same repo without having to create custom commands. But this will definitely help for now, appreciate it!

I actually like the separate command because I mentally switch context to the “overarching dots repository” whereas using `:Git` is only for the current working directory.

I get what you’re saying though, to each, their own :)

**Comment by benelan** [comment]
Yeah that's fair, but then you have to create different keymaps, functions, etc. for Git vs Yit and and my muscle memory wouldn't like that lol. 

The git submodule use case isn't something that impacts me since I only use them for managing dependencies. But I have seen people use git submodules for active development (bless their hearts) so I thought I'd mention it.

I have my own workaround so the issue is low priority for me, but I thought I'd bring up the inconsistency between `Git status` and `!git status`. After reading through the issue you linked, it seems like an actual fix could be complicated, so if tpope needs to close this one too I'd understand.

**Comment by tpope** [comment]
Not much to add here except to clarify that with Fugitive, the current file's repository is king. The current working directory and environment variables don't matter because Fugitive goes out of its way to make sure they don't matter.

**Comment by benelan** [comment]
Thanks for the response. Out of curiosity, what is the intended behavior when Fugitive's status buffer is the only one open? That's the edge case that resulted in this issue.

**Comment by tpope** [comment]
Fugitive's status buffer is just another "current file" (or more accurately "current buffer") with a URL buffer name that points at the particular repository it belongs to.
