### ISSUE TITLE
`dq` seems to leave the wrong buffer open after `:Gvdiffsplit!`

### ISSUE THREAD

**Issue by gwerbin** [tpope/vim-fugitive#2196]
After invoking `:Gvdiffsplit!` or `dv` in the Git buffer, everything works as expected. However, when I return to the same Git buffer and invoke `dq`, the `fugitive://...//2/...` buffer is left in the remaining window, not the original buffer of the file I was diffing.

I am using a somewhat-outdated Neovim dev release (`v0.10.0-dev-482+g38b0bb`) and Fugitive commit `43f18ab9155c853a84ded560c6104e6300ad41da`.

It seems to occur reliably in the repo I happen to be working on if I follow the following steps:

1. Start Neovim in the project's top-level directory (also the Git repo top level)
2. Invoke `:Git` to open the Git buffer in a new window. Switch to it and run `:25wincmd _` and `:setl winfixheight`.
3. Choose an unstaged file with merge conflicts (`UU` in `git status --short`), and invoke `dv`.
4. Fix conflicts. Run `:w` in the middle window, and and then `:Git add %` (or `s` in the Git buffer).
5. Switch back to the Git buffer window, and invoke `dq`.

Let me know if there's any other information I can provide to help reproduce the issue.

**Comment by swarn** [comment]
I ran into the same issue with both Vim 9.0 and Neovim 0.11.0-dev. It is dependent on the order you visited the windows (working tree, index) before moving to the fugitive status window and using `dq`.

I hope it's okay if I post my little workaround code here. My vimscript-fu is weak, so this is sadly neovim-specific:
```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = "fugitive",
  callback = function(args)
    vim.keymap.set("n", "dq", function()
      for _, win in ipairs(vim.api.nvim_tabpage_list_wins(0)) do
        local buf = vim.api.nvim_win_get_buf(win)
        local name = vim.api.nvim_buf_get_name(buf)
        local isDiff = vim.api.nvim_get_option_value("diff", { win = win })

        if vim.startswith(name, "fugitive:") and isDiff then
          vim.api.nvim_win_close(win, false)
        end
      end

      vim.cmd "diffoff!"
    end, { buffer = args.buf, silent = true })
  end,
})
```

**Comment by swarn** [comment]
Am I _really_ missing the point?

The docs after d0c1a43 say "Close all but the _currently focused_ diff buffer." Fair enough, but `dq` isn't mapped in the diff buffers, only the status buffer.

1. Use `:Git`
2. Use `dd` on a file.
3. In the status buffer, `map dq` -> `n  dq          &@:<C-U>call fugitive#DiffClose()<CR>`
4. In either diff buffer, `map dq` -> ` `
