### ISSUE TITLE
Make disabling deprecated an option

### ISSUE THREAD

**Issue by richsalz** [tpope/vim-fugitive#2197]
Since the github front page points to five videos, and they mention a bunch of new-deprecated commands, perhaps it makes sense to enable those old commands by default, and let them be turned off by a variable setting.

**Comment by tpope** [comment]
I did that for a while. The variable is called `g:fugitive_legacy_commands` and is still there, but it's now off by default. Those videos are 12 years old. I have decided not to let them hold Fugitive back for ever.

If you or someone wanted to catalog which videos use which deprecated commands, I could note them in the README.

**Comment by richsalz** [comment]
Thanks, that makes sense.  Congrats on the software.
