### ISSUE TITLE
:G doesn't work for a new saved file in git repo

### ISSUE THREAD

**Issue by mooreye** [tpope/vim-fugitive#2202]
If you open vim without any arguments (new empty file) from a git repo path, it doesn't show the git status in statusline (and `:G` gives an error that file is not in a git repo), even after you save it with `:w filename`. Only running `:e` after that or reopening the file fixes this.

My statusline:
`set statusline=%f\ %{FugitiveStatusline()}\ %h%w%m%r%=%-14.(%l,%c%V%)\ %P`

**Comment by mooreye** [comment]
Sorry, it appears that if you reopen file in vim, it shows git even if it's not tracked. However, the issue remains that it doesn't show git branch for:

- empty new opened file
- untracked saved file before you reopen it

This is my (apparently problematic) statusline:

`set statusline=%f\ %{FugitiveStatusline()}\ %h%w%m%r%=%-14.(%l,%c%V%)\ %P`

How to fix it?

**Comment by tpope** [comment]
> If you open vim without any arguments (new empty file) from a git repo path, it doesn't show the git status in statusline

This was a deliberate design choice.

>  (and `:G` gives an error that file is not in a git repo),

It shouldn't. What error does it give?

> even after you save it with `:w filename`. 

This should work too. Are you sure you're on the latest version of Fugitive?
