### ISSUE TITLE
Undocumented reblame at grandparent & parent

### ISSUE THREAD

**Issue by SevereOverfl0w** [tpope/vim-fugitive#2204]
https://github.com/tpope/vim-fugitive/blob/master/autoload/fugitive.vim#L7276 and https://github.com/tpope/vim-fugitive/blob/master/autoload/fugitive.vim#L7277C1-L7278C1 seem to have gone missing from `:help :Git_blame`.  `-` is still present in the docs.

**Comment by tpope** [comment]
Removed in https://github.com/tpope/vim-fugitive/commit/09908d82efc602fde72ef02ae05a75953376f842. See discussion in #2070.
