### ISSUE TITLE
In status buffer got "Merge" instead of "Push"

### ISSUE THREAD

**Issue by albasili** [tpope/vim-fugitive#2208]
Up until few days ago I was able to create a branch and switch to it through :Git checkout -b branch-name and in the status buffer I would see at the top the following:
```
Head: branch-name
Push: origin/branch-name
Help: g? 
```
I would stage and commit on the branch and it would show the Unpushed committees. Once complete I'd go and hit `-` on the Push: line and it would push the branch on the remote. 

All that is great, but in the past few days, in some repos, the top status buffer started to look like this:

```
Head: branch-name
Merge: origin/branch-name
Help: g? 
```

And if I hit the `-` key on the Merge line I get a failure because the branch is still not in `origin`.

I thought I heard a MERGE_HEAD with a merge in progress, but that's not the case and git status doesn't show anything worth sharing. 

What is going on here?
Any idea how to revert to the previous behavior? Any hint is appreciated.

**Comment by tpope** [comment]
See #2129, and more specifically f75dbb19672b590fe8e32334051314b47e91ae02. I think the answer here is to press `-` on the `Unpushed to origin/branch-name` heading rather than on the `Push:` header. I don't want to add a `Push` header here that duplicates the `Merge` header, and I don't want to make `-` on `Merge:` push, that's too confusing. If anything, I want to remove the behavior from `Push:`, because it's weird that it's not available all the time.

**Comment by albasili** [comment]
> See #2129, and more specifically [f75dbb1](https://github.com/tpope/vim-fugitive/commit/f75dbb19672b590fe8e32334051314b47e91ae02). I think the answer here is to press `-` on the `Unpushed to origin/branch-name` heading rather than on the `Push:` header. 

Interesting, I do not have any `Unpushed to origin/branch-name` but rather `Unpushed to * (1)` and I'm afraid I do not know what that means. I have gone through the issue you are referencing but here I do not have a Bare repo and I fail to understand how that applies to my case.

So pressing `-` on the `Unpushed` heading doesn't work until I get that *sensible* branch to push to and I'm not sure how to achieve that.

Let me know if I'm missing anything. Thanks a lot!
