### ISSUE TITLE
:Git init requires a restart

### ISSUE THREAD

**Issue by sidequestboy** [tpope/vim-fugitive#2213]
I open a file in an empty directory, run `:Git init`, the command works, but my gitsigns plugin and fugitive don't know it's a git repository yet. `:Git` complains: "fugitive: file does not belong to a Git repository". Restarting neovim makes everything ok again.

It might be more understandable that other plugins don't notice the new repo, but I would at least expect fugitive to.

Let me know if you need more details, I am on neovim 0.9.2, macOS 14.0

**Comment by tpope** [comment]
A restart is never required. Worst case scenario you can always reload the buffer with ` :e`.

I'll try changing it so `:Git` is a little more aggressive about re-detecting a repository.

**Comment by sidequestboy** [comment]
nice - that seemed to fix it thank you!
