### ISSUE TITLE
Wishlist Feature: Improved Autocomplete

### ISSUE THREAD

**Issue by amadeus** [tpope/vim-fugitive#222]
Would it be possible to improve the tab autocomplete when using :Git such that it uses the proper versions of origin/ vs origin when doing things like push/pull/merge/rebase etc?

Not sure if vim allows any special functionality into that or not so I don't know if this is even feasible.

Cheers

**Comment by LucHermitte** [comment]
Hi.

Can't we simply `substitute()` the slash into a space in `s:GitComplete()`  when the command line contains `\vGit\s*(push|pull)`?

**Comment by tpope** [comment]
`:Gpull` and `:Gpush` already have proper autocomplete.
