### ISSUE TITLE
Ggrep specific commit within specific folder fail.

### ISSUE THREAD

**Issue by qlibp** [tpope/vim-fugitive#2224]
command: `Glgrep -q pattern {commit}:{directory}`

- it successfully generate a quickfix list
- but the file path is wrong, which can't be open in vim

<img width="1156" alt="image" src="https://github.com/tpope/vim-fugitive/assets/43082379/7abf10ac-86f3-4895-8650-b99eb7711e39">

**Comment by tpope** [comment]
Look at the output from `git grep augroup 610a6a:lua/`. Fugitive's just doing what Git tells it to do.

Git's intended interface here is `git grep augroup 610a6a lua/`. That is, pass the commit and the path separately.

But I can probably salvage it.

**Comment by qlibp** [comment]
Thanks for the commit, the original git interface is good enough though
