### ISSUE TITLE
Remote file path is incorrectly encoded before being passed to `GBrowse` handler 

### ISSUE THREAD

**Issue by cedarbaum** [tpope/vim-fugitive#2230]
I maintain the  [fugitive-azure-devops.vim](https://github.com/cedarbaum/fugitive-azure-devops.vim) `GBrowse` plugin and I've been debugging an issue where the file paths produced from remotes with URL encodings (e.g., `git@ssh.dev.azure.com:v3/scedarbaum/Test%20project/Test%20project`) are being passed in to the handler with the `%` character encoded. This produces a final URL that is incorrect (e.g., `https://dev.azure.com/scedarbaum/Test%2520project/_git/Test%2520project?path=hello_world.txt&version=GBmaster`)

I think this can be avoided by skipping over already encoded URL segments, as you proposed in https://github.com/cedarbaum/fugitive-azure-devops.vim/issues/3 when making the change to have fugitive handle URL encodings (patch below). This does at least fix my bug, but not sure if there are any unintended consequences.

```diff
 function! s:UrlEncode(str) abort
-  return substitute(a:str, '[%#?&;+=\<> [:cntrl:]]', '\=printf("%%%02X", char2nr(submatch(0)))', 'g')
+  return substitute(a:str, '[#?&;+=\<> [:cntrl:]]\|%\%(\x\x\)\@!', '\=printf("%%%02X", char2nr(submatch(0)))', 'g')
 endfunction
```

**Comment by tpope** [comment]
The SSH short format—`user@host:port`—does not support percent escapes. So this is invalid:

`git@ssh.dev.azure.com:v3/scedarbaum/Test%20project/Test%20project`

You can fix it either by using a proper `ssh://` URL, or by avoiding the escaping entirely:

* `ssh://git@ssh.dev.azure.com/v3/scedarbaum/Test%20project/Test%20project`
* `git@ssh.dev.azure.com:v3/scedarbaum/Test project/Test project`

This raises a question of why that invalid URL works with Git itself. My guess is that this is a common mistake, so the Azure DevOps servers help you out by unescaping it for you.

**Comment by cedarbaum** [comment]
I appreciate the quick response and explanation! Unfortunately this is the format that Azure DevOps gives the user when cloning projects (see below), so while it may be technically incorrect, it will be a common issue for using `GBrowse` with the extension. There a few solutions I've been considering, but if you have any further thoughts I would greatly appreciate it:

1. Handle this in fugitive as proposed here, though sounds like this is a no-go (which I totally understand) and also wouldn't work with older versions of fugitive.
2. Instruct users to fix their remotes manually
3. Try to recognize this case and handle it within the extension (i.e. look for `%2F20` in URLs and replace with %20).

I am leaning towards 3 currently, as I think this will be relatively safe and also backwards compatible.

![CleanShot 2023-10-20 at 00 06 43@2x](https://github.com/tpope/vim-fugitive/assets/1669622/51f55e14-1652-4fb3-8cc3-3cfb543a7f28)

**Comment by tpope** [comment]
> 3\. Try to recognize this case and handle it within the extension (i.e. look for `%2520` in URLs and replace with `%20`).

Yes, this is what I would recommend. Since it's specific to Azure DevOps it makes sense for it to live in fugitive-azure-devops.vim. You could take it a step further and _fully_ URL decode any remote URL using the SSH short format.
