### ISSUE TITLE
Gdiffsplit Ignore whitespace in diff

### ISSUE THREAD

**Issue by azhow** [tpope/vim-fugitive#2243]
Hi, I have been recently using the plugin quite a lot for reviewing PRs and quite often I find myself wanting to use the ```-w``` argument (to ignore all whitespace changes).

I can do that for example when comparing my branch to another one using ```:G diff -w target_branch```, but not in a per file basis.

Is there any way to invoke the Gdiffsplit command with that argument?

**Comment by tpope** [comment]
No, this is a limitation of `:diffsplit`.
