### ISSUE TITLE
Gsplit: get other branch name

### ISSUE THREAD

**Issue by rkochar** [tpope/vim-fugitive#2247]
Open a file in a git repository in branch 1, `:Gsplit <branch 2>` opens a new tab with same file in branch 2. Bottom left corner branch name is branch 1 (should be branch 2).

```
let g:lightline = {
...
  \ 'component_function': {
  \   'gitbranch': 'FugitiveHead'
  \ },
```

Since branch 2 is not checked out, `FugitiveHead` returns branch 1. Is it possible to get branch 2? Thanks!

**Comment by tpope** [comment]
Here's what the relevant functions do:

* `FugitiveStatusline()` is a high level function that returns both the current branch and the commit of the file currently open, formatted for display in the status line.
* `FugitiveHead()` is a low level function for getting the current branch.
* `FugitiveParse()` is a low level function that returns the "Fugitive object" for a given Fugitive buffer, which includes the commit.

You could parse either `FugitiveStatusline()` or `FugitiveParse()` to get the commit. This is corresponds to "branch 2" (but it's a commit, not a branch name).
