### ISSUE TITLE
Diffing a renamed file among different commits

### ISSUE THREAD

**Issue by SureshGovindachar** [tpope/vim-fugitive#2248]
Issue: unable to figure out how to use vim-fugitive to diff renamed files among different commits:

    # in repo <hash> that contains old/path/to/file               
    # some edits and commits                                      
    # git mv old/path/to/file  current/path/to/file               
    # edit and commit current/path/to/file                        
    # following two commands work in the bash shell              
    # Issue: how would such a diff be done using vim-fugitive?
    git difftool <hash> -- old/path/to/file  current/path/to/file 
    git diff <hash> -- old/path/to/file  current/path/to/file

**Comment by kmARC** [comment]
Try specifying it via the `:` format:

```sh
git difftool <hash>:old/path/to/file current/path/to/file
```

**Comment by SureshGovindachar** [comment]
> Try specifying it via the `:` format:  `git difftool ...`

As mentioned in the original post, there are no problems with performing the diff using the git command line. The reason for this post is for support on how to perform the diff from inside Vim, e.g.:

  `vi current/path/to/file` 

Then inside vim:

 `:Gvdiff <need support for what needs to be written here>`

**Comment by SureshGovindachar** [comment]
It is OK to close this ticket.
