### ISSUE TITLE
Creating own `:Git` commands like `:Git pushom`

### ISSUE THREAD

**Issue by PhilippFeO** [tpope/vim-fugitive#2251]
My autocompletion suggestst `:Git pushom` when typing mentioned command. Sadly, `pushom` referes to a `master` branch
```
error: src refspec master does not match any [...]
```
but I use `main`, hence I can't use `:Git pushom`. (Maybe the warning exceeds my git skills and I am on the wrong path, I am just on page 150 in progit). Therefore two questions arise:
1. How can I alter `pushom` to align with non-`master` branches?
2. More general: How can I add my own `:Git` commands?

This may due to my inexperience with Vim plugins: I didn't find `pushom` in the help and searching your codebase via GitHub also yielded no matches.

**Comment by tpope** [comment]
Whatever `pushom` is, it's not a Fugitive feature. I imagine `git pushom` in your shell would behave the same way. It's either a Git alias or a `git-pushom` in your PATH.

**Comment by PhilippFeO** [comment]
By showing me the cause for the behavior is on my side[^1], you also answered my question. There were some relicts, I wasn't anymore aware of **and** now, I know how to define commands like `:Git pushom`. Thank you!

[^1]: Retrospectively obvious, since your help mentioned `pushom` not a single time.
