### ISSUE TITLE
Adding a FOSS license

### ISSUE THREAD

**Issue by ColinKennedy** [tpope/vim-fugitive#2256]
Hi, I love and use this plug-in every day. It's been my gold standard for git integrations in any text editor! My workplace is cautious about allowing code without a `LICENSE` file and it'd be a big help if this plug-in could use a FOSS license. I'm sure others in the same position and would appreciate it too. Could a FOSS license please be added if this plug-in is meant for public use?

**Comment by flexagoon** [comment]
The license of the project is mentioned in the readme.

> Copyright (c) Tim Pope. Distributed under the same terms as Vim itself. See :help license.

**Comment by ColinKennedy** [comment]
My bad, thank you for pointing this out!

**Comment by tpope** [comment]
> My workplace is cautious about allowing code without a `LICENSE` file and it'd be a big help if this plug-in could use a FOSS license.

I'd add that your employer probably cares a lot about the licenses of _dependencies_, but for the code you run locally on your machine, probably not so much.
