### ISSUE TITLE
I want gitfugitive to open the diff in vertical mode in a separate neovim tab.

### ISSUE THREAD

**Issue by shibisuriya** [tpope/vim-fugitive#2259]
I use fugitive in neovim, I make some changes to my git repo, and I use :G which opens a status window, I want window to open without any preview window below... When I press enter on a staged or unstaged file it should open the diff in vertical mode in a new neovim tab (not window or pane)... 

Thank you.

**Comment by shibisuriya** [comment]
Open the file or |fugitive-object| under the cursor in a new tab. -   *fugitive_O*
Can I open the file in a new tab with vertical splits directly?

**Comment by ikiet** [comment]
@shibisuriya 
Hey, did you figure this out? Can you share how you did it?
