### ISSUE TITLE
Question: search `:G status` similar to `fugitive-object`

### ISSUE THREAD

**Issue by fab4100** [tpope/vim-fugitive#2261]
If there are many changed files in the working tree, I would like to search for a particular pattern in `:G status` and then stage the hunk(s) that contain the pattern I am looking for.  Searching skips over files with collapsed inline diffs and I could not find a way to expand all inline diffs at once.  I believe it is something small I am missing but could not find the solution in the fugitive docs.  (Similar procedure with fugitive commit objects work as I intend.)

Thanks for the time!

**Comment by tpope** [comment]
You can expand all collapsed diffs in the `Unstaged` section by pressing `>` on the `Unstaged` heading.
