### ISSUE TITLE
Issue when reusing same branch name that no longer exists in remote

### ISSUE THREAD

**Issue by marlocov** [tpope/vim-fugitive#2265]
We create a branch each time we work on a bug and use the bug's ID in the branch `bugfix/XXXX`.  Once we resolved it, we PR it into main and squash the bugfix branch and I remove the branch locally too. 

Now the problem I'm having is that when the bug is reopened and I recreate `bugfix/XXXX` locally, but NeoVim some how still has some **unpushed/unpulled** from `origin/bugfix/XXXX` which actually no longer exists on `origin`. 

I tried to fetch the latest changes but vim-fugitive doesn't seem to "update" to the current state. 

Note that I when I use git in the cli it doesn't show me those **unpushed/unpulled** commits when doing a `git status`.

**Comment by tpope** [comment]
That's just how Git works.  Try `:Git remote prune` to clean up stale refs.

It's not an issue with `git status` because `git status` shows you less information.
