### ISSUE TITLE
The lead `!:` of the completion item is redundant when complete `!:` object.

### ISSUE THREAD

**Issue by gh-liu** [tpope/vim-fugitive#2268]
<img width="1420" alt="Screenshot 2024-03-03 at 14 21 15" src="https://github.com/tpope/vim-fugitive/assets/46311996/60d59526-36ef-4688-820f-f0e16e47f059">

**Comment by tpope** [comment]
I think this might be whatever plugin you're using that makes the completions pop up like that. When I type `:Ge !:<Tab>` I get `840ce4a9d9087cf9c321917dd6dd050ec6c9c49c:.gitignore` as I would expect.

Do try with/without that plugin and see what you can figure out.
