### ISSUE TITLE
Fugitive Borked when using NVIM_APPDIR

### ISSUE THREAD

**Issue by rwblokzijl** [tpope/vim-fugitive#2271]
When using [$NVIM_APPDIR](https://neovim.io/doc/user/starting.html#%24NVIM_APPNAME) to change the config (and installation) directory. Many fugitive commands don't work anymore and fugitive leaves all kinds of files in the working directory (`.sh`, `.exit`, and `.fugitiveblame`).

```:Git log``` leads to the following error:

![image](https://github.com/tpope/vim-fugitive/assets/446634/4f5aecd7-4d13-4345-beec-e9aca881b945)

And the following file shows up in the working dir: 
`.exit`:
```
fugitive: aborting edit due to use of pager.
```

Is there any workaround to change the directory fugitive works with? And are there plans to support `$NVIM_APPDIR` in the future?

**Comment by tpope** [comment]
Fugitive is just using `tempname()`. Check `:echo tempname()` and `:echo resolve(tempname())` and see what those return. My guess is a blank string. If `NVIM_APPDIR` is causing that somehow, then `NVIM_APPDIR` (or the way you are using it) is broken.

**Comment by rwblokzijl** [comment]
Ah looking for `tempname` makes it seem it's a neovim `NVIM_APPDIR` issue: https://github.com/neovim/neovim/issues/23056. Thanks for the answer.
