### ISSUE TITLE
winfixbuf leads to duplicate status window after interactive rebase

### ISSUE THREAD

**Issue by tom-anders** [tpope/vim-fugitive#2276]
Precondition: (n)vim supports `winfixbuf`

Reproduction steps:

- :G status (with unpushed changes)
- Put cursor over a commit and press `rw` (interactive rebase with reword)
- In rebase edit window, press :wq
- in commit message window, press :wq
-> You now have **two** status windows

**Comment by tpope** [comment]
Testing in Neovim, I can't reproduce. You could try reverting each of 8d4e8d45385c63a0bf735fe1164772116bf0da0d and 8d4e8d45385c63a0bf735fe1164772116bf0da0d to see which one is responsible. And make sure to try with other plugins disabled.

**Comment by tom-anders** [comment]
Okay I bisected by config and nailed it down to `Konfekt/FastFold`.

Not sure which plugin causes the actual issue, but I'm commenting here just for future reference if other people encounter this problem.

Here's a minimal init.lua that reproduces the issue:

```
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require'lazy'.setup {
    {'tpope/vim-fugitive'},
    {'Konfekt/FastFold'},
}
```
