### ISSUE TITLE
the cursor doesn't go back to the buffer that opened the status buffer when using "gq"

### ISSUE THREAD

**Issue by alarbada** [tpope/vim-fugitive#2280]
It's a bit annoying. Let's say I have these windows open in a tab:

| A | B | C |

and I open fugitive on window C.

when I close fugitive, the cursor will go to window A, and I have to manually go to C again.

In my case, usually A is NvimTree. I know I'm not really supposed to use this as a vim user, but that's besides the point.

Is this expected behaviour? I think I'm using a recent fugitive version.

**Comment by tpope** [comment]
All `gq` is doing is invoking `:bdelete`. If you have a better suggestion, do share. But I suspect your grievance isn't with Fugitive, it's with Vim (or Neovim).
