### ISSUE TITLE
E1513: Cannot switch buffer. 'winfixbuf' is enabled when refreshing

### ISSUE THREAD

**Issue by mosheavni** [tpope/vim-fugitive#2282]
Hi, I saw there were couple of other issues regarding `winfixbuf` but I really didn't understand where it hits other users,
for me, sometimes I want to reload the git window, for example when I delete a committed file from outside of vim, and I usually use `:e` but now it prompts me the dreaded error:
```
E1513: Cannot switch buffer. 'winfixbuf' is enabled
```
Is there any alternative to reloading the fugitive buffer?
Thanks.

**Comment by tpope** [comment]
That's https://github.com/vim/vim/issues/14237. Until it's fixed, you can use `:e!` instead.
