### ISSUE TITLE
Completion of the commit hash in cmdline?

### ISSUE THREAD

**Issue by name-snrl** [tpope/vim-fugitive#2284]
I was previously using git in cli, and the completion provided by fish helped a lot. For example, when I want to get a diff or an interactive rebase. What is the appropriate workflow for these cases in fugitive?

**Comment by tpope** [comment]
Git accepts abbreviated commit hashes. Completion seems redundant?

**Comment by name-snrl** [comment]
> Completion seems redundant?

The problem is remembering the right one. Essentially, `fish` completion is `git log --online`.
