### ISSUE TITLE
Request: Move to first file in GStatus

### ISSUE THREAD

**Issue by idbrii** [tpope/vim-fugitive#229]
GStatus always starts on the first line, but there's nothing useful to do there. Is there any reason not to start on the first file?

**Comment by MRAAGH** [comment]
To anyone who wants this, I suggest mapping
`nmap <Leader>gi :Gstatus<CR>gg<C-n>`
or equivalent. Same as suggested above, but with an additional `gg`.

**Comment by tpope** [comment]
`<C-N>` still works, but `)` is now the preferred "jump to first file" map.
