### ISSUE TITLE
issue still there

### ISSUE THREAD

**Issue by MRDEADRIM** [tpope/vim-fugitive#2290]
vim place a cursor on a link > type gf command > new open file | now type Git or any fugitive command  showing this issue fugitive: file does not belong to a Git repository.

tried echo FugitiveExtractGitDir(expand('%:p')) this command where issue there showing returning null.

vim version : VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Apr 01 2024 14:35:29)
os : arch linux

**Comment by tpope** [comment]
A link as in an HTTP/HTTPS link? You're leaving the repository, it sounds like the correct behavior to me.

**Comment by MRDEADRIM** [comment]
It is not https http link .it file link.

**Comment by MRDEADRIM** [comment]
It seems there's a symlink issue in my configuration.Thanks for your response. Tim Pope Have a good day!
