### ISSUE TITLE
:Gedit and similar commands spawn non-persistent buffers

### ISSUE THREAD

**Issue by hood** [tpope/vim-fugitive#2296]
Every time I try to open a past revision of a file, with something like:
```sh
:Gedit HEAD~4:%
```

A new buffer is open with -following this example- the current file at the indicated revision as expected, but as soon as I navigate away from that buffer, it vanishes. The only way for me to get back to it is by navigating to it using the jumplist, but it’s not persisted as the content of a buffer.

https://github.com/tpope/vim-fugitive/assets/56588510/6dcea009-00bf-4bf4-8651-c87e774a3026

As the video shows, I’m opening a previous revision of the file I’m currently working on, then moving to the tab to the left, making the newly opened buffer disappear.

**Comment by tpope** [comment]
The reason it defaults to `bufhidden=delete` is that multiple people complained about the default behavior. Sounded like a personal problem to me, but ultimately, I gave the people what they wanted.
