### ISSUE TITLE
Add `:GBrowse` handler for `git@example.com:username:repo.git` (as for SSH)

### ISSUE THREAD

**Issue by vollowx** [tpope/vim-fugitive#2309]

**Comment by tpope** [comment]
I don't understand what is being requested.

**Comment by OJFord** [comment]
They probably had an error similar to the one that brought me here:
> fugitive: no GBrowse handler installed for 'git@github.com:Org-Name/repo'

But, I just didn't have vim-rhubarb. (Did it used to be built-in here? I'm sure I've used G[bB]rowse with GH before..)

**Comment by tpope** [comment]
> But, I just didn't have vim-rhubarb. (Did it used to be built-in here? I'm sure I've used G[bB]rowse with GH before..)

A long time ago, yes. Built-in support for GitHub was deprecated in 2015 and removed in 2017.
