### ISSUE TITLE
Feature request: Rebase to the commit the current line was edited in

### ISSUE THREAD

**Issue by jclsn** [tpope/vim-fugitive#2311]
I often find myself in the situation where I need to exchange a value in a line that was changed in a previous commit. I then have to look at the blame, copy the commit hash, ``git rebase -i $hash`` and change. Since fugitive already comes with blame support, I think it would be neat if you could rebase directly to this commit. Do you think this is possible?

**Comment by tpope** [comment]
First make your change and stage it (e.g., with `:Gwrite`). Then switch back to the blame window and press `cF` on that line to create a fixup commit and rebase it in automatically.

**Comment by jclsn** [comment]
I kind of suspected you already had a way to do this! :D Thanks
