### ISSUE TITLE
toggling `Press ENTER or type command...` prompt?

### ISSUE THREAD

**Issue by kristoferfannar** [tpope/vim-fugitive#2316]
Hey, thanks for you work. Fugitive is great and very useful!

There is however one thing that I'd like to ask about:
Whenever I commit `:Git commit` or push `:Git push` or the like, I not only receive the output, but also the prompt to continue, like below.

![image](https://github.com/tpope/vim-fugitive/assets/68929760/3268597a-0e36-4498-822d-45a4cfe510aa)

ps, I have cmdheight = 1, which causes this.

I see in your readme that you've specifically made `:Git add` quiet in this sense, which works for me (no prompt, unlike with `:!git add .`), but committing and pushing still display this prompt.

I imagine including it for commit/push is deliberate, but I doubt I've ever found the prompt very useful. I wonder therefore whether there are options to toggle this prompt for commands other than `:Git add`, such as those I've mentioned.

Thanks a lot!

**Comment by kristoferfannar** [comment]
For now, I've looked at #190 and see that prepending with `:silent !` in front of my commands does silently remove the message. That will do for me, but I'd like to still see some message without the prompt. 
Maybe that's a vim issue rather than a fugitive issue, but I'll leave this here.

**Comment by tpope** [comment]
> I see in your readme that you've specifically made `:Git add` quiet in this sense, which works for me (no prompt, unlike with `:!git add .`)

This is not a special case for `:Git add`. `:Git add --verbose .` can produce a "Press ENTER" prompt and `:Git commit --quiet .` won't. The README is only calling out that you don't get "Press ENTER" prompts except when they're necessary.

> prepending with `:silent !` in front of my commands does silently remove the message.

This silences _everything_, including important messages like "no changes added to commit" and even exceptions thrown by Fugitive. You probably want `--quiet` (or `-q`).

> For example, only displaying the last cmdheight lines?

This would be actively harmful most of the time.
