### ISSUE TITLE
Windows 11: `g?` does not show help

### ISSUE THREAD

**Issue by zstadler** [tpope/vim-fugitive#2320]
I'm running vim 9.1 on Windows 11.  `vim-fugitive` works perfectly well, except for the `g?` in the `:Git` window which gives an error:
```
E149: Sorry, no help for fugitive-map
```

I've followed the README instructions, after adapting them for Windows:

```
mkdir %USERPROFILE%\.vim\pack\tpope\start
cd %USERPROFILE%\.vim\pack\tpope\start
git clone https://tpope.io/vim/fugitive.git
vim -u NONE -c "helptags fugitive\doc" -c q
```

It seems that `helptags` worked well as `dir fugitive\doc` shows a `tags` file.

What am I missing!?

**Comment by tpope** [comment]
On Windows, the default user directory is `%USERPROFILE%\vimfiles`, not `%USERPROFILE%\.vim`. So I wouldn't expect this installation to load at all.

Is it possible you have a second installation somewhere?

**Comment by zstadler** [comment]
Thanks!

I didn't know that, and indeed there was also another `vim-fugitive` installation at `%USERPROFILE%\vimfiles\pack\tpope\start`. I assume it was installed there a long time ago.

Would you mind adding the following to the [Installation](https://github.com/tpope/vim-fugitive/blob/master/README.markdown#installation) instructions:

> Using command shell on Windows
> ```
> mkdir %USERPROFILE%\vimfiles\pack\tpope\start
> cd %USERPROFILE%\vimfiles\pack\tpope\start
> git clone https://tpope.io/vim/fugitive.git
> vim -u NONE -c "helptags fugitive\doc" -c q
> ```
