### ISSUE TITLE
Cannot read or write temp files on diff command

### ISSUE THREAD

**Issue by keitee** [tpope/vim-fugitive#2321]
Hi all,

When running "Git difftool -y" under neovim and lazy, gets following error:

nvim --version

NVIM v0.10.0
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info

fugitive

* 8c8cdf4 : (HEAD -> master, origin/master, origin/HEAD) Use callback based workflow for status buffer (Fri Jul 5 12:04:03 2024 -0400) <Tim Pope>

Error detected while processing function fugitive#Diffsplit[140]..function fugitive#Diffsplit:
line  122:
E121: Undefined variable: diff
E810: Cannot read or write temp files
E97: Cannot create diffs
Press ENTER or type command to continue

Since fugitive works well on Vim on the same machine, permission of tmp seems to be fine. Any suggestions to try out would be appreciated. 

Many thanks

**Comment by tpope** [comment]
Looks to me like `:diffsplit` is broken. You can confirm with `:diffsplit /dev/null`. If it causes an error, that's the real problem, not Fugitive.

**Comment by keitee** [comment]
That's right and diffsplit still causes an error. Thanks for the pointer and need to figure out though. :-)
