### ISSUE TITLE
In `:Git blame`, use color as a proxy for commit age

### ISSUE THREAD

**Issue by jez** [tpope/vim-fugitive#2324]
In GitHub's blame view, there's a little legend showing that older commits are accented with a light yellow color, and the lightness/brightness of the shade of yellow drops all the way to pitch black for very young commits. See it in action here:

https://github.com/tpope/vim-fugitive/blame/0444df68cd1cdabc7453d6bd84099458327e5513/autoload/fugitive.vim

<img width="436" alt="Screenshot 2024-07-31 at 2 38 39 PM" src="https://github.com/user-attachments/assets/65da0d90-65de-4789-8ebf-48cd3b61a9a2">

It would be super cool if vim-fugitive could do the same. Happy to work on this, but I didn't want to start working on it if the feature had been considered and explicitly been rejected for consideration. I searched the issue list and didn't see anything specifically mentioning this but it's possible I just didn't search thoroughly enough.

**Comment by tpope** [comment]
I not just considered but implemented it, but I never merged it because I wasn't happy with how it looked. See https://github.com/tpope/vim-fugitive/issues/901#issuecomment-509017914.
