### ISSUE TITLE
Implement counterpart for ``-`` mapping in ``:Git log``

### ISSUE THREAD

**Issue by jclsn** [tpope/vim-fugitive#2328]
I have found that you can navigate down the commit history by pressing ``-``. This mapping is undocumented in seems and there also is not counterpart ``+``. Would it be possible to create one? 

I have looked at the ``NavigateUp`` and ``DirRev`` functions, but it is not obvious to me how to achieve that.

**Comment by tpope** [comment]
No, that's not how Git works. Commits know about their parents but not their children. You can find children by hunting through the history of a branch, but which branch to hunt through is subjective. For example, the children that exist on `main` and the children that exist on `dev` might be different.

**Comment by jclsn** [comment]
I see. Would just have a nice way to jump back and forward through my merge request without having to open the browser. Works with ``:Gclog`` and the quickfix list, but for the kernel this is not usable.

**Comment by jclsn** [comment]
Ah `:Gclog -n 100` works like a charm

**Comment by jclsn** [comment]
How does that work? I don't understand what is meant by "currently edited commit". For me it just shows nothing

**Comment by tpope** [comment]
Where are you using the `-` map?

**Comment by jclsn** [comment]
I have my ``command Glog :Git log --oneline --decorate --graph -500`` command and I am using it in there

**Comment by jclsn** [comment]
In the buffer of the diff, but no matter in which buffer I execute ``:Gclog ^!``, it just returns me an empty buffer

**Comment by tpope** [comment]
> In the buffer of the diff, 

The first buffer that opens is the top most commit. It has no children. So it will not list anything.

> but no matter in which buffer I execute `:Gclog ^!` in, it just returns me an empty buffer

Are you just trying it in random files? Those don't have child commits either.

**Comment by jclsn** [comment]
> The first buffer that opens is the top most commit. It has no children. So it will not list anything.
I did not try in the first commit, but in one further down.
> Are you just trying it in random files? Those don't have child commits either.
I have been trying in many commits and files now. The list is alway empty

**Comment by tpope** [comment]
I guess it needs a starting point too. Try `:Gclog @ ^!` to use the currently checked out branch.

**Comment by jclsn** [comment]
Yep, that works! Thx
