### ISSUE TITLE
Can we enable keepalt for the diff from Git status window?

### ISSUE THREAD

**Issue by brookhong** [tpope/vim-fugitive#2336]
We can use `keepalt Gvdiffsplit` to prevent fugitive temp file to be a alternate file, but when using `dv` from Git status window, the fugitive temp file still appears to be a alternate file, which make `C-^` not work as we want.

Is it possible to use `keepalt` [here](https://github.com/tpope/vim-fugitive/blob/1d18c696c4284e9ce9467a5c04d3adf8af43f994/autoload/fugitive.vim#L2713)?

**Comment by tpope** [comment]
Yeah I don't see why not.
