### ISSUE TITLE
Error when switching to eclim ProjectTree

### ISSUE THREAD

**Issue by rnestler** [tpope/vim-fugitive#234]
I use the [eclim http://eclim.org/index.html] plugin. When I switch to the ProjectTree split window (with ^-w,^-w) fugitive throws the following error:

```
Error detected while processing function <SNR>26_Detect..fugitive#buffer..<SNR>26_buffer..<SNR>26_throw:
line    2:
E605: Exception not caught: fugitive: not a git repository: workspace/project/ProjectTree_1
```

The project directory is actually a git repository, but the ProjectTree_1 file/folder doesn't really exist

**Comment by tpope** [comment]
I still don't have an Eclim setup to test, but Fugitive generally handles these sorts of cases much better now.
