### ISSUE TITLE
Performance issue: this plugin is almost not useable with large project.

### ISSUE THREAD

**Issue by flyingosprey** [tpope/vim-fugitive#2347]
On large project which has 10k commits or more, "G log"/"Gclog"/"Gllog" is very slow, which is not usable. (too slow to use)

I think the reason is because above cmd try to pull all commit info in 1 time. On larget project, this 1 time action take very log time.

So can "G log"/"Gclog"/"Gllog" support pagenation? or support "load more"?

pagenation: this is how "git log" works. It loads commit info page by page.

"load more": This is how VSCode + gitlens plugin works. It queris a limit number of commit info. And there is a button "load more", which allows user to load more commit info if needed.

The most simple way to repro this issue: clone linux repro. Then run above 3 command. They ALMOST don't work because of the perf issue. The command takes very long time to finish.

Thanks.

[The request orignates from this questions https://github.com/tpope/vim-fugitive/discussions/2344. Please close one or both if making nonsense to you. ]

**Comment by tpope** [comment]
I have no plans to add pagination at this time. I favor the simplicity of a `:Git` output being the exact output of the given command. Recommended workaround is `:Git log -1000`.
