### ISSUE TITLE
Feature request: Show details only on first line of a block with git blame

### ISSUE THREAD

**Issue by srgsanky** [tpope/vim-fugitive#2348]
It is visually easier to comprehend if only the first line of a block of change is marked by git blame. This is also how github shows the blame. For e.g.

<img width="782" alt="Screenshot 2024-10-13 at 08 35 05" src="https://github.com/user-attachments/assets/a3fbd245-6341-410e-b021-badef88cbcd8">

If vim-fugitive already support this, please share how I can configure it. Otherwise, can you please support this?

**Comment by tpope** [comment]
The `:Git blame` pane will always contain the output of `git blame`. It would probably be possible to achieve the desired rendering with syntax highlighting, and I would entertain a PR that did so.
