### ISSUE TITLE
Mappings not overwritten in summary window

### ISSUE THREAD

**Issue by SammysHP** [tpope/vim-fugitive#2349]
Since 3d9cace1ff599d1315028802c086d7e39810a432, fugitive no longer overwrites previous mappings in the `:Git` summary window. For example, pressing <kbd>\<CR\></kbd> does not open the file under the cursor anymore, but calls the normal mapping (`:map <CR> <Plug>(wildfire-fuel)` in my case).

**Comment by SammysHP** [comment]
Just as expected:

```
   <CR>          <Plug>(wildfire-fuel)
        Last set from ~/***/wildfire.vim/plugin/wildfire.vim line 59
```

In my opinion fugitive should have higher precedence in its own "special" buffers.

**Comment by tpope** [comment]
That's the entire output? I would expect to see 2 maps, a global one and a buffer local one. What's the output of `:verbose map <buffer> <CR>`?

**Comment by tpope** [comment]
So wildfire.vim, in an attempt to disable itself, is overwriting our `<CR>` map by mapping `<CR>` to `<CR>`. This is a bug, and not one I'm inclined to work around in Fugitive. Possibly you could work around it yourself by setting `g:wildfire_fuel_map` to a dummy map, and mapping `<CR>` yourself.
