### ISSUE TITLE
Ignore a file from status window

### ISSUE THREAD

**Issue by thomaspeklak** [tpope/vim-fugitive#235]
When on the status window, I would like to press `i` to add the current file to the nearest `.gitignore` file.
If no `.gitignore` file exists, then a new file in the project root should be created.

**Comment by au-phiware** [comment]
:+1: for ignore function

**Comment by hildensia** [comment]
+1

**Comment by bigardone** [comment]
👍

**Comment by clawoflight** [comment]
:+1:

**Comment by dmolinae** [comment]
So nothing here?

**Comment by 0e318236-1680-41a8-a989-3c9227637cdf** [comment]
Probably just a quality of life thing. If it 12 plus years this has been requested, no one has bothered to hack something up, its probably isn't needed. 

Fugitive seems really nice for frequently done tasks. After all how many files are you really ignoring on a day to day basis.
