### ISSUE TITLE
How to use enhanced diffs in fugitive?

### ISSUE THREAD

**Issue by jclsn** [tpope/vim-fugitive#2356]
I just discovered the enhanced diffs plugin https://github.com/chrisbra/vim-diff-enhanced. The diffs look much nicer, but fugitive seems to user its own syntax highlighting. Is there a way to use this in fugitive? Haven't found anything related in the docs.

**Comment by tpope** [comment]
As I read the docs, you can call `:EnhancedDiff` in any diff buffer. So with Fugitive, you'd call `:Gdiffsplit`, then `:EnhancedDiff`. See also the [update in the README](https://github.com/chrisbra/vim-diff-enhanced?tab=readme-ov-file#update) that this can now be achieved with a native Vim option.

**Comment by jclsn** [comment]
Thanks, that actually works by default. I mostly use ``Gclog``  though and there the diff looks different. Is it possible to use the same highlighting there?

**Comment by tpope** [comment]
That's just a plain text diff with syntax highlighting, unrelated to Vim's diffing features.

**Comment by jclsn** [comment]
Alright, thanks for clearing that up!
