### ISSUE TITLE
Cannot use editor in fish shell

### ISSUE THREAD

**Issue by justhsu** [tpope/vim-fugitive#2357]
I recently switched to fish shell (3.7.1) from zsh, and since I switched I have been unable to use the editor in fugitive. For instance, `:G` and `ca` gives the error:

```
error: sh /var/folders/rt/byl_72vn5n36snpnzk_rrx8c0000gn/T/vlevmG1/7.sh died of signal 9
error: there was a problem with the editor 'sh /var/folders/rt/byl_72vn5n36snpnzk_rrx8c0000gn/T/vlevmG1/7.
sh'
Please supply the message using either -m or -F option.
```

Running `:! which sh` shows that `sh` is bash, not fish shell, so I am not sure what might be wrong. This error doesn't happen under zsh or sh.

**Comment by tpope** [comment]
Fish is known to work; this is likely something on your end. You could try narrowing down by running `env SHELL=/bin/bash vim` inside Fish, and vice versa, to find out if it's the parent shell or the default shell.
