### ISSUE TITLE
Non-interactive hunk staging (enhancement request)

### ISSUE THREAD

**Issue by rocksolidwebdesign** [tpope/vim-fugitive#237]
Without needing to use the interactive mode, have the ability to select only some hunks for staging. The `gitg` tool lets you do this, for example.

Technically you can accomplish this already by using `p` in the `:Gstatus` window to trigger `git add --patch` but I don't want to use interactive mode, I just want to be able to view `git diff` output for each file at my leisure then and be able click on an individual hunk from inside the diff to be able to stage that hunk.

Example desired workflow
- Open the `:Gstatus` window
- Place the cursor on an unstaged file
- Hit `dp` to get the output of `git diff`
- Place the cursor on or inside of a hunk beginning with a line such as

for example:
    @@ -6,16 +6,18 @@ int foo_qux(char *bar) {
- Press a key such as `-` to add just that hunk to the staging area
- Additionally, ability to just click on the first line of a hunk, they way you do in `gitg`

**Comment by albfan** [comment]
Just take a look to [gapply tutorial](https://www.youtube.com/watch?v=NmxZczuN7_8)

[AndrewRadev/gapply.vim](https://github.com/AndrewRadev/gapply.vim) is mostly what you want, but it would be cool to integrate on fugitive

**Comment by MarioRicalde** [comment]
Good stuff!

@albfan gracias!

**Comment by tpope** [comment]
This is part of the new `:Gstatus`.
