### ISSUE TITLE
git-flow support

### ISSUE THREAD

**Issue by mhubig** [tpope/vim-fugitive#246]
Hi Tim,

thank you very much for this awesome plugin!
One thing I'm missing a bit is [git-flow](https://github.com/nvie/gitflow) support ...
maybe you can have a look in that?

Cheers, Markus

**Comment by aemonge** [comment]
Is the :Gflow or :Git flow still only under consideration ?

**Comment by tpope** [comment]
No, I think it's best suited to a separate plugin.
