### ISSUE TITLE
Diff two branches

### ISSUE THREAD

**Issue by tidbeck** [tpope/vim-fugitive#270]
I would like to diff two commits and get a window similar to the :Gstatus window. More info on this SO question: http://stackoverflow.com/questions/13304469/how-can-i-diff-two-branches-with-fugitive

**Comment by poige** [comment]
I don't know how it sounded like #132 but I'd assume it was about having some counterpart to `git diff branch1 branch2 --` and thus it's completely different. Seems fugitive currently ain't able to do anything alike, right?

**Comment by tpope** [comment]
No special support for it, but you can do `:Git diff branch1 branch2 --`.
