### ISSUE TITLE
vim-fugitive is awfully slow over sshfs

### ISSUE THREAD

**Issue by seletskiy** [tpope/vim-fugitive#280]
Not a fugitive issue really, but git issue.

I'm edit files ofter over an sshfs connection, so all git commands need to get and post files through network connections, which is slow as hell.

I've did not found ready-to-use solution, so I've made some workaround by myself: https://github.com/seletskiy/vim-refugi

It catches up usage sshfs and proxies all git commands through already opened ssh connection. It's fully transparent and fugitive visually works same, but much, much faster.

Maybe it will be to good idea to incorporate this mechanism into vim-fugitive.

Anyway, any feedback is a appreciated.

Thanks for attention.

**Comment by tpope** [comment]
The fact you did this externally is awesome really. It's enough of edge case that I think that's probably the best place for it.
