### ISSUE TITLE
fugitive workflow for commit --fixup?

### ISSUE THREAD

**Issue by lkraav** [tpope/vim-fugitive#303]
Wondering first of all if there's a more fluid way to fugitive this besides typing :Gcommit --fixup=<findhashfromsomewhere>

**Comment by jreybert** [comment]
One interesting feature would be to ease the fixup when this is a one line fix (or all modified lines belong to the same commit).

Then, the map could take as --fixup argument the line commit SHA1. With one command, the line fix is commited with the right fixup SHA1.
However, Gblame shows zeros when the line is modified...

**Comment by lwm** [comment]
In the meanwhile, [this is awesome](https://blog.mikecordell.com/vim/2014/07/20/quick-fixup-in-vim-with-fugitive.html).

**Comment by still-dreaming-1** [comment]
If anyone here is still interested in this, I made an implementation of this, which is being discussed in pull request #843 . This would be a good time to provide some feedback and input.

**Comment by tpope** [comment]
Provided as `cf` as part of the new `:Gstatus`.

**Comment by ultrox** [comment]
I love this feature, but it seems I have a problem understanding to find commit. 

In documentation it reads:
```
cf                      Create a `fixup!` commit for the commit under the
                        cursor.
```
So I open :Gclog and do cf there, but nothing happens. Am I been missing something obvious? How can I find a list to `cf` on?

I also tried to `cf` unpushed, and that works fine.

**Comment by tpope** [comment]
> part of the new `:Gstatus`.

**Comment by tmccombs** [comment]
but what if you want to fixup a commit that isn't shown in the status buffer?

**Comment by tpope** [comment]
It works editing a commit object too.

**Comment by ultrox** [comment]
Oooh, now I get it! @tpope you are cryptic fella! :smile: 

Basically, I just did 
1. :Gcommit, found the commit I want, 
2. 'Enter' to it to get it to editing, 
3. `cf` when the cursor was line after committer 

This works fine.

I was expecting to be able to `cf` from QuickFix List.

**Comment by tpope** [comment]
The quickfix window is global. It's not our place to go dumping Fugitive specific maps in it. It's also problematic in other ways. These days I recommend using `:Git log` instead.

**Comment by ultrox** [comment]
Absolutely make sense!
