### ISSUE TITLE
What does fugitive do to every line of my file on :Gdiff?

### ISSUE THREAD

**Issue by gfixler** [tpope/vim-fugitive#313]
After a :Gdiff there are `n` changes to my file, `n` equaling the number of lines in my file. Nothing visible is ever changed, but it always makes me wonder. What is it that creates this undo entry?

**Comment by tpope** [comment]
Reading this again this is just the standard way `BufReadCmd` works. It's changing the blank buffer at `fugitive://` to a buffer with the contents of your file in it.
