### ISSUE TITLE
Fugitive is freakin' nice!... A small feature request:

### ISSUE THREAD

**Issue by trusktr** [tpope/vim-fugitive#327]
It's nice that when you open a git-tracked file that the Git command become available.

But, vim also has the `:lcd` command to change the current working directory in the current window. So, if I move into a directory using `:lcd /path/to/git-tracked-project`, then I'd expect the Git commands to become available for that directory, even if I haven't opened a git-tracked file from that location.

EDIT: In most cases, I'll  have a file open and I'll use git commands with them, but there are few exceptions: what if for some reason I want to simply `:lcd` to a new place, and check a git log or status?

IDEA:
Right now, fugitive makes Git commands available based on the file that's open in the buffer, and if you `:lcd`, it has no effect. Fugutive needs a way to change the directory that the Git commands take place in, and a way to reset back to normal functionality.

TWO NEW FEATURE SET POSSIBILITIES:
-- THE FIRST POSSIBILITY:
--(1) If you `:lcd /somewhere`, allow the Git commands work be based on the directory you are now in. So if you change to some other git project's directory, the `:Git` commands work in the scope of the project.
--(2) One could easily change back to the current file's location by typing `:lcd %:p:h<CR>`, and the `:git` commands would now work with the current file's git project scope.

-- THE SECOND POSSIBILITY:
--(1) Fugitive already has a `:Gcd` command. Why not let it change directories to anywhere like`:lcd` or `:cd` do, not just relative to the current file's git project scope, and if you land in a folder of another git project, then the commands take effect in the scope of that git project.
--(2) Add a `:Greset` command (or similar) to bring you back to the scope of the current file's git project.

I think this would make fugitive more powerful and allow for more usage possibilities.
So, what do you think?

**Comment by still-dreaming-1** [comment]
> You can `:e /path/to/repo` just as easily as you can `:lcd /path/to/repo`.

Oh wow this actually works. I didn't realize you can edit a directory...

**Comment by still-dreaming-1** [comment]
> Oh wow this actually works.

I'm no longer sure this is working/helping me. I may have just been noticing an improvement made to fugitive a while back. Doing further testing and research.
