### ISSUE TITLE
shortcuts to open commit

### ISSUE THREAD

**Issue by pimlott** [tpope/vim-fugitive#328]
I arrived at fugitive because I was looking for a quick way to view commits while looking at 'git rebase -i' or 'git log' output.  I was copying and pasting onto 'git show' a lot.

With fugutive, I created the following mappings to go to the commit under the cursor:

    nmap gc :exe "Gedit " . expand("<cword>")<CR>
    nmap <C-W>c :exe "Gsplit " . expand("<cword>")<CR>

`gc` is mnemonic for "goto commit" and similar to `gf`.  It also happens to be unused by vim.  `<C-W>c` is similar to `<C-W>f`, though it does override a built-in binding.

Just offering in case anyone finds this useful or has better ideas.

Andrew

**Comment by blueyed** [comment]
This was done in https://github.com/tpope/vim-fugitive/issues/697.

**Comment by CervEdin** [comment]
How does one do this? Can't get any of the suggestions to work. Does anyone have any helpful links to docs?

**Comment by tpope** [comment]
This issue is very old. In `:Git log` buffers you can press `<CR>` on the `commit` line. In rebase buffers, try `<C-W>f` on the SHA to open the commit in a split.

**Comment by CervEdin** [comment]
> This issue is very old. In `:Git log` buffers you can press `<CR>` on the `commit` line. In rebase buffers, try `<C-W>f` on the SHA to open the commit in a split.

That's extremely useful during rebase. Is there a way to default to a vertical split?

**Comment by tpope** [comment]
No, but you should be able to make your own map.

```vim
cnoremap <Plug><cfile> <C-R><C-F>
nmap <C-W><C-F> :vert sfind <Plug><cfile><CR>
```

This is global, it will work with Fugitive's jump-to-file but also fall back to the Vim default.

**Comment by CervEdin** [comment]
Hmmm.. Not able to get it to work 🤔

> ```viml
> cnoremap <Plug><cfile> <C-R><C-F>
> ```
This renamps `<Plug><clife>` to insert the object under the cursor? 

> ```viml
> nmap <C-W><C-F> :vert sfind <Plug><cfile><CR>
> ```
Then this runs `sfind` on the SHA under the cursor and opens in a vertical split?

**Comment by tpope** [comment]
> Hmmm.. Not able to get it to work 🤔 `<C-W><C-F>` complains it can't find the file in the path

What is the _exact_ error, including file name?

> > ```viml
> > cnoremap <Plug><cfile> <C-R><C-F>
> > ```
> 
> This renamps `<Plug><clife>` to insert the object under the cursor?

Yes. But Fugitive _overrides_ this map in Fugitive buffers to insert a Fugitive URL instead. We only define this so it works outside of Fugitive too.

> > ```viml
> > nmap <C-W><C-F> :vert sfind <Plug><cfile><CR>
> > ```
> 
> Then this runs `sfind` on the SHA under the cursor and opens in a vertical split?

In a Fugitive buffer, it shouldn't be a SHA, it should be a `fugitive://` URL.

**Comment by CervEdin** [comment]
> 
> What is the _exact_ error, including file name?

```
E345: Can't find file "309c681" in path
```

> 
> Yes. But Fugitive _overrides_ this map in Fugitive buffers to insert a Fugitive URL instead. We only define this so it works outside of Fugitive too.

It doesn't look a fugitive url is inserted 🤔
How would a proper fugitive url of a ref look like?
Like this:
`: vert sfind fugitive:///home/erik/repos/tpope/vim-fugitive/.git//309c68117eca3a95349093@12e5886a184c1812d/`

> 
> In a Fugitive buffer, it shouldn't be a SHA, it should be a `fugitive://` URL, thanks to the override.

So it works in other (at least some) buffers, but curiously not in the rebase buffer 😟
