### ISSUE TITLE
:Glog diff browsing

### ISSUE THREAD

**Issue by qstrahl** [tpope/vim-fugitive#329]
It would be super awesome if we could do `:vsp` on a file in diff mode, then `:Glog` and step through all the revisions of that file - all the while maintaining the diff, so we see the differences highlighted through whatever revisions. Maybe that doesn't belong in an official command (awesome though it is), but that should definitely be scriptable.

The problem is that fugitive bends over backwards to switch off the diff if you leave a revision in diff mode. While this behaviour is nice at times, perhaps a flag could be introduced to control it? That way, at least, we could script the workflow easily for ourselves.

**Comment by seb-mueller** [comment]
I'm trying to to exactly the same, would you mind sharing the solution you came up with @qstrahl ? Thanks!

**Comment by Konfekt** [comment]
Dear Sebastian @seb-mueller , did you find out? I'd also like to diff recent revisions of the currently open file by something like `Gdiffsplit HEAD~2` but now `2` not referring to the penultimate commit in the repository, but that touching the currently open file. Currently I am copy-pasting the commit hash from `:Git! log --oneline -- %` or similar

**Comment by Konfekt** [comment]
One work around could be to open a revision in `:0Gllog`(in a new tab) and then `:Gdiffsplit` in that buffer.
