### ISSUE TITLE
Gdiff doesn't work with submodules under Windows

### ISSUE THREAD

**Issue by vadz** [tpope/vim-fugitive#330]
When using submodules, `:Gdiff` doesn't work under Windows/Cygwin, it just opens an empty window. There are no error messages and I don't know how to debug this (all I did was to check that `b:git_dir` was set correctly, i.e. to the parent repository `.git` subdirectory) so I have no idea about what is going wrong here.

FWIW it works just fine with the same repository under Unix and `:Gdiff` works perfectly well inside the main repository itself under Windows too.

**Comment by tpope** [comment]
Submodule support was a hack in 2013, it's much better now. If this is still happening report back on the value of `b:git_dir` (it should be the child repo, not the parent repo).

**Comment by vadz** [comment]
Sorry, I've completely forgotten about this one, but it indeed works just fine now and, I suspect, has been working for quite some time. Sorry again for not closing it myself and thanks for doing it (and for fixing the underlying problem, in passing)!
