### ISSUE TITLE
Preview changes from Gstatus.

### ISSUE THREAD

**Issue by eloyesp** [tpope/vim-fugitive#339]
I come from gitg so when I check Gstatus I would like something like a preview of the diff on each file. I'm using `dp` for that, but it have two downsides, it reuse a existing window and it get focus, so I have to came back and forth.

So can be added a preview on the diff of the file on the current line in a preview window?

I think it is related to #318 as it would help preview without disturbing the layout.

**Comment by tpope** [comment]
Now provided.
