### ISSUE TITLE
:Glog has no results when used via gvim on Windows.

### ISSUE THREAD

**Issue by afoster1** [tpope/vim-fugitive#340]
I know this problem has been reported in the past (Issue #199 & #211) but it seems to have reappeared.  I've raised this issue as they are both now closed.

If I issue the command ":Glog" from a file I know has git history, then view the quickfix window, it is empty.  
Doing the same using vim on the command line shows the history as expected.

From what I can see the previous solution was implemented by commit 5298448, which I have in my fugitive commit history... so it seems it may be suffering from a regression somewhere.

On further investigations, it seems that a vim command such as the following, does not generate any output:
":!git --git-dir="c:/path/to/repo/.git" --no-pager log --no-color -- path/to/source/filename"

While, a command such as this does work, but obviously outputs all the history:
":!git --git-dir="c:/path/to/repo/.git" --no-pager log --no-color"

I'm still confused.  Any ideas what would be causing this?

My work environment consists of:
Windows 7 64 bit.
vim - "VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Oct 27 2010 17:59:02)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1-46"
Portable git - "git version 1.8.0.msysgit.0"
vim-fugitive - up to date as of commit 54ead5a

**Comment by tpope** [comment]
If this is a Windows escaping issue as it appears to be it should definitely be fixed.
