### ISSUE TITLE
No syntax coloring in MacVim for Gblame

### ISSUE THREAD

**Issue by dsummersl** [tpope/vim-fugitive#344]
I'm not sure why this is, I've tried making a minimal vimrc to isolate why/how syntax coloring doesn't work in MacVim. Coloring does work just fine on the console vim, however...

**Comment by andyearnshaw** [comment]
This appears to affect Neovim too.

**Comment by cweilemann** [comment]
I'm seeing this as well using MacVim... It worked a few months ago (I don't remember exactly when) but now doesn't.

**Comment by tpope** [comment]
We're using a real `syntax/` file, that should clear up most weirdness around this.
