### ISSUE TITLE
Interactive pre-commit hook waits indefinitely

### ISSUE THREAD

**Issue by kayleg** [tpope/vim-fugitive#355]
When using a pre-commit hook which requires user input, the commit just hangs.

I am using https://github.com/nextbigsoundinc/Sprintly-GitHub hook which checks if the commit references a Sprint.ly item and prompts the user if it does not. 

The prompt never appears when committing using the Gstatus and Shift-C process

update: changed reference repository to correct one

**Comment by lukeberry99** [comment]
I'm experiencing this issue at the moment, any work around for this?

**Comment by tpope** [comment]
There's no mechanism for input, but it should fail now instead of hanging. I'm skeptical that interactive input can be shoehorned into the convoluted process `:Gcommit` uses to invoke the editor, but I'm open to ideas.
