### ISSUE TITLE
Windows :Gstatus - "fatal: not a git repository"

### ISSUE THREAD

**Issue by mgatto** [tpope/vim-fugitive#359]
Full error is:

```
fatal: Not a git repository: ''C:/Development/CSV_Merger/src/.git''

shell returned 128
```

I'm using TCC as my shell, but also get this in a vanilla CMD. I use Solarized in my shell. 

My _vimrc is at: http://pastebin.com/apTiS83D

Msysgit is correctly setup and the plain :!git commands work. CLI Git works fine, too.

Using :Gcommit, I get this odd-looking collection of characters in red:

```
fugitive: <ff><fe>T^@C^@C^@:^@ ^@U^@n^@k^@n^@o^@w^@n^@ ^@c^@o^@m^@m^@a^@n^@d^@ ^@"^@e^@n^@v^@"^@^M
```

**Comment by xelat09** [comment]
fyi, issue still persists with shellslash version (git-bash@Windows)

**Comment by durgaswaroop** [comment]
I got this error today on Cygwin. Is it not fixed yet?

**Comment by tpope** [comment]
I'm fairly confident the original TCC issue is fixed (or perhaps replaced by a much different issue). If you have problems with other environments, open a separate issue for them.
