### ISSUE TITLE
A noob question, exiting out of Gdiff

### ISSUE THREAD

**Issue by wavded** [tpope/vim-fugitive#36]
Love this plugin, but one thing I can't figure out is how to stop doing a Diff.  If I use:
    :Gdiff
It will split my windows out and let me do that, but how to do I exit that.  I've tried:
    :diffoff
But that doesn't get me back to my original file and remove the other "orig" version.  Any tips?  Thanks.

Marc

**Comment by starikovs** [comment]
The way I do a diff:

1. :Glog --
2. :cw to open a list of commits
3. Navigate to a commit and its info as well affected files are shown
4. Focus on a file path
5. <c-w>gf and the diff is opened in new tab
6. :tabclose to just close the tab and get the previous state before the diff

https://stackoverflow.com/a/45075152/202550

**Comment by tandrewnichols** [comment]
> Yeah no problem I'll just store them all on the SPACE SHUTTLE THAT VIM ALSO SHIPS WITH.

How do I access said space ship? `:h spaceship` is missing. Please advise.
