### ISSUE TITLE
Losing fugitive commands

### ISSUE THREAD

**Issue by bluddy** [tpope/vim-fugitive#361]
It often happens to me that while working, I will try a fugitive command and it'll suddenly be unbound in a particular buffer (that's under git's control). I'll try switching to another open buffer and it'll work in that one. Sometimes I'll even open the status window and the fugitive commands won't be bound there. Looking at augroups, they all seem to load, so I'm really unsure what the problem is. Sometimes fugitive commands don't work from any buffer, so I restart vim and everything's back to normal (for a while).

I'm wondering if anyone else here is experiencing this? It's most likely a conflict with some other plugin, but it doesn't happen predictably enough that I can bisect it easily. BTW I'm working on OSX, and I update my local copy of fugitive often (which doesn't seem to help).

**Comment by Konfekt** [comment]
In my setup, if `&hidden` is set, then `:Git` is no longer available on startup when Vim is started with more than one file argument inside a git repository. If `&hidden` is unset, then `:Git` is available again.

**Comment by tpope** [comment]
The `hidden` thing is not currently reproducible for me. A lot has changed in 6 years, hopefully this is fixed.
