### ISSUE TITLE
Is there a way disabling vim-fugitive when accessing a file on a netshare from windows?

### ISSUE THREAD

**Issue by robi-wan** [tpope/vim-fugitive#365]
I use vim on windows and discovered a slowdown when the file I want to open is accessed on an UNC path on a netshare (\server\share\folder\server.log). I did some profiling (thanks to Drew Neil http://vimcasts.org/episodes/profiling-vimscript-performance/) and discovered that the line

```
    let type = getftype(dir)
```

in function [fugitive#extract_git_dir](https://github.com/tpope/vim-fugitive/blob/124550cfee33a1bb9a227e78ccc709317a89dae9/plugin/fugitive.vim#L125) takes nearly 3 seconds when the accessed file is on a windows netshare - but it returns almost instantly when the accessed 
file is local.

Is it possible to disable fugitive (for the buffer) when the accessed file is on an UNC path, e.g some autocommand?

**Comment by tpope** [comment]
I *think* this is better now because we don't look for weird stuff like `\\.git`. Do report back if it's still a problem in practice.
