### ISSUE TITLE
Could we get some eye candy from GitHub blame in :Gblame?

### ISSUE THREAD

**Issue by bananu7** [tpope/vim-fugitive#369]
I've recently discovered how nice GH blame really is. What caught my eye was:
- grouping lines affected by one commit
- coloring based on the date of change
- displaying a commit message that impacted the lines

I think at least the grouping should be relatively easy to implement, and it would significantly increase readability.

Something like that just looks like a wall of text:

![lounge](https://f.cloud.github.com/assets/2399997/917079/155a3be8-fe9d-11e2-9cd0-0c4c9f36546b.png)

compared to:
![lounge2](https://f.cloud.github.com/assets/2399997/917095/4d6236bc-fe9d-11e2-9836-145a47290cc0.png)

**Comment by tpope** [comment]
Per commit colors are now standard and can be forced with `:Gblame --color-lines`. This is my solution. I will consider a @mattboehm style solution if it can be implemented with zero regressions ("breaks some buffer local keymaps" is a dealbreaker) and a performance overhead of less than double.
