### ISSUE TITLE
Feature request: :Gwrite should accept a range

### ISSUE THREAD

**Issue by cemerick** [tpope/vim-fugitive#370]
I use vim-signify to see signs corresponding to `git diff` output.  Because of this, I already know where diff hunks exist, and so staging them directly from the buffer with a single command would be great (rather than dropping into a split diff view, `:diffput`-ing, and closing the diff view).  Allowing `:Gwrite` to accept a range for its operation would be great; presumably, a higher-order `:Ghunkw` (or whatever) command could then be cobbled together that used vim-signify signs' line numbers to determine the range to be provided to `:Gwrite`.

**Comment by sharplet** [comment]
:+1: :sparkles:  yes please!

**Comment by tpope** [comment]
No amount of +1ing will cause an implementation to materialize.

**Comment by frioux** [comment]
I think that this would also make sense for :Gread.

**Comment by rgrinberg** [comment]
In that case, we shall re-double our efforts.

+2

**Comment by tpope** [comment]
Let's merge this into #269, which is basically the same thing.
