### ISSUE TITLE
More verbose behavior required when no space left on /tmp

### ISSUE THREAD

**Issue by isbjorn** [tpope/vim-fugitive#373]
If no space left on /tmp then commands like Gstatus, Gdiff, Gcommit will open empty buffer without any errors

Glog prints

:!git --git-dir=/path/to/.git --no-pager log --no-color '--pretty=format:fugitive:///path/to/.git//%H::%s'  2>&1| tee /tmp/vqTlMqH/15
fatal: bad default revision 'HEAD'
tee: /tmp/vqTlMqH/15: No space left on device

shell returned 1

**Comment by tpope** [comment]
Open to suggestions of how to detect this.
