### ISSUE TITLE
Improve startup time

### ISSUE THREAD

**Issue by ipkiss42** [tpope/vim-fugitive#376]
With the current implementation, all the code lives in plugin/fugitive.vim. It means that everything is parsed when vim starts, no matter if fugitive is going to be used or not.

Why not moving most of the code to the autoload folder (see :h autoload)? It would improve vim startup time, without any drawback.

**Comment by lucc** [comment]
I am also interested in this. But when I had a look at the code I noticed that there are no comments in the code and it is near to impossible to understand which function does what without reading all the code.

Is there a plan to add comments to the code (like python doecstrings)? Or will PRs for such be merged?

I think this could be a step to get people (me?) interested in doing the autoload implementation.

**Comment by tpope** [comment]
It's an internal API. Documentation is just more work to maintain with very little benefit.

The main section you have to worry about is "Initialization", along with whatever functions it calls from "Utility".

**Comment by tpope** [comment]
Done.
