### ISSUE TITLE
:Gblame gives "fugitive: file or blob required" when using python-mode

### ISSUE THREAD

**Issue by andrewmichaelsmith** [tpope/vim-fugitive#379]
I'm running vim-fugitive with python-mode, whenever I do a :Gblame I get the error:

```
fugitive: file or blob required
```

Other fugitive commands result in other errors.

My .vimrc looks like:

```
set hlsearch
set ts=4
set textwidth=80
set incsearch
set smartcase
set modeline
set ls=1
set shiftwidth=1
set tabstop=4
set nocompatible
set expandtab
set hidden
execute pathogen#infect()
syntax on
filetype plugin indent on
au BufRead,BufNewFile *.md set filetype=text
let g:pymode_folding = 0
set backupdir=/tmp
set directory=~/tmp,/tmp " swap files
```

I have the following bundles installed:
- ctrlp
- fugitive
- gitgutter
- python-mode

As of posting this I am on the latest commit for all these plugins:

```
Entering 'vim/bundle/ctrlp'
b5d3fe66a58a13d2ff8b6391f4387608496a030f
Entering 'vim/bundle/fugitive'
124550cfee33a1bb9a227e78ccc709317a89dae9
Entering 'vim/bundle/gitgutter'
878c3422c9ad9edc7b907948515b3118d91a67d1
Entering 'vim/bundle/python-mode'
2bbe97969bba72ba67e67ea5f20bb8cbc95606d2
```

Any pointers or ideas? I would have thought that python-mode and vim-fugitive would be a popular combination.

The reason I suspect that this is a conflict with python-mode is that vim-fugitive worked perfectly with ctrlp and gitgutter before

Thanks

**Comment by tpope** [comment]
There were a lot of case insensitivity issues that have been fixed so that probably was indeed the cause.
