### ISSUE TITLE
Gdiff and autocommand

### ISSUE THREAD

**Issue by dathinaios** [tpope/vim-fugitive#38]
First of all thanks for a great plugin! 
Not very sure this is related to fugitive but here it goes...
I am trying to have an autocommand that will unfold all my folds after Gdiff
is called and then also set the foldmethod to diff to fix the display. I tried it
like that which I think should work but...

function OpenFoldsAndDiff()
    if &diff
        foldopen
        set foldmethod=diff
    endif
endfunction

au FilterWritePost \* if &diff |set foldmethod=marker| endif 
au FilterWritePre \* call OpenFoldsAndDiff()

D.

**Comment by tpope** [comment]
This sounds like a personal config issue, as `foldmethod=diff` is already set when `:diffsplit` is called.
