### ISSUE TITLE
Gmove: path doesn't match buffer name

### ISSUE THREAD

**Issue by fweep** [tpope/vim-fugitive#385]
Given a file and buffer named `services/cart.py`, doing `:Gmove cart_service.py` results in a buffer named `services/cart_service.py`, but performs a `git mv services/cart.py cart_service.py`. The `services` directory was not included in the `git mv`, even though the buffer name still includes it.

I was actually just testing to see how this worked, because normally I'll `Gmove` using the relative path. I was pleasantly surprised to see that without a path it renamed only the file, but there's a mismatch between the buffer name and the filename.

It'd be nice if there were an intuitive way to do this rename without having to specify the relative path (I believe this is how `Rename` in vim-eunuch works), but whatever the case, the buffer name and filename should match.

Thanks for a great plugin!

**Comment by daliusd** [comment]
I think this can be closed as :Grename exists already in fugitive.

**Comment by tpope** [comment]
It's no longer directory relative (that's been moved to `:Grename`) so definitely fixed.
