### ISSUE TITLE
:G* shortcuts, and most recent shell command

### ISSUE THREAD

**Issue by leeola** [tpope/vim-fugitive#386]
Would it be possible to make Fugitive work, as in using `:Gcommit`, `:Gstatus`, `Git foo` and so forth, _without_ it triggering the most recent `!` command?

Eg, when developing i often run the most recent shell command to rerun tests. This occurs constantly. I love the workflow, because i can run specific tests, or manual interactions with code, etc. Basically anything, and repeat it until i get it right.

Fugitive sort of screws with this though. Most of the Fugitive commands execute `!git foo` and cause my most recent `!` command to be fugitive. Making writes, commits, diff checks, etc, something i want to avoid.

Is there a way around this? Could Fugitive restore the most recent `!command` to that list, rather than trampling over my command history?

I'm not familiar with VimScript, so pardon my weird/incorrect wording.

**Comment by tpope** [comment]
Most commands use `system()` not `:!` now. For the ones that don't, this is probably cantfix, unless you can offer a workaround.
