### ISSUE TITLE
Gdiff dies :(

### ISSUE THREAD

**Issue by vito-c** [tpope/vim-fugitive#387]
Running :Gdiff on a conflicted file when I have the below in my vimrc causes vim to background itself then when I type fg vim will keep backgrounding itself... 

in my vimrc:
set shell=/usr/local/bin/bash\ --rcfile\ ~/.pirate-setup/pirate-vim/vim-bashrc\ -i
# !/usr/local/bin/bash

shopt -s extglob
shopt -s cdspell
shopt -s nocaseglob
shopt -s histappend
shopt -u expand_aliases
shopt -s globstar

**Comment by tpope** [comment]
My new official policy on `'shellcmdflag'` shenanigans is to file them under PEBKAC. You're almost certainly breaking a lot more than Fugitive, and if not, the burden of proof is on you to demonstrate that.

**Comment by vito-c** [comment]
blast from the past!
