### ISSUE TITLE
Feature Request: Simple Status

### ISSUE THREAD

**Issue by rdegges** [tpope/vim-fugitive#39]
Hi,

I love using `vim-fugitive`, it has really change my workflow. Anyhow, this is feature request. If you don't agree with it, feel free to reject, I just thought it would make a nice addition:

If you do a :Gstatus and no changes have been made, I propose that instead of opening up a split just to display the 'no changes have been made' message should be replaced by a simple vim status line saying the same. This way, it wouldn't force the developer to close the split, and would be quicker.

**Comment by tpope** [comment]
This would not make sense with the new `:Gstatus`.
