### ISSUE TITLE
E492: Not an editor command

### ISSUE THREAD

**Issue by ioiioi** [tpope/vim-fugitive#400]
I install vim-fugitive with vundle

```
set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'plasticboy/vim-markdown'
Bundle 'altercation/vim-colors-solarized'
Bundle 'tpope/vim-fugitive'

filetype plugin indent on
```

`:BundleInstall` install vim-fugitive successfully.

but when issue :Gstatus, there is `E492: Not an editor command`

what's problem?

**Comment by JieVoo** [comment]
HI ioiioi, Could you tell me which file did you edit for such a problem? Because I think I met with the exactly same issue as you posted here. Thank you!

**Comment by robin92** [comment]
Frankly speaking, I'd love to be able to issue {{Gstatus}} or {{Gdiff}} without the need to have any file open. In this case the git root could be deduced by a current directory.

**Comment by tpope** [comment]
There is no autocommand for "new unnamed buffer created." It's not possible without a gross hack.

**Comment by maxim-usikov** [comment]
@tpope 
> There is no autocommand for "new unnamed buffer created." It's not possible without a gross hack.

So can't resolve next?

1. Start vim
2. Execute `:%bd`
3. Try execute `:Gstatus` got `E492: Not an editor command: Gstatus`

**Comment by 0xyeti** [comment]
@maxim-usikov I'm facing the same issue. Did you fix that?

**Comment by maxim-usikov** [comment]
> @maxim-usikov I'm facing the same issue. Did you fix that?

@0xyeti nope.

**Comment by mcansky** [comment]
any news on this ?

**Comment by tpope** [comment]
Still impossible with the current design!

**Comment by amir-teymuri** [comment]
I'm facing the same issue 3 years after. Is there any solution to this problem?

**Comment by tpope** [comment]
`:Gstatus` was deprecated and removed in favor of `:Git`. This is documented at `:help :Gstatus`.
