### ISSUE TITLE
Custom height for GStatus

### ISSUE THREAD

**Issue by jgallen23** [tpope/vim-fugitive#401]
I'd like to make the GStatus taller, is there already a variable exposed to change this, if not, would you accept a pull req for it if I did the work?

**Comment by aeonaut** [comment]
Like several commenters from [this SO question](http://stackoverflow.com/questions/3712725/can-i-change-vim-completion-preview-window-height), I get no effect from `set previewheight=whatever`. The Gstatus window is unchanged (at 5 lines). There is a workaround suggested in that thread:

```
set previewheight=50
au BufEnter ?* call PreviewHeightWorkAround()
func PreviewHeightWorkAround()
    if &previewwindow
        exec 'setlocal winheight='.&previewheight
    endif
endfunc
```
 
This works, but I'm curious why I can't make it work just by setting `previewheight`. What am I missing here? `:help previewheight` only mentions that my Vim must be compiled with the +windows and +quickfix options, which it is.

**Comment by dhruvasagar** [comment]
The `:Gstatus` window is no more a preview window, so setting `previewheight` will have no effect on it.

**Comment by tpope** [comment]
Was not true when the question was asked but is now. Use `:20Gstatus` to open a window with a height of 20.

**Comment by rdamborsky** [comment]
Using `:20Gstatus` works fine, until I press `P` on some file to do interactive patches selection. Then, once I go back from patching, the window is back to default height (not 20).

What's the right way to keep the height set even in this scenario? Is it possible to open Gstatus in full size of the window/pane I called it from?

**Comment by dhruvasagar** [comment]
Well you can now add / remove hunks from the `Gstatus` window itself so I would recommend using that instead of the interactive patching. You can toggle the diffs inline using `=` on a file in the `Gstatus` window and navigate between individual hunks using the regular `<C-p>`/`<C-n>`bindings (also used for navigating between files) and add / remove those hunks individually.

**Comment by rdamborsky** [comment]
This is awesome! Thank you for the tip

**Comment by kubek2k** [comment]
> Was not true when the question was asked but is now. Use :20Gstatus to open a window with a height of 20.

@tpope what should I do to retain that height over time?

**Comment by Moshem123** [comment]
Still looks unresolved.
Opening the status split in a certain height works well, but when performing an action like commit, the window goes back to its original size.

**Comment by tpope** [comment]
The Fugitive window behaves like every other window. Look into `'winfixheight'`.

**Comment by Moshem123** [comment]
Thanks @tpope 
Here is some code for people googling:
```
function! ToggleGStatus()
  if buflisted(bufname('.git/index'))
    bd .git/index
  else
    Git
    20wincmd_
  endif
endfunction
command! ToggleGStatus :call ToggleGStatus()
nnoremap <silent> <leader>gg :ToggleGStatus<cr>

augroup fugitive_au
  autocmd!
  autocmd FileType fugitive call s:ftplugin_fugitive() | setlocal winfixheight
augroup END

```

**Comment by WIttyJudge** [comment]
I found this and it works:

```
nmap <leader>gs :Gstatus<CR><C-w>5-
```

It reduces the height by 5, but if you want to increase height, add + instead of -
