### ISSUE TITLE
Proposed features for :Gblame

### ISSUE THREAD

**Issue by tommcdo** [tpope/vim-fugitive#405]
I have a few ideas for `:Gblame` that are of questionable usefulness and that would both make use of similar data in different ways.
#### Show commit message for commit under cursor on the cmdline

I've got a basically working prototype of this in the form of a plugin to be installed alongside fugitive: https://github.com/tommcdo/vim-fugitive-blame-ext

Presently, it looks up the commit message on every first encounter of a new commit hash using `git show` and caches it in a Dict. But I'm considering using `git log --oneline %` to grab them all at once. A problem here is that it may (probably will) grab more commits than it needs in the case that a commit is part of the file's history but no longer present in its blame. It also muddies the notion of when to grab a commit message -- grabbing them all each time `:Gblame` is fired will result in a lot of wasted effort, particularly when multiple files have common commits to blame.
#### Chronological commit navigation key mappings

The idea is to be able to navigate to the first line in the blame output for the next/previous commit chronologically relative to the commit under the cursor.

I was thinking to have `<C-n>` and `<C-p>` do this. Not totally sure if useful; a friend of mine asked if there was a way to jump to a line from the most recent commit while in the `:Gblame` window, and this is what I thought of as a more general, encompassing feature.

This could potentially use the same data that the first idea uses, but it would need to store it differently (an ordered List rather than a Dict with commit messages as values).

Another problem is how to efficiently obtain this data. Using `git log --oneline %` would be a good starting point, but it would need to either intersect that with commits present in the blame or know how to skip over commits that are not present until it finds one that is. Both seem somewhat unpleasant.

---

Seems like the two ideas kind of step on each other's toes for data. The first is definitely more useful for a general audience, but potentially too expensive to be enabled by default. The second is also pretty expensive, and maybe not as useful, but could satisfy some niche needs.

Any ideas about this?

**Comment by SevereOverfl0w** [comment]
Just gave this a spin locally, and it works great!

Using git blame -p, gives a porcelain format, with other things, this provides the summary of the commit message. Vimscript would need to be written to parse this porcelain.

**Comment by eyalfir** [comment]
Tried locally. Same result as @SevereOverfl0w.
Work great, no sluggishness with neovim on Mac.

Merge with master still works w/o conflicts.

When moving out from the `fugitiveblame` window and back in, the statusline no longer updates. This patch seems to have solved the problem:
```
diff --git a/plugin/fugitive.vim b/plugin/fugitive.vim
index 4d953cf..7e15e8d 100644
--- a/plugin/fugitive.vim
+++ b/plugin/fugitive.vim
@@ -1925,6 +1925,7 @@ augroup fugitive_blame
   autocmd Syntax fugitiveblame call s:BlameSyntax()
   autocmd User Fugitive if s:buffer().type('file', 'blob') | exe "command! -buffer -bar -bang -range=0 -nargs=* Gblame :execute s:Blame(<bang>0,<line1>,<line2>,<count>,[<f-args>])" | endif
   autocmd ColorScheme,GUIEnter * call s:RehighlightBlame()
+  autocmd BufEnter *.fugitiveblame let &l:statusline = '%{fugitive#blame_statusline('.bufnr('').')}%<'
 augroup END
 
 function! s:linechars(pattern) abort
```

**Comment by tommcdo** [comment]
I just tried out the [blame_message](https://github.com/tpope/vim-fugitive/tree/blame_message) branch and it works beautifully. Definitely an improvement over my extension. The way it interacts with `'scrollbind'` is fantastic :smile:

Is there anything holding up merging this branch in?

**Comment by tpope** [comment]
I refrained from merging due to the aforementioned redraw issues: scrolling too fast through a bunch of unloaded commits would garble the screen. I can't seem to reproduce that any more. Let me try it out a few days and then I will try merging.

**Comment by tpope** [comment]
@eyalfir I can't reproduce your problem. My guess would be you have some other plugin mucking around with `&l:statusline`.

@SevereOverfl0w parsing the porcelain output is certainly doable, although I worry it would be on the slow side. Using it for the commit message would probably not be too hard, but fully re-implementing `:Gblame` on top of it sounds to me like it would be much harder than you're assuming. The devil is in the details.

**Comment by SevereOverfl0w** [comment]
I was on a new machine today, and surprised myself that the commit messages weren't there. Is this branch ready for merge @tpope. You mentioned some testing.

**Comment by omeid** [comment]
Would love to have this feature, sometimes commit message is all you need to know about a line of code.
