### ISSUE TITLE
Feature request: Gdiff just like Gstatus

### ISSUE THREAD

**Issue by icx-jonv** [tpope/vim-fugitive#425]
It would be awesome if you could issue :Gdiff <commit> <commit>.  This would then produce a list of files that are different between the two commits, similar to Gstatus at the top of the window.  Like Gstatus, pressing D on a particular line would open the diff for the versions of the file.

**Comment by aflatt** [comment]
FWIW I would also love it if fugitive had this feature.

The Visual Studio git plugin does basically this, and I find it incredibly useful for code reviewing a patch. I believe the tortise git client also does something like this as well.

**Comment by ekryyn** [comment]
+1 I would use it every day for the same usecase : code reviews

**Comment by mujz** [comment]
+1

**Comment by sudavid4** [comment]
I also miss this a lot. Mostly to diff between branches(normally before push or merge back into master)
I wrote a little bit of code that work's well enough for my needs. It loads a preview window with the result of 'git diff $branchname --name-status' and does a (side by side) Gdiff between branches for file under cursor on `gd`. It's pretty rudimentary code but maybe someone else will have use for it.
call it with `GDiffBranch master` - or whatever other branch or commit you'd like
```vim
function! DiffFile()
    let winheight = winheight(winnr())
    let branchname=b:branchName
    let filename = substitute(getline('.'), '^\w*\s*\(.*\)', '\1', '')
    only
    wincmd s
    execute 'resize '.winheight
    wincmd j
    execute 'edit '.filename
    execute 'Gdiff '.branchname
endfunction
function! GDiffBranch(branchName)
    let tmpfile = tempname()
    execute 'pedit '.tmpfile
    wincmd P
    let b:branchName=a:branchName
    nmap <buffer> q :q<cr>
    execute 'silent read! git diff --name-status '.a:branchName
    normal! ggdd
    resize 12
    setlocal nomodifiable
    nmap <buffer> gd :call DiffFile(GetFileName())<cr>
endfunction
command! -nargs=1 GDiffBranch call GDiffBranch(<q-args>)
```

**Comment by robertocarta** [comment]
+1

**Comment by tpope** [comment]
Yes, #132 is the issue to end all issues regarding this.
