### ISSUE TITLE
Keep .git/tags in tags-option while in a git submodule.

### ISSUE THREAD

**Issue by tbelaire** [tpope/vim-fugitive#426]
I've adapted your convention to put tags files in .git/tags, ([thanks!](http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html)), and almost everything works great, except that fugitive doesn't look in there when in a submodules.
Currently, when editing a file in `submodule_name`, `tags=...,.git/modules/submodule_name/tags,...` (not mentioning the language specific ones), but it'd be great if in addition to that, I could also have `.git/tags` as a less specific tags file to fall back upon if it can't locate that file.

**Comment by tpope** [comment]
I have decided I will be dropping this entire feature.
