### ISSUE TITLE
Can't run :Gcommit on Windows 7 with PowerShell

### ISSUE THREAD

**Issue by tbrosnan** [tpope/vim-fugitive#435]
I'm seeing the following error message "Can't open file C:/.../Appdata/Local/Temp/VILA140.tmp". That temporary file doesn't appear to exist.

I am using GVim 7.4, running :Git --version shows "git version 1.8.3.msysgit.0".

**Comment by justinmk** [comment]
Does anyone have `set shell=powershell` working with Vim+fugitive at this point?

@Konfekt `let &shellpipe='| Out-File -Encoding UTF8 %s'` seems to break things like `:r!ls` (which works with `shellpipe=| shellredir=>`).

**Comment by dragon788** [comment]
@justinmk I've been having many failures with Vim+PowerShell as my working combo, which makes me really sad as I need to work in PowerShell for work, and I'd prefer to use Vim to do so, but these failures mean I probably need to use PowerShell and fall back to cmd.exe as the Vim shell and pass /c powershell -Command to do anything. :-1:

**Comment by justinmk** [comment]
@dragon788 I use `co!` mapping to toggle powershell on/off: 

https://github.com/justinmk/config/commit/bb1469f870f0a9a8613802513ff5acdf1e1e19fe#diff-4e12c6a37ff2cbb2c93d1b33324a6051R493

Yes, this sucks.

**Comment by dragon788** [comment]
Interestingly, I seem to have less issues with it failing once I disabled
the solarized plugin. I was seeing these failures when using vim plug to
install or update plugins in Windows.

At first I thought it was some of my symlinks causing issues, but I went
through and unmade and remade them and was able to reproduce the issue in
all my various iterations, but as soon as I removed solarized and cleared
out my plugins it worked fine.

I may need to switch to another theme and see if it is a particular issue
there or if it is reproducible depending on the plug-in list.

I did set up the mapping and it does seem to help in some cases, so I'll
have to see about testing both ways.

Apologies Tim, I do like a pathogen but experiment from time to time.

**Comment by Konfekt** [comment]
There is vim-flattened as a stripped down alternative to solarized.

**Comment by tpope** [comment]
How well does PowerShell play with Vim jobs? Been thinking of using jobs to make `:Gstatus` snappier and could see rolling it out for everything if it works out well.

**Comment by Konfekt** [comment]
As I was just looking at https://github.com/janlazo/dotvim8/blob/5cfc40a9c7fd2723bf5d23cea1a046e02e96d7e1/autoload/dotvim8.vim#L131 when you asked about it, perhaps @janlazo could answer that question.

**Comment by tpope** [comment]
It has just occurred to me that PowerShell is only relevant in the `[&shell, &shellcmdflag, cmd]` case. Mind you, this is a case I care very much about because it's the easiest to transition to.

**Comment by janlazo** [comment]
@Konfekt Check https://github.com/janlazo/dotvim8/blob/master/after/ftplugin/ps1.vim on how I use powershell for keyword search.

**Comment by tpope** [comment]
Does `|` in PowerShell pipe stdout and stderr or just stdout?

**Comment by janlazo** [comment]
@tpope stdout

**Comment by tpope** [comment]
Thanks @janlazo.

Fugitive assumes that `system()` and friends capture stderr, so my guess is all error handling is broken with PowerShell. `:Gcommit` needs to capture stdout and stderr separately even for its success case, is that even possible with PowerShell?

**Comment by tpope** [comment]
No longer using `:!`, is this working now?

**Comment by thekpaul** [comment]
Same problem appears for me, seems to say that `env` is not a recognised cmdlet, etc. when the command `env GIT_EDITOR=false git commit ...` is called.

(Windows 10, Powershell 5.0 used in `nvim-qt`)

**Comment by tpope** [comment]
Try `set shellcmdflag=\ -Command` (with the leading space) and see if that fixes it.

**Comment by thekpaul** [comment]
Fixed it, thanks. :D

**Comment by Konfekt** [comment]
@tpope Is the leading white space for the same reason (to circumvent a faulty shell detection by Vim) as that given here: https://github.com/tpope/vim-fugitive/issues/435#event-2699501243 ?
