### ISSUE TITLE
the `<C-R><C-G>` cmapping conflicts with vim's default `<C-R>` cmapping

### ISSUE THREAD

**Issue by yuex** [tpope/vim-fugitive#437]
According to the help file of vim-fugitive

> `<C-R><C-G>`            On the command line, recall the path to the current
>                                    object (that is, a representation of the object recognized by |:Gedit|).`

But this will cause  a annoying delay when using the default cmapping `<C-R>`. Seems it's inappropriate to use `<C-R>`. Use another prefix should solve this problem.

**Comment by tpope** [comment]
You can set `g:fugitive_no_maps` if you positively can't stand this.
