### ISSUE TITLE
Hyphen not getting properly mapped or overridden

### ISSUE THREAD

**Issue by vendion** [tpope/vim-fugitive#442]
On the git status buffer in vim-fugitive, pressing the hyphen key does not toggle the status of a file instead it just moves the cursor up a line.  Calling `:map -` returns that no mapping found for that key.  Scanning through the source for this plugin I did not see a way to redefine this mapping in my vimrc, is there another way I can make sure this is set?

**Comment by tpope** [comment]
If this is still happening, report back with both `verbose nmap -` and `verbose nmap o`.
