### ISSUE TITLE
dp in Gstatus after `-` opens buffer in Gstatus buffer

### ISSUE THREAD

**Issue by ainformatico** [tpope/vim-fugitive#448]
## Facts:

Sounds kind of tricky, but it's easy:
1. `Gstatus`
2. on a candidate do `dp`
   - it replaces a buffer with the patch
3. go back to the `Gstatus` buffer and press `-` on a candidate
4. repeat step 2
   - in this case it opens the patch in the same window of the `Gstatus`, so you lose the `Gstatus` window. And yo still have the previous patch visible in the other buffer.
## Should:

do not open the patch in the `Gstatus` window.

**Comment by tpope** [comment]
Should be fixed because the `'previewwindow'` shenanigans have been replaced with a much more robust system.
