### ISSUE TITLE
:Gstatus needs to accept options and pathspec

### ISSUE THREAD

**Issue by Ferenc-** [tpope/vim-fugitive#467]
Currently Gstatus doesn't accept any extra characters "E488: Trailing characters".
On large repositories without the -uno option and pathspec, even the CLI git status is painfully slow, not to mention Gstatus... 
So Gstatus needs to accept options and pathspec, otherwise it remains unusable on large repositories.

**Comment by lxcode** [comment]
At least in modern git, it's ```git config status.showUntrackedFiles no```, rather than ```false```.
