### ISSUE TITLE
Gdiff without focus change in Gstatus

### ISSUE THREAD

**Issue by jreybert** [tpope/vim-fugitive#476]
When I want to review all the changes in my project within vim, I like to go through modified files with Gstatus. On each file, I press D (:Gdiff), but the focus goes on fugitive diff window.

A new key map (like V for view?) which does a Gvdiff without moving focus, staying in Gstatus window would be great!

**Comment by kiryph** [comment]
You could use following modified mappings (http://vi.stackexchange.com/a/8721/1292)

```
diff --git a/plugin/fugitive.vim b/plugin/fugitive.vim
index 805518a..f0120f8 100644
--- a/plugin/fugitive.vim
+++ b/plugin/fugitive.vim
@@ -14,6 +14,10 @@ endif

 " Section: Utility

+function! s:focus_preview()
+  call feedkeys("\<c-w>P")
+endfunction
+
 function! s:function(name) abort
   return function(substitute(a:name,'^s:',matchstr(expand('<sfile>'), '<SNR>\d\+_'),''))
 endfunction
@@ -2552,12 +2556,12 @@ function! s:BufReadIndex() abort
     nnoremap <buffer> <silent> cc :<C-U>Gcommit<CR>
     nnoremap <buffer> <silent> cva :<C-U>Gcommit --amend --verbose<CR>
     nnoremap <buffer> <silent> cvc :<C-U>Gcommit --verbose<CR>
-    nnoremap <buffer> <silent> D :<C-U>execute <SID>StageDiff('Gdiff')<CR>
-    nnoremap <buffer> <silent> dd :<C-U>execute <SID>StageDiff('Gdiff')<CR>
-    nnoremap <buffer> <silent> dh :<C-U>execute <SID>StageDiff('Gsdiff')<CR>
-    nnoremap <buffer> <silent> ds :<C-U>execute <SID>StageDiff('Gsdiff')<CR>
-    nnoremap <buffer> <silent> dp :<C-U>execute <SID>StageDiffEdit()<CR>
-    nnoremap <buffer> <silent> dv :<C-U>execute <SID>StageDiff('Gvdiff')<CR>
+    nnoremap <buffer> <silent> D :<C-U>execute <SID>StageDiff('Gdiff')<Bar>exe <SID>focus_preview()<CR>
+    nnoremap <buffer> <silent> dd :<C-U>execute <SID>StageDiff('Gdiff')<Bar>exe <SID>focus_preview()<CR>
+    nnoremap <buffer> <silent> dh :<C-U>execute <SID>StageDiff('Gsdiff')<Bar>exe <SID>focus_preview()<CR>
+    nnoremap <buffer> <silent> ds :<C-U>execute <SID>StageDiff('Gsdiff')<Bar>exe <SID>focus_preview()<CR>
+    nnoremap <buffer> <silent> dp :<C-U>execute <SID>StageDiffEdit()<Bar>exe <SID>focus_preview()<CR>
+    nnoremap <buffer> <silent> dv :<C-U>execute <SID>StageDiff('Gvdiff')<Bar>exe <SID>focus_preview()<CR>
     nnoremap <buffer> <silent> p :<C-U>execute <SID>StagePatch(line('.'),line('.')+v:count1-1)<CR>
     xnoremap <buffer> <silent> p :<C-U>execute <SID>StagePatch(line("'<"),line("'>"))<CR>
     nnoremap <buffer> <silent> P :<C-U>execute <SID>StagePatch(line('.'),line('.')+v:count1-1)<CR>

```

**Comment by jreybert** [comment]
Finally, I resolved this issue with [vimagit](https://github.com/jreybert/vimagit) :)

I still use fugitive for everything git else than staging and commit: Gdiff, Gblame...

**Comment by tpope** [comment]
Is there still demand for this with the new inline diffs available?

**Comment by danielo515** [comment]
Seems that I'm late to the party, but yes, this is exactly the workflow that I am looking for. Is there a way of customizing it so it behaves that way?

**Comment by tpope** [comment]
The only supported method for customization is to define your own maps, perhaps in `after/ftplugin/fugitive.vim`. My recommended implementation strategy would be to call the original maps (e.g., `:normal dd`) and then refocus the status window afterwards (`wincmd p` would probably work).

**Comment by danielo515** [comment]
I was guessing if it would be possible to override default maps just for that buffer type. Do you have any example I can look at?

**Comment by tpope** [comment]
The `fugitive` file type is the relevant criteria. Something as simple as this might work, but I haven't tested:

```vim
nmap <buffer> Dd dd<C-W>p
```

**Comment by danielo515** [comment]
That almost worked perfectly. I use vertical splits, so the command was more like `dv<c-w>2h`.
There are some visual annoyances because the windows actually became active and the airline plugin reflects that, but that is not fugtive fault.

Thank you very much
