### ISSUE TITLE
Glog / Gdiff fail to work for anything beyond tag 1.1

### ISSUE THREAD

**Issue by benjumanji** [tpope/vim-fugitive#477]
Unless I have tags/v1.1 checkout out for every repo that I try to use the following error is shown when I run `:Glog`:

`Error detected while processing BufReadCmd Auto commands for "fugitive://**//[0-9a-f][0-9a-f]*":
fugitive: rev-parse 133fd7afd3e4cb44afdb1aeaefd4ac5953b0d151:src/GraphViz.hs: 0a572a1e10547c3f9909e6cdfdc6e99fc00c3c06
Press ENTER or type command to continue`

and if I `:Gdiff` I get nothing but blank (I assume because it can't parse the revision). I am using git 1.9.2 and vim 7.4 on (arch) linux. 

Any ideas?

**Comment by louwers** [comment]
Came across this too. Still a won't fix?

**Comment by tpope** [comment]
I won't be spending time on it but you're welcome to try.
