### ISSUE TITLE
Is there a way to commit without quiting :Gstatus window?

### ISSUE THREAD

**Issue by ccll** [tpope/vim-fugitive#480]
My typical workflow is:
1. ':Gstatus' to bring up status window
2. 'dd' on changed files to see the diff
3. ':diffput' to stage hunks
4. Repeat step 2 and 3 until I got enough hunks to commit
5. 'cc' in the status window to bring up commit window
6. Enter commit message and ':wq' to execute the commit

**The ':wq' will also close ':Gstatus' window, so I have to reopen it in order to commit the rest of changes.**

This is inconvenience, is there any way to avoid this?

**Comment by prognostikos** [comment]
@tpope I just updated fugitive, and this feature totally made my day. I spend more time using vim with tons of your plugins than almost any other software, and I really appreciate the thoughtfulness that you bring to your work. You rock! :metal:
