### ISSUE TITLE
[n00b] Ggrep to search just in the current directory

### ISSUE THREAD

**Issue by prat0318** [tpope/vim-fugitive#481]
I tried `:Ggrep search_key .` but still it starts searching from the git root. Even `:Git grep search_key .` starts searching from root. How can i just search in the current directory?

**Comment by rryk** [comment]
You probably meant `:Ggrep search_key -- sub/directory`. Note that `sub/directory` is a path relative to the repository root, so if you are deep down the hierarchy, you'll have to do a lot of typing :-)

**Comment by rryk** [comment]
Btw, would you be against me adding a flag to control this and sending you a pull request?

**Comment by tpope** [comment]
I'd be more open to adding some special casing if `.` is passed as an argument. I don't know how hard that would be to implement.
