### ISSUE TITLE
fugitive: error: pathspec 'bla' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by paulepanter** [tpope/vim-fugitive#497]
With the directory structure and files below, running `vim bla` from inside the directory `test`, making a change and then `:Gcommit %` an error is returned.

```
    fugitive: error: pathspec 'bla' did not match any file(s) known to git.
```

It looks like the full path is not passed to Git.

```
    $ cd /tmp/
    $ mkdir f
    $ cd f
    $ git init
    Initialized empty Git repository in /tmp/f/.git/
    $ mkdir test
    $ cd test/
    $ touch bla
    $ echo 1 > bla
    $ git add bla
    $ git commit -a
    [master (root-commit) 1fc2027] bla: test
     1 file changed, 1 insertion(+)
     create mode 100644 test/bla
    $ vim test
```

**Comment by markstos** [comment]
Considering these been no follow-up from the OP since 2014, this issue can be closed.

**Comment by tpope** [comment]
I've definitely made some changes to to directory handling so I agree.
