### ISSUE TITLE
Vim-Fugitive commands in VimFiler buffers 

### ISSUE THREAD

**Issue by jonmorehouse** [tpope/vim-fugitive#502]
Is there any way to access Fugitive commands from within Vimfiler windows? It would be nice to be in a directory view and commit the project.

From my brief looks through the code, it looks like this should work. I notice there is some NerdTree autocmds, but I don't see what that would be needed for vimfiler as it looked like it was just for VimEnter events.

**Comment by tmsanrinsha** [comment]
```vim
autocmd FileType vimfiler
\   autocmd CursorMoved <buffer> let b:git_dir = '' | call fugitive#detect(vimfiler#get_filename())
```
This code makes fugitive commands accessible in Vimfiler.
But after using Gitv command of gregsexton/gitv in Vimfiler window and quiting gitv, opening file in Vimfiler window fails.

**Comment by tpope** [comment]
VimFIler claims to be deprecated, I think this particular request is moot.

More generally, calling `FugitiveDetect()` on the appropriate event is indeed the way to go. But `CursorMoved` is a terrible event that fires, well, every time the cursor moves. You don't want to do IO every time the cursor moves.
