### ISSUE TITLE
Update vim-gitgutter via `:GitGutterAll` after vim-fugitive actions

### ISSUE THREAD

**Issue by autochthe** [tpope/vim-fugitive#503]
This is probably something with a simple workaround, but it would be useful behavior to have as gitgutter and fugitive are probably the most popular git extensions for vim.

Simply, it would be useful if vim-gitgutter updated after any vim-fugitive actions.  This can be done by the command `:GitGutterAll`, which could be called after any fugitive actions if both plugins are installed.

See https://github.com/airblade/vim-gitgutter/issues/182

**Comment by tpope** [comment]
Perhaps `:Gwrite` should also trigger `BufWritePost fugitive://...` for the relevant index buffer, which would be easy to target. That makes sense because if you call `:w bar` from `foo`, `BufWritePost bar` gets triggered.

**Comment by airblade** [comment]
@tpope That would be great.

**Comment by tpope** [comment]
Oh, the behavior in https://github.com/tpope/vim-fugitive/commit/57afba5bdd49b59d57485f90aa0cf3f3a6c47f63 is exactly what I was suggesting. I assume your objection to `BufWritePost` is you didn't want to trigger on *all* writes, but targeting it with `autocmd BufWritePost fugitive://*//0/*` ought to do the trick.

**Comment by airblade** [comment]
Yes, that's right.

**Comment by thisisrandy** [comment]
Re: a parallel issue on the gitgutter repo (airblade/vim-gitgutter#666), it seems this is not completely resolved. `:Gwrite` plays nicely with gitgutter, but stage/unstage actions via fugitive are not reflected in gitgutter.

As discussed on the other issue, a close approximation to actual syncing would be something like:
```vim
autocmd BufLeave */.git/index call gitgutter#all(1)
```
i.e. refresh gitgutter whenever we leave the fugitive window. However, `*/.git/index` seems a little clunky. @airblade suggested
```vim
autocmd BufLeave fugitive://* call gitgutter#all(1)
```
but this unfortunately does not work. My vim-foo isn't up to the task here. How would one go about matching the fugitive filetype in an autocmd like the one above?

**Comment by tpope** [comment]
The [recently introduced](ab26e9fdb328cc351933f8d6178178e8ce5c8381) `User FugitiveChanged` event should be perfect for this.

**Comment by thisisrandy** [comment]
Wonderful. Looks like @airblade has already made a commit. Thanks to you both.
