### ISSUE TITLE
Support for `:Glog -- <relative path>`?

### ISSUE THREAD

**Issue by ackalker** [tpope/vim-fugitive#504]
When working with large projects like the Linux kernel, I often want to change to a directory, then see a log of commits which touch a certain subtree.

In the shell I would do it like so:

```
$ cd linux/drivers/media/usb
$ git log -- .
```

In fugitive, I haven't found an easy way to do this.
After navigating to a directory using Netrw, I can view the revision history for a tree by doing `:Glog`, but that shows me tree objects, not commits. I still need to type 'C' to go to the corresponding commit. This becomes tedious when stepping through a long list of revisions using `:cnext` and `:cprevious`.
Also, `:Glog -- .` doesn't work as I had expected: it lists the commit history for the entire repository.

I've currently found two options to work around this, but neither is very practical in the long run.
The first option: navigate to a directory using Netrw, open a random file in that directory, then use `:Glog -- %:h`
The second option: navigate to a directory using Netrw, type 'c' to make that directory current (important!), then run `:execute "Glog -- ".getcwd()`

It would be nice if fugitive commands like `Glog` would support paths relative to the current directory, either the local directory for a file browser window or the current working directory.

**Comment by tpope** [comment]
Four years later I've untangled the mess enough to make this possible. Use `:Glog ./path` to reference a file in the working directory and `:Glog path` to reference a file in the root of the work tree.

This works by looking for arguments that start with `./` (or a bare `.`) and rewriting them, which makes it impossible to pass a literal `.` argument. If that becomes a problem in practice I may have to roll this back.
