### ISSUE TITLE
Gdiff is the same as Gsdiff

### ISSUE THREAD

**Issue by ldong** [tpope/vim-fugitive#508]
Current version 6/24/2014
When I use `Gidff`, it splits the window vertically just like `Gsdiff`.

**Comment by dguitarbite** [comment]
This issue occurred again, I added the ``set diffopt+=vertical`` and this solves the issue, this should solve similar issues for every split scenario even with other plugins unless I would really need horizontal split ;).

**Comment by jalberto** [comment]
@tpope using latest version on nvim I get horizontal splits even if `set co` -> 211 (`textwidth` reports to be 0 in Gdiff)
-

**Comment by tpope** [comment]
Here is the logic if you want to try to debug it. The `count` parameter is the number of windows and will be `3` in a merge conflict and `2` otherwise.

https://github.com/tpope/vim-fugitive/blob/c118dabb89b6e7e42383d4cf6f426e53bb45279c/autoload/fugitive.vim#L1869-L1878

**Comment by dtabell** [comment]
@tpope The above snippet does not seem to explain why I see a different split depending on the file type. When I Gdiff a .f file, I see a vertical split; but when I Gdiff a .f90 file, I see a horizontal split. Why?

**Comment by tpope** [comment]
One reason might be `’textwidth’`.

**Comment by Lattay** [comment]
@dtabell Hello, just had the same problem, the reason is probably that by default you have `textwidth` at 80 for F70 and at 150 or something for F90.
