### ISSUE TITLE
:Gwrite to take range as an argument

### ISSUE THREAD

**Issue by rgrinberg** [tpope/vim-fugitive#514]
I use `vim-gitgutter` which shows me the diff from the index in the buffer itself. It would be great if I could stage a selection with `Gwrite` inside the buffer itself.

P.S. I know vim-gitgutter allows you to stage hunks but I'd rather stage selections.

**Comment by airblade** [comment]
@rgrinberg What do you mean by staging selections?  Maybe it's something we could add to vim-gitgutter.
