### ISSUE TITLE
Switch from `git web--browse` to `netrw#NetrwBrowseX` broke :Gbrowse

### ISSUE THREAD

**Issue by iamvery** [tpope/vim-fugitive#518]
A [recent commit](https://github.com/tpope/vim-fugitive/commit/585fcc8a9b2b12d5dd811b94fa969d5e3ba0d192) has caused the `:Gbrowse` command to stop working in my environment.
## The symtom

When I attempt to `:Gbrowse`, the url flashes quickly in the status bar and nothing further happens.
## What I've done

I verified that the problem still occurs when fugitive and pathogen are the only plugins loaded and my config is vanilla.

Per the discussion in #108, I verified that `git web--browse http://google.com` indeed opens the browse both from bash and in vim.
## System information

Also, as the may be helpful, here are some env variables referenced in that issue:

```
● master ~ » echo $SECURITYSESSIONID
[redacted, but not blank]
● master ~ » echo $TERM_PROGRAM
iTerm.app
● master ~ » sw_vers
ProductName:    Mac OS X
ProductVersion: 10.9.3
BuildVersion:   13D65
● master ~ » bash --version
GNU bash, version 3.2.51(1)-release (x86_64-apple-darwin13)
Copyright (C) 2007 Free Software Foundation, Inc.
```

My default browser is Google Chrome (currently) Version 35.0.1916.153

**Comment by koreymacdougall** [comment]
installing xdg-utils fixed a broken :Gbrowse for me.

I'm on arch linux running xfce4 desktop environment

I'm not sure this comment is in the correct place, but following @dhose's workaround, above,  {which didn't work on my system}, led me eventually to research xdg-utils and xdg-open
