### ISSUE TITLE
Shorten result list and buffer names

### ISSUE THREAD

**Issue by phmarek** [tpope/vim-fugitive#519]
If I do `Ggrep word branch`, the result list currently includes `$PWD/.git//<commit-id>/<path>`, which gets quite long. (With `tput cols` == 149 some buffer names get already wrapped.)

Is there a way to make the _displayed_ paths shorter (ie. the `:cl` list)? I understand that the buffer names have to be as precise as possible, but could at least `:cl` use some abbreviation?

Cutting the commit IDs to 8 characters, and/or using `$PWD`, would give me a reduction of 65 characters. (Ie. `fugitive:///$PWD/.git/12345678/<path>`).
I understand that this would break if the user does `:cd`.

Alternatively, fugitive could hold a global hash of abbreviation-to-WC; eg. the last component before `.git` would be a good choice, I guess.

**Comment by tpope** [comment]
Vim recently got a "module" quickfix item to provide a display alternative, and this is now in place.
