### ISSUE TITLE
enhanced git log/diff feature request

### ISSUE THREAD

**Issue by Silex** [tpope/vim-fugitive#52]
Hello,

First of all, thanks for this awesome plugin!

There's one thing that I find missing in it for it to be supazomggreat tho, the ability to browse your git tree like `gitk` does.

I think of something pretty simple: some command, like `:Gitk`, which would display `git log --graph --oneline --all` in a `:split` window. When you select one of the commit, another window appear with the list of modified files of that commit. Finally, when you select one of the file, a `vimdiff` window shows what was modified.

I think you probably can rip most of the `Gundo` plugin, which does pretty much that: visualize file differences along a timeline.

As this plugin is pretty file-centric, maybe we could start by a simple `:Ghistory` which would create a split with the commits concerning that file, and when you move over them it shows a vimdiff below. This would allow to enhance with stuffs like "revert to this commit", etc.

Tell me what you think :)

**Comment by TamaMcGlinn** [comment]
Just in case someone stumbles across this, vim-extradite still works excellently together with fugitive, but gitv was abandoned a while back. In my opinion, [vim-flog](https://github.com/rbong/vim-flog) fills the gap great; it integrates very nicely with fugitive.
