### ISSUE TITLE
Gdiff does an horizontal split instead of vertical

### ISSUE THREAD

**Issue by PVince81** [tpope/vim-fugitive#523]
This is on master (f55b1feda7e26ce4ee8867c7776a0102843f13b2)

`Gdiff` command does an horizontal split instead of vertical.

I see in the commit history that `Gsdiff` is supposed to be the command to split the window horizontally, but `Gdiff` also does so. It seems now I need to type `Gvdiff` for a vertical split.

Has the default be changed or is this a bug ? Is this configurable without resorting to aliases ?

**Comment by froody** [comment]
Add set `diffopt+=vertical` to your vimrc for those who don't like to click links

**Comment by tpope** [comment]
The correct summary is "use `:Gvdiffsplit`, fuck `diffopt` imo.

**Comment by ariel-frischer** [comment]
`:Gvdiffsplit!` with the additional exclamation mark `!` worked for me.
