### ISSUE TITLE
Gstatus is broken on windows 7

### ISSUE THREAD

**Issue by kirtgoh** [tpope/vim-fugitive#525]
hi, 
:Gstatus and :Gcommit are broken when doing :Gstatus, it says W13: Warning: File ".git\index" has been created after editing started and offers me "Ok" or "Load file".

**Comment by chigur** [comment]
Has anybody found what the problem is?.

**Comment by justinmk** [comment]
This is the same issue as https://github.com/tpope/vim-fugitive/issues/690, which has more details.

**Comment by chigur** [comment]
@justinmk no file named `.git/index.lock` exists in my case.

**Comment by justinmk** [comment]
Ok, my mistake.

**Comment by chigur** [comment]
I tried changing things around in my `vimrc` file and found that a snippet in it required by `YouCompleteMe` that was causing the problem. I think everybody using `YCM` on windows faces the [R6034](https://github.com/Valloric/YouCompleteMe/issues/1891) error and to fix it you have to include the following snippet of python in the `vimrc` file. After much trial and error I think the `os.environ['PATH'] = ';'.join(path)` line is causing the problem but I can't figure out what it has to do with the current issue.

```python
python << EOF
import os
import re
path = os.environ['PATH'].split(';')

def contains_msvcr_lib(folder):
    try:
        for item in os.listdir(folder):
            if re.match(r'msvcr\d+\.dll', item):
                return True
    except:
        pass
    return False

path = [folder for folder in path if not contains_msvcr_lib(folder)]
os.environ['PATH'] = ';'.join(path)
EOF
```
@kirtgoh do you have `YouCompleteMe` installed too?.

**Comment by ykDu-CGCL** [comment]
I am facing exactly the same problem.
Is there a solution?

**Comment by Chiel92** [comment]
I had a similar issue for another plugin, and for me the cause was that the script mentioned by @chigur removed the system32 folder from the path. I currently use the following script.

```
if has("win32") && has("gui_running")
python << EOF
import os
import re
path = os.environ['PATH'].split(';')

def contains_msvcr_lib(folder):
    try:
        if 'system32' not in folder:
            for item in os.listdir(folder):
                if re.match(r'msvcr\d+\.dll', item):
                    return True
    except:
        pass
    return False

path = [folder for folder in path if not contains_msvcr_lib(folder)]
os.environ['PATH'] = ';'.join(path)
EOF
endif
```

You could fiddle around and see if re-including a folder solves the issue.

**Comment by tpope** [comment]
If any one has an issue that can be reproduced without a weird `contains_msvcr_lib` script in the mix let me know.
