### ISSUE TITLE
# in file name breaks D, dv, and ds from :Gstatus window

### ISSUE THREAD

**Issue by gfixler** [tpope/vim-fugitive#533]
Filenames like `#foo` and `foo#bar` will diff fine through `:Gdiff` and `:Gvdiff`, but using `D`, `dv`, and `ds` from the `:Gstatus` window shows two new files: `fugitive:///blahblah/.git//0/\#foo` and `"\#foo" [New file]` (it's not new; it's modified). Tested against latest - 90ee6fb - on 64-bit Linux.

**Comment by tpope** [comment]
Works on latest.
