### ISSUE TITLE
Failure to open Browser window with Github Link for highlighted or selected file

### ISSUE THREAD

**Issue by Blue-Dog-Archolite** [tpope/vim-fugitive#536]
So I am on linux, Fedora to be spicific, and vim-fugitive no loger works. It works when using pathogen but not when using vundle. 

Fedora 20
gVim 7.4.179
All plugins are up to date according to 

```
 ag.vim
 matchit.zip
 splitjoin.vim
 syntastic
 tagbar
 tlib_vim
 vim-abolish
 vim-coffee-script
 vim-fugitive
 vim-less
 vim-rails
 vim-ruby
 vim-vroom
 Vundle.vim
 wildfire.vim
```

`:Glog` returns 

```
:!git --git-dir=/home/thief/dev/liveworld/leatherman/.git --no-pager log --no-color '--pretty=format:fugitive:///home/thief/dev/liveworld/leatherman/.git//%H/lib/omniauth/stratigies/liveworld_pey
ote.rb::%s' -- lib/omniauth/stratigies/liveworld_peyote.rb  2>&1| tee /tmp/v3djNkl/26  
```

as i would expect. However `:Gbrowse` flashes what appears to be the correct url for the file and then .... nothing. 

Suggestions on how to help debug this one?

**Comment by araslanov-e** [comment]
@dohse https://superuser.com/questions/386646/xdg-open-url-doesnt-open-the-website-in-my-default-browser/407675

**Comment by igbanam** [comment]
What's the equivalent for Mac users? I find `:Gbrowse` does not open the url. I do see with `messages` that the URL was well formed though. I think this is just an opening issue

p.s: could we have something which just copies the URL to the clipboard?

**Comment by araslanov-e** [comment]
@igbanam use method `:Gbrowse!`

**Comment by igbanam** [comment]
That was quick. Was coming here to say I had figured it out. Thanks!!!
