### ISSUE TITLE
`:[range]Gblame [flags]` to show in buffer?

### ISSUE THREAD

**Issue by felixSchl** [tpope/vim-fugitive#539]
Currently running `:[range]Gblame [flags]` just prints the results in the command buffer on unix and in the external shell on windows. So before I can use vim again, I have to clear them. Is this the intended behavior? Would it possible to show the results in the same buffer where `:Glame [flags]` results are shown?

**Comment by tpope** [comment]
It was a long journey but this is basically what the current implementation has evolved to, except it uses a horizontal split rather than the vertical scrollbound one.
