### ISSUE TITLE
Add support for core.commentchar configuration

### ISSUE THREAD

**Issue by schmidt** [tpope/vim-fugitive#547]
Git 1.8.2 allows setting a configuration called `core.commentchar` ([see announcement](http://article.gmane.org/gmane.linux.kernel/1443021)). This allows users to change the default `#` to something else, so that commit subjects may e.g. start with issue references.

It would be great if fugitive could change the syntax highlighting of commit messages accordingly.

**Comment by netzwerg** [comment]
+1 (I am using "|" as a comment char and `:Gstatus` becomes unusable)

**Comment by tpope** [comment]
Moot.
