### ISSUE TITLE
The default state of the quickfix window upon :Glog is … obtuse.

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [tpope/vim-fugitive#549]
I'm opening this due to @tpope's re-opening of #519; but that issue is about a specific situation involving `:cl`. I'd like to submit my :+1: towards some sort of prettification (using `conceal`, probably?) of what a new Fugitive user sees upon executing `:Glog`.

![screen shot 2014-09-23 at 7 21 14 am](https://cloud.githubusercontent.com/assets/200/4371749/2366d808-431c-11e4-97af-bc4d3df5efca.png)

**Comment by tpope** [comment]
I take insult at "obtuse", but this has since been changed.
