### ISSUE TITLE
Git blame output looks like an ugly rainbow

### ISSUE THREAD

**Issue by YorickPeterse** [tpope/vim-fugitive#550]
Currently fugitive adds a colour to Git commit hashes in the `:Gblame` output using the following code: https://github.com/tpope/vim-fugitive/blob/0374322ba5d85ae44dd9dc44ef31ca015a59097e/plugin/fugitive.vim#L2089

This in turn results in the following output for most of my projects: 
![screenshot - 290914 - 11 53 11](https://cloud.githubusercontent.com/assets/86065/4439956/d08eb586-47be-11e4-9165-3a002a5c7d61.png)

The extremely annoying problem here is that there doesn't seem to be a way for me to change this behaviour. I'd much rather use a single colour for my hashes. This _only_ happens when running in a GUI, in a terminal the colour of `Identifier` is used.

It would be really appreciated if either this behaviour can be disabled, or if the colours used can be changed to a fixed colour.

**Comment by mhartington** [comment]
My favorite feature of fugitive.

**Comment by john-kurkowski** [comment]
> My favorite feature of fugitive.

Hear hear. I'd actually like it in my terminal vim too. Maybe the compromise is to let the user configure Gblame colors on/off?

**Comment by john-kurkowski** [comment]
Oops, I learned from [this SO](http://stackoverflow.com/a/26327001/62269) that I can already get the rainbow in terminal vim with [CSApprox](https://github.com/godlygeek/csapprox).

**Comment by tpope** [comment]
`g:fugitive_dynamic_colors`

**Comment by YorickPeterse** [comment]
@tpope Thanks! That does the trick wonderfully!

**Comment by maricn** [comment]
If using terminal vim/neovim, you should have both https://github.com/godlygeek/csapprox installed and `let g:fugitive_dynamic_colors = 1` in your vimrc.
