### ISSUE TITLE
:Gpush - hidden ask for password and debug

### ISSUE THREAD

**Issue by davelsio** [tpope/vim-fugitive#556]
Thanks for this and your many other awesome plugins, they're the main reason I finally switched to vim!

I'm having a minor issue. It is likely due to some setting I have, since I remember it working properly in the past (some previous install, probably).

When I use :Gpush, GVim apparently freezes, but it is in fact waiting for password input. If I type it and hit enter the commit will be pushed (without the usual debug log) and Gvim will unfreeze.

This does not happen if I use :Git push; GVim's console will appropriately expand, showing the input password messages and the debug log when pushing.

Any ideas about what may be causing this?

Thanks in advance.

**Comment by jsatk** [comment]
For what it's worth, I came across this thread and it helped me. @tpope's suggestion to use `ssh-agent` proved to be what I needed to do. Github has a [lovely guide](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#adding-your-ssh-key-to-the-ssh-agent) on how to do exactly that. In short, after running `ssh-add ~/.ssh/id_rsa` Dispatch's `Gpush` works just dandy for me.

**Comment by mMontu** [comment]
I just came across this thread and found it very helpful. I had the exact same problem of `:Gpush` freezing under Linux. I wasn't aware of `:Git push`, which works very well -- maybe a note could be added to the documentation regarding `:Gpush` .
