### ISSUE TITLE
Add command `Gadd` for `git add`

### ISSUE THREAD

**Issue by paulepanter** [tpope/vim-fugitive#558]
Working on files with a conflict, I’d like to add that file to the Git index to resolve the conflict. Currently I mostly do `:Git add %` and then have to press enter.

If I am not missing something, could a command `Gadd` be added, which by default, that means with no arguments, adds the current file to the Git index?

**Comment by josh-gleason** [comment]
AFAIK the standard way git is used is to use `git add <file>`. IMO the fugitive command `:Gw` seems non-intuitively named, is there some justification for this naming convention that I'm missing? Is there a reason an alias can't be added with the more intuitive `:Gadd` naming convention?

**Comment by tpope** [comment]
#1057
