### ISSUE TITLE
Fugitive doesn't handle copied files

### ISSUE THREAD

**Issue by asheidan** [tpope/vim-fugitive#56]
Fugitive is unable to unstage a staged file with the following line in a :Gstatus buffer

```
#   copied:     apa.c -> bepa.c
```

This is probably due to the output from git is a bit different than standard.

The name of the file is bepa.c, and as can be seen in the output above git thinks that this file is a copy of another file (apa.c).

Using the latest version (as of 2011-04-22).

**Comment by tpope** [comment]
Moot on the new `:Gstatus`.
