### ISSUE TITLE
Add :Gwnext and :Gwprevious

### ISSUE THREAD

**Issue by glittershark** [tpope/vim-fugitive#560]
I like arglists. `vim $(git grep --name-only 'a thing')` is a common occurence on my command line. Vim has `:wn[ext]` and `wp[revious]` (alias `:wNext`) for writing then going to the next/previous file in the arglist. It'd be nice if fugitive had counterparts to both of these for `:Gwrite`

**Comment by tpope** [comment]
Discussion in #562.
