### ISSUE TITLE
Support viewing commits with --word-diff with coloring

### ISSUE THREAD

**Issue by tyll** [tpope/vim-fugitive#561]
Please make it possible to view commits with --word-diff enabled. Ideally additions/removals would be highlighted only by color for example like the output of

```
git show HEAD --color-words
```

This is especially useful when using git writing text files (documentation), because then whitespace changes might not matter as much but there might be a lot of changes line-wise if text is formatted to e.g. fit into 80 columns after words were changed.

**Comment by tpope** [comment]
With fresh eyes this sounds like it might be a request to adjust the display in `:Gedit commit`. Let's file this under #1109 if so.

**Comment by paulrougieux** [comment]
The command `:term git diff --word-diff` is useful when editing prose (markdown or latex files). I mapped it to this command:
```
" Display a word diff
command! Gwd term git diff --word-diff
```
It would be nice to have a similar output in the in line diffs when pressing `i` in the `fugitive-summary` buffer. Not sure if this is the same renderer as `:Gedit @`.
