### ISSUE TITLE
Arglist sync with :Gmove and :Gremove

### ISSUE THREAD

**Issue by stellarhoof** [tpope/vim-fugitive#565]
Hi
I use the arglist quite extensively to load a project's files there. Would it make sense on top of modifying the bufferlist for the commands above to modify the arglist as well?
Thanks

**Comment by tpope** [comment]
Seems to already be the case for `:Gmove`. I think *removing* an entry from the args list would be weird, no Vim built-in does that automatically as far as I'm aware.
