### ISSUE TITLE
Restore/maintain mappings in `:Git!` command output buffers

### ISSUE THREAD

**Issue by tommcdo** [tpope/vim-fugitive#566]
I have a common workflow that involves exploring recent commits. I'll start with `:Git! log`, then take advantage of the `<CR>` mapping to dive into an interesting commit. The problem is, when I jump back to the git output buffer (which is some file in /tmp) using `<C-O>`, the mappings are gone. I've found that `:edit` restores them, but it feels a little clunky.

Is there a reason the mappings don't persist without forcing a re-edit?

**Comment by tpope** [comment]
The way temp settings are applied now should make this impossible.
