### ISSUE TITLE
Set "norelativenumber" when diffing?

### ISSUE THREAD

**Issue by cowboy** [tpope/vim-fugitive#567]
I generally use `set relativenumber` but when doing `:Gdiff` (or variants) I'd like to have `norelativenumber` set. Is there a setting for this that I'm unaware of, or an `autocmd` I can use to set it?

**Comment by prophittcorey** [comment]
I'm also interested in this functionality for the same reason.

**Comment by tpope** [comment]
Worst case scenario, you could probably do this with an `OptionSet diff` autocommand.
