### ISSUE TITLE
Add a "magit like" commit mode: all git repository diffs in one buffer, with easy stage mapping

### ISSUE THREAD

**Issue by jreybert** [tpope/vim-fugitive#569]
Hi,

I don't know if such functionality introduction is possible in fugitive, or if it should be another vim plugin.

I often see colleagues use magit, and I understood recently what I like so much in magit.

It is simple: all diffs of the git repository appears in one buffer, with smart collapse rules. User can go through this buffer, stage some parts and commit at some moments.

It differs a lot of current stage/commit scheme of fugitive. I like the current scheme, but sometimes, when I have bunch of independent commits in multiple files, series of :Gstatus, D, ^Wj, [ do,]c ]*, ^Wk, C, blah, :wq can be boring, and I sometime feel git gui ( :'( ) more efficient for that.

I am not asking someone to implement such stuff. However, I am just wondering: is there already something like that for vim (with git-gutter, I still need to navigate through unstaged files)? if not, is it best to develop into fugitive, or in a fresh new plugin?

Anyway, fugitive is still an awesome plugin!

Jérôme

**Comment by juanibiapina** [comment]
I feel like I just want to press D and get the diff of all cached files, so I know what is going on the next commit. That would be like git status --cached, except inside vim. This is the part where Magit is better, although showing the whole diff all the time is just too much clutter.

**Comment by tpope** [comment]
Using `:Gstatus` to walk through diffs does sound unimaginably tedious. I mostly use `:Git add -p`. An inline diff with good folding and keybindings to stage hunks sounds vastly superior, and I'd totally be willing to completely toss out the old `:Gstatus` in favor of something like that. This is a pretty big task though, and I'm not even sure where to begin.

See #269 for a ranged `:Gwrite`.

**Comment by jreybert** [comment]
> An inline diff with good folding and keybindings to stage hunks sounds vastly superior, and I'd totally be willing to completely toss out the old :Gstatus in favor of something like that.

It actually exists, and it is called [vimagit](https://github.com/jreybert/vimagit)

I started it few months (or weeks?) after writing this issue. Give it a try, for the moment it does mainly that, but it does pretty well.

fugitive still stays under my fingers for all the rest: Gblame, Gdiff...

**Comment by tpope** [comment]
Okay, so step 1 is giving that a try...

**Comment by tpope** [comment]
Plenty of fine tuning left to do but the core functionality is complete.

**Comment by nhooyr** [comment]
This is an amazing feature, opened #1566 to get some awareness for it.
