### ISSUE TITLE
:Gcommit makes a terminal vim 'background' to flash

### ISSUE THREAD

**Issue by mkoskar** [tpope/vim-fugitive#579]
Running `vim` in a text mode inside terminal and doing `:Gcommit` will for a moment show the 'background' of the vim, resulting in disturbing flashing behaviour.

After a brief inspection it seems the reason being `:silent !command` execution pattern. This seems to be handled by Vim always the way that alternate screen into which Vim is doing its output is dropped for a period of execution. This can be demostrated by running e.g., `:silent !sleep 2`. Of course, subsequently alternate screen is put back and `:redraw!` has to be called.

With further testing (and help on freenode#vim) 'background' execution can be achieved by doing `:call system(...)` which seems to do the job. Is there any reason to not use this technique in `vim-fugutive`? I've came across described behavior only while doing `:Gcommit` though it seems `:call system(...)` could be used on other places too.

**Comment by tpope** [comment]
There are downsides to both `:!` and `:system()`, but as of right now, `:Gcommit` uses the latter.
