### ISSUE TITLE
Open fugitive buffer readonly

### ISSUE THREAD

**Issue by bogdan** [tpope/vim-fugitive#587]
Sometimes I am editing fugitive buffer by mistake and save it. It makes a git index corrupt.

Can we make it so that fugitive buffers always open readonly?

**Comment by QzCurious** [comment]
I'm not sure what corruption you mean. But sometime I accidentally did some change on a index file (which is opened by `:Gdiff`) and write it (by `:w` or `:update`). It makes me not able to rescue the stupid steps that I done. 

Still want a configurable variable that set readonly to index files and if there are operation like this.

**Comment by tpope** [comment]
No variable necessary, you could achieve this with an autocommand.

**Comment by kting28** [comment]
Any pointers / hints on how to achieve this? I too sometimes accidentally wrote the index file from ./git/... opened by `:Gdiff`  (e.g. I closed the actual file with the index file left open),would like to find a way to avoid it.

**Comment by tpope** [comment]
```viml
autocmd User FugitiveBlob setlocal readonly
```

This is a little imprecise because it also targets committed blobs, but those are already readonly so it doesn't matter.

**Comment by kting28** [comment]
Awesome this works. Thanks for the prompt reply! I added nomodifiable as well :)
`autocmd User FugitiveBlob setlocal readonly nomodifiable noswapfile`

**Comment by kting28** [comment]
hmm.. sorry to bring this up again, after a few  vim-fugitive updates the autocmd setting above no longer works. Unfortunately I'm not sure which version broke this. I also tried FugitiveObject to no avail. If you have no immediate clues, I can try a binary search.

**Comment by kting28** [comment]
Did some digging. The FugitiveBlob style autocommand was added in 397fb99 . The relevant code was changed in e91d17dd . If I go back to before this commit on 8/24 autocommand works. Please have a look?

**Comment by Sekhniashvi** [comment]
Yes, it's me

ოთხ, 6 ოქტ. 2021, 18:48-ში Kai Ting ***@***.***> დაწერა:
