### ISSUE TITLE
Invalid address with a given range in Gbrowse

### ISSUE THREAD

**Issue by petobens** [tpope/vim-fugitive#590]
If, for instance, I visually select some lines in  `fugitive.vim` and then run `:GBrowse` I get 

    E14: Invalid address

and the browser opens the `fugitive.vim` file at Github but not at the selected lines.  Note that when no range is given then the command works just fine and no error appears. 

I reproduced the error with the following minimal vimrc

    set nocompatible
    let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro/')
    let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')
    set runtimepath+=$DOTVIM/bundle/fugitive/

**Comment by tpope** [comment]
One step you might take to debug is put a similar URL (with a `#` anchor) in an empty buffer and press `gx` on it. This invokes netrw's URL opener, similar to what Fugitive does.

**Comment by petobens** [comment]
Pressing `gx` on an empty buffer with a similar URL works just fine. Can you provide further guidance? Thanks in advance!

**Comment by tpope** [comment]
Do you have a `:Browse` command? If so that would take priority over the netrw opener.

**Comment by petobens** [comment]
In my full vimrc I do have a `:Browse` command. However in the minimal vimrc (posted above) I don't have such command. I really don't understand why I get the `E14: Invalid address` error.

**Comment by tpope** [comment]
And there's no stacktrace?

**Comment by petobens** [comment]
This is the only thing I see:

![fugitive](https://cloud.githubusercontent.com/assets/2583971/5732967/0f450eec-9b7a-11e4-813d-6e5715113c4e.gif)

**Comment by tpope** [comment]
Looks like the echoed URL is incorrect. See if you still get the problem with `:'<,'>Gbrowse!` (which skips opening). The web browser may be a red herring.

**Comment by petobens** [comment]
With `Gbrowse!` the problem persists (I have no idea what's going on):

![fugitveproblem](https://cloud.githubusercontent.com/assets/2583971/5750154/7e6757d4-9c2f-11e4-8390-121ae6c149c3.gif)

**Comment by tpope** [comment]
With the browser ruled out I really don't know what could cause this, other than a Vim bug. The code https://github.com/tpope/vim-fugitive/blob/2c8461db084d205903a792a23163faa546f143c9/plugin/fugitive.vim#L2220-2229 prepares a statement to execute in a top level context. A top level error wouldn't have a stack trace, so it's the most likely culprit. You can try simulating what it's doing with

    :execute 'echomsg '.string('https://github/url#with-anchor')

**Comment by petobens** [comment]
Probably a Vim bug, if I ever find out what's going on I'll report it here. Thanks for the help!

**Comment by petobens** [comment]
I was using vim 7.4.559 and I updated to 7.4.567 and `Gbrowse` now works just fine. Maybe [Patch 7.4.565](http://ftp.vim.org/vim/patches/7.4/7.4.565) solved my problem. In any case sorry for all the noise and thanks again for the help and patience.
