### ISSUE TITLE
Invalid Range Error in latest vim

### ISSUE THREAD

**Issue by amadeus** [tpope/vim-fugitive#591]
When I use the hotkey `C` from a `:Gstatus` split to enter a commit message, I get the following error:
```
Error detected while processing function <SNR>44_Commit:
line   57:
E16: Invalid range: 3wincmd+
```

The commit split still comes up, but when I `:wq` on it to commit, nothing happens.

I have patches MacVim with patches 1-567, and there were some recent patches that I believe might have been related to this:

https://groups.google.com/forum/#!topic/vim_dev/pqDLkEFL-dc
https://groups.google.com/forum/#!topic/vim_dev/_Va04jSbKMs

It should be also noted, that if I just invoke `:Gcommit` everything works fine, it's only when using `C` from the `:Gstatus` window that I get the errors.

**Comment by tpope** [comment]
Does `:3wincmd+` fail by itself? Is that because there's not enough room to expand the window?

**Comment by amadeus** [comment]
It returns invalid range:

![example](https://dl.dropboxusercontent.com/s/9stqbuzz18ujsuw/Page.js_2015-01-08_13-29-06.png?dl=0)

**Comment by tpope** [comment]
In a `:Gstatus` window

**Comment by amadeus** [comment]
Seemingly same result/error.

![example](https://dl.dropboxusercontent.com/s/athyaiba1s5s9fl/index_2015-01-08_14-04-16.png?dl=0)

**Comment by tpope** [comment]
Given that there's adequate room for said resize, that sounds like a Vim bug to me?

**Comment by amadeus** [comment]
Yeah it probably is.

I just did `:wincmd+` and `:2wincmd+`, they both work, but `:3wincmd+` and even `:4wincmd+` throw the error.

**Comment by amadeus** [comment]
I've reported to the vim dev mailing list:

https://groups.google.com/forum/#!topic/vim_dev/LLTw8JV6wKg%5B1-25-false%5D

**Comment by ajh17** [comment]
This is now fixed apparently. I can successfully commit using the latest vim (patch 580).

refs #592
