### ISSUE TITLE
"E117: Unknown function: netrw#NetrwBrowseX" in Vim's master/tip

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-fugitive#594]
`netrw#NetrwBrowseX` has been renamed to `netrw#BrowseX` in https://github.com/vim-jp/vim/commit/9e29e82.

(around Vim's patch 567):

    -fun! netrw#NetrwBrowseX(fname,remote)
    -"  call Dfunc("NetrwBrowseX(fname<".a:fname."> remote=".a:remote.")")
    +fun! netrw#BrowseX(fname,remote)
    +"  call Dfunc("netrw#BrowseX(fname<".a:fname."> remote=".a:remote.")")

**Comment by tpope** [comment]
I guess the solution here is to check for both, with the annoying caveat that that requires ensuring `autoload/netrw.vim` has been loaded.

**Comment by harriott** [comment]
Is this why `:Gbrowse` ain't working for me on my Arch install (vim v7.4, patched to 580)?
If so, anything I can do about it locally, or just wait for a fix?

**Comment by tpope** [comment]
You can define a `:Browse` command.

**Comment by Keithbsmiley** [comment]
Here's a possible patch for this:

```diff
diff --git i/plugin/fugitive.vim w/plugin/fugitive.vim
index 65e6665..b61e49c 100644
--- i/plugin/fugitive.vim
+++ w/plugin/fugitive.vim
@@ -2225,7 +2225,11 @@ function! s:Browse(bang,line1,count,...) abort
     elseif exists(':Browse') == 2
       return 'echomsg '.string(url).'|Browse '.url
     else
-      return 'echomsg '.string(url).'|call netrw#NetrwBrowseX('.string(url).', 0)'
+      if has("patch-7.4.567")
+        return 'echomsg '.string(url).'|call netrw#BrowseX('.string(url).', 0)'
+      else
+        return 'echomsg '.string(url).'|call netrw#NetrwBrowseX('.string(url).', 0)'
+      endif
     endif
   catch /^fugitive:/
     return 'echoerr v:errmsg'
```

Seems like it will have to be a switch on the patch version since you can't check existence on an autoloaded function.

**Comment by Keithbsmiley** [comment]
Until something like this is added I wrapped this into a function:

```vim
if has("patch-7.4.567")
  function! s:Browse(args)
    execute 'call netrw#BrowseX('.string(a:args).', 0)'
  endfunction

  command! -nargs=* Browse call <SID>Browse(<q-args>)
endif
```

**Comment by tpope** [comment]
Not perfect because the new netrw can be installed on old Vim. But at least it addresses the common case. Thanks.

**Comment by elyscape** [comment]
@tpope Maybe something like this would work better?
```viml
if exists('*netrw#BrowseX')
  return 'echomsg '.string(url).'|call netrw#BrowseX('.string(url).', 0)'
else
  return 'echomsg '.string(url).'|call netrw#NetrwBrowseX('.string(url).', 0)'
endif
```

**Comment by tpope** [comment]
You would also need to ensure the autoload file has already been loaded. But yes, that's the right idea.

**Comment by elyscape** [comment]
Hmm, that's a good point.  You could force autoload like this:
```viml
try
  let dummy = netrw#fakevar
catch
endtry
if exists('*netrw#BrowseX')
  return 'echomsg '.string(url).'|call netrw#BrowseX('.string(url).', 0)'
else
  return 'echomsg '.string(url).'|call netrw#NetrwBrowseX('.string(url).', 0)'
endif
```

**Comment by tpope** [comment]
I would prefer the more explicit (and exception free)

```viml
if !exists('g:loaded_netrw')
  runtime! autoload/netrw.vim
endif
```

Wrap it up in a pull request and I'll merge.

**Comment by elyscape** [comment]
On it.

**Comment by dukedave** [comment]
Is it possible this patch would have failed to fix the `:Gbrowse` fugitive command *inside a commit* (i.e. first `:Gblame` then `o` a commit, then `:Gbrowse` with the commit focussed)?

**Comment by tpope** [comment]
Not in any way I can conceive of.

**Comment by tpope** [comment]
What does seem possible is you have a `:Browse` defined in some subset of circumstances that causes that.

**Comment by dukedave** [comment]
@tpope does this confirm anything?

    E492: Not an editor command: Browse

I'm actually on a fresh install of Ubuntu 14.04, and have solely added Janus. So if it is a conflict then perhaps it'd be better to track it there? I created an issue: carlhuda/janus#640

**Comment by tpope** [comment]
If you're running it immediately after you have the problem, then yes, that rules out my hypothesis.

**Comment by dukedave** [comment]
@tpope ah, looks like Janus was just running behind, fixed there, thanks!
