### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by wikimatze** [tpope/vim-fugitive#595]
Would it be possible to create a new release tag?

**Comment by tpope** [comment]
The most tedious part of cutting a release is putting together release notes. If you can make a first pass at that, it would make it much easier for me to prioritize. This holds true for all of my repos.

See the respective script pages on vim.org for examples. I usually start with

    git log --no-merges --reverse --pretty=format:%s. v<last-release>..

and then edit it pretty heavily. Things like changes to the readme and typo fixes should be deleted. Multiple commits around a single new feature should be combined. (For example, there are several commits in vim-speeddating extracting an autoload file, but that needs just one bullet point.)

**Comment by tpope** [comment]
Let me know if you start working on a repo so we don't duplicate effort.

**Comment by wikimatze** [comment]
Thanks for letting me know your thoughts about it and no I'm not working on a new repo. Here is the list of release notes:


* Support -L in :Glog errorformat
* Use -L to handle :Glog range
* Colorize hashes in blame
* Add `:Gmerge` and `:Gpull`
* Invoke `:Browse` if available to open URL.
* `:Gcommit` -v opens message in new tab.
* Add Provide `:Gpush` and `:Gfetch`.
* Browse handler API e API.


If this is okay, I can create it for your other repos as well.

**Comment by tpope** [comment]
Yes, that's the right idea. You can look at the final release I just pushed for further inspiration. My main request would be to be a bit less aggressive about deleting things, as it's much easier for me to delete them myself than to discover and undo your deletion. (There were a couple of things this round you omitted that I chose to include.)

**Comment by wikimatze** [comment]
Got it, I will take that in account for the other plugins.
