### ISSUE TITLE
toggling fugitive on/off

### ISSUE THREAD

**Issue by AlainPilon** [tpope/vim-fugitive#596]
Hi, how can I toggle Fugitive on/off? It does not play well with the Cadre plugin so I want a key to toggle it when I want to use the other plugin.

Thx

**Comment by edkolev** [comment]
I don't think there is much to toggle - fugitive provides some (very well though out) commands and a function which can use in your statusline. As powerful as fugitive is, I don't think there is anything to toggle.

**Comment by tpope** [comment]
Yeah whatever the problem, I don't think a toggle is a solution.
