### ISSUE TITLE
Running `:Gdiff`with rails-vim installed fails

### ISSUE THREAD

**Issue by teoljungberg** [tpope/vim-fugitive#598]
I'm not sure to which plugin I should report this error to, but it feels right doing it here.
If I run  `:Gdiff` in any file with rails-vim installed, I get the following error:

```
Error detected while processing function rails#buffer_syntax..<SNR>63_readable_projected..<SNR>63_buffer_name:
line    8:
E716: Key not present in Dictionary: path()),'\\ @!','/')) || f == ""
E116: Invalid arguments for function tolower(app.path()),'\\ @!','/')) || f == ""
E116: Invalid arguments for function s:gsub(tolower(app.path()),'\\ @!','/')) || f == ""
E116: Invalid arguments for function s:startswith(tolower(f),s:gsub(tolower(app.path()),'\\ @!','/')) || f == ""
E15: Invalid expression: s:startswith(tolower(f),s:gsub(tolower(app.path()),'\\ @!','/')) || f == ""
Press ENTER or type command to continue
```

Removing rails.vim makes the error not appear.

**Comment by johnideal** [comment]
:+1:, seeing the same here.

**Comment by tpope** [comment]
Any file meaning not just Rails app files? I can't reproduce, but there was a recent change to `rails#app()` that would explain it.

Check the value of `b:rails_root`.

**Comment by teoljungberg** [comment]
I don't have the slightest clue what might have caused the issue, but I'm on `HEAD` for both fugitive.vim and rails.vim and I don't see the problem anymore. Sadly.
I'll re-open the issue if the issue occurs again
