### ISSUE TITLE
:Gstatus mapping for git checkout --patch

### ISSUE THREAD

**Issue by sharplet** [tpope/vim-fugitive#600]
In addition to interactively staging and unstaging files, I like to be able to interactively discard changes in the working directory with `git checkout -p`. It would be lovely to have a mapping for this in the `:Gstatus` buffer to go along with the `p` mapping!

I imagine the mapping would have the same effect on both staged and unstaged files, as in either case you're applying changes from the index to the working directory.

Thanks for the great plugin! :sparkles:

**Comment by sharplet** [comment]
Actually come to think of it, it would make sense to have a non-interactive version as well! Just plain `:Git checkout <file>` to discard changes. This would go well with the `-` mapping.

**Comment by tpope** [comment]
The non-interactive form is available (undocumented) on `U`. I guess `u` could be the interactive form. (`U` is a terrible mnemonic, but I want to keep it far away from the `c` family of commit mappings.)

**Comment by sharplet** [comment]
u for unstage, right? Works for me ¯\_(ツ)_/¯

**Comment by thirtythreeforty** [comment]
@tpope do you have plans to implement this?  It would be great to have!

**Comment by tpope** [comment]
No plans, but I would entertain a pull request. I don't think it would be that hard to implement?

**Comment by thirtythreeforty** [comment]
It probably would not be.  If I have some time perhaps I'll look at it!

**Comment by Holzhaus** [comment]
I'd rather not use `u` for `git checkout -p` when `U` is the regular `git checkout`. In case you accidently have capslock on and you hit `u`, you lose all your worktree changes of that file. Hitting `U` is dangerous enough already. Why replace the `U` mapping with the patch version? In case you want discard the whole file you can still press `U` and then `a`.

**Comment by tpope** [comment]
`X` (the replacement for `U`) now operates at a diff level, providing the same functionality as `checkout -p`.
