### ISSUE TITLE
Commands not defined when opening via file-line plugin

### ISSUE THREAD

**Issue by pbrisbin** [tpope/vim-fugitive#602]
I'm not sure where this bug is, so I apologize if it's not in fugitive.

I've created a minimal reproducing repo here: https://github.com/pbrisbin/fugitive-bug, the following should show the bug:

- `git clone https://github.com/pbrisbin/fugitive-bug && cd fugitive-bug`
- `vim -u vimrc foo.md +5`
- Notice that `:GDiff` etc work as expected
- `vim -u vimrc foo.md:5`
- Notice that `:GDiff` etc are not defined

Thanks!

**Comment by tpope** [comment]
Fugitive doesn't do anything more complicated than `autocmd BufReadPost`, so I am quite confident in blaming whatever weird trick file-line is doing until demonstrated otherwise.
