### ISSUE TITLE
Function error when Ggrep on Windows

### ISSUE THREAD

**Issue by bohrshaw** [tpope/vim-fugitive#603]
Error occurs in the function `s:Grep` with all these commands: `Ggrep "t`, `Ggrep \"t` or `Ggrep '"t'`.
Tested with `gvim -Nu NORC  --cmd 'se rtp+=~/.vim/bundle/vim-fugitive'` on Windows.

**Comment by tpope** [comment]
None of those are valid shell syntax on Windows.

**Comment by bohrshaw** [comment]
Oh, thanks for pointing out, my fault of reluctance to learn Windows shell syntax. `Ggrep """t"` works.
