### ISSUE TITLE
Gstatus fails to launch a diff if a new folder is added

### ISSUE THREAD

**Issue by elyscape** [tpope/vim-fugitive#605]
If you've created new files in a directory not currently tracked by Git, `git status` by default only outputs the name of the new directory.  If you select an untracked directory in the Gstatus window and hit `D`, Gdiff gets passed the directory name.  As a result, the "current" buffer is passed that directory to open and displays a directory listing, which is not useful for a diff.

A workaround for this is to set `status.showUntrackedFiles` to `all` in one's gitconfig.  That results in `git status` enumerating all untracked files, even if they're in untracked directories.  I don't know how many versions back you support, but this feature [was added in Git v1.6.0](https://github.com/git/git/commit/d6293d1f2cadcdf45f8ada7847a32b51fa5bf0a6) and requires the user to set it.  A way for fugitive.vim to handle this itself would be to be to add the `-u` flag to its `git status` calls. The `-u`/`--untracked-files` flag [was added to `git-status` in Git v1.4.0](https://github.com/git/git/commit/443f8338b9e248353a7095a1096684f1ed106c66) and results in the full enumeration of untracked files, which solves this issue.

**Comment by elyscape** [comment]
This also (for obvious reasons) breaks `ds` and `dv`.  A workaround is for the user to press `dp` on the directory before trying to run a diff, as this executes `:Git add --intent-to-add`, which causes Git to identify all the untracked files in the directory.

**Comment by elyscape** [comment]
Looks like support for `--intent-to-add` [was added in Git v1.6.1](https://github.com/git/git/commit/394258190c76dd7944688a3a28931071ec02087d).

**Comment by elyscape** [comment]
Screenshot of the problem:

![Broken diff](https://cloud.githubusercontent.com/assets/792695/7780105/c08331b4-008f-11e5-8ec3-7b4ecc005ad7.png)

**Comment by bounceme** [comment]
What about for a repository located somewhere like the home directory? I assume there would be a very large list of untracked files

**Comment by elyscape** [comment]
That should only matter if the home directory is the repository.

**Comment by elyscape** [comment]
Also note that this will not cause Git to enumerate ignored files.
