### ISSUE TITLE
Diff from Glog

### ISSUE THREAD

**Issue by ghost** [tpope/vim-fugitive#606]
With <code>[diff]
    noprefix = true</code> in my .gitconfig, pressing enter on a diff summary line in the Glog window, as seen [here](http://vimcasts.org/episodes/fugitive-vim-browsing-the-git-object-database/), does nothing.

**Comment by elyscape** [comment]
One possible solution to this would be, [for Git >=1.5.4](https://github.com/git/git/commit/eab9a40b6dd5c1c571b1deb264133db47bb4794d), add the flags `--src-prefix=a/ --dst-prefix=b/` to the diff command.  The `diff.noprefix` config option [was added in Git 1.7.2](https://github.com/git/git/commit/f89504ddb9392fa6b9407957bf26905fd1d59d0a), so we wouldn't have to worry about having it set but not being able to use the flags to override it.

**Comment by tpope** [comment]
Probably `-c diff.noprefix=false` is more to the point?

**Comment by elyscape** [comment]
Yes, but it only works for Git >=1.7.2.  Then again, since `diff.noprefix` was added in 1.7.2, the other flags wouldn't be necessary before then anyway.  So `-c diff.noprefix=false` is the better way to go, yeah.

**Comment by NightVigil** [comment]
Any progress on this? It's still an issue with the latest code.

**Comment by tpope** [comment]
Solution is right there for the taking.
