### ISSUE TITLE
Gblame "P" shortcut throws confusing error if file does not exist in previous revision

### ISSUE THREAD

**Issue by benbarbour** [tpope/vim-fugitive#607]
This is the error:

> Error detected while processing BufReadCmd Auto commands for "fugitive://**//[0-9a-f][0-9a-f]*":  
> fugitive: rev-parse _[[SHA#]]_:_[[FILE_NAME]]_: fatal: Needed a single revision
> Error detected while processing function <SNR>79_BlameJump:
> line   22:
> E492: Not an editor command: Gblame 

I'm not sure why it says "Needed a single revision" when I run `git rev-parse [[SHA#]]:[[FILE_NAME]]` I get the much more helpful error:

> _[[SHA#]_:_[[FILE_NAME]]_
> fatal: Path _[[FILE_NAME]]_ exists on disk, but not in _[[SHA#]_

In my case the file does exist in the grandparent commit (it was removed accidently in one commit) so I can use `2~` in the blame window to get past the error. I'm not sure if `P` should be changed so that it jumps to the last parent commit where the file exists... needs more than the 5 seconds of thought I'm giving it. I do think the error should be more helpful though.

**Comment by matthewd** [comment]
In case it helps, while trying to reproduce #693, I ran into this issue a few times.

For example:

```
cd vim-git
vim ftplugin/git.vim
:1
:Gblame
P
```

**Comment by tpope** [comment]
Obvious incremental improvement is to short circuit when things first go south.

**Comment by tpope** [comment]
The next step would be to decide what to do if we edit a `fugitive://` path that doesn't exist. The natural thing to do in Vim would be to just leave the buffer empty (just like any other non-existent file).

**Comment by matthewd** [comment]
Ah, now that I've finally understood why I was seeing the two different behaviours... in this particular case (trying to go past the beginning of time for a given line), my ideal behaviour would be a bell or an error message, and staying on the "current" blame... acknowledging the obvious complication that by the time we notice the problem it's not actually current anymore. :smile:

**Comment by blueyed** [comment]
@benbarbour 
JFI: fugitive uses `git rev-parse --verify`, which results in a different error message (but for the same reason).

**Comment by blueyed** [comment]
I assume https://github.com/tpope/vim-fugitive/pull/961 (for #866) might help here as well.
