### ISSUE TITLE
Show all changed unstaged files in quicklist

### ISSUE THREAD

**Issue by mollerhoj** [tpope/vim-fugitive#610]
Is it possible to get a quicklist with names of files that have been changed but not yet staged?

It would also be nice to able to get a quicklist of files that differ from master. That is, the files that show up on: `git diff --name-only master..HEAD`

**Comment by githorse** [comment]
+1 for part 2. I'm reviewing someone's pull request and I want to visit each file that has changes (ideally, each diff in the file) -- not sure how I can do this with fugitive.

**Comment by patovala** [comment]
+1 I think this is the missing command

**Comment by tpope** [comment]
See #132, which we might be getting closer to solving, but don't start holding your breath just yet.
