### ISSUE TITLE
If iTerm2 is open, :Gpush on Macvim opens iTerm tab, then hangs

### ISSUE THREAD

**Issue by jasonschock** [tpope/vim-fugitive#615]
Using a vanilla install of carlhuda/janus and Macvim (build 73) via homebrew. (I have also replicated this on a second machine with a similar but modified setup.)

* Working within a git repo, with a file open, run `:GPush`

* IF I have iTerm2 open, a new tab opens.
  * It is blank.
  * Focus remains in Macvim.
  * Nothing happens in the iTerm tab, just seems to hang.

* In Macvim, the command line shows `!git push  (iterm/?) `
* No git push actually happens.

* IF I have iTerm closed, the command works as expected.

* The command works as expected from vim running in a terminal.

The culprit seems to be `:Make` (https://github.com/tpope/vim-fugitive/blob/master/plugin/fugitive.vim#L1577), which is a [vim-dispatch](https://github.com/tpope/vim-dispatch) thing, where there seems to be some iTerm2 issues anyway.

Not sure if there's much to be done; just reporting it, but happy to help troubleshoot. It's easy enough to work around with `:!git push`.

**Comment by tpope** [comment]
For sure sounds like a dispatch.vim issue. Feel free to reopen there. You might start by ruling out other plugins.
