### ISSUE TITLE
Gblame error after closing window

### ISSUE THREAD

**Issue by srasku** [tpope/vim-fugitive#616]
To reproduce:
1. :Gblame
2. Press '-' to go to previous revision specified on current
3. Press ctrl-W o to close right-side window
4. Select a previous revision and press '-'

The following message is displayed:

> Error detected while processing function <SNR>18_BlameJump..<SNR>18_buffer..<SNR>18_throw:
> line    2:
> E605: Exception not caught: fugitive: not a git repository: /tmp/vBXSi57/152.fugitiveblame
> Error detected while processing function <SNR>18_BlameJump:
> line    8:
> E171: Missing :endif 

I would expect it to re-open the Gblame window at the selected revision.

If you close the left window instead of the right one it won't open the Gblame window (because the revision is no longer in the buffer) but it doesn't throw an error.

**Comment by tpope** [comment]
Fixed.
