### ISSUE TITLE
commit should have an option to work like git commit -v

### ISSUE THREAD

**Issue by mcepl** [tpope/vim-fugitive#617]
I am too sloppy with my `git add` (or `:Gwrite`) and I have acquired as self-protection a habit to run `git commit -v` always so I can see what actually goes to the commit. One of the things which makes me using fugitive less than it deserves is the fact I don't know who to persuade `:Gcommit` to include the diff in the window where I write the commit message. Is there some option for it which I haven’t found yet, or is this actually a RFE?

**Comment by tpope** [comment]
`:Gcommit` accepts arguments.

**Comment by mcepl** [comment]
well, I would prefer some kind of configuration to make it automatic (also for `cc` in `:Gstatus`).

**Comment by glittershark** [comment]
[There is one](https://github.com/tpope/vim-fugitive/blob/master/doc/fugitive.txt#L47)

**Comment by mcepl** [comment]
Thanks

**Comment by magnetophon** [comment]
@glittershark 
Thanks for the pointer.
It;s a good workaround, but it would be nicer if it was an option you could set.
That way, you can still use the regular mappings.

Having the dif is also nice because then the $autocompleter can help writing the commit msg.

**Comment by tpope** [comment]
If only Vim let you define your own maps..........................................................................

**Comment by magnetophon** [comment]
@tpope
Do you mean redefine each of the built in fugitive mappings that use Gcommit?
 
Or is there a global way to do this?
I tried:
```
:command -nargs=* Gcommit :Gcommit --verbose
```
but that didn't work.

**Comment by tpope** [comment]
I was talking about maps like `cc`. If you just want to override it *everywhere* that's between you and Git. I'm not going to make `:Gcommit` more malleable than `git commit` itself.

**Comment by magnetophon** [comment]
OK, fair enough.
I didn't even realise untill now that the alias I've been using on the cli is not the default behaviour of git, but yours is. 

Thanks.
