### ISSUE TITLE
Gstatus "p" shortcut endless loop

### ISSUE THREAD

**Issue by nuimk** [tpope/vim-fugitive#618]
This issue happens in neovim only.

When press "p" in Gstatus window, vim keeps asking for decision but  never responses to any keys. it caused vim to become unresponsive.

**Comment by tpope** [comment]
Works for me. What do you mean by "asking for decision"?

**Comment by nuimk** [comment]
Sorry for my bad english.

nvim keep printing output like this
```shell
Unstage this hunk [y,n,q,a,d,/,e,?]? @@ -1,6 +1,7 @@
 import os
 import sys
 from distutils.sysconfig import get_python_lib
+import sys

 from setuptools import find_packages, setup

Unstage this hunk [y,n,q,a,d,/,e,?]? @@ -1,6 +1,7 @@
 import os
 import sys
 from distutils.sysconfig import get_python_lib
+import sys

 from setuptools import find_packages, setup

Unstage this hunk [y,n,q,a,d,/,e,?]? @@ -1,6 +1,7 @@
 import os
 import sys
 from distutils.sysconfig import get_python_lib
+import sys

 from setuptools import find_packages, setup

Unstage this hunk [y,n,q,a,d,/,e,?]? @@ -1,6 +1,7 @@
 import os
 import sys
 from distutils.sysconfig import get_python_lib
+import sys

 from setuptools import find_packages, setup

Unstage this hunk [y,n,q,a,d,/,e,?]? @@ -1,6 +1,7 @@
 import os
 import sys
 from distutils.sysconfig import get_python_lib
+import sys
```

None of y,n,q,a,d,/,e and '?' keys work. I have to close my terminal to exit nvim.

NVIM 0.0.0-alpha (compiled Mar 15 2015 05:20:38)

**Comment by tpope** [comment]
Oh, I can reproduce this. It also happens when I do `:!git add --patch`, so I think this is an neovim issue that is unrelated to fugitive.vim.

**Comment by nuimk** [comment]
Thanks, I will report this issue to neovim.

**Comment by justinmk** [comment]
This is a known issue: https://github.com/neovim/neovim/issues/1496

`:terminal` is a workaround (https://github.com/neovim/neovim/pull/2076 , not merged yet).

**Comment by languitar** [comment]
Any chance to add the required changes for neovim in this plugin?
