### ISSUE TITLE
Print post-commit hook output to :Gcommit buffer 

### ISSUE THREAD

**Issue by huoxito** [tpope/vim-fugitive#621]
So when I run `git commit` from shell I can see the output generated by the post-hook script fine, for example:

```
1 file inspected, no offenses detected
[master b96ab66] test
 Date: Fri Mar 20 11:43:17 2015 -0300
 1 file changed, 7 insertions(+), 1 deletion(-)
```

However when I commit inside vim via `:Gcommit` (which is what I do 90% of the times) it seems it always swallows any output on the post-commit hook:

```
"~/coding/example/.git/COMMIT_EDITMSG" 18L, 383C written

[master 60e3a57] test
 Date: Fri Mar 20 11:43:17 2015 -0300
 1 file changed, 7 insertions(+), 1 deletion(-)
```

I wonder if this is by design or if there's some sort of config / hack we could do to make sure the post-hook script results also show up on the Gcommit buffer? The post-hook script looks like this:

``` sh
#!/bin/sh
rubocop-git HEAD~1 HEAD
```

thanks

**Comment by tpope** [comment]
My guess is that adding `2>&1` to the hook will fix it. The current implementation relies on capturing stderr and checking it for certain output, so it doesn't get displayed.

**Comment by huoxito** [comment]
Appreciate the input @tpope I tried `rubocop-git HEAD~1 HEAD 2>&1` or even `echo huhu 2>&1` but it still behaves the same way posted above, I'm also not sure I understand why moving stderr to stdout would help (not that I know much about shell or anything at all about vim scripting), would the post-commit output be considered stderr? I'll try to keep digging need to know this better

**Comment by tpope** [comment]
This should be fixed now. I didn't realize Git forced all hook output to stderr when I suggested that 4 years ago.
