### ISSUE TITLE
Gdiff Explosion

### ISSUE THREAD

**Issue by benhamill** [tpope/vim-fugitive#623]
Often, when I'm looking at a file with a merge conflict in it, I type `:Gdiff`and get output like this:

```
Error detected while processing function <SNR>79_Diff:
line    6:
E116: Invalid arguments for function <SNR>79_buffer_expand
E116: Invalid arguments for function <SNR>79_repo_translate
E116: Invalid arguments for function s:fnameescape(fugitive#buffer().repo().translate(s:buffer().expand('':2'')))
E15: Invalid expression: s:fnameescape(fugitive#buffer().repo().translate(s:buffer().expand('':2'')))
line   10:
E116: Invalid arguments for function <SNR>79_buffer_expand
E116: Invalid arguments for function <SNR>79_repo_translate
E116: Invalid arguments for function s:fnameescape(fugitive#buffer().repo().translate(s:buffer().expand('':3'')))
E15: Invalid expression: s:fnameescape(fugitive#buffer().repo().translate(s:buffer().expand('':3'')))
```

I can't reproduce it in trivial conflict cases, though. Any clues? I am awful at VimL, so I haven't dug in to see if I can understand what the code is doing in those places mentioned.

**Comment by tpope** [comment]
Are you on the latest? That code doesn't match up.

**Comment by benhamill** [comment]
```
● vim-fugitive master ❱ git remote show origin
* remote origin
  Fetch URL: https://github.com/tpope/vim-fugitive.git
  Push  URL: https://github.com/tpope/vim-fugitive.git
  HEAD branch: master
  Remote branches:
    blame_color    tracked
    blame_message  tracked
    buffer_path    tracked
    copied         tracked
    http_github_fi tracked
    master         tracked
  Local branch configured for 'git pull':
    master rebases onto remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
● vim-fugitive master ❱ git l
0095769 Fedor Gusev (5 weeks ago) - (HEAD, origin/master, origin/HEAD, master) Provide g:fugitive_no_maps to disable key maps
e8b9409 Eli Young (5 weeks ago) - Support browsing with new netrw.vim
eb8eb18 Tim Pope (6 weeks ago) - Support for browsing with recent Vim
933f6a1 Daniel Hahler (8 weeks ago) - s:Diff: use winnr with `<C-W>w` instead of `<C-W>p`
3471901 Tim Pope (9 weeks ago) - (tag: v2.2) fugitive.vim 2.2
2c8461d Daniel Hahler (4 months ago) - Use `<nomodeline>` with Fugitive autocmds, and un-silent them
d3b98d9 John Whitley (5 months ago) - Make configured_tree a caching global function
5699f46 Tim Pope (5 months ago) - Fix instaweb support
0374322 Tim Pope (7 months ago) - Fix :Glog
90ee6fb Tim Pope (8 months ago) - Pass line1 and line2 as 0 for :Gbrowse without range
● vim-fugitive master ❱ git p
Current branch master is up to date.
```

It looks up to date to me... but maybe I have something jacked up somehow? Shall I try removing fugitive completely and reinstalling it?

**Comment by rscircus** [comment]
+1 :-/

**Comment by rscircus** [comment]
@benhamill, and fixed it via:

Remove ./git/* from wildignore in vim's config!

As detailed [here](https://github.com/tpope/vim-fugitive/issues/121).

**Comment by benhamill** [comment]
If I run `:set wildignore` in vim, it tells me `wildignore=`. Which I assume means I'm not modifying that anywhere. I also looked in my `.vimrc` to see if I was doing anything with `.git/`, but didn't spot anything.

**Comment by glittershark** [comment]
Try `set wildignore?`

**Comment by glittershark** [comment]
fwiw I have `.git` in my wildignore and Fugitive works just fine.

**Comment by tpope** [comment]
If it chases back to wildignore, at least some of the time, then the underlying problem is probably a `` `=...` `` expansion somewhere. The fix would be to replace it with an equivalent `exe '...' fnamescape(...)`.

**Comment by danielkza** [comment]
I am currently observing this issue. My `wildignore` does not include `.git`, and am I running the current latest master (366996484e3f51fefb14b). Whenever I try to run `Gdiff` in any file of my repository I get the same errors from the original post.

Are there any workarounds, or have I commited any mistakes during installation/configuration?

**Comment by danielkza** [comment]
Thank you, I'll test the fix.
