### ISSUE TITLE
Gcommit editing message opens a file listing?

### ISSUE THREAD

**Issue by gerroon** [tpope/vim-fugitive#625]
Hi

I am not sure if this is by design but I am getting a file listing window when I try to edit {a} or {i} the Gcommit buffer to include a message.

**Comment by tpope** [comment]
You're not in `Gcommit` you're in `Gstatus`

**Comment by gerroon** [comment]
Ok that is fine. But here is the catch. I use git -am, and I cant see how I can do that with Fugitive?
