### ISSUE TITLE
Support the fish shell

### ISSUE THREAD

**Issue by euclio** [tpope/vim-fugitive#626]
Currently, Fugitive gets the cryptic error `W13: Warning: File ".git/index" has been created after editing started` if attempting to call `:Gcommit`. Additionally, `:Gstatus` comes up with an empty split. I realized that this was due to having my shell set to `/bin/fish`. Of course, the workaround would be to set my shell to `/bin/bash`, but I'd like to use fish if possible.

If you think this is a worthwhile feature, I wouldn't mind putting a patch together for it.

**Comment by tpope** [comment]
Vim assumes a POSIX shell; Fish isn't really feasible to support.

**Comment by euclio** [comment]
I actually wrote the patch for fish support in vim, it's fully supported as far as I'm aware.

**Comment by tpope** [comment]
Oh, then in that case have at it.

**Comment by bronzehedwick** [comment]
:+1:

**Comment by shawnbon206** [comment]
:+1:

**Comment by kaleb** [comment]
I have confirmed that this change works. Thanks @euclio for this and your vim patch!

**Comment by tpope** [comment]
Commit message needs to be fixed and it's good to go.

**Comment by euclio** [comment]
Capitalized the message. Did you have any other issues with it?

**Comment by tpope** [comment]
I've decided I'd rather have the conditional inline, but I just fixed that myself.
