### ISSUE TITLE
:Gcommit verbose

### ISSUE THREAD

**Issue by trotha01** [tpope/vim-fugitive#628]
Is there a way to make :Gcommit always verbose?
Same as git commit --verbose

I wasn't able to find anything in the fugitive documentation
And making a git alias didn't seem to change :Gcommit
git config --global "alias.ci" "commit -v"
git config --global "alias.commit" "commit -v"

Thank you in advance!

**Comment by tpope** [comment]
No. You can define a command that wraps it.

**Comment by trotha01** [comment]
Okay I see the map, I was looking under "Gcommit" instead of "Gstatus", my bad.
so it's "cvc" :+1: 

Thank you for such a quick response!
