### ISSUE TITLE
Feature request: Cycle back through previous commit messages in commit window

### ISSUE THREAD

**Issue by tuzz** [tpope/vim-fugitive#629]
I often refer back to previous commit messages when committing to help with consistency. When committing, it would be really helpful if you could use the autocompletion pane to cycle back through previous commit messages.

**Comment by atlib77** [comment]
I'd like this as well. In the mean time I'm using:
`:Git! log --oneline`
which opens a temp file which I can copy from.

If there are any better alternatives, I'd like to hear!

**Comment by tpope** [comment]
I think `:Git! log --oneline` (now available as `:Git log --oneline`) is pretty good. You can also do `:0Gread commit` to copy a previous commit message. I don't think hacking up autocompletion to do something that's clearly not completion is a good interface.
