### ISSUE TITLE
feature request: extension on diff against branch

### ISSUE THREAD

**Issue by raghuramos1987** [tpope/vim-fugitive#630]
We can currently open a file and get its diff against a branch by :Gdiff <revision> . It would be nice to have a mode where I'm on branch b1 and need to diff against master and view the files in the quickfix window (or something else). And :Gv on the file should open the diff between the file in branch and master directly. If you can provide some insight into where I need to start, I can try and implement this. (Although this would be my first vim feature and the pull request might need some cleanup)

**Comment by mcepl** [comment]
I don't understand your request, probably. What's missing from (while on branch ``b1``) using ``Gdiff master``?

**Comment by tpope** [comment]
I'm gonna guess this is yet another request for something like #132.
