### ISSUE TITLE
Can't blame files with numbers in their name

### ISSUE THREAD

**Issue by xaizek** [tpope/vim-fugitive#631]
I experienced trouble with blaming man pages (named `man.1`) via fugitive. The cause seems to be regular expression in `s:BlameJump` function, which stops at first number due to non-greedy quantifier (`.\{-\}`). The fix is simple as the patch shown below, but I'm not sure whether it won't break anything, e.g. is there a case where there will be no space between file name and line number?

``` patch
diff --git a/plugin/fugitive.vim b/plugin/fugitive.vim
index 70451eb..0d00350 100644
--- a/plugin/fugitive.vim
+++ b/plugin/fugitive.vim
@@ -2039,7 +2039,7 @@ function! s:BlameJump(suffix) abort
     let commit = ':0'
   endif
   let lnum = matchstr(getline('.'),' \zs\d\+\ze\s\+[([:digit:]]')
-  let path = matchstr(getline('.'),'^\^\=\x\+\s\+\zs.\{-\}\ze\s*\d\+ ')
+  let path = matchstr(getline('.'),'^\^\=\x\+\s\+\zs.\{-\}\ze\s\+\d\+ ')
   if path ==# ''
     let path = s:buffer(b:fugitive_blamed_bufnr).path()
   endif
```

**Comment by tpope** [comment]
Fixed.
