### ISSUE TITLE
Fails to load plugin when re-editing file

### ISSUE THREAD

**Issue by h3xx** [tpope/vim-fugitive#632]
Fugitive fails to load its functions when editing a file in a repo.

Steps to reproduce:

1. Clone any git repository.

    git clone https://github.com/tpope/vim-fugitive.git ~/git/vim-fugitive

2. Symlink a file inside the git repository anywhere where not under git control.

    ln -s ~/git/vim-fugitive/README.markdown ~/

3. Open the symlink in vim. Fugitive will not (and should not) load.

    vim ~/README.markdown

4. Open to the same file referenced by the symlink but inside the git repository.

    :e! ~/git/vim-fugitive/README.markdown

Fugitive functions will not be loaded for the file in the git repository. Even running `:bdelete` doesn't help. Opening a different file inside the repository loads Fugitive as expected.

I have tested this in a "clean room" environment with an empty .vimrc and only Fugitive installed.

**Comment by tpope** [comment]
This is just an artifact of the way Vim symlinks work. There's not really an elegant solution, but `:bwipe` will completely eliminate the old file name, enabling you to open it again with the correct name.

**Comment by h3xx** [comment]
Interesting. I suppose this is an edge case and probably not worth fixing. The workaround should do fine.
