### ISSUE TITLE
Stale view files with error Gcommit.  Cursor out of Range

### ISSUE THREAD

**Issue by John-Appleseed** [tpope/vim-fugitive#634]
Stale view files with error Gcommit.  

Error: Cursor out of Range

Vim config

``` vim
au BufWrite ?* mkview!
```

Problem:
Gcommit view fails to render

Solution:
- Remove stale view files
- Fix: Have Gcommit ignore the view file from the committed file

**Comment by John-Appleseed** [comment]
Error: E16: Invalid range: 17,54fold

**Comment by tpope** [comment]
This is a very aggressive autocommand of your own design. It's on you to offer a fix.
