### ISSUE TITLE
Gstatus: default to `Gcommit -v`

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-fugitive#635]
When given a Vim buffer, verbose output with `git commit` is useful (and won't flood your terminal etc).

Is there a reason why `cc` in `:Gstatus` should not default to it, so that it would obsolete `cvc`?

The other Gcommit mappings should also use `--verbose` then probably!?

**Comment by tpope** [comment]
Yes, `--verbose` forces a new tab to open which might not be desired. But more importantly, I am not interested in bikeshedding differences on top of the standard git commands. If you think `-v` should be a default, go get it merged into Git proper.

**Comment by glittershark** [comment]
or just:
```vim
autocmd BufReadCmd index{,.lock} nnoremap <buffer> <silent> cc :<C-U>Gcommit --verbose<CR>
```

**Comment by blueyed** [comment]
Thanks, but I have the following already, which is useful in general, not just with `:Gst`:

    nnoremap <Leader>gc :Gcommit -v
