### ISSUE TITLE
how to identify when Gdiff is used and apply different highlight/options

### ISSUE THREAD

**Issue by nbari** [tpope/vim-fugitive#636]
On my ``.vimrc`` I have something like this:

    if &diff
        syntax off 
        highlight DiffAdd cterm=NONE ctermfg=bg ctermbg=Green gui=NONE guifg=bg guibg=Green
        highlight DiffDelete cterm=NONE ctermfg=bg ctermbg=Red gui=NONE guifg=bg guibg=Red
        highlight DiffChange cterm=NONE ctermfg=bg ctermbg=Yellow gui=NONE guifg=bg guibg=Yellow
        highlight DiffText cterm=NONE ctermfg=bg ctermbg=Magenta gui=NONE guifg=bg guibg=Magenta
    endif

That helps me to use a different color schema when using **vimdiff**.

How could I continue to use does definitions when using Gdiff?

**Comment by tpope** [comment]
Those highlights belong in an after colorscheme file. For disabling syntax highlighting you might try something like

    autocmd FileType * if &diff | setlocal syntax= | endif
