### ISSUE TITLE
Speed of fugitive on windows

### ISSUE THREAD

**Issue by idvorkin** [tpope/vim-fugitive#637]
I love fugitive, but on windows commands take several seconds. 

For example,  when I run GDiff I see 5 different consoles getting spawned, each taking ~ 1 second. This results in a single GDiff taking 5 seconds. 

Is this expected? If not, how do I debug?  
If so, any tips to speed things up?

**Comment by tpope** [comment]
One second per console sounds really high. If you call `:!git rev-parse HEAD` directly, is that similarly slow?

**Comment by idvorkin** [comment]
I'm not timing accurately maybe it's 0.5 seconds, but it's observably slow.  The git rev-parse command takes a similar amount of time.  

How long does the command take on your setup?  Any ideas on how to speed up?

**Comment by tpope** [comment]
I don't have convenient access to a Windows machine at the moment but I'm pretty sure `:Gdiff` took less than a second last I tried. I wouldn't know where to begin debugging a slow Git.

**Comment by glittershark** [comment]
Looks like you're [not the only one who's encountered this issue](http://stackoverflow.com/questions/27519050/gitbash-generally-slow#comment43467899_27519050)

**Comment by run2cmd** [comment]
I know this is old, but I've been experiencing performance issues with gVim and vim-fugitive since :Gstatus UI change(:Gstatus takes 8-12sec). Previously it was kinda slow too(3-5sec), but not like now. Right now :Gstatus seems to performance serveral git commands and each needs to open new CMD window. As Git commands works fast opening new windows is very slow:

```
PS D:\code\> Measure-Command {git status}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 87
Ticks             : 871487
TotalDays         : 1.00866550925926E-06
TotalHours        : 2.42079722222222E-05
TotalMinutes      : 0.00145247833333333
TotalSeconds      : 0.0871487
TotalMilliseconds : 87.1487
```


```
PS D:\code\> Measure-Command {cmd /C git status}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 418
Ticks             : 4184517
TotalDays         : 4.84319097222222E-06
TotalHours        : 0.000116236583333333
TotalMinutes      : 0.006974195
TotalSeconds      : 0.4184517
TotalMilliseconds : 418.4517
```
And this does not include opening new graphical window. Even if that is 0.5 sec its still a lot. 
I wonder if there is a way that vim-fugitive could prepare bulk of commands to execute in single window.

**Comment by tpope** [comment]
Batching commands sounds really hard, but please by all means investigate. I would accept a solution that batches only on Windows, if that makes things any easier.

For a quick win, the two calls to `diff` could each be skipped if the relevant section of `git status` is empty.  And the two calls to `log` could be cached based on the timestamps of the two refs being compared.

**Comment by tpope** [comment]
Closing in favor of #1254, which is focused on the speed of the new implementation.
