### ISSUE TITLE
doesnt work on ubuntu 14.04?

### ISSUE THREAD

**Issue by liangguohuan** [tpope/vim-fugitive#639]
vim version: 7.4.052-1ubuntu3

i install it with vundle manager.

the same config, it works well on ubuntu 15.04 desktop, but failt on ubuntu 14.04 desktop.

**Comment by tpope** [comment]
Not enough information.

**Comment by tpope** [comment]
Let me be clearer, this plugin doesn't care about your distro so this is a problem on your end.

**Comment by liangguohuan** [comment]
ok, i got it.
thanks for your tips.
and thanks for your other wonderful plugins.
