### ISSUE TITLE
fugitive on windows

### ISSUE THREAD

**Issue by charyxiao** [tpope/vim-fugitive#640]
gvim 7.4 + windows 7 x64
![1](https://cloud.githubusercontent.com/assets/5407327/7648199/88472ea4-fb12-11e4-8f0d-41e42a88a52e.png)
![2](https://cloud.githubusercontent.com/assets/5407327/7648201/8ff98f66-fb12-11e4-811c-42e7745a655a.jpg)

I do love fugitive, but I enconter two problems above. I searched this problem for three days, but it get no result.

**Comment by charyxiao** [comment]
I tried comment other plugins, it does not work.

**Comment by tpope** [comment]
Can you try

    :echo b:git_dir

in the blame buffer?

**Comment by charyxiao** [comment]
E121:undfined var: b:git_dir
E15: undfined var: b:git_dir
it mean's something wrong with my buffer's plugin?

**Comment by charyxiao** [comment]
b:git_dir is unleted, it is the exact problem is, but I do not know how to fix it, after I read some of fugitive's code. I so sorry to bother you again.

**Comment by tpope** [comment]
Hard to say what is going wrong on your machine, but as a wild guess, can you see if `:set shellslash` fixes it?

**Comment by tpope** [comment]
By the way that second error is just because you have unsaved changes.

**Comment by charyxiao** [comment]
Thanks for your answers. I will try to figure it out.
