### ISSUE TITLE
fugitive relies on English git

### ISSUE THREAD

**Issue by ctford** [tpope/vim-fugitive#642]
Some fugitive features rely on parsing output from git. For example, there are many instances of comparing against *Changes to be committed*. This breaks if git is another language and outputs e.g. *Cambios para hacer commit*.

I have no idea how this could be reasonably solved, but I thought I would log this issue to at least alert those who might have encountered the same problem.

Putting an alias in `.bashrc` doesn't work:

    alias git='LANG=en_US git'

I assume vim doesn't respect bash aliases.

**Comment by tpope** [comment]
This should work fine assuming you haven't disabled status hints.

**Comment by ctford** [comment]
You're totally right - it was the status hints. Thanks!
