### ISSUE TITLE
Feature request: Stage and destage all

### ISSUE THREAD

**Issue by ctford** [tpope/vim-fugitive#644]
When I have a commit that involves a lot of files, it would be useful to be able to stage everything.

I can achieve something similar with `:Git add -u .`, but that drops me out of the nice Gstatus workflow and doesn't give me a chance to see what files are included.

As far as I know, there is no binding for this.

**Comment by glittershark** [comment]
I propose `_` because it's `Shift+-`

**Comment by ctford** [comment]
I'm happy to bumble my way through a patch if it seems useful.

**Comment by tpope** [comment]
Press `-` on the section heading.

**Comment by ctford** [comment]
I'm using the following, but since I don't know how to detect whether everything is already added or not, I have two bindings:

    nnoremap <buffer> <silent> -a :<C-U>silent Git add -u .<CR>
    nnoremap <buffer> <silent> -r :<C-U>silent Git reset .<CR>

**Comment by ctford** [comment]
Nice.
