### ISSUE TITLE
Gpull fails with older git versions

### ISSUE THREAD

**Issue by bijancn** [tpope/vim-fugitive#645]
Most likely you haven't noticed this, but `Gpull` does not work with `git version 1.7.1` due to
```
|| Unknown option: -c
```
While a work around would be nice (if possible), I would suggest to at least mention the required git version in the README. With `git version 1.9.1`, it works as expected.

You might ask why I have such an ancient git version but in physics departments it seems rather common not to update the software to have a 'stable' system.

**Comment by tpope** [comment]
If you can figure out the exact required version I will mention it. I think other commands like `:Gstatus` would fail as well.

**Comment by bijancn** [comment]
No, `Gstatus` and `Gpush` work interestingly. In the release notes of `1.7.2`, I see
```
 * "git" wrapper learned "-c name=value" option to override configuration
   variable from the command line.
```

**Comment by tpope** [comment]
Oh I see, I forgot about https://github.com/tpope/vim-fugitive/blob/b0e38f08dca7dc33664705253e63cb92b3592e99/plugin/fugitive.vim#L2426-2434. We can't make the `-c` optional in this case but there is another trick we can use.

**Comment by bijancn** [comment]
Sadly, now I get
```
|| error: unknown option `edit'
```
`git merge` learned `--edit` in `1.7.8` but I don't find something about `git fetch`.

**Comment by tpope** [comment]
Oh, bummer. I think I'll abstain from documenting at this time. That error message is a bit more obvious, and this issue will hopefully make it easy to Google.
