### ISSUE TITLE
:Gbrowse doesn't do the right thing when on a detached HEAD.

### ISSUE THREAD

**Issue by tomprince** [tpope/vim-fugitive#646]
If I've checked out a remote branch, it should take me the the corresponding file in that remote branch, rather than 

It when I've checked out ``origin/master``, it should take me to
``https://github.com/ClusterHQ/build.clusterhq.com/blob/master/buildbot.tac``
instead of 
``https://github.com/ClusterHQ/build.clusterhq.com/blob//buildbot.tac``
(not the double '//` there).

**Comment by tpope** [comment]
This code is deprecated in favor of [rhubarb.vim](/tpope/vim-rhubarb), which appears to handle this case correctly. A fix would still be great, but it should match up with the code there, rather than continue to diverge the two.

**Comment by tpope** [comment]
A copy and paste of the appropriate function body would be fine; just double check that it works.
