### ISSUE TITLE
Getting `:Gcommit` to work like `git commit -vs`?

### ISSUE THREAD

**Issue by magthe** [tpope/vim-fugitive#650]
I have an alias in my `~/.gitconfig` which reads

    commit = commit -vs

Is there some way to get `:Gcommit` to behave in the same way without having to add `-vs` on each invocation?

 (I know about the option of invoking `:GCommit` via `:Gstatus` and [doing a verbose commit](https://github.com/tpope/vim-fugitive/blob/master/doc/fugitive.txt#L47) that way, but that's both a detour to committing and doesn't add the `--signoff` flag)

**Comment by tpope** [comment]
That doesn't make sense because Git aliases that override built-ins are ignored.

**Comment by magthe** [comment]
Indeed, I was surprised when I noticed that ;)  But I don't care about it if I can somehow configure fugitive such that I don't have to remember to add `-vs` to each call to `:Gcommit`

**Comment by glittershark** [comment]
`command! Gcvs Gcommit -vs`

**Comment by magthe** [comment]
So in short, no, there is no way to modify how `:Gcommit` works, the way to do it is adding a custom command.  Again I'm somewhat surprised, this time at the lack of configurability, but I can live with it.

**Comment by tpope** [comment]
It is exactly as configurable as Git itself.

**Comment by magthe** [comment]
Well, I guess I just have to look into the sources myself to find the configurability then, or get used to using an alias (either on the vim level or the git level).
