### ISSUE TITLE
Error on issuing git commit --amend

### ISSUE THREAD

**Issue by anoopcs9** [tpope/vim-fugitive#653]
I recently cloned the vim-fugitive repo and installed it in ~/.vim directory on my fedora 22 system running Vim 7.4. I added the following line in ~/.vimrc file to load the plugin by default.
source ~/.vim/fugitive.vim
But on issuing git commit --amend I get the following error
Error detected while processing /root/.vim/fugitive.vim:
line  726:
E492: Not an editor command:     Gpedit :
line  728:
E518: Unknown option: foldmethod=syntax 
Press ENTER or type command to continue

Did I miss something in loading the plugin? Help me please since its really annoying.

**Comment by tpope** [comment]
You should install it in `~/.vim/plugin` and remove the `source` from your vimrc.

**Comment by anoopcs9** [comment]
Thanks.. That worked...!!
