### ISSUE TITLE
Error when trying ":Git review"

### ISSUE THREAD

**Issue by phmarek** [tpope/vim-fugitive#654]
When I try to run `:Git review`, I get the error
```
Traceback (most recent call last):
  File "/usr/bin/git-review", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/git_review/cmd.py", line 1041, in main
    class DownloadFlag(argparse.Action):
AttributeError: 'module' object has no attribute 'Action'
```

because `PYTHONPATH` includes the current directory (and there are some conflicting files, I guess).

As this setting is needed by another plugin (and might make sense on its own, too) I believe it would be good to (optionally) clean `PYTHONPATH` before calling external programs. (If this environment variable is *needed* to make `git` work, then perhaps we should _clean_ it by setting some `&fugitive_pythonpath` value to it).

**Comment by tpope** [comment]
Unless `:!git review` is working properly this isn't a fugitive issue. You can throw environment variables into `g:fugitive_git_executable` as a workaround.
