### ISSUE TITLE
Fugitive doesnt seem to understand git workdirs created by 'git checkout --to'

### ISSUE THREAD

**Issue by bjornars** [tpope/vim-fugitive#655]
This command is reasonably new, git v2.4 or v2.4.1.

**Comment by mathstuf** [comment]
Same with `git workdir add` from 2.5.0.

**Comment by mathstuf** [comment]
So with `git workdir add`, the first problem is that the `.git` file points to a directory not recognized by fugitive. Once that is done, the repo object needs to be updated to understand how to get information given the differences.

**Comment by bjornars** [comment]
This did not work for me using a worktree created by an older version of git, I cannot say which version exactly. In `s:repo_tree`, `self.dir()` returned `/home/<user>/src/<project>/.git/worktrees/<branch>`, that is without the tailing `/.git`. Git seems to understand this worktree perfectly.

Remaking the worktree with git 2.7 make everything work again, tho, great thanks!

**Comment by kaddkaka** [comment]
I'm having issues now with worktrees created with git 2.31.0. Doing:

`cd repo-root`
`git worktree add worktrees/branch`
`cd worktrees/branch`
`nvim file_in_repo.v`
`:Gblame`

Gives error
`fugitive: fatal: no such path 'worktrees/branch/file_in_repo.v' in HEAD`

What am I doing wrong? To me it seems like `worktrees/branch/` is incorrectly included as part of the path.

**Comment by tpope** [comment]
That should work. Check that `.git` in the root of the work tree looks like `gitdir: /absolute/path/.git/worktrees/branch'.

**Comment by kaddkaka** [comment]
The `.git` file in my worktree root contains `/abs/path/repo_root/.git/worktrees/branch` so that looks fine I think. Hmm ...

**Comment by tpope** [comment]
What does `:echo FugitiveIsGitDir("/abs/path/repo_root/.git/worktrees/branch")` (with the correct absolute path) report?

What does `:echo FugitiveExtractGitDir(expand("%"))` report?

**Comment by kaddkaka** [comment]
Thanks tpope, I didn't have `FugitiveIsGitDir` which made me realize I had a really old version of fugitive loaded. With newer version it worked! :)
