### ISSUE TITLE
Fails to hijack netrw in scp://HOST/PATH

### ISSUE THREAD

**Issue by h3xx** [tpope/vim-fugitive#657]
Steps to reproduce:

1. Open vim
2. `:e scp://HOST/`

Where HOST is a host you have configured in your .ssh/config file via pubkey or something. Directory listing will be opened in netrw, NOT NERDTree.

Netrw supports browsing remote file systems over ssh but NERDTree does not.

**Comment by tpope** [comment]
And none of this relates to fugitive :)

**Comment by h3xx** [comment]
Whoops, wrong project. You're too prolific. :-)
