### ISSUE TITLE
Ggrep -l or --files-with-matches output not directed to quickfix window

### ISSUE THREAD

**Issue by Pieter-Jan** [tpope/vim-fugitive#663]
can be very useful to do large refactorings

**Comment by tpope** [comment]
This is almost certainly achievable by tweaking the `'grepformat'`.

**Comment by Pieter-Jan** [comment]
I'm not sure. I checked into the grepformat option and the default option is set to "%f:%l%m,%f  %l%m" which should be OK. but with the -l option I only get the %f, which is normal as it stops after matching a file, but for some reason it shows up in the quickfix list with two pipes "| | %f" ...

**Comment by tpope** [comment]
The plugin has its own override of grepformat.

**Comment by Pieter-Jan** [comment]
Ok so what I did to get something was I added these lines to the fugitive.vim plugin (line 1208 etc.):

    if(a:arg !~ '-[a-zA-Z]*l[a-zA-Z]* .*') " check wheter the -l option is used
        let &grepformat = '%f:%l:%m'
    else
        let &grepformat = '%f'
    endif

This works but I still get two nasty pipe characters behind the filename ...

**Comment by tpope** [comment]
Is there any unfortunate consequences of unconditionally setting it to `%f:%l:%m,%f`?

**Comment by Pieter-Jan** [comment]
No that is a much cleaner solution. I did not know the , worked here!
