### ISSUE TITLE
:Gcommit not working with cmd.exe on Windows

### ISSUE THREAD

**Issue by sentriz** [tpope/vim-fugitive#665]
Hi, 
I'm having trouble with vim-fugitive.  
setup:
- Windows 8.1   _:-(_
- gVim 7.4
- usual way of using Git: 
  - Git for Windows though Git Bash _(C:\Program Files (x86)\Git\bin\sh.exe)_
  - SSH with **.ssh\id_rsa**, **.ssh\id_rsa.pub** pair  

problem:
- open a file that's in a local Git repo
- modify
- _:Gstatus_ (works just fine)
  - _<C-n>_ to file
  - _-_ to stage
- _:Gcommit_ (I know this can be done from the _:Gstatus_ pane, but for simplicity...) **[this](http://i.imgur.com/ZdZLOEd.png)** happens

I think this problem might be linked to the fact that I can't _git push_ from cmd.exe (what is set to be vim's default **shell**), but I can from Git Bash. I think this an SSH problem.
I have tried:
**:set shell="C:\Program\ Files\ (x86)\Git\bin\sh.exe"**
**:set shellcmdflag=-c**
**:set shellxquote=\"**
And basically by messing with vim shell\* options, I got _:!_ commands to work using Git Bash, where pushing works, but that wasn't any help, _:Gcommit_ still doesn't work. 

Any help would be appreciated!
    - sentriz

**Comment by dkharlan** [comment]
I'm also affected by this; I haven't tried pushing via SSH yet so I can't comment on that, but I get the same behavior and status line output with :Gcommit.

**Comment by benmoss** [comment]
Have you tried this with the latest Git for Windows? https://git-for-windows.github.io/

It seems to work for me.

**Comment by tpope** [comment]
This does work on a standard setup.
