### ISSUE TITLE
vim stopped when firing up :Gdiff command

### ISSUE THREAD

**Issue by eduOS** [tpope/vim-fugitive#666]
Hi all,

When I intended to merge two branches using Gdiff the Vim just stopped and brought me back to bash/zsh. After several attempts all Vim jobs were stopped, which can be checked by entering jobs. What's confusing is that whatever I enter into the shell the first time after the Vim fails, the prompt will remind me that `There are stopped jobs.` Thus, I thought, this issue may relate to bash/zsh.

I encountered a similar problem(the first time) after I installed oh-my-zsh, which has been issured [here](https://github.com/robbyrussell/oh-my-zsh/issues/4174). I avoided that problem by not setting zsh as the default shell.

Please help. Thanks,
Leo

**Comment by tpope** [comment]
What is `:set shellcmdflag?`?

**Comment by eduOS** [comment]
`-ic`

**Comment by tpope** [comment]
`-i` means load the the entire interactive shell config. oh-my-zsh's interactive config is massive. You've broken a lot more than Fugitive, I'm sure.

My recommendation is to drop `-i`.

**Comment by eduOS** [comment]
Thanks.

**Comment by tpope** [comment]
With `$BASH_ENV` or `.zshenv`, depending on your shell of choice.

**Comment by YaroSpace** [comment]
Sorry, possibility of life without Fugitive did not let me think straight.  Somewhere in my vim configs I have found `set shell=bash\ -i` which was the issue.
Thank you for quick reply and great, great plugin!
