### ISSUE TITLE
Gbrowse highlight links broken.

### ISSUE THREAD

**Issue by patrickdavey** [tpope/vim-fugitive#669]
Github seems to have changed their highlighting functionality.  If I open up vim, highlight a range then this sort of link is produced:

https://github.com/tpope/vim-fugitive/blob/master/plugin/fugitive.vim#L2319-2321

However, github no longer highlights it, and it should now be

https://github.com/tpope/vim-fugitive/blob/master/plugin/fugitive.vim#L2319-#L2321

I did have a quick try at patching the (linked above) lines, but they were escaped.  I will try take a look into it over the next week or so, just don't have time at the minute.

**Comment by tpope** [comment]
Looks like the second `#` is unnecessary.

This needs to be fixed in [rhubarb.vim](/tpope/vim-rubarb] too.

**Comment by patrickdavey** [comment]
Good call on not needing the second # .. not quite sure why I saw that the first time.  Anyway - quick PR if you want it.
