### ISSUE TITLE
`:Gread` doesn't work with explicit ref

### ISSUE THREAD

**Issue by petersohn** [tpope/vim-fugitive#672]
Since `:Gread` is equivalent to `git checkout -- <filename>`, I expect `:Gread <ref>` to be equivalent to `git checkout <ref> -- <filename>`. However, it does not do that. Instead it replaces the buffer with some information about ''<ref>'' (something similar to that `git log` would print).

**Comment by tpope** [comment]
Feel free to look into special casing this. Alternatively you can do `:Gread ref:%` or something like `:Gread ^` (which is equivalent to `:Gread HEAD^:%`).
