### ISSUE TITLE
:Gstatus window is empty in neovim

### ISSUE THREAD

**Issue by antoyo** [tpope/vim-fugitive#673]
Hello.
When I run the `:Gstatus` command in a git project, the preview window is empty.
This only happens in neovim.
Here is my neovim version:

```
NVIM 0.0.0-alpha+201508051117 (compiled Aug  5 2015 16:39:02)
Commit: b732a27c4e568ff0d56c74348e1c3fdf38364b81
```

I am using fugitive version 2.2 (I also tried the lastest revision in this repository).

Other commands like `:Gcommit` and `:Gpush` work.

Thanks to fix this.

**Comment by deivid-rodriguez** [comment]
Just trying neovim + vim-fugitive and this seems to be working fine with latest versions of both. I think this can now be closed ;)

**Comment by antoyo** [comment]
I am using neovim 0.1.0 and fugitive 2.2 and I still have this issue.

**Comment by deivid-rodriguez** [comment]
Ooops @antoyo , sorry about that. This cannot be closed then, but I guess it's something specific to your environment/config.

**Comment by antoyo** [comment]
Even with an almost empty `init.vim` file, it does not work:

```vim
let g:nvim_path = split(&runtimepath, ",")[0]

call plug#begin(g:nvim_path . "/plugged")
Plug 'fugitive.vim'
call plug#end()
```

**Comment by deivid-rodriguez** [comment]
It works for me with that `init.vim` file. This is under Linux.

**Comment by sondr3** [comment]
Not working for me either on OS X 10.11 with Neovim 0.1 and fugitive.

**Comment by torvitas** [comment]
Same issue here.
Fedora 25, neovim 0.2.0, fugitive 2.2

**Comment by tpope** [comment]
I can confirm it works for me. `:Gstatus` is basically just `:pedit .git/index` with the real work happening in a `BufReadCmd`, so it makes sense they would fail the same way.

**Comment by torvitas** [comment]
I can't open .git/index with neovim while fugitive active. I was unable to find a solution and switched back to vim.

**Comment by jonahx** [comment]
I'm seeing this as well.  Even stranger, in my case it was working fine, I made a commit via the `Gstatus` window, and closed nvim.

When I reopened it and ran `Gstatus` again, it was blank.  And I can't get it back.

**Comment by tpope** [comment]
`:Gstatus` has been completely redone. Open a fresh issue if it's still happening.
