### ISSUE TITLE
Should 3-way diff force 'equalalways' setting?

### ISSUE THREAD

**Issue by tommcdo** [tpope/vim-fugitive#674]
When looking at a 3-way diff from the `:Gstatus` window (i.e. typing `dv` on an "Unmerged paths" file), if `'noequalalways'` is set, the 3 windows are opened with widths of 50%, 25%, and 25%, like this:

```
+----------+-----+-----+
|          |     |     |
|    2     |  1  |  3  |
|          |     |     |
+----------+-----+-----+
|    :Gstatus          |
+----------------------+
```

It's easy enough to fix it, but still kind of annoying.

I think it could be pretty simple to store, set, and restore the `'equalalways'` setting while opening these windows. What do you think?

**Comment by tpope** [comment]
Yeah either force the option or perhaps more simply `wincmd =` after the fact.

**Comment by tommcdo** [comment]
The latter is definitely simpler and probably functionally identical.
