### ISSUE TITLE
:Gcommit works but throws errors messages when it's done

### ISSUE THREAD

**Issue by kriox26** [tpope/vim-fugitive#676]
Let's say i'm on the root of my repo, I created a file named `file.rb`, made some changes, run `:Gwrite`, then `:Gcommit`. After git commit a buffers opens to edit the commit message, so I edit the message, save the buffer, and when I want to close that buffer the following error appears:
```
Error detected while processing function <SNR>54_FinishCommit..<SNR>54_Commit:
line   26:
E480: No match: `=dir`
Error detected while processing function <SNR>54_FinishCommit:
line    4:
E171: Missing :endif
```
The commit works great, but it's annoying because the commit message buffer remains opened and I can't close it.
I'm running the latest build of NeoVim. vim-fugitive at: `b319b69453`, and I also have vim-git.(using zsh)
PD: On Vim this does not happens, so if I run `:Git commit` after it opens a new Terminal buffer with vim inside, I can edit the message save it and quit with no error messages, so I supose it's a NeoVim/vim-fugitive issue.

**Comment by tpope** [comment]
Sounds like a `'wildignore'` problem.

**Comment by kriox26** [comment]
It was!!! I had `set wildignore+=*/.git/*,*/tmp/*,*.so,*.swp,*.zip` to make CtrlP a bit faster. Removed the .git and it worked perfectly, thanks for the immediate response!!! Closing :+1:
