### ISSUE TITLE
Glog outputs to terminal instead of quickfix window

### ISSUE THREAD

**Issue by mddubs** [tpope/vim-fugitive#677]
Running :Glog, :Gpush, :Gpull, or :Gfetch seems to kick me out to the terminal temporarily to display the output instead of opening a quickfix window.  Oddly enough, :Gstatus and :Gcommit work just fine.  Screenshots attached.

![screenshot from 2015-08-20 16 29 48](https://cloud.githubusercontent.com/assets/366233/9394913/2956b19c-4759-11e5-83cc-7eca9068cbc9.png)

![screenshot from 2015-08-20 16 33 02](https://cloud.githubusercontent.com/assets/366233/9394917/3144864a-4759-11e5-9099-315aa874067e.png)

**Comment by tpope** [comment]
Yes, they work exactly the same as `:grep`.

**Comment by dave-kennedy** [comment]
If they work the same then shouldn't the following autocmd cause the quickfix window to open as indicated in the readme?

`autocmd QuickFixCmdPost *log* cwindow`

**Comment by lfv89** [comment]
Hi @tpope.

There is something weird then, since `:help fugitive` says that `Glog` should open a quickfix window, and now I'm not sure which one is wrong, the implementation, the `:help fugitive` or neither one of them.

From the help:


```
:Glog [args] Load all previous revisions of the current file into the quickfix list.
```

**Comment by tpope** [comment]
Neither "open" nor "window" appear in that description.

**Comment by lfv89** [comment]
If someone else stumbles on this PR, what he meant is the `Glog` content is indeed loaded into the quickfix list, but doesn't necessarily opens it. If one opens the quickfix list using `copen` after the `Glog` command then the expected output is shown.

Thanks @tpope.

**Comment by dave-kennedy** [comment]
You can also add `autocmd QuickFixCmdPost *grep* cwindow` to your .vimrc, then it will open automatically. It's mentioned in the readme.

**Comment by huangzonghao** [comment]
But is there anyway that the contents being loaded silently to the quickfix list? I mean without being kicked out of vim?

**Comment by tpope** [comment]
Some combination of `:silent`/`:silent!` and `:redraw`/`:redraw!` will do the trick. I forget which if any needs a bang.

**Comment by huangzonghao** [comment]
Hey I bypassed the problem by setting a key map for Glog with extra <CR> on the end. The command looks like `nmap xx :Glog<CR><CR>` and it worked quite well. Just in case someone else got the same issue :)

**Comment by gauteh** [comment]
Not sure about the implications of this, but setting `shellpipe` prevent output being copied to stdout. I still need a `:redraw!` to get file rendering right. In particular with split windows.

```
set shell=bash
set shellpipe=>
nnoremap <leader>gl :silent! Glog<CR> :redraw!<CR>
```

Also affects `grep` and others like `make`.
