### ISSUE TITLE
Gcommit does allow me to input commit message

### ISSUE THREAD

**Issue by yaojingguo** [tpope/vim-fugitive#679]
After I input `:Gcommit` in Gvim, a split window with the following content is opened:

```
# On branch master
# Your branch is up-to-date with 'origin/master'.
#
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   _posts/2014-11-23-linux.md
#
no changes added to commit (use "git add" and/or "git commit -a")
```
There is no a empty line above `# On branch master` for me to input commit message.

**Comment by tpope** [comment]
Maybe you should try staging a file first

**Comment by yaojingguo** [comment]
Running `:Git add .` and then `:Gcommit` works. But `:Gcommit .` does not need `:Git add .`
