### ISSUE TITLE
Gdiff not working after updating to Git 2.5.0

### ISSUE THREAD

**Issue by petobens** [tpope/vim-fugitive#680]
With the following minimal vimrc:

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/fugitive/
filetype plugin indent on
```

If I open Gvim, start editing a file with uncommited changes and run `:Gdiff` I get an error stating:

```
Error detected while processing function <SNR>64_Diff:
line   51:
E97: Cannot create diffs
```
I read this [issue](https://github.com/tpope/vim-fugitive/issues/541) but the solution posted there doesn't work in my Windows machine since `set shellcmdflag?` returns `shellcmdflag=/c`. 

For the record `:Gdiff` worked just fine until yesterday when I decided to update from `Git 1.9.0` to `Git 2.5.0`. 

Any help will be greatly appreciated. Thanks in advance.

**Comment by tpope** [comment]
Try doing it manually:
```
:diffthis
:Gsplit
:diffthis
```

Same error?

**Comment by petobens** [comment]
Hi @tpope . Thanks for the quick reply. Doing it manually generates the same `E97: Cannot create diffs` error.

**Comment by justinmk** [comment]
@petobens is git in your cmd.exe PATH?

**Comment by tpope** [comment]
On which step?

**Comment by petobens** [comment]
On the last one.

For the record: I use [this](https://tuxproject.de/projects/vim/) 64bit Vim build, I installed Git 2.5.0 from [here](https://git-scm.com/download/win) and I have `C:\prog-tools\Git\cmd` in my path. All other fugitives commands (such as `Glog`, `Gstatus`, `Gcommit`) work  fine.

**Comment by tpope** [comment]
If it's on `:diffthis` then it has nothing to do with fugitive. My guess is the new version of Git came with its own version of `diff` that's getting in the way.

**Comment by petobens** [comment]
@tpope, I have no idea if this is in fact the cause of my problem but  according to this [answer](http://stackoverflow.com/a/30699239) Git 2.5 added winmerge as a builtin tool.
I'm sorry for a new question (but I'm completely lost): if the new version of Git has a its own version of diff that might be getting in the way, can you suggest possible workaround? Once again thanks for the help.

**Comment by justinmk** [comment]
@petobens What does `!where diff` report from gvim?

**Comment by petobens** [comment]
Hi @justinmk, thanks for your interest. `!where diff`from Gvim returns an error: `INFO: Could not find files for the given patterns(s).`. Where should the diff executable be located? Once again thanks.

**Comment by justinmk** [comment]
Oh, I get it. The tuxproject build does *not* include `diff.exe`, they really need to fix that. And Vim should really show a better error message that avoids this pain for new users.

**Comment by justinmk** [comment]
Just plop a `diff.exe` in the top level of your `vim/` program files folder.

**Comment by petobens** [comment]
@justinmk thank you!!  I copied the `diff.exe` from `C:\prog-tools\Git\usr\bin` to my top level vim directory and the problem is solved. Thank you once again!!

**Comment by petobens** [comment]
@justinmk also thanks for your awesome work in neovim! (I hope to try it one of these days on Windows) .
