### ISSUE TITLE
Fugitive commands not working in a worktree directory

### ISSUE THREAD

**Issue by Serabe** [tpope/vim-fugitive#682]
If inside a git repo we use the command `git worktree` to create a different worktree in our file system and go there, then fugitive does not detect the project as using Git.

This directory would contain a file .git with `gitdir: /absolute/path/to/git/dir/for/this/worktree`.

I don't mind giving this a try, but my VimScript is close to 0.

**Comment by glittershark** [comment]
#671

**Comment by RsrchBoy** [comment]
Also, this seems to be a duplicate of #655.

**Comment by RsrchBoy** [comment]
Well. "duplicate"

**Comment by tpope** [comment]
Yeah see those 2
