### ISSUE TITLE
Neovim throws E499 when args include "%"

### ISSUE THREAD

**Issue by elentok** [tpope/vim-fugitive#686]
For example, running

```
:Git add %
```

neovim throws the following exception:

```
E499: Empty file name for '%' or '#', only works with ":p:h": terminal git add %
```

It seems to be a result of the [`tabnew` command](https://github.com/tpope/vim-fugitive/blob/master/plugin/fugitive.vim#L686), it creates a new blank tab where "%" is empty.

I can think of several possible solutions:

1. Change `tabnew` to `tabedit`
2. Remove `tabnew` completely (so the terminal will open in the same window)
3. Expand `%` signs before calling `tabnew`

What do you think?

**Comment by tpope** [comment]
Does removing `tabnew` work as expected? I would think leaving the buffer for a terminal would be problematic.

**Comment by elentok** [comment]
I agree, and also I've noticed that removing `tabnew` is only relevant when there is only one open window, since once the command ends it goes back to the previous buffer.

However, if you have multiple windows, once the command ends it closes the previous window, and the file you were working on disappears...

I thought about a few more options:

1. `split` or `vsplit` (personally, I find `vsplit` more useful for git-related tasks since I need more height than width).
2. `tab split`

**Comment by tpope** [comment]
I lean against splits because they'll disrupt the existing window layout. I guess go with `tabedit`.

**Comment by tpope** [comment]
Neovim's omission of a `:sterminal` command (in the spirit of `:sbuffer`, `:stag`, etc) is really obnoxious.

**Comment by justinmk** [comment]
@tpope We're still figuring out the UX for `:terminal`. We may end up restoring some of the missing behavior of `:!` so that `:terminal` isn't needed as a workaround.
