### ISSUE TITLE
No luck running :GBlame HEAD (Git on Windows shows Not commited yet)

### ISSUE THREAD

**Issue by bjartwolf** [tpope/vim-fugitive#688]
In Windows I get these (Not commited yet) when running :Gblame
![image](https://cloud.githubusercontent.com/assets/1174441/9953400/bad0dcf4-5de0-11e5-9983-9bf2a0a2da55.png)

I am trying to figure out how to, or if it is possible, to send it as a parameter to Gblame but so far all the options I've tried hasn't worked for me.

Running :Git blame HEAD % works fine.

Also, running g? in the git blame section after running :Gblame and g? shows.
![image](https://cloud.githubusercontent.com/assets/1174441/9953440/21962c0a-5de1-11e5-9004-897ae3491f4d.png)

**Comment by justinmk** [comment]
@bjartwolf What does `set wildignore?` say?

**Comment by bjartwolf** [comment]
Had to remove the plugin due to a repo that ended up corrupt, will reinstall later and try on a dummy repo.

**Comment by tpope** [comment]
This was probably a line ending issue, which should be better supported now.
