### ISSUE TITLE
:Gstatus functions silently fail if index.lock exists

### ISSUE THREAD

**Issue by justinmk** [tpope/vim-fugitive#690]
Steps to reproduce:
1. `:Gstatus` in a repo that does _not_ have `.git/index.lock`.
2. `touch .git/index.lock` 
3. In the `:Gstatus` window, invoking `-` on a file fails silently.

Another unexpected behavior is that if the the `index.lock` already exists, invoking `:Gstatus` will show the result of `git ls-files -s` instead of the typical `:Gstatus` buffer.

In both cases above, no error is shown. This is contrary to `:Gcommit` which shows an error message:

```
fugitive: git process crashed in this repository earlier. Make sure no other git
```

I searched the issues but did not see a discussion of this. 

Tested on Windows / git `2.5.0.windows.1` and ubuntu / git `2.0.0`.

**Comment by h3xx** [comment]
Other symptom I noticed:

`:Gstatus` window is completely blank if .git/index.lock exists, no error messages printed in error bar.

Steps:

1. `git init`
2. `touch .git/index.lock`
3. `vim +Gstatus`

**Comment by tpope** [comment]
This displays an error now.
