### ISSUE TITLE
Support Cygwin Git with native Windows GVim

### ISSUE THREAD

**Issue by vadz** [tpope/vim-fugitive#691]
This used to work before, but the latest Cygwin git version (2.5.1) doesn't accept mixed style, i.e. Windows with slashes, paths such as `c:/foo/bar` any longer and requires the use of Unix paths i.e. `/cygdrive/c/foo/bar`.

For now I've worked around the problem by using a `git-fugitive` wrapper translating `--git-dir` on the fly but there are other problems in the code related to Vim/git paths mismatch when using the native Vim and Cygwin git, e.g. comparing paths with `GIT_WORK_TREE` and `GIT_DIR` is never going to succeed and there are probably more.

I could try to fix them by adding `vim_to_git_path()` and `git_to_vim_path()` functions and using them appropriately, but before spending time on this I'd like to ask if there would be any interest in improving Cygwin support?

**Comment by tpope** [comment]
My interest is somewhat limited. In my experience trying to stitch together cygwin and win32 vim has always dicey; much better to use a cygwin vim instead. Though I wouldn't refuse a solution that kept the maintenance burden to a minimum.

**Comment by tpope** [comment]
Things are much better structured now and I would be amenable to this. The function `s:Slash()` is basically your `vim_to_git_path()`, and `s:PlatformSlash()` is `git_to_vim_path()` (`PlatformSlash` meaning "Windows slashes", we can certainly rename these). You can start by updating those functions and seeing what does and does not work. There are definitely additional `s:PlatformSlash()` calls that will be needed.

**Comment by vadz** [comment]
Thanks, I'll try to return to this and at least check what breaks now if I drop my wrapper.

**Comment by tpope** [comment]
I've gone ahead and added `FugitiveGitPath()` and `FugitiveVimPath()`. You can override these in `after/plugin/fugitive.vim` if you want to keep you vim-fugitive work tree clean. Be sure to share what you come up with so other people can try!

**Comment by tpope** [comment]
Those functions solve this in theory. If anyone does this in practice please report back with your results.

**Comment by shmup** [comment]
I guess something like this? Though this would just be set when vim starts:

```
function! StartsWith(longer, shorter) abort
  return a:longer[0:len(a:shorter)-1] ==# a:shorter
endfunction

if StartsWith($PWD, '/mnt')
  let g:fugitive_git_executable = '/mnt/c/PROGRA~1/Git/cmd/git.exe'
  let g:fugitive_git_executable = "/mnt/c/PROGRA~1/Git/cmd/git.exe"
endif
```

I'm getting warmer.. I think?

**Comment by tpope** [comment]
I don't think your approach is tenable, on two counts:

* There's no guarantee `FugitiveGitPath()` will be called before Fugitive tries to invoke Git, so you can't set `g:fugitive_git_executable` there.
* You can't rely on `$PWD`, as there's no guarantee the current repository is the same as the current working directory. Also, it doesn't update after Vim has started.

**Comment by shmup** [comment]
> I don't think your approach is tenable, on two counts:
> 
>     * There's no guarantee `FugitiveGitPath()` will be called before Fugitive tries to invoke Git, so you can't set `g:fugitive_git_executable` there.
> 
>     * You can't rely on `$PWD`, as there's no guarantee the current repository is the same as the current working directory. Also, it doesn't update after Vim has started.

Ah, thanks.

I was getting lucky with the race condition re: "called before or after". And thanks for reminding me about `$PWD`, instead of using `getcwd()`

**Comment by shmup** [comment]
I've updated it to `getcwd()` and for now I'm going to just lazily, untenably, assume that yes in fact `FugitiveGitPath` is wrapping the various git commands fugitive provides, and I'm Still Gonna Send It

![image](https://user-images.githubusercontent.com/118710/187075737-1de6c1a4-3c33-4d7b-93d6-873959bcafb0.png)

**Warning to others:** may not work as intended

**Comment by shmup** [comment]
I've updated it to `getcwd()` and for now I'm going to just lazily, untenably, send it

![image](https://user-images.githubusercontent.com/118710/187075737-1de6c1a4-3c33-4d7b-93d6-873959bcafb0.png)

**Warning to others:** may not work as intended

**Comment by tpope** [comment]
The current working directory isn't guaranteed to be the current repository, so you've just swapped one problem for another.

**Comment by tpope** [comment]
Also I just checked the source and it [retrieves `g:fugitive_git_executable`](https://github.com/tpope/vim-fugitive/blob/b411b753f805b969cca856e2ae51fdbab49880df/autoload/fugitive.vim#L796) _before_ [calling `FugitiveGitPath()`](https://github.com/tpope/vim-fugitive/blob/b411b753f805b969cca856e2ae51fdbab49880df/autoload/fugitive.vim#L809).  You're not "getting lucky with the race condition" you're just failing to test it correctly.

**Comment by shmup** [comment]
:gif of homer disappearing into a bush and never coming back:

Understood, lol. Thank you for taking the time to point these things out

**Comment by tpope** [comment]
> Forgot this is how I do a thing:
> 
> ```
> nnoremap <silent> ,cd :lcd %:p:h<cr>
> nnoremap <silent> ,cr :lcd <c-r>=FugitiveWorkTree()<cr><cr>
> ```
> 
> So.. probably should have used that. Please tell me _that is the way_ lol. It must be the way..

You'll want a `fnameescape()` in there for maximum robustness, but you could do that, yeah. Or use `:Glcd`.

**Comment by shmup** [comment]
> You'll want a `fnameescape()` in there for maximum robustness, but you could do that, yeah. Or use `:Glcd`.

Ah, thanks again

---

Ok I comment out:

```
" if InWindows()
"   let g:fugitive_git_executable = '/mnt/c/PROGRA~1/Git/cmd/git.exe'

"   return substitute(a:path, '^/mnt/\(\a\)/', '\1:/', '')
" endif
```

I `cd` into a `/mnt` repo, open vim, do a `:Git`, and it's a good 10+ seconds.

I do this without commenting that out, and it's a good 500 ms.

I do want to know why, maybe I'll figure it out

**Comment by tpope** [comment]
> I only want this stuff to operate when I'm operating in a Windows path:
> 
> ```viml
> let g:fugitive_git_executable = "/mnt/c/PROGRA~1/Git/cmd/git.exe"
> 
> function! FugitiveGitPath(path) abort
>   return substitute(a:path, '^/mnt/\(\a\)/', '\1:/', '')
> endfunction
> 
> function! FugitiveVimPath(path) abort
>   return substitute(a:path, '^\(\a\):/', '/mnt/\1/', '')
> endfunction
> ```

My recommendation would be to dig in on this approach. Add more `substitute()` calls for things like `/home`, etc, and get it to where you can use the Windows version for all repos.

> I `cd` into a `/mnt` repo, open vim, do a `:Git`, and it's a good 10+ seconds.

That does sound excessive even by WSL2 standards, but I'm out of my wheelhouse.
