### ISSUE TITLE
Not working with git-worktree feature

### ISSUE THREAD

**Issue by ashcatch** [tpope/vim-fugitive#692]
The fugitive plugin does not work with a checkout using the new (I think starting with git 2.5) [git-worktree feature](https://git-scm.com/docs/git-worktree).

For example:

     cd /tmp
     git clone https://github.com/tpope/vim-fugitive.git
     cd vim-fugitive
     git worktree add -b snafu /tmp/snafu
     cd /tmp/snafu

In the `/tmp/snafu` directory, the fugitive plugin does not detect that this is a git directory, so nothing of the fugitive plugin is available. But on the command line, git works pretty much normally.

I looked into a fix, but I found my knowledge on low-level git and how the fugitive plugin works to be not sufficient to produce a patch.

Some additional info on how things look with worktree: in the above example, there is a file `/tmp/snafu/.git` with the following content:

    gitdir: /private/tmp/vim-fugitive/.git/worktrees/snafu

(I'm on OS X, so `/tmp` is actually a symlink to `/private/tmp`, but it does not work in other, non-symlinked directories either, so this is not the problem here.)

And the directory `/private/tmp/vim-fugitive/.git/worktrees/snafu` contains the following files and directories:

    HEAD
    commondir
    gitdir
    index
    logs

So this is not the full content of a typical `.git` directory (`objects` and `refs` are missing, e.g.) -- I think git uses that from the original's git checkout directory; the `commondir` file's content is `../..` and `gitdir` file's content is `.git`. But the last part is just what I observed and more or less guessing.

Any chance that this can be fixed in the fugitive plugin?

**Comment by glittershark** [comment]
Dupe of #671, #682

**Comment by ashcatch** [comment]
Thanks for pointing this out... seems my checking if an issue for this already exists was flawed (shouldn't have searched for only open issues)...
