### ISSUE TITLE
Gblame: blaming "Not Committed Yet" lines

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-fugitive#694]
I often end up in a situation, where I want to blame lines around `Not Committed Yet` addition by myself, and would appreciate a way to blame the "committed" version.

Is that possible already?
Could `P` (`reblame at [count]th parent (like HEAD^[count])`) be made to handle this?

**Comment by tpope** [comment]
Sounds like a giant rat hole, but do of course feel free to investigate.

**Comment by blueyed** [comment]
What's your usual workaround in this case?

**Comment by tpope** [comment]
`:Gedit` to get to the staged version, and `:Gblame` again.
