### ISSUE TITLE
:Gwrite crashes, fails to write buffer, and adds all changes in working directory

### ISSUE THREAD

**Issue by tobanw** [tpope/vim-fugitive#696]
I just updated my vim plugins after probably a few months and now I'm getting this error when trying to write and add with :Gw

```
"~/.../working-dir/"
Error detected while processing function <SNR>23_Write:
line    77:
E502: "~/.../working-dir/" is a directory
```

The buffer doesn't even get written, and all changes in the pwd get added (even untracked files).

**Comment by tpope** [comment]
What is `:echo fugitive#buffer().path()`?

**Comment by tobanw** [comment]
It's blank on the two trouble files I tested with, but now I'm trying other files and it shows the filename.

I'm wondering if there's a conflict with [ranger](https://github.com/hut/ranger) (a terminal-based filemanager), because the bug shows up when I launch vim from ranger, but not when I launch vim from the command line.

**Comment by tpope** [comment]
Could also be related to symlink tomfoolery,

**Comment by tobanw** [comment]
Yes, perhaps -- all my files are in one main (soft) symlinked directory.

**Comment by tpope** [comment]
Ok, it's on you to figure out what's going on. I pushed up a proper error message for when it happens.

**Comment by bogem** [comment]
Same issue

**Comment by tpope** [comment]
Same response

**Comment by bogem** [comment]
I haven't got any symlinks in project
In `:echo fugitive#buffer().path()` there is a path of my file

**Comment by tpope** [comment]
So are you getting the *exact* same error message?

**Comment by bogem** [comment]
Not exactly the same

I type `:Gwrite .`
fugitive says: `fugitive: file has uncommitted changes (use ! to override)`

I type `:Gwrite! .`
fugitive says:
```
~/nehm
Error detecting while processing function <SNR>50_Write:
line 80:
E502: "~/nehm" is a directory
Press ENTER or type command to continue
```
P.S. `~/nehm` is a root directory of my project

**Comment by tpope** [comment]
Why are you passing a dot?

**Comment by bogem** [comment]
To add all project
I thought that `:Gwrite .` is the same `git add .`

**Comment by bogem** [comment]
Or how to add all project?

**Comment by glittershark** [comment]
`:Git add .`

**Comment by bogem** [comment]
Ok. Thanks @glittershark 
Problem solved
