### ISSUE TITLE
Feature Request: Jump to changed hunk from :Gcommit --verbose

### ISSUE THREAD

**Issue by aquach** [tpope/vim-fugitive#697]
In my workflow, I rely primarily on this shortcut:

```
nnoremap <Leader>c :silent Git add -A<cr>:Gcommit --verbose<cr>
```

which allows me to eyeball everything that's dirty and commit it in one go. I'd like to be able to use the diff output included in `git commit --verbose` to jump to the changed block. This might already be possible, but I didn't see any functionality for this in the documentation.

Here's a (poorly written) version I've written that accomplishes this in Python so that one can just hit Enter anywhere in the diff block to jump to the hunk.

```vim
function! s:GoToFileFromGitCommitDiff()
  python << endpython
import vim
import re
import os

def find_str_upwards(buf, start_line_num, match_regex):
    line_num = start_line_num
    while line_num > 0 and not re.match(match_regex, buf[line_num]):
        line_num -= 1

    return buf[line_num]

win = vim.current.window
line_num = win.cursor[0] - 1

line_match = find_str_upwards(win.buffer, line_num, r'^@@')
file_match = find_str_upwards(win.buffer, line_num, r'^\+\+\+')

if line_match and file_match:
  coords = line_match.split(' ')[2][1:]
  line, col = coords.split(',')

  filename = file_match.split(' ')[1][2:]

  git_directory = vim.eval("expand('%:p:h:h')")

  vim.command('edit %s' % os.path.join(git_directory, filename))

  win.cursor = (int(line), int(col))
endpython
endfunction

augroup filetype_gitcommit
  autocmd!
  autocmd FileType gitcommit nnoremap <buffer> <Enter> :call <SID>GoToFileFromGitCommitDiff()<cr>
augroup END
```

If this is relevant to your interests, I can turn it into a PR.

**Comment by tpope** [comment]
We already have something similar for when editing historical commits (`:Gedit HEAD^`) that could be adapted. The thing I'm hung up on is abandoning the commit message to open the file in the same window. This seems confusing and inappropriate, and definitely shouldn't be the only option. Perhaps we can use `gf` and friends?

**Comment by aquach** [comment]
Sweet, thanks!
