### ISSUE TITLE
is it possible Gdiff previous file like tig foo.c

### ISSUE THREAD

**Issue by lecheel** [tpope/vim-fugitive#698]
tig foo show dedicate file history in diff view how can do in vim-fugitive

**Comment by lecheel** [comment]
fugitive extension extradite seems doing for this part http://int3.github.io/vim-extradite/

**Comment by glittershark** [comment]
`:Glog` will load the commits changing a file into the quickfix window

**Comment by glittershark** [comment]
[docs](https://github.com/tpope/vim-fugitive/blob/master/doc/fugitive.txt#L99-L105)

**Comment by h3xx** [comment]
If you're looking to view the content of all commits that hit the file opened in a buffer, here's a workflow you could use:

1. `:Glog` while you have a file in a git working directory opened.
2. `:cw` - open quickfix window
3. Press Enter on a file in the quickfix window. This brings up the state of the file after that commit was applied.
4. Press `C` in normal mode to view the content of the commit you opened.
5. `:Gedit` to get back to your working copy.

**Comment by tpope** [comment]
`:Glog` no longer defaults to the current file so that will no longer work, but you can call `:Glog %` to the same effect. That loads the commit so you don't need to hit `C`.
