### ISSUE TITLE
Weird coloring to text on Gcommit

### ISSUE THREAD

**Issue by FuzzOli87** [tpope/vim-fugitive#699]
When I'm trying to do a commit, the text starts off at a yellow color then turns white after about 40 chars. Any new line after that is unreadable, as in it's a dark color that makes it "invisible" with my dark background.

**Comment by tpope** [comment]
This is from vim-git. The first line is hinted at being no longer than 50 characters. The second should be blank and will be flagged as an error if not. Further lines should be normal.

**Comment by FuzzOli87** [comment]
Yeah, I realized the mistake I've made after some more intensive Googling. Thanks!
