### ISSUE TITLE
Gbrowse escaping GitHub line numbers OS X

### ISSUE THREAD

**Issue by keith** [tpope/vim-fugitive#701]
I have noticed that when using `:Gbrowse` in visual mode with files that have spaces in the paths, the `#` character for specifying the line numbers is also escaped, making it 404 on GitHub.

For example if you're editing a file in the repo with path `foo/Space Path/file.txt`, and you use `:'<,'>Gbrowse`, you'll open this URL:

```
https://github.com/foo/bar/blob/master/foo/Space%20Path/file.txt%23L2
```

The problem here is the `%23` instead of the `#`. This is only the behavior when there is a space in the path.

I know the escaping isn't being done in fugitive but I'm hoping someone might have some bright ideas about how to work around this.

**Comment by tpope** [comment]
Do you have a `:Browse` command?

**Comment by keith** [comment]
No I haven't customized this.

**Comment by keith** [comment]
I can reproduce this with my vimrc just including:

```vim
source ~/.vim/bundle/vim-fugitive/plugin/fugitive.vim

filetype plugin indent on
syntax enable
```

**Comment by tpope** [comment]
In that case it's almost certainly a netrw quirk. Try

    :call netrw#BrowseX('https://github.com/foo/bar/blob/master/foo/Space Path/file.txt#L2')
    :call netrw#NetrwBrowseX('https://github.com/foo/bar/blob/master/foo/Space Path/file.txt#L2')

If the space is a trigger than it is probably doing something clever with conditional escaping. It would probably be prudent for us to do a preliminary escaping to side step the issue. After all, the URL we construct with an unescaped space is technically invalid.

**Comment by keith** [comment]
Yea it actually looks like this is solved by preemptively escaping spaces from fugitive:

```vim
let url = substitute(url, " ", "%20", "g")
```

Doing this right before passing the URLs to netrw solves the problem.

**Comment by tpope** [comment]
https://github.com/tpope/vim-unimpaired/blob/1ec6af944e3bac5f8ccf0bfa18692a83828bde04/plugin/unimpaired.vim#L305 is a more general solution. Just need to throw `/` and perhaps a couple of other characters in the negated character class.

**Comment by keith** [comment]
Submitted a PR https://github.com/tpope/vim-fugitive/pull/703

Let me know if you can think of any other characters we need to add.
