### ISSUE TITLE
Gvdiff/Gdiff for all changes

### ISSUE THREAD

**Issue by jordwalke** [tpope/vim-fugitive#704]
It would be very nice to be able to see a single (vertically, ideally) scrolling window that has all of the changes in your repo - not just the current file.

**Comment by tpope** [comment]
You mean like `:Git! diff`?

**Comment by jordwalke** [comment]
Ah, I mispoke - what I meant was a single diff view for all file changes, but with the side by side locked scrolling behavior. Does such a thing exist?

**Comment by tpope** [comment]
So you want it to just concatenate all the files together in each pane? No, such a thing does not exist, and doesn't really seem practical.

**Comment by rasha108bik** [comment]
It would be a great functionality as it seems to me
