### ISSUE TITLE
Gblame failing with syntax errors

### ISSUE THREAD

**Issue by carlos4ndre** [tpope/vim-fugitive#705]
I'm getting syntax errors when running Gblame:

```
Error detected while processing function <SNR>125_BlameSyntax: line 36:
E117: Unknown function: csapprox#per_component#Approximate
E15: Invalid expression: csapprox#per_component#Approximate(r, g, b)
```
I'm a Vim newbie so it is most likely I'm doing something wrong :smile:

**Comment by tpope** [comment]
Are you using https://github.com/godlygeek/csapprox?

**Comment by carlos4ndre** [comment]
No, and you are right that's the reason why it was failing. 
All good and ready to blame people, specially myself!

`:Gthanks @tpope`

**Comment by chrisbra** [comment]
Hi, have the same problem. And yes I am using csapprox

**Comment by tpope** [comment]
Looks like [the function is still there](https://github.com/godlygeek/csapprox/blob/d3c277b73e4618ac3d8ab12c2794d01e54b95e74/autoload/csapprox/per_component.vim#L49). Ball's in your court to explore further.

**Comment by chrisbra** [comment]
Yeah, i must have had an old version. Cloned the repo, deleted the old installation that must have been there for more than 5 years and now it works again. Thanks.
