### ISSUE TITLE
Is there a command is equal to $ commit -am 'something' ?

### ISSUE THREAD

**Issue by fortyMiles** [tpope/vim-fugitive#707]
If we changed a file which has been staged , when we modified this file, if use command commit -am, could just type once, do not need to **$git add _file_** first.

But, I **don't find** the command that could do the task like **$commit -am** in vim-fugitive.

Is there a command in vim-fugitive?

**Comment by tpope** [comment]
`:Gcommit` accepts exactly the same arguments as `git commit`.

**Comment by fortyMiles** [comment]
thx :)
