### ISSUE TITLE
:Gblame kills everything if NerdTree is open

### ISSUE THREAD

**Issue by matthiasbeyer** [tpope/vim-fugitive#708]
I have the following Nerdtree plugins:

* Nerdtree
* vim-nerdtree-tab
* vim-nerdtree-git-plugin

If nerdtree is opened and I execute `:Gblame` the blame buffer contains the raw output of `git blame` (so including the lines of the file) and has almost the size of my complete vim window, so it kills my buffer layout entirely. If the layout was something like 10%-90% (nerdtree - buffer) it is like 1%-98%-1% afterwards (nerdtree - git blame - buffer) afterwards.

Feel free to request screenshots.

**Comment by tpope** [comment]
Some combination of `'winwidth'` and `'minwinwidth'` might help. Fugitive will always attempt to make the blame window wide enough to accommodate all metadata, if possible.
