### ISSUE TITLE
Gdiff issue

### ISSUE THREAD

**Issue by chazubell** [tpope/vim-fugitive#709]
This may be a rehash of an old issue however when I run this command:
```
Gdiff master:CustomActions/silentinstallv4.5.au3 dev:CustomActions/silentinstal:lv4.5.au3. 

```
My goal was to see the difference between and old master branch that is working and the current test branch that is not quite there.  That said, the following error is produced:
```
fugitive: rev-parse 3fbe41559be5769d16688fb6fb34701d709d516:CustomActions/silentinstallv4.5.au3 dev:CustomActions/silentinstallv4.5.au3: fatal: Needed a single revision  
```

I have looked through the previous cases and I do not seem to find a match.   

Any pointers would be as always appreciated.  

-cdu

**Comment by tpope** [comment]
The `:Gdiff` syntax doesn't currently support that, but you can do

```
    Gedit master:CustomActions/silentinstallv4.5.au3
    Gdiff dev:CustomActions/silentinstal:lv4.5.au3
```

It would certainly be possible to make `:Gdiff` take 2 arguments, but given that the above is more flexible (e.g. you can do `:Gtabedit` to do the diff in a new tab) I'm not convinced that would be a good idea.

**Comment by chazubell** [comment]
Thank you very much.  As always, very much appreciated.

**Comment by chazubell** [comment]
Oh, yes.  I really enjoy using fugitive and your other work.  It really makes using Vim a more encompassing editor.
