### ISSUE TITLE
:Gstat fail when using with mintty+gitbash

### ISSUE THREAD

**Issue by serpent7776** [tpope/vim-fugitive#710]
`:Gstat` command fails on windows for me. I'm using conemu+gitbash+mintty configuration and vim from cream project.
This command fails when trying to `pedit` index file and tries to execute 
```
C:/apps/Git/usr/bin/bash -c "cmd /c "git --git-dir="C:/workspace/my_project/.git"
 -c "status.displayCommentPrefix=true" -c "color.status=false" -c "status.short=
false" -c "status.showUntrackedFiles=all" status > C:/apps/conemu/Data/Temp/VITF
1FD.tmp 2>&1" >C:/apps/conemu/Data/Temp/VIoF1FE.tmp 2>&1"
```
which spawns cmd.exe and does nothing more ("cmd /c" is making the command not working I guess, but I don't know where does it come from).
When I try to execute `:Gstat` in vim shipped with gitbash it works correctly. `:Gblame` works for both.
This might be some vim configuration issue, but I'm not sure. One thing I noticed is my vim has 'noshellslash'; this option is not even defined for vim shipped with gitbash.
Trying to directly `pedit` index file cause exact same issue.
I also tried to disable other plugins, but it changed nothing.

**Comment by tpope** [comment]
https://github.com/tpope/vim-fugitive/blob/dba8a0705d95cda76d599bb7d09964d67741a5c5/plugin/fugitive.vim#L2424-L2429 is where the `cmd /c` is coming from, which in turn is dependent upon https://github.com/tpope/vim-fugitive/blob/dba8a0705d95cda76d599bb7d09964d67741a5c5/plugin/fugitive.vim#L30. I'm confused about why you're getting forward slashes when that shellslash conditional is detecting otherwise.

Can you report back on
    :set shellquote? shellxquote?

**Comment by serpent7776** [comment]
the problematic vim says
```
shellquote=
shellxquote="
```
s:winshell function returns 1

vim shipped with gitbash says
```
shellquote=
shellxquote=
```
s:winshell function returns 0

I noticed that setting `shellslash` fixes this issue

**Comment by tpope** [comment]
If `:set shellslash` works you should just do that. The original meaning of `'shellslash'` was essentially "I am using a shell that requires forward slashes" aka a UNIX like shell.
