### ISSUE TITLE
:Gblame doesn't work in working trees created with git worktree

### ISSUE THREAD

**Issue by jrmuizel** [tpope/vim-fugitive#716]

**Comment by knirch** [comment]
b:git_dir doesn't get set when .git is a file. (or in my case b:git_dir got set to my /home/knirch/.git), so vim-fugitive doesn't work at all with git worktree right now.

Manually setting b:git_dir to what .git points to doesn't do much good either, things break down quite amusingly.

**Comment by knirch** [comment]
https://github.com/tpope/vim-fugitive/pull/671 seems like an effort to fix this.

**Comment by tpope** [comment]
The effort was successful.
