### ISSUE TITLE
:Gstatus `D` on a file with "$" in its name

### ISSUE THREAD

**Issue by qstrahl** [tpope/vim-fugitive#717]
Might apply to other characters, too; it opens `path/to/\$file.js` (the name of the file in the index is escaped too) rather than `path/to/$file.js`, resulting in empty buffers.

**Comment by tpope** [comment]
I think this came up before but I can't find anything. I think a config var or something affects it? Could me mixing it up with something else.

**Comment by tpope** [comment]
Fixed by new `:Gstatus`.
