### ISSUE TITLE
commit templating

### ISSUE THREAD

**Issue by aemonge** [tpope/vim-fugitive#719]
It would be awesome if we could template our commits. For example, make all our commit to be the following:
[type] : [title]
[description]

It should be text-based, since It's easier ;)

**Comment by tpope** [comment]
Git has `prepare-commit-msg` for that.

**Comment by aemonge** [comment]
Thanks a lot @tpope  !!!!!

**Comment by aemonge** [comment]
I've got this commit, how can I tell fugitive to enter it's text after my commit message ?

*.git/hooks/prepare-commit-msg*
```bash

echo '<type>(<component>): <subject>' >> $1
echo '' >> $1
echo '<body>' >> $1
echo '' >> $1
echo '# types: feat, fix, docs, style, refactor, test, chore (mantian)' >> $1

```

**Comment by aemonge** [comment]
I've managed by doing the following:

```bash

echo '<type>(<component>): <subject>' > .prepare-commit-msg-temp
echo '' >> .prepare-commit-msg-temp
echo '<body>' >> .prepare-commit-msg-temp
echo '' >> .prepare-commit-msg-temp
echo '# types: feat, fix, docs, style, refactor, test, chore (mantian)' >> .prepare-commit-msg-temp

{ cat .prepare-commit-msg-temp; cat $1; } > $1.new
mv $1{.new,}
rm .prepare-commit-msg-temp
```

but it doesn't seams clean to me, what do you think ?

**Comment by aemonge** [comment]
More over, it's making my comments twice. But this issues is just when committing over fugitive .....

**Comment by tpope** [comment]
I don't have a deep understanding of how `prepare-commit-msg` works, but I am pretty sure it's the hook's responsibility to guard against commenting twice. Otherwise, not just Fugitive, but also `git commit --amend` will have issues. So basically, check the file at `$1` to see if it already has your additions.

**Comment by aemonge** [comment]
I've done it, but I wasn't sure how's resposability was. But it makes sense, that it should be the hook, since `--amend`. I'll leave my hook here if someone finds it interesting (:

https://gist.github.com/aemonge/9e60332c6a3e7147ee8e
