### ISSUE TITLE
Odd `Git(...)` wrapping branch name in statusline

### ISSUE THREAD

**Issue by timfayz** [tpope/vim-fugitive#721]
Today I've installed the plugin, but I can't understand why there is odd `Git()` wrapper surrounding the current branch name. Please, see the screenshot:

![screenshot from 2015-11-23 21 54 21](https://cloud.githubusercontent.com/assets/6209197/11346349/47942b0c-922d-11e5-90cd-abc64624ea82.png)

Any ideas how can I leave just a branch-name instead Git(branch-name)?

**Comment by tpope** [comment]
That's how I designed it. You can manipulate the returned string if you desire something else.

**Comment by timfayz** [comment]
Got it, thank you)
