### ISSUE TITLE
:Gpush freezes when used with neovim

### ISSUE THREAD

**Issue by lzh9102** [tpope/vim-fugitive#722]
Hello,

When running Fugitive with Neovim, the `:Gpush` command freezes if a password prompt is shown.

![gpush](https://cloud.githubusercontent.com/assets/1400062/11342796/03b46b9c-9244-11e5-9783-e45ef6076330.png)

This is because neovim doesn't redirect keyboard input to the stdin of the subprocess. The only way to quit is to kill the neovim process.

The `:Git` command already [makes use of the neovim terminal emulator](https://github.com/tpope/vim-fugitive/blob/1ecd12d523ffe031b5840316eeae1f24dd8920e4/plugin/fugitive.vim#L689-L693) so that functions like `s:StagePatch()` don't freeze on the password prompt. Could you also make `s:Dispatch()` use `:terminal` in neovim (something like https://github.com/lzh9102/vim-fugitive/commit/dc4f285927808cb6b77404a9366646890132b568) so that `:Gpush` and `:Gfetch` don't freeze? Thank you!

**Comment by tpope** [comment]
It will probably require something a bit more involved, as we are using `:make` to capture output.

**Comment by lewicki-pk** [comment]
I have the same problem.
@tpope Do you even consider support for neovim or are we on our own with this editor?

**Comment by tpope** [comment]
Fugitive supports it but this is out of my element.

**Comment by prdx** [comment]
Hi there!

I have this problem as well. However, my current workaround is to add ssh-key to your github account and use ssh instead of https.

**Comment by gbrlsnchs** [comment]
This issue still exists when credentials are requested...

**Comment by shym** [comment]
Would it help to use a poor workaround like setting `GIT_ASKPASS='true'` (when it is not set to something else) so that git gets the empty password instead of hanging everything?

**Comment by tpope** [comment]
That's a good idea, though we should check that we're not overriding `core.askPass`. Or perhaps just set `SSH_ASKPASS` because it has the lowest precedence.

On that note, we could use `git-gui--askpass` or even `ssh-askpass` if available and we're running under a GUI. But I'm not sure what a good check for running under a GUI would be.

**Comment by sfzylad** [comment]
Not sure if it's the same problem I'm encountering, but `:Glog` freezes for me almost every other time I run it.

**Comment by shym** [comment]
@sfzylad, to make sure what you mean by freeze: `Glog` is not run asynchronously, it waits for `git log` to finish (which might take a little time). Is that what you mean?
If not, can you elaborate? But I hardly see how this could be really related, since `git log` does not require a password.

**Comment by sitilge** [comment]
Ping, same here, running `nvim v0.2.0`.

**Comment by irishmac473** [comment]
Same here, running `nvim v0.2.1`.

**Comment by paolousero** [comment]
Encountering this same problem in ` nvim v0.2.2.`

**Comment by sitilge** [comment]
I guess, the problem is present for a while now. Anyhow, using ssh keys is
more convenient and safe.

On Jan 12, 2018 02:28, "Paolo Usero" <notifications@github.com> wrote:

Encountering this same problem in nvim v0.2.2.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tpope/vim-fugitive/issues/722#issuecomment-357106214>,
or mute the thread

**Comment by tpope** [comment]
Here's an overly elaborate vimrc snippet to use `git-gui--askpass` or `ssh-askpass` which y'all can test as a potential workaround:

```vim
if (len($SECURITYSESSIONID) || len($DISPLAY)) && empty($SSH_ASKPASS)
  let s:gui_askpass = system("git --exec-path")[0:-2] . "/git-gui--askpass"
  if executable(s:gui_askpass)
    let $SSH_ASKPASS = s:gui_askpass
  elseif executable("ssh-askpass")
    let $SSH_ASKPASS = "ssh-askpass"
  endif
endif
```

You'll need at least one of those two tools installed, obviously.

**Comment by ssiccha** [comment]
@tpope This works for me. I'm using `NVIM v0.2.1-255-g9cc185d` without a GUI and have `ssh-askpass` installed.

**Comment by zubairakram** [comment]
error still exists, Gpush command is not working.
neovim freezes immediately

**Comment by doronbehar** [comment]
Hey @tpope, thanks for caring and pushing these changes. I've checked out the latest version today (80996c2e2c5a0185cc6ce77c2cd18665d26d4041)  and it seems `:term` isn't being used at all in `s:Displatch` right? From my initial testings of `:Gpush`, in an X session I got the Graphical x11-ssh-askpass working which is fine. But, I got this error when `$DISPLAY` was unset:

```
|| git@github.com: Permission denied (publickey).
|| fatal: Could not read from remote repository.
|| 
|| Please make sure you have the correct access rights
|| and the repository exists.
```

It's as if no askpass was found in that setup and therefor the git push command failed..

Besides this issue which might interest you, I will confirm though, in relation to your comment in https://github.com/tpope/vim-fugitive/pull/1052#issuecomment-451685414, that having both https://github.com/tpope/vim-dispatch and https://github.com/radenling/vim-dispatch-neovim installed, gives a UX I'm satisfied with, as a Neovim user - `:terminal` is always used for `:Gpush`.

If anyone has come to depend on [my fork of fugitive](https://github.com/doronbehar/nvim-fugitive), I'm archiving it.

**Comment by tpope** [comment]
Correct, no `:terminal`, just `:Make` if dispatch.vim is installed and `:make` if not.

I am not particularly satisfied with this solution, but as someone who doesn't enter their password on every single fetch, that's the priority. Side note, I recommend everyone use ssh keys or credential caching or anything other than typing in your password like an animal each time, you deserve it.
