### ISSUE TITLE
Multiple repositories

### ISSUE THREAD

**Issue by aemonge** [tpope/vim-fugitive#724]
Hi !

When I open three files with each of them in three distinct repositories, fugitive just suggest changes on the first file repository. I think it's due to the PATH, could it be possible to tell fugitive (with an option) to look for the repo based on the file and not the PATH ??

**Comment by tpope** [comment]
What do you mean "suggests changes"?

**Comment by aemonge** [comment]
Never-mind, it's actually working as expected. Sorry, I was hoping I could close the issue before you noticed it q=
