### ISSUE TITLE
Should we add confirmation before applying checkout (U)? 

### ISSUE THREAD

**Issue by lvarayut** [tpope/vim-fugitive#725]
I sometimes have checked out file by mistake using `U` while looking at the `:Gstatus` files. As I frequently use `D` to diff a file and `U` to checkout a file, my brain sometimes gets confused and uses one over the other.  

Should we prevent this mistake by adding such a confirmation alert before applying the checkout for real?

**Comment by tpope** [comment]
Are you not seeing https://github.com/tpope/vim-fugitive/blob/1ecd12d523ffe031b5840316eeae1f24dd8920e4/plugin/fugitive.vim#L859?

**Comment by lvarayut** [comment]
Thanks for your response. I just noticed it! However, would it be better to confirm before apply the U command? For example, pressing `To confirm y/N`.

**Comment by tpope** [comment]
No, undo is always better than "nag the user every single time".
