### ISSUE TITLE
Gstatus very slow with many untracked files

### ISSUE THREAD

**Issue by Corax26** [tpope/vim-fugitive#726]
21b6dd7a made Gstatus display all the untracked files (with a recent git). The issue is that is that with many untracked files, this makes Gstatus extremely slow to update. Would it be possible to add an option to revert to the original behaviour (don't pass -u to `git status`), or even better choose which option is passed to `-u` (no/normal/all)?

**Comment by tpope** [comment]
I think I'll just revert it (sorry @elyscape) as it never really sat right with me. My inclination is to suggest setting `showUntrackedFiles` directly if you really care about it.

**Comment by tpope** [comment]
Though I would also like to go on the record and say that this is what `.gitignore` and `.git/info/exclude` are for. So there's your config option, should some variant of this behavior ever make it back.

**Comment by elyscape** [comment]
Oh well! Thanks for tagging me.

Would it be possible to add a setting to pass arbitrary flags to git on certain or all commands? I prefer not having `status.showUntrackedFiles` set to `all` in my `.gitconfig` but I also want to have that functionality in fugitive, if that's possible. If you'd be okay with that enhancement, I can whip up a pull request.

**Comment by tpope** [comment]
Now that I think about it you could probably just tack those onto `g:fugitive_git_executable`.

What's the priority for `-c` arguments? I am wondering if we bring it back, can @Corax26 (or myself) do the opposite and override the value given in the plugin (which comes later on the command line).

**Comment by elyscape** [comment]
On git 2.6.3 (and likely everything since 1.8), priority for `-c` arguments is that, if you have multiple for the same setting, the last one takes precedence. The `-u` argument overrides any setting you might provide for `status.showUntrackedFiles`, but that was only being applied for git 1.4-1.7 anyway.

**Comment by tpope** [comment]
Yeah that's no good for my idea, since `g:fugitive_git_executable` arguments would always precede the `:Gstatus` ones. Will think on it.

**Comment by Corax26** [comment]
@tpope I agree that `.gitignore` mostly solves the issue, still I think in most cases the default behaviour is preferable. Thanks for reverting to the default option.

As to make it configurable, since `git status` is explicitly passed the option it will indeed override anything else, so I think the only solution would be to add an additional fugitive config variable.
