### ISSUE TITLE
Feature request: open Gstatus in new tab

### ISSUE THREAD

**Issue by rhardih** [tpope/vim-fugitive#727]
Sometimes it's nice to have a little more vertical space to deal with preparing commits and in those cases opening Gstatus as a new tab would be nice to have.

I've tried to "promote" the window to a new tab, by either `Ctrl-W_T` or `:tabedit %`, but in both cases the navigation bindings are lost and e.g. `Ctrl-d` results in an error:

`E486: Pattern not found: context`

**Comment by tpope** [comment]
Huh? `Ctrl-d` isn't mapped in fugitive. Either of those should work fine, or `:Gtabedit :`.

**Comment by rhardih** [comment]
What a brainfart on my part. :disappointed: It totally does work. :thumbsup:, don't know how that `d` got in there, as I was obviously thinking of `Ctrl-{n,p}`.

Closing :grin:

**Comment by ipod825** [comment]
either 
autocmd BufEnter *.git/index if &ft == 'gitcommit' | wincmd T | endif
or 
autocmd BufEnter *.git/index if &ft == 'gitcommit' | Gtabedit | endif
does the trick automatically.

However, I get the error message "E441 no preview window".
It seems "wincmd P " in s:Status() is making this error.

@tpope, I would like to know if I can achieve this trick without making errors?

**Comment by geneotech** [comment]
@ipod825 
Looks like I can just

```vim
nmap <silent> <C-s> :Gstatus <bar> wincmd T<CR>
```

**Comment by ipod825** [comment]
@geneotech 
Even with the map, I still get the same error.

**Comment by tpope** [comment]
`:Gtabedit :`

**Comment by tpope** [comment]
`:set previewwindow` should work.

**Comment by huangzonghao** [comment]
Thank you @tpope! That's exactly what I want!

**Comment by Melandel** [comment]
Hi, I have these lines in my vimrc:
```
augroup gitstatus
	autocmd!
	autocmd FileType fugitive set previewwindow
augroup END

nnoremap <silent> <Leader>G :Gtabedit :<CR>
```

It works fine but now the status window closes after I leave Insert mode in the commit window.

How can I keep the status window open at all times in my new tab?

**Comment by tpope** [comment]
Preview window closing sounds like a completion plugin. This is one of the reasons I recommend against using a preview window!

**Comment by Melandel** [comment]
I'll `:tabedit % | G` instead of `:Gtabedit :` in that case.

Thank you for your time :)

**Comment by tpope** [comment]
`:tab G` works!

**Comment by Melandel** [comment]
Oh. My. God.

Thanks a bunch tpope!
