### ISSUE TITLE
Feature Request: show changes interactively

### ISSUE THREAD

**Issue by phmarek** [tpope/vim-fugitive#73]
When doing "git rebase -i" it would be nice to have a vertical split, with one side showing the rebase buffer and the other one the files changed and the diff related to the change the cursor is on.

When moving the cursor in the rebase buffer, the other pane should be updated immediately, without any intervention.

The same could be used for Gstatus - showing the file diff in the other pane.

Thank you very much for this very nice plugin!

**Comment by ain** [comment]
Executing `git rebase -i <branch>` fails for me with `Could not execute editor` and is completely not usable. How can I debug it?

**Comment by tpope** [comment]
I have decided that "automatically updating a second window when moving the cursor" is clunky, un-Vim-like, and not a good fit for Fugitive.
