### ISSUE TITLE
`:Gdiff` is broken

### ISSUE THREAD

**Issue by rgrinberg** [tpope/vim-fugitive#731]
I get the following error when running it on a merge conflict:

```
E480: No match: `=fugitive#buffer().repo().translate(s:buffer().expand(':2'))`
```

**Comment by tpope** [comment]
Try after `:set wildignore&`. Still a problem?

**Comment by rgrinberg** [comment]
Fixes it, thanks.

**Comment by rgrinberg** [comment]
Although having to do this a bit annoying.

**Comment by tpope** [comment]
`*.git/*` is all kinds of broken and isn't supported. But patches are welcome if you can find a workaround. Generally replacing "`=...`" with `s:fnameescape(...)` does the trick.
