### ISSUE TITLE
Gstatus window unpredictable, same with Gstatus+diff

### ISSUE THREAD

**Issue by bernastoc** [tpope/vim-fugitive#732]
Hi,

I work with many open windows and I have no idea where 'Gstatus' is going to open - it may open in a new window above my current one, or sometimes overwrite an existing window to the side.

The diff option within Gstatus ('D') is the same, with splits sometimes creating new windows, sometimes using existing ones.

For all I know this isn't feasible, but shouldn't the output absolutely always create a new window(s)?

**Comment by tpope** [comment]
No, it should *never* create a new window, unless there is no other window to open into. It's basically quickfix window behavior. Are you experiencing different results, and if so, can you consistently reproduce the problem?

**Comment by bernastoc** [comment]
I've played with it some more. I haven't been able to reproduce my issue since I originally posted. Summary: Gstatus appears in a new "window" (quickfix?) above the one with my cursor, and "D" horizontally splits the last window my cursor was in. If this is normal behavior this thread should be closed.

**Comment by tpope** [comment]
So yeah, "never creates" does not count the split for the diff. Sounds like business as usual.
