### ISSUE TITLE
Commit message use buffer word complete

### ISSUE THREAD

**Issue by lookforit** [tpope/vim-fugitive#733]
I mean when `Gcommit` run,a new buffer window appears to input the commit message.
However ,if i type some words in that commit window,I can not use `ctrl - x,ctrl-p` to complete the words existed in the main buffer window.
Any way to do that?

**Comment by h3xx** [comment]
This works for me.

**Comment by tpope** [comment]
`<C-X><C-P>` is a Vim built-in; I don't see this as having anything to do with Fugitive.

**Comment by aschrab** [comment]
@lookforit You might want to examine your setting for the `complete` option, and the docs for that. It determines where vim looks for completions, and by default it should be checking other buffers.
