### ISSUE TITLE
Glog: Enter does not open tree objects from within commit objects

### ISSUE THREAD

**Issue by bmcilw1** [tpope/vim-fugitive#735]
When I run :Glog I can pull up the quickfix window and click enter on sha hashes to jump to the object. For me this is working for commits, blobs, and the diff features, but not with the tree objects ONLY within commit objects. I can open the tree objects only by preforming :Gedit sha, which works as desired. Also once I've entered the first tree object I can open other tree objects with just the enter key.

.vimrc attached
[vimrc.txt](https://github.com/tpope/vim-fugitive/files/71370/vimrc.txt)

**Comment by tpope** [comment]
Good catch.
