### ISSUE TITLE
Error detected while processing function <SNR>61_BufReadIndex..<SNR>61_ReplaceCmd:

### ISSUE THREAD

**Issue by mcnichol** [tpope/vim-fugitive#736]
Sorry, a pre-emptive submission.  

When trying to execute `:GStatus` from within my local repo I receive this error.   I saw a previous issue that you referenced a potential swp file hanging around causing the issue.  I searched around and haven't found any leftover swp/tmp files (which show as _._~ on win)

That being said, and I realize this may be somewhat forced, I am running this entire setup using gvim on Win7 using Pathogen to install plugins and using vim-fugitive from within the bundle folder.

I do have linux boxes available to me, I am trying to create some VIM configs for every machine so I can just hop on to a machine, pull it down from my remote, and be off and running with my setup agnostic to the underlying hardware (as much as is possible)

Here is the referenced issue from previous if at all helpful: #19

**Comment by tpope** [comment]
This portion of the error doesn't really narrow it down. You need the next line.

**Comment by mcnichol** [comment]
My apologies.

The next line is 
`E484: Can't open file C:\Users\ADMINI~1\AppData\Local\Temp\VIo340.tmp`

After that I see the *Enter to Continue* message where I am taken to a split with an empty file in the buffer at .g/index

**Comment by tpope** [comment]
That suggests a problem with your shell config. Can you `:!git status`?

**Comment by mcnichol** [comment]
Yes, when I `:!git status` I get the expected output from the command line.

To add to this, I can run other Commands such as :Gblame which behave as expected.  So far it just seems to be :Gstatus

It's very possible an issue with my shell config as I am still very green in the world of vim.

**Comment by tpope** [comment]
It could be a shell problem limited to quoting. Try running the command returned by

    :echo fugitive#repo().git_command( '-c', 'status.displayCommentPrefix=true', '-c', 'color
.status=false', '-c', 'status.short=false', 'status')

**Comment by mcnichol** [comment]
When I run this command everything works as expected.  

`!git --git-dir="C:\Program Files (x86)\Vim\vim74\.git" -c "status.displayCommentPrefix=true" -c "color.status=false" -c "status.short=false" status`

I was able to see the normal behavior from both the command line as well as within vim and gvim.

Forgive my ignorance, but I'm not sure what I should change in order to make this the standard behavior for my setup.

**Comment by tpope** [comment]
If you are using `cmd.exe`, and you haven't changed any "shell" options, then it's probably not the issue. Unfortunately, the next step is going to involve getting your hands dirty.

https://github.com/tpope/vim-fugitive/blob/18d6d1ab82d9ac15586d7d3c1a36f9ef6fb50eae/plugin/fugitive.vim#L2458 is presumably the line that's blowing up. You should (a) confirm that, and (b) figure out the exact command that's blowing up. Changing it to `:echoerr 'cmd /c....'"'` out to do it.

The error you're getting is basically "I told your shell to run a command and redirect to this file, but it's done and the file still doesn't exist." Which typically means your shell couldn't parse the command.

**Comment by jiahony** [comment]
Hi, @tpope ! I went into the same problem as @mcnichol . But my problem became a little bit wired.
Fugitive can work perfectly everywhere, except while I am edit any file in a dropbox folder. 

1. Every time I try to run `Gstatus` in my dropbox folder, it threw the same error messages as @mcnichol described above (i.e. `E484: Can't open file C:\Users\jiaho\AppData\Local\Temp\VIo5C8A.tmp`
2. I can move that file out of dropbox folder, and then everything goes well.

Could you provide any workaround? Thanks!

**Comment by jiahony** [comment]
I changed the corresponding line, and when I tried to run `:Gstatus`, the messages was:
```
cmd /c "git --git-dir="c:/Users/jiaho/DropBox (Personal)/FlexlabTest/integrated control simulation/.git" -c "status.displayCommentPrefix=true" -c "color.status=false" -c "status.short=false" status > c:\Users\jiaho\AppData\Local\Temp\VIAE073.tmp 2>&1"
```

**Comment by tpope** [comment]
If this isn't fixed, it should at a minimum be giving a much better error message. Report back if so.

**Comment by surajitbasak109** [comment]
> It could be a shell problem limited to quoting. Try running the command returned by
> 
> ```
> :echo fugitive#repo().git_command( '-c', 'status.displayCommentPrefix=true', '-c', 'color.status=false', '-c', 'status.short=false', 'status')
> ```

Thanks it fixed above problem on my windows 10 machine. 👍
