### ISSUE TITLE
Best way to activate fugitive features

### ISSUE THREAD

**Issue by albfan** [tpope/vim-fugitive#737]
After reading a commit on a buffer

https://github.com/albfan/vim-git-graph/blob/master/plugin/git-graph.vim#L203

and mark it as git filetype

https://github.com/albfan/vim-git-graph/blob/master/plugin/git-graph.vim#L204

I can only benefit from fugitive features if `b:git_dir` is set. The only way to do that is to add this autocmd on BufEnter:

https://github.com/albfan/vim-git-graph/commit/50be37eb482a1b14c0a83d1284dc2dc96eba3942

Is there a better way?

**Comment by tpope** [comment]
Definitely don't abuse `BufEnter` for this. Can't you just call it directly when you create the window?

**Comment by albfan** [comment]
Seema a better way to use it, thanks!
