### ISSUE TITLE
Revert commit failure

### ISSUE THREAD

**Issue by ain** [tpope/vim-fugitive#738]
**Steps to reproduce**:
1. `:Git revert HEAD~0`
2. `:wq` in status window to commit
3. `:q`

**What happens**: 

```
error: There was a problem with the editor 'vi'.
Please supply the message using either -m or -F option.

shell returned 1
```

**What should happen**:  one could expect commit to succeed as it does in the regular commit using the same steps.

**Comment by ain** [comment]
NB! Works on the 2nd try if `:Gstatus` is triggered exclusively.

**Comment by tpope** [comment]
`:Git revert` spawns a subshell which in turn spawns a `vi` instance, so this doesn't sound (directly) Fugitive related.

**Comment by tpope** [comment]
`:Grevert` is a built-in now (and `:Git revert` calls it).
