### ISSUE TITLE
:Gbrowse with specified remote

### ISSUE THREAD

**Issue by chrisarcand** [tpope/vim-fugitive#739]
Thanks @tpope for such an awesome plugin. Its been by far one of the best tools I've used and I've used it for quite a while now.

I'd like to open a file on Github ala :Gbrowse, but with the link containing the upstream project as the remote. Looking through the doc this option seems to be exactly that:

```
:Gbrowse [...]@{remote} Force using the given remote rather than the remote
                        for the current branch.
```

But when I do `:Gbrowse @<remotenamehere>` I just get an error:

`fugitive: Instaweb failed to start and <remotenamehere> is not a supported remote`

:Gbrowse works perfectly fine without arguments (goes to my fork). I've looked everywhere to try and find a solution, as it could be as dumb as me failing to understand the syntax, but nothing :confused:

**Edit:** `:Gbrowse @{something}` opens an invalid url, at least. I'm clearly just not understanding and doing something wrong.

**Comment by tpope** [comment]
That error message is no longer in the code base. Update.

**Comment by chrisarcand** [comment]
Ah! It does open a URL now, but just appends whatever I give it to the end of the url. `:Gbrowse @projectname` -> `<normal github url of the fork>/@projectname`. Sigh, I'm missing something. Thank you for your time though, I really appreciate it.

**Comment by tpope** [comment]
Just pushed a fix for an issue extracting the remote name.

**Comment by chrisarcand** [comment]
Works! Thanks so much, @tpope!
