### ISSUE TITLE
:Glog should be streamed/paged unto a buffer

### ISSUE THREAD

**Issue by dlee** [tpope/vim-fugitive#74]
So that we can press enter on a commit line and go to fugitive's display of the SHA. Right now, you can only do :cn / :cp to navigate through the log.

Also, doing :Glog without any arguments on a project with a long history eats up a CPU for a long time.

**Comment by joshtriplett** [comment]
Vim supports some asynchronous process and buffer handling now, inspired by neovim; that might help with the "streaming" part of this request.

**Comment by tpope** [comment]
You can load into a buffer now with `:Git log`. It's not streamed but when you remove the quickfix overhead it's a lot faster.
