### ISSUE TITLE
Silly error message when amending commit

### ISSUE THREAD

**Issue by h3xx** [tpope/vim-fugitive#740]
When stage completely negates the last commit, typing <kbd>c</kbd><kbd>a</kbd> in the `:Gstatus` window results in a very silly error message. This error message isn't any longer when the terminal is maximized.

> fugitive: it empty. You can repeat your command with --allow-empty, or you can

![screenshot-2016-0112-1736](https://cloud.githubusercontent.com/assets/615684/12280407/38c4c24c-b953-11e5-8c32-063bb2749636.png)
## Steps to reproduce:

```
$ mkdir temp_gitdir ; cd temp_gitdir ; git init
$ echo 'hello world' > testfile
$ git add testfile
$ git commit -m 'Dummy commit'
$ git rm testfile
$ vim
```

Then in vim type `:Gstatus` which correctly shows the deletion as a staged change.

Type `ca` to do a commit --amend. This is when the error message shows up.

I tested this under a clean-room environment with only fugitive installed, and a [minimal gitconfig](https://gist.github.com/75bb21eefc7953f74a1e):
- git 2.6.4
- vim-fugitive fd36aa9c61e06d71befdbe8931f97137c489b065
- vim 7.4.898
- Linux

**Comment by tpope** [comment]
What's the full error message? I'm guessing it's just a regex misfire.

**Comment by h3xx** [comment]
That's all the error message that appears in vim's error bar.

Doing a `git commit --amend` from the command line under the same circumstances gives this:

    On branch master
    
    Initial commit
    
    No changes
    You asked to amend the most recent commit, but doing so would make
    it empty. You can repeat your command with --allow-empty, or you can
    remove the commit entirely with "git reset HEAD^".

**Comment by tpope** [comment]
Oh that's an old issue: a really shoddy heuristic trying to get the error message without all that `On branch master` crap. See #95 for example. Run it with `>/dev/null` so we can see what's actually on standard error.

**Comment by h3xx** [comment]
$ git commit --amend >/dev/null
    You asked to amend the most recent commit, but doing so would make
    it empty. You can repeat your command with --allow-empty, or you can
    remove the commit entirely with "git reset HEAD^".

**Comment by PeterDaveHello** [comment]
This is silly +1, but it's from `git`, not this project.

**Comment by h3xx** [comment]
True, but in every other circumstance this project deals with git errors by detecting and sidestepping them, or elegantly dealing with the error message, not cutting it off mid-sentence.

**Comment by PeterDaveHello** [comment]
The better way may be to report to git IMO.

**Comment by h3xx** [comment]
The problem isn't with git, it's with how fugitive formats the error message.

**Comment by tpope** [comment]
The full error message is always shown now.
