### ISSUE TITLE
gf: use includeexpr instead / or "norm! gf"

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-fugitive#744]
https://github.com/tpope/vim-fugitive/issues/697 was done by mapping `gf` in the buffer.

In https://github.com/tpope/vim-fugitive/issues/328#issuecomment-46755692 however it was mentioned to use `'includeexpr'` for that, which might be better than overwriting `gf`, because `includeexpr` allows for chaining (where a function could try multiple callbacks, similar to what `s:cfile` is doing).

1. The Vim help mentions that `includeexpr` gets used for `<cfile>` only, so by using that the existing `includeexpr` could be called before/with fugitive's `gf`?
2. What about using `norm! gf` when nothing was found?

**Comment by tpope** [comment]
Unfortunately `'includeexpr'` is extremely limited: It won't allow for jumping to a line within the destination file, for example, and it gets really hacky if you want to take into account anything else on the same line. To answer the rest of this I need a bit more context about the problem you are trying to solve.

**Comment by blueyed** [comment]
The problem I had was that my custom `includeexpr` was ignored (it handles Git's `diff.mnemonicprefix` style, #743), and I've noticed that `gf` stopped working for those.

I can see that remapping `gf` is good, but wonder how a custom `includeexpr` could still be used (before or after fugitive's `gf`).

**Comment by tpope** [comment]
Bug mitigation is hardly a compelling justification, but calling `includeexpr` on the fallback only seems pretty harmless, so I've done that.
