### ISSUE TITLE
Use fugitive and flagship without adding fugitive to the statusline

### ISSUE THREAD

**Issue by Hotschke** [tpope/vim-fugitive#745]
I have added following to my vimrc:

    augroup! fugitive_statusline

However, this does not help. I use the plugin manager 'junegunn/vim-plug'. Probably `augroup!` is not helpful here anyway. Is there any way without touching fugitive itself, to avoid getting the fugitive_statusline added to flagship?

**Comment by tpope** [comment]
let g:flagship_skip = 'fugitive#statusline'

**Comment by Hotschke** [comment]
Thanks for your help.
