### ISSUE TITLE
:Gdiff hangs Vim on os x

### ISSUE THREAD

**Issue by aligit** [tpope/vim-fugitive#746]
When I do :Gdiff my vim crashes and shows the following error. 

> [1]  + 17921 suspended (tty output)  vim package.json

Then to view and open the session I have to type:
`fg %vi`

This only happens in my os x and the ubuntu version is fine. Here is the output from :version in os x:

> VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  1 2016 15:10:32)
> MacOS X (unix) version
> Included patches: 1-1016
> Compiled by Homebrew

Thanks in advance

**Comment by tpope** [comment]
My hunch would be to blame Git not Vim. Custom external diff, perhaps?

**Comment by aligit** [comment]
Hi @tpope 
Thanks for your reply. I checked and saw only diff tool being installed.
Otherwise .vimrc is synced between both machines. How should I check
for external diff?

**Comment by tpope** [comment]
Check your gitconfig.

**Comment by aligit** [comment]
I disabled difftool but didn't help neither.
Here is .gitconfig:

>   d = difftool
> [diff]
>   tool = vimdiff
>   mnemonicprefix = true
> [difftool]
>   prompt = false
> [merge]
>   tool = vimdiff
> [mergetool]
>   prompt = false

**Comment by tpope** [comment]
Can you try both of the following?

1. With no gitconfig at all
2. With the exact same gitconfig as the ubuntu machine

**Comment by aligit** [comment]
It only happen once and the first time. Without gitconfig, it didn't happen.
Ubuntu didn't have that proble

**Comment by tpope** [comment]
If it doesn't happen without gitconfig then it sounds like the problem is your gitconfig.
