### ISSUE TITLE
:Gbrowse <branch> only works when branch is in .git/config file

### ISSUE THREAD

**Issue by WouterSioen** [tpope/vim-fugitive#748]
I use the "current" strategy as default for pushing (because I don't like using the `git push --set-upstream <origin> <branch-name>` command every time I create a new branch).

This doesn't put the branches in my .git/config file though, causing the `:Gbrowse <branch-name>` not to work.

Can this be fixed? Or do I have to change my push strategy to make it work?

**Comment by tpope** [comment]
The logic could definitely be changed: https://github.com/tpope/vim-fugitive/blob/9835920a3c91236021fc8c88cc4157304e24356b/plugin/fugitive.vim#L2279-L2287

 We currently do fall back to origin but apparently not in the case of a branch argument: https://github.com/tpope/vim-fugitive/blob/9835920a3c91236021fc8c88cc4157304e24356b/plugin/fugitive.vim#L2250-L2269

**Comment by WouterSioen** [comment]
Ok, I'll take a look at it if I can implement this. I've never written vimscript though, so this will probably be a nice challenge for me.

**Comment by tpope** [comment]
Should be fixed.
