### ISSUE TITLE
highlight a set of names in Gblame

### ISSUE THREAD

**Issue by scampi** [tpope/vim-fugitive#749]
I would like to highlight a predefined set of names when executing `:Gblame`. This way, it would be easier to see from which "team" the person who did the change comes from.

Would you have some advices to achieve this ?

**Comment by tpope** [comment]
I think an `after/syntax` file would work? Personally I'd probably just hack it and set `hlsearch` and search for the names I want to highlight.

**Comment by scampi** [comment]
thanks @tpope for the ideas. Probably `hlsearch` is the best way to go, as I don't imagine needing this very often.
