### ISSUE TITLE
:Gstatus in worktree is very wrong

### ISSUE THREAD

**Issue by jwhitley** [tpope/vim-fugitive#751]
In the wake of #671 being closed, I just checked out `:Gstatus` in one of my existing worktrees.  It's showing a ton of deleted files, but `git status` (v2.7.2) shows a large number of *added* files.  Also, fugitive shows this:

```
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	COMMIT_EDITMSG
#	FETCH_HEAD
#	HEAD
#	ORIG_HEAD
#	commondir
#	gitdir
#	gitfile
#	index
#	index.lock
#	logs/
#
```

**Comment by tpope** [comment]
Check the contents of `gitfile`, `gitdir`, and `commondir` in the git dir of the work tree.

**Comment by jwhitley** [comment]
FWIW, I have another test worktree lying around and it doesn't exhibit this problem.  Investigating the problematic one right now.  The `.git` files in the worktrees check out with correct absolute paths.

**Comment by tpope** [comment]
My guess is it's something to do with the contents of `gitdir` and https://github.com/tpope/vim-fugitive/blob/16c2b7abb97111a4c241fbe37ac40e21585773a9/plugin/fugitive.vim#L273

**Comment by jwhitley** [comment]
So in the busted one `gitdir` contains just:

`.git`

In the working one, `gitdir` contains the absolute path to the worktree's .git file, e.g.:

`/Users/whitley/tmp/local2/.git`

`commondir` is `../..` for both.
`gitfile` is `.git` for both.

**Comment by jwhitley** [comment]
Grr, `gitrepository-layout(5)` doesn't specify semantics for the contents of `gitdir`.  But it seems that a relative file value in `gitdir` has to be resolved against the root of a worktree checkout directory.

**Comment by tpope** [comment]
Unfortunately we're getting the worktree by reading this very file and stripping off `.git`, so that's no good.

Is this a problem with freshly created worktrees, or just old ones (perhaps created by a different version git)?

**Comment by jwhitley** [comment]
Yeah, so I've confirmed that the bad behavior seen here and by users in #671 is when a worktree's `gitdir` file contains just `.git`.  I followed the repro steps I wrote [here](https://github.com/tpope/vim-fugitive/pull/671#issuecomment-129294574) with git v2.7.2 and :Gstatus works as expected.  But when I modified `gitdir` by hand, I get exactly the kind of broken results seen elsewhere:

```
# On branch ft2
# Changes to be committed:
#   (use "git reset HEAD <file>..." to unstage)
#
#	new file:   c.txt
#
# Changes not staged for commit:
#   (use "git add/rm <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	deleted:    a.txt
#	deleted:    c.txt
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	HEAD
#	ORIG_HEAD
#	commondir
#	gitdir
#	index
#	index.lock
#
```

This is incredibly unfortunate, since this represents a rather bumpy divergence between git's CLI behavior and fugitive.  Some options are 1) doc it and flee screaming :sob: or 2) perhaps outright ask git what the prefix abspath is in this special case via `git rev-parse --show-toplevel`.

**Comment by jwhitley** [comment]
Compare that status to what `git status` shows for the same worktree (incl. the modified `gitdir` file):

```
>> git status
On branch ft2
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   c.txt
```

**Comment by tpope** [comment]
`show-toplevel` won't work because it depends on the current working directory.

Other than you manually editing `gitdir`, what are the situations this actually happens? Couldn't this just be a bug in old versions of Git?

**Comment by jwhitley** [comment]
Using `git` when there isn't a well-defined notion of a toplevel project/working tree doesn't make any sense, and fugitive inherits that limitation.  So either we have to depend on Vim's notion of `cwd` or else we have to otherwise be able to derive the toplevel, either for an entire vim session, or perhaps relative to the file in the current buffer.

Put another way: fugitive *must* have valid semantics for picking an effective working directory for its commands.  E.g. If using a buffer's path as the reference point, then it's easy enough to run `show-toplevel`, temporarily changing `cwd` to the file's parent directory, if those are the desired semantics.

**Comment by jwhitley** [comment]
FWIW, I virtually always have vim's `cwd` set to the root, or sometimes the one-level subdir of a valid git clone (or worktree).  This is because I use vim in a very project-centric manner for software work, so that tools like `:Ag`, `:CtrlP`, etc. have a well-defined chunk of filesystem to work on.  This likewise implies that it's very rare for me to have files from two git repos open in one vim at a time, and when I do, it's just to reference another repo's file(s) read-only w.r.t. the current working repo.

**Comment by tpope** [comment]
So I finally checked `gitrepository-layout` for myself:

       worktrees/<id>/gitdir
           A text file containing the absolute path back to the .git file that points to here.

So your repository was broken. End of story. Based on the other thread this was a bug in Git that has been fixed.

And no, we don't need to use the current working directory when we have a current file within the project. The fact we cope with a broken repository worse than Git itself is an implementation detail, not a technical limitation. If it actually mattered I'd find a way to fix it.

**Comment by jwhitley** [comment]
:facepalm:  Yeah, I've read that exact same bit from `gitrepository-layout` before, but somehow missed it on rereading it.  I'd also thought that my broken repo was actually older than the introduction of the git worktree regression that broke `gitdir`, but apparently that was wrong.  Sorry for the wild goose chase.
