### ISSUE TITLE
Commiting in a worktree opens git index file instead of doing a commit

### ISSUE THREAD

**Issue by grodzik** [tpope/vim-fugitive#752]
Hi,

I'm really glad that support for worktrees is finally in fugitive. However I have an issue with doing a commit when working in a worktree. Mainly I have issue that was observed also in #671. After typing my commit message and closing GCommit window/buffer (:x), there is no commit made, but git index file is opened. I finally tracked the root cause of this issue and it's a change introduced in Vim's patch 7.4.860. It changes
```au BufNewFile,BufRead *.git/COMMIT_EDITMSG  setf gitcommit```
in filetype.vim to
```au BufNewFile,BufRead COMMIT_EDITMSG        setf gitcommit```

I use Arch Linux, so I have quite recent version of Vim, and changing that one line (with latest Fugitive) to one before that patch fixes commiting from Vim. Also I've tested that on Debian machine where vim is in version 7.4.4xx and introducing that one change breaks Fugitive commit ability.
Is this something Fugitive should fix somehow or it relayed on the way it worked previously or is it issue with upstream?

**Comment by sergei-dyshel** [comment]
Same bug wtih 7.4.900

**Comment by grodzik** [comment]
Yes, every version of Vim after 7.4.860 is affected

**Comment by tpope** [comment]
Opening the index sounds like it might be trying to call `:Gstatus` on a failure. Are you saying the commit succeeds without that change? I can see the file type affecting *how* it fails, but I'm struggling to think of a reason why it would change it from a success.

**Comment by grodzik** [comment]
@tpope yes, exactly. It seems like it was not triggering that autocmd before in worktrees, but it was always and still is in main git tree. So looks like commit is done differently for worktrees in some way.

**Comment by grodzik** [comment]
@tpope I think I found root cause of this. Seems to be rather 'upstream', although located in a file maintained by You ;).
In general `git commit` fails because it has `b:git_dir` (and command gets `--git-dir=b:git_dir`) set to main repository, not worktree. This seems to be due to change introduced in patch `#860`, which makes also wortkree `COMMIT_MSG` files filetype `gitcommit` and `b:git_dir` is set inside `ftplugin/git.vim` invoked from `ftplugin/gitcommit.vim` that are in Vim directory. Without that patch `filetype=gitcommit` is applied to the buffer by Fugitive and `b:git_dir` is already set by Fugitive at that time, `ftplugin/git.vim` doesn't have to set it by itself.
