### ISSUE TITLE
:Ggrep should not run from top-level git dir

### ISSUE THREAD

**Issue by dmerejkowsky** [tpope/vim-fugitive#753]
Use case: I have a project with some documentation in doc/, some Python code in python/, and some CMake code in cmake/

If I run :Ggrep, fugitive will set working dir to the top-level git dir, and I'll get matches everywhere, when I only want results in my current working dir.

Update: the culprit seems to be here:

``` VimL
function! s:Grep(cmd,bang,arg) abort

 " ...
  try
    execute cd.'`=s:repo().tree()`'
    " ...

   finally
      execute cd.'`=dir`'
   endtry
endfunction
```

I'm using version 2.2. 

I've tried commenting the lines running `execute cd`, but then fugitive calls git with

```
git grep --git-dir /path/to/proj/.git foo
```

which cannot work (--work-tree should be set to /path/to/proj for this to work)

**Comment by tpope** [comment]
See #787.
