### ISSUE TITLE
D from status buffer could not open file

### ISSUE THREAD

**Issue by still-dreaming-1** [tpope/vim-fugitive#754]
Is there a minimum git version for the D mapping from a status buffer to work? It works on my local machine with a git version of 2.7.2, but not on this other server with git version 2.3.7. Well sometimes it works depending on which repository it is looking at. But there is this older repository where it shows an error message like "|| P Could not open input file: fugitive:///home/jesse/acs/.git//0/www/ACSmanager/upgrade/new.php". At this point there are 4 windows on the screen. The status buffer is open in a window on the top, as expected. Below that there are two sections. The right half is a window with a buffer to the file as is, with diff highlighting and such, as expected. But the left half of the screen below the status buffer is split horizontally into 2 windows. The window on the top is the current file being compared, just like the window on the right, except it does not have any special diff highlighting. Below that is a window that seems like it is supposed to be the contents of the file if it was checked out in git, but instead it displays that error message.

**Comment by tpope** [comment]
Definitely not a Git version issue; possibly a Vim version issue.

**Comment by still-dreaming-1** [comment]
Actually it is happening in both places. I figured out it is only happening with .php files though. It's conflicting with the phpqa plugin: https://github.com/joonty/vim-phpqa they are completely incompatible with each other or if my config is getting too complicated. I should have tested a clean config before reporting this. I will let you know what I figure out. I am actually getting a different phpqa related error on my local machine with under Noevim: 

> ```
"www/ACSmanager/AcceptManuallyEnteredAmr.php" 44L, 2009C                                                                                                                                      
> Error detected while processing function Phpqa#PhpLint:                                                                                                                                       
> line    8:                                                                                                                                                                                    
> E684: list index out of range: 0                                                                                                                                                              
> E116: Invalid arguments for function match(l:php_list[0],"No syntax errors") == -1                                                                                                            
> E15: Invalid expression: 0 != v:shell_error && match(l:php_list[0],"No syntax errors") == -1
```

**Comment by still-dreaming-1** [comment]
Still getting this error with very small Neovim config, latest version of Neovim, vim-fugitive, and vim-phpqa:

```
call plug#begin()
Plug 'joonty/vim-phpqa'
Plug 'tpope/vim-fugitive'
call plug#end()
set nobackup
set noswapfile
let g:phpqa_messdetector_autorun = 0
let g:phpqa_codesniffer_autorun = 0
```

Once again the problem only happens with php files. I will see what the phpqa people have to say as well.

**Comment by tpope** [comment]
If phpqa is blowing up it's because phpqa made some assumptions that don't hold true for fugitive buffers.

**Comment by PickRelated** [comment]
Just an update for those interested. Corresponding pull request with a fix is created for joonty/vim-phpqa repo.
