### ISSUE TITLE
Why :Gcommit does not have completions for '--fixup' and '--squash' ?

### ISSUE THREAD

**Issue by aleprovencio** [tpope/vim-fugitive#755]
When hitting `tab` after `:Gcommit` we get completions for a lot of `git commit`'s options, such as `--ammend`,`--file`, etc. Why the completions for `--fixup` and `--squash` are not there?

**Comment by tpope** [comment]
Because I wrote the completion years before those options existed.

**Comment by aleprovencio** [comment]
Closed by #811
