### ISSUE TITLE
Gdiff on file from work directory (no conflict) invokes 3-way diff and the two temporary buffers are empty

### ISSUE THREAD

**Issue by liuhmg** [tpope/vim-fugitive#756]
Other commands like Gstatus, Gblame work fine.

The path to the two temporary buffers are like: 
workDir/.git/2//pathToFile
workDir/.git//3/pathToFile

**Comment by bicycle1885** [comment]
I can reproduce this issue, but it happens sometimes, not 100%. Let me just file a screenshot and version information.

<img width="1392" alt="screen shot 2016-03-12 at 14 21 14" src="https://cloud.githubusercontent.com/assets/905683/13721080/ffe05380-e85d-11e5-8eed-122b783bc0e4.png">


* OS: OS X Yosemite
* Vim: NeoVim
* Git: v2.7.0

```
:version
NVIM v0.1.3-317-gbd81239
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99
-Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160306-90595-1eym0sa/build/config -I/tmp/neovim20160306-90595
-1eym0sa/src -I/tmp/neovim20160306-90595-1eym0sa/deps-build/usr/include -I/tmp/neovim20160306-90595-1eym0sa/deps-build/usr/include -I/tmp/neovim20160306-90595-1eym0sa/deps-build/usr
/include/luajit-2.0 -I/tmp/neovim20160306-90595-1eym0sa/deps-build/usr/include -I/tmp/neovim20160306-90595-1eym0sa/deps-build/usr/include -I/tmp/neovim20160306-90595-1eym0sa/deps-bu
ild/usr/include -I/tmp/neovim20160306-90595-1eym0sa/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim20160306-90595-1eym0sa/build/s
rc/nvim/auto -I/tmp/neovim20160306-90595-1eym0sa/build/include
Compiled by kenta@KS-Mac.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

**Comment by jimmyharris** [comment]
This is happening to me as well. Though I am running git 1.9.1 (as per company policy).  I am also running on Ubuntu 14.04 x86_64

```
NVIM 0.1.5-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-rLisGy/neovim-0.1.2ubuntu1+git201605030045+2464+19~ubuntu14.04.1/build/config -I/build/neovim-rLisGy/neovim-0.1.2ubuntu1+git201605030045+2464+19~ubuntu14.04.1/src -I/build/neovim-rLisGy/neovim-0.1.2ubuntu1+git201605030045+2464+19~ubuntu14.04.1/.deps/usr/include -I/build/neovim-rLisGy/neovim-0.1.2ubuntu1+git201605030045+2464+19~ubuntu14.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-rLisGy/neovim-0.1.2ubuntu1+git201605030045+2464+19~ubuntu14.04.1/.deps/usr/include -I/build/neovim-rLisGy/neovim-0.1.2ubuntu1+git201605030045+2464+19~ubuntu14.04.1/.deps/usr/include -I/build/neovim-rLisGy/neovim-0.1.2ubuntu1+git201605030045+2464+19~ubuntu14.04.1/.deps/usr/include -I/build/neovim-rLisGy/neovim-0.1.2ubuntu1+git201605030045+2464+19~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-rLisGy/neovim-0.1.2ubuntu1+git201605030045+2464+19~ubuntu14.04.1/build/src/nvim/auto -I/build/neovim-rLisGy/neovim-0.1.2ubuntu1+git201605030045+2464+19~ubuntu14.04.1/build/include
Compiled by buildd@lgw01-57

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by jimmyharris** [comment]
Looks like this is something funky happening with neovim. Regular vim appears to work fine using the following package:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 10 2016 03:45:56)
Included patches: 1-1529
Modified by pi-rho
Compiled by buildd@lcy01-33
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-balloon_eval    +float           +mouse_urxvt     -tcl
-browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +title
+cindent         -hangul_input    +netbeans_intg   -toolbar
-clientserver    +iconv           +packages        +user_commands
-clipboard       +insert_expand   +path_extra      +vertsplit
+cmdline_compl   +job             -perl            +virtualedit
+cmdline_hist    +jumplist        +persistent_undo +visual
+cmdline_info    +keymap          +postscript      +visualextra
+comments        +langmap         +printer         +viminfo
+conceal         +libcall         +profile         +vreplace
+cryptv          +linebreak       +python/dyn      +wildignore
+cscope          +lispindent      -python3         +wildmenu
+cursorbind      +listcmds        +quickfix        +windows
+cursorshape     +localmap        +reltime         +writebackup
+dialog_con      -lua             +rightleft       -X11
+diff            +menu            -ruby            -xfontset
+digraphs        +mksession       +scrollbind      -xim
-dnd             +modify_fname    +signs           -xsmp
-ebcdic          +mouse           +smartindent     -xterm_clipboard
+emacs_tags      -mouseshape      +startuptime     -xterm_save
+eval            +mouse_dec       +statusline      -xpm
+ex_extra        +mouse_gpm       -sun_workshop    
+extra_search    -mouse_jsbterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -Wall -Wextra -g -O2 -fPIE -Wformat -Werror=format-security -fstack-protector-all -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,-z,nodlopen -Wl,-z,nodump -Wl,-z,noexecstack -Wl,-z,noexecheap -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl 
```

**Comment by justinmk** [comment]
What are the steps to reproduce using `nvim -u NORC` ?

**Comment by jimmyharris** [comment]
Unfortunately I don't know enough about how @tpope constructs the diff commands in his script to cause this to generate a 3 way diff instead of a 2 way diff. The only way I could reproduce this with no custom configuration would be to git bisect neovim until I found the change that broke with the current version of this plugin and then say "That did it!." Unless @tpope can help break this down further, all I can report is that with the versions of git and neovim I am using this functionality never works. But with classic vim instead, it always works.

One thing I did notice is this: 
![screenshot from 2016-05-04 11 44 47](https://cloud.githubusercontent.com/assets/96391/15021775/4281eb68-11ee-11e6-8737-64349c71eb12.png)

At the bottom of the screen running nvim generated those two lines before attempting to generate the three way diff even though I was only asking for a 2 way diff.

To reproduce this with the versions I was discussing

Using a minimal nvim vim-fugitive setup:

1. Clone any git repository to a directory.
2. open any file tracked in the repository `nvim README.md`
3. Run `:Gdiff`

This should result in the three window issue I was seeing. @tpope is there anything else I can get you to help try and reproduce this issue?

**Comment by justinmk** [comment]
@jimmyharris Thanks for the steps, but they do not cause the issue, using 

```
nvim -u NORC -c ':set runtimepath+=~/.vim/bundle/vim-fugitive/' -c ':runtime plugin/fugitive.vim'
open any file tracked in the repository
make a change
:Gdiff
```

Using those steps, Gdiff shows 2 panes. Again, this means there are missing steps to reproduce the issue. (e.g., setting an option)

**Comment by justinmk** [comment]
@jimmyharris What is `:set diffopt?` output?

**Comment by tpope** [comment]
The relevant conditional: https://github.com/tpope/vim-fugitive/blob/bdd216827ae53cdf70d933bb30762da9bf42cad4/plugin/fugitive.vim#L1778

**Comment by jimmyharris** [comment]
@justinmkmy `diffopt=filler`

**Comment by jimmyharris** [comment]
@tpope:

It looks like I am getting int a weird situation with the behavior of:
```VimL
s:repo().git_chomp_in_tree('ls-files', '--unmerged', '--', s:buffer().path()) !=# ''
```

In the vim version I am using it appears that the value of 
```VimL
s:repo().git_chomp_in_tree('ls-files', '--unmerged', '--', s:buffer().path())
```
Is blank when I call `Gdiff` with no arguments.

Neovim however returns the following output:
```
^[]1;harrisja@ola-2hv9fb2: ~/github/k480_conf^G^[]2;harrisja@ola-2hv9fb2: ~/github/k480_conf^G
```

I am not entirely sure where the behavior change is coming from. Bit it depends on the output of the call to [git_chomp](https://github.com/tpope/vim-fugitive/blob/bdd216827ae53cdf70d933bb30762da9bf42cad4/plugin/fugitive.vim#L385) which uses `system()`

@justinmk 
Could this have do do with a change in the behavior of the `system()` API in NeoVim? Is there something that is happening somewhere else that could have an effect on the behavior of the `system()` call?

**Comment by justinmk** [comment]
@jimmyharris We changed system() to use pipes instead of a pty, but that should definitely not cause your prompt to appear in system() output.

Can you add this line in [git_chomp](https://github.com/tpope/vim-fugitive/blob/bdd216827ae53cdf70d933bb30762da9bf42cad4/plugin/fugitive.vim#L385):

    echom self.git_command '/' string(a:000)

**Comment by justinmk** [comment]
@jimmyharris We changed system() to use pipes instead of a pty, but that should definitely not cause your prompt to appear in system() output.

Can you add this line in [git_chomp](https://github.com/tpope/vim-fugitive/blob/bdd216827ae53cdf70d933bb30762da9bf42cad4/plugin/fugitive.vim#L385):

    echom call(self.git_command,a:000,self)

Then check the result in `:messages`.

**Comment by jimmyharris** [comment]
@justinmk 

Here is what I am seeing in my output so far when I instrument the path as you suggested.

```
git_chomp calling: git --git-dir=/home/harrisja/github/k480_conf/.git ls-files --unmerged -- README.md             
Unmerged files list: ^[]1;harrisja@ola-2hv9fb2: ~/github/k480_conf^G^[]2;harrisja@ola-2hv9fb2: ~/github/k480_conf^G
```

**Comment by justinmk** [comment]
@jimmyharris What's the output of:

    :set shell?  shellcmdflag?  shellpipe?  shellquote?  shellredir?  shelltemp?  shellxquote?  shellxescape?

**Comment by jimmyharris** [comment]
```
  shell=/usr/bin/zsh                                                                                               
  shellcmdflag=-c                                                                                                  
  shellpipe=2>&1| tee                                                                                              
  shellquote=                                                                                                      
  shellredir=>%s 2>&1                                                                                              
  shelltemp                                                                                                        
  shellxquote=                                                                                                     
  shellxescape=                                         
```

Sorry for the long reply I had to head home for the day.

**Comment by justinmk** [comment]
@jimmyharris Try `:set shell=/bin/bash`. If that works, I'm guessing something in your `.zshrc`, `.zshenv`, `.zlogin`, or `.zprofile` is triggering the issue.

Another thing to try: temporarily move/delete your `.zshrc`, `.zshenv`, `.zlogin`, `.zprofile`, then open a new terminal and see if the problem persists. If you can narrow down the line that triggers the issue, that could lead to a fix.

**Comment by jimmyharris** [comment]
For reference I believe the issue was setting an option that should only have been set in .zshrc in my .zshenv. Sorting my zsh init scripts better fixed the issue.  I will investigate further into what option might have caused it.

**Comment by thisguychris** [comment]
Hi, @tpope 👋 I just got this issue, using fish. It's intermittent, sometimes it works sometimes it doesn't. It doesn't matter if `:set shell=/bin/bash`. I get this randomly.

I'm using `nvim`  v0.3.1 and fish shell by default. I also get the error in `vim 8.0.1283`

It happens most when I do a :Gstatus and `D` on the unstaged file.

**Comment by tpope** [comment]
All it's doing is checking `git ls-files --unmerged -- filename`. A shell issue or a Git issue are the most likely culprits.

I've updated `:Gdiff` to fail if the shell returns an error.

**Comment by thisguychris** [comment]
hi @tpope! thanks the update, will test this out and report once I get the error. So far doing Gstatus and D works as intended on fish. Also to add some details on what happened before, I somewhat had a file with 3 in the prefix. Not sure if it's for a 3-way merge.
