### ISSUE TITLE
:Gstatus and then D opens diff in Gstatus window

### ISSUE THREAD

**Issue by OskarSigvardsson** [tpope/vim-fugitive#758]
I don't know if this is a problem with my configuration or if it's something i'm missing, but I find that pressing D in the :Gstatus window to open the diff of a file opens it in the wrong window. 

So, lets say I'm editing a file:
![skarmklipp 2016-03-03 15 23 17](https://cloud.githubusercontent.com/assets/7059777/13497191/64a0386e-e154-11e5-8597-b0e3be6ffd53.png)

And I type in :Gstatus

![skarmklipp 2016-03-03 15 23 26](https://cloud.githubusercontent.com/assets/7059777/13497201/7246fd4a-e154-11e5-8bac-f842d9005c43.png)

And I press D over test.txt and this happens: 

![skarmklipp 2016-03-03 15 24 04](https://cloud.githubusercontent.com/assets/7059777/13498440/4864c740-e15a-11e5-9140-a152408c6454.png)

I would, of course, MUCH rather that the bottom window is the one where the diffing happens. I should say that this doesn't happen every time, but the vast majority of the time (about 9 times in 10), and I don't know what's different between it happening and not happening. Is this a configuration issue on my end? I would really appreciate some advice. 

Awesome plugin, by the way, only started using it a few months ago, and I felt a flood of regret washing over me that I hadn't discovered it earlier.

**Comment by tpope** [comment]
This sort of stuff usually traces back to another plugin doing some sort of hackish window management.

**Comment by grodzik** [comment]
To be exact this is a problem with Powerline plugin. I moved from Powerline to Airline, because od this issue. It has to do something with getbufvar or similar Vim method (I don't remember exact name od it). Try to disable Powerline and check if it will help.

**Comment by OskarSigvardsson** [comment]
@grodzik Yeah, you're right, that was exactly the problem. Using airline instead of Powerline fixed it. Thanks for the help!
