### ISSUE TITLE
Missing commentstring on commit files

### ISSUE THREAD

**Issue by somini** [tpope/vim-fugitive#759]
The gitcommit filetype should have a commentstring defined.
A simple file `ftplugin/gitcommit/comments.vim` with
```
setl commentstring=#\ %s
```
will do.

**Comment by glittershark** [comment]
you probably want https://github.com/tpope/vim-git

**Comment by somini** [comment]
That's right, I wasn't aware of that separate project.

**Comment by somini** [comment]
It's https://github.com/tpope/vim-git/pull/38
