### ISSUE TITLE
New option to start Gdiff in a new tab

### ISSUE THREAD

**Issue by ronniel1** [tpope/vim-fugitive#76]
Hi,

   I really like this plugin.
One thing that would make it easier to use, for me, is a variant of Gdiff to open the diff in a new tab.

Thanks
Ronnie

**Comment by acornejo** [comment]
Can this solution be easily extended to open diff in a tab while in the Gstatus window?

The obvious thing which is

```autocmd FileType gitcommit noremap <buffer> dt :GdiffInTab<CR>```

Doesn't really work for various reasons (new tab looes Gstatus state, and we would want to open a tab and then do Gdiff with the file on the current line of Gstatus). This really feels like something that would be better if built into fugitive.

**Comment by acornejo** [comment]
For posterity this is the hack I came up with

```
function GStatusTabDiff()
  if has('multi_byte_encoding')
    let colon = '\%(:\|\%uff1a\)'
  else
    let colon = ':'
  endif
  let filename = matchstr(matchstr(getline(line('.')),'^#\t\zs.\{-\}\ze\%( ([^()[:digit:]]\+)\)\=$'), colon.' *\zs.*')
  execute ':Gedit ' . filename
  Gvdiff
endfunction
command GStatusTabDiff call GStatusTabDiff()
autocmd FileType gitcommit noremap <buffer> dt :GStatusTabDiff<CR>
```

The regexps look pretty complex, but I decided to copy them from what fugitive uses internally since its battle tested.

**Comment by sflip** [comment]
While @acornejo was helpful for me, it doesn't seem to work anymore in recent versions of this plugin. See [my answer here](https://github.com/tpope/vim-fugitive/issues/1451#issuecomment-765576235) for a working alternative.
