### ISSUE TITLE
Mapping `y<C-G>` from outside fugitive.vim

### ISSUE THREAD

**Issue by jooize** [tpope/vim-fugitive#761]
Is there any way to map these from outside `fugitive.vim`?

```
cnoremap <buffer> <expr> <C-R><C-G> fnameescape(<SID>recall())
nnoremap <buffer> <silent> y<C-G> :call setreg(v:register, <SID>recall())<CR>
```

The idea is to map `c<C-G>` with [vim-colemak](https://github.com/jooize/vim-colemak) (where `c` is mapped to `y`). `<C-R><C-G>` should stay as is.

Can I take what `y<C-G>` is mapped to at runtime, and map `c<C-G>` to that? Example:

```
nnoremap <buffer> <silent> c<C-G> :call setreg(v:register, <SNR>50_recall())<CR>
```

Appears to work. Any advice for how to get the mapping of `y<C-G>` using VimL?

A problem with doing that however is I don't know a way to unmap `y<C-G>` only if it's set by vim-fugitive, to avoid unsetting desired mappings.

Relevant: https://github.com/tpope/vim-fugitive/issues/394

**Comment by tpope** [comment]
You can get it with `maparg("y\<C-G>", 'n')` and unmap it afterwards with `nunmap <buffer> y<C-G>`.

I think I'd be okay with making `s:recall()` a public function. If that would help send a pull request.

**Comment by linduxed** [comment]
My solution was to use the undocumented feature of [disabling all mappings](https://github.com/tpope/vim-fugitive/blob/master/plugin/fugitive.vim#L214). One can quite easily define mappings oneself.

**Comment by tpope** [comment]
https://github.com/tpope/vim-unimpaired/blob/bacf1543cc957d47aa70c1dc0bcf99392925b008/doc/unimpaired.txt#L148-L169 is a new map customization system I've been using that is a great fit for alternative keyboard layouts. Porting it to Fugitive would be great.  With it in place, vim-colemak could solve the problem out of the box.
