### ISSUE TITLE
cac on :Gstatus removes lines from the current buffer

### ISSUE THREAD

**Issue by Tranquility** [tpope/vim-fugitive#762]
If I use <kbd>cac</kbd> to amend my changes to the last commit I see the "Press ENTER or type command to continue" message which tells me "x fewer lines" after I press ENTER once. After I press it a second time it closes but I am in insert mode and all the line from the current line up to the top are removed. 
It also happens if I remove all plugins and most of my configuration from my .vimrc file.

But it does not happen if I use `:Gcommit --amend`.

I am happy about every hint on how to fix this. Please tell me if you need any more information.

**Comment by tpope** [comment]
The map is `ca`, not `cac`.

**Comment by Tranquility** [comment]
:flushed: Thanks!
