### ISSUE TITLE
:Gmove trouble on filename with '#' (pound sign)

### ISSUE THREAD

**Issue by otterpro** [tpope/vim-fugitive#763]
Hi, I am unable to use a filename with "#" (pound sign) when using :Gmove.  If I do, I get a very strange filename, as it looks like it is substituting "#" with the filename from another buffer in vim.

For example, these will change the filename to something weird.

    :Gmove Hello#World.txt
    :Gmove ThisWontWorkEither#.txt

Am I doing anything incorrectly?  Thank you

**Comment by tpope** [comment]
You need to `\` escape the the `#`, just like with `:edit`
