### ISSUE TITLE
"gx" fails to open URL's under cursor from commit buffer

### ISSUE THREAD

**Issue by h3xx** [tpope/vim-fugitive#764]
**(Note: I'm fairly convinced this is a bug in netrw, having to do with the `fugitive:///` file path making netrw think it's viewing remote file and causing `NetrwBrowseX` to behave differently)**

Fugitive version: 19d1c944dbf59f252135688018610a12ce5718b4 (2016-03-09)
Vim version: 7.4 (patches 1-1530)
Netrw version: ([netrw.vim](https://github.com/vim/vim/blob/master/runtime/autoload/netrw.vim) 155 2016-02-16, [netrwFileHandlers.vim](https://github.com/vim/vim/blob/master/runtime/autoload/netrwFileHandlers.vim) 11b 2013-05-03, [netrwSettings.vim](https://github.com/vim/vim/blob/master/runtime/autoload/netrwSettings.vim) 15 2014-12-30)

I have verified under a clean-room environment with only fugitive installed.
### Symptoms:
- When viewing a commit in a `fugitive:///` buffer, and pressing <kbd>gx</kbd> when the cursor is over a URL in the commit message, netrw evidently pulls down the remote URL to a temporary file in `/tmp` and passes that file's absolute path to the browser command.
### Expected behavior:
- Netrw opens the URL under the cursor in the browser defined in `g:netrw_browsex_viewer` by invoking that command with the bare URL.
### Steps to reproduce:
1. Execute the following shell commands to set up a repo:
   
   mkdir _temp
   cd _temp
   git init
   echo 'hello world' >test-file
   git add test-file
   git commit -m $'Test commit\n\nReference: https://example.com/foo'
   vim +Gblame test-file
2. [in Vim] Open commit from fugitive's :Gblame view in split buffer using <kbd>o</kbd>
3. Move cursor over any part of the URL in the commit message
4. Use <kbd>gx</kbd> to attempt to invoke the browser

**Comment by tpope** [comment]
This is happening for me now, unclear why it took so long. It's absolutely a bug or misfeature in Netrw. Nothing I can do about it, I don't think, if someone could report it upstream that would be great.
