### ISSUE TITLE
U does not delete Untracked files

### ISSUE THREAD

**Issue by firedev** [tpope/vim-fugitive#765]
Is it possible to `rm` them? Thank you.

**Comment by tpope** [comment]
It calls `git clean` on them, which should delete them if you haven't configured it to do otherwise.

**Comment by firedev** [comment]
Thanks for the insight. However, it might be the default behaviour. Added the following my git config:

```
git config --global clean.requireForce false
```

**Comment by justinmk** [comment]
I believe @firedev is right. 

```
$ touch foo
$ git clean foo
fatal: clean.requireForce defaults to true and neither -i, -n, nor -f given; refusing to clean
```

**Comment by firedev** [comment]
Maybe use `git clean -f`?

**Comment by tpope** [comment]
Yes
