### ISSUE TITLE
Gcommit silently fails on fresh git

### ISSUE THREAD

**Issue by jdagilliland** [tpope/vim-fugitive#766]
When git is not configured (no user name or e-mail), and an attempt to `git commit` is made, it results in a fatal error that starts with `*** Please tell me who you are.[...]`.
When instead `:Gcommit` is run while git is so freshly unconfigured, it simply fails silently, saying only `fugitive:`.

The issue seems to come down to the portion of the function `s:Commit` that is responsible for detecting various git errors, but I'm not sure of the best way to fix it.

**Comment by sirex** [comment]
Same here, just installed Ubuntu 16.04 and neovim shows strange `fugitive:` message on `:Gcommit`. Setting git username/email make `:Gcommit` work again.

**Comment by tpope** [comment]
It shows all stderr output now.
