### ISSUE TITLE
Go to previous window/split on Gblame quit not working (or not implemented)

### ISSUE THREAD

**Issue by anemator** [tpope/vim-fugitive#770]

**Comment by tpope** [comment]
Please provide further details if this is still an issue.

**Comment by anemator** [comment]
Hey Tim, sorry for the poor title/explanation.

Steps to reproduce:
1. open file A (where A is file in some git repo)
2. type `:vsplit` so now you have A and A side-by-side
3. type ':Git blame'
4. press gq to quit the blame popup

result: the cursor always goes to the left split regardless of the original side of the cursor.
expected: the cursor goes back to the last 'focused' split.

A similar problem happens with horizontal splits.

Not a pressing issue (clearly), but if you also agree this is a bug and feel like taking a look some day...

Thanks!
