### ISSUE TITLE
Gbrowse {range} gives an incorrect github url

### ISSUE THREAD

**Issue by goldenapples** [tpope/vim-fugitive#772]
Hi, been loving this plugin for a long time. I've got one beef with it, though:

Selecting a range of text in visual mode, and typing `:Gbrowse` will open up a url that looks like

```
https://github.com/tpope/vim-fugitive/blob/master/plugin/fugitive.vim#L2193-2402
```

On github, though, that url format doesn't open with the selected text highlighted. I think it should actually be something like

```
https://github.com/tpope/vim-fugitive/blob/master/plugin/fugitive.vim#L2193-L2402
```

**Comment by tpope** [comment]
This was fixed long ago; you must be out of date.

**Comment by goldenapples** [comment]
Oh! Sorry then. I made sure to pull latest first, apparently I didn't source the new files...
