### ISSUE TITLE
Gitv is looking for a Maintainer 

### ISSUE THREAD

**Issue by luisdavim** [tpope/vim-fugitive#774]
Hi, Gitv (https://github.com/gregsexton/gitv) is looking for a maintainer and since it is an extension to vim-fugitive, would you consider adopting it or even merging the two projects together?

**Comment by tpope** [comment]
I don't have bandwidth for this, no.

**Comment by justinmk** [comment]
@luisdavim  see https://github.com/junegunn/gv.vim

**Comment by luisdavim** [comment]
Thanks @justinmk the only thing gv.vim is missing for me is the side by side diff in file mode.
