### ISSUE TITLE
restoring settings after exiting Gdiff

### ISSUE THREAD

**Issue by minusf** [tpope/vim-fugitive#777]
i see several issues (#38, #132, #194, #360, #567) where settings are "lost"
upon exiting `Gdiff`. i personally do not think it is fugitive's job to set/unset
settings, but it would be nice if it honoured my settings and restored them afterwards.

my use case is similar to those issues. normally i use `cursorline`, `number`,
`relativenumber`, folds, etc but these are distracting in diff mode, so i turn them off:

```
set number
set cursorline
augroup MyAutoCmd
  autocmd!
  autocmd InsertEnter * if &number | setlocal relativenumber | endif
  autocmd InsertLeave * if &relativenumber | setlocal norelativenumber | endif
  autocmd FilterWritePre * if &diff | setlocal fdc=0 nocursorcolumn nocursorline nonumber norelativenumber | endif
augroup END
```

After coming back from diff mode, except the fold settings, the rest is "lost".
My quick and hacky solution is this:

``` patch
diff --git a/plugin/fugitive.vim b/plugin/fugitive.vim
index b2f7785..6e16107 100644
--- a/plugin/fugitive.vim
+++ b/plugin/fugitive.vim
@@ -1706,6 +1706,9 @@ function! s:diff_restore() abort
         \ . ' foldcolumn=' . &l:foldcolumn
         \ . ' foldlevel=' . &l:foldlevel
         \ . (&l:foldenable ? ' foldenable' : ' nofoldenable')
+        \ . (&l:cursorline ? ' cursorline' : ' nocursorline')
+        \ . (&l:number ? ' number' : ' nonumber')
+        \ . (&l:relativenumber ? ' relativenumber' : ' norelativenumber')
   if has('cursorbind')
     let restore .= (&l:cursorbind ? ' ' : ' no') . 'cursorbind'
   endif
```

I am sure there is a better way for `s:diff_restore()` to be "more intelligent"
but i am out of my depth here.

**Comment by tpope** [comment]
My memory of this is fuzzy; can you remind me what exactly it is we're doing that affects any of those options? The fold stuff is intertwined with how diffing works, but I don't recall anything that would affect, say, `'cursorline'`.

**Comment by minusf** [comment]
it's not fugitive that changes those settings, i am -- when entering `diff` mode (`FilterWritePre`).
but these settings are _only_ for diff mode (less clutter, different colorscheme, etc).
so the wider problem is, that these "diff-mode only settings" stay in effect after exiting diff mode.

**Comment by squfrans** [comment]
rereading this, i wonder why i never tried to use `FilterWritePost` to restore those settings...

```
  autocmd FilterWritePre * if &diff | setlocal fdc=0 nocursorcolumn nocursorline nonumber norelativenumber | endif
  autocmd FilterWritePost * if &diff | setlocal cursorline number relativenumber | endif
```

can you please close this? :}

**Comment by minusf** [comment]
rereading this, i wonder why i never tried to use `FilterWritePost` to restore those settings...

```
  autocmd FilterWritePre * if &diff | setlocal fdc=0 nocursorcolumn nocursorline nonumber norelativenumber | endif
  autocmd FilterWritePost * if &diff | setlocal cursorline number relativenumber | endif
```

can you please close this? :}

**Comment by miquecg** [comment]
@minusf I'm having the same problem for changing settings after invoking `Gdiffsplit`. `colorscheme` or several others I've tried do not change at all.

```vim
if &diff
  colorscheme PaperColor
endif

autocmd FilterWritePre * if &diff | colorscheme PaperColor | endif
```

Is this still working for you?

**Comment by minusf** [comment]
my use case has changed since and i dont have any of those autocmd's anymore, sorry.

**Comment by miquecg** [comment]
> ```viml
> if &diff
>   colorscheme PaperColor
> endif
> 
> autocmd FilterWritePre * if &diff | colorscheme PaperColor | endif
> ```

@tpope Could this possibly work? Is there anything wrong with the `autocmd` as is?

**Comment by tpope** [comment]
`FilterWritePre` is way, way off base. Look into `OptionSet`, maybe.

**Comment by miquecg** [comment]
Thanks. I've found an example that it can be done with `OptionSet`: https://github.com/tpope/vim-fugitive/issues/1545

But now I face another problem, status line colors disappear when entering the diff split mode.

```
colorscheme gruvbox
autocmd OptionSet diff colorscheme PaperColor
```

Do you have any guess of what could be happening? If I just change the colors manually when in diff mode, status line stays the same.

**Comment by miquecg** [comment]
I kind of have it working after adding `++nested` to the `autocmd` based on https://github.com/itchyny/lightline.vim/issues/406.

```vim
function! ToggleColors()
  if &diff | colorscheme PaperColor | else | colorscheme gruvbox | endif
endfunction

call ToggleColors()

augroup VimDiff
  autocmd!
  autocmd OptionSet diff ++nested call ToggleColors()
augroup END
```

But now there's another issue because the wrong status line is highlighted when the diff split opens.
