### ISSUE TITLE
git_dir/tags is not read when opening vim with multiple empty windows

### ISSUE THREAD

**Issue by Cydfrey** [tpope/vim-fugitive#781]
Hi,

I've noticed a small issue when opening vim with multiple windows, if one or more windows after the first one are empty.
Example: with `vim -O2 <file>`, the first window will have the `tags` parameter include `git_dir/tags` but not the empty, second one. If I do `vim -O2 <file1> <file2>` I have the `git_dir/tags` file sourced in both windows.

I noticed this because I am often working with NERDTree, and I am often opening vim with only the NERDTree open. That makes the directory tree window have the `git_dir/tags` file sourced but not the second window (the one I will be working in), which is empty at this time.

For me, the `tags` file should be sourced in all opened windows, empty or not empty. What do you think?

**Comment by tpope** [comment]
There is no autocommand for opening an empty window, so I'm going to say this is impossible.
