### ISSUE TITLE
Impossible to enter password to sign commit in Neovim

### ISSUE THREAD

**Issue by wichtounet** [tpope/vim-fugitive#782]
Hi, 

I don't know what is the status of the support of Neovim. If you don't plan to support it fully, you can delete this issue ;)

I'm signing my Git commits in some projects. When I do, I have to set the password of my GPG key. This works perfectly from vim, but does not work well at all from neovim. What I do is open the status window, type the commit enter, validate it and then the GPG window appears. And here it is really weird, but _most of the keys I type are lost_, it is as if it was lagging as hell. I haven't been able to type my password in. Probably due to the way the git process is spawn ?

Thanks

**Comment by tpope** [comment]
Neovim is supported but you're on your own for chasing down this one. Neovim's terminals are strange.

**Comment by J3RN** [comment]
I am also having this issue. I'll try to do some digging if I have the time.

**Comment by J3RN** [comment]
It looks like the root of the issue is that a user cannot input into a shell command run with `!` in NeoVim (whereas they can with Vim). I'm not sure if this is intentional behavior of NeoVim.

**Comment by dmerejkowsky** [comment]
Maybe you could use something like this on neovim?

```
:terminal git commit -s
```

**Comment by monokrome** [comment]
Seems like I get the same issue in MacVim as well. Is this not supported either? I'll try gvim later

**Comment by J3RN** [comment]
@dmerejkowsky The only issue with this is that you get your git editor inside the Vim terminal, which can be weird if your git editor is Vim.
<img width="605" alt="screen shot 2016-06-09 at 12 53 21" src="https://cloud.githubusercontent.com/assets/2058614/15938446/2e1eec38-2e41-11e6-98bf-2fd8f169995e.png">

**Comment by appplemac** [comment]
Getting the same issue in MacVim.

```
$ gpg-agent
gpg-agent: gpg-agent running and available
```

But getting the following when using `:Gcommit`:

```
"~/code/frontend/.git/COMMIT_EDITMSG" 9L, 284C written
fugitive: error: gpg failed to sign the data 
```

MacVim 8.0, macOS 10.12, GPG Suite 2016.10.

**Comment by jaysoifer** [comment]
@appplemac I was suffering just like you...

Just found out a [solution](http://stackoverflow.com/questions/43078230/unable-to-use-gcommit-fugitive-plugin-on-vim-when-signing-commits/43078307#43078307)

**Comment by qrevel** [comment]
`no-tty` solution doesn't work with a passphrasse:
`gpg: can't connect to the agent: IPC connect call failed`

**Comment by tpope** [comment]
See #846.
