### ISSUE TITLE
:Git don't play well with empty buffers

### ISSUE THREAD

**Issue by MaG21** [tpope/vim-fugitive#783]
:Git status

Error detected while processing function <SNR>17_Git:
line   11:
E499: Empty file name for '%' or '#', only works with ":p:h":     tabedit %

![screen shot 2016-04-13 at 5 34 13 pm](https://cloud.githubusercontent.com/assets/1760771/14510379/295b8356-019f-11e6-8b96-563a2c7205e4.png)

**Comment by tpope** [comment]
Looks to be an issue with the hoops we are jumping through to accommodate Neovim's `:terminal`. Open to suggestions.

**Comment by MaG21** [comment]
It works well in Vim.
