### ISSUE TITLE
Option to checkout a branch

### ISSUE THREAD

**Issue by skgbanga** [tpope/vim-fugitive#790]
This was slightly discussed in issues #441 but I would like to present a fresh perspective:

Let's say I am working on branch _feature_ which is n commits ahead of branch _master_, and I have some buffers open in my vim which contain changes from those n commits. Now I want to change my branch to _master_. If I do

> :Git branch _master_

I would get:

> file "xyz" has changed since editing
> [O]K, (L)oad File

On pressing L, I would get 
> "Press Enter or type command to continue"

I would have to press L for all the open buffer files. 

It would be nice to have a command (:Gbranch?) which does all of this automatically, and I would never have to go to 'shell'.

**Comment by skgbanga** [comment]
Also note that if someone can guide me on how it can be done (or if there is a better way), I am happy to work on it.

**Comment by glittershark** [comment]
Would `:bufdo e!` do it?

**Comment by aschrab** [comment]
You can `:set autoread` to reload those files without prompting as long as there aren't any unsaved changes to the vim buffer.

**Comment by tpope** [comment]
Yeah I think `'autoread'` is the way to go.

**Comment by skgbanga** [comment]
'autoread' certainly helps. Thanks!
