### ISSUE TITLE
Add Gstatusdo command

### ISSUE THREAD

**Issue by ktonga** [tpope/vim-fugitive#793]
I have implemented it as a function in my `vimrc`, it accepts a pattern and a Vim command as parameters, and what it does is to filter the files returned by `git status` using the given pattern and sets the result using `args`. Then it invokes `argdo` passing the given command.

It's handy to apply some action to all (or some) modified files.

I use it like:

``` VimL
Gstatusdo('\.scala$', 'call SortScalaImports() | update')
```

To sort imports on all modified Scala files.

Do you think it is worth it to add it to the core **vim-fugitive** commands?
If you do, I can work on a PR to contribute it.

Thanks.

**Comment by tpope** [comment]
I wouldn't entertain that interface but maybe something along the lines of

    :Glsfiles *.scala | cdo call SortScalaImports() | update

**Comment by ktonga** [comment]
Are you gonna merge #469 ?

The line you are suggesting could be used directly in a mapping.
Currently, I'm getting the file list with:
```VimL
system('git status --porcelain | grep ... | awk ... | xargs')
```

**Comment by tpope** [comment]
Looks like my most recent thoughts are over in #132. Basically, wrap `git diff --name-status`. Can that address your use case?

**Comment by ktonga** [comment]
Sure, any git command that lists all modified (and added) files will work for my use case.
Feel free to close this issue in favor of #132 

Thank you very much.

**Comment by tpope** [comment]
Further updates in #132.
