### ISSUE TITLE
what happens when adding a "!" after the G command

### ISSUE THREAD

**Issue by wangxiexe** [tpope/vim-fugitive#794]
I did not see the doc about Glog! , but it does help for me as it does not edit the temp.

So as this piece of info is missing in the doc, I just wonder if it is globally supported for adding "!" after the G commands and if it is , what the result for adding "!" .

Thx.

**Comment by lifecrisis** [comment]
The code says that `:Glog!` and `:Gllog!` are supported as one would expect.  The line that does this can be found [here](https://github.com/tpope/vim-fugitive/blob/master/autoload/fugitive.vim#L3137).

The support for this feature is not documented.

**Comment by tpope** [comment]
Docs updated.
