### ISSUE TITLE
Glog -Ssomething with spaces -- not working

### ISSUE THREAD

**Issue by Fab1n** [tpope/vim-fugitive#795]
outputs `fatal: Option 'S' requires a value` multiple times which I did expect.

`Glog -S"something with spaces" -- not working` does not work either. 

How can a pickaxe log something with spaces?

**Comment by Fab1n** [comment]
also `'` didn't do it either

**Comment by tpope** [comment]
It uses Vim's definition of word breaking, which means `Glog -Ssomething\ with\ spaces` should work.
