### ISSUE TITLE
vim-fugitive  Shortcut conflict

### ISSUE THREAD

**Issue by aixiaoxiaoyu** [tpope/vim-fugitive#796]
version: Ubuntu 14.04

rtk@ubuntu:/$ gvim hello.c
Error detected while processing /home/rtk/.vimrc:
line  451:
E18: Unexpected characters in :let
Error detected while processing function vundle#config#bundle..<SNR>19_check_bundle_name:
line    2:
Vundle error: Name collision for Plugin tpope/vim-fugitive. Plugin tpope/vim-fugitive previously used the name "vim-fugitive". Skipping Plugin tpope/vim-fugitive.
Error detected while processing /home/rtk/.vim/bundle/newL9/plugin/l9.vim:
line   88:
E174: Command already exists: add ! to replace it
line   99:
E174: Command already exists: add ! to replace it
line  104:
E492: Not an editor command: A

**Comment by tpope** [comment]
Sounds like an issue with you trying to load the plugin twice.

**Comment by aixiaoxiaoyu** [comment]
Yes.Thank you.
