### ISSUE TITLE
mapping for ``diffget //2`` and ``diffget //3``?

### ISSUE THREAD

**Issue by mcepl** [tpope/vim-fugitive#798]
I really like `dp` and `do` shortcuts in two-split merge window. I know that `dp` works even in the three-split merge window, but for `diffget` I have to run whole complicated `:diffget //2<CR>` and `:diffget //3<CR>`. Could we get some Gdiff (or diff) specific shortcuts, like e.g.

```
nmap d2 :diffget //2<Cr>
nmap d3 :diffget //3<Cr>
```

Of course I can add these mappings to my `~/.vimrc`, but it would be lovely if they were just three-split window specific.

**Comment by mcepl** [comment]
Actually, @tpope , what do you think about?
```diff
 $ git diff
diff --git a/plugin/fugitive.vim b/plugin/fugitive.vim
index 06d2e87..7e0835d 100644
--- a/plugin/fugitive.vim
+++ b/plugin/fugitive.vim
@@ -1783,6 +1783,8 @@ function! s:Diff(vert,keepfocus,...) abort
     call s:diffthis()
     wincmd p
     call s:diffthis()
+    execute 'nnoremap <buffer> <silent> d2 :diffget //2<Bar>diffupdate<CR>'
+    execute 'nnoremap <buffer> <silent> d3 :diffget //3<Bar>diffupdate<CR>'
     return post
   elseif len(args)
     let arg = join(args, ' ')
 $
```

**Comment by tpope** [comment]
No good, `d2` could be the start of a valid command like `d2d`.

**Comment by mcepl** [comment]
> No good, d2 could be the start of a valid command like d2d

Would anybody miss ``d2d`` and ``d3d`` inside of the middle of buffer of the three-panel diff window? OK, probably, somebody would. Any idea for better shortcuts?

**Comment by justinmk** [comment]
d2p, d3p, d2o, d3o

**Comment by tpope** [comment]
`d2o` style sounds good. Link it to the buffer number rather than `//2` and you've got yourself a commit.

**Comment by mcepl** [comment]
@tpope is this what you meant?

**Comment by tpope** [comment]
You'll need to do something [like this](https://github.com/tpope/vim-fugitive/blob/bdd216827ae53cdf70d933bb30762da9bf42cad4/plugin/fugitive.vim#L1782), only instead of `nr`, you'll need other temp variables where you've stashed the other 2 buffer numbers.

**Comment by mcepl** [comment]
I don't want argue, just curious. May I ask why? What's the difference between:
```viml
let b3nr = bufnr('//3')
execute "diffget " . b3nr
```
and
```viml
execute "diffget //3"
```
?

**Comment by tpope** [comment]
Because it avoids any ambiguity with multiple `//3` buffers. And to that end, `bufnr('//3')` has the the same problem.

**Comment by mcepl** [comment]
So, what do you suggest? How to say "buffer on the left", and "buffer on the right"? Also, I have to admit I have never seen more than three-split. How to get there (ignoring possibility of running split in diff-mode; that seems silly).

**Comment by tpope** [comment]
Save the buffer number with `let nr2 = bufnr('')` immediately after the `split` command that opens it.

**Comment by mcepl** [comment]
@tpope you were saying that I had a commit ... ;)

**Comment by tpope** [comment]
Please make a pull request.

**Comment by mcepl** [comment]
Ehm, that’s #801.
