### ISSUE TITLE
Provide an API / option to get shortened commit

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-fugitive#799]
It would be nice if fugitive could use abbreviated commit hashes by default and/or allow to get it through `buffer_commit`.

**Comment by tpope** [comment]
You mean something like `buffer.commit()[0:6]`? I'm not sure I see a need to complicate the API just for that.

**Comment by tpope** [comment]
The new way to get this would be something like `matchstr(FugitiveParse()[0], '^\x\{7\}')`. I don't think I'll be providing a dedicated API for this. Using shortened hashes by *default* means more `rev-parse` calls when we need to get the full hash back, not an acceptable tradeoff in my book.
