### ISSUE TITLE
Provide an easier API to get the absolute file path

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-fugitive#800]
I have found `fugitive#buffer().repo().tree(fugitive#buffer().path())`, but this could be provide through e.g. `fugitive#buffer().abs_path()`.

Seems to be a common thing if you look at improving the display in statusline / titlestring.

**Comment by tpope** [comment]
Does `.spec()` do the trick?

**Comment by blueyed** [comment]
Yeah, of course.
Sorry for missing it!
Thanks!

**Comment by blueyed** [comment]
Well, it does not actually: it will return the `fugitive://` spec.
I've only tested it on the working copy version apparently.

**Comment by blueyed** [comment]
Assuming you've meant `fugitive#buffer().spec()`?!

**Comment by tpope** [comment]
`FugitiveReal()` does this now.
