### ISSUE TITLE
U on untrack files does not work (on windows 10)

### ISSUE THREAD

**Issue by wangxiexe** [tpope/vim-fugitive#807]
I am setting up a new dev env on windows 10 and noticed U does not work on untracked file any more after installing fugitive (it works fine with tracked file )

it did print this message : To restore, :Git cat-file blob.....

but the file is still there

I did not find any place where I can check the log, please advise. 

Thanks

**Comment by justinmk** [comment]
Solution is here: https://github.com/tpope/vim-fugitive/issues/765

Someone just needs to send a PR :)

**Comment by wangxiexe** [comment]
yes, I just replaced the vimfiles with the old isntallation, it works fine... 

please help fix in the latest version

**Comment by tpope** [comment]
It's fixed.
