### ISSUE TITLE
Execute function/command after successful committing

### ISSUE THREAD

**Issue by hkupty** [tpope/vim-fugitive#808]
I didn't find anywhere else to check this, so sorry if I'm using the wrong channel.

I want to trigger a function (specifically, `SignifyRefresh`, from [mhinz/vim-signify](https://github.com/mhinz/vim-signify)) just after successfully committing anything, so I get the gutters refreshed. Is this somehow possible (or would it be possible by extending the code in a feasible manner)?

Thanks in advance.

**Comment by tpope** [comment]
I would think an event like `autocmd BufDelete COMMIT_EDITMSG` would be good enough.

**Comment by hkupty** [comment]
That totally makes sense.. Thanks!
