### ISSUE TITLE
Diffing again in Gstatus diffs in the preview window

### ISSUE THREAD

**Issue by suy** [tpope/vim-fugitive#809]
Hi.

As always, thanks for fugitive, it's awesome, and it helps a lot on my daily workflow.

There is an issue when opening diffs in Gstatus when there is already a diff view added. Try the following.
- Modify a couple of files in the repository.
- Open Gstatus
- Press `D` on the first file. Two versions of the file show well
- Move again to the preview window where Gstatus is shown
- Press `D` on the second file. Now the two sides of the diff are in the preview window instead of where they used to be. :(

I've bisected, and it seems the commit that introduced it was 933f6a1e1df549564062f936bd1c836d28cf1676.

Closing the file on the window that shows the git index version of the file prevents the problem from happening.

Thank you!

**Comment by tpope** [comment]
@blueyed, any thoughts?

**Comment by blueyed** [comment]
Sorry, I cannot look at it currently.
Would have to investigate / try to replicate it.

**Comment by dhruvasagar** [comment]
I believe this is a non-issue now, unable to reproduce it.

**Comment by blueyed** [comment]
Thanks.

@suy 
Do you agree?

**Comment by suy** [comment]
I have not been able to reproduce it lately, but I changed habits a bit in order to ensure I never triggered the issue. I did a quick check and I'm not able to reproduce it either with the old habit, so I'll just close.

(Sorry for the delay, my github folder is full of noise)
