### ISSUE TITLE
Move cursor directly to the first modified or untracked file in GStatus

### ISSUE THREAD

**Issue by purpleP** [tpope/vim-fugitive#812]
It would be more efficient if you wouldn't need to press things like `7j` and only then `-`.

I've actually already implemented this, but haven't done fork.

```
function! s:Status() abort
    ...
    let pos = search('modified')
    if pos == 0
      pos = search('untracked')
    endif
```

Also it would be nice to make `-` take motions and text objects. So if you need to add all files at once you just press `-ap` etc.

**Comment by justinmk** [comment]
ctrl n

**Comment by purpleP** [comment]
@justinmk Oh, thanks for pointing this out. I've skimmed through the docs and have seen this, but the issue remains. This should be automated because there's not point in not doing that. It's unobtrusive etc. I've modified the solution to use `execute <SID>s:StageNext(...)` thanks to you.

**Comment by tpope** [comment]
There is a point in not doing it because the first line has some valid edge
case actions on it.

**Comment by tylerbrazier** [comment]
Something like this works
```
nmap <leader>gs :Gstatus<cr><c-n>
```

**Comment by sinisterstuf** [comment]
With @tylerbrazier's comment shall we consider this issue resolved and close it?

The other part

> Also it would be nice to make `-` take motions and text objects. So if you need to add all files at once you just press `-ap` etc.

seems like a separate and unrelated issue to me.

**Comment by tpope** [comment]
You can now use `gu` to jump to the untracked/unstaged sections. The new status window has more than just files in it, so automatically jumping to a file is hereby declared arbitrary and wontfix.

> Also it would be nice to make `-` take motions and text objects. So if you need to add all files at once you just press `-ap` etc.

You say "etc", but the only two motions I can think of you'd actually use are "`[count]` files" and "all files", and these are solved by `[count]-` and selecting the section header, respectively. And taking a motion would have the significant downside of making you have to do `--` just to stage one file.

**Comment by 3nuc** [comment]
See https://github.com/tpope/vim-fugitive/issues/1252#issuecomment-508088610 for ftplugin that moves you to first dirty file in Gstatus
