### ISSUE TITLE
Force Gstatus to split above

### ISSUE THREAD

**Issue by nwaywood** [tpope/vim-fugitive#813]
I have `set splitbelow` in my vimrc because I prefer my splits from ctrlp, NERDTree etc to split below. However this setting also effects splitting when using `:Gstatus` (which I would like to split above)

I have tried `:aboveleft Gstatus` and `:topleft Gstatus` but neither works, it still splits below. The commands do work for non fugitive commands though.

Is it possible to force `:Gstatus` to split above? 

Edit:

To further elaborate on this, from the `:h :aboveleft`/`:h :belowright` docs:

> Overrules 'splitbelow' and 'splitright'

So it seems like `:Gstatus` is not respecting the `:aboveleft` and `:belowright` behaviour to override the `splitbelow` setting.

**Comment by nwaywood** [comment]
@tpope any thoughts on this?

**Comment by edkolev** [comment]
Maybe s:Edit() (here somewhere https://github.com/tpope/vim-fugitive/blob/master/plugin/fugitive.vim#L1429) has to take into account whether `:topleft` has been prepended to the command.

However, I'm not sure vimscript can even check this (there's no &topleft option)

**Comment by tpope** [comment]
The default has been changed to respect `'splitbelow'`, and mods like `:aboveleft` are now respected (requires `<mods>` which didn't exist when the request was made).
