### ISSUE TITLE
Opening files from Gstatus window don't work with french language

### ISSUE THREAD

**Issue by KabbAmine** [tpope/vim-fugitive#815]
First of all, thanks for the wonderful plugin, I'm using it for years and its a real life savior :smiley: 

Looks like we have the same issue as #806, but with `LANG=fr_FR.UTF-8`.
In `Gstatus` window:

![gstatus](https://cloud.githubusercontent.com/assets/5658084/16579351/64fcc008-42b0-11e6-9ff0-2ecb46ee8153.png)

Pressing `<CR>` on the 1st file opens `modifié :         README.md` instead of `README.md`.

**Comment by tpope** [comment]
My guess is the extra space before the colon is killing it, if you want to try your hand at tweaking the regexp.

**Comment by KabbAmine** [comment]
I'll give a try
