### ISSUE TITLE
Runtime errors when fugitive.vim is encoded with Windows line endings

### ISSUE THREAD

**Issue by kaepora** [tpope/vim-fugitive#818]
When running the latest `fugitive.vim` under Cygwin on Windows, I get the following error:

```
$ vim
Error detected while processing /home/Nadim/.vim/bundle/vim-fugitive/plugin/fugitive.vim:
line    5:
E492: Not an editor command: ^M
line    6:
E15: Invalid expression: exists('g:loaded_fugitive') || &cp^M
line 3097:
E171: Missing :endif
Press ENTER or type command to continue
```

I was able to fix this error by running `dos2unix` on `fugitive.vim`.

**Comment by justinmk** [comment]
This is a Vim limitation. There's nothing fugitive can do about it.

**Comment by kaepora** [comment]
@justinmk kthx

**Comment by tpope** [comment]
You should set your Git config to not inject the carriage returns.
