### ISSUE TITLE
Split layout changed after closing Gstatus window

### ISSUE THREAD

**Issue by languitar** [tpope/vim-fugitive#819]
When using e.g. `GStatus` in a vim with several splits it is quite likely that after closing the status window, the layout of the splits (in terms of heights) is different then before opening the status window. It would be nice if things could be preserved.

I am not sure how easy this is to address in vim at all and this is possibly at least related to junegunn/fzf#520.

**Comment by ohcibi** [comment]
I can confirm this and I had the same issue with another plugin that spawned a window like fugitive does (denite.vim, latest version has fixed that). Reproducing is easy:

1. Open vim inside a git repo
2. `split`
3. `resize <some-number>`
4. `:Gstatus<cr>`
5. `q`
6. Split position is at default when it should be at `<some-number>`

**Comment by tpope** [comment]
`:Gstatus` behaves the same way `:split` does. See `:help 'equalalways'`, that's what's causing the resizing. I do not consider this a bug.
