### ISSUE TITLE
Splitting hunks in `:Gdiff`

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [tpope/vim-fugitive#82]
Pretty much, what the title says. I don’t see any way to split hunks in `:Gdiff` mode before `go`\- or `gp`-ing them.

This may be something that fugitive can’t do anything about (specific to the vim-diff functionality?) but it’s probably my single-most-requested feature, because this would allow me to do all my interactive staging directly in my editor instead of popping out to `git add -i` to handle it.

**Comment by tlelson** [comment]
Visually selecting and hitting `d` removes the selected lines before i can get the `p` hit.  Is this what you mean by "visually select" @tpope ? Or is then when you would yank/put manually?

**Comment by tpope** [comment]
I'm not sure what I was referring to there, but your description is correct. If you want to use visual mode, you can replace `dp` with `:diffput`.

**Comment by tlelson** [comment]
Thanks for the clarification @tpope. I'm sure I speak for many here when I say I can't convey appropriate appreciation for sharing your work.
