### ISSUE TITLE
":Git rebase -i" not working with neovim

### ISSUE THREAD

**Issue by phmarek** [tpope/vim-fugitive#821]
Although 4cc201cbe3a already looks for `:terminal`, a `Git rebase -i` still says

```
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
Vim: Error reading input, exiting...
```

Using `:terminal git rebase -i ...` works as expected, though.

**Comment by tpope** [comment]
Not sure why this would have failed, but we have native `rebase -i` support now, so this should work fine on the latest.
