### ISSUE TITLE
Implement Irish's git open

### ISSUE THREAD

**Issue by ain** [tpope/vim-fugitive#822]
Would be nice to have something like `:Gopen` that behaves similarly to [paulirish/git-open](https://github.com/paulirish/git-open). 

It could of course be a separate plugin, just posting here for an idea.

**Comment by justinmk** [comment]
@ain What about `:Gbrowse` ?

**Comment by tpope** [comment]
Yes, that.

**Comment by ain** [comment]
Excellent, thanks guys. That works brilliantly.
