### ISSUE TITLE
Renamed file with changes renamed to original file when unstaging

### ISSUE THREAD

**Issue by kaihowl** [tpope/vim-fugitive#824]
Reproduction scenario:

Have a tracked file with name 'A'. Rename the file to 'B'. Make some slight changes in 'B' such that git still can track the rename. Open git :Gitstatus. Stage the untracked file 'B'. Stage the deletion of the tracked file 'A'. Unstage the line for the rename and change of 'A' to 'B'. Observe that the file 'B' is gone and the file 'A' is present again. (Yet the changes made in 'B' are still retained of course. Only the filename changed back.)

The expected behavior would be that file 'B' keeps its name on unstaging the rename status line.

**Comment by tpope** [comment]
So what is the Git command you expect to run when you initiate the unstage?

**Comment by kaihowl** [comment]
For a line "renamed: a -> b" I would expect an unstage of that line to be done with:
```git reset -- a b```
