### ISSUE TITLE
Flashing in Windows taskbar on fugitive event

### ISSUE THREAD

**Issue by andreasthoelke** [tpope/vim-fugitive#826]
Thank you for fugitive, it looks great so far!

When navigating between buffers (:bn, :bp), I notice a slight delay and (what I think is) a command window flashing very briefly in the Windows task bar. (gvim on Windows 10)
It seems the flashing up in the taskbar is happening on every fugitive event.

Is there any trick to prevent this?

Alternatively, as most of the time I'm not actually using git/fugutive, is there a way to temporarily disable/pause fugitive?

**Comment by tpope** [comment]
I went to great care to avoid this. It's possible something bad snuck in, but I think a more likely scenario is some secondary plugin is calling into fugitive to determine the current branch name, or something.

**Comment by andreasthoelke** [comment]
Not sure how I can best test this. I have a lot of plugins. Fugitive is the only git related plugin I’m aware of. Might be airline, as this is showing the current branch.

Would be interesting to hear if other Windows users experience this.

The behaviour I see is: I open (say) 3 buffers. When I go to each of them first, I see the command window flash on each :bn. But when I go back to a buffer it does not flash again. However all open buffers will flash again after I did a commit. Also with many open buffers I have seen flashing each time I (re-)visit a buffer.

**Comment by tpope** [comment]
Yes, airline.

**Comment by andreasthoelke** [comment]
It's airline! 

After I deactivated airline, fugitive did not show the behaviour I described above - no delays, no flashing of command windows. 

This is resolved then, thank you for your help!

I will try to figure out how I can set up airline, so this doesn’t happen.
