### ISSUE TITLE
New mapping request, while in tree type window

### ISSUE THREAD

**Issue by vbauerster** [tpope/vim-fugitive#828]
Dear Tim!

Please consider the situation when one browsing a git tree. It is easy to drill down through the directories, but it’s not obvious how one could go up a level to the parent directory. Running the following command will open the parent tree:

`:edit %:h`

This problem first addressed by Drew Neil, in his [vimcast](http://vimcasts.org/episodes/fugitive-vim-browsing-the-git-object-database/) blog. Drew proposed the following solution:
```vim
autocmd User fugitive 
  \ if fugitive#buffer().type() =~# '^\%(tree\|blob\)$' |
  \   nnoremap <buffer> .. :edit %:h<CR> |
  \ endif
```
However, instead of copy pasting this, I think it would be better to integrate the mapping into the plugin. As for me, it is pretty obvious to press <kbd>u</kbd>, while in tree buffer, to go one level up. Furthermore <kbd>u</kbd> mapping will be consistent with the NERDTree plugin behaviour.
At the moment pressing <kbd>u</kbd> displays useless message: `Cannot make changes, 'modifiable' is off`.

**Comment by justinmk** [comment]
Does `-` not already do what you want?

**Comment by vbauerster** [comment]
Indeed, <kbd>-</kbd> does the trick!
Thank you @justinmk ! I do not mind the issue to be closed now.

**Comment by justinmk** [comment]
`-` is, for better or worse, the convention set by netrw (also used by [dirvish.vim](https://github.com/justinmk/vim-dirvish)). As more plugins adhere to conventions, things become more obvious and predictable.
