### ISSUE TITLE
I need to type `:Gwrite` twice in order to add a file

### ISSUE THREAD

**Issue by sfahlberg** [tpope/vim-fugitive#829]
Not sure why this is happening but I consistently have to type `:Gwrite` twice whenever I want to add a file.

**Comment by edkolev** [comment]
I think I'm having the same issue, however I experience the issue if I run `:Gw` while in `:Gdiff` mode. I reproduce it like so:

1. make a change to some git-tracked-file `test.txt`
2. `:Gdiff`. At this point I have `fugitive://test.txt` in the left buffer, `test.txt` in the right buffer
3. `:Gw` in the right buffer (`test.txt`)
4. Now the left buffer (`fugitive://test.txt`) becomes empty, which is incorrect. I expect the buffer to have the same contents as the right buffer.

Some more details: after 4., if I run `:e` in the left buffer (`fugitive://test.txt`), the left buffer's contents become correct.
Alternatively, if I re-run `:Gw` in the right buffer (`text.txt`) (as @sfahlberg  reported), the left buffer's contents become correct again.

**Comment by tpope** [comment]
This sounds like #1102.
