### ISSUE TITLE
Prevent myself from editing git file after diff

### ISSUE THREAD

**Issue by still-dreaming-1** [tpope/vim-fugitive#830]
I have a problem where I use fugitive to see the diff of a single changed file vs what it was before the changes. Then after viewing the differences, I will sometimes close the wrong buffer and have the file open that shows the old version. I start editing that code thinking it is my code. Eventually I realize my mistake. Is there a setting or something I can use to make that file not editable? What is that file exactly? Am I messing up my git files by editing it?

**Comment by tpope** [comment]
The file is the staged changes - what will be included in the commit. If you add a line to it, it will show up as an addition in `git diff --cached`, but as a removal in `git diff`.

Newer versions of Fugitive focus this new staged changes window by default, so it should be a bit harder to accidentally `:q` the wrong window. You could enforce `:set nomodifiable` with an autocommand, but you'd be losing the ability to change that buffer for legitimate reasons, so I wouldn't recommend it.
