### ISSUE TITLE
Empty buffer_path when repo tree is a symlink

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-fugitive#831]
When in /home/user/.dotfiles/vim/neobundles/ultisnips and with a symlink `/home/user/.vim -> .dotfiles/vim/`:

% vim /home/user/.vim/neobundles/ultisnips/pythonx/UltiSnips/snippet_manager.py

The buffer shows up as "pythonx/UltiSnips/snippet_manager.py", apparently since Vim resolves the symlink.

When calling `:Gdiff` now, I get weird errors like nothing happening on the first call, and then a dir manager opening up (netrw and/or Dirvish).  This is causes by `s:buffer_path` returning an empty string.

While I think there should be a safeguard in `buffer_path`, I could fix it using the following patch:

``` diff
diff --git i/plugin/fugitive.vim w/plugin/fugitive.vim
index 345ea34..a4be745 100644
--- i/plugin/fugitive.vim
+++ w/plugin/fugitive.vim
@@ -589,10 +589,17 @@ function! s:buffer_path(...) dict abort
   elseif s:cpath(self.spec()[0 : len(self.repo().dir())]) ==#
         \ s:cpath(self.repo().dir() . '/')
     let rev = '/.git'.self.spec()[strlen(self.repo().dir()) : -1]
-  elseif !self.repo().bare() &&
-        \ s:cpath(self.spec()[0 : len(self.repo().tree())]) ==#
+  elseif !self.repo().bare()
+    if s:cpath(self.spec()[0 : len(self.repo().tree())]) ==#
         \ s:cpath(self.repo().tree() . '/')
-    let rev = self.spec()[strlen(self.repo().tree()) : -1]
+      let rev = self.spec()[strlen(self.repo().tree()) : -1]
+    else
+      let resolved_tree = resolve(self.repo().tree())
+      if s:cpath(self.spec()[0 : len(resolved_tree)]) ==#
+        \ s:cpath(resolved_tree . '/')
+        let rev = self.spec()[strlen(resolved_tree) : -1]
+      endif
+    endif
   endif
   return s:sub(s:sub(rev,'.\zs/$',''),'^/',a:0 ? a:1 : '')
 endfunction
```

What do you think?  Should I create a PR for that?

**Comment by tpope** [comment]
Alright I think airblade/vim-rooter#60 led me to the root of the matter.  Calling `:cd` or `:lcd` forces the buffer name to be resolved. If this happens after Fugitive has already initialized, `b:git_dir` will be out of sync with the buffer name.  While vim-rooter uses `:cd` for obvious reasons, it could also be any other plugin that changes directory, even temporarily. Lots of plugins use temporarily directory changes including Fugitive itself, so I assume this very issue was triggered by one of them. That's certainly the case on my machine.

Given this newly discovered buffer name fragility, my inclination is just to force a `cd` early to get it over with. I submit for your consideration the `symlink` branch.

**Comment by mcepl** [comment]
yeah, ``symlink`` branch seems to work, I cannot reproduce https://github.com/airblade/vim-rooter/issues/60#issuecomment-297073627 at least.
