### ISSUE TITLE
Autocommands do not fire for files named `index`

### ISSUE THREAD

**Issue by brennen** [tpope/vim-fugitive#834]
I have an autocommand to do some stuff.  I noticed that it fails on files named `index`, I think because fugitive.vim has its own autocommand for `index{,.lock}` that triggers `BufReadIndex()`, which in turn does something to prevent further processing of the event. I'm kind of hazy on how.

Background: I have some blog entries named like `foo/archives/2016/9/8`, and others named like `foo/archives/2016/9/7/index`.  I couldn't figure out why [an autocommand](https://github.com/brennen/bpb-kit/blob/master/home/.vimrc#L389) to set `filetype` was failing on the latter, and figured it must be because I had written the pattern wrong.  Eventually I realized that the function wasn't getting called at all for the `index` files, even with a pattern of `*`.

I dug around in the output of `:autocmd`, which led me to:

```
fugitive_files  BufReadCmd
    index{,.lock}
              if fugitive#is_git_dir(expand('<amatch>:p:h')) |   exe s:BufReadIndex() | elseif filereadable(expand('<amatch>')) |   read <amatch> |   1delete | endif
    fugitive://**//[0-3]/**
              exe s:BufReadIndexFile()
    fugitive://**//[0-9a-f][0-9a-f]*
              exe s:BufReadObject()
```

It turns out that if I start vim without fugitive, the autocmd fires as expected.

Here's a sample `.vimrc`:

```
set nocompatible

filetype off

set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#rc()

" let Vundle manage Vundle - required:
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'

au BufReadPost,BufNewFile * echom "my autocommand fired"
```

This can be tested with `:e index` and `:e some_other_file`.

This is pretty edge-case-y, and not a serious impediment to my work or anything, but it does feel like a thing that shouldn't really happen.

Thanks!

**Comment by tpope** [comment]
I think `doautocmd` is the way to go. It's imperfect but at 2 lines of code I wouldn't really call it complicated.

**Comment by brennen** [comment]
I wasn't sure if it was appropriate to fire both "missing" commands every time - seems like strictly speaking `BufNewFile` at least oughta be conditional on whether the file's new, and I'm not sure whether there are other commands that're blocked here.

Anyhow I can throw together a PR at some point.

**Comment by tpope** [comment]
Indeed it should be conditional. You should be able to use the existing `filereadable()` check for that. Add `BufReadPre` and `BufReadPost` to the `elseif` clause and `BufNewFile` to a new `else` clause.
