### ISSUE TITLE
Undo discard ("U") from status window doesn't work

### ISSUE THREAD

**Issue by TamaHobbit** [tpope/vim-fugitive#836]
Thank you for fugitive; it is fantastic.

I made a change to a file, then opened the fugitive status window, pressed C-n to move to the changed file, pressed U to discard it's changes, and in the command field I got this echo:

```
To restore, :Git cat-file blob fatal:  > main.cpp
```

That's two spaces after fatal:

Running that command does not restore the changes, but makes main.cpp an empty file.

**Comment by assembler** [comment]
I didn't have this issue until i recently updated the plugin and now there seems to be no `U` option at all. I really miss that one. Any chance of bringing it back?

**Comment by tpope** [comment]
@assembler do you ... not see the `Changed to X` error message when you press `U`?

@TamaHobbit I've redone that code so it's probably no longer an issue, but if it still happens let me know.

**Comment by odnoletkov** [comment]
This problem reproduces for me now

When I <kbd>X</kbd> unstaged file this hint is shown
> To restore, :Gedit .vimrc|Gread cf75d59

But when I run it the result is just empty buffer for the file.

https://github.com/tpope/vim-fugitive/commit/137433c3c058e0a70f45697ad515e3a881877f95 broke this for me – cat-file version works just fine

**Comment by tpope** [comment]
Yikes, good catch.  I replaced `cat-file` because `:Git` no longer supports shell syntax like redirects.
