### ISSUE TITLE
Feature request: add :Gshow

### ISSUE THREAD

**Issue by siadat** [tpope/vim-fugitive#837]
To run `git show` in Vim.

**Comment by tpope** [comment]
Which does what?

**Comment by siadat** [comment]
I'd like to see the changes made to the current file in the last commit. Similar to the output of `git show`. At the moment, I can do this using `:Gdiff HEAD~1`.

**Comment by qstrahl** [comment]
@siadat what's wrong with `:Gdiff HEAD~1` or `:Git! show` or `:command Gshow Gdiff HEAD~1`?

**Comment by qstrahl** [comment]
@siadat You might be interested in [these mappings](https://github.com/qstrahl/.vim/blob/9a5ef2ae0e93dc5a42a8f2893b6b33908996cd23/after/plugin/fugitive.vim#L9-L10) instead?

**Comment by siadat** [comment]
Thanks for suggesting `:Git! show`, it is cool! But I use vim-fugitive mainly for its great split view of the diffs.

For me, `:Gdiff HEAD~1` is good enough, but it would have been even better if I could see the other commits as well by their SHA1.

As an alternative, it would also be great if `:Gdiff` would allow a range, e.g. `:Gdiff <commit>...<commit>`. It doesn't seem to be possible at the moment.

**Comment by qstrahl** [comment]
> For me, `:Gdiff HEAD~1` is good enough, but it would have been even better if I could see the other commits as well by their SHA1.

You can. Try it.

> As an alternative, it would also be great if `:Gdiff` would allow a range

Try `:Git! diff HEAD~4..HEAD~1`

**Comment by siadat** [comment]
> Try :Git! diff HEAD~4..HEAD~1

Thanks, as I said I'm looking for split (vertical or horizontal) diff view.

**Comment by qstrahl** [comment]
> split (vertical or horizontal) diff view.

`:Gedit revision1`
`:Gdiff revision2`

**Comment by siadat** [comment]
:Gedit revision1
    :Gdiff revision2

Cool, thanks!

**Comment by bam80** [comment]
This command could be useful to show the changes for not only single file but for all the files from the commit (and show it with vimdiff facility).

**Comment by tpope** [comment]
So if 10 files are changed, it opens 20 windows?

**Comment by bam80** [comment]
No, I meant - open it all in one buffer.
That way the commit could be examined as single unit, combining the benefits of `got show` and `vimdiff`.

**Comment by tpope** [comment]
`vimdiff` requires at least 2 windows. I'm not sure what you're asking for.

**Comment by bam80** [comment]
Yes, I'm just asking a way to put in those 2 vimdiff windows changes from all the files commit changes.

**Comment by tpope** [comment]
Sounds like the worst of both worlds. You wouldn't even get syntax highlighting.

**Comment by bam80** [comment]
I think it's not a big problem - got show haven't it either.
But vimdiff facilities would be very useful.
