### ISSUE TITLE
Cannot stage file from status window on just one project

### ISSUE THREAD

**Issue by v0d1ch** [tpope/vim-fugitive#842]
If anybody has any idea what can cause this behavior please share. Fugitive is awesome and I use it in all of my projects but on this one when I view git status window the filetype is conf and I can't use '-' to stage/unstage file. We use git-flow btw but that should not be the cause of this.

**Comment by aschrab** [comment]
@vodich 
The filetype being would tend to indicate that there's a problem with detecting of that, either something in the status buffer makes it look like a conf file or you have a plugin that's being overly aggressive about setting the file type.

Try doing `:verbose set ft?` from within the status window in that condition. This should tell you where that is being set.

**Comment by vodich** [comment]
@aschrab Yes I get:
"Last set from /usr/local/Cellar/vim/8.0.0002/share/vim/vim80/filetype.vim"

**Comment by aschrab** [comment]
@vodich 
OK, so not a plugin. Can you post the content of one of these broken status buffers?

**Comment by vodich** [comment]
Sure here it is, don't know how to format it nicely:
# On branch develop
# Your branch is up-to-date with 'origin/develop'.
#
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   public/client/assets/modules/directives/search-box/searchBoxFactory.js
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	resources/views/front/index.blade.php
#	settings
#
no changes added to commit (use "git add" and/or "git commit -a")

**Comment by aschrab** [comment]
@vodich That would probably display better if you put a line with three backticks before and after that buffer content. Should still be able to edit it.

I'm not seeing anything that looks suspicious though.

**Comment by vodich** [comment]
Funny... it works for all the other projects. Thanks for the help, maybe someone comes up with the same issue

**Comment by vodich** [comment]
Maybe this can be of help - it keeps poping up every time I open file for the first time
```
Error detected while processing function <SNR>26_WildignoreFromGitignore:
line   14:
E518: Unknown option: Trash
```

**Comment by vodich** [comment]
Yup that was it. Somebody pasted a lot of stuff in the .gitignore and I this that if it not in the right format it screws up fugitive. All works well after I commented out all lines in .gitignore. This is how it looked like, loads of un-needed poorly formatted stuff
```
/.phpcomplete_extended
### General rules:
.env
.settings
.project
.buildpath

## Sass cache files:
**/*.scssc
**/.sass-cache/


### Dependency management
**/bower_components
**/node_modules

### Node shrinkwrap
npm-shrinkwrap

### PhpStorm
# Covers JetBrains IDEs: IntelliJ, RubyMine, PhpStorm, AppCode, PyCharm, CLion, Android Studio
*.iml

### Laravel
/vendor/*
!/vendor/phpdocx
Homestead.yaml
Homestead.json

#uploaded temp files
/storage/tmp


## Directory-based project format:
#.idea/
# if you remove the above rule, at least ignore the following:

# User-specific stuff:
.idea/workspace.xml
.idea/tasks.xml
.idea/dictionaries
.idea/blade.xml
.idea/deployment.xml
.idea/modules.xml

# Sensitive or high-churn files:
# .idea/dataSources.ids
# .idea/dataSources.xml
# .idea/sqlDataSources.xml
# .idea/dynamic.xml
# .idea/uiDesigner.xml

# Gradle:
# .idea/gradle.xml
# .idea/libraries

# Mongo Explorer plugin:
# .idea/mongoSettings.xml

## File-based project format:
*.ipr
*.iws

## Plugin-specific files:

# IntelliJ
/out/

# mpeltonen/sbt-idea plugin
.idea_modules/

# JIRA plugin
atlassian-ide-plugin.xml

# Crashlytics plugin (for Android Studio and IntelliJ)
com_crashlytics_export_strings.xml
crashlytics.properties
crashlytics-build.properties


### OSX ###
.DS_Store
.AppleDouble
.LSOverride

# Icon must end with two \r
Icon


# Thumbnails
._*

# Files that might appear in the root of a volume
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns

# Directories potentially created on remote AFP share
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk


/.idea/blade.xml
/.idea/encodings.xml
/.idea/misc.xml
/.idea/modules.xml
/.idea/vcs.xml
/.idea/.name
# log files
*.log
*.log.*
/.idea

#library folder
lib
!/vendor/phpdocx/lib
!/vendor/phpdocx/lib/*/lib

#build folder
build

#composer
*.lock

#PhpMyAdmin
phpmyadmin/*
phpmyadmin



#Translations on frontend
gettext.config.js

#laravel storage
storage/
!storage/docx
storage/docx/*
!storage/docx/.gitkeep
!storage/pdf
storage/pdf/*
!storage/pdf/tmp
storage/pdf/tmp/*
!storage/pdf/tmp/.gitkeep
storage/xls
!storage/xls/*

#generated translation template
public/client/i18n/template.pot
```

**Comment by dhruvasagar** [comment]
You should close this issue if fixed.
