### ISSUE TITLE
Cannot sign commits when GPG key requires a password

### ISSUE THREAD

**Issue by eligundry** [tpope/vim-fugitive#846]
I recently added this line to my global git config:

```
[commit]
    gpgsign = true
```

This will cause all my commits to be signed by my GPG key. This works perfectly on OSX once the key has been unlocked for the session. The issue I am now running into is that I cannot sign on my Linux box because it requires me to enter my GPG password for each commit. When I go to save my commit in fugitive, the window will shift upwards with a prompt for me to enter my password. I can enter my password but pressing enter, `<Ctrl-C>`, `<Ctrl-D>`, or `<Ctrl-Z>` will do nothing and I need to kill my tmux window and commit from the shell.
### Environment
- Neovim 0.1.5
- Tmux 2.2
- Xfce4 terminal

**Comment by justinmk** [comment]
@eligundry This is because `:!` in Nvim uses pipes, not a tty, so interactive processes don't work. Fugitive might be able to work around this by using `:terminal` instead of `:!`, but I haven't looked closely at it.

Note that `:!` in non-terminal Vim will have a similar problem on some platforms:

https://github.com/tpope/vim-fugitive/issues/556#issuecomment-57834511

FWIW `:terminal` in Nvim works on all platforms/GUIs. (Consistent behavior of `:!` and `:terminal` across platforms is a goal and a tradeoff.)

**Comment by tpope** [comment]
My recommendation is to get `gpg-agent` working. Even setting aside fugitive.vim, you'll be glad you did.

**Comment by qrevel** [comment]
@tpope what do you mean by having a `gpg-agent` working?
I actualy have `gpg-agent` running with a `default-cache-ttl` and `max-cache-ttl` of 3600.
It means every hour, I need to run a command in a separate terminal to cache the passphrase again instead of directly putting the password in nvim. Do you have any solution (expect increasing ttls) to improve my workflow?

**Comment by tpope** [comment]
The solution, as I understand it, is to set `pinentry-program` to a GUI tool in `gpg-agent.conf`. I don't think there's a good way to inject a `:terminal` into the process, so this will have to do.

**Comment by davelens** [comment]
For anyone who, like me, finds this thread in a search to get (n)vim + tmux to behave when entering GPG passphrases in the `pinentry` tool, you can read up on configuring your `gpg-agent` [here](https://gist.github.com/troyfontaine/18c9146295168ee9ca2b30c00bd1b41e).

I'm on macos, so what I did is install gpg with Homebrew. It will come with `/usr/local/bin/pinentry-mac`, which you can configure as the value of `pinentry-program` in `~/.gnupg/gpg-agent-conf`. I'm using this specific configuration to have it ask my passphrase and remember it for the next 8 hours:

```
default-cache-ttl 28800
max-cache-ttl 28800
pinentry-program /usr/local/bin/pinentry-mac
```

**Comment by strottie** [comment]
This is assuming that you have GUI environment available.
If you're SSH'd to a remote machine with no X forwarding (e.g., for security reasons) or running a terminal multiplexer (e.g., tmux, screen, or Zellij) on that remote machine, then there's no choice but to use a TTY-based pinentry as fallback.

Please consider alternative solutions.

**Comment by strottie** [comment]
Thanks Tim,

Unfortunately, neither option works for my case:
1. Yes, gpg-agent can work over SSH with X forwarding. But X forwarding is not always possible (or desirable). In my case, ssh + mosh + tmux makes it impossible to use X forwarding. But even if I used straight ssh, I still would not enable X forwarding when logging in to a "foreign" computer or one I don't have 100% control of the security.
2. loopback: Unfortunately, enabling loopback mode is also insecure.

I just noticed that with NVIM 0.10.2 I can get vim-gnupg working just fine with pinentry-curses.
(ssh + mosh + tmux, target system is RedHat Enterprise 8.9, no DISPLAY, GPG_TTY=`tty`, not loopback mode)

vim-gnupg uses `:execute` and `&shellredir`. It ends up wrapped like this:
```
nvim,32233 test.gpg
  └─nvim,32234 --embed test.gpg
      └─sh,32417 -c (gpg --trust-model always --use-agent --quiet --decrypt '/users/strottie/.config/nvim/test.gpg' 2>/dev/null) >/tmp/nvim.strottie/1YhQ7Y/0 2>&1
          └─gpg,32420 --trust-model always --use-agent --quiet --decrypt /users/strottie/.config/nvim/test.gpg
```

With Fugitive, running `:G commit` does the following: (The main difference being the lack of shell wrapping)
```
nvim,7040 --embed
  ├─git,7736 -c color.advice=false -c color.branch=false -c color.diff=false -c color.grep=false ...
  │   └─gpg,8604 /users/strottie/bin/gpg --status-fd=2 -bsau CF0AB12B1EB80D4F538AF01E145352C8F31E11C4
```

Perhaps nvim leaves the terminal alone while running a redirected shell command?

I also posted my surprise that it worked in vim-gnupg on their issue tracking nvim support. I'll revert back if there's anything interesting on that side.

Cheers

**Comment by tpope** [comment]
> Unfortunately, neither option works for my case:
> 
> 1. Yes, gpg-agent can work over SSH with X forwarding. But X forwarding is not always possible (or desirable). In my case, ssh + mosh + tmux makes it impossible to use X forwarding. But even if I used straight ssh, I still would not enable X forwarding when logging in to a "foreign" computer or one I don't have 100% control of the security.

I don't mean X forwarding, I mean something akin to SSH agent forwarding but for GPG.

> 3. loopback: Unfortunately, enabling loopback mode is also insecure.

I'm sure that's true in many contexts, but it's not clear to me why it would be in this case.

> I just noticed that with NVIM 0.10.2 I can get vim-gnupg working just fine with pinentry-curses. (ssh + mosh + tmux, target system is RedHat Enterprise 8.9, no DISPLAY, GPG_TTY=`tty`, not loopback mode)
> 
> vim-gnupg uses `:execute` and `&shellredir`.

You missed something, `:execute` has nothing to do with executing a process.

**Comment by strottie** [comment]
> I don't mean X forwarding, I mean something akin to SSH agent forwarding but for GPG.

Yes, gpg-agent is actually the one that can double as gpg+ssh agent.
So, if you have SSH and do ssh+gpg agent forwarding, you can use a graphical pinentry and, in some cases, a tty pintentry.

But if you don't actually have SSH at all, you're out of luck. Specifically with mosh, the initial connection is based on ssh which is used to spawn a mosh-server on the target system. The ssh connection is dropped and then mosh sets up an encrypted and resilient connection over UDP to that mosh-server instance. In lossy environments, it's a life saver -- but no X and no agent forwarding of any kind is possible.

> I'm sure that's true in many contexts, but it's not clear to me why it would be in this case.

To use `--pinentry-mode loopback`, you need to enable it "globally" in your gpg-agent.conf (`allow-loopback-entry`) which means that a bad actor could bypass your pinentry of choice by using loopback mode and faking the real pinentry and thus intercept your passphrase. The whole point of pinentry is to make damn sure that your passphrase is being kept secret. With loopback mode, the application (`gpg` in this case) is receiving the passphrase directly and any process with sufficient privileges can also read its memory and extract the information. With proper pinentry, a bunch of security measures are in place and the attack surface is diminished. Mind you, 99.99% of the population don't know or don't care.

> You missed something, :execute has nothing to do with executing a process.

Indeed, my bad. It actually uses `:read ++edit !<gpg command here>`:
```
let cmd = { 'level': 1, 'ex': silent . 'read ++edit !' }
let cmd.args = '--quiet --decrypt ' . s:shellescape(filename, { 'special': 1, 'cygpath': 1 })
call s:GPGExecute(cmd)
```
where the `s:GPGExecute` adds the gpg command and args after the "!" and then runs `:execute` on the result.

**Comment by tpope** [comment]
> `:terminal wrapper-that-sets-GPG_TTY git commit ...`?
> With a POSIX `&shell`, `:terminal GPG_TTY=`tty` git commit ...` seems to WFM.

With all the constraints you've imposed ("it won't work over a UDP ssh alternative" is truly incredible), I think this is the only option. It's a terrible interface though, you end up running Vim inside of Vim, and when I tried it just now everything blew up because it inherited mismatched environment variables like `VIMRUNTIME`.

But you can force Fugitive to do that with by setting a custom `pager.commit` (since the purpose of a custom per-command pager is typically to do fancy things with the terminal):

```vim
:Git -c pager.commit=cat commit
```

You can also set it in your `.gitconfig`, which I imagine wouldn't hurt anything since that command doesn't have much use for a pager.
