### ISSUE TITLE
Support skywind3000/asyncrun.vim as replacement for tpope/vim-dispatch

### ISSUE THREAD

**Issue by mcepl** [tpope/vim-fugitive#847]
https://github.com/skywind3000/asyncrun.vim should be a replacement for `tpope/vim-dispatch` using async capabilities in vim8. The only usage of `vim-dispatch` I can find for me is in this function in `vim-fugitive`:

``` vim
function! s:Dispatch(bang, args)
  let cd = exists('*haslocaldir') && haslocaldir() ? 'lcd' : 'cd'
  let cwd = getcwd()
  let [mp, efm, cc] = [&l:mp, &l:efm, get(b:, 'current_compiler', '')]
  try
    let b:current_compiler = 'git'
    let &l:errorformat = s:common_efm
    let &l:makeprg = g:fugitive_git_executable . ' ' . a:args
    execute cd fnameescape(s:repo().tree())
    if exists(':Make') == 2
      noautocmd Make
    else
      silent noautocmd make!
      redraw!
      return 'call fugitive#cwindow()'
    endif
    return ''
  finally
    let [&l:mp, &l:efm, b:current_compiler] = [mp, efm, cc]
    if empty(cc) | unlet! b:current_compiler | endif
    execute cd fnameescape(cwd)
  endtry
endfunction
```

I guess just adding another branch to that `if` statement should be enough?

**Comment by tpope** [comment]
Don't think of it as supporting dispatch.vim. Think of it as supporting any plugin that provides a `:Make` command. This is why I picked a generic command name. Much simpler for new async runners to provide a `:Make` command than for me to update half a dozen plugins.

**Comment by mcepl** [comment]
Of course, another option would be to make ``vim-dispatch`` use native asynchronous capabilities of vim8 as well and make ``asyncrun`` redundant. ;)

**Comment by tpope** [comment]
That would be great, though I'm pretty content with my setup so it hasn't been a high priority for me.

**Comment by tpope** [comment]
Dispatch does use jobs now, fwiw.
