### ISSUE TITLE
Gstatus <cr> binding breaks when using a certain autocmd

### ISSUE THREAD

**Issue by anilanar** [tpope/vim-fugitive#848]
I have the following autocmd in my `.vimrc`:

```
au BufEnter,BufNew * if &diff | syntax off | else | syntax on | endif
```

Gdiff colors, my syntax coloring and my terminal colors don't fit together (seriously, I have no idea why diff background highlighting uses the same color as diff foreground, or how colors work in general).

This autocmd breaks `Gstatus`, when I hit `<Return>` key on a file, it edits the file in the preview window (i.e. status window) which is very inconvenient. 

Any idea why? Or any workaround you suggest?

Here is a screenshot displaying why I want to turn syntax off when diffing:

<img width="383" alt="screen shot 2016-10-16 at 14 24 33" src="https://cloud.githubusercontent.com/assets/753736/19417408/5ef054d4-93ac-11e6-91c7-c7c0ce079571.png">

When syntax is off:

<img width="372" alt="screen shot 2016-10-16 at 14 26 53" src="https://cloud.githubusercontent.com/assets/753736/19417413/a5679300-93ac-11e6-9d61-8514f5632156.png">

**Comment by tpope** [comment]
You will probably have better luck disabling syntax for the buffer in question (`set syntax=`) rather than globally.

**Comment by anilanar** [comment]
Hey Tim, I found a way to change `DiffText` color, which did a better job than setting syntax off:

```
highlight! link DiffText MatchParen
```

Cheers!
