### ISSUE TITLE
Feature request: Gbrowse blame

### ISSUE THREAD

**Issue by alextrastero** [tpope/vim-fugitive#849]
First of all: bow. Great project!

Secondly, I'm not sure if someone already asked for this/duplicate dunno.
I use `:Gbrowse` quite often. I was wondering if there was a flag to Gbrowse directly on blame view, it would be so useful to open current line in github's blame page, ie;
https://github.com/tpope/vim-fugitive/blame/master/plugin/fugitive.vim#L47

**Comment by mcepl** [comment]
I guess #491 ?

**Comment by tpope** [comment]
#1171 now.
