### ISSUE TITLE
Git worktree and fugitive issues

### ISSUE THREAD

**Issue by smani** [tpope/vim-fugitive#851]
**Steps to reproduce:**
1. mkdir temp
2. cd temp/
3. git clone git://github.com/tpope/vim-fugitive.git
4. cd vim-fugitive/
5. git branch wt remotes/origin/worktree
6. git worktree add ../wt wt
7. cd ..
8. cd wt
9. vim plugin/fugitive.vim
10. `:Gstatus`
    - `Error detected while processing function <SNR>18_BufReadIndex:`
    - `line   30:`
    - `E344: Can't find directory "C:/temp/wt/" in cdpath`
    - `E472: Command failed`
11. `:Gblame`
    - `fugitive: file or blob required`

**My setup:**

`Vim:`
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  9 2016 08:08:03)
Included patches: 1-1721

`vim-fugitive:`
 58ed86e434951319ff7d438fb1096f24a51e6458

`Git:`
git version 2.10.0.windows.1

**Comment by smani** [comment]
It doesn't seem to happen on Linux. I see this only on Windows. I use the `vim` within `Git Bash` (MINGW64) terminal.

**Comment by tpope** [comment]
Closed per discussion in #855.
