### ISSUE TITLE
showing errors when I push or pull

### ISSUE THREAD

**Issue by sfahlberg** [tpope/vim-fugitive#852]
thanks for your contributions to this project!

sometimes when pushing and pulling in vim, I get an error. I also have problems with git hooks that prevent me from committing if I have certain errors. How can I get the output into vim so I don't have to leave vim to find out what my errors were? thanks!

**Comment by rockydd** [comment]
@sfahlberg have you tried :redir ?

**Comment by sfahlberg** [comment]
excellent! thanks!
