### ISSUE TITLE
Jump to changed file from diff

### ISSUE THREAD

**Issue by zsorizs** [tpope/vim-fugitive#856]
In my workflow I have the point when I review my changes either by issuing :Git! diff or using dp from Gstatus.

When I find an issue in the diff that I think I need to change I would want to go to the code in question. Both <CR> and gf take me to the HEAD version and not the working copy, so I cannot edit it immediately.

Not sure if there is a way to get to the working copy. It would be nice to have a shortcut that brings me to the file in the working copy.

One other issue I have regarding this is that I tried to use :Gedit to get from the HEAD version to the working copy. Of course, it works, but the cursor position is changed to the start of the file. It would be very nice if :Gedit would keep the cursor position (at least if staying in the same file). This would be also useful for some other use scenarios.

**Comment by tidbeck** [comment]
Can't you just do a normal diff, **D**, form Gstatus on the same file?

**Comment by tpope** [comment]
The problem is nothing in the diff actually tells us the correct destination. I'm pushing a change that adds some smarter heuristics if `diff.mnemonicPrefix` is set. That should be adequate for your use case.

I'm confused about your "shortcut" request, as you seem to be aware of `:Gedit`. Blindly preserving the line number would be doable but I'm not sure how one might intelligently preserve the cursor position with respect to changes.

**Comment by srcrip** [comment]
I’d be interested in this same workflow, any thoughts on this @tpope? I really want to be able to perserve the line number better.

**Comment by srcrip** [comment]
to specify this would be a great improvement and seems like it should be pretty doable:

```
running :Gedit from the commit actually opens a file browser for the current working directory, but would ideally have the same effect as pressing enter (to go to same line in an historical version), then running :Gedit
```

```
running :Gedit from an historical version of the file jumps to the same line number; ideally it should jump to the same line (as reported by git blame)
```

this would be amazing but I'm not sure if it can be done or not.

**Comment by srcrip** [comment]
actually I've noticed that *sometimes* the line does take you to the proper file but sometimes not, I'm not sure why.

**Comment by tpope** [comment]
> * running `:Gedit` from an historical version of the file jumps to the same line _number_; ideally it should jump to the same _line_ (as reported by `git blame`)

This isn't true. It should jump to the same line, not the same line number, barring some edge cases (e.g., around renamed files).
