### ISSUE TITLE
After :Gblame, when viewing the commit, please also include the commit hash

### ISSUE THREAD

**Issue by chrisbra** [tpope/vim-fugitive#857]
Currently, after pressing o in the `:Gblame'd` window, `o` opens the commit, with additional information as tree and parent hash. However I feel I miss the commit hash or tag, if it exists.

Thanks for considering.

**Comment by justinmk** [comment]
You can use `{register}y<C-G>` to yank the current object id. `<C-R><C-G>` also works at the cmdline.

**Comment by chrisbra** [comment]
Ah, I see. That is useful. However sometimes it is useful to have the name visible.

**Comment by 0x62ash** [comment]
For me `tree` and `parents` is always confusing, because what Im usually want in first lines of diff is commit hash

**Comment by tpope** [comment]
Let's just say I understand where you are coming from, but I have an irrational love for the way we exactly mirror the internal structure of a Git object. The commit hash is also visible in the status line, which in my book is (just barely) an acceptable alternative.

**Comment by tpope** [comment]
No longer opposed to this if someone wants to send a PR.

**Comment by chrisbra** [comment]
see #939

**Comment by tpope** [comment]
Not sure why I never merged (perhaps I didn't have the energy to point out "Gblame'd detail window" is a bad description?), but I have decided that commit buffers are going to be completely redone to use the `fugitive` file type, and I don't think I want to risk bikeshedding the old format in the meantime. (Although if you're desperate, ask again after 3.0.)

Note that in addition to `y<C-G>`, you can also use `!` as an argument to any `:G` command to pass in the current commit. For example, `:Gcommit --fixup=!`. So I would hope the actual need for this is pretty small (though I do currently plan to include it in the redo).

**Comment by ilor** [comment]
Hi! As a friendly ping, any updates on this? I have to admit I much prefer having the commit hash plainly visible like #939 tried to add.

**Comment by tpope** [comment]
It's still going to be done, but it has slid in priority below all the job stuff, because the rewrite is going to require calling out to Git multiple times, and jobs eliminate a ton of performance overhead there especially on Windows.

**Comment by ilor** [comment]
Thanks for the reply, good luck then.

**Comment by ilor** [comment]
Could we keep this open though, since it is after 3.0 and I want this enough to consider staying on the pull request branch for a while. My use case is interacting with various places where I need to paste a git sha to, through various terminals and ssh that make me prefer to just see the data on screen.
