### ISSUE TITLE
How can I test if fugitive is loaded?

### ISSUE THREAD

**Issue by dave-kennedy** [tpope/vim-fugitive#864]
I want to add `fugitive#statusline` to my status line if it's loaded, but I can't figure out how to detect that. I tried the following:

`if exists("fugitive#statusline")`
`if exists("fugitive#statusline()")`
`if exists(":fugitive#statusline")`
`if exists(":fugitive#statusline()")`
`if exists("fugitive#")`
`if exists("fugitive")`

What do I need here?

**Comment by qstrahl** [comment]
`if get(g:, 'loaded_fugitive')`

**Comment by qstrahl** [comment]
Could also go for `if exists('*fugitive#statusline')` to be more precise to your use case
