### ISSUE TITLE
Discard all local changes with confirmation

### ISSUE THREAD

**Issue by anhari** [tpope/vim-fugitive#865]
What do you think of adding a command that does the equivalent of `git add .; git stash; git stash drop` with a confirmation?

**Comment by tidbeck** [comment]
Does this have the same effect as `git reset --hard HEAD`?

**Comment by anhari** [comment]
It will also discard unstaged changes as opposed to `git reset --hard HEAD`, which will only discard staged changes.

**Comment by tidbeck** [comment]
I see. Could you create an alias so that you can run `:Git myalias`?

**Comment by nmschulte** [comment]
Also, `git reset --hard HEAD; git clean -df`.

**Comment by anhari** [comment]
Yeah I think that will do just fine. I'm not sure that this will be used enough to warrant inclusion into the plugin. I'm going to go ahead and close this issue.
