### ISSUE TITLE
Gdiff to a revision without this file

### ISSUE THREAD

**Issue by somini** [tpope/vim-fugitive#866]
If you run `Gdiff $revision` and that revision doesn't have that file (it was created afterwards), there's an error and Fugitive gets confused. If you repeat the command, the split gets opened with an empty file, and when you close that all returns to normal. Here's a test case.

- Open `$REDACTED_FILENAME` that doesn't exist yet on commit e51d2e933cf35a2d06174c6f667a345732e167b1.

```
Gdiff e51d2e933cf35a2d06174c6f667a345732e167b1
```

```
Error detected while processing BufReadCmd Auto commands for "fugitive://**//[0-9a-f][0-9a-f]*":
fugitive: rev-parse e51d2e933cf35a2d06174c6f667a345732e167b1:$REDACTED_FILENAME: fatal: Needed a single revision 
```

**Comment by blueyed** [comment]
It depends on if you have `set hidden` (which most people will have): with `hidden` `:ls!` lists the fugitive buffer with `x` ("a buffer with read errors"), and when you issue the command again it appears to get used.
With `:set nohidden` however, you will get the same error again.

Related: #607

**Comment by somini** [comment]
I can confirm `96adffd` solves this by diffing with an empty file.
