### ISSUE TITLE
:Gpush pushes but doesn't exit cleanly with Neovim

### ISSUE THREAD

**Issue by jc00ke** [tpope/vim-fugitive#867]
As always, thanks for your tireless work!

I'm not sure if the regression is in Neovim or fugitive but this used to work without errors.

I'd `:Gpush -u` which runs [Credo](https://github.com/rrrene/credo) in a `pre-push` hook, then kicks the code up. When that completes I get the following error:

![0_selection_001](https://cloud.githubusercontent.com/assets/18191/22003364/deaf8516-dc07-11e6-9377-2b897aeeadbc.png)

I'm on Neovim `0.1.7ubuntu1+git201701151345+3058+23~ubuntu16.10.1` (maybe I should get off the unstable release?) and b754bc2 using Plug to manage my plugins.

**Comment by justinmk** [comment]
`s:UsesTerminal` is not part of fugitive, so it must be some other plugin. The problem is likely a missing `dict` marker on the `JobExit` function.

https://github.com/neovim/neovim/wiki/Following-HEAD#20161212

This change was required for Vim compatibility.

**Comment by jc00ke** [comment]
@justinmk you're right, and when I add `dict` to [this line in vim-dispatch-neovim](https://github.com/radenling/vim-dispatch-neovim/blob/85deb470b53ab796e6201b3345de588f1d648555/autoload/dispatch/neovim.vim#L148) I don't see the error. I'll move this over there.

Thanks!

**Comment by jc00ke** [comment]
radenling/vim-dispatch-neovim#10
