### ISSUE TITLE
Provide a history of :Ggrep search results?

### ISSUE THREAD

**Issue by kostix** [tpope/vim-fugitive#868]
While I very much enjoy using `:Ggrep`, when digging up large codebases which actively work against using IDEs (or `ctags` in Vim or whaveter)¹, I often find myself repeating the following pattern:

1. I `:Ggrep` for some function; explore where and how it's called.
1. I then `:Ggrep` for some other function from the context of the calls explored above.
1. I would then like to go back to the results of the previous `:Ggrep` calls (and sometimes even beyond in the history of searches).

Would it be possible to somehow implement a list of the results of the last `N` searches and a pair of commands to move back and forth between them?

----

¹ One glaring example is PHP projects using the Magento webstore engine: Magento likes to use "magic" functions on some of its objects which are not defined anywhere but their names are actually "interpreted" at the call time to mean accessing to some persisted state etc. Like you call `$session->getMyStuff()` and it's interpreted as the request to locate the "model" named "my_stuff" in a session proxied by the object `$session` and load data from it.

**Comment by justinmk** [comment]
`:colder`

**Comment by kostix** [comment]
Silly me; thank you very much, @justinmk!

`:colder` and `:cnewer` is what I longed for!
