### ISSUE TITLE
GBlame: syntax highlighting don't work

### ISSUE THREAD

**Issue by maln0ir** [tpope/vim-fugitive#869]
Syntax highlighting in blame window doesn't work.

[Screenshot](https://i.imgur.com/uSLHfRw.png)

Steps to reproduce:

    mkdir ~/.vim/pack/bundle/start
    git clone git://github.com/tpope/vim-fugitive.git ~/.vim/pack/bundle/start/fugitive
    echo "packloadall" > ~/.vimrc
    echo "syntax on" >> ~/.vimrc

Then open any file inside git repository and run `:GBlame`.

OS details:
- Arch Linux 
- Vim: 8.0.237
- Fugitive: commit b754bc2031f21a532c083dd0d072ba373bbe3a37

**Comment by justinmk** [comment]
You forgot `:filetype plugin on`

**Comment by maln0ir** [comment]
That's right, but result is the same.

**Comment by justinmk** [comment]
I think the one-man tech support for fugitive has exhausted: https://github.com/tpope/vim-fugitive/issues

Best thing would be to figure out the issue and propose a fix.

**Comment by maln0ir** [comment]
It looks like using Pathogen instead of build-in package manager solves the problem.

For some reason, `syntax` commands in `s:BlameSyntax()` function are not executed, when fugitive is loaded by build-in package manager, because `:syntax` command in blame window returns `No Syntax items defined for this buffer`.

Replacing `packloadall` command with lines below (assuming Pathogen is placed in `$HOME/.vim/pack/bundle/opt/pathogen`) fixes the problem.

    source $HOME/.vim/pack/bundle/opt/pathogen/autoload/pathogen.vim
    execute pathogen#infect('pack/bundle/start/{}')

**Comment by justinmk** [comment]
@maln0ir Might want to report that to https://github.com/vim/vim to get feedback.

**Comment by bewuethr** [comment]
I had the exact same problem, even when using Pathogen for package management, but it looks like commit 5d11ff7 has fixed the problem for me.
