### ISSUE TITLE
Feature Request: Gbrowse on non-github repos using manual configuration.

### ISSUE THREAD

**Issue by MobiusHorizons** [tpope/vim-fugitive#870]
First let me say, thanks so much for this extremely useful plugin. I use it daily, and appreciate it very much. 

For github based projects I love the ability to use `Gbrowse` from visual mode to quickly show lines of code to coworkers. I would very much appreciate the ability to use this feature against Bitbucket and Stash (self hosted Bitbucket) repositories. 

My proposed solution would be to read a configuration item from the git config to set the http viewable browsing url.  For example 

```
[remote "origin"]
    url = git@github.com:tpope/vim-fugitive.git
    fetch = +refs/heads/*:refs/remotes/origin/*
    browse = https://github.com/tpope/vim-fugitive/blob/$REF$/$PATH$
```

here `browse` serves as a template for creating a browsable url for any given path in the repository.

for Bitbucket the url would look more like `.../browse/$PATH$?at=$REF$`

Additionally the format for selecting lines would need to be a configuration option since Github uses `#LX-LY` and Bitbucket uses `#X-Y`. For these two cases, a simple prefix could be set up, however I do not know about other git source browsing implementations.

Would you be interested in including such an option in fugitive.vim?

--Thanks

**Comment by justinmk** [comment]
This was made extensible, see https://github.com/tpope/vim-rhubarb. Though I don't know where the list of implementations is, would be good for that to be in fugitive's readme.

**Comment by MobiusHorizons** [comment]
Cool, that looks promising.

**Comment by shumphrey** [comment]
Another example is https://github.com/shumphrey/fugitive-gitlab.vim for gitlab support

**Comment by MobiusHorizons** [comment]
thanks. I guess I'll close this if that feature is going away, and third party plugins are the answer

**Comment by nmschulte** [comment]
I'm interested in a Stash (BitBucket) adaptation for this extension point.  Quick searching turned up squat.  Thumbup to show interest for this.

**Comment by MobiusHorizons** [comment]
So I ended up adapting shumphrey's plugin for use with the stash environment I use at work. It seems to work, but I haven't tested it rigorously. https://github.com/mobiushorizons/fugitive-stash.vim if anyone is interested.

**Comment by MobiusHorizons** [comment]
@justinmk, It seems there should probably be some sort of list of extensions of this type as you say. Should that be a wiki? Readme?

**Comment by tpope** [comment]
I like wiki for starters.

**Comment by nmschulte** [comment]
I found this: https://en.wikipedia.org/wiki/User:Riceissa/fugitive.vim

@tpope
https://guides.github.com/features/wikis/#creating-your-wiki -- #879
