### ISSUE TITLE
Over-matching fugitive buffer breaks path for some buffers

### ISSUE THREAD

**Issue by natebosch** [tpope/vim-fugitive#871]
The pattern match for fugitive buffers is against '//' which can match some (possibly mistaken but still valid) file paths. This causes a change to `&path` when it isn't expected.

Match was introduced https://github.com/tpope/vim-fugitive/commit/063d1fcaa980207e44f2bcbe1bccf895daf2b3af

Currently it's at https://github.com/tpope/vim-fugitive/blob/b754bc2031f21a532c083dd0d072ba373bbe3a37/plugin/fugitive.vim#L198

I think changing it to `fugitive://` should work

**Comment by tpope** [comment]
Can you send a pull request that makes it `://` instead? While I don't think it should ever happen in practice, we'd still need the guard if it was called on, say, a `http://` buffer.

**Comment by natebosch** [comment]
Makes sense. Updated https://github.com/tpope/vim-fugitive/pull/872
