### ISSUE TITLE
Accept ':Gdiff master...'

### ISSUE THREAD

**Issue by teto** [tpope/vim-fugitive#876]
First of all, thanks for the fantastic plugin !

While `:Gdiff master` works perfectly, `:Gdiff master...` (master... is supposed to give you the commit at where your current branch forked from master) returs some junk, like it opens a new window but with some random commit, with its log and all files instead of the current file only.

**Comment by tpope** [comment]
I think the best way to implement this would probably be to add an extra `elseif` to  [this conditional](https://github.com/tpope/vim-fugitive/blob/785bb15745f0cf41b9163b364d2d809756adb912/plugin/fugitive.vim#L1807-L1821) and call `s:repo().git_chomp('merge-base',...)` in it.

**Comment by tpope** [comment]
Further discussion in #913.
