### ISSUE TITLE
Support :tab Gstatus

### ISSUE THREAD

**Issue by mgedmin** [tpope/vim-fugitive#880]
It would be nice if `:tab Gstatus` would open the status window in a new tab.

This could be implemented by using `<mods>` in the command mapping, if the Vim version is sufficiently recent (>= 7.4.1898).

**Comment by tpope** [comment]
I haven't really looked at `<mods>` before. Sounds awesome if it can be done in a backwards compatible way.

**Comment by tandrewnichols** [comment]
As long as you're doing that . . . vsplit too?

**Comment by tpope** [comment]
Supported.
