### ISSUE TITLE
"fugitive: file or blob required" when :Gblame in symlinked repo

### ISSUE THREAD

**Issue by stephentalley** [tpope/vim-fugitive#882]
I have two repos with the same root dir:

    ~/.git-homedir-private/
    ~/.git-homedir-public/
    ~/.git -> .git-homedir-public

~/.git is a symlink that is currently pointing to .git-homedir-public.

When I edit a file managed by the homedir-public repo, say ~/.vim/mappings.vim, and run :GBlame, I get a "fugitive: file or blob required" error.

All command-line git utilities work fine with ~/.git as a symlink.  If I "rm ~/.git" and "mv ~/.git-homedir-public/ ~/.git", :GBlame works as expected.

I see from fugitive#extract_git_dir(), fugitive does try to work when ~/.git is a symlink, or did at some point, but it currently does not.

This looks like a breakdown in buffer_path(), though my vimscript-fu is not strong enough to see where.

**Comment by tpope** [comment]
You can probably fix it with `core.worktree`, or feel free to propose another solution.
