### ISSUE TITLE
Gstatus is not showing status, instead shows file permissions and hashes

### ISSUE THREAD

**Issue by durgaswaroop** [tpope/vim-fugitive#883]
Gstatus used to work fine for me and then suddenly yesterday when I do `:Gstatus`, I get this output, 
```
100644 9b3173e2886982a3a070d57afdf6de0e7c3608af 0	.gitignore
100644 fc5d1bfd19cb78464f70ce5aba3f9454bf0b65dd 0	README.md
100644 38385902be6ee6f390f388ddbe83e283c454ce2e 0	build.gradle
```
So, instead of showing the file statuses, it is showing file permissions and hashes. Any idea why this is happening?

**Comment by tpope** [comment]
This is an alternate "raw index" view that can be toggled on and off with `i` or `a`.
