### ISSUE TITLE
does vim-fugitive do anything special with ctags? 

### ISSUE THREAD

**Issue by stites** [tpope/vim-fugitive#884]
While this hasn't been an issue in the past, I recently have been having problems finding my ctags file. When I uninstall vim-fugitive, however, this capability is restored.

Thanks

**Comment by tpope** [comment]
There is [this](https://github.com/tpope/vim-fugitive/blob/87c1bda4d5573185a1f79c42a919c4b62bc34c42/plugin/fugitive.vim#L201-L208), but it should only fire if you actually have a `tags` file in `.git`, and even then, it should only add, not remove anything.

**Comment by stites** [comment]
Thanks, @tpope! I'll close this ticket.
