### ISSUE TITLE
Return commit details

### ISSUE THREAD

**Issue by asilvadesigns** [tpope/vim-fugitive#885]
Is there a method that returns details about the numbers of changes added, removed, changed for the current branch, similar to how fugitive#head() return the current branch? The purpose would be to show the changes in the statusline.

**Comment by nmschulte** [comment]
There are some unstated assumptions here:
1) that there exists some other branch that these changes are based against; typically this is done by (remote) tracking branches.
2) that everyone agrees on what a change is

Your question indicates that we need more help with this.  A change can be an entire line, and a change can be an addition, or a removal.  It's not clear if substitutions should count as changes, but I think there's a safe default about this too; maybe even signalled by the repository config, or Vim's configuration.

**Comment by tpope** [comment]
Correctly, there's many ways to interpret this question, but the answer to all of them is no.
