### ISSUE TITLE
How to do the first step for reporting an issue

### ISSUE THREAD

**Issue by SureshGovindachar** [tpope/vim-fugitive#886]
Regarding:  

> Before reporting a bug, you should try stripping down your Vim configuration and removing other plugins ...

I tried:

    cd vim-fugitive-master
    gvim -u NONE -U NONE

followed by `:source ./plugin/fugitive.vim`.  I then opened a file under git control, and tried `:Gstatus` but that command did not work.

The same steps but with gvim being started without the -u and -U arguments results in fugitive working almost as expected -- there is some issue but I am unable to report the issue because of not knowing how to do the first step for reporting an issue.

So how does one "Before reporting a bug, you should try stripping down your Vim configuration and removing other plugins ..." ?

**Comment by tpope** [comment]
There are many ways, but if you want to go the `-u NONE` route you also need `-N`, to disable `'compatible'`.
