### ISSUE TITLE
Support for GitHub's `hub` commands

### ISSUE THREAD

**Issue by Coaxial** [tpope/vim-fugitive#891]
I love the plugin!

I use Github's [`hub` command](https://github.com/github/hub) which adds extra commands to git (and is aliased to `git` in my environment).

Although fugitive works with git aliases, it won't use `hub` as `git`. Therefore, `:Git pull-request` won't work.

**Comment by tpope** [comment]
`let g:fugitive_git_executable = 'hub'`. This used to be the default in [rhubarb.vim](/tpope/vim-rubarb) but I [had to axe it](https://github.com/tpope/vim-rhubarb/issues/9).
