### ISSUE TITLE
Gblame only with Name and Date?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [tpope/vim-fugitive#892]
Is it possible to customize the output format of the Gblame? This is not mentioned in documentation.

**Comment by tpope** [comment]
No, `git blame` doesn't provide for that.

**Comment by nmschulte** [comment]
@tpope, I've never written a Vim plugin before, and fugitive is like magic to me (truly; thanks!), but does not the `--porcelain` option for `git-blame` provide for this?  There is a `--porcelain-line` option, too.

I ask only because `:Gstatus` is so magical, it _must_ be doing some kind of transformation on the output of `git status` and friends.

The critical bit, I suppose, is that `git-blame` (and `git-annotate`) claims to:
> Annotates each line ...

**Comment by tpope** [comment]
Take a look at that output and tell me your honest feelings on implementing a VimL parser for it. Especially when the end goal is hiding 7 columns of commit id.

**Comment by tpope** [comment]
BTW `:Gstatus` is raw `git status` output. All the magic that happens in that buffer is from parsing it.

**Comment by nmschulte** [comment]
First, I misinterpreted the OP's request; I missed the bit about removing the commit's columns, as I was more interested in removing the source-line's columns.

But, `git-blame` allows to specify the formatting of the commit ids (though I doubt you can elide them entirely this way), and it also allows specifying the formatting of the dates, via the system's `strftime`, which if I understand correctly will allow inserting a custom sentinel value into before or after the date (thus, after the name-columns, and/or before the source-line columns).

Again, I have no vimscript experience, but I imagine that knowing the column numbers absolutely makes the VimL jamming a bit more trivial than writing a lexer/parser.

**Comment by tpope** [comment]
Source column is implicitly hidden by the window size. You can hide date and author too that way if you want. There are even maps for it. A sentinel isn't strictly necessary for that. So really that just leaves the commit SHA, and that's necessary for the internal implementation, so really the best you could do there is scroll the window to the left a bit or maybe `:syn conceal` it.

Use `:Gedit` with no arguments to return from a historical file to the work tree version.

**Comment by tormodatt** [comment]
For people arriving here; The date-part is customizable at least. To make the date-part a bit more readable, add the following in `.gitconfig`:

```
[blame]
    date = human
```

This will cause git blame (and thereby also fugitive) to show dates as `Mon Feb 3 14:00`, `50 minutes ago` etc.

**Comment by jdsutherland** [comment]
@tormodatt the output seems to differ for the current year, which looks a little strange:
![image](https://user-images.githubusercontent.com/5385846/109199303-82cb7300-775c-11eb-8d28-55023c1b8836.png)

Another option is `date = relative`:
![image](https://user-images.githubusercontent.com/5385846/109200921-64ff0d80-775e-11eb-9009-52894f4fe161.png)

**Comment by abodelot** [comment]
@tormodatt thanks for suggesting configuring it with `.gitconfig`.

If you only want the date (without the time), and having the same format for each line, you can customize the format too:

```
[blame]
    date = format:%Y-%m-%d
```

![image](https://user-images.githubusercontent.com/1200828/234524621-f6737cda-639d-48b5-8009-22914fed175e.png)
