### ISSUE TITLE
:Gbrowse returns: '.' is not a supported remote

### ISSUE THREAD

**Issue by bswinnerton** [tpope/vim-fugitive#894]
I believe that this is a result of https://github.com/tpope/vim-fugitive/pull/874, I was able to Git bisect my way to 245ce889e2a6eb318cec865cf787e7bb0cb8aa95 as the offending commit.

Here's what I get when I type `:Gbrowse` in one of my projects: `fugitive: '.' is not a supported remote`.

Interestingly, this only seems to be happening for one of my repositories, most others seem fine. So I imagine it has something to do with the way _that_ repository's remotes are configured.

Here is some relevant version information (with the organization and repository changed):

```
$ git remote -v
origin  https://github.com/foo/foo.git (fetch)
origin  https://github.com/foo/foo.git (push)
```

```
$ git remote get-url origin
https://github.com/foo/foo.git
```

```
$ git config remote.origin.url
https://github.com/foo/foo.git
```

```
$ git --version
git version 2.12.0
```

```
$ vim --version
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20161203-31348-14wti82/neovim-0.1.7/build/config -I/tmp/neovim-20161203-31348-14wti82/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20161203-31348-14wti82/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20161203-31348-14wti82/neovim-0.1.7/build/include
Compiled by brooks@Alfred.home

Optional features included (+) or not (-): +acl   +iconv    -jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.7/share/nvim"
```

**Comment by tpope** [comment]
Maybe @frioux can weigh in, but if this is only happening for one of your repos, you're probably the one in the best position to diagnose the problem.

**Comment by frioux** [comment]
@bswinnerton can you include the fill `.git/config` for the repo?

**Comment by smancill** [comment]
I have the same problem.

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = git@gitlab.com:ORG/REPO.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[remote "github"]
	url = https://github.com/ORG/REPO
	fetch = +refs/heads/*:refs/remotes/github/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

Both `ORG` and `REPO` are just ASCII letters.

**Comment by smancill** [comment]
No, I changed 'origin' url to `https://gitlab.com/ORG/REPO.git` and the problem continues.

**Comment by frioux** [comment]
@smancill did you install vim-rhubarb?

**Comment by frioux** [comment]
@smancill any chance  you can build a checkout of a public github and gitlab repo so I can try to reproduce locally?

**Comment by smancill** [comment]
Try this:

```
git clone https://gitlab.com/smancill/test-repo.git
cd test-repo
git checkout -b foo
vim README.md
```

`Gbrowse` will report `fugitive: '.' is not a supported remote` (on branch `foo`).

I would expect that the URL `https://gitlab.com/smancill/test-repo.git` is open, instead of reporting that `origin` is not supported. I didn't know about `fugitive_browse_handlers` until now.

**Comment by frioux** [comment]
Actually it does work for me, but I have vim-rhubarb installed and https://github.com/shumphrey/fugitive-gitlab.vim

**Comment by smancill** [comment]
@frioux installing _fugitive-gitlab_ fixed the problems.

**Comment by frioux** [comment]
I vote we close this and move on.

**Comment by bswinnerton** [comment]
> I vote we close this and move on. 

This is still a problem for me with a GitHub remote.

**Comment by frioux** [comment]
@bswinnerton using the repo provided above?  Can you detail how you run into it?  And you have latest fugitive, rhubarb, and fugitive-gitlab?

**Comment by tpope** [comment]
Don't forget the version of Git might play into it. https://github.com/tpope/vim-fugitive/blob/be2ff98db543990d7e59a90189733d7a779788fd/plugin/fugitive.vim#L2348-L2352

**Comment by bswinnerton** [comment]
This was resolved by installing `tpope/vim-rhubarb`.

**Comment by hakujin** [comment]
This problem still exists if `.git/config`'s `origin.url` contains a username in the URL. e.g. `foo@github.com/bar/baz.git`.

**Comment by tpope** [comment]
I didn't even know that was allowed. That's handled on the Rhubarb side of things.
