### ISSUE TITLE
G-commands don't work when file symlinked from git repo

### ISSUE THREAD

**Issue by sphaugh** [tpope/vim-fugitive#895]
I use stow + git to manage my dotfiles and something that irks me is that, for example, if I want to edit my managed `~/.config/nvim/init.vim` I have to do `vim ~/etc/neovim/.config/nvim/init.vim`. 

It's just a little extra typing but I have do something like this every time I want to edit a stowed config file. And the virtual pain is even worse if I'm already in `~/.config/nvim`. Since I can do git commands from this folder, is there a good reason fugitive shouldn't also be functioning?

**Comment by tpope** [comment]
Let's start with how is Git able to to figure out the correct repository location?

**Comment by sphaugh** [comment]
Well, I think this is "the" way, but there could be another:
```
~/.config/nvim <master *>
% readlink -f init.vim
/home/sean/etc/nvim/.config/nvim/init.vim
```
Then you can go up the file tree as usual.

**Comment by tpope** [comment]
Well, you managed to answer the question without so much as telling me the location of the symlink, which is kind of amazing, but I don't have time for a game of 20 questions.

**Comment by justinmk** [comment]
@sphaugh You could try a hack like this so that symlinks are always resolved:

    :au BufRead * if resolve(expand('<afile>')) !=# expand('<afile>')|exe 'file '.fnameescape(resolve(expand('<afile>')))|e|endif

There might be something better on vim wiki or something, but that seems to work fine.

**Comment by sphaugh** [comment]
@tpope I'm confused. Do you mean "location of the symlink" in an abstract sense? In my example, the symlink is the file `~/.config/nvim`. But, that's determined when stow runs and depends on the differences between the actual file tree and the stow package tree.

Could fugitive do something like (the VimScript equivalent of) `cd $(readlink -f foo.c | xargs dirname)` before running its git commands? I don't mind learning a little VimScript and submitting a PR, I'm just wondering if there's a rationale for not doing this?

I know it's aggravating when someone asks for a feature thinking it should be easy, and really has no idea what it takes... and I'm sorry, but am I overlooking something obvious? It seemed like your reply was a leading question, so what answer were you expecting?

**Comment by nmschulte** [comment]
Fugitive just runs Git; if you're file (symlink in this case) isn't in a Git repository, what exactly are you expecting to happen here?  It doesn't make sense for Fugitive to accommodate something specific to Stow.  Fugitive works with Git.

Maybe I'm missing something about symlinks; I don't use Git to manage symlinks, and I'm not really sure how or why one would want to do that (and I don't think that's what is going on here, either.).

**Comment by sphaugh** [comment]
@nmschulte It's not specific to stow, though. If I open a symlink to a file, where the actual file is in a git repository, fugitive won't work. Git command line will still work. Why the difference in behavior?

**Comment by tpope** [comment]
@sphaugh The reason we're all confused is you keep saying stuff like "symlink to file", but in your third post you finally revealed what you actually have is a symlink to a *directory* (but even then you still called it a file). File symlinks do not behave the way you describe. The fact directory symlinks work is news to me, but not wholly unexpected. I think your best bet is still to start with solution @justinmk suggested.

**Comment by sphaugh** [comment]
Okay, I'll try that. Sorry again for the misunderstanding.
