### ISSUE TITLE
:Gbrowse master:#

### ISSUE THREAD

**Issue by esniper** [tpope/vim-fugitive#896]
Ability to browse the current file but on a different branch.

I have a local branch which doesn't have an upstream or I don't want to look at it and instead, I want to look at the remote version on a different branch.

Could we have the ability to say something like `:Gbrowse <branch>:#` which would open the current file on a the specified `<branch>`.

**Comment by tpope** [comment]
You probably want either `:Gbrowse branch:%` or `:Gbrowse origin/branch:%`.

**Comment by esniper** [comment]
You're right. That worked. Thanks.

**Comment by esniper** [comment]
Is there a way to set it to look up to a given branch by default?

**Comment by tpope** [comment]
Only by changing your local branch's upstream.
