### ISSUE TITLE
':Gcommit -m "msg"' raises error when not in :Gstatus buffer

### ISSUE THREAD

**Issue by igorcadelima** [tpope/vim-fugitive#897]
Every time I ```:Gwrite``` an edited file and try to ```:Gcommit -m "commit msg"``` I get one error like the following:
> Error detected while processing function <SNR>52_Commit:
> line   23:
> E194: No alternate file name to substitute for '#': !env GIT_EDITOR=false git --git-dir=/home/igorcadelima/workspaces/ws-ruby/koans/.git commit -m "Solve AboutArrays#test_shifting_arrays" > /tmp/vOEr7c0/6 2> /tmp/vOEr7c0/7
> Press ENTER or type command to continue

Shouldn't this be acceptable and raise no errors?

If I really want ```:Gcommit -m "msg"``` to work, I need to enter such command while in the :Gstatus buffer. This means that in order to commit the file I'm working on atm, I'd have to:
1. :Gw
2. :Gstatus
3. :Gcommit -m "msg"

or

1. :Gw
2. :Gcommit
3. Insert commit message

If the ```:Gcommit -m "msg"``` command really doesn't work outside the :Gstatus buffer, would there be a way of staging and commiting the current file with a short message using less keystrokes than I'd use if following either one of the steps list above?

Cheers.

**Comment by tpope** [comment]
You need to `\` escape the `#`.  This is congruent with Vim's built-in `!`.

    :!echo "Solve AboutArrays#test_shifting_arrays"
    :!echo "Solve AboutArrays\#test_shifting_arrays"

**Comment by igorcadelima** [comment]
Incredibly quick and helpful! Thanks heaps!
