### ISSUE TITLE
Can't change diff colors

### ISSUE THREAD

**Issue by dunk** [tpope/vim-fugitive#903]
When browsing a diff that I jump to from `:Gblame`, in this case using shift-O to view it in a new tab, I get highlights in my macvim standard scheme. However, if I set, say, `:hi DiffAdd guibg=red guifg=white` (white on red just so it would stand out for testing), it doesn't affect the colors in the diff. How can I change the color of additions and deletes in the diff?

**Comment by tpope** [comment]
You need to look in `syntax/diff.vim` and use the highlight groups found there.

**Comment by dunk** [comment]
When I change the colours in the diff nothing seems to change when I set `DiffAdd` and friends, but `Identifier` and `Special` seem to set the colour for the added and removed colours, respectively 😕.

**Comment by dunk** [comment]
Urgh, it's `diffAdded`, not `DiffAdd`. Oops!

**Comment by augustovictor** [comment]
Thanks. Just sharing my choices:
```shell
hi diffAdded ctermfg=188 ctermbg=64 cterm=bold guifg=#50FA7B guibg=NONE gui=bold
hi diffRemoved ctermfg=88 ctermbg=NONE cterm=NONE guifg=#FA5057 guibg=NONE gui=NONE
```
![image](https://user-images.githubusercontent.com/938051/150133102-9a20ffd2-75c1-49d4-aa4a-c2231128adf1.png)
