### ISSUE TITLE
<CR> to close :Gstatus buffer before openning the file

### ISSUE THREAD

**Issue by aminroosta** [tpope/vim-fugitive#905]
How can i map `<CR>` to close status before doing `:Gedit`?

Many thanks :-)

**Comment by tpope** [comment]
I think the closest you can get with the current implementation is your own map that calls `<CR>` and then closes the window after the fact. Untested:

```viml
autocmd FileType gitcommit if &previewwindow|nmap <buffer> <Leader>f <CR><C-W>z|endif
```

**Comment by tpope** [comment]
Actually this might achieve what you want, but it circumvents a lot of internal machinery so watch out for edge cases:

autocmd FileType gitcommit if &previewwindow|nmap <buffer> <CR> :pclose<Bar>edit <Plug><cfile><CR>|endif

**Comment by aminroosta** [comment]
@tpope Thanks for your comment, and thanks for your awesome plugins.
I tried both versions but it didn't worked for me.
But i figured out a working hack `nmap <buffer> <CR> S<C-w>o`.
It uses the `S` command to show the buffer in a new split and then maximizes with `<C-w>o`.

Thanks :-)

**Comment by tpope** [comment]
I just tested both of my maps and they do work for me. *shrug* Anyways one more thing you might consider is just `:Gedit :` to load the status window as a full buffer. Then you don't need to close it.

**Comment by aminroosta** [comment]
@tpope ahh, there should be some problem in my config then.
Thanks for testing.
