### ISSUE TITLE
Empty error message when commit fails with "useConfigOnly = true"

### ISSUE THREAD

**Issue by gautaz** [tpope/vim-fugitive#907]
I have recently added the `useConfigOnly = true` option to my git configuration.
When trying to commit from `Gstatus` window with `cc` on a repo where my user properties are not defined, fugitive fails (which is expected) but the error message reported is empty: `fugitive: `.

Is there any way to tell fugitive to be more verbose in this particular use case?

**Comment by tpope** [comment]
[Here is where we try to extract the error.](https://github.com/tpope/vim-fugitive/blob/c2877d0d5cf1f9aefd91b2821b89f44ce1b7174d/plugin/fugitive.vim#L1092-L1093) We need a one line error message because it's going into an exception. Tweaks to the logic welcome.
