### ISSUE TITLE
Errors when opening file not in a git work tree in neovim 0.2

### ISSUE THREAD

**Issue by lohfu** [tpope/vim-fugitive#908]
After upgrading my neovim to v 0.2, fugutive has started throwing uncaught exceptions:

```
Error detected while processing function fugitive#detect[8]..<SNR>32_buffer_path[7]..<SNR>32_repo_tree[7]..<SNR>32_throw:
line    2:
E605: Exception not caught: fugitive: no work tree
Error detected while processing function fugitive#detect[8]..<SNR>32_buffer_path[7]..<SNR>32_repo_tree:
line    7:
E171: Missing :endif
Error detected while processing function fugitive#detect[8]..<SNR>32_buffer_path:
line    7:
E171: Missing :endif
Error detected while processing function fugitive#detect:
line    8:
E171: Missing :endif
```

I am running Arch Linux (kernel 4.10.13-1-ARCH) with NVIM v0.2.0.

In order to check if any other plugins were conflicting my simplified `init.vim` is now just:

```
"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

call plug#begin('~/.local/share/nvim/plugged')
" required

Plug 'tpope/vim-fugitive'

call plug#end()

" required
filetype plugin indent on

syntax on

set bg=dark
```

**Comment by tpope** [comment]
Do you have any symlinks in any of the paths you are editing?

**Comment by tpope** [comment]
Also please report back on the value of `:echo b:git_dir` in the buffer where the error occured.

**Comment by lohfu** [comment]
No symlinks in any of the paths i am editting...

`:echo b:git_dir` outputs `/.git`

**Comment by tpope** [comment]
Does `/.git` actually exist, per chance?

**Comment by lohfu** [comment]
Oh my god, it does... what was i thinking, when and why?

Silly, silly me. Sorry for wasting your time
