### ISSUE TITLE
Feature Request: Pull request review

### ISSUE THREAD

**Issue by xangelux** [tpope/vim-fugitive#916]
Hi, I really enjoy your plugins and I use some every day, like this one. To me, my day to day work would include Github Pull Request management (from the same repo or from forks) and some times Github's web interface it's enough but some times it's too annoying when there are too many changes to go through. 

Steps to go:
- Git pull (`fugitive-:Git pull` it's more than fine)
- Get the branch to review (`fugitive-:Git  fetch origin pull/ID/head:BRANCH` it's ok for it)
- List the files changed between target branch and source branch (well... )

As you can see, there is no easy way to load all the files changed so we can jump between them and do a fugitive-:Gdiff on them. I know there is a command in git to list the files (git diff --name-status master..branchname)

**Comment by tpope** [comment]
`:Gedit FETCH_HEAD^{}` might be the jumping off point you are looking for.

**Comment by xangelux** [comment]
That would help me to jump on the next one right? wouldn't it be better if we could see the list of files?

**Comment by glittershark** [comment]
`:args \`git diff -l BRANCH origin/BRANCH\``, maybe?

**Comment by glittershark** [comment]
```
:args `git diff -l BRANCH origin/BRANCH`
```
maybe?

**Comment by xangelux** [comment]
the `:args` would help opening the files, though that wouldn't provide a quickfix list to "fast switch" between the buffers/open files (it would be better to have only a list instead of opening all the files, and only open the files if I hit enter on them.

**Comment by xangelux** [comment]
About the `:Gedit FETCH_HEAD^{}` the list of files would be needed so I would know the files to open and then `:Gedit` but then, that would only show info on the revision, not the contents of the file right?

**Comment by tpope** [comment]
This is sounding a lot like #132.

**Comment by xangelux** [comment]
Yes, it sounds like the one that is generic would solve the problem, I mean, the "accept any command" I would only suggest to add a target revision/branch so we can load by doing something like ":Gdiffiles BRANCH"
