### ISSUE TITLE
Gdiff not respecting the setting splitright

### ISSUE THREAD

**Issue by joaqo** [tpope/vim-fugitive#919]
I set `set splitright` in my vimrc to make new splits appear on the right, but `Gdiff` is creating the new splits on the left.

(Awesome plugin btw, just started using it and I love it!)

**Comment by tpope** [comment]
I found this sort of behavior confusing, especially in light of the fact `:Gdiff` can split both horizontally and vertically, so I instead hard coded the older file to always appear on the left and the newer file to always appear on the right.
