### ISSUE TITLE
Installation/Startup error

### ISSUE THREAD

**Issue by pfackler** [tpope/vim-fugitive#920]
I tried installing vim-fugitive with vim-plug. Both in the installation and afterward when starting vim, I get the following error:
```

Error detected while processing ~/.vim/plugged/vim-fugitive/plugin/fugitive.vim:
line 1963:
E216: No such event: fugitiveblame call s:BlameSyntax()
```

**Comment by tpope** [comment]
Does your version of Vim have syntax highlighting? `:echo has('syntax')`

**Comment by pfackler** [comment]
1

**Comment by tpope** [comment]
What's actually on line 1963?

**Comment by pfackler** [comment]
autocmd Syntax fugitiveblame call s:BlameSyntax()

**Comment by tpope** [comment]
That's correct. Not a lot of ideas. Check `:echo exists("##Syntax")` I guess. And report your `:version` because I'm starting to suspect it's a Vim bug.

**Comment by pfackler** [comment]
`:echo exists("##Syntax")` returns 1

These are the first three lines from `:verson`
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 26 2017 07:49:10)
Included patches: 1-586
Compiled by Arch Linux

**Comment by tpope** [comment]
Not sure what else to do. As a workaround you can delete that line.

**Comment by pfackler** [comment]
I'm sorry for wasting your time on this. Turns out I had an `augroup Syntax` definition in my vimrc.
