### ISSUE TITLE
So laggy

### ISSUE THREAD

**Issue by xahon** [tpope/vim-fugitive#921]
My `syntime on` `syntime report` show a lot of time spent to syntax highlighting. I can provide any information you need

**Comment by tpope** [comment]
For starters you could provide the filetype.

**Comment by xahon** [comment]
HTML with 3000 lines for example

**Comment by tpope** [comment]
And this relates to fugitive how exactly?

**Comment by xahon** [comment]
Sorry, I forgot to specify command. Gblame lags

**Comment by tpope** [comment]
Fixed some low hanging fruit. Further improvements welcome.
