### ISSUE TITLE
Add vim 8 support?

### ISSUE THREAD

**Issue by aliev** [tpope/vim-fugitive#922]
Is it possible to add Vim 8 async support to Pull/Push/Commin in background?

There is an option https://github.com/skywind3000/asyncrun.vim/wiki/Cooperate-with-famous-plugins#fugitive but will be great to have it without any plugins :)

**Comment by tpope** [comment]
The problem with using Vim 8 support is that jobs will hang indefinitely if the underlying command prompts for a password. In fact that's a pretty big sticking point for adding Vim 8 job support to fugitive.vim.

**Comment by viktorstrate** [comment]
Could async Pull/Push/Commit be archived in Neovim? - Maybe using the builtin terminal.

**Comment by tpope** [comment]
See #911.

By the way I was wrong about Vim 8 hanging. But natively supporting async make is still an awful lot of code I don't think I want Fugitive to take responsibility for.

**Comment by mcepl** [comment]
> But natively supporting async make is still an awful lot of code I don't think I want Fugitive to take responsibility for.

Which is why #847 , isn’t it? You should use some third part library (e.g., asyncrun) for it?

**Comment by tpope** [comment]
This will be handled by https://github.com/tpope/vim-dispatch/pull/193.
