### ISSUE TITLE
Unexpected error after updating to Vim 8

### ISSUE THREAD

**Issue by jabellcu** [tpope/vim-fugitive#923]
I ma getting the following error on "Gdiff":

![image](https://user-images.githubusercontent.com/16623672/27076466-2ad75112-5025-11e7-999c-c1ae479bf1cf.png)

I am positive I am working on a git repo.

It has been happening intermittently ever since I updated to Vim 8.

Any guidance would be appreciated, Many thanks!

**Comment by fpereira1** [comment]
I have no problem running fugitive on vim8 or neovim

**Comment by jabellcu** [comment]
I believe the current directory is a git repo. I have "set autochdir" on my _vimrc.
I haven't been able to replicate the problem consistently, but whenever this happens, deleting vim-fugitive and installing it again solves it. I am clueless!

**Comment by jabellcu** [comment]
Update: the issue is persisting. It seems to be linked with network paths in Windows. I would like to know if anyone else is experiencing issues. Thanks!

**Comment by tpope** [comment]
That particular error message is gone, is it fixed now or failing in a new way?

**Comment by jabellcu** [comment]
I haven't had this error again. All I did is a clean re-install (a while after I gave up). I don't know what went wrong. I suspect it was related with repos on UNC paths. Many thanks for the update.
