### ISSUE TITLE
An ls-files command

### ISSUE THREAD

**Issue by bpj** [tpope/vim-fugitive#924]
What about a command which invokes `git ls-files`, puts the output in a temporary file and opens a buffer where you can `<CR>` on a file to edit that file?

**Comment by juanibiapina** [comment]
`command! -nargs=? -bar GLsFiles call setqflist(map(systemlist("git ls-files"), '{"filename": v:val, "lnum": 1}')) | copen`

**Comment by mcepl** [comment]
@juanibiapina that's awesome! Thank you.
