### ISSUE TITLE
Gblame insite a Gdiff broke cursorbind

### ISSUE THREAD

**Issue by feliperama** [tpope/vim-fugitive#927]
Steps to reproduce:
1) :Gdiff  to open a 3-way merge using Gvdiff (I didn't tested with Gdiff, probably same issue)
2) :Gblame to blame that file, for example to see the commit of a specific line
3) :q to close the blamed opened window and return the merge
4) use up/down/pageup/pagedown and will noticed that there is no more cursorbind at 3way merge.

I think is a very common thing do other fugitive commands during a big merge conflict resolution.

**Comment by tpope** [comment]
I don't think using multiple `cursorbind` Fugitive features at once will every be tenable. As an alternative, you might try `:%Gblame`, which will do the blame in a window without `cursorbind`.
