### ISSUE TITLE
Breaks on "Vim 8" because of check for ":terminal"

### ISSUE THREAD

**Issue by pappasam** [tpope/vim-fugitive#928]
## Action + Symptom

When I try to use ":Git add", This causes the command "terminal git add %:p" to be executed, which my Vim version does not support.

```txt
E319: Sorry, the command is not available in this version: terminal git add %:p
```

## Cause

Bram is implementing a terminal emulator in Vim 8.

```txt
*terminal.txt*	For Vim version 8.0.  Last change: 2017 Jul 04
		  VIM REFERENCE MANUAL	  by Bram Moolenaar
Terminal window support					*terminal*
WARNING: THIS IS ONLY PARTLY IMPLEMENTED, ANYTHING CAN STILL CHANGE
```

Lines 727:741 in vim-fugitive/plugin/fugitive.vim check for the existence of ":terminal", which I do not think we can unset.

```viml
if exists(':terminal')
  let dir = s:repo().tree()
  if expand('%') != ''
    -tabedit %
  else
    -tabnew
  endif
  execute 'lcd' fnameescape(dir)
  execute 'terminal' git args
else
  call s:ExecuteInTree('!'.git.' '.args)
  if has('win32')
    call fugitive#reload_status()
  endif
endif
```

## Possible Remedy

Update aforementioned code to use a check other than "if exists(':terminal')".
Possibly provide a global configuration variable enabling people to choose whether they would like to use a built-in Vim terminal emulator or their system shell.

Thanks in advance!

**Comment by tpope** [comment]
Tacking on `&& has('nvim')` sounds good to me.

**Comment by pappasam** [comment]
@tpope that might work for now, but is it possible some neovim users prefer using their terminal and not neovim's built-in terminal? Not sure why one would be preferable over the other since I'm not a neovim user, but it sounds plausible to me.

Additionally, if and when the terminal is ready in Vim 8, Vim 8 users will probably want the option to use the Vim 8 terminal feature with this Plugin. Is this something to be fixed at a later date, or do you think this is something worth addressing now?

**Comment by tpope** [comment]
Neovim's `:!` is completely broken for interactive commands. That's the only reason `:terminal` support is implemented at all. I say alter the conditional for now, and revisit once Vim's `:terminal` is fleshed out.

**Comment by pappasam** [comment]
Cool, makes sense to me; thanks for the clarification. Looking forward to the update! If you're swamped with something else, let me know if you'd like me to submit a pull request.

**Comment by tpope** [comment]
PR would be great.
