### ISSUE TITLE
Closing a Gblame window also closes the NERDTree window

### ISSUE THREAD

**Issue by JESii** [tpope/vim-fugitive#931]
To reproduce:
1) Open vim with NERDTree window in a repo
2) select any code file
3) Issue :Gblame on that file
4) Close the :Gblame window, either with 'q' or ':q'
5) Gblame window closes and NERDTree window is closed.

**Comment by hiteshpaul** [comment]
Tried reproducing. Did not face the issue. 
Try updating vim-fugitive and see if the problem still persists.

**Comment by tpope** [comment]
If it's happening on `:q`, I'm inclined to say it's not a Fugitive bug? Try with just those 2 plugins installed and see if it still happens.
