### ISSUE TITLE
New Command: Greset

### ISSUE THREAD

**Issue by somini** [tpope/vim-fugitive#934]
As a companion to `Gwrite`, I'm requesting a command to reset the current file.

On Vim, my old hack still works:
```
execute 'silent Git reset '.shellescape(expand('%:p'))
```
But on neovim this is no longer silent, it requires me to hit Enter in the `:terminal` bufer.

I know Fugitive can reset files non-interactively, because I can do it from the `:Gstatus` buffer. I'm just asking for this functionality to be exposed as a command.

**Comment by tpope** [comment]
You should be able to update your hack to something like

    :echo fugitive#repo().git_chomp('reset', fugitive#buffer().path())

I'm reluctant to wrap an existing command with the same name but differing semantics.  That is, having `:Greset` call not `git reset` but rather `git reset %` feels too confusing. I'm open to providing the behavior in other ways, but I'm not sure what that would look like.

**Comment by somini** [comment]
Perfect, thanks for that snippet.

I just told git to shut up to achieve non-interactiveness:
```
echo fugitive#repo().git_chomp('reset', '--quiet', '--', fugitive#buffer().path())
```
This will only print messages on error. It will also avoid funny business with files starting with `-`.
