### ISSUE TITLE
3-way diff for staging

### ISSUE THREAD

**Issue by wcooley** [tpope/vim-fugitive#941]
Maybe this is a "HOWTO" for someone adventurous to find in the issues or add to the docs or maybe it's a feature request to make it more straightforward.

I really love the 2-way diff for staging changes, so I can split my changes into logical commits, even when I'm changing things around the same lines and `git add --patch` or GUI tools get things wrong.
However, because I get distracted by things my staging process can take long enough that I forget what on the index side are staged changes and what are not, so I'd really like to be able to _also_ compare the index with _HEAD_.
If I select the staged file in the Gstatus window, the diff changes to be just HEAD vs index.

Solution:
1. Open the index vs working copy diff as usual (`:Gstatus`, select unstaged file, `D`)
1. Ensure the window of the index in the diff is active (it is for me after the previous) (this is the file with the `fugitive:///...` name).
1. Run `:Gdiff HEAD`.

The result is a 3-way diff with read-only HEAD, index and working copy.

**Comment by dhruvasagar** [comment]
Not entirely sure if this would be very valuable as a 3-way diff. I usually prefer doing them independently to ensure I see clearly what's up for commit, and what's in the index. Also swapping hunks around may become a bit confusing at times if you're not careful. Still may be worth adding as a feature, but I reckon this wouldn't be a very used feature.

**Comment by tpope** [comment]
I think this is esoteric enough that putting it in the issue tracker where people can search for it, as you have done, is the right way to go. Cheers!
