### ISSUE TITLE
:Gw writes to refs instead of file

### ISSUE THREAD

**Issue by hseg** [tpope/vim-fugitive#943]
To reproduce:
Have a branch and a file with the same name.
Edit the file.
Run `:Gw`.
The edit in question will be saved to the _ref_ instead of the file+index,
necessitating the usage of the reflog to recover state.

**Comment by tpope** [comment]
Older versions of Fugitive let you do `:Gedit master` to edit the ref, so it's possible that was leaking into `:Gwrite` somehow. This behavior has since been removed.
