### ISSUE TITLE
Feature request: Checkout multiple files at once using visual mode

### ISSUE THREAD

**Issue by aankittcoolest** [tpope/vim-fugitive#944]
It would be cool to checkout multiple files at once by using virtual selection of vim.

**Comment by dhruvasagar** [comment]
@aankittcoolest Kindly check out my fork and see if you face any issues while tpope finds the time to merge the PR

**Comment by tpope** [comment]
@dhruvasagar, what happens to the multiple `echomsg` lines? The reason I haven't hooked this up myself is I want the recovery situation to be top notch before allowing the user to shoot themselves in the foot this hard.
