### ISSUE TITLE
trimmed output of pre-commit hook

### ISSUE THREAD

**Issue by alfredodeza** [tpope/vim-fugitive#95]
I took an initial look at issue #19 [0] but this seems a bit different.

I have to work with a set of pre-commit hooks that display errors in a few lines almost
always. So when something fails due to a pre-commit hook, I can't tell why because all
I am able to read is the first line of all the output (which does not include the _actual_ error).

It seems fugitive is using `messages`, and when I do check :messages I again see just one 
line.

Is there a way to see the whole output of a failure in a hook? 

I was using the latest version of the plugin (1.2) so I decided to checkout the latest changes from the
actual repo but I still found the same problem.

[0] https://github.com/tpope/vim-fugitive/issues/19

**Comment by vnikk** [comment]
Hi. I got the same issue. When i do `:Gcommit` with some changes staged it just shows an empty bash screen (without any hook output). What would be the correct way to use those hooks with fugitive?

**Comment by tpope** [comment]
I think this is *finally* sorted.
