### ISSUE TITLE
:Git doesnt expand revision shorthands

### ISSUE THREAD

**Issue by bounceme** [tpope/vim-fugitive#950]
example: `:Git rebase -i ~2`

**Comment by tpope** [comment]
That doesn't work with `git` either. Maybe you want `HEAD~2` or `@~2`.

**Comment by bounceme** [comment]
so the `fugitive-revision` only applies to the non `:Git`, `:G...` commands? `git rebase -i <commit>`  but with the `<commit>`  in the fugitive-revision syntax is what i am looking for. maybe i'm forgetting something

**Comment by tpope** [comment]
Oh, yes. Note that Fugitive's `~2` is a shorthand for a blob - `current-buffer-revision~2:current-buffer-path` - not a commit, so it would not work as an argument to `git rebase` in any case.
