### ISSUE TITLE
Gpush provides no output

### ISSUE THREAD

**Issue by YanDoroshenko** [tpope/vim-fugitive#951]
When running Gpush, the editor freezes for a bit (executing the push I suppose) and then just clears the message line, providing no output from push.
Like: 
```
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 297 bytes | 297.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To github.com:.........git
   c7cc1dd..d30fd3d  test -> test
```
Tested with Neovim 0.2.0, vim-fugitive 2.2 installed from AUR (package neovim-fugitive), with and without vim-airline.

**Comment by PetraOleum** [comment]
Try `:copen` after it's finished

**Comment by YanDoroshenko** [comment]
@PetraOleum Well, it does show part of the stuff I'd like to see, but what the hell is `:copen` and why doesn't `:Gpush` show output by default?

**Comment by PetraOleum** [comment]
It opens the quickfix list (see also e.g. :help Glog). This issue has
more to do with how neovim handles command output than fugitive.

**Comment by YanDoroshenko** [comment]
@PetraOleum The thing is, it's not working with Vim either. Vim just shows me my terminal for the same couple of seconds (with no `git push` output) and then returns to the editor window. So it can't be just a Neovim issue.

**Comment by PetraOleum** [comment]
With vim you can type `:!<CR>` to get the result of shell commands (like
that one, in effect) back; neovim does not let you do that.

**Comment by YanDoroshenko** [comment]
@PetraOleum Why should you though? Should not the plugin show you what it's doing? If I wanted to type additional stuff to get a terminal output, I could have run the command in another tab or window or something. Isn't this plugin specifically designed so that you don't have to do that?

**Comment by tpope** [comment]
What is the output of `:set shellpipe?`?

**Comment by YanDoroshenko** [comment]
@tpope `shellpipe=2>&1| tee`

**Comment by tpope** [comment]
The output should be visible then. It's basically just calling `set makeprg=git\ push | silent make | redraw!` if you want to debug further. Or try installing dispatch.vim, which provides for an alternative, asynchronous execution path which might be more to your liking and thus render the whole thing moot.

**Comment by YanDoroshenko** [comment]
[Dispatch](https://github.com/tpope/vim-dispatch) + [Dispatch-Neovim](https://github.com/radenling/vim-dispatch-neovim) works fine, thanks.
