### ISSUE TITLE
:Gcommit -p flashes output to screen, fails to select patches

### ISSUE THREAD

**Issue by markstos** [tpope/vim-fugitive#953]
I'm using fugitive with NeoVim 0.2.1. 

When I try to use `:Gcommit -p`, something flashes to the screen so fast it can't be read, then my pending patches are skipped over. How can I see what's being flashed to the screen when `:Gcommit` is being run? I presume it's some sort of interesting error output.

**Comment by tpope** [comment]
It's probably just spamming the diff at you. I recently gave up and had it open `:Gstatus` inline diffs instead, as this isn't really possible to support. You can use those or if you hate them `:Git add -p`.
