### ISSUE TITLE
Gblame with keywordprg on commit hash show bottom of `git show --no-pager` output

### ISSUE THREAD

**Issue by guimaluf** [tpope/vim-fugitive#955]
When I open `:Gblame` and press `Shift + K` on a commit hash, it loads `keywordprg` which uses `git show` with `--no-pager`. That manner  I can't see the commit description nor other things that were changed in previous file.
Is this my misconfiguration or an expected behavior?

**Comment by tpope** [comment]
It uses `--no-pager` in the GUI, which doesn't really support a pager correctly anyways. Try `o` instead.

**Comment by keithlo** [comment]
what does the `o` do ? I'm having a similar issue

**Comment by tpope** [comment]
https://github.com/tpope/vim-fugitive/blob/f7a6097caad06cdcd9106a856f43fc913baad0bd/doc/fugitive.txt#L318-L320

I'm not sure where y'all are finding `K` as it doesn't appear to be documented. I'm leaning towards removing it just to clear up the confusion.

**Comment by keithlo** [comment]
Thanks! I often use `K` to insite `keywordprg` on commits.
ie. `git log | vim -R -` then hitting `K` expands a commit. So it was more of a habit than anything
