### ISSUE TITLE
Cannot patch add files in Gstatus

### ISSUE THREAD

**Issue by treyhunner** [tpope/vim-fugitive#957]
Steps to reproduce:

1. Change a file that is tracked by git
2. `:Gstatus`
3. Hit down arrow or `j` to move the cursor over an untracked file
4. Type `p` to enter patch add mode
5. Type `y`, `n`, or any other key and see that the key's usual behavior occurs instead of the usual patch add response behavior

I suspect the issue may be related to cache or temporary files on my machine, but I'm not sure what I should do to test that hypothesis easily.

**Comment by eprikazc** [comment]
I have the same issue.

**Comment by assaf758** [comment]
I have the same issue. Found a simple work-around though - pressing 'i' will change to insert mode, where one can slect y,n etc.

**Comment by tpope** [comment]
Neovim?

**Comment by assaf758** [comment]
yep

**Comment by wbthomason** [comment]
Same issue, also Neovim (0.2.2).

**Comment by Holzhaus** [comment]
Also same issue here.
```
:version
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-pl
t -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL
=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallt
hrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS
-D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/inclu
de -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/
build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Translated by builduser
Features: +acl +iconv +jemalloc +tui
```

**Comment by phansch** [comment]
Same here on neovim 0.2.3. As a workaround I am currently using
```vim
augroup nvim_term
  au!
  au TermOpen * startinsert
  au TermClose * stopinsert
augroup END

```

**Comment by treyhunner** [comment]
And yes I'm on neovim also.

**Comment by tpope** [comment]
Possibly Fugitive can call `:startinsert` itself. I'll defer to someone with more NeoVim knowledge.

**Comment by jc00ke** [comment]
I'm just now experiencing this on NeoVim 0.3.7 and 3684c01.
Not sure why, but I'm not able to get @phansch's [suggestion](#issuecomment-352774977) to work, nor does `augroup neovim_terminal`. What does work is `:sp term://git add -p %` when in the file buffer. I'm not sure where in fugitive the `P` key is bound to trigger the patch. If someone can point me there (I looked) I'll play around with a few options.

**Comment by tpope** [comment]
The reason it broke on Neovim is I recently [ripped out `:terminal` support for `:Git`](https://github.com/tpope/vim-fugitive/commit/17618402fa793d347d60540b9caf84210128ad49), because it's, well, freaking obnoxious to create a terminal window for every single Git command. It works fine in Vim, blame Neovim for breaking `:!`.

I'll probably bring back `:terminal` for a subset of commands that actually need it, but now that `:Gstatus` supports inline diffing, I consider `P` to be softly deprecated, so this is not a high priority.

**Comment by jc00ke** [comment]
I missed the inline diffing addition; will retrain my `P` finger to hit `=`. Thanks!
