### ISSUE TITLE
Error detected while processing User Auto commands for "NERDTreeInit"

### ISSUE THREAD

**Issue by hbarcelos** [tpope/vim-fugitive#967]
I'm getting the following errors after I recently did a fresh install of my vim plugins whenever I try to open nerdtree for the first time in the session:

```
Error detected while processing User Auto commands for "NERDTreeInit":
E121: Undefined variable: b:NERDTreeRoot
E116: Invalid arguments for function fugitive#detect
```

I tried to isolate the problem, so I disabled all plugins but `nerdtree` and the issue was not there. If I enable the `fugitive` along side with `nerdtree`, then the error comes back.

Any subsequent calls of nerdtree functions don't raise any errors.

### Environment:
- `$ vim -v`: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 02 2017 06:40:50)
- Plugin manager: vim-plug

**Comment by tjdavenport** [comment]
I ran into this too. I applied the following bandaid to `vim-fugitive/plugin/fugitive.vim`

Before...
```
 240 augroup fugitive
 241   autocmd!
 242   autocmd BufNewFile,BufReadPost * call fugitive#detect(expand('%:p'))
 243   autocmd FileType           netrw call fugitive#detect(expand('%:p'))
 244   autocmd User NERDTreeInit,NERDTreeNewRoot call fugitive#detect(b:NERDTreeRoot.path.str())
 245   autocmd VimEnter * if expand('<amatch>')==''|call fugitive#detect(getcwd())|endif
 246   autocmd CmdWinEnter * call fugitive#detect(expand('#:p'))
 247   autocmd BufWinLeave * execute getwinvar(+bufwinnr(+expand('<abuf>')), 'fugitive_leave')
 248 augroup END
```

After
```
 240 augroup fugitive
 241   autocmd!
 242   autocmd BufNewFile,BufReadPost * call fugitive#detect(expand('%:p'))
 243   autocmd FileType           netrw call fugitive#detect(expand('%:p'))
 244   if exists('b:NERDTreeRoot')
 245      autocmd User NERDTreeInit,NERDTreeNewRoot call fugitive#detect(b:NERDTreeRoot.path.str())
 246   endif
 247   autocmd VimEnter * if expand('<amatch>')==''|call fugitive#detect(getcwd())|endif
 248   autocmd CmdWinEnter * call fugitive#detect(expand('#:p'))
 249   autocmd BufWinLeave * execute getwinvar(+bufwinnr(+expand('<abuf>')), 'fugitive_leave')
 250 augroup END
```

I just wrapped the autocmd with an exists() check.

**Comment by chocoelho** [comment]
Actually, this is fixed in #966. Thing is `NERDTreeRoot` was deprecated and recently removed from NERDTree codebase.

**Comment by rainerborene** [comment]
Workaround:
```VimL
au User NERDTreeInit let b:NERDTreeRoot = b:NERDTree.root
```

**Comment by chocoelho** [comment]
FYI, `NERDTreeRoot` was added back to NERDTree, so no need for the workaround. We should move to `NERDTree.root` anyway.
