### ISSUE TITLE
Does fugitive support union merge?

### ISSUE THREAD

**Issue by ganli** [tpope/vim-fugitive#968]
That's is a very common scenario, keep both side changes. Append right below left, or conversely. I read the guide and try, but cannot find the solution.

**Comment by mcepl** [comment]
@ganli How would you do it with plain git on the command line?

**Comment by tpope** [comment]
It provides no special support other than deleting the hunk markers yourself. I'm away of no command line solution, which means I don't think there's much that would make sense to add to Fugitive.
