### ISSUE TITLE
Shortcut to checkout/remove files

### ISSUE THREAD

**Issue by behrendtio** [tpope/vim-fugitive#97]
It would be great to have an shortcut in `Gstatus` to quickly restore the working copy for a certain file.

Using `co` is propably a pretty good shortcut for this. I figured this way:

Anytime you press the desired key combination, the file will be reverted to the current state (HEAD) of the remote repository (if there is one).
- Staged file: Unstage + Checkout
- Unstaged file: Checkout
- Untracked file: Remove from filesystem

I guess a little confirmation message should also be included, especially on removing untracked files.

**Comment by bpj** [comment]
Is `U` going to get documented? I only found this issue because i searched for "untracked" before submitting an issue for a remove untracked feature.

**Comment by tpope** [comment]
#714
