### ISSUE TITLE
fugitive: 'origin' is not a supported remote

### ISSUE THREAD

**Issue by astropanic** [tpope/vim-fugitive#972]
`:Gbrowse` produces: `fugitive: 'origin' is not a supported remote`

~~~
git remote -v
origin	git@gitlab.webdev.wlw.de:webdevs/wlw_sneakers.git (fetch)
origin	git@gitlab.webdev.wlw.de:webdevs/wlw_sneakers.git (push)

git --version
git version 2.13.5 (Apple Git-94)
~~~
latest updated version of vim-fugitive
~~~
silent! let g:plugs['vim-fugitive'].commit = 'd16cd9c'
~~~
NVIM v0.2.0

**Comment by shumphrey** [comment]
fugitive does not support gitlab out of the box.
You need https://github.com/shumphrey/fugitive-gitlab.vim

**Comment by astropanic** [comment]
another plugin? why not just extending the original one?

**Comment by tpope** [comment]
Fugitive doesn't natively support any hosting providers because it sure as heck can't support all of them.
