### ISSUE TITLE
Nicer quickfix title for :Ggrep

### ISSUE THREAD

**Issue by mgedmin** [tpope/vim-fugitive#973]
When I do `:Ggrep foo` followed by `:cw`, I see a quickfix window with the following in the statusline:

    [Quickfix List] :hub --git-dir=/path/to/my/project/.git --no-pager grep -n --no-color foo

It would be nice if would see

    [Quickfix List] :Ggrep foo

instead.

**Comment by mgedmin** [comment]
Currently I'm working around this by adding the following to my `~/.vim/ftplugin/qf.vim`:

    let w:quickfix_title = substitute(w:quickfix_title, '^:hub --git-dir=.* --no-pager grep -n --no-color', ':Ggrep', '')

**Comment by tpope** [comment]
Achieved with the newish `setqflist([], 'a', {'title': '...'})` Vim feature.
