### ISSUE TITLE
Gblame reports 'fugitive: file or blob required" When Repo Path Contains Symlink

### ISSUE THREAD

**Issue by egan** [tpope/vim-fugitive#980]
At some point Gblame stopped working. I've updated vim, git, and my bundles a few times since I last used it, so I don't know what change is to blame.

`:echo fugitive#buffer().path()` on files returns nothing, but `echo fugitive#repo().tree()` returns the correct containing directory.

The repositories in question are configured strangely at all. However, they are contained in a directory whose path contains a symlink, e.g.:

`/home/user/w/repo`

Where `w` is a symlink to `/home/user/a/long/path/`.

`:echo expand('%:p')` returns `/home/user/w/repo/path/to/file`.

But `:echo b:git_dir` returns `/home/user/a/long/path/repo/path/to/file`.

My understanding is that this is what causes failure. But it was working before. And I understand that using symlinks to files within a repository is questionable. But it seems reasonable to expect to be able to access the repository itself through a symlink.

vim: 8.0
git: 2.15.0
fugitive: 5032d9

The other wrinkle is that I am running this under MSYS2 on Windows. I don't know whether this happens on a real Unix system.

**Comment by egan** [comment]
I found the commit that introduced the regression: d5208d4.

**Comment by egan** [comment]
Replacing the call to `resolve()` with one to `simplify()` fixes the problem for me. I have no idea what the side effects are, or how the commit was supposed to work in the first place.

**Comment by tpope** [comment]
Appears to be working on the latest.
