### ISSUE TITLE
Staging performance improvement on large sets

### ISSUE THREAD

**Issue by ain** [tpope/vim-fugitive#981]
__Steps to reproduce__:

1. Create a new Node.js project with a set of bigger dependencies (Angular)
2. Commit `node_modules`
3. Remove `node_modules`
3. Go `:Gstatus`
4. Stage all removals 

__What happens__: Vim lags for >10 min without success, would probably take very long, depending on a machine. What I saw in staging output, was about 21k lines. I simply did it with `git add -A` since the change was only targeted to removal. Also, if just one file of the big bunch is unstaged, it also takes a minute or so.

__What should happen__: performance should be better on large stagings.

**Comment by tpope** [comment]
"Performance should be better" is a universal truth so I won't keep this open as a bug, but feel free to provide specific improvement suggestions or a patch.
