### ISSUE TITLE
Calling cnext after Glog clears the quickfix list

### ISSUE THREAD

**Issue by herrbischoff** [tpope/vim-fugitive#983]
### Environment

```
$ nvim -v
NVIM v0.2.2
```

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.2
BuildVersion:	17C88
```

### Issue 

I'm not sure if this is some unfortunate conflicting setting in my `init.vim` (using Neovim) or a possible issue with Fugitive.

Whenever I run `:Glog` on an opened file, I get the results back fine and the quicklist is populated with the revisions. I can select any entry or simply do `:cnext`. However, as soon as I do, the quicklist is emptied and I cannot proceed. This is contrary to `:Glog -- %` which populates the quicklist with commits that I can then browse forwards (`:cnext`) and backwards (`:cprev`) just fine.

**Comment by tpope** [comment]
That's really strange but yes, probably some sort of conflict with something else, as nothing Fugitive does will clear the quickfix list.
