### ISSUE TITLE
Display output during Gcommit

### ISSUE THREAD

**Issue by brendanator** [tpope/vim-fugitive#985]
I have a pre-commit hook which runs units tests. These take quite a while and vim locks up while running them with no visible output

It would be great if the output could be displayed using `make` or dispatch

**Comment by tpope** [comment]
Not possible with `:make` because of the way we need to intercept the editor invocation, but might be solvable with job support.

**Comment by tpope** [comment]
Filing this under #1433. The branch there solves this.

**Comment by atomdmac** [comment]
Sorry for the necromancy.  Happy to create a separate issue for this question if it would be helpful.

This doesn't seem to work for me.  I have `vim-dispatch` installed but doing after staging my files with `:G`, pressing `cc`, and saving my commit message, I'm unable to use `neovim` while the pre-commit script runs (with the output being displayed at the bottom).  My understanding is that having `vim-dispatch` installed should allow the output to display in a temporary buffer instead (a la `:G log`, etc.)

If I attempt to run `G! commit` instead, I get this message:

```
fugitive: aborting edit due to background operation.
error: There was a problem with the editor 'sh /var/folders/8k/74p75qrn5gx5yw8bh01j785r0000gn/T/nvimXaiYGU/5.sh'.
Please supply the message using either -m or -F option.
```

I assume I'm just doing something wrong but I'm not sure what that is.

**Comment by tpope** [comment]
You're not doing anything wrong. There's no mechanism to commit in the background _and_ interactively edit the commit message in the foreground.
