### ISSUE TITLE
Confused about Glog command

### ISSUE THREAD

**Issue by ldelossa** [tpope/vim-fugitive#987]
Hello there,

I'm currently a buffer user of vim. New files wind up in a buffer of their own. Windows are created on split and are closed with the ':q' command. Buffers are closed with 'bd'. When I run "Glog" I get throw into a brief shell explaining what fugitive is doing. For example:

```
~/git/go/src/github.com/ldelossa/userd master ⇡ 33s
❯ vim

fugitive:///Users/louis/git/go/src/github.com/ldelossa/userd/.git//238b75edd95b04c15c5646a202875f6306f3b8d9/user.go::Add comments for User constructor
fugitive:///Users/louis/git/go/src/github.com/ldelossa/userd/.git//6b3e73e9b21aa6f2ebbdb58a75de57dd73ea1d7c/user.go::Introduce user constructor which sets User UUID on call. Update server to use constructor.
fugitive:///Users/louis/git/go/src/github.com/ldelossa/userd/.git//7f1b99f06104428f8a15209d5e94259457d83ee1/user.go::Initial commit
Press ENTER or type command to continue
```

This is fine, however when I hit ENTER the first revision is loaded into a new buffer when VIM regains control. My understanding is each revision should show up in a quickfix menu, and I should be able to move from revision to revision by iterating through the quick fix menu. This does not happen for me. Instead I get:

```
(1 of 3): Add comments for User constructor
Press ENTER or type command to continue
```

And hit enter - Then this revision is loaded into a buffer - but I can do nothing else but close the buffer and the command seems to end. 

<img width="1680" alt="screen shot 2018-01-07 at 4 57 04 pm" src="https://user-images.githubusercontent.com/5642902/34654576-df162a46-f3cb-11e7-8f9a-9e403dad5a62.png">

I will attach a link to my .vimrc

https://hastebin.com/cohazisuhu.xml

**Comment by tpope** [comment]
It uses Vim's quickfix list which has exhaustive documentation available at `:help quickfix`. Start with `:copen` to get a list you can interact with.
