### ISSUE TITLE
:Gedit on a renamed file at a previous commit opens a new buffer at the file's old location

### ISSUE THREAD

**Issue by jeffvandyke** [tpope/vim-fugitive#988]
Great plugin (of course)! One thing I'm wondering and can't find a solution for: Say I do `:Gblame` on a file that was renamed or moved at some point (even just renamed), and through <kbd>-</kbd> or <kbd>P</kbd> manage to open the file at a commit before it was renamed/moved (in the same window as I was editing the working directory file, as Gblame works), then I type `:Gedit` in that buffer, I would expect, if possible, the editor to open the file that I was editing, in its file path at the working directory version, but instead, it tries to open the file with the name/path as it was at the revision I was looking at, which is, of course, a new file according to vim.

I see how it could be expected behavior not to follow renames forward to the working directory filepath when using `:Gedit`, but is there any way that I could configure it to? Or perhaps this is a possible improvement to Gedit's behavior

Thanks again for this amazing tool!

**Comment by tpope** [comment]
That behavior does not sound unreasonable but how would you implement it? I don't know of any command to tell me the work tree filename for a pre-rename file.

**Comment by jeffvandyke** [comment]
I'm not sure right now, maybe some more expensive incantation if the current file path doesn't exist involving git log --follow, but I will look into it to see if I can find something soon.

**Comment by jeffvandyke** [comment]
Just for personal research notes, this seems interesting:

git log --name-status f7a38027:old-file-path.cpp f7a38027..HEAD

Could be parsed to follow old-file-path.cpp through its paths, but there could be an even better solution

**Comment by jeffvandyke** [comment]
Ok, given the way git saves things now, I think this is conceptually the best that can be done:
```
git log --reverse --format="%H" --name-status --diff-filter=R <old-browsing-sha>..
```
... then all vim-fugitive has to do is search for the current file name open from the top in column 2 (columns separated by tabs), then when it finds it, change the filename its looking for to what's in column 3, then jump forward to the next commit `[0-9a-f]\{40\}`, then repeat until we reach the end of file.

That filename will be what you want to open in the current working directory.

As for performance, in a repo with >30k commits, this takes about 2 seconds, and for a recent commit (but still before a huge folder move), it takes 0.260 seconds, so the further back you go, the longer it takes, and doesn't take very long for commits closer to HEAD.

There could be a future improvement in remembering rename events, in vim-fugitive, or even in git, to make this go much faster.

Definitely be best to make this behavior optional, since it is a bit of the expensive operation.

Oh! You would only need to do this if the current buffer file name didn't exist, so the common case would be completely unaffected.

**Comment by tpope** [comment]
Is that 2 seconds just to run the `git log` command, or does that also include the Vim parsing? I'm afraid it might go up by an order of magnitude, given how slow VimL is.

Regardless, since it doesn't affect the performance of the base case, I'd consider supporting it, though actually implementing it may be easier said than done. [Here's where the file name to jump to is determined](https://github.com/tpope/vim-fugitive/blob/5032d9ee72361dc3cfaae1a9b3353211203e443f/plugin/fugitive.vim#L1456), if you want to take a whack at it.

**Comment by jeffvandyke** [comment]
Sounds good! I haven't done any plugin programming with VimL yet, but I'll most likely give it a stab sometime this week.

**Comment by jeffvandyke** [comment]
Ok, maybe next week, got busy with other projects this week.

**Comment by tpope** [comment]
When I said "doesn't affect the performance of the base case", I was thinking that we would only run the command if the file had been renamed, but of course, we don't know if it's been renamed until after we run the command. I'm not going to make `:Gedit`'s behavior dependent on a hidden variable, so this is dead in the water.

But do see the discussion in #693, which is about the exact same problem, but proposes a `:Gblame` specific solution.
