### ISSUE TITLE
E492: Not an editor command: Gwrite -- FollowSymlink Issue

### ISSUE THREAD

**Issue by John-Appleseed** [tpope/vim-fugitive#989]
Using the FollowSymlink autocmd causes `autocmd fugitive` to not load the buffer commands and `b:git_dir`
```vim
" Follow symlink to open actual file
autocmd BufReadPost * call FollowSymlink(expand('<afile>'))
```

Symlink Issue 1

1. start vim
2. open symlink file
3. :Gwrite
`E492: Not an editor command: Gwrite`

Nonsymlink Success
1. start vim
2. open non-symlink file
3. :Gwrite
`:Works!`

Symlink Issue 2

Opening a nonsymlink file will load the `:Gwrite` function, which will then work on the symlink file. However the `b:git_dir` isn't loaded so `:Gwrite` throws an error

```
Error detected while processing function <SNR>115_Write[5]..<SNR>115_buffer[6]..<SNR>115_throw:
line    2:
E605: Exception not caught: fugitive: not a git repository: /Volumes/Work/.do/Dotfiles/vimrc
Error detected while processing function <SNR>115_Write:
line    5:
E171: Missing :endif
```

Workaround is to reload the file after FollowSymlink was executed.

```vim
:e
:Gwrite
```

**Comment by John-Appleseed** [comment]
Related Issue https://github.com/tpope/vim-fugitive/pull/652 

New buffers not activating fugitive autocmds

**Comment by tpope** [comment]
This isn't actionable without knowing what `FollowSymlink` is/does, but generally speaking, there's nothing Fugitive can do if another plugin is renaming the buffer without kicking off the correct `BufReadPost` event.
