### ISSUE TITLE
Gsdiff :1 opens vertical diff when diffopt contains vertical

### ISSUE THREAD

**Issue by HarmtH** [tpope/vim-fugitive#990]
When ```diffopt``` contains ```vertical```, running ```Gsdiff``` with an argument (without argument works fine), the diff opens in a vertical split instead of a horizontal one.

**Comment by tandrewnichols** [comment]
Not for me. Even without an argument `:Gsdiff` opens vertically.

**Comment by tpope** [comment]
Can confirm. I think the solution would be to temporarily remove `vertical` from `diffopt` before splitting.
