### ISSUE TITLE
Gwrite! not documented

### ISSUE THREAD

**Issue by minusf** [tpope/vim-fugitive#995]
according to http://vimcasts.org/episodes/fugitive-vim-resolving-merge-conflicts-with-vimdiff/ `Gwrite!` is useful when solving merge conflicts. This seems to be an udocumented command...

**Comment by rajaravivarma-r** [comment]
Are you talking about `Gwrite` command without the `!`, then it is here. https://github.com/tpope/vim-fugitive/blob/a5a75aca924a1f3a424709aadfa96ab56e300fa4Are /doc/fugitive.txt#L158

**Comment by tpope** [comment]
An extra sentence would probably be ideal, but the command does tell you when the `!` is needed, which seems adequate.
