### ISSUE TITLE
Gdiff no split / single window diffing

### ISSUE THREAD

**Issue by plexigras** [tpope/vim-fugitive#996]
I like Gdiff but i don't need to see the index file and its especially bothersome since i like to use small terminal windows.

**Comment by tpope** [comment]
I don't understand what you're proposing as an alternative. I've never heard of "single window diffing".

**Comment by plexigras** [comment]
you can diff two buffers, there is no need to have them both opeed in a window.

i will try to hack together an example

**Comment by plexigras** [comment]
this kinda works but its quite buggy.

and here is the example :smile: 

`touch a.txt b.txt && vimdiff a.txt b.txt -c ':only'`

**Comment by plexigras** [comment]
I just came back to this and it turns out what you can do is run `:diffthis` in a buffer and then run it again in another buffer resulting in you diffing both buffers without having them open in their own windows.

But i can't figure out a way to have the index open in a buffer but not in a window i am still unable to do this.

maybe if there where a way to not have the index open in a window but still have the buffer i could get this to work.

**Comment by tpope** [comment]
Might related to `bufhidden=delete` in the index buffer.

**Comment by plexigras** [comment]
> Might related to bufhidden=delete in the index buffer.

can that be disabled?

**Comment by tpope** [comment]
With the right autocommand I'm sure it could be.

**Comment by tpope** [comment]
The right autocommand is:

```vim
autocmd BufReadPost fugitive://*//[0-3]/* set bufhidden= 
```

This feature idea is pretty esoteric. I don't see providing a built-in for it unless more people request it.
