### ISSUE TITLE
(Ubuntu -> vim-plug ->) vim-fugitive not working

### ISSUE THREAD

**Issue by mathieucaroff** [tpope/vim-fugitive#997]
I'm on Ubuntu (17.10, artful, 4.13.0-36-generic), with `git version 2.14.1`.
I tried installing vim-fugitive through vim-plug.
`:PlugInstall` indicates `- vim-fugitive: Already installed`, and `:PlugStatus` indicates `- vim-fugitive: OK`, but when I open a tracked file, the commands are unavailable (E492: Not an editor command).

In comparison, the `vim-fugitive` package from Ubuntu repositories works well. The vim-fugitive package version is `2.2-2`. I tried with vim.basic, vim.athena and vim.gtk3, with each time the same result.

**Comment by x4m3** [comment]
can you show your vimrc? maybe the issue is there

**Comment by mathieucaroff** [comment]
I'm now on Ubuntu MATE, 18.04. I cannot reproduce the error on my laptop.

**Comment by mathieucaroff** [comment]
I'm now on Ubuntu-MATE 18.04. I cannot reproduce the issue.
